### ISSUE TITLE
Registration grid can't handle empty backend

### ISSUE THREAD

**Issue by atz** [sul-dlss/argo#10]
On http://localhost:3000/items/register, five 500 errors spawned on attempting to build dropdowns:

* GET http://localhost:3000/registration/workflow_list?apo_id= 
* GET http://localhost:3000/registration/collection_list?apo_id= 
* GET http://localhost:3000/registration/rights_list?apo_id= 
* GET http://localhost:3000/registration/workflow_list?apo_id= 
* GET http://localhost:3000/registration/collection_list?apo_id= 
* GET http://localhost:3000/registration/rights_list?apo_id= 

All because the #apo_id is empty.  Need to detect emtpy case and not get weird.  Probably display a link to create an APO object.

**Comment by drh-stanford** [comment]
fixed in #320
