### ISSUE TITLE
"Edit Collection" collection title drawn from wrong source data

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1006]
Reported by a user, noticed when using the "edit collection" functionality, the collection title seems to be drawing from the Fedora label rather than descMetadata or the other defaults (identityMD or DC).

See below:

Object to be modified:
![screenshot 2017-08-15 08 56 26](https://user-images.githubusercontent.com/796990/29324201-23527b2a-8198-11e7-9eba-e183c6807bcb.png)

Incorrect collection title in modal:
![screenshot 2017-08-15 08 56 36](https://user-images.githubusercontent.com/796990/29324214-2e64e066-8198-11e7-81be-40e0d2e401c1.png)

Collection item view showing correct title (also verified in identityMD and DC):
![screenshot 2017-08-15 08 56 03](https://user-images.githubusercontent.com/796990/29324227-3d3f1390-8198-11e7-9ac6-8d753952da71.png)

View of Fedora label:
![screenshot 2017-08-15 08 56 12](https://user-images.githubusercontent.com/796990/29324247-4a5e93ca-8198-11e7-8554-bb9e38bc3c20.png)

(see for instance, any object associated with the collection druid:jt898xc8096 - https://argo.stanford.edu/catalog?page=1&per_page=100&q=Chinese+Non-Profit+Organizations&utf8=%E2%9C%93 ).

**Comment by blalbrit** [comment]
@arcadiafalcone also reports (possibly related to above): 

> -Changing the collection name in the collection record should update how it displays in the Edit Collections dialog (the updated collection does appear on the item show page)

**Comment by peetucket** [comment]
@blalbrit do you know if it safe to assume that all objects (including collections) will have a dublin core title element?   because i presume some collections may not have descMetadata

**Comment by blalbrit** [comment]
@peetucket - the small handful of objects that are causing problems in Goobi (by trying to draw on a non-existent Fedora label) will also be a problem here. The decision tree should be:

- MODS title
- identityMetadata label
- DC title
- Fedora label

Collection items should *always* have a MODS title, the other datastreams are there as backup in case something goes awry with creation of the descMetadata datastream.

**Comment by peetucket** [comment]
@blalbrit in the PR review, @jcoyne suggested that if collection items should _always_ have a MODs title, we should just look there and then throw a honeybadger exception if none is found (instead of continuing to look in other places).  This exception could be used to indicate which objects may need remediation.  Thoughts?

**Comment by blalbrit** [comment]
@peetucket - I like that approach for collection objects (items can sneak through, but collections should always have a MODS title to draw from). Also really like the idea of throwing an exception if none can be found. +1 from me.

**Comment by peetucket** [comment]
@blalbrit: Great.  One more question -- instead of just throwing an exception, how about notifying honeybadger and then returning the fedora object label (as it does now)?  This would at least allow the user to continue in the UI instead of bombing out.
