### ISSUE TITLE
improve error reporting for `.htaccess` refreshing rake task

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#1012]
currently, the rake task that re-generates `.htaccess` every 5 minutes is scheduled by a cron job (via the whenever gem).  

because:
* generating `.htaccess` requires querying solr
* the cron daemon sends emails any time it runs something that errors out
* the rake task errors out if it can't connect to solr to query it

many developers are spammed every five minutes by every argo VM if solr becomes unreachable (which tends to happen every few weeks to every few months, presumably due to network hiccups).  while not the end of the world, this can be a moderate annoyance, and it trains us to pay less attention to our alerts (while we do want the `.htaccess` file to be refreshed very regularly if possible, it's not worth 12 emails from each VM to a long list of developers just because solr was unreachable for an hour on a random sunday morning).

here's an idea for cutting down on that noise, while still reliably reporting the errors when they start occurring:
* modify the rake task so that it doesn't allow exceptions to bubble up and cause the invocation to exit with a status code other than zero, so that the cron daemon never sees the rake task as erroring out.  maybe we just trap solr connection exceptions, maybe we trap all exceptions.
* for any trapped exception, send the error to honeybadger.  this will cause an initial email alert to be sent to interested parties (and a follow up alert if the error volume is high enough in a short time?).  but it'll prevent an alert from being sent for every connection failure (because honeybadger is smarter than the cron daemon about keeping noise down).
* have okcomputer check that the `.htaccess` file has been refreshed no more than an hour ago (or some configurable threshold).  this will add an extra bit of protection, since nagios' okcomputer check will alert if the `.htaccess` file becomes too stale (but the nagios alert can be acknowledged, again allowing for less noise than the cron daemon's error reporting).

i ran this idea by @LynnMcRae and @tallenaz last week, and both thought it sounded reasonable.  it shouldn't be too hard to implement, and as a bonus, we might be able to apply this same pattern to other applications that have cron jobs prone to transient errors.

**Comment by jcoyne** [comment]
.htaccess is gone since switching to shibboleth.
