### ISSUE TITLE
originInfo portion of item view page pulled from wrong metadata

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1014]
In the title block of the item view page (https://argo.stanford.edu/view/druid:mv824ck4135 , for example), the originInfo block which contains the publication info, seems to be drawn from the wrong metadata block.

For instance:
<img width="1035" alt="screenshot 2017-09-29 15 26 58" src="https://user-images.githubusercontent.com/796990/31038321-fa73ec3c-a52a-11e7-9426-299abb75617a.png">

displays originInfo: [Jackson, Ms.]Test : [U.S. Department of the Interior], [2010?]

In the metadata, however, the originInfo for the object is:
`<originInfo displayLabel="publisher">
    <place>
      <placeTerm>Jackson, Mississippi :</placeTerm>
    </place>
    <publisher>U.S. Department of the Interior, Bureau of Land Management, Eastern States Jackson Field Office,</publisher>
    <dateIssued>[2010?]</dateIssued>
  </originInfo>`

while the originInfo that is being displayed seems to be drawn from relatedItem metadata block of descMD:

`<originInfo>
      <publisher>[Jackson, Ms.] : [U.S. Department of the Interior], [2010?]</publisher>
    </originInfo>`

I can't tell if this is an indexing problem with how originInfo is added into the solr doc, or an issue with how the display is built from the descMD datastream.

**Comment by hannahfrost** [comment]
Would be interesting to know the extent of impact (number of objects; is this a one-off or rare?)

**Comment by andrewjbtw** [comment]
I think this got fixed when solr indexing was shifted to use the Cocina metadata rather than the MODS.
