### ISSUE TITLE
Add reading-order specification to Set Content Type blue button

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1019]
Currently you can change to a book-like object, but have no way of specifying reading order, so the object defaults to ltr and requires manual correction if it is rtl.

Goal would be to specify reading direction. Preferable place would be in Set Content Type action at individual object and in bulk. But - totally open to other implementation options, this seems like the most logical from a user point of view.

* NOTE * We do not currently believe reading direction is set correctly in contentMetadata during accessioning right now. This would be set based on the tag of `Process : Content Type : Book (ltr)` in `identityMetadata` when the object is registered.

see https://github.com/sul-dlss/assembly-objectfile/issues/16 and https://github.com/sul-dlss/assembly/issues/113

**Comment by peetucket** [comment]
Can you remind me how the order is manifested in Fedora?  Is it a valid content type in content metadata?  I see two options in the content type in the reg form ("book (ltr)" and "book (rtl)") but I don't see any objects in prod which with those content types (they are all just "book").

**Comment by peetucket** [comment]
Oh, looks like maybe its specified in a sub-element under the contentMetadata (according to https://consul.stanford.edu/display/chimera/DOR+content+types,+resource+types+and+interpretive+metadata): 


```
<bookData>

    readingOrder=ltr | rtl -- coded values for left-to-right vs right-to-left
    pageStart=left | right -- an indication of the position of thee first page image, optional. It is used in cases where the first image should not occupy the first (right or left) side of the first 2-page layout.
e.g.
<contentMetadata type="book" ...>   <bookData readingOrder="rtl" pageStart="right"/>
```

**Comment by peetucket** [comment]
Postponing for now after discussion with @blalbrit due to low usage.  Also discussed first implementing reading direction being respected correctly at accessioning time (which we don't believe it is now either).  

see https://github.com/sul-dlss/assembly-objectfile/issues/16 for the first work needed there

**Comment by andrewjbtw** [comment]
New item page content type menu includes reading order.
