### ISSUE TITLE
"Purge" action should also clean up workflow table

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1020]
Currently, "purge" removes a registered (not accessioned) object from DOR. However, it leaves the register workflow for that object in the Oracle workflow table.

Expected behavior for "purge" would be to also clean up the workflow table while removing the object from DOR

**Comment by blalbrit** [comment]
@LynnMcRae - do you have a preference for archiving that register workflow, or removing it altogether?

**Comment by LynnMcRae** [comment]
Anything in the active workflow table could/should go, which in principle would be the registration WF for almost all cases of Purge, given its availability. Archived workflows wouldn't likely matter one way or the other should it come up. It would just be past data of very marginal interest.

**Comment by blalbrit** [comment]
Decommission uses: `Dor::WorkflowService.archive_active_workflow 'dor', 'druid:ng000nd5495'`

**Comment by aaron-collier** [comment]
Tracking: https://jirasul.stanford.edu/jira/browse/DEVQUEUE-231

**Comment by aaron-collier** [comment]
@jcoyne would it help to open a new/related ticket for that specifically?

**Comment by mjgiarlo** [comment]
Blocked by requiring a team discussion, planned for Tuesday, 12/11/2018.

**Comment by peetucket** [comment]
What's the endpoint needed?  Not only is there an archive workflow option as Ben noted above, there appears to be a delete workflow option: https://github.com/sul-dlss/dor-workflow-service/blob/master/lib/dor/services/workflow_service.rb#L171-L174

**Comment by mjgiarlo** [comment]
From https://github.com/sul-dlss/workflow-archiver/issues/23 (now closed as dup):

> Summary: In its current state, the workflow-archiver cron job runs regularly and sweeps closed workflows from the workflow table to the workflow-archive table. However, the "purge" functionality in Argo (https://github.com/sul-dlss/argo/blob/f60a721af7a5007edf1c97ac359cbce39235caf0/app/controllers/items_controller.rb#L523) doesn't clean up the workflow rows for purged items - leaving ghost rows which then error repeatedly when the workflow-archiver runs.
> 
> This eventually leads to the archiver not being able to clear a backlog, and we wind up with more and more items which, for the user, become uneditable for longer than we would like, from a service perspective.
> 
> Currently, I think manually clear this list of ghost rows, but it really shouldn't require human intervention. Adding a ticket to the Argo GH project as well, and proposing to @vivnwong for a maintenance fix.

**Comment by blalbrit** [comment]
Thanks for consolidating @mjgiarlo - and just to clarify, the concern is removing the rows from the active workflow table by either archiving them (that is, moving them to the workflow_archive table) or deleting them entirely from the active workflow table.

I think - based on experience and @LynnMcRae 's comments above - that either approach is acceptable.

**Comment by mjgiarlo** [comment]
@peetucket Good question. For @blalbrit: when an object is purged in argo, which workflows should be deleted?

* Active?
* Archived?
* All?

The method @peetucket referenced deletes a single named workflow for a specified druid. There is also a method in the workflow service that will delete all archived workflows (not yet implemented in the ruby client).

**Comment by blalbrit** [comment]
@mjgiarlo - comments might have overlapped there. Goal is to delete all rows for a given druid from the *active* workflow table. Already archived workflows are not problematic.

**Comment by mjgiarlo** [comment]
Ha, I believe @blalbrit answered my question while I was typing it up. It sounds like when an object is purged, we could/should 1) archive all its active workflows; 2) then delete all its archived workflows.

**Comment by blalbrit** [comment]
@mjgiarlo - just 1) above would suffice.

**Comment by mjgiarlo** [comment]
@blalbrit OK. Thanks!

**Comment by mjgiarlo** [comment]
@blalbrit OK, having read your responses and all the comments above, it seems like we can either archive all active (DOR and SDR) workflows or we can delete all of them. 

Which is more appropriate for a purge?

**Comment by mjgiarlo** [comment]
> Now I will be disappointed if the PR is more than 1 line.

I mean, I do have to write some tests.

**Comment by mjgiarlo** [comment]
> @blalbrit OK, having read your responses and all the comments above, it seems like we can either archive all active (DOR and SDR) workflows or we can delete all of them.
> 
> Which is more appropriate for a purge?
> 
> (My last question for you today, I promise. Btw, I see @LynnMcRae's reply above but I don't fully grok it.)

Spoke with Ben on Slack. Going to archive them.

**Comment by LynnMcRae** [comment]
Hi guys ... there is a potential issue with archiving them. If the archive method works properly, it will only archive completed workflows, that is, where all rows are either completed or skipped. And it will balk if the object is already purged because it needs to ask the object for which version a workflow is being archived, a meaningless question in this context. I think we should just delete them from the active table.

**Comment by blalbrit** [comment]
@LynnMcRae - ah, so it will only archive if it has confirmed rows completed? If so, agrred. @mjgiarlo - we'll want to delete from the active workflow table in that case. Sorry for the confusion.

**Comment by blalbrit** [comment]
Just to pick this up again - @LynnMcRae I stopped counting at > 10000 rows of objects with a status other than "completed" in the archive table. These seem to go back to at least 2012/2013 and come from across multiple workflows (dpgImageWF, hydrus, goobi, eems, versioning, etd, gis, etc.).

I agree with the "delete" approach in active workflow table above, nonetheless, but I'm now less confident that the archiver is working as expected.

**Comment by LynnMcRae** [comment]
There's a smattering of outliers which we could clean up, and then there's GoogleScannedBooks, moved to the newly created archive table post project, likely en masse:

All statuses
     inprogress | 10
     queued | 3
     skipped | 7248844
     hold | 1
     completed | 116879116
     error | 4
     waiting | 163925

waiting (I cleaned up a single rogue gis workflow contributing 15 steps)
     googleScannedBookWF | sdr-ingest-archive | waiting | 163429
     releaseWF | update-marc | waiting | 215
     releaseWF | release-members | waiting | 50
     releaseWF | release-publish | waiting | 213

I suspect the archive code itself is blind, relying on the archiver query to only deliver completed workflows for archiving.

**Comment by mjgiarlo** [comment]
@blalbrit @LynnMcRae This is now in `master`.

**Comment by blalbrit** [comment]
Fantastic @mjgiarlo - not tonight, of course, but maybe we could deploy tomorrow?

**Comment by mjgiarlo** [comment]
@blalbrit You bet. I'll make it happen first thing in the morning.
