### ISSUE TITLE
Collection "More" Modal Fails to Populate in Profile View

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1021]
User-reported error occurs in the following situation:
1) User navigates to a result set by faceting on a specific APO (https://argo.stanford.edu/profile?_=1509670214239&f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=Web+Archive+Crawl+Object+Public+APO for example)
2) User chooses "Profile View" as the view modality:
<img width="1159" alt="screenshot 2017-11-02 19 42 48" src="https://user-images.githubusercontent.com/796990/32358791-19b806aa-c006-11e7-927c-8feb967e21b6.png">
3) User opens the collection facet and clicks on the "more" link to open the collection modal:
<img width="366" alt="screenshot 2017-11-02 19 44 05" src="https://user-images.githubusercontent.com/796990/32358818-4494d6f0-c006-11e7-9339-bd14c410a030.png">
4) The modal opens, but fails to populate with any collections:
<img width="1139" alt="screenshot 2017-11-02 19 44 22" src="https://user-images.githubusercontent.com/796990/32358827-52f1e6de-c006-11e7-9821-ae94a928492e.png">

DESIRED BEHAVIOR: collection modal would populate and allow the user to drill down into a subset of the information while still in the Profile View (as currently functions with the other facets that don't have modal behavior - like rights, object type, content type, etc.)

**Comment by justinlittman** [comment]
So I think the problem is `add_profile_queries()` in `profile_queries.rb`. The profile fields are getting joined together in a single `facet.field` instead of multiple instances of `facet.field` parameters.

**Comment by justinlittman** [comment]
More specifically, `solr_parameters['facet.field']` is a string instead of an array. (I can't quite figure out where it originally gets set to a string.)
