### ISSUE TITLE
Weird UI bug for open/close version modal

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1035]
![screenshot 2018-02-12 17 51 03](https://user-images.githubusercontent.com/796990/36129715-68cec320-101d-11e8-8979-6ee992366fe9.png)

Within the last week, the open/close version modal has gotten out of whack. Note that the modal now includes a search bar and full html for Argo (rather than being limited to the open/close information. In addition, the Type and Version description boxes are now larger than the modal itself.

Not sure how this happened - but @cbeer it seems to have begun about the time of last week's Argo redeploy.

**Comment by jcoyne** [comment]
We only recently added deploy tracking to honeybadger, so I'm guessing that this is the entirety of the changeset that was deployed:

https://github.com/sul-dlss/argo/compare/ffff8e2d9f3259626530dca247b9aa78f7ddbbbe...master

I'm not seeing anything there that should affect this.

When I look at the HTML I see:
<img width="650" alt="screen shot 2018-02-13 at 10 01 32 am" src="https://user-images.githubusercontent.com/92044/36156414-f4a5e3c4-10a4-11e8-9814-93925a4b0c6f.png">

This has `.container` nested within a `.row`, which I'm pretty sure is not allowed by bootstrap.  As this is part of an XHR request, it may be that we're rendering a layout that we didn't intend.  So, I'm wondering if it's this? https://github.com/sul-dlss/argo/commit/90931937aecfb70ab005e9446c473bab373c4cf7 @cbeer what do you think?

https://getbootstrap.com/docs/3.3/css/#overview-container

**Comment by jcoyne** [comment]
No, https://github.com/sul-dlss/argo/commit/90931937aecfb70ab005e9446c473bab373c4cf7  was definitely not the problem.

**Comment by mejackreed** [comment]
Pretty sure all of the *.js.erb files need to be migrated to the new way Blacklight does this.
