### ISSUE TITLE
Browser tab label issue 

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#1038]
The browser tab labels seem to have changed to expose underlying code:

![screen shot 2018-02-16 at 2 03 31 pm](https://user-images.githubusercontent.com/1824732/36336332-a443ba84-133b-11e8-8975-b412fd033f97.png)

**Comment by jcoyne** [comment]
I believe this is still a valid issue.

**Comment by aaron-collier** [comment]
@jcoyne do you have an example? I'm not seeing this happening.

**Comment by andrewjbtw** [comment]
Looks like it's been fixed:

<img width="536" alt="Screen Shot 2022-05-11 at 4 19 10 PM" src="https://user-images.githubusercontent.com/8975583/167962809-62e386d4-157c-4f6f-a727-5c712ba53b1b.png">
