### ISSUE TITLE
Resizeable javascript makes modals look odd

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1040]
It gives weird edges and they don't seem to work anyway.

<img width="947" alt="screen shot 2018-02-16 at 10 54 18 pm" src="https://user-images.githubusercontent.com/92044/36338129-8e68fe32-136c-11e8-9955-6fb525b3e470.png">
<img width="540" alt="screen shot 2018-02-16 at 10 54 03 pm" src="https://user-images.githubusercontent.com/92044/36338130-8e7fede0-136c-11e8-9b87-15a121a745a9.png">

**Comment by blalbrit** [comment]
This is low priority in terms of a fix. Will tag as backlog.
