### ISSUE TITLE
Allow for bulk updating rights to include AND/OR read access declarations

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/argo#1045]
Currently, bulk rights updates can't be combined, i.e. you either get world access or Stanford access, not both. There's at least one collection (ARS0021 - Stanford Recital Collection) that would like the following type of access block (from: https://consul.stanford.edu/display/chimera/Rights+metadata+--+the+rightsMetadata+datastream):

```
<access type="read">
  <machine>
     <group>stanford</group>       <-- The stanford community has unrestricted access
  </machine>
  <machine>
     <world rule="no-download"/>     <-- while the rest of the world can view but not download
  </machine>
</access> 
```

Because of the size of ARS0021, adding this block in manually to each object would be tough. The ability to bulk update hundreds of objects would be most welcome.

**Comment by andrewjbtw** [comment]
The multi-select Cocina rights menu can cover this case now. Select:

- view: world
- download: stanford
