### ISSUE TITLE
Add "Access Rights" information to Report View

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1055]
Per user request:

"When troubleshooting why a set of objects is not displaying as expected, access restriction information would be very useful to have available as a column in the report view for download. This would facilitate pinning down the source of an issue more easily."

As an Argo user, I can confirm that including an "Access Rights" column to the report view, that includes the same information as the "Access Rights" facet, would be extremely helpful in reporting out to stakeholders.

**Comment by andrewjbtw** [comment]
Closing in favor of #4077
