### ISSUE TITLE
Mock Workflow Service behaves unexpectedly on Shibboleth branch

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1091]
Something about the shibboleth code (see https://github.com/sul-dlss/argo/pull/1061) is interacting with the capybara-discoball mock WFS in an unexpected way.  On Ruby 2.3.1, the tests won't complete on travis, because enough WFS calls timeout to cause the Travis build to timeout overall.  On Ruby 2.3.4, one test fails with a 500 from the mock WFS as follows:

```
  1) Workflow Service Creation redirect and display on show page
     Failure/Error: @object.create_workflow(wf_name)
     Dor::WorkflowException:
       Failed to retrieve resource: put http://127.0.0.1:38253//dor/objects/druid:qq613vj0238/workflows/accessionWF (HTTP status 500)
     # ./app/controllers/items_controller.rb:669:in `add_workflow'
     # ./lib/test_shibboleth_headers.rb:14:in `call'
     # ./spec/features/workflow_service_creation_spec.rb:10:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Faraday::ClientError:
     #   the server responded with status 500
     #   ./app/controllers/items_controller.rb:669:in `add_workflow'
```

The mock WFS was implemented to help disentangle Argo from depending on a live Workflow Service when running automated tests.

https://travis-ci.org/sul-dlss/argo/builds/374946823?utm_source=github_status&utm_medium=notification

@jcoyne and @jmartin-sul were hoping that @mejackreed might be able to lend a hand in debugging, since he's likely more familiar with capybara-discoball and Argo's use of it, as the original implementer of the mock WFS during the Argo 2 to 3 upgrade (IIRC).

**Comment by jmartin-sul** [comment]
this was solved by @jcoyne breaking out the mock WFS into a docker container, instead of mounting it from within argo.
