### ISSUE TITLE
APO registration can't handle empty backend, Uber-APO not configurable

### ISSUE THREAD

**Issue by atz** [sul-dlss/argo#11]
Attempt to register the first APO on an empty system.  500 error from attempting to lookup some random ID.  

**ActiveFedora::ObjectNotFoundError in ApoController#register**
Unable to find 'druid:hv992ry2431' in fedora. See logger for details.

app/controllers/apo_controller.rb:25:in `register'

Request
Parameters:

``` ruby
{"utf8"=>"✓",
 "authenticity_token"=>"tgcwFvvRpNbQ7gCeACZLjwprUEbAXK4kljZg6eWq9oU=",
 "title"=>"Devs First APO",
 "desc_md"=>"MODS",
 "metadata_source"=>"DOR",
 "managers"=>"sdr:developer  sdr:service-manager  sdr:metadata-staff",
 "viewers"=>"",
 "collection_radio"=>"none",
 "collection"=>"",
 "collection_title"=>"",
 "collection_abstract"=>"",
 "collection_rights"=>"World",
 "collection_catkey"=>"",
 "collection_rights_catkey"=>"World",
 "default_object_rights"=>"World",
 "use"=>"Property rights reside with the repository. Literary rights reside with the creators of the documents or their heirs. To obtain permission to publish or reproduce,
 please contact somebody or other.",
 "copyright"=>"Copyright © Stanford University. All Rights Reserved.",
 "cc_license"=>"by-nc",
 "register"=>""}
```

Obviously there is nothing to retrieve yet, so that fails.  The question is... why would it even be looking?!  Would you believe that the druid is hardcoded in two different places?
- app/assets/javascripts/registration/register.js
- app/controllers/apo_controller.rb

Hey, if it's that important, maybe include it in some seed data with the repo, you know?  Otherwise we have a completely useless repo.  Can't add items because no APO.  Can't add APO because no **very special druid**.  Can't add **very special druid** because not included in repo.  Game over.

**Comment by atz** [comment]
It is configurable in Hydrus, btw.

**Comment by jmartin-sul** [comment]
:+1: to making the uber APO druid configurable

**Comment by LynnMcRae** [comment]
druid:hv992ry2431 is indeed the ur-APO, the one that needs to be bootstrapped for a DOR instance since all object registered through services need to designate a governing APO (it governs all APOs including itself and the master Hydrus APO, agreements, and workflow objects).  Configuring the object PID is a no-brainer. I had understood from long ago it existed as a fixture or equivalent, though maybe that was something Willy held elsewhere?

**Comment by aaron-collier** [comment]
This looks like it was closed in https://github.com/sul-dlss/argo/commit/8649a0f6cedca494b128f545420158ccc122e3e8#diff-1ebb208965b93b81a44d3ffe22a82a77. .. and at this point the `register` method no longer exists.
