### ISSUE TITLE
remove defunct workflows from workflow_grid view

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#1102]
I looked into possibly removing these defunct workflows from the argo workflow_grid, but that would really mean changing the indexing of the objects to skip these workflows  or making a pretty ugly Solr query or winnowing out search results. …. ugh.  (See https://github.com/sul-dlss/argo/blob/master/app/helpers/workflow_helper.rb#L6-#L12:

![pastedgraphic-1](https://user-images.githubusercontent.com/96775/39834540-2a066f0a-5382-11e8-9f22-66a0f1738b1e.png)

 And https://github.com/sul-dlss/dor-services/blob/master/lib/dor/workflow/document.rb#L90-L100

![pastedgraphic-2](https://user-images.githubusercontent.com/96775/39834523-19612ae6-5382-11e8-9466-08cb8b46fd66.png)

Yuck.  Boo.

Candidates of what to remove from workflow_grid:

accession2WF - no longer in use
eemsAccesionWF - no longer in use
googleScannedBookWF - no longer in use
sdrAuditWF - defunct?
sdrIngestWF - replaced by preservationIngestWF
sdrMigrationWF - defunct Was a one-time process to migrate ETDs from SDR1 to SDR2
wasCralDisseminationWF - typo

**Comment by blalbrit** [comment]
And just to document my reply from our slack convo about this:

please don't remove googleScannedBookWF or sdrIngestWF

B.

**Comment by andrewjbtw** [comment]
Looks like in the intervening years the defunct workflows have been removed from the grid. They are still accessible from the three workflow-based facets. I think this way is a good balance between keeping the grid for current work and keeping items find-able by workflow usage, so I'm going to close this.
