### ISSUE TITLE
Support "document" in the bulk update operation "Set content and resource type"

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1140]
Similar to #1139 and #1138 , we need to support bulk operations to change object and resource level types to/from "document".

From the "bulk update" page, the choice "Set content and resource type" brings up the following option set:
<img width="1654" alt="screenshot 2018-06-13 08 37 09" src="https://user-images.githubusercontent.com/796990/41362024-39d3a6ea-6ee5-11e8-8e8b-49ad252ed61c.png">

We need to be able to support "document" at both object and resource levels.

Likely relationship to dor-services work as well.

**Comment by peetucket** [comment]
Completing #1139 should complete this as well, since both use the exact same view partial and controller functionality (bulk just does repeated posts to the single action endpoint)
