### ISSUE TITLE
Increase number of tag fields in registration step

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/argo#1141]
One of the goals for the Digital Production Group, as well as the Digitization Services Manager, is to track objects in Argo by item type in a more granular way. To do this, DPG would like to utilize tagging within Argo at the point of registration. Currently, the 4 tag fields are utilized by other necessary information, so the addition of fields is the only way to include this information. 

See below for an example of SMPL tagging procedure that is akin to the desired behavior for material that is digitized by DPG: 
![screen shot 2018-06-14 at 5 20 07 pm](https://user-images.githubusercontent.com/9371978/41444347-70da5c20-6ff7-11e8-82ed-3a41259d57a4.png)

**Comment by justinlittman** [comment]
@dinahhandel How does this look?
![2019-01-25_1449](https://user-images.githubusercontent.com/588335/51769251-9e14b180-20b0-11e9-8bef-fc6660c76ac6.png)

**Comment by blalbrit** [comment]
@justinlittman - this looks good to me, as Argo product owner, and covers the DPG use-case that triggered @dinahhandel 's ticket. Is it in -stage now for testing?

**Comment by justinlittman** [comment]
@blalbrit Not yet, but will get it there for review.
