### ISSUE TITLE
Possible permissions bug - user without permission to object allowed to bulk update the object

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1159]
This is an odd one - possibly related to our nested workgroup situation for Shib access to Argo.

Summary: User was able to open an object in "bulk update" by including a druid. However, the user was not able to get to the item view page because - at the time - she did not belong to a workgroup that had permissions in the roleMetadata of the governing APO.

Expected behavior: bulk update / bulk actions should not be possible on druids for which the user does not have APO-level permissions.

One of the objects in question is: https://argo.stanford.edu/view/druid:cm398bd3554

Event metadata on that object shows user opening version 4 on 8/27/2018, though she was unable to actually view the object and required assistance from another user to close the object.

(subsequently, we have given the user APO permissions to this content, though she did not have them at the time the above action was taken and should have been barred from editing the content)

**Comment by andrewjbtw** [comment]
I believe this has been fixed.
