### ISSUE TITLE
Edit Collections dropdowns for blue button & bulk update are providing the wrong list of collections

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1171]
This is an unusual one, but in summary:
* In the Blue Button (in item view) and Bulk Update options for adding/editing the collection to which an item belongs, we would expect the list of available collections to be drawn from the list of collections associated with the APO to which the item belongs
* Currently, that list functions as expected on the registration page
* *But* the list in the Blue Button and Bulk Update dropdown does *not* match the list of collections in the APO

Desired behavior: make the "edit collection" dropdowns (in blue button & bulk update) display the same list that the registration collection dropdown displays.

As an example:
* From the Register Item page (https://argo.stanford.edu/items/register), a user has chosen the "Stanford University Libraries - Special Collections" APO and is given the choice of available collections (which matches the list of collections available in the administrativeMetadata datastream in the APO object at https://argo.stanford.edu/view/druid:ww057vk7675)
![screenshot 2018-10-31 12 51 57](https://user-images.githubusercontent.com/796990/47819101-bc1f7f80-dd16-11e8-9ea6-bd84b2417241.png)
* As can be seen, the Digital BookPlates collection is an option in this list
* **However**, if the user forgot to assign that collection at registration time, they have two options: 
** Use the "Edit Collections" blue button at the Item View (for instance at https://argo.stanford.edu/view/druid:jh486mk1405)
![screenshot 2018-10-31 14 13 59](https://user-images.githubusercontent.com/796990/47819308-5089e200-dd17-11e8-879e-252be2724407.png)
** Or use the "Add Collection" option on the Bulk Update page
![screenshot 2018-10-31 14 15 23](https://user-images.githubusercontent.com/796990/47819360-7d3df980-dd17-11e8-9317-294f99367b7e.png)

* Curiously, for _both_ of those options, the list of available collections does *not* match the collections associated with the APO for the object. See, for instance, here where Digital BookPlates is *not* an option the user can choose:
![screenshot 2018-10-31 12 53 09](https://user-images.githubusercontent.com/796990/47819414-a8284d80-dd17-11e8-9a63-a8fed9222462.png)

This list - which can also be seen in the collection_ui partial for the object here: https://argo.stanford.edu/items/druid:jh486mk1405/collection_ui - seems to be drawing from a list of collections for which I can't find the origin (that partial is here https://github.com/sul-dlss/argo/blob/master/app/views/items/_collection_ui.html.erb).

Desired behavior should match the collection generation for the registration page (https://github.com/sul-dlss/argo/blob/193ae0710a0ce0875a49d1cbf320462a1ae13df4/app/controllers/registration_controller.rb#L37 ) and should draw list of available collections from the APO.

**Comment by ndushay** [comment]
@andrewjbtw - I believe this was addressed when #1490 was addressed - do you agree?  Please close ticket if so.

**Comment by jcoyne** [comment]
@andrewjbtw Can you confirm this is no longer an issue?

**Comment by andrewjbtw** [comment]
I'm closing this because there are cases where it has to be possible to put an item in a collection that is not in the same APO as the item. This happens in web archives, for example. Until we can work out another way to support these unusual cases, it turns out to be a feature that the collections menu shows all collections, rather than an issue.

**Comment by andrewjbtw** [comment]
Adding a note also to say that the collections list does now appear to not be missing collections we'd expect to see.
