### ISSUE TITLE
add content type 3d to registration

### ISSUE THREAD

**Issue by snydman** [sul-dlss/argo#1201]
per https://jirasul.stanford.edu/jira/browse/DEVQUEUE-229

add content type 3d to registration and "set content" processes at item view (blue button) and bulk update (this should produce a content type "3d" for the object)

**Comment by ndushay** [comment]
this is done.

**Comment by ndushay** [comment]
this needs to be verified:
- for registration (?)
- for single object view (done)
![image](https://user-images.githubusercontent.com/96775/62732801-19e5a400-b9da-11e9-97bd-4a441d6b7b25.png)
- for bulk update

Ensuring selecting 3d does the right thing ... is that #1202 ?  @peetucket @aaron-collier can you help?

**Comment by peetucket** [comment]
Confirmed this is actually done in all of those places identified above.  Will review #1202 to see if that makes sense.
