### ISSUE TITLE
support resource type 3d in "set content" processes

### ISSUE THREAD

**Issue by snydman** [sul-dlss/argo#1202]
per https://jirasul.stanford.edu/jira/browse/DEVQUEUE-229

support resource type 3d in "set content" processes (this should set resources containing .obj, threejs or GLTF files to resource type = 3d, leaving all other resources as type = file)

**Comment by ndushay** [comment]
Given that #1201 might be done ... is this done?

https://jirasul.stanford.edu/jira/browse/DEVQUEUE-229 suggests: these types must all be accommodated:
  obj, ply, threejs, GLTF, etc. type files

**Comment by peetucket** [comment]
This is not done, and is actually rather complex as defined.  The current "set content type" functionality is a simple search and replace from one content/resource type to another, and does not involve any logic (i.e. looking at the files contained in a resource to decide what to set it to).  As this functionality should only be needed to remediate existing objects that were not accessioned with the correct type, I would suggest lowering the priority of this.

**Comment by andrewjbtw** [comment]
Closing as I believe this can be addressed via the structural CSV.
