### ISSUE TITLE
[argo/prod] JSON::ParserError: 765: unexpected token at ''

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1234]
## Backtrace

    line 21 of [PROJECT_ROOT]/app/services/dor_services/client.rb: register
    line 8 of [PROJECT_ROOT]/app/services/dor_services/client.rb: register
    line 11 of [PROJECT_ROOT]/app/controllers/dor/objects_controller.rb: create

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/43102017)

**Comment by mjgiarlo** [comment]
I believe we resolved this late last week by making the dor-services client more robust. Closing for now.
