### ISSUE TITLE
Links to download a file from preservation core lead to a 404

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#1240]
Current code links to something like  `https://argo.stanford.edu/items/druid:xp320ym6981/files/xp320ym6981_004.tif/preserved?version=1` but based on the route, it expects it to be `https://argo.stanford.edu/items/druid:xp320ym6981/files/xp320ym6981_004/preserved.tif?version=1` (with the format at the end of the url, not the end of the filename ID)

Note from the routes: `preserved_item_file GET      /items/:item_id/files/:id/preserved(.:format)                                            files#preserved` 

Or the link could also be something like `https://argo.stanford.edu/items/druid:xp320ym6981/files/xp320ym6981_004/preserved?version=1&format=tif`

**Comment by jcoyne** [comment]
Can't duplicate. 

<img width="976" alt="screen shot 2018-12-14 at 6 33 48 pm" src="https://user-images.githubusercontent.com/92044/50036589-85a07a00-ffcf-11e8-9168-3eb008467dda.png">

Maybe it was fixed by #1238?

**Comment by peetucket** [comment]
oh yes, works now, that must have fixed it
