### ISSUE TITLE
Remove the "Metadata Source" drop-down menu from item registration

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#1258]
This is a holdover from the days when you could put select other metadata sources, like MDToolkit.  At the moment, there are no options other than "Auto", which pulls from symphony if you include a catkey in the "Metadata ID" column.  We should also just call the column "Catkey" instead of "Metadata ID" since that is what it is now

**Comment by ndushay** [comment]
Note partial PR #1257 may be a starting point.
