### ISSUE TITLE
[argo/prod] RestClient::Unauthorized: 401 Unauthorized

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1277]
## Backtrace

    line 351 of [PROJECT_ROOT]/app/controllers/items_controller.rb: open_version

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/44017600)

**Comment by jcoyne** [comment]
It is attempting to get the current_version from sdr-services-app rather than dor-services-app, so there may be some kind of misconfiguration.

**Comment by jcoyne** [comment]
Possibly because `Dor::Config.sdr.url` is set to a value, which causes dor-services to take this path:

https://github.com/sul-dlss/dor-services/blob/master/lib/dor/utils/sdr_client.rb#L71

**Comment by jcoyne** [comment]
Nope:
```
$ ./bin/rails c -e production
Loading production environment (Rails 5.2.2)
[1] pry(main)> Dor::Config.sdr.url
=> nil
```

**Comment by jcoyne** [comment]
```
> client = Dor::Config.dor_services.rest_client['v1/sdr']
=> #<RestClient::Resource:0x0000000008eac7b8 @block=nil, @options={}, @url="https://dor-services-prod.stanford.edu/v1/sdr">
> client["objects/druid:ch844jn5754/current_version"].get
RestClient::Unauthorized: 401 Unauthorized
```

**Comment by jcoyne** [comment]
Here is the request from the logs on dor-services-app:
```
I, [2019-01-08T11:46:22.038713 #93649]  INFO -- : [696df6e5-bb73-4867-89ab-db6085deb615] Started GET "/v1/sdr/objects/druid:ch844jn5754/current_version" for 171.67.35.73 at 2019-01-08 11:46:22 -0800
I, [2019-01-08T11:46:22.039257 #93649]  INFO -- : [696df6e5-bb73-4867-89ab-db6085deb615] Processing by SdrController#current_version as */*
I, [2019-01-08T11:46:22.039371 #93649]  INFO -- : [696df6e5-bb73-4867-89ab-db6085deb615]   Parameters: {"druid"=>"druid:ch844jn5754"}
I, [2019-01-08T11:46:22.039504 #93649]  INFO -- : [696df6e5-bb73-4867-89ab-db6085deb615] Filter chain halted as #<Proc:0x0000000005d89528@/opt/app/dor_services/dor_services/shared/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/http_authentication.rb:72> rendered or redirected
I, [2019-01-08T11:46:22.039571 #93649]  INFO -- : [696df6e5-bb73-4867-89ab-db6085deb615] Completed 401 Unauthorized in 0ms
```

**Comment by jcoyne** [comment]
This was broken in https://github.com/sul-dlss/argo/commit/4f371ebe840818cd7d63e54e3a9206ca7e82751f#diff-71fc5ddd980a9714e4224eacdf4bbac9

because the rest client connection used here: https://github.com/sul-dlss/dor-services/blob/master/lib/dor/utils/sdr_client.rb#L77
and which is created here: https://github.com/sul-dlss/dor-services/blob/master/lib/dor/rest_resource_factory.rb#L17

Depends on the username and password being in the URL.

**Comment by mjgiarlo** [comment]
@jcoyne recommended the following course of action:

- [ ] add open_version back-end functionality to dor-services-app
- [ ] add open_version integration to dor-services-client
- [ ] use dor-services-client to open versions in argo

That's what I'll be pursuing.

**Comment by mjgiarlo** [comment]
I am reopening this issue to give @blalbrit a chance to confirm this is resolved in the staging environment.

**Comment by blalbrit** [comment]
opening a new version on objects in -stage throws https://app.honeybadger.io/projects/49894/faults/44162193 . cc. @mjgiarlo

**Comment by mjgiarlo** [comment]
@blalbrit got it. thanks!

**Comment by mjgiarlo** [comment]
@blalbrit Can you take another look at stage when you get a chance?

**Comment by mjgiarlo** [comment]
@blalbrit has confirmed this is now resolved. Closing.
