### ISSUE TITLE
Support for "combinate" functionality

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1278]
Story ticket for new feature request.

Summary: "virtual objects" (ie. objects made up of other SDR objects) are currently created by running the virtual-merge script in dor-utils (https://github.com/sul-dlss/dor-utils/blob/master/bin/virtual-merge). Ideally, this functionality would be brought into Argo as a bulk action - though there are likely design and functionality questions to be answered before this is possible.

Background - Existing documentation other than the code:
* https://consul.stanford.edu/display/chimera/Virtual+Object+Combinator+I
* https://consul.stanford.edu/display/chimera/Virtual+Object+Combinator+II
* https://consul.stanford.edu/display/DIGMETADATA/Preparing+and+describing+virtual+objects
* https://consul.stanford.edu/display/DIGMETADATA/Virtual+object+and+combinator+FAQ

Current input to the script is as follows:
```
bundle exec bin/virtual-merge --environment=production druid:cr768rj4665 druid:by372cw6149 druid:vn515vk3705 druid:sh918nq3930 druid:sv576sr3765 druid:pn021qw4383 druid:yn253dq9120 druid:mz593xn2710 druid:jk409zp2668 druid:wn125wt2889
```

User could provide a spreadsheet with druid list on each row, if desired, as input.

Assumptions:
* first druid is the "parent" object
* the list of druids to follow provides the child objects *in the order in which they should appear in the parent object*
* all child objects must already be in an accessioned state and not dark or citation-only
* running the script should completely replace the contentMD for the parent object, not append to it (if not the first time the virtual object has been created)
* rels-ext for the child objects is updated with an is_constituent_of element pointing to the parent object
* contentMetadata for the parent object points each resource to external file content

Examples:
* parent "virtual" object: https://argo.stanford.edu/view/druid:cr768rj4665
* sample "child" object of above parent: https://argo.stanford.edu/view/druid:by372cw6149

**Comment by ndushay** [comment]
related / similar to 1323

**Comment by ndushay** [comment]
All info here has been covered in #1323 or in specific tickets to do the work, such as #1458.
