### ISSUE TITLE
laptop installation issues

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#128]
* i notice that when i do a fresh installation after cloning on my laptop, things fail if i don't manually create the `log` directory.
* on my laptop, i get three unit test failures from a clean installation, even though all of the fixtures were successfully loaded:
```
Failures:

  1) CatalogController show enforces permissions without APO with user is_admin
     Failure/Error: expect(response.code).to eq("200")
       
       expected: "200"
            got: "404"
       
       (compared using ==)
     # ./spec/controllers/catalog_controller_spec.rb:38:in `block (5 levels) in <top (required)>'

  2) CatalogController show enforces permissions without APO with user is_viewer
     Failure/Error: expect(response.code).to eq("200")
       
       expected: "200"
            got: "404"
       
       (compared using ==)
     # ./spec/controllers/catalog_controller_spec.rb:43:in `block (5 levels) in <top (required)>'

  3) DiscoveryController :data should fetch json data with the gdor fields in it
     Failure/Error: expect(json_body['rows'].first).to match a_hash_including('sw_format_tesim')
       expected nil to match (a hash including "sw_format_tesim")
     # ./spec/controllers/discovery_controller_spec.rb:12:in `block (3 levels) in <top (required)>'
```
* i get the same errors running `RAILS_ENV=test bundle exec rake ci` on a clean checkout.  but the same branches where that happens for me locally (develop and laptop_installation_fixes) pass on travis.  so i'm wondering if something's screwy about my laptop setup.
* it seems that `tmp:create` was removed from the list of tasks that `argo:install` runs.  was that intentional?  relevant diff here:  https://github.com/sul-dlss/argo/commit/e2b3ee190008fa7dc58020de1650ed81cf8f66c2#diff-4c5ae9e17f273c380104e0ef14e17c7aR39

**Comment by mejackreed** [comment]
I think this has to do with the issue I described about installing fixtures with a specific RAILS_ENV. This will cause a disparity on whether they get installed in dev or test solr core.

**Comment by mejackreed** [comment]
You should be able to do something like this to run locally for now: `TEST_SOLR_URL=http://127.0.0.1:8983/solr bundle exec rspec`

**Comment by darrenleeweber** [comment]
Test failures on my laptop today when running `git pull; bundle install; bundle exec rake ci` on the develop branch:
```
rspec ./spec/controllers/catalog_controller_spec.rb:35 # CatalogController show enforces permissions without APO with user is_admin
rspec ./spec/controllers/catalog_controller_spec.rb:40 # CatalogController show enforces permissions without APO with user is_viewer
rspec ./spec/controllers/discovery_controller_spec.rb:5 # DiscoveryController :data should fetch json data with the gdor fields in it
rspec ./spec/controllers/status_controller_spec.rb:49 # StatusController log with test_obj should 404 instead of 500 on bad IDs
```

Should the `TEST_SOLR_URL` be updated in sul-dlss/shared_configs?

**Comment by mejackreed** [comment]
No... working on a PR right now to address this. shared configs should never need any of this as no test env is used in deployments

**Comment by darrenleeweber** [comment]
Using `TEST_SOLR_URL=http://127.0.0.1:8983/solr bundle exec rspec` generated more failures (19), while running `TEST_SOLR_URL=http://127.0.0.1:8983/solr bundle exec rake ci` has 1 failure:
```
  1) StatusController log with test_obj should 404 instead of 500 on bad IDs
     Failure/Error: get 'log', :test_obj => 'junk'
     Rubydora::FedoraInvalidRequest:
       See logger for details
     # ./app/controllers/status_controller.rb:14:in `log'
     # ./spec/controllers/status_controller_spec.rb:52:in `block (3 levels) in <top (required)>'
```

**Comment by darrenleeweber** [comment]
I meant `shared_configs/argo-laptop`.

**Comment by mejackreed** [comment]
Ah I see. No i don't think so. #139 addresses this issue and adding something to the laptop branch wouldn't solve this issue either unfortunately.

**Comment by mejackreed** [comment]
So I don't think that #139 will help in this instance and would move forward with educating the team on how our CI dependencies index data rather than a code change. Happy to discuss further.

**Comment by darrenleeweber** [comment]
Maybe add information to the README.md, where all we have now is `rspec`?
