### ISSUE TITLE
break .htaccess generation logic out into app method, add tests

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#129]
currently, all the logic for generating argo's .htaccess file is inline in the rake task.  we should probably at least take the logic that generates the relevant workgroup list based on solr query results, and turn that into a helper method in the app, preferably with tests.

https://github.com/sul-dlss/argo/blob/develop/lib/tasks/argo.rake#L289

**Comment by blalbrit** [comment]
@jmartin-sul - is this still a valid concern? (looking to groom the backlog)

**Comment by jcoyne** [comment]
.htaccess is no longer used since we switched to Shibboleth.
