### ISSUE TITLE
Manage content for resource type=object

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1293]
Parking this here as it is a use-case we may need to account for. Not sure how pervasive this is in existing data, which would tell us how to prioritize the work.

Scenario:
- A user has content of object type book that contains only resources of type object. This situation would arise if PDFs were registered as book instead of file or document. In this scenario, items of type book would have a single shelved resource of type object - so should be pretty easy to track down.

In the "Set content type" blue buttons, the choice to change something from a dropdown list *to* "document" for both object and resource is available. However, the option to change *from* resource type object does not exist.

Purpose of this ticket would be to add "object" to the dropdown list of "Old Resource Type"

<img width="912" alt="screenshot 2019-01-24 15 18 59" src="https://user-images.githubusercontent.com/796990/51714889-86272a00-1feb-11e9-93d6-bd1a9e587e1d.png">

Seems like this might just be a matter of updating that dropdown list?

**Comment by andrewjbtw** [comment]
Not sure when it happened but object is on the relevant dropdown now.
