### ISSUE TITLE
update dor_development.rb and dor_production.rb to use new cert/key approach

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#130]
whole file name (including path) is now in the setting, since the two files may not share a parent directory, and their respective parent directories may not be within the argo app folder structure.

will also need to update the laptop settings in the private shared_configs branch.

not relevant for dor_test.rb, which should be fine as-is.

this was already done for dor_staging.rb here:  https://github.com/sul-dlss/argo/commit/6ae7ec8c7edc5e72b7c90932183a8565bd1696ed#diff-8b5c140397bffd71dd34ed036ca3e5feL5

**Comment by aaron-collier** [comment]
Out of date.
