### ISSUE TITLE
Add standard results navigation to workflow grid

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#132]
Add the same set of "Start Over" button, results and report view buttons, etc  to the workflow grid page as when viewing a result listing.

**Comment by mejackreed** [comment]
@LynnMcRae can you provide a screenshot of the "results view" and "Back to Search" buttons you are referring to?

**Comment by LynnMcRae** [comment]
The buttons from the old/current interface have been replaced by the standard blacklight navigation, the workflow grid being just another view of the search result.  I guess what would not apply is the paging controls since the workflow information is all on  a single page.

"Back to search" was my misstatement since you are still on the searcj ... I meant the buttons that let you switch among Result View, Report Views, and Workflow Grid. Does this help? clarify?

There is a separate ticket not yet included that has the idea that view swapping could be a single pulldown rather than 4 buttons for real estate reasons. I would discuss first, but is that a promising idea?

**Comment by mejackreed** [comment]
Thanks yes that helps tremendously.

It would be good to understand all of the goals of what you are trying to accomplish WRT the various buttons. Blacklight has the facility to have this as a dropdown, but I think the argo codebase would need some shifts to accomplish this. Feel free to put the tickets in the backlog so I can see what's in store.

**Comment by LynnMcRae** [comment]
The overarching goal is consistency of navigation thingies across the app, with common elements like "Start over"  in the same place in the shared parts of screen layout.  I assume blacklight out of the box gives us that:

![screen shot 2015-11-12 at 2 16 56 pm](https://cloud.githubusercontent.com/assets/1824732/11133169/f92285b4-8948-11e5-853c-e38c80e0a031.png)

It also gives us the ready place for "Items-per-page" and "Sort" as they get introduced.

Searchworks has modified the BL layout a bit, perhaps of future interest. But SW does illustrate the only addition that Argo also has, which is the ability to switch Results views:

![screen shot 2015-11-12 at 2 11 13 pm](https://cloud.githubusercontent.com/assets/1824732/11133709/59e2ffa2-894c-11e5-972d-e12e78609805.png)

You see they have the pulldpwn menu, while we have the four buttons -- Results View, Report View, Discovery Report, and "Workflow Grid" (shortened from Workflow Grid View in case that's missed in a ticket). Only 3 of the buttons show at a time depending on which view you are on. The idea of a Pulldown was in part growth (we might want to have the not yet implemented data profiler be a view) but in the short term to address a real estate issue since the buttons share the same space as the search breadcrumbs which might get long.

Happy to chat more in person if this isn't what you were looking for.
