### ISSUE TITLE
(uber ticket) Add bulk action (async) for virtual merge

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1323]
**References:**
* current code: https://github.com/sul-dlss/dor-utils
* original reqs and specs: https://consul.stanford.edu/display/chimera/Virtual+Object+Combinator+I

**User story:**
* stakeholder has accessioned a large number of individually-cataloged single-image objects that they wish to assemble and present as a composite object (for example, an atlas in which each map has been individually cataloged; a photo album of which each individual photo has its own PURL, etc.)
* rather than accession the individual binaries AND also accession the binaries as part of a composite object, we create a virtual composite object in which the contentMD points to binaries held in other objects
* the child objects have an isConstituentOf element in RELS-EXT allowing traversal to a parent object in discovery interfaces

**Example:**
* "virtual" composite object: https://argo.stanford.edu/view/druid:rf572mg1458
* constituent child objects: https://argo.stanford.edu/catalog?f%5Bexploded_tag_ssim%5D%5B%5D=CATKEY+%3A+10448342&per_page=100

**Current Implementation:**
* at the moment, a repository admin does the following:
* receives a spreadsheet from the stakeholder listing the druid of the virtual composite object in the first column and the child objects _in_ _sequence_ in the following columns
* stakeholder registers all virtual composite objects
* stakeholder opens version on all child objects
* admin adds blank contentMD datastream to the virtual composite object
* admin uses spreadsheet to invoke each row similar to `rvm use 2.2.4 do bundle exec bin/virtual-merge --environment=production druid:cr768rj4665 druid:by372cw6149 druid:vn515vk3705 druid:sh918nq3930 druid:sv576sr3765 druid:pn021qw4383 druid:yn253dq9120 druid:mz593xn2710 druid:jk409zp2668 druid:wn125wt2889` (this is currently scripted to iterate through rows and, because it is a slow process, usually run nohup - depending on size of job and number of objects involved, this can run for up to several days)
* once virtual merge is complete, admin closes open objects and - for the virtual composite objects - invokes the accessionWF to run those objects through accessioning.

**Desired Implementation:**
* user still registers virtual composite object as before 
* if we go the Argo route, then user uploads the spreadsheet above (described here: https://consul.stanford.edu/display/DIGMETADATA/Preparing+and+describing+virtual+objects#Preparinganddescribingvirtualobjects-III.PrepareaCSVmanifestforthecombinator) as a Bulk Action
* bulk action should build virtual composite object contentMD, insert RELS-EXT isConstituentOf element in child objects, close open objects, accession virtual composite objects
* Edge case: sometimes users need to run the virtual merge process more than once (overwriting previous contentMD for virtual composite objects). This case should be handled without adding a second isConstituentOf element to RELS-EXT and should overwrite rather than append to virtual object contentMD.  (Note from Naomi:  Our existing code infrastructure (activefedora?) already prevents duplicate relationships in RELS-EXT)
* Bulk Action is desired because of potential long-running aspect of these jobs - user needs to be able to leave the interface and come back later to check on progress.

Additional Reading: https://consul.stanford.edu/display/DIGMETADATA/Virtual+object+and+combinator+FAQ

**Comment by ndushay** [comment]
we should do combinator in bulk action (background processing, specifically)

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/62333346-ff5e7880-b477-11e9-96f5-839b577da73a.png)

For bulk actions, provide a drop down with all the possible bulk actions. When user selects an action, the appropriate fields and instructions appear allowing them to perform the action.

**Comment by ndushay** [comment]
See also:  #1278

**Comment by ndushay** [comment]
doing this probably requires dor-utils script migration:  see https://github.com/sul-dlss/dor-utils/issues/65

**Comment by ndushay** [comment]
#1458 is part one of this work

**Comment by ndushay** [comment]
After this is done, sunset dor-utils:   sul-dlss/dor-utils#65

**Comment by ndushay** [comment]
#1463 is the hook-up-the-UI part of this work

**Comment by andrewjbtw** [comment]
Following up on a question from storytime: the "Reverse combinator" AKA "Virtual Object Combinator II" was never implemented. This was the proposal to create child objects for individual files from an already existing multi-file parent object.

https://consul.stanford.edu/display/chimera/Virtual+Object+Combinator+II

See also the bottom of this page:
https://consul.stanford.edu/display/DIGMETADATA/Virtual+object+and+combinator+FAQ#VirtualobjectandcombinatorFAQ-Whatisthedifferencebetweenthecombinatorandthereversecombinator?

Only the combination of existing child objects into a virtual parent object has been implemented. 

cc: @ndushay

**Comment by ndushay** [comment]
I think what remains for virtual-merge is ticketed elsewhere:
- [x] dor-services-app gets virtual-merge method
- [x] dor-services-client gets virtual-merge method
- [x] #1458  virtual merge re-worked as active-job implementation
- [ ] #1464  ensure object is not dark or citation-only
- [ ] #1463  create/hook up UI to bulk action
  - [ ] UI design needed???
  - [ ] PO will vet after this is ready

**Comment by mjgiarlo** [comment]
All subtasks are now done! closing.
