### ISSUE TITLE
Wait for solr in build

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1328]
The Travis build regularly fails when solr isn't starting up fast enough. We should add something like this to make sure this never happens: https://github.com/ledermann/docker-rails/blob/develop/docker/wait-for-services.sh

**Comment by justinlittman** [comment]
Also, we did this in the Dockerfile-dev for RIALTO webapp: https://github.com/sul-dlss/rialto-webapp/blob/master/docker/invoke.sh#L4

**Comment by jcoyne** [comment]
This is complete
