### ISSUE TITLE
Manage Catkey Bulk Job Enhancement - Change "close" behavior and add option to refresh metadata from source

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1333]
Now that this bulk job has been in production for a bit, users have provided the following feedback:

* they would like the _option_ of include a "refresh metadata from source" step to the bulk job (that is, they could load in the catkeys and then _choose_ to also refresh the metadata from those new catkeys while closing the job). This should be an *option* as there are use-cases where they do *not* want to update the metadata from source

* they would like the option to keep the job open after the catkeys have been loaded in (in case there are other remediations to be done) _or_ to close the versions in bulk at the end of the job

**Comment by blalbrit** [comment]
(Note: this would effectively migrate another "Bulk Update" (refresh MODS) into the "Bulk Action" framework - so a secondary task would be to remove that "Bulk Update" blue button as well - which will have implications for implementation and likely require some design consideration).

**Comment by andrewjbtw** [comment]
Superseded by https://github.com/sul-dlss/argo/issues/2274 for the auto-close behavior. Any changes to add options in the bulk actions framework will be separately ticketed. Currently, each bulk action does only one thing and we'll need to spend some time on designs if we want bulk actions to provide options like "add catkey + refresh" and "add catkey but don't refresh".
