### ISSUE TITLE
Argo should consistently support optional "druid:" prefix

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#134]
You can request an object in argo directly with a url like 

    argo.stanford.edu/view/druid:xx123yy4567 or
    argo.stanford.edu/view/xx123yy4567

The "druid:" prefix is optional for convenience, but apparently the system in some context thinks "xx123yy4567" alone identifies the object in cases where the full "druid:xx123yy4567" is expected, to wit ... this led to a "Object does not exist error" when using "Add workflow". Should have all contexts support optional druid: prefix.

**Comment by mejackreed** [comment]
Can you point to some specific routes/examples?

**Comment by atz** [comment]
If you are adding a workflow, you *should* be required to PUT or POST (for proper RESTfulness).  Editing the URL creates a GET request that shouldn't be able to create *anything*.  We haven't been good about following this discipline though.  

I don't think that every method and every context should have to interrogate the string(s) it is passed and optionally add `druid:`, if only because it is unnecessarily burdensome and redundant.  It makes sense to do it for the commonly used routes, if we can enumerate them here.

**Comment by mejackreed** [comment]
Just to note we do seem to use "druid:xx123yy567" in our unique identification field in Solr

**Comment by LynnMcRae** [comment]
I totally agree, but I was imagining that there was only one place ... the URL that got you to the object ... that needed to support the short cut, and that as implemented it was deficient in that it took the shortened string as equal to the full druid and somehow allows the session to think that is the object's identifier when it is not. I'm not sure why the value passed in on the URL fools the system this way instead of the object providing its own proper druid irrespective of how you got there, but there you are. Adding the shortcut on the service calls would be bad bad bad.

I don't recall if we allow users to past a druid list in for bulk update without the prefix, but that would be another place where an app affordance would need to expand the druid up front and nothing deeper would be the wiser.

**Comment by atz** [comment]
I think this was just a configuration/data problem.  Going to need more specificity about where this problem exists presently.  Otherwise, we can close this until it comes up concretely.

**Comment by LynnMcRae** [comment]
Since Add Workflow works in this situation in Stage, I think we can call it fixed.  I tried a variety of other functions and had no problem.
