### ISSUE TITLE
Blue button 'edit tag' suggests versioning required on accessioned objects when it should not

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/argo#1340]
As a user, if I try and add a tag to an accessioned object using the blue button, I get this error when I submit my change:

"Object cannot be modified in its current state."

However, doing a bulk tag update on the same accessioned object will not throw an error. This latter behavior is what is expected (versioning shouldn't be required when adding/removing tags).

**Comment by andrewjbtw** [comment]
This has now been fixed with the new tag implementation.
