### ISSUE TITLE
Bulk Descriptive Metadata Download

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#136]
1. from a list of Druids, fetch and output the MODS from the descMetadata stream
     - as a single \<xmlDocs> document (see https://consul.stanford.edu/display/chimera/MODS+bulk+loading)
2. Offline process managed as background task and tracked, delivered via a history screen similar to that developed for Replayable Spreadsheets 
3. Authorization checked for access with "Not authorized" error" on a per object basis
3. First instance of data output in bulk ... offer "druids from search" and "paste a druid list" choice like Bulk Update
4. Change name of "Bulk Update" to "Bulk actions" ... or implement separate "Bulk output" for this and (future) tracking sheet generation.

**Comment by darrenleeweber** [comment]
Discussed this today with @LynnMcRae, @blalbrit and @tingulfsen.
 - @LynnMcRae to draft mockup designs
 - I'll start to review code

**Comment by darrenleeweber** [comment]
@tingulfsen notes:

To actually run the current bulk upload process on your local machine, do `./bin/delayed_job start` before starting the `rails server`. Then navigate to an APO and click on “MODS bulk loads”.

These are the relevant code files:
- routes: https://github.com/sul-dlss/argo/blob/develop/config/routes.rb#L19-L27
- controller: https://github.com/sul-dlss/argo/blob/develop/app/controllers/catalog_controller.rb#L191-L264
- view - bulk upload history: https://github.com/sul-dlss/argo/blob/develop/app/views/catalog/_bulk_index_table.html.erb
- view: https://github.com/sul-dlss/argo/blob/develop/app/views/catalog/bulk_jobs_index.html.erb
- view: https://github.com/sul-dlss/argo/blob/develop/app/views/catalog/bulk_upload_form.html.erb

The background job that gets executed, based on Delayed Job:
- https://github.com/sul-dlss/argo/blob/develop/app/jobs/modsulator_job.rb
- started by: https://github.com/sul-dlss/argo/blob/develop/app/controllers/catalog_controller.rb#L206

Also note that the modsulator_job.rb calls the remote service for the [MODSulator](https://github.com/sul-dlss/modsulator), the gem that generates the upload file's XML translation (combines several DOR objects’ XML into a single document):

We may or may not need any of the MODSulator code for manipulating XML within the new download code.

**Comment by darrenleeweber** [comment]
Work for this will be in https://github.com/sul-dlss/argo/tree/bulk_upload_issue136

**Comment by darrenleeweber** [comment]
Working in https://github.com/sul-dlss/argo/tree/bulk_download_issue136

**Comment by LynnMcRae** [comment]
Here's a first pass at a screen design (not including the surrounding screen where it will live).

![mods-download](https://cloud.githubusercontent.com/assets/1824732/11082205/f8a33632-87d7-11e5-929c-ecbf1554b192.png)

**Comment by darrenleeweber** [comment]
Great.  The 'Who' column can only be the logged in user, so it's superfluous.  Is the 'Action' column always the same (if so, remove it too).  Removing constant columns makes more room for other items (like notes).  Add an 'expires' column?

**Comment by darrenleeweber** [comment]
Working in https://github.com/sul-dlss/argo/tree/bulk_download_issue136

**Comment by LynnMcRae** [comment]
Agree with the Who column.  We'd like to leave the Action column in because a near follow-on if we have time will be a second form of output (tracking sheets for labs to track the physical item). Le't maybe change that column to "Output" and just have it say "Desc Metadata" to be shorter about it.

**Comment by darrenleeweber** [comment]
I'm try to clarify where the bulk download UX starts and I'm guessing it starts with `/report/bulk?someQuery` because it provides a panel for 'Bulk update operations’ and a couple of buttons to get druids.  It seems reasonable to add a new button for ‘download MODS’ under ‘harmless’.

**Comment by darrenleeweber** [comment]
I'm OOO for argo until Nov 23, so handing off this issue now.

**Comment by LynnMcRae** [comment]
Slight revisions for download screen

![mods-download](https://cloud.githubusercontent.com/assets/1824732/11252166/896e5eaa-8de9-11e5-843b-ae3565531686.png)

**Comment by tingulfsen** [comment]
@blalbrit @LynnMcRae Can you confirm that it's correct to tie each bulk action (whatever type of action it may be) to the user that initiated the action? As opposed to connecting bulk actions and collections/APOs?

**Comment by blalbrit** [comment]
@tingulfsen - if possible, yes. That would be the model we would like to move to.

**Comment by darrenleeweber** [comment]
FYI, dropping off this thread.

**Comment by LynnMcRae** [comment]
Revised mockups, separating Download page with history from the action-taking modal. Also includes a help box with a brief explanation of the output (to be revised for .zip as that is decided). 
![mods-download](https://cloud.githubusercontent.com/assets/1824732/12155727/a1fcb1b6-b47b-11e5-9df3-8f5195755499.png)

**Comment by LynnMcRae** [comment]
![screen_shot_2016-02-01_at_5 14 20_pm_1024](https://cloud.githubusercontent.com/assets/1824732/12737256/d4ee94dc-c90b-11e5-8e69-812747b82e79.png)

Some quick comments:
- Label screen the same as (the new) Button, just "Bulk Actions" I assume.
- The "New bulk action" button shouldn't float at the bottom of a growing history list. It should be above.
- Submitted date will be local time I trust, not UTC, and drop the seconds please
- Show history in reverse time order (newest at top)
- Column heading "Action", not "Action type"
- Better names for that actions, something more user facing. "Download Desc MD" perhaps. 
- Is it the same set of statuses we use for spreadsheets?  Spreadsheet loading has an interpretive key that would be nice to include (a version of). Picture of its implementation shown below.
- Only need to show total and if/how many errors ... "Total / Errors"
- Log and output file links are not yet shown.


![screen shot 2016-02-01 at 5 58 33 pm](https://cloud.githubusercontent.com/assets/1824732/12737466/9c4da81e-c90d-11e5-818a-075a5e7de7f4.png)

**Comment by mejackreed** [comment]
Thanks for your comments @LynnMcRae . As we move forward we will look at incorporating them in. Though, we may at some point incorporate some of them as follow on enhancement PR's. Also updating your comment as a checklist so we can knock them off as we go.
