### ISSUE TITLE
"Add workflow" modal has header menu bar

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1365]
Reported by @arcadiafalcone - for some reason the "Add workflow" modal now includes the menu bar.

To replicate, go to an item view and use the blue button to "Add workflow"

![Screenshot 2019-04-16 10 52 43](https://user-images.githubusercontent.com/796990/56232749-57db4880-6036-11e9-8199-3c1a64bd6573.png)

**Comment by andrewjbtw** [comment]
Appears to have been fixed by https://github.com/sul-dlss/argo/pull/1720
