### ISSUE TITLE
What are the implications of load balancing in production?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#137]
ping @drh-stanford 

Seems like there are some implications with race conditions in Fedora 3. Same item being edited by multiple users.

**Comment by atz** [comment]
Race condition exists in F3 without load balancing anyway.  Can be multiple writes from *same* user even.  Or from delayed job and current action.

**Comment by drh-stanford** [comment]
Re: the local MySQL database. If there's information in there that's either needed by multiple users concurrently or needed over long periods of time (e.g., bookmarks), then we'll need to deploy a shared MySQL database server, and/or setup database replication.

**Comment by LynnMcRae** [comment]
Is this the MySQL that comes free/standard with blacklight, for keeping track of things owned by users, like bookmarks?  If so, Argo currently makes no use of it.

**Comment by mejackreed** [comment]
@LynnMcRae we do use it. Blacklight uses it for various things besides bookmarks, even though we don't expose bookmarks.

**Comment by jmartin-sul** [comment]
yup.  argo uses it for managing basic session info, and presumably things like preferred number of results per page?

**Comment by mejackreed** [comment]
Yep and there is a delayed_jobs table ... so I suspect the replayable spreadsheets does something with it to. TLDR, yes we use the mysql database

**Comment by jmartin-sul** [comment]
i'm also considering using it (maybe via delayed_jobs, will get advice from @tingulfsen) for improving the rake reindex task.

**Comment by drh-stanford** [comment]
here's what i'm seeing in development:

```
sqlite> .tables
bookmarks            robots               users              
delayed_jobs         schema_migrations  
indexing_exceptions  searches           
```

it sounds like from the comments above, that we do have data in there that would require a shared database across argo instances in a load-balanced environment. 

so, the solution in production/stage would either be instance databases that are synchronized via replication, or a single master database. the latter is simpler, though it introduces a single point of failure, but i'm not aware of a shared mysql instance running so we'd have to bootstrap prod/stage VMs. we do have PostgreSQL databases running for EarthWorks if we want to use them.

**Comment by jmartin-sul** [comment]
argo's database usage seems simple enough that swapping MySQL for Postgres shouldn't cause any trouble.

**Comment by mejackreed** [comment]
Yep also to note, SW uses a shared MySQL in prod for LB.. So we've solved this problem already.

**Comment by drh-stanford** [comment]
can we use the SW MySQL instance, or will we need to spin up our own?

**Comment by mejackreed** [comment]
Most likely need to rope in devops on this stuff to see what is possible in our timeline. F3 race conditions seem like a deal breaker to me.. thoughts?

**Comment by drh-stanford** [comment]
The Fedora 3 race conditions are a pre-existing condition. The robots and Argo for example might write to the same object concurrently, for example. I think the Argo load balancing just increases the exposure (i.e., potentially more concurrent users with a faster app).

**Comment by LynnMcRae** [comment]
Like DrH say, we've lived with the lack of transaction semantics in Fedora3 because that's the way it is, and addressing it is out of scope. Load balancing or not, we'll have the same users and processes doing the same activities.  I'm more concerne

**Comment by drh-stanford** [comment]
@blalbrit what's the status of this issue? the brief summary is that if we do load balancing then we will need a shared MySQL database we can use (i.e., share with SearchWorks) or deploy our own.

**Comment by mejackreed** [comment]
I think this issue was more about just outlining things that need to be down. Hopefully that can help us figure out if this needs to be a priority.

Doubt @sul-devops-team would have argo and SW share a db
