### ISSUE TITLE
bulk actions should handle very large collection of objects

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/argo#1396]
Read all the comments - note that #816 (replace delayed_job as Rails ActiveJob middleware is a pre-req) 

(copied over from https://jirasul.stanford.edu/jira/browse/ARGO-502)

Bulk actions require adding or editing items to a graphical interface. For very large collections (gt 500), time delay and browser time-out become factors, which require that large batches be broken down into smaller batches.

Can we create a method to register and do other bulk actions that does not require so many browser resources?

This is a factor for EVIS, University Archives, and Laura Wilsey.

Thanks!

**Comment by LynnMcRae** [comment]
Does this refer to the functions still under "Bulk Update", which does have browser dependencies and requires a session to remain active, or to the newer "Bulk Actions" which runs in the background and can handle much bigger jobs (which I understand also has some large batch limitations)?

**Comment by oceanofsound** [comment]
Primarily "Bulk Update" and the registration screen, I believe, although I think "Bulk Actions" has issues as well. I'll admit I don't usually work with object groups as large as the stakeholders who reported this issue, but that's what I've gathered through the grapevine.

**Comment by Mellen22** [comment]
A possible solution would be to integrate registration into the pre-assembly app. See https://github.com/sul-dlss/pre-assembly/issues/493

**Comment by ndushay** [comment]
from slack:

Andrew Aug 7, 2019:
>  it looks like accessioners are able to run more than 500 objects at a time in pre-assembly so registration is the bottleneck there. But I could be wrong.

Ben Aug 7 2019:
> that’s correct @bergeraj - support for bulk actions includes registration, open/close versions, etc. as asynchronous activities rather than in-browser activities (aka. bulk action vs bulk update / registration)
> that’s what is desired here.

So we want:
- asynchronous bulk action (rails ActiveJob) to support 
  - registration
  - other stuff

**Comment by ndushay** [comment]
See also #816 - we probably need to switch to resque-pool for this.

**Comment by ndushay** [comment]
@blalbrit @andrewjbtw @hannahfrost  - @jmartin-sul  makes an excellent point about separating the required non-trivial refactoring/bug shakeout (issue #816 re: replacing our Argo background process middleware away from delayed_job) from new feature development.

So pursuing this work should NOT be concurrent with other changes to bulk actions, esp. async ones (refactoring, adding new bulk actions, etc.)

So a key question for SDR Fall 2019 work: would you rather:  

- A.  create new async bulk actions (e.g. 
  - virtual merge https://github.com/sul-dlss/argo/issues/1323
  - re-accessioning https://github.com/sul-dlss/argo/issues/1147
  - open, close sets of objects
  - md5 self service https://github.com/sul-dlss/argo/issues/1145
  - sdrget self servicee https://github.com/sul-dlss/argo/issues/1146

OR 

- B.  be able to push more than ~500 objects through at a time?  (this ticket)

**Comment by andrewjbtw** [comment]
This was accomplished by moving bulk actions to sidekiq. Because the actions are different, some bulk actions scale better than others. I've been able run some bulk actions, such as reindex, manage tags, and download descriptive metadata, on the scale of 100,000+ druids. Given that, I'm closing this in favor of individual tickets for:

- any bulk action that needs specific attention to scale better
- the tickets to move the not-so-scalable bulk update over to bulk actions.
