### ISSUE TITLE
Bulk action 'populate with previous search' button returns undefined results

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/argo#1412]
Steps to reproduce:

https://argo.stanford.edu/catalog?per_page=50&q=%22JIRA+%3A+SPECPAT-1993%22

- click on ‘Bulk Actions’ button
- click on ‘New Bulk Action’ button
- click on ‘Populate with previous search’

Results returned are ‘undefined’ where they should be a set of druids. Discovered this quirk when trying to release these objects to SearchWorks. I've tried with a couple different object sets and the behavior is the same.

Notably bulk update does return the correct set of druids.

**Comment by oceanofsound** [comment]
<img width="1465" alt="undefined" src="https://user-images.githubusercontent.com/1029087/57877065-bcbbc700-77cb-11e9-8da4-af75d5edb46a.png">

**Comment by blalbrit** [comment]
@vivnwong - per our conversation this afternoon.

**Comment by peetucket** [comment]
is it possible this is fixed?  I just tested and can't reproduce.

**Comment by oceanofsound** [comment]
yeah, looks like it works now
