### ISSUE TITLE
Expected Argo results pagination, sorting, view

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#142]
Currently in argo it has a non-standard results view with pagination. Should it be more vanilla blacklight? @LynnMcRae

**Comment by LynnMcRae** [comment]
It's not even based on an older Blacklight pagination model? Absolutely no reason for that.  We want all the usual results page navigation affordances that come with blacklight.  Probably some other tickets will require it (like implement #-entries per page choice, sorting, standard navigation placement?). Will anything unexpected happen from the switch or will that be basically transparent?

**Comment by mejackreed** [comment]
Gotcha.. doing all of this in one swoop right now.

**Comment by mejackreed** [comment]
Related to #133

**Comment by mejackreed** [comment]
Closed by #144
