### ISSUE TITLE
Collection name in drop-downs drawn from wrong data source

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1421]
**Describe the bug**
As reported by a user, a specific collection was not showing up in the drop-down menus for registration or remediation:
```
Stanford University, Faculty Senate, records
gh292ts1354
```
In fact, the collection was there, but under an old title (the one with which it was initially registered):

![Screenshot 2019-06-03 14 36 11](https://user-images.githubusercontent.com/796990/58836438-b2902a00-860d-11e9-961b-25c56462e19c.png)

Upon investigation, the title in the drop down does not appear anywhere in Argo (not in identityMetadata, descMetadata, or DC). However, it *does* appear as the Fedora label for the object (a non-user-facing piece of metadata created by default when the object is first registered in the system):

![Screenshot 2019-06-03 14 37 27](https://user-images.githubusercontent.com/796990/58836508-d6537000-860d-11e9-935a-54775ce637a8.png)

The bug appears to be that the label being used for the drop-downs is not using data from any of the active datastreams (see https://argo.stanford.edu/view/druid:gh292ts1354 - esp. descMetadata, identityMetadata, and DC) but is, instead, going to Fedora directly to get an object label.

**User Impact**
See above. If a collection label has been edited at any point after registration, it is not updated and - effectively - disappears from where the user would expect to find it in a drop-down list.

**To Reproduce**

See links and screenshots above.

**Expected behavior**
Label should be drawn from: descMetadata first, falling back to identityMD label if descMetadata not present.

**Screenshots**

Screenshots incorporated above.

**Comment by jcoyne** [comment]
@blalbrit It says "See links and spreadsheets above.", but I don't see what that refers to.

**Comment by jcoyne** [comment]
@blalbrit what page did you find this drop-down on?  When I'm walking through the code for the registration page, it's returning the correct value:
```
solr_doc = Dor::SearchService.query('id:druid\:gh292ts1354', fl: SolrDocument::FIELD_TITLE)['response']['docs'].first
=> {"sw_display_title_tesim"=>["Stanford University, Faculty Senate, records"]}
```

**Comment by blalbrit** [comment]
@jcoyne - thanks for following up on this. The screenshot above is from the registration page at https://argo.stanford.edu/items/register . The dropdown list comes from choosing the Stanford University Archives APO:
<img width="588" alt="Screenshot 2019-06-04 07 13 00" src="https://user-images.githubusercontent.com/796990/58886253-6dfda080-8698-11e9-8c9b-21b764b898ba.png">

Then scrolling through the alphabetical list in the Collections dropdown:
<img width="304" alt="Screenshot 2019-06-04 07 15 53" src="https://user-images.githubusercontent.com/796990/58886404-b0bf7880-8698-11e9-8e0f-b49d80209577.png">
<img width="304" alt="Screenshot 2019-06-04 07 15 53" src="https://user-images.githubusercontent.com/796990/58886416-b6b55980-8698-11e9-8fc5-001eea7d152d.png">

I'm also not seeing "Academic Council" in the bulk page, but nor am I seeing the Faculty Senate Records - not sure if I'm just missing it, or if it's not there at all.

Don't know where "spreadsheets" came from - just a typo from me trying to write "screenshots" I think, corrected above.

**Comment by jcoyne** [comment]
It's trying to use the title from the mods, e.g.:
```ruby
Dor.find('druid:pb873ty1662').stanford_mods.sw_title_display
```
