### ISSUE TITLE
Is solr request in page head a feature needed in argo?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#143]
This legacy code added in https://github.com/sul-dlss/argo/commit/fea324130be0e0391233755c7315a82c9e0d81f7

https://github.com/sul-dlss/argo/blob/develop/app/views/catalog/index.html.erb#L1-L3

I can't figure out what this does or what might use this. @LynnMcRae Can you please provide some historical context? Can we get rid of this?

**Comment by LynnMcRae** [comment]
I can't tell what this does either.  There is a"View solr document" link in the sidebar where we offer links to PURL, Fedora admin, and the FoXML as well. That is tremendously useful. Does this relate to that?

**Comment by mejackreed** [comment]
Not that I can tell. That "View Solr document" link is generated using this helper:
https://github.com/sul-dlss/argo/blob/04815a9188821c0c3b090a3d60cf7c0a497ab4bf/app/helpers/argo_helper.rb#L215-L220

**Comment by drh-stanford** [comment]
It looks like an attempt at linked data to me -- but it could be done by adding `.json` to the request instead, right?

**Comment by mejackreed** [comment]
Yeah but why do we even need it there (there == in the <head> section)?

**Comment by drh-stanford** [comment]
+1 to remove it
