### ISSUE TITLE
Catalog service not working in argo-stage

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#1430]
I'm attempting to test the new web service box by registering objects in argo-stage with catkeys. The registrationWF did not generate descMetadata datastreams for these objects, and Ben reports that the catalog service is not set up on argo-stage.

Test druids: ck139cn8667, jw492ky4306

**Comment by hannahfrost** [comment]
@arcadiafalcone Is this urgently blocking you?

**Comment by arcadiafalcone** [comment]
Not me, but my inability to test this may block @shelleydoljack and @dlrueda .

**Comment by shelleydoljack** [comment]
We are upgrading Symphony web services to a new version and servers. At the very minimum, a test of the connection to the new servers and the data returned from the web services call it (dor-services-app?) makes, should be done before we cut off the old servers (t.b.d.).

**Comment by hannahfrost** [comment]
@shelleydoljack Yeah, agreed. We should be in touch about the timeline for this and make sure we have what we need in place to test.

**Comment by ndushay** [comment]
I spoke to @shelleydoljack this morning;  I may garble this.  Shelley says she did a PR on dor-services-app to point to their new URL;  
- did it get deployed to stage?
- do we need to update shared_configs?
- not sure what else.

**Comment by jmartin-sul** [comment]
just discussed on slack w/ @shelleydoljack.  she had (sensibly) updated the stage dor-services-app configs to point to the new dev symphony web service.  but it seems like we actually want dor-services-app-stage to point to the prod symphony web services, so we can test our symphony connection in stage, before cutting over dor-services-app-prod (and the other services that depend on it).

submitted a shared_configs PR to that effect and connected it back to this issue.

**Comment by jmartin-sul** [comment]
@arcadiafalcone, @shelleydoljack, and @dlrueda, the config change has been merged and deployed.  dor-services-stage (and thus argo-stage) should now be using the new prod symphony URL.

**Comment by hannahfrost** [comment]
@arcadiafalcone @shelleydoljack Can you confirm that this is working for you in -stage as expected?

**Comment by jcoyne** [comment]
Confirmed by @arcadiafalcone on slack today

**Comment by ndushay** [comment]
w00000t!
