### ISSUE TITLE
"Registered" (by date) facet does not appear after setting a starting limit 

### ISSUE THREAD

**Issue by ryunleeuu** [sul-dlss/argo#1455]
**Describe the bug**
Registered (by date) facet disappears after setting an initial limit, no matter how the user limits

**User Impact**
This makes it a bit more difficult to find assets, but I can work around by using other facets or faceting on "Registered" first.

**To Reproduce**
1. Go to argo.stanford.edu
2. Click on any facets besides "Registered"
3. Scroll down, and "Registered" no longer appears in the left menu of facets, and there is no "More Facets" button
4. Alternatively, see as example facets
https://argo.stanford.edu/catalog?all=true&f%5Bexploded_tag_ssim%5D%5B%5D=CONS
https://argo.stanford.edu/catalog?all=true&f%5Bnonhydrus_collection_title_ssim%5D%5B%5D=Alfred+A.+Hart+photographs
https://argo.stanford.edu/catalog?all=true&f%5Bsubmitted_latest_date%5D%5B%5D=days_7

**Expected behavior**
Normally, I'd be able to facet by Tag or Collection first and then sort further by limiting to when I'd registered an item by finding the Registered facet after the initial sort.

**Comment by jcoyne** [comment]
I believe this is a feature of Solr and Blacklight, where it removes facets that don't apply to the set you have selected.  None of your results are "Registered within 7 days or "Registered within 30 days". Which are the queries we have preset for that facet. https://github.com/sul-dlss/argo/blob/master/app/controllers/concerns/date_facet_configurations.rb#L15-L16

**Comment by ryunleeuu** [comment]
Thanks @jcoyne. I'm trying to test it by registering a new item that needs to be done soon anyway, but it's stuck in Unknown Status. I need to wait and check in about it with others and circle back later.

**Comment by ryunleeuu** [comment]
That seems to be correct--the "Registered" facet shows up because of the new item I registered yesterday. I think this can be closed. Thanks again!
