### ISSUE TITLE
virtual-merge reworked as activejob implementation - part one

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#1458]
~~pre-req:  #1451~~

(note:  hooking this up to the UI will be ticketed separately)
Part one of #1323

Assumptions:
- user will upload spreadsheet (or list of druids?) via UI -- parent and child objects already open for modification
  - the list of child druids provides the child objects in the order in which they should appear in the parent object
  - parent object can be separate on form or in uploaded list (?) <-- design here?

Work:
- [x] functionality ported over to new ActiveJob from virtual-merge script:
  - possibly make a "virtual-merge" service, with tests, that the activejob calls?
  - [x] (parent) build virtual composite object contentMD
      - [x] running the script should completely replace the contentMD for the parent object, not append to it (if not the first time the virtual object has been created)  (so it's as if --purge option is always used)
      - [x] contentMetadata for the parent object points each resource to child external file content, in order of children on spreadsheet.
  - [x] (children) insert RELS-EXT isConstituentOf element in child objects
     - [x] all child objects must already be in an accessioned state and not dark or citation-only (is `allows_modification?` sufficient for this?)
  - [x] write tests for what were the run and merge methods in the script

- [x] close open objects (parent and children) (close version, which *should* kick off accession workflow for each object closed)

##### what do we do with the output?
- In the absence of other info:  let's do something similar to other async jobs
- Lingering questions output questions
  - how provide feedback back to user?  (modsulator - creates separate log file;  send email? ?? what else is done?)
  - if immediately fails
  - if individual child objects fail
  - if everything ran successfully

**Comment by ndushay** [comment]
@jcoyne confirming delayed_job means there is no redis hookup or other tasks needed for this ...

**Comment by jcoyne** [comment]
@ndushay it's using activeJob, so it doesn't care what the underlying job processor is (currently set to delayed_job)

**Comment by ndushay** [comment]
sure, but if it were using resque for activejob, there would be other setup required ... just making sure I don't need to add a ticket I didn't think of ...

**Comment by ndushay** [comment]
Per Storytime Tues Aug 13, 2019:

We will be implementing this ticket effectively as it stands:
- ActiveJob can expect a single parent druid and array of child druids  (this is phase 1 implementation)
- output:  using the same log file and argo screens as other bulk actions is the desired outcome.

**Comment by ndushay** [comment]
This ticket should not be closed until virtual-merge filters out dark / citation only objects #1464 -- WIP.  (Dark objects are ready)

**Comment by ndushay** [comment]
I think what remains for virtual-merge is ticketed elsewhere:
- [ ] #1464  ensure object is not dark or citation-only
- [ ] #1463  create/hook up UI to bulk action
  - [ ] UI design needed???
  - [ ] PO will vet after this is ready

If you agree, @jcoyne, you may close this ticket.

**Comment by jcoyne** [comment]
Agreed
