### ISSUE TITLE
make "prepare objects" (open a new version) bulk update (sync) action into bulk action (async)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#1465]
basically, re-implement as activejob.

- @astridu or @andrewjbtw or someone -- will we keep the button name "Prepare objects"?
  - do we want to keep the extra descriptive text?  If so .. how do in UI?
- @andrewjbtw -- will we keep the bulk update (sync) action, or will it go away?
- @andrewjbtw -- how will users provide druids?
  - Search results
  - Pasted list
  - Upload csv
  - Other
  - All of the above?

from:  https://argo.stanford.edu/bulk_actions/new

![image](https://user-images.githubusercontent.com/96775/62907346-a1f3e280-bd27-11e9-9a2c-b8bcd8767021.png)

**Comment by andrewjbtw** [comment]
Answering the questions above:

- keep the existing language "Prepare objects" in the button label
  - the descriptive text can go under the row of buttons, following existing behavior for other bulk actions -- for example:

![bulk-action-label-description](https://user-images.githubusercontent.com/8975583/63201175-f0132980-c038-11e9-929d-df72afe490a8.png)

- input options: "populate with previous search" button plus a text box, following the examples for "Download descriptive metadata" and "Reindex"
  - if we change the input options to include CSV or spreadsheet input that will be a separate ticket

- add this option to the existing row of buttons
  - in the long run we will probably go to a dropdown menu for all the bulk actions, but that will be a separate design ticket and should not hold up this work

- we can remove the bulk update (sync) option -- I can't think of a reason to have both methods and I don't see any other bulk operations that exist in both categories
