### ISSUE TITLE
argo build is failing

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#1469]
it seems like this is an issue with argo's dor-services-client and dor-workflow-client needing a token that the test dor-services-app instance sees as valid.  that instance is spun up by docker-compose.

**Comment by jcoyne** [comment]
Can we do `docker-compose dor-services-app run rake generate_token`?

**Comment by mjgiarlo** [comment]
@jcoyne I don't think we can because that rake task blocks expecting user input.  

I'm working on a fix here: https://github.com/sul-dlss/argo/pull/1468/files

**Comment by jcoyne** [comment]
```
$ docker-compose run dor-services-app rake generate_token
WARNING: The SECRET_KEY_BASE variable is not set. Defaulting to a blank string.
Account name: Foo
Your token:
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGb28ifQ.-BVfLTW9Q1_ZQEsGv4tuzGLs5rESN7LgdtEwUltnKv4
```

**Comment by mjgiarlo** [comment]
@jcoyne Sorry, I thought you meant wiring up docker-compose to do that at runtime. Is that token safe to persist in docker-compose.yml? (I assume so since our server instances use a different HMAC secret.)

**Comment by jmartin-sul** [comment]
that seems safe to me to persist, and to leave in public view.  if the real servers are using a different secret for signing, then this token shouldn't be valid on them, right?

**Comment by jmartin-sul** [comment]
unassigned myself, as i did no real work on this issue 😄

**Comment by jmartin-sul** [comment]
hopefully our secret key base IRL is better than blank string 😆
