### ISSUE TITLE
Investigate why collections are not showing in collection drop-down lists

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#1490]
Investigation needed to address #1428 

### Describe the problem
Some (all?) newly created collections are not showing up in the list of collections for the Bulk Update "Set Collection" or Item View "Edit Collection" tasks.

### Investigation needed
The drop-down menus that show the list of available collections for adding (both on the item detail page and in the bulk actions page) are built from Solr, as shown here:

https://github.com/sul-dlss/argo/blob/master/app/models/concerns/permitted_queries.rb#L52-L76

This code filters the collections in Solr based on which APOs the logged in user has permissions to access.  There is a method in that same class linked to above called `#permitted_apos` that does this.  The `#permitted_apos` appears to be used in other ways, so if that contains a bug, it may be causing unknown issues elsewhere (or perhaps this suggests it is unlikely there is any problem with `#permitted_apos` if other issues have not been reported regarding viewing of APOs/permissions).

The drop-down menu for the item detail page "Edit collections" modal window is rendered here: 
https://github.com/sul-dlss/argo/blob/master/app/views/items/_collection_ui.html.erb#L22

The drop-down menu for the Bulk Actions "Set collection" is rendered here:
https://github.com/sul-dlss/argo/blob/master/app/views/report/bulk.html.erb#L111

Both use the same `#permitted_queries` method on the `user` model.

The `user` model called in the view code delegates the called to `#permitted_queries` to the `permitted_queries` class linked to above here:
https://github.com/sul-dlss/argo/blob/master/app/models/user.rb#L34

### Four possibilities suggested by Peter for investigation:

- look at the indexing code in `dor-services` gem, possibly in https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/rights_metadata_ds.rb#L139-L204 to
-- **Are we correctly identifying APO permissions when creating Solr docs?**
-- **Is indexing correctly tying collections to APOs when creating Solr docs?**
- **Are there problems with the particular roles certain people are in** (i.e. not a bug in the code, but incorrect roles management)**?**
- **Is there some bug in the argo code** (in `#permitted_queries` that constructs the Solr query that is doing the filtering) **that is perhaps not filtering correctly?**

If you find a problem, feel free to fix it or to make fixing it a separate github issue - your choice.

<hr/>
NOTE:  the code that returns a list of collections for the "add collection" drop-down menus (the bug per above) is different from the code that returns a list of collection on the *item registration page*.  For item registration, you only see collections governed by the APO selected on the registration page.  That code is here:

https://github.com/sul-dlss/argo/blob/master/app/controllers/registration_controller.rb#L35-L64

For collections to show up in this list, they need to be in the `administrativeMetadata` datastream under the `<registration>` node.

**Comment by peetucket** [comment]
From an item detail page in Argo, this is the blue button to set the collection:

![Roger_Howe_Professorship__Stanford__Calif____20____-_Argo_1](https://user-images.githubusercontent.com/47137/63609514-1c283080-c58c-11e9-863a-812b7f5378e7.png)

The blue button opens a window pane which has the drop-down menu with the list of collections.  This is the drop-down menu that is missing collections:

![Roger_Howe_Professorship__Stanford__Calif____20____-_Argo](https://user-images.githubusercontent.com/47137/63609543-2813f280-c58c-11e9-8379-3ff1128eb3f6.png)

The same drop-down (built in the same way) is available "Bulk Update" operations when you listed druids, and then click the "Set Collection" action:

![Argo_Search_Results](https://user-images.githubusercontent.com/47137/63609658-5b568180-c58c-11e9-8bcf-5ba9d1ebf69a.png)

**Comment by justinlittman** [comment]
See https://github.com/sul-dlss/argo/issues/1428#issuecomment-526262343

Just want to say, wow, this research was really thorough @peetucket.
