### ISSUE TITLE
Are we using memcache for anything in argo?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#153]
Seems like we have dalli configured for memcache in argo. Is that being used anywhere?

**Comment by mejackreed** [comment]
Check this out: https://github.com/sul-dlss/argo/blob/develop/app/controllers/status_controller.rb#L30-L43

**Comment by jmartin-sul** [comment]
so i've never used memcache or rails caching, but there are a couple more uses of `Rails.cache` in the app (specifically `value_helper.rb` and `dor_object_helper.rb`):

https://github.com/sul-dlss/argo/blob/develop/app/helpers/dor_object_helper.rb#L173
https://github.com/sul-dlss/argo/blob/develop/app/helpers/value_helper.rb#L6

and then something in the configs setting an event for cache resets?  creating a clear cache for new passenger threads?
https://github.com/sul-dlss/argo/blob/develop/config/environment.rb#L9

**Comment by mejackreed** [comment]
Hmm... thats interesting in the passenger config. Well putting this off for now.

**Comment by drh-stanford** [comment]
This is related to Dalli. Looking into it...

**Comment by drh-stanford** [comment]
we removed the Dalli configuration and passenger looks clean.
