### ISSUE TITLE
Use dor-services-client to modify the embargo date (and add associated event)

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#1538]
Depends on https://github.com/sul-dlss/dor-services-client/issues/84

This is the code that should be replaced by a call to `Dor::Services::Client`: https://github.com/sul-dlss/argo/blob/master/app/controllers/items_controller.rb#L132-L133

**Comment by jcoyne** [comment]
Unblocked https://github.com/sul-dlss/dor-services-client/pull/85

**Comment by jcoyne** [comment]
This work is complete.
