### ISSUE TITLE
Improve user experience if refresh_metadata gets an error in symphony response

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#1545]
(part of uber ticket sul-dlss/common-accessioning#188)

https://github.com/sul-dlss/dor-services-app/pull/358 means dor-services-app will return an HTTP 500 error if it receives the wrong number of bytes from Symphony:

after hitting "Refresh Metadata" button in left "nav" for an existing item:

### Argo UI:

![image](https://user-images.githubusercontent.com/96775/64038464-f0b5c080-cb0c-11e9-831f-ce8a7274fa69.png)

This is probably not the best user experience.  Something super simple: keep the same error page, but change the text
- to have the specific error message:  "Dor::Services::Client::UnexpectedResponse (Internal Server Error: 500 (Incomplete response received from Symphony for 111 - expected 1960 bytes but got 1965))", where 111 is the ckey.
  - could add the druid
  - could "sweeten" the error message for an end user
  - etc.

**Comment by ndushay** [comment]
user is in single object view, clicking "refresh metadata" blue button before error:

![image](https://user-images.githubusercontent.com/96775/64287791-7d012280-cf15-11e9-8e51-0b89acc026f7.png)

**Comment by astridu** [comment]
Design option 1: Update text in existing error message. @andrewjbtw what do you think of the error message?
![image](https://user-images.githubusercontent.com/42216982/64291653-8ee6c380-cf1d-11e9-8ab3-8d06b0cf1b1e.png)

Design option 2: Open error in dialogue box.
![image](https://user-images.githubusercontent.com/42216982/64291706-ae7dec00-cf1d-11e9-8c2e-5ed0187dd572.png)

**Comment by andrewjbtw** [comment]
I prefer the dialogue box, as it's easier to read and doesn't load a new page.

For the contact message, there are multiple SDR-related slack channels. The sdr-operations channel would be the most appropriate for this situation, so please direct them to that one.

**Comment by ndushay** [comment]
It turns out it's easy to do this approach, so I will adjust the message per Astrid's suggestion.

![image](https://user-images.githubusercontent.com/96775/64378593-e484a400-cfe1-11e9-96fb-fffeb1cc1c59.png)

**Comment by andrewjbtw** [comment]
I think that's acceptable, given that banner is already used for other messages. I like the idea of suggesting they retry, if it turns out this was just a temporary error.
