### ISSUE TITLE
Cleanup unused registration logic around metadata source

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#1548]
Now that we have removed the metadata source drop-down menu (there is no need for it anymore), we should also clean up all the logic having to do with checking the metadata source in the register.js.erb file: https://github.com/sul-dlss/argo/blob/master/app/assets/javascripts/registration/register.js.erb#L129-L179

**Comment by peetucket** [comment]
See #1257 and #1258

**Comment by jcoyne** [comment]
I believe this work is complete.
