### ISSUE TITLE
hound wants us to prefer after_action over after_filter

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#156]
Here and here specifically:

https://github.com/sul-dlss/argo/blob/develop/app/controllers/apo_controller.rb#L7
https://github.com/sul-dlss/argo/blob/develop/app/controllers/items_controller.rb#L13

as far as I can tell they are identical so maybe this is a deprecation issue with Rails 4?

**Comment by mejackreed** [comment]
Yes `after_filter` is deprecated: http://apidock.com/rails/AbstractController/Callbacks/ClassMethods/after_filter

**Comment by atz** [comment]
I changed this in apo_controller on a topic branch.

**Comment by mejackreed** [comment]
:+1: @atz
