### ISSUE TITLE
Hierarchical facet UI is confusing

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1574]
<img width="216" alt="Screen Shot 2019-09-06 at 2 22 10 PM" src="https://user-images.githubusercontent.com/92044/64454899-cb4b2880-d0b1-11e9-9778-d4d0e2cce3ee.png">

It's displaying the triangle pointing down (i.e. DMM), but there are no levels of hierarchy under these facets -- they are leafs.

**Comment by andrewjbtw** [comment]
This is still a valid ticket but putting in the backlog since it might not be relevant after the upgrade to Blacklight 7.

**Comment by jcoyne** [comment]
Agreed, this is fixed in blacklight 7
