### ISSUE TITLE
[argo/prod] Notice: Unable to find title of the collection druid:jj449jt3139 in Solr. Checking Fedora, but this is slow.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1590]
This is because the solr record for this collection does not have a `sw_display_title_tesim` field.
Which is because the mods_display doesn't return one:
```
> col = Dor::Collection.find( 'druid:jj449jt3139')
> col.stanford_mods.sw_title_display
=> nil
```

Which is because the object has no descMetadata datastream.

## Backtrace

    line 49 of [PROJECT_ROOT]/app/controllers/registration_controller.rb: block in collection_list
    line 38 of [PROJECT_ROOT]/app/controllers/registration_controller.rb: each
    line 38 of [PROJECT_ROOT]/app/controllers/registration_controller.rb: collection_list

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/54082399)

**Comment by andrewjbtw** [comment]
This object has never been accessioned, so it should not be releasable. It does not have a PURL yet, and has not completed the accession workflow. It looks like it stalled at accessioning in March 2019, but it's not clear why.

**Comment by jcoyne** [comment]
@andrewjbtw should non-accessioned collections show up on the list of collections in that you can register into?

**Comment by jcoyne** [comment]
@andrewjbtw ping ☝️

**Comment by andrewjbtw** [comment]
I don't think so. It seems like the collection needs to exist as an accessioned object before you can add to it.

@blalbrit Are there ways to create collections at the same time as creating objects to register into those collections -- before the collection is accessioned? It seems like the collection needs to exist first.

**Comment by aaron-collier** [comment]
@jcoyne this particular instance works now:

```
[1] pry(main)> col = Dor::Collection.find( 'druid:jj449jt3139')
=> #<Dor::Collection pid: "druid:jj449jt3139", admin_policy_object_id: "druid:yf767bj4831">
[2] pry(main)> col.stanford_mods.sw_title_display
=> "Stanford University, Department of Art and Art History, Documentary Film Program, motion pictures"
[3] pry(main)>
```

Is this an issue that can be closed or a larger issue that needs to be addressed?

**Comment by andrewjbtw** [comment]
Honeybadger says this error hasn't recurred since February, when I got the druids that were generating this error accessioned. I think there is potentially a larger issue here, but I'd rather address it under another ticket if it recurs.
