### ISSUE TITLE
remove virtual merge bin script - needs SDR manager approval

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#1596]
Since we added virtual merge as a bulk action to Argo, there is no need for the script in the bin directory.  

However, since we didn't leave Andrew a lot of time to shake down bugs with virtual merge, we want to keep the script version around for a bit, just in case.

If @andrewjbtw hasn't given his explicit approval to remove the script before Nov 2019, we can re-surface the question to him at that point or later.

Huzzah for less code to maintain;  huzzah for self-service for virtual object creation.

**Comment by mjgiarlo** [comment]
@andrewjbtw feel free to drop a comment on this issue once you are feeling confident that the virtual object creation UI is working, and we can move forward with decommissioning and removing the virtual-merge script.

**Comment by andrewjbtw** [comment]
With virtual objects running at a large scale via the Argo UI, I think we can now retire this old script.
