### ISSUE TITLE
Don't look in fedora for workflow templates

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1602]
They are managed in workflow-server-rails and there are methods in dor-workflow-client to access the necessary properties.
- [x] https://github.com/sul-dlss/argo/pull/1601
- [x] https://github.com/sul-dlss/argo/pull/1597
- [x] https://github.com/sul-dlss/argo/blob/master/app/controllers/report_controller.rb#L103
- [x] Remove workflow template object from fixtures
  - `fedora_conf/data/tm388wy6148.xml`
  - `fedora_conf/data/fy957df3135.xml`
- [x] Remove workflow template objects from dor-services-app https://github.com/sul-dlss/dor-services-app/blob/master/lib/tasks/seeds/druids (maybe leave just 1 to show that the indexer still works)

**Comment by andrewjbtw** [comment]
I think this may have been done. We don't look for the templates in Fedora anymore but I don't know if the last two items in the checklist have also been done.

**Comment by jcoyne** [comment]
This is totally complete.
