### ISSUE TITLE
[argo/stage] Dor::WorkflowException: Failed to retrieve resource: get https://workflow-service-stage.stanford.edu//workflow_templates/sdrRecoveryWF (HTTP status 500)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1617]
## Backtrace

    line 114 of [PROJECT_ROOT]/app/controllers/workflows_controller.rb: workflow_processes
    line 108 of [PROJECT_ROOT]/app/controllers/workflows_controller.rb: build_show_presenter
    line 21 of [PROJECT_ROOT]/app/controllers/workflows_controller.rb: block (2 levels) in show

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/54926229)

**Comment by jcoyne** [comment]
This is appearing because when Andrew exported from prod and imported to stage, the datastream content is now returning something other than what is as the dsLocation of the external datastream.  That is, doing:
```
 item = Dor::Item.find('druid:xs835jp8197')
item.workflows.content
```

is giving a different result than fetching this url:

```
item.workflows.dsLocation
# => "https://lyberservices-prod.stanford.edu/workflow/dor/objects/druid:xs835jp8197/workflows"
```

**Comment by jcoyne** [comment]
I believe we could make this problem go away by adjusting the indexer to use the workflow client rather than the datastream.

**Comment by aaron-collier** [comment]
```
[4] pry(main)> item.workflows.content
NoMethodError: undefined method `workflows' for #<Dor::AdminPolicyObject:0x0000000005d0cb18>
from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activemodel-5.2.4.2/lib/active_model/attribute_methods.rb:430:in `method_missing'
[5] pry(main)> item.workflows
NoMethodError: undefined method `workflows' for #<Dor::AdminPolicyObject:0x0000000005d0cb18>
from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activemodel-5.2.4.2/lib/active_model/attribute_methods.rb:430:in `method_missing'
```

Is this still valid?

**Comment by jcoyne** [comment]
no, we've fixed this by removing the workflow datastream.
