### ISSUE TITLE
Error:  reset-workspace : undefined method `local_export_home' for nil:NilClass is blocking items from completing accessioning

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1649]
**Describe the bug**
Since this morning (2019-09-19), items in the accessioning workflow have errored out at the reset-workspace step in the accessionWF with the following error:

```
reset-workspace : undefined method `local_export_home' for nil:NilClass
```

**User Impact**
This error appears to be blocking all accessioning and reaccessioning from being completed.

**To Reproduce**
1. Run an item through the accession workflow
2. If it doesn't hit a different error first, it's likely to get caught at reset-workspace

A search for items caught at that workflow step:
https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=accessionWF%3Areset-workspace%3Aerror

**Expected behavior**
Accessioning completes as expected.

**Comment by justinlittman** [comment]
I believe this is fixed by https://github.com/sul-dlss/common-accessioning/pull/406. This change has been deployed to stage and prod. @andrewjbtw please verify the fix.

**Comment by jcoyne** [comment]
The HB alert was: https://app.honeybadger.io/projects/52894/faults/55053400

**Comment by andrewjbtw** [comment]
Closing this as it has been fixed.
