### ISSUE TITLE
Predictive Text for Tags on registration form

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#165]
When a user is on the registration page, they have currently have 4 tag boxes that they can interact with. The number of potential tags is overwhelming, so the user desire is to have auto-complete enabled so that they can quickly filter down to a desired tag or tag set. This would be similar to the functionality in the project tag box.

**Comment by blalbrit** [comment]
Suggest backlogging this until a future iteration of Argo can address user interface/experience needs wholistically.

**Comment by andrewjbtw** [comment]
Edited the title to clarify that this is for the registration form. A separate ticket could apply to the "edit tags" interface if we want to apply the predictive text to all individual tag edits.
