### ISSUE TITLE
 Attempts to close versions are leading to the library system status page

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1655]
**Describe the bug**
Attempts to close objects that should be closeable are leading to a system status page.

**User Impact**
It's not possible to close objects after making changes.

**To Reproduce**
1. Go to any object that can be closed.
2. Click on close version and attempt to close the version.
3. See the library system status page

**Expected behavior**
The object can be closed.

**Comment by jcoyne** [comment]
Andrew said on slack this is fixed.
