### ISSUE TITLE
Version open/close should handle errors

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1656]
**Describe the bug**
Currently it raises `Dor::Services::Client::UnexpectedResponse` which redirects to the system status page.  Instead catch this error and display the error message to the user

The error message looks like this:
```
Dor::Services::Client::UnexpectedResponse: Unprocessable Entity: 422 ({"errors":[{"status":"422","title":"Unable to close version","detail":"accessionWF already created for versioned object druid:cg610np3550"}]})
```

**Comment by andrewjbtw** [comment]
I think we've covered this now. Closing because it hasn't been reported in a long time and the open/close logic now should prevent the link to open from becoming active if opening will not succeed.
