### ISSUE TITLE
Attempting to view files from an individual object page in Argo returns "network error"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1669]
**Describe the bug**
Since Monday (9/23), many links to files at the bottom of individual Argo pages have been returning a modal with the message, "Network Error". 

I've done some investigating and the problem looks specifically related to whether or not a file has a "preserved" version.

This is the result I get when I click on a file that has "preserve" as a status, with or without "publish" and "shelve":

![Screen Shot 2019-09-24 at 10 19 26 AM](https://user-images.githubusercontent.com/8975583/65535006-6e26e380-deb5-11e9-8488-fa54461f5086.png)

This is the result I get when I click on a file that has only "publish" and "shelve":

![Screen Shot 2019-09-24 at 10 21 56 AM](https://user-images.githubusercontent.com/8975583/65535083-99a9ce00-deb5-11e9-8898-74160b0ebe8f.png)

In this case, the JP2 is available and downloadable from Stacks. 

**User Impact**
Users are not able to download copies of files that have "preserved" versions. Access to self-service downloads is an important part of many workflows.

**To Reproduce**
1. Go to the page for an individual druid that contains files.
2. Click on the link to any file that has a "preserve" indicator.
3. See the "Network Error"

**Expected behavior**
The modal that allows the user to select a link to download should appear.

**Additional context**
This looks like the corresponding honeybadger error: https://app.honeybadger.io/projects/49894/faults/55148725

**Comment by jmartin-sul** [comment]
it appears that this was fixed by #1672.  if it appears that's not the case, feel free to reopen.
