### ISSUE TITLE
Create a collection action doesn't update fields when radio button for 'from Symphony' is pressed

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/argo#1677]
Steps to reproduce:

1) Navigate to an APO (i.e. https://argo.stanford.edu/view/druid:mq437xz1554)

2) Click on 'Create Collection' blue button

3) Click on radio button for 'Create a Collection from Symphony'

The fields for 'Create a Collection from Title/Abstract' do not update with the new selection.

**Comment by andrewjbtw** [comment]
This issue looks like a recent regression. The code for the "create a collection from Symphony"  option is in the HTML page source, but clicking on the radio button isn't exposing it to the interface. 

The expected view, after clicking "Create a Collection from Symphony" is:

![Screen Shot 2019-09-26 at 2 13 52 PM](https://user-images.githubusercontent.com/8975583/65726250-8475a080-e069-11e9-8cfa-fbb1cc6bb5d5.png)
