### ISSUE TITLE
Running a report (in the view or download) where you enter in dates produces no results

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#1694]
**Describe the bug**
Faceting on specific date ranges produces no results in the report view.

**User Impact**
Users can't download specific date range reports.

**To Reproduce**
Select a date facet (such as "Earliest Accessioned") and then enter manual dates in the fields (e.g. 2019-10-01 and 2019-10-02).  Click Submit and you will get a results view with results, e.g.

https://argo.stanford.edu/catalog?f%5Baccessioned_earliest_dttsi%5D%5B%5D=%5B2019-10-01T00%3A00%3A00.000Z+TO+2019-10-02T23%3A59%3A59.000Z%5D

Then select "Report view" and you will get an empty grid and nothing to download.

**Expected behavior**
We should get the same results in the grid view

**Additional context**
perhaps related to #1693 which changed how the report view search results are build by leaving off faceting ?

**Comment by jcoyne** [comment]
@peetucket probably because the `ReportSearchBuilder` doesn't run `add_date_field_queries` as the `SearchBuilder` does

**Comment by peetucket** [comment]
will try that, but interestingly enough, a manual query seemed to work in stage and produce results:

https://argo-stage.stanford.edu/report?commit=submit&f%5Baccessioned_earliest_dttsi%5D%5B%5D=%5B2018-10-01T00%3A00%3A00.000Z+TO+2019-10-01T23%3A59%3A59.000Z%5D&f%5Bexploded_tag_ssim%5D%5B%5D=Process&utf8=%E2%9C%93

same query in -prod is empty
