### ISSUE TITLE
Blue Button to "Update Embargo" has disappeared from Record View page in Argo

### ISSUE THREAD

**Issue by caaster** [sul-dlss/argo#1699]
**Describe the bug**
There used to be a blue button in Argo on the record view page, called "update embargo." It has disappeared recently (I don't know when it disappeared; I just noticed today that it is gone.)

Here is how it worked:

1) Navigate to record view page in Argo
2) Open new version
3) Select "update embargo button"
4) Select new date from calendar menu
5) Close version

I use this feature to update ETD embargoes on a per-object basis, which is how those requests are received and need to be acted upon. In other words, this is never a bulk action, but rather an action that needs to occur on a per-object basis.

**User Impact**
This is not a blocker because I know how to update the embargo metadata datastream manually, but having the button saved me a lot of time and prevented manual xml editing  errors. It has been in existence since prior to 2014, and was created during the time Hannah was ETD service manager. 

**To Reproduce**
Not applicable in this case as the blue button is gone.

**Expected behavior**
Already stated above.

**Screenshots**
No applicable.

**Additional context**
Please reinstate this feature wherever it would work best to do so for the dev team, where I can easily access it.

**Comment by andrewjbtw** [comment]
Related consul documentation from when this button was in the interface: https://consul.stanford.edu/display/ETD/ETD+Embargo+Change+Requests

**Comment by jcoyne** [comment]
The "Update Embargo" button only appears for Items (not collections) and only for items currently under embargo: https://github.com/sul-dlss/argo/blob/ff24e233d6c55059eeea5caaa3dd311c169236b2/app/presenters/buttons_presenter.rb#L89

Does the item you are looking at meet both conditions?

**Comment by caaster** [comment]
Yesterday I was looking at an item in Argo that was embargoed, so I could demonstrate to Michael Olson how to update an embargo. The blue button was not displaying. I selected the item from the ETD APO, Stanford only rights facet. This morning, I checked, and for example, found this embargoed ETD, which does have the blue button displaying: https://argo.stanford.edu/view/druid:bf828xw5211. So I am mystified. I will poke around to look at other embargoed ETDs and report back.

**Comment by jcoyne** [comment]
@caaster do you have an update on your investigation?

**Comment by jcoyne** [comment]
@caaster can this be closed?

**Comment by jcoyne** [comment]
@caaster is this issue still relevant?
