### ISSUE TITLE
Reset link is not working

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1704]
When @oceanofsound tries to reset things in the workflow status the system returns a 403 (forbidden) response, but he doesn't see any indication that it isn't allowed.  Furthermore he shouldn't be forbidden from using this link.

**Comment by jcoyne** [comment]
Caused by
https://github.com/sul-dlss/argo/blob/master/app/controllers/report_controller.rb#L65

Introduced in https://github.com/sul-dlss/argo/commit/17ed7a8b95174febc4643c83dab3b43f48a40efc

**Comment by andrewjbtw** [comment]
The options are:

1. Leave as it currently is and only admins can reset from the workflow grid. This effectively takes away an option non-admins previously could use.
2. Check permissions on each item in a set and allow reset if the user has the appropriate permissions. This could slow down the operation of the workflow grid considerably.
3. Remove restrictions from this one setting and allow all users to use it.

My vote is for option 2, but if the performance makes it unacceptable, then I vote for option 3. 

Users' view of the workflow grid is restricted by workgroup and APO settings, so there are already limits on the scope of what they are able to see. A reset is simply a re-run of the step currently in error and will either resolve the issue or return the object to an error state.

**Comment by jcoyne** [comment]
@andrewjbtw what are the performance characteristics that are required for #2 to be feasible.

**Comment by jcoyne** [comment]
@andrewjbtw considering that the results are already constrained by workgroup and APO, why don't we just remove the restrictions?

**Comment by andrewjbtw** [comment]
If you're ok with it, I'm ok with it. Let's go with option 3.

**Comment by jcoyne** [comment]
I looked into it a little more, that report would allow you to reset everything you have *view* access to. But we really want to restrict to what you have *manage* access to.

**Comment by andrewjbtw** [comment]
Yes, that's true. So it's a question of how much difference there is between what people can view and what they can manage. I don't know how to gather that information.

**Comment by andrewjbtw** [comment]
I suspect that the difference for most people is small, except for people who have only view rights and no manage rights. But that's just my guess based on what I see on the few occasions where I've given people new Argo permissions.

**Comment by jcoyne** [comment]
@oceanofsound is this fixed for you?

**Comment by andrewjbtw** [comment]
I think this was fixed last fall. Closing.
