### ISSUE TITLE
Create better tests for the bulk update page

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#1717]
We have a number of buttons that trigger bulk updates that are currently untested.  Until and unless we have move these to bulk actions, we may want to have tests.  We have run into a couple bugs that have slipped through (eg. #1715)

**Comment by jmartin-sul** [comment]
my (unsolicited) $0.02:  i would lobby for us to strongly prefer porting any given thing we might test to bulk actions, and then writing the test.  i think it'll be easier to write tests around bulk actions than around the old bulk update page, and bulk actions is way more robust (bulk update is one of the cruftiest things in argo).

of course, if it's super easy to just write a test for a particular bulk update as it exists, i guess that couldn't hurt.  but as much as i hate to see untested code in use, i'd also hate to see us entrench the old bulk update mechanism even more.

**Comment by andrewjbtw** [comment]
We ported all updates to actions.
