### ISSUE TITLE
setting RAILS_ENV after Rails has loaded only creates misinformation

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#172]
we should remove lines that set RAILS_ENV like so:
```ruby
ENV['RAILS_ENV'] = 'test'
```

e.g.:  https://github.com/sul-dlss/argo/blob/70416658b95549881c847cf01f4b06a6775ed7d1/lib/tasks/argo.rake#L20

not sure if we do this elsewhere, but we shouldn't do it anywhere.  note that doing `Rails.env = ` is no better.  neither actually reloads the environment.  all the old configuration stays in place, though `Rails.env` and `ENV['RAILS_ENV']` will misreport the loaded environment as the name that was given in the "reset".

for the specific issue seen in the rake task, we should do something like:
```ruby
if Rails.env.test?
  # run ci tests
else
  system('rake ci RAILS_ENV=test')
end
```

more explanation on that proposed fix in the comment where @mejackreed suggested it:  https://github.com/sul-dlss/argo/pull/114#issuecomment-154270331

and the comment where i explained my testing in a bit more detail: https://github.com/sul-dlss/argo/pull/114#issuecomment-156216601

in the meantime, no harm in merging PR #114, which partially addresses the situation (and which spawned this investigation).

**Comment by mejackreed** [comment]
:+1:

**Comment by atz** [comment]
:+1:
