### ISSUE TITLE
Items in the process of accessioning when new steps were added to AccessionWF are not completing accessioning

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1723]
**Describe the bug**
Items that were in the process of accessioning when the "shelve-complete" and "publish-complete" steps were added to the accessionWF now show blank lines where those steps should be:

<img width="901" alt="Screen Shot 2019-11-06 at 1 31 06 PM" src="https://user-images.githubusercontent.com/8975583/68342569-beda5080-009f-11ea-9437-67446db9b087.png">

These steps cannot be set to complete from Argo. Clicking on the "set to completed" link leads to a blank page.

**User Impact**

This issue may be preventing items from being accessioned. It is hard to tell if these incomplete workflow steps are the problem because items do not get caught at the blank steps, but fail at other points in time.

Example: Item cannot be reaccessioned

This item had a version mismatch error when the new workflow steps were added: https://argo.stanford.edu/view/druid:kt615pj8918 I cleared the error and the item seemed to have completed accessioning, but it is now failing at reaccessioning using preassembly.

Even though it looks like the object can be opened and updated and then closed, reaccessioning via preassembly results in the following error: https://app.honeybadger.io/projects/52900/faults/56798035

The workflow database shows all steps in the object as complete, but the AccessionWF must not be getting set to complete, preventing the object from being closed. It looks like preassembly made a partial update, as the object in Argo has an updated contentMetadata that differs from the contentMetadata stored in preservation core for the previous object version.

Example: Item does not complete accessioning

Other items that had been in error states when the new workflow steps were added are not completing accessioning even after the errors have been resolved. These two druids have now successfully passed the stage where they experienced an error (sdr-ingest-transfer) but are not moving further through the accessionWF:

Version mismatch error resolved: https://argo.stanford.edu/view/druid:bb043ww5756
Checksum error resolved: https://argo.stanford.edu/view/druid:nk441zn4775

In both of these examples, the items have stalled at reset-workspace, not at the step where they originally ran into errors.

**Expected behavior**
Objects complete accessioning if they do not encounter additional errors. If they are subsequently reaccessioned, the next time they go through the accessionWF they will have the new workflow steps.

**Additional context**
This problem does not seem to affect new items (created after the steps were added) or items that were not in the actual process of being accessioned when the steps were added. I have successfully reaccessioned items that were in an "Accessioned" state following the addition of the new workflow steps. I have only encountered problems with objects that were in accessioning when the steps were added.

**Comment by jcoyne** [comment]
@andrewjbtw I think we're conflating at least 2 issues here.

I looked at `druid:kt615pj8918` and it should not currently get this error: https://app.honeybadger.io/projects/52900/faults/56798035 because that happens when the following workflow call returns `true`:

```ruby
Dor::Config.workflow.client.active_lifecycle('dor', work.pid, 'submitted', version: work.current_version)
```
but currently that returns `nil`.


The workflow table is drawing based on the current template, which has 2 extra steps.  If the object went through the workflow and the workflow didn't have the steps at the time, it's just drawing the blank lines.   The way the table is rendering has no influence on how objects are moving through the workflow.

**Comment by andrewjbtw** [comment]
@jcoyne I changed the title of the ticket because the issue isn't the blanks, it's that items are not completing accessioning. I think the key common feature with these items is that they did not complete the workflow when the steps were added. Objects that went all the way through the workflow before the steps were added seem fine, even if they show blank lines.

I can separate druid:kt615pj8918 into its own ticket because I attempted manual remediation on it so it now looks different than the others. But I just ran preassembly on it again, and it once again ended up with that HB error. Even though when you manually put it in an "Accessioned" state, it looks like it will open, update, and close without a problem.

**Comment by jcoyne** [comment]
Both druid:bb043ww5756 and druid:nk441zn4775 have been fixed.

**Comment by andrewjbtw** [comment]
I made a separate ticket for druid:kt615pj8918 https://github.com/sul-dlss/argo/issues/1725

**Comment by jcoyne** [comment]
This will be fixed by querying everything in an error: https://argo.stanford.edu/catalog?f%5Bexploded_tag_ssim%5D%5B%5D=Project&f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+University+Archives+Scanning&f%5Bwf_wps_ssim%5D%5B%5D=goobiWF&f%5Bwf_wps_ssim%5D%5B%5D=accessionWF%3Asdr-ingest-transfer%3Aerror

then adding the missing publish-complete and shelve-complete

**Comment by andrewjbtw** [comment]
I am closing this as we added the missing steps for these items and set them to completed this morning. There is likely still other data that will need to be fixed as we see it but we have a solution.

**Comment by ndushay** [comment]
@jmartin-sul  will post instructions here.

**Comment by jmartin-sul** [comment]
instructions for adding missing workflow steps:  https://github.com/sul-dlss/workflow-server-rails/wiki/How-to-add-missing-workflow-steps

for posterity, pasting below what we (@jcoyne and @andrewjbtw and i) ran in rails console on wednesday morning to remediate missing steps (this was an iterative process that included some mistakes, so you should likely just do what's suggested in the above wiki link):

```ruby
# remediation stuff we ran morning of wed 2019-11-13

# go through the druids we got in the csv dump of the above solr query results.  find the max version for each druid.  if needed add missing publish-complete step
CSV.foreach('sdr-ingest-transfer-err-druids.csv') do |row|
  puts row.first.inspect
  max_version = WorkflowStep.where(druid: row.first, workflow: 'accessionWF', repository: 'dor').pluck('version').max
  WorkflowStep.find_or_create_by(druid: row.first, workflow: 'accessionWF', version: max_version, process: 'publish-complete', repository: 'dor')
end

# go through the druids we got in the csv dump of the above solr query results.  find the max version for each druid.  if we added a step in a buggy version of our first take on the publish-complete remediation loop, missing a value for repository, fill that in
CSV.foreach('sdr-ingest-transfer-err-druids.csv') do |row|
  puts row.first
  max_version = WorkflowStep.where(druid: row.first, workflow: 'accessionWF', repository: 'dor').pluck('version').max
  bad_step = WorkflowStep.find_by(druid: row.first, workflow: 'accessionWF', version: max_version, process: 'publish-complete', repository: nil)
  bad_step.update(repository: 'dor') if bad_step
  puts 'remediated' if bad_step
end

# go through the druids we got in the csv dump of the above solr query results.  find the max version for each druid.  if needed add shelve publish-complete step
CSV.foreach('sdr-ingest-transfer-err-druids.csv') do |row|
  puts row.first.inspect
  max_version = WorkflowStep.where(druid: row.first, workflow: 'accessionWF', repository: 'dor').pluck('version').max
  WorkflowStep.find_or_create_by(druid: row.first, workflow: 'accessionWF', version: max_version, process: 'shelve-complete', repository: 'dor')
end

# go through the druids we got in the csv dump of the above solr query results.  find the max version for each druid.  if we added a step in a buggy version of the publish-complete loop, missing a value for status, fill that in
CSV.foreach('sdr-ingest-transfer-err-druids.csv') do |row|
  puts row.first
  max_version = WorkflowStep.where(druid: row.first, workflow: 'accessionWF', repository: 'dor').pluck('version').max
  bad_step = WorkflowStep.find_by(druid: row.first, workflow: 'accessionWF', version: max_version, process: 'publish-complete', repository: 'dor', status: nil)
  bad_step.update(status: 'completed') if bad_step
  puts 'remediated' if bad_step
end

# go through the druids we got in the csv dump of the above solr query results.  find the max version for each druid.  if we added a step in a buggy version of the shelve-complete loop, missing a value for status, fill that in
CSV.foreach('sdr-ingest-transfer-err-druids.csv') do |row|
  puts row.first
  max_version = WorkflowStep.where(druid: row.first, workflow: 'accessionWF', repository: 'dor').pluck('version').max
  bad_step = WorkflowStep.find_by(druid: row.first, workflow: 'accessionWF', version: max_version, process: 'shelve-complete', repository: 'dor', status: nil)
  bad_step.update(status: 'completed') if bad_step
  puts 'remediated' if bad_step
end

# so we probably just could have run something like...
workflow_name = 'accessionWF'
step_name = 'shelve-complete'
step_status = 'completed'
CSV.foreach('druids-in-error.csv') do |row|
  druid = row.first
  max_version = WorkflowStep.where(druid: druid, workflow: workflow_name, repository: 'dor').pluck('version').max
  WorkflowStep.find_or_create_by(druid: druid, workflow: workflow_name, version: max_version, process: step_name, repository: 'dor', status: step_status)
end
```
