### ISSUE TITLE
druid:kt615pj8918 has an active accessionWF but all accessionWF steps in the current version are completed

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1725]
**Describe the bug**
I have been trying to reaccession druid:kt615pj8918 but I am not able to close the object. All of the AccessionWF steps show as "completed" in the current version, but in Argo the "Close Version" button is grayed out. 

I tried to close the object using Bulk Action close in order to get an error message explaining why it couldn't be closed. The log says that the object can't be closed because it has an active accessionWF:

```
Closing druid:kt615pj8918 failed Dor::Services::Client::UnexpectedResponse Unprocessable Entity: 422 ({"errors":[{"status":"422","title":"Unable to close version","detail":"accessionWF already created for versioned object druid:kt615pj8918"}]})
```

As far as I can tell from the database, no workflow steps are active (waiting, queued, or error) so this object should be closeable.

**User Impact**
New changes cannot be saved to a new object version.

**To Reproduce**
1. Go to https://argo.stanford.edu/view/druid:kt615pj8918
2. Attempt to close the object

**Expected behavior**
If all the steps in the accessionWF are completed, then the object should no longer have an active accessionWF. It should be possible to close the object and start a new accessionWF.

**Additional context**
There are a few other unusual things about this object:

The versionMetadata shows 3 versions:

![Screen Shot 2019-11-11 at 4 29 57 PM](https://user-images.githubusercontent.com/8975583/68631827-13ffd300-04a1-11ea-9a1f-8a9e07ad43f2.png)

The Argo display shows only versions 1 and 3:

![Screen Shot 2019-11-11 at 4 32 55 PM](https://user-images.githubusercontent.com/8975583/68631840-21b55880-04a1-11ea-855f-389d46f275fd.png)

Note also that for version 3, the "Opened" date is much later than all of the other dates. This happened because I initially thought I could manually close the versioningWF because it looked like the accessionWF was completed. After setting the versioningWF steps to completed, I was able to re-open the object. But instead of opening a new version 4, it re-opened version 3 and then I was unable to close it.

A further confusing thing to consider is that version 3 has not been written to preservation core. Preservation core does have a version 1 and a version 2 -- even though Argo does not show a version 2. The version 2 in preservation does not match the version 3 in Argo, so the difference is more than numbers. In preservation, the content type for version 2 is "image", but in Argo the content type is "book", so the current version has to eventually be written to preservation.

**Comment by peetucket** [comment]
- [ ] remove all workflow rows for v3
- [ ] update the versionMetadata remove v3 stanza
- [ ] see if the object can be made openable
- [ ] open and close to see if this heals the object

if all fails
- [ ] unrelease from searchworks (how?)
- [ ] set rights to dark
- [ ] publish
- [ ] accession as brand new object

**Comment by andrewjbtw** [comment]
This item has successfully completed reaccessioning via Preassembly, so I am ready to close the ticket.
