### ISSUE TITLE
does argo still need to set encoding to utf-8 explicitly?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#173]
the following places in the code explicitly set the encoding to utf-8.  do we still need to do that under ruby 2.2.2?  e.g., i thought i had to do it as a one-off for a test that was failing for me last week (which used a non-ascii char in an `expect` statement), but it turns out i was able to resolve that by switching from ruby 1.9.3 to ruby 2.2.2 (which i should've been using anyway, since we've switched from ruby 1.9.x to ruby 2.x for argo).

```
app/controllers/catalog_controller.rb:# -*- encoding : utf-8 -*-
app/controllers/discovery_controller.rb:# -*- encoding : utf-8 -*-
app/controllers/report_controller.rb:# -*- encoding : utf-8 -*-
app/helpers/apo_helper.rb:# encoding: utf-8
app/helpers/items_helper.rb:# encoding: utf-8
app/helpers/registration_helper.rb:# encoding: utf-8
app/models/solr_document.rb:# -*- encoding : utf-8 -*-
db/migrate/20110820000003_create_searches.rb:# -*- encoding : utf-8 -*-
db/migrate/20110820000004_create_bookmarks.rb:# -*- encoding : utf-8 -*-
db/migrate/20110820000005_remove_editable_fields_from_bookmarks.rb:# -*- encoding : utf-8 -*-
db/migrate/20110820000006_add_user_types_to_bookmarks_searches.rb:# -*- encoding : utf-8 -*-
db/migrate/20150128201043_add_polymorphic_type_to_bookmarks.blacklight.rb:# -*- encoding : utf-8 -*-
spec/helpers/items_helper_spec.rb:# encoding: utf-8
```

i imagine we won't edit the old db migrations, since they're essentially historical artifacts, right?

**Comment by mejackreed** [comment]
Don't think we need them, but don't mind leaving them in. :+1: either way

**Comment by cbeer** [comment]
Nope, Ruby 2 is UTF-8 by default.

**Comment by blalbrit** [comment]
Closing per @cbeer 's response above.
