### ISSUE TITLE
Some items stall during accessioning with no error message and don't restart until the sweeper arrives

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1739]
**Describe the bug**
Occasionally, but frequently enough to be noticeable, an item stalls in accessioning for no apparent reason. 

By "stall" I mean that:

- the object has the status of 'queued' on a workflow step, usually in the assemblyWF or accessionWF
- no work is being done on the object (i.e. it is not being processed in a long-running step)
- no errors are reported to the Argo interface (and probably not in honeybadger) 
- the item does not move to the next step until its status is set back to 'waiting' at its current step

These items usually move on through the rest of the accessioning workflow after being reset either by the sweeper or by a DLSS staff member able to reset workflow steps.

**User Impact**
Waiting 12 hours for the sweeper means splitting work across multiple days that could be done in one day. Sometimes it can mean missing deadlines. It looks like any type of accession can be delayed by this issue. I've seen it happen with:

- new accessions using preassembly
- new accessions using Hydrus
- reaccessions using preassembly
- metadata updates or other modifications made via Argo
- single items accessioned alone
- single items that were part of a batch
- small objects like a single small PDF
- large objects with one or more large files

In two recent cases, Hydrus depositors emailed SDR staff asking for assistance in moving along Hydrus items that were not large in size. In one case the item was just a single PDF. 

In another case, the depositor needed the item accessioned so soon that after a long wait they accessioned the same content under a different druid, resulting in duplicate druids (after the sweeper ran) and a need to decommission the original, stalled druid in order to avoid confusion between the two objects. 

Depositors should be able to rely on Hydrus to accession content at a speed that is relative to the size of their deposited material, particularly when there appear to be no issues with the content or metadata provided that would cause problems with the accessioning process. 

**To Reproduce**
It is hard to intentionally reproduce this, but this honeybadger alert suggests that it happens 50+ times per day during periods of regular accessioning: https://app.honeybadger.io/projects/58890/faults/49707486

This alert is triggered whenever the sweeper encounters a stale workflow step, which I believe refers to steps that have been queued for 12 hours and not in an error state.

**Expected behavior**
Objects continue accessioning unless stopped by an error. They may have to wait in a queue if it's a particularly busy time, but they should not stall completely until reset.

**Additional context**
This is potentially a huge problem for when we scale up for Google Books.

**Comment by mjgiarlo** [comment]
Adding this to first-responder queue. Cc: @vivnwong @peetucket (next up)

**Comment by ndushay** [comment]
if @justinlittman's tweaks to workflows (additional states to distinguish 'queued' from 'started' and so on) address restart problems for long running jobs, we could run the sweeper much more frequently.  We could also .. figure out the real cause of this and fix it.

This never showed up on the first responder spreadsheet, that I could see - at least ... it's not considered an open issue there ... https://docs.google.com/spreadsheets/d/10UmZVCvNoTOi3MzNhoUK72efxKUiXEQ7fcE5nsc6zRo

**Comment by peetucket** [comment]
I think this got overlooked and its absence from the spreadsheet is not on purpose.  Thanks for adding.

**Comment by justinlittman** [comment]
I doubt the changes I made will fix this. However, we've made a few changes that may shed some light on the problem.

**Comment by mjgiarlo** [comment]
@justinlittman where should I look to see said "more light?" thanks!

**Comment by justinlittman** [comment]
I am cautiously optimistic that this has been resolved. Obviously, the proof is in what @andrewjbtw experiences. However, the absence of emails from the sweeper cron job is promising.

**Comment by mjgiarlo** [comment]
I recommend we let this stick around a week or so and then re-assess. @jcoyne - check in on this next Weds or so?

**Comment by andrewjbtw** [comment]
Are we ready to say this is solved? It's been almost a month and it seems to be working.

**Comment by peetucket** [comment]
I'd close it then.

**Comment by mjgiarlo** [comment]
@sul-dlss/infrastructure-team cool to close? :point_up:
