### ISSUE TITLE
Hierarchical facets no longer work as expected

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1750]
**Describe the bug**
Hierarchical facets no longer show an "arrow" icon on the left hand side. Facets do not expand when you click on the icon, but do expand when you click on whitespace to the right of the text.

**User Impact**
It's confusing and counterintuitive. At first it appears that facet expansion has stopped working at all, since nothing happens when you click on the icon. The only sign you can still expand facets is the change in the mouse icon from an arrow to a hand when hovering to the right of the text.

**To Reproduce**
1. Go to Argo
2. Open a facet with hierarchical choices (like Tags)
3. Note that the icon on the left is no longer an arrow
4. Click on the icon and nothing happens
5. Click to the right of the icon and the facet expands

**Expected behavior**
The facet expands when clicking on the icon to expand it.

**Screenshots**
Example in the Tag facet. This also applies to other facets with hierarchies.

![Screen Shot 2019-12-16 at 10 23 36 AM](https://user-images.githubusercontent.com/8975583/70934439-c839cf80-1ff2-11ea-8447-730b35ea6494.png)

**Additional context**
I've confirmed this issue in both Firefox and Chrome on OSX.

**Comment by jkeck** [comment]
FWIW, we released a major version of the gem last week that updated the markup and styling.  A few goals being to make the toggle icon more easily configurable, adding keyboard/screenreader accessibility, and better out of the box stying to reduce the need for custom styling.

I would be happy to chat w/ whoever takes this on as I initiated a lot of these changes upstream.
