### ISSUE TITLE
[argo/prod] ActionView::Template::Error: druid:bb005bg5914 not found in Preservation at https://preservation-catalog-prod-01.stanford.edu/v1/objects/druid:bb005bg5914.json

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1752]
## Backtrace

    line 59 of [PROJECT_ROOT]/app/helpers/dor_object_helper.rb: last_accessioned_version
    line 27 of [PROJECT_ROOT]/app/views/files/index.html.erb: block in _app_views_files_index_html_erb__2879927824058432150_69990765145400
    line 16 of [PROJECT_ROOT]/app/views/files/index.html.erb: _app_views_files_index_html_erb__2879927824058432150_69990765145400

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/55148725)

**Comment by andrewjbtw** [comment]
bb005bg5914 might be SDR1 content.

**Comment by jcoyne** [comment]
Fixed by #1753
