### ISSUE TITLE
trap for preservation-client errors and handle appropriately in argo

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#1756]
PR #1753 traps for NotFoundError for ONE call to preservation-client, but it doesn't trap for other specific pres-client errors or even their superclass. 

argo uses preservation-client in at least 3 ways:
- to retrieve preserved content file
- to get current_version
- to get checksums report
- opening/closing versions (via dor-services-app and dor-services-client, I believe ... but same idea applies re: error trapping and handling)

Ideally, we could:
- get error details to the user when appropriate 
   -  e.g. if pres-client has an UnexpectedResponse or other error or unexpected status code  (i.e. not a 200) , the user could see "unable to get response from Preservation for (druid)" or something instead of "something went wrong" 500 page.
- have a honeybadger notification when appropriate
- log appropriate error messages

See https://github.com/sul-dlss/preservation-client/blob/master/lib/preservation/client.rb#L30-L39

**Comment by ndushay** [comment]
tagging @andrewjbtw as this ticket pertains to his action item for https://docs.google.com/document/d/1FsoFOl9izY6vBkVNbqvaZ6k9L4OQIKcUQI_qUCA90rk.  Edit or comment this ticket as needed, Andrew.

**Comment by andrewjbtw** [comment]
I made a new ticket specifically for the error reporting part in Argo: https://github.com/sul-dlss/argo/issues/1758 . It may be that only the problem with getting sent to a generic status page when opening a version fails needs to be addressed.

**Comment by ndushay** [comment]
See https://github.com/sul-dlss/argo/issues/1759 and https://github.com/sul-dlss/argo/issues/1762
