### ISSUE TITLE
Surface preservation-client errors to the Argo interface

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1758]
This should be considered an uber ticket that will be broken down to smaller components.

Related to https://github.com/sul-dlss/argo/issues/1756

Argo should show users a useful error message when there is an error related to preservation-client.

Argo users can run into preservation-client errors in the following situations:

1. Opening a version 
2. Closing a version
3. Running a checksum report
4. accessionWF steps that use preservation-client
    - technical-metadata (checks existing technicalMetadata in moab)
    - shelve (checks contentMetadata in moab)

Errors encountered in each of these situations should be surfaced to Argo users. Currently, that seems to happen in some situations but not others.

1. Opening a version
     - when opening from an item page, a preservation-client error sends users to a generic page that does not provide information about the error
     - honeybadger does show a useful 422 error in this situation 
     - the information in the 422 should be shown to the user in Argo
     - note that when trying to open from a bulk action, an error is sent to the log for that bulk action, so this doesn't need to be fixed

2. Closing a version
    - when a version cannot be closed, the item page shows a grayed out button for "Close version"
    - it would take a larger redesign to surface an error message here, and not showing an error has been considered acceptable in general for when a version can't be closed
    - the lack of an error message is not specific to preservation-client errors and can be considered out of scope for this ticket
    - note that attempting to close an object with a bulk action already does surface a useful error message in the log, so this doesn't need to be fixed

3. Checksum reporting
    - during the problem with the preservation API urls, errors in retrieving the checksums were being reported as 301 redirects, which was not very helpful
    - there have also been cases where preservation-client reported a generic 404 (when the list of druids contains a druid not yet in preservation, for instance) when a more specific message would be more helpful
    - this may already have been fixed in https://github.com/sul-dlss/preservation_catalog/pull/1274

4. accessionWF steps that use preservation-client
    - it's not clear if anything needs to be fixed or if it's already working fine
    - these steps already report errors to Argo, so the question is: were they failing to report preservation-client errors?
    - it's possible that during the preservation API URL problem, there were no errors at these steps, in which case there was nothing to be surface in Argo
    - there don't seem to have been any actual technical-metadata errors during this time: see https://github.com/sul-dlss/common-accessioning/issues/484

**Comment by jcoyne** [comment]
Can you break this down to smaller tickets? Otherwise nobody would likely be able to take this on outside of a dedicated Argo workcycle. If you think of the smallest possible change that would improve the experience, then we have something that could be fit in when we have spare time.

**Comment by andrewjbtw** [comment]
Ok, I made a smaller ticket for the open version problem. I'm not sure if there's any work still to be done on the other three, but I can break them down tomorrow.

**Comment by andrewjbtw** [comment]
Closing this issue as the only aspect with work remaining has been ticketed already in #1759 for showing a message when opening a version fails.

Summarizing the other issues:

2. Closing a version -- Argo does not normally display an error if you can't close an object. Changing this behavior is out of scope for preservation work.

3. Checksum reports -- messaging has been updated there and is much more helpful when a druid doesn't exist or there's otherwise a problem.

4. We've confirmed that there were no technical-metadata or shelve errors during the preservation API outage, so there were no messages to display, and thus no failure to display messages.
