### ISSUE TITLE
Show a useful message when preservation-client errors prevent an object from opening

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1759]
Breaking this out from https://github.com/sul-dlss/argo/issues/1758

When attempting to open a version from an Argo item page

- a preservation-client error sends users to a generic page that does not provide information about the error
- but honeybadger does show a useful 422 error in this situation

Argo should show the user the information from the 422 error.

Note that when trying to open from a bulk action, an error is sent to the log for that bulk action, which is as it should be.

**Comment by jcoyne** [comment]
I don't believe that opening a version talks (directly) to preservation-catalog. It's checking with dor-services-app. Dor-services-app is sending some information from preservation-catalog if it is the source of the problem, but I don't believe this is the only thing that can trigger the 422. 

 I presume you mean this error?
```
Dor::Services::Client::UnexpectedResponse: Unprocessable Entity: 422 ({"errors":[{"status":"422","title":"Unable to open version","detail":"Preservation (SDR) is not yet answering queries about this object. When an object has just been transferred, Preservation isn't immediately ready to answer queries."}]})
```
https://app.honeybadger.io/projects/49894/faults/54744722

**Comment by andrewjbtw** [comment]
Yes, that's the error I was thinking of. I'm not sure if there are other ways opening a version can fail, but if there are this will be useful in telling them apart.

**Comment by aaron-collier** [comment]
As noted by @andrewjbtw 

"I don’t know if the details are the same in terms of http status codes, but when opening a version from the Argo item page fails, you just get sent to the library status page. That’s very confusing since Argo isn’t mentioned on that page, so the general goal of that ticket is still valid: to show some more useful error message."

So part of this is not to redirect to the library status page on these errors.

**Comment by ndushay** [comment]
Andrew: "You don't know until you're at the point of opening a version that something is wrong" - the button is NOT grayed out.  

also, folks are being sent to ... library status page?

**Comment by andrewjbtw** [comment]
Closing because in the new Argo UI, and post-Fedora, it does not appear to be possible to run into this issue anymore.
