### ISSUE TITLE
APO creation stalls in accessioning

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1768]
**Describe the bug**
It is not possible to register and accession APOs. When creating a new APO either via Argo or Hydrus, the druid for the APO stalls at "waiting" in the "publish-complete" step and does not go further. 

**User Impact**
Users cannot create new APOs. This means that they cannot create any new collections or new items that would use the new APO, and they cannot reassign existing items to the new APO. All of these are tasks user commonly carry out.

Often a user creates a new collection at the same time that they create a new APO, so the result is an error when trying to create a collection because the APO cannot be found. The preservationIngestWF has a step called "verify-apo" which checks to make sure that the APO being used has been accessioned. Nothing can be accessioned to SDR without a valid APO.

**To Reproduce**
1. Go to Argo
2. Click on Register >> Register APO
3. Create an APO
4. Check the APO's item page and see that it does not pass publish-complete

For examples:

In prod:
https://argo.stanford.edu/view/druid:zh978tn5683 (APO)
https://argo.stanford.edu/view/druid:px507jb1735 (collection)
https://argo.stanford.edu/view/druid:ty870gh9714 (item)

In stage:
This issue has been verified on stage by creating a test APO: 
https://argo-stage.stanford.edu/view/druid:dj604jb4901

**Expected behavior**
Newly registered APOs are accessioned successfully. A new collection registered at the same time to the new APO gets accessioned after the APO has been accessioned.

**Additional context**
The behavior when creating a new APO appears to be slightly different in Argo and in Hydrus. 

In Argo, you can create a new collection at the same time as creating a new APO. This is an option on the Register APO form. I don't think you can create new items until the APO has finished accessioning.

In Hydrus, it might be possible to create a new APO, new collection, and new item all at the same time. That seems to be the case in the example above.

But the underlying problem here is that APOs do not finish accessioning. Once the APOs are accessioned, the verify-apo errors on the affected collections and items should clear up when resetting the step.

**Comment by jcoyne** [comment]
There was an error with dor-service-apps connection to the database seen https://dor-services-stage.stanford.edu/queues/retries

**Comment by jcoyne** [comment]
problem is here: https://github.com/sul-dlss/common-accessioning/blob/master/lib/robots/dor_repo/accession/publish.rb#L17
we don't ever get to the "publish_complete" step because APOs don't get published

**Comment by justinlittman** [comment]
To address this, in publish step if an APO then set publish-complete step to complete.

**Comment by andrewjbtw** [comment]
I am closing this as the issue has been fixed.
