### ISSUE TITLE
Checksum Report Jobs fail with a 301 redirect when calling preservation catalog API endpoint

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#1776]
**Describe the bug**
When running checksum reports, a 301 is being thrown by the preservation catalog API endpoint.

See https://app.honeybadger.io/projects/49894/faults/55032532
and slack discussions: https://stanfordlib.slack.com/archives/C0EAZ09QF/p1579897286010800

**User Impact**
The user cannot run checksum reports.

**Comment by peetucket** [comment]
Naomi looked at shared_configs for argo and for dor-services-app
```
argo: preservation-catalog-prod-01
dor-services-app: preservation-catalog
```

**Comment by peetucket** [comment]
I'm confused since the call to PresCat API (here https://github.com/sul-dlss/argo/blob/master/app/jobs/checksum_report_job.rb#L26) works on the rails console on argo-prod-a and argo-prod-b:

```
pids = %w[druid:yz991qg9478 druid:hg916pq6480]
csv_report = Preservation::Client.objects.checksums(druids: pids)
=> "druid:hg916pq6480,hg916pq6480_01_01_pm.wav,4cb121dd3869ab3ddc983e8a32be0016,5402488d30a8e5b8b5d17da9fd150e94e421c746,3d24852c0ed4654a2a7db20c7ace4182d9995231da5cf9f194d8e8f65b71877b,86127282\ndruid:hg916pq6480,hg916pq6480_01_01_sh.wav,247c20235a8c693018811f02d3116a3d,dc486bd571e132bca2f58846083d7d350999312b,6507e4f424ccfc5cce70d846e9c92a3ba9c162bb4e0e406cbb008d0e517c3f7a,26376958\ndruid:hg916pq6480,hg916pq6480_01_01_sl.m4a,efb284b1fd5488968c6d6a40aa720aa5,4ff6853f6820c0a1e089c71a29bd77574fa2f675,68b1685e77fc542d4689ad1fb1d2fcc8ce6802541a366c741b4fecbfadc75ab3,6043017\ndruid:hg916pq6480,hg916pq6480_02_01_pm.wav,5db40dc3e3fa01ff6205abad91561aa9,aa41b2708fe456c0370642bdb7f7e59a405f1f66,8f1dbfe6d8ffd7c476cea5d85bd2e775b0ae8b64a

etcetcetc
```

**Comment by peetucket** [comment]
URL on the rails console matches shared configs:

```
[4] pry(main)> Settings.preservation_catalog.url
=> "https://preservation-catalog-prod-01.stanford.edu"
[5] pry(main)>```

**Comment by peetucket** [comment]
Just restarted the web app, and tried the bulk job and got a 401 unauthorized now.

But it still works on the rails console, which is still confusing.

**Comment by peetucket** [comment]
Maybe the actual activejob execution is running in some context other than the rails app which is not authorized, which explains why the app calls to fetch files and the calls from the rails console work, but the job does not?

**Comment by andrewjbtw** [comment]
I was able to run the same checksum report that Geoff couldn't, but Geoff still wasn't able to when he tried again. There could be a difference in authorization, but I believe these are all items that Geoff accessioned himself, so he shouldn't be blocked from getting information about them.

Don't know if it makes a difference, but I ran the job in Argo on campus, on VPN. Geoff is in SRWC and I'm not sure if he was on VPN or not.

**Comment by oceanofsound** [comment]
Not on VPN over here in RWC.

**Comment by ndushay** [comment]
We found some old background workers on argo-prod-a which, if used for background jobs, would have caused all sorts of wacko stuff.  I have killed the old workers.  I'm hopeful this is ok now.

@oceanofsound @andrewjbtw please close this ticket unless you can replicate the problem again (and I hope you can't.)

```
[lyberadmin@argo-prod-a current]$ ps -eaf | grep delay
503       8687     1  0 09:50 ?        00:00:25 eye monitoring v0.10.0 [delayed_job] (in /opt/app/lyberadmin)                                                             
503       9021     1  0 09:50 ?        00:00:00 delayed_job.0                                                                                                                             
503       9026     1  0 09:50 ?        00:00:01 delayed_job.1                                                                                                                             
503       9030     1  0 09:50 ?        00:00:01 delayed_job.2                                                                                                                             
503       9035     1  0 09:50 ?        00:00:02 delayed_job.3                                                                                                                             
503       9038     1  0 09:50 ?        00:00:00 delayed_job.4                                                                                                                             
503       9042     1  0 09:50 ?        00:00:00 delayed_job.5                                                                                                                             
503       9047     1  0 09:50 ?        00:00:00 delayed_job.6                                                                                                                             
503       9050     1  0 09:50 ?        00:00:00 delayed_job.7                                                                                                                             
503       9054     1  0 09:50 ?        00:00:00 delayed_job.8                                                                                                                             
503       9057     1  0 09:50 ?        00:00:00 delayed_job.9                                                                                                                             
503       9062     1  0 09:50 ?        00:00:00 delayed_job.10                                                                                                                            
503       9072     1  0 09:50 ?        00:00:00 delayed_job.11                                                                                                                            
503      10209     1  0 Jan14 ?        00:05:18 delayed_job.10       <---  I killed this one                                                                                                           
503      11923     1  0  2019 ?        01:04:25 delayed_job.2         <-- I killed this one, too
```

**Comment by peetucket** [comment]
good catch, that seems like it would cause problems

**Comment by oceanofsound** [comment]
Sadly I'm still getting errors on the reports I run.

**Comment by ndushay** [comment]
1.   preservation-client gem is incorrectly sending lists of druids as part of url, even for http post request.  This would make the urls really really long for long lists of druids.

I have PR https://github.com/sul-dlss/preservation-client/pull/33 drafted so the request url for checksums will not be too long;  I want to debug the fix in stage first.

2. if the list is really long, we can hit the timeout for the request being made from argo.   Since each run has a varying time, sometimes things work and sometimes they don't.  We can address this by switching it to do the same thing that virtual object merge does ... but I'm not sure how simple that is / worth it ... esp if most checksum reports are small.  I can confer with the virtual merge async experts and find out if it's relatively easy.

**Comment by peetucket** [comment]
Good catch .... I hope this is what it is (though there was one particular request that Geoff was trying that worked for me on the rails console and worked for Andrew in Argo).  So that still seems odd.

**Comment by ndushay** [comment]
Here is the plan for fixing the checksum report

- [x] preservation-client fix for POST errors:  https://github.com/sul-dlss/preservation-client/pull/33/
- [x] preservation-client 3.1.0 gem released
- [ ] preservation-catalog tweak for erroring objects https://github.com/sul-dlss/preservation_catalog/pull/1344
    - [ ] preservation-catalog fix deployed to stage and prod (should help with some failing checksum reports)
- [ ] argo uses preservation-client 3.1.0 gem (should fix checksum report)
    - [ ] argo fix deployed to stage and prod

The following are also affected by the update to preservation-client, but are not yet experiencing the problem from large HTTP POST requests being sent to prescat.

- [ ] preservation_robots uses preservation-client 3.1.0 gem  <- can wait for Mon dep updates
    - [ ] preservation_robots update deployed to stage and prod
- [ ] dor-services-app uses preservation-client 3.1.0 gem <- can wait for Mon dep updates
    - [ ] dor-services-app update deployed to stage and prod
- [ ] common-accessioining uses preservation-client 3.1.0 gem  <- can wait for Mon dep updates
    - [ ] common-accessioining update deployed to stage and prod

**Comment by ndushay** [comment]
At this point, the improvements to the argo side (allow long lists of druids to be send) and the prescat side (handle erroring individual druids better) have both been deployed.  I'm going to say, from my perspective, this has been fixed.   Please close this ticket if you agree, @oceanofsound @andrewjbtw .    If the timing out problem occurs, I would ask that a new ticket be opened.
