### ISSUE TITLE
argo intermittently fails to provide auth token when running checksum report job

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#1777]
**Describe the bug**

people seem to be able to consistently run it from the rails console, and @andrewjbtw has been able to run it intermittently from the UI, but it seems that most requests today have failed with:

```
ChecksumReportJob got error from Preservation Catalog API (Preservation::Client::UnexpectedResponseError): Preservation::Client.http_response got 401 from Preservation at v1/objects/checksums: {"error":"Not Authorized"}
```

see https://app.honeybadger.io/projects/49894/faults/59864732

the notification on the pres cat side indicates the token isn't being provided at all (as opposed to an invalid token being provided):
```
no Authorization token was provided by [ip address]
```

see https://app.honeybadger.io/projects/54415/faults/59956404

**User Impact**

work is partially blocked for argo users who need to run checksum reports.

**To Reproduce**
1. e.g. using argo search results, run a Checksum Report Job
2. the job will likely fail, producing the above described notifications

**Expected behavior**

checksum job should run successfully if the user has permission to view the objects and the batch size is reasonable.

**Comment by jmartin-sul** [comment]
we have also seen two other strange recent alerts that we think are related:
1. argo attempting to run a large checksum retrieval job via `GET` instead of `POST`, resulting in an error due to the request being too large.
2. argo attempting to hit the preservation API without `/v1` in the path.

which both sound an awful lot like issues we've run into elsewhere with async worker processes continuing to run stale code after newer code has been deployed.

when she looked just now, @ndushay saw what appeared to be a Delayed Job process on argo-prod-a from 2019.  considering that the error in this issue's description came from -a, as did the behavior described in this comment, it starts to look even more like stale job code being executed.

naomi killed the old `delayed_job` process that was hanging around on argo-prod-a, and found nothing similar on argo-prod-b.

we're hopeful this will resolve the issue.

(corrections welcome if i got any of this comment wrong)

**Comment by jmartin-sul** [comment]
see also @ndushay's comment on #1776

**Comment by ndushay** [comment]
Once PRs 

- [ ] sul-dlss/argo#1783 and 
- [ ] sul-dlss/preservation_catalog#1344 

have been deployed to prod, let's see if this can be recreated or if we fixed it.

**Comment by ndushay** [comment]
When can this ticket be closed?  How will we know when this is no longer a problem?   Can we set a date (if this has no occurrences by XXX then close this ticket)?
