### ISSUE TITLE
Take workflow objects out of Fedora

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#1791]
Workflow objects in fedora behave really badly in Argo

bb163sd6279 will not display in Argo, throws cocina model error in dor-services-app
This object is the definition of the sdrIngestWF

https://app.honeybadger.io/projects/50568/faults/58801703 dor-services-app
https://app.honeybadger.io/projects/49894/faults/57442187 argo

**Comment by jcoyne** [comment]
I think we should remove them from Fedora as they are no longer useful and have diverged from the definitions that we are actually using (https://github.com/sul-dlss/workflow-server-rails/tree/master/config/workflows).  Keeping two different copies around invites confusion.

**Comment by ndushay** [comment]
@jcoyne that makes a lot of sense.  If Andrew/Hannah are ok, I have no objection.

**Comment by andrewjbtw** [comment]
We can take these out of Fedora, but I want to keep some historical information about them first. It shouldn't take me more than a couple of days to pull it together. Basically, I just want to have a record (not much more than a list) of what the old workflows were for administrative history purposes.

**Comment by jmartin-sul** [comment]
and fwiw, if @andrewjbtw ends up missing something in the documentation he's assembling, the objects should at least be around in preservation for revisiting later, should we come up with questions down the road that we haven't thought of yet.

**Comment by andrewjbtw** [comment]
It turns out we don't send the workflow objects to preservation. My understanding of the history is that they went to Fedora because they needed a place to put them when SDR was getting started, not because they were meant to get preservation/moab treatment.

**Comment by jmartin-sul** [comment]
> It turns out we don't send the workflow objects to preservation

oh interesting.  but yeah, that makes some sense, i guess.

**Comment by andrewjbtw** [comment]
Ok, I've exported what I think might be helpful to the future. These can be removed whenever it's convenient.

**Comment by jcoyne** [comment]
Done
