### ISSUE TITLE
descMetadata datastream is not created when registering an object to a catkey

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1792]
**Describe the bug**
When registering an object to a catkey by supplying the catkey on the registration form, no descMetadata datastream is being created at the time of registration. Previously, a descMetadata datastream was created as part of registration.

Note: registering without a catkey does create a descMetadata datastream.

**User Impact**
This has caused some confusion for users, who have reported the issue. Often one user will register items and then pass on those druids to digitization staff, who will accession the content that goes with them. The Symphony metadata should be part of the object at the time of the hand off.

The descMetadata datastream can be created by using the "Refresh descMetadata" blue button on an item page or the "Refresh MODS" bulk update, but this is an extra step that was not previously necessary.

**To Reproduce**
1. Register an item with a catkey.
2. Go to the item page.
3. Check for a descMetadata datastream.

**Expected behavior**
The descMetadata datastream should be created with the metadata imported from Symphony for that catkey.

**Comment by jcoyne** [comment]
@andrewjbtw isn't the datastream created in the desc-metadata step of the accessionWF?

**Comment by jcoyne** [comment]
@andrewjbtw if you want to move this to registration time, I think this would be really helpful as we could cut this step out of the accessionWF, which means we break the dependency with Fedora there.

**Comment by jcoyne** [comment]
It does look like it gets metadata from symphony if you pass `seed_datastream=['descMetadata']`. 
https://github.com/sul-dlss/dor-services-app/blob/master/app/services/registration_service.rb#L116

**Comment by jcoyne** [comment]
If you look at this item, you'll see that argo is not properly passing `seed_datastream`:

https://argo-stage.stanford.edu/view/druid:gd760yn3870
<img width="1239" alt="Screen Shot 2020-01-31 at 3 46 06 PM" src="https://user-images.githubusercontent.com/92044/73576755-d035bd80-4440-11ea-99bb-0f747a1ba5d5.png">

**Comment by andrewjbtw** [comment]
The datastream does get created during the accesionWF if it didn't exist before, but I'm fairly certain the datastream used to be created during registration. This mainly affects staff workflows where registration and accessioning are done by different people, possibly weeks or months apart.

I don't think we can cut descriptive metadata out of the accessionWF because that step also functions as a point where metadata updates are applied to existing objects.

**Comment by jcoyne** [comment]
@andrewjbtw I'm not talking about the part where it does updates, only the part where it creates an initial datastream.
