### ISSUE TITLE
items failing release with     release-members : `object_identifier` argument cannot be `nil` in call to `#object(object_identifier)

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1796]
**Describe the bug**
Items are failing release with the following error:

```release-members : `object_identifier` argument cannot be `nil` in call to `#object(object_identifier)```

These all look to be related to releasing collections to searchworks:
https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=releaseWF%3Arelease-members%3Aerror

**User Impact**
Items cannot complete release.

**Comment by mjgiarlo** [comment]
@andrewjbtw This is now resolved in production: https://argo.stanford.edu/view/druid:bg721dv4225

**Comment by andrewjbtw** [comment]
Thanks!
