### ISSUE TITLE
Items failing accessioning at end-accession

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1797]
**Describe the bug**
Collection items are failing at the end-accession step with

```end-accession : undefined method `hasAdminPolicy' for #<Cocina::Models::Collection::Administrative releaseTags=[]>```

Examples:
https://argo.stanford.edu/view/druid:xd695sf9329
https://argo.stanford.edu/view/druid:yc400qw4578

**User Impact**
Collections can't complete accessioning.

**Comment by mjgiarlo** [comment]
@andrewjbtw This is now resolved in production: https://argo.stanford.edu/view/druid:xd695sf9329

**Comment by andrewjbtw** [comment]
Thank you!
