### ISSUE TITLE
Virtual objects job won't stop

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1800]
**Describe the bug**
I started a virtual objects job a couple of days ago and it keeps restarting itself as a background job. At one point yesterday, Sidekiq reported more than one instance of the job running at the same time. 

In an attempt to stop the job, I changed all the parent objects to citation only (which prevents virtual object creation), and eventually the bulk action page reported that it had stopped. 
![Screen Shot 2020-02-06 at 9 49 35 AM](https://user-images.githubusercontent.com/8975583/73963999-351c6800-48c6-11ea-86fa-bb2efe3e0f5d.png)

But if you check Sidekiq you'll see that it is still active in either the busy or the retries tab. It's possible that what happened is that one instance of the job stopped and the other kept going.

This seems related to, but not quite the same as #1728 

**User Impact**
It's not clear if this is a one time problem, or a problem that will affect large batches. Up to this point, I'd been successfully running large batches of virtual objects with as many as 70 lines and 40,000 druids in them, following the fix to #1728 

**Additional context**
The job does seem to be operating correctly by not merging any of the citation-only objects. But it keeps running/restarting.

**Comment by mjgiarlo** [comment]
The job is now killed. Note that because of OpenAPI not allowing all Sidekiq routes, jobs must be killed via the Rails console. Here's how I did that:

1. Find the job in the set of retry jobs: `jobs = Sidekiq::RetrySet.new.select.to_a` This is an array of retry jobs. In my case, it was the second entry in the array, so I assigned it to a new variable: `job = jobs.second`
2. Then I delete it via `job.delete`

**Comment by mjgiarlo** [comment]
Feel free to close or lmk if anything else needs doing.

**Comment by mjgiarlo** [comment]
Once https://github.com/sul-dlss/dor-services-app/pull/638 is merged, it should be possible to delete and kill jobs in the Sidekiq UI.

**Comment by andrewjbtw** [comment]
I think this ancient ticket can be closed as this has not been an issue for years.
