### ISSUE TITLE
When creating a collection at the same time as an APO, the collection object hits an error at verify-apo

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1801]
**Describe the bug**
SDR users have the option to create a collection when creating an APO. This is available both via Argo and Hydrus.

All objects in SDR must be attached to an APO. There is a check in the preservationIngestWF step "verify-apo" that checks whether the APO assigned to an object has been accessioned. The problem when creating both at the same time is that frequently the APO has not finished accessioning before the collection reaches verify-apo.

This results in the collection object halting with an error until the APO has been accessioned, and then someone has to come along afterwards to reset the step.

**User Impact**
The collection isn't available for use until it has been accessioned, so this causes delays.

**To Reproduce**
1. Go to Argo > Register > Register APO
2. When creating an APO, choose one of the options to create a collection

![Screen Shot 2020-02-06 at 11 05 25 AM](https://user-images.githubusercontent.com/8975583/73969796-e922f080-48d0-11ea-874d-b4999a016b37.png)

3. Wait for both objects to run through accessioning. You will see an error if the APO object doesn't finish before the collection object reaches verify-apo

**Expected behavior**
Collections are accessioned after the APO they're tied to has been accessioned.

**Additional context**
Except for when creating a collection at the same time as an APO, collection can only be created after an APO has been accessioned (via the blue button for "Create Collection" on an APO's item page in Argo).

**Comment by mjgiarlo** [comment]
@andrewjbtw I wonder whether we should consider removing the ability to create them simultaneously in favor of architecting something more complex to orchestrate the two create operations. How important is it to do these steps in one fell swoop? Is it saving folks significant time, especially considering this bug?

cc: @vivnwong

**Comment by andrewjbtw** [comment]
I think it's a pretty common task. I admittedly haven't kept statistics, but it seems like most APOs created in Argo are created with a collection from the start. Most projects that involve creating a new APO also involve creating a new collection.

For Hydrus this appears to be the default behavior when creating a collection. I don't think that users are aware they are creating an APO when they create a collection. So it's not something that looks like it would be easy to turn off. 

I don't know if it is saving people time because I've been in the habit of fixing the issue on my daily check of the workflow grid, so most people probably never notice it. I can of course continue to do that, and rely on people raising the issue if they need the problem resolved sooner.

This has left me wondering if the process worked differently before because I don't remember seeing errors here until possibly last fall, but it's also possible that no one created a collection from an APO for the first few months after I started.

**Comment by mjgiarlo** [comment]
@andrewjbtw Thanks, Andrew. Having taken a look at Hydrus now, yes, this would take some doing to disentangle. Do you have a sense of the extent to which these situations are in the Hydrus context (as opposed to the Argo context where, presumably?, it might be easier to disentangle)?

**Comment by andrewjbtw** [comment]
It's really hard to say. Most new Hydrus users are channeled into the Stanford Research Data collection to avoid proliferating collections with just a couple of deposits. But in the last month, there has been a flurry of cases where it made sense to create new collections. I cleared up two of these errors from Hydrus collections created just yesterday. 

Argo seems more evenly spread out, based on when new projects are started.

**Comment by mjgiarlo** [comment]
@andrewjbtw OK, good to know. Lastly, do you have a sense of how frequently this error is cropping up? I'm wondering whether it's a few times a day, a few times a month, or what order of magnitude we're talking about here.

**Comment by andrewjbtw** [comment]
I don't think it's more than a few times per month.

**Comment by andrewjbtw** [comment]
This Hydrus issue I just came across indicates this problem has been around for a while https://github.com/sul-dlss/hydrus/issues/335

**Comment by peetucket** [comment]
The simplest way I can think to handle most of these cases is just to wait a bit, though just blindly holding the process for some period of time is a bad idea.  And if we just return it to the waiting state to try again, it is likely to get picked up immediately, so we will be doing all the checking again.

But I can't think of a straightforward way of avoiding the race condition.

**Comment by andrewjbtw** [comment]
We can skip or remove this step for future accessioning, as it is not providing a useful check anymore.

**Comment by justinlittman** [comment]
Remember when removing this step to:
1. Remove the robot (and associated code): https://github.com/sul-dlss/preservation_robots/blob/master/lib/robots/sdr_repo/preservation_ingest/verify_apo.rb
2. Remove workflow step from template: https://github.com/sul-dlss/workflow-server-rails/blob/master/config/workflows/preservationIngestWF.xml#L14
3. In the workflow db, set any `verify-apo` steps that are not `status=completed` to `status=skipped`.

**Comment by ndushay** [comment]
We could, and perhaps should, check that the APO is REGISTERED.

**Comment by peetucket** [comment]
Following on from Naomi's comment, how about if we keep the verify-apo step, but instead of going all the way to preservation core, we just confirm that the object exists (i.e. it is registered)?  This may actually simplify things a bit, as we will keep the step, and don't have to worry about any existing steps in progress, we just change the logic.

**Comment by andrewjbtw** [comment]
That sounds like a good idea to me. It's a weird place to do the check but given that it already exists as a step changing the check does seem like the simplest path.

There is a risk that a registered APO could be purged, while and accessioned one would remain in the system even if it got deactivated, but I believe all methods of registering an APO lead directly to accessioning (in Argo and Hydrus) so it's unclear to me how you could have an APO remain at registered for more than a few seconds.

**Comment by peetucket** [comment]
There were objections to doing the check here, and Justin Littman also noted we check the APO existence at time of registration now (in the cocina reg code), so it is not necessary.  So new proposal is to simply strip the robot completely: https://github.com/sul-dlss/preservation_robots/pull/220

**Comment by peetucket** [comment]
verify-apo step doesn't exist anymore via sul-dlss/preservation_robots#220, so this shouldn't happen anymore
