### ISSUE TITLE
</span> tags showing on Argo facet pages

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1823]
**Describe the bug**
Reported via the argo-feedback list:

When I click through to the full page view of the SW Genres facet, I see ```</span>``` tags near the Previous/Next buttons at the top and bottom of the page.
https://argo.stanford.edu/catalog/facet/sw_genre_ssim?all=true&f%5Bsource%5D%5B%5D=hydrus

Also an issue on other facet pages.
https://argo.stanford.edu/catalog/facet/hydrus_collection_title_ssim?all=true&facet.sort=count
 
**Screenshots**
![image001](https://user-images.githubusercontent.com/8975583/74962598-17222d80-53c5-11ea-8404-7159b5055eda.png)

**Comment by andrewjbtw** [comment]
From @peetucket on the same listserv thread:

Looks like this exists in searchworks too by the way (confirming its blacklight, and searchworks also seems to be using 6.22.0) ….  looking at the language facet and clicking the more link shows this:

![sw-facet-span](https://user-images.githubusercontent.com/8975583/74963119-0920dc80-53c6-11ea-9cb5-1b08c44002e3.png)

So this may be an issue in Blacklight more generally.

**Comment by jcoyne** [comment]
It's fixed in blacklight but hasn't been released yet: https://github.com/projectblacklight/blacklight/commit/a746fa59b6b138f7d1f10200da635ad60b4f6fd3

**Comment by andrewjbtw** [comment]
Possibly fixed with Blacklight 7.

**Comment by aaron-collier** [comment]
Verify now that BL7 is in stage.
