### ISSUE TITLE
 NoMethodError in items # set_rights 

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#1830]
```
NoMethodError: undefined method `set_read_rights' for #<Dor::Item:0x...>
```

See https://app.honeybadger.io/projects/49894/faults/61225214

**Comment by jcoyne** [comment]
It looks like this method was deprecated in dor-services 7.2, this must not be covered by a test.

https://github.com/sul-dlss/dor-services/blob/7-2-stable/lib/dor/models/abstract.rb#L130
