### ISSUE TITLE
Data "not found" errors in assemblyWF

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1843]
**Describe the bug**
Many druids are stalling at with errors like:

```
checksum-compute : Path to object bd351bj1440 not found in any of the root directories: /dor/assembly,/data/hydrus-files
```
https://argo.stanford.edu/view/druid:bd351bj1440

or
```
jp2-create : Path to object tg843cr2056 not found in any of the root directories: /dor/assembly,/data/hydrus-files
```
https://argo.stanford.edu/view/druid:tg843cr2056

This indicates that content cannot be found in the directories where it should be during accessioning. Either the content is not being copied correctly, or it is being deleted prematurely. Either possibility is a serious issue.

I have spot checked these druids and the content is indeed not there.

**User Impact**
This prevents these items from being accessioned. It is also difficult to solve errors of this nature, as the objects either need to be reset so that pre-assembly can be run again, or the files must be manually copied to the proper directories.

**Additional context**
For some or all of these items, Pre-Assembly reported success. See for example:

https://sul-preassembly-prod.stanford.edu/job_runs/3998

This job has multiple druids with no content found when they reached the assemblyWF.

**Comment by peetucket** [comment]
Both of those examples above appear to be a "re-accession" with versioning instead of a new object.  Is there an easy way to tell if that is a common thread for all in this error state?  That may help pinpoint the error.

**Comment by andrewjbtw** [comment]
I've done some further investigation on qt744wh8095, tg843cr205, ys245nc9912which are all in error at jp2-create. 

https://argo.stanford.edu/catalog?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=Maps+-+Stanford+General+Collections&f%5Bwf_wps_ssim%5D%5B%5D=assemblyWF%3Ajp2-create%3Aerror&page=1&per_page=100

All three of them show recently accessioned versions in preservation core, but those versions do not include new tif files. Also, both the accessionWF and preservationWF show successful recent runs.

It look like what might be happening is:

1. assemblyWF starts on new druid
2. accessionWF also starts on same druid without waiting for assemblyWF to finish.
3. accessionWF does not have information indicating there are new files because assemblyWF has not finished yet
4. accessionWF goes ahead a creates a new version anyway, which preservationIngestWF deposits
5. since all indications are that accessioning was a success, accessionWF cleans up the /dor workspace.
6. assemblyWF, still running, no longer has files to process

**Comment by andrewjbtw** [comment]
They do all appear to be new versions so far.

**Comment by peetucket** [comment]
> I've done some further investigation on qt744wh8095, tg843cr205, ys245nc9912which are all in error at jp2-create.

Your logic sounds plausible and leads to some potential avenues for further sleuthing (like when did those workflows start and who started them).

**Comment by peetucket** [comment]
Looking at the XML view of the workflows for version 3 of `druid:bd351bj1440`, which is the version started by the re-accesion indeed shows that accessionWF was started at exactly the same time as assemblyFF, which is not right.

accessionWF:
```
  <process version="3" note="" lifecycle="submitted" laneId="default" elapsed="" attempts="0" datetime="2020-03-03T22:22:56+00:00" status="completed" name="start-accession"/>
```

assemblyWF:
```
  <process version="3" note="" lifecycle="" laneId="default" elapsed="" attempts="0" datetime="2020-03-03T22:22:56+00:00" status="completed" name="start-assembly"/>
```

**Comment by andrewjbtw** [comment]
Spot checking the recent pre-assembly runs, it does look like entirely new objects are being created successfully, which suggests it is a reaccession issue. There have been a lot of preassembly runs this week (March accessioning time has begun), so we'd expect to see even more of this error if all preassembly was affected.

**Comment by peetucket** [comment]
I wonder if this line in pre-assembly that closes the version but tells accessioning not to start is somehow not working as expected anymore: 

https://github.com/sul-dlss/pre-assembly/blob/master/app/lib/pre_assembly/digital_object.rb#L159

This is a part of the code that was extracted and moved to dor-services-app as part of my "re-accesion in goobi" work, but pre-assembly usage of that new code in dor-services-app is not deployed yet and remains in a branch for testing in the future.  And I didn't touch the actual version closing methods in either dor-services-app or client either (just used them in a new method).

**Comment by peetucket** [comment]
Pre-assembly in prod is also currently a slightly older version of dor-services-client that doesn't have any of the recent changes, suggesting that may not be relevant:
From Gemfile.lock: `dor-services-client (4.16.0)`  (currently version with new start accession methods is 4.17.0)

**Comment by peetucket** [comment]
I've followed the path from this line that closes the version (https://github.com/sul-dlss/pre-assembly/blob/master/app/lib/pre_assembly/digital_object.rb#L159) in pre-assembly from `dor-services-client` --> `dor-services-app` --> `dor-workflow-client` --> `dor-workflow-app` and I don't see anything obviously wrong.  That parameter to indicate if accessionWF should be started seems to be passed all the way through and acted upon as needed. 

But presumably this re-accession pre-assembly issue has started very recently?  Is there any way to know when the last successful re-accession job was run with pre-assembly?  May help pinpoint any changes that occurred since that date.

**Comment by andrewjbtw** [comment]
Trying to see if I can work some Solr magic to find specifically pre-assembly reaccessions.

**Comment by peetucket** [comment]
ok, that's useful ... so basically we think it broke sometime between Feb 29 and March 5
