### ISSUE TITLE
The download-a-file modal in Argo is returning "Network error"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1844]
**Describe the bug**
Clicking on individual file links at the bottom of an item page should return a pop-up with direct links to the file in stacks and/or preservation. Currently this modal is taking a long time to load, then popping up with the message: "Network error".

<img width="529" alt="Screen Shot 2020-03-05 at 3 37 52 PM" src="https://user-images.githubusercontent.com/8975583/76035979-b5e77780-5ef7-11ea-8773-311a2b1e5d93.png">

**User Impact**
It's not possible to download files via Argo.

**To Reproduce**
1. Go to an item in Argo that has accessioned files.
2. Click on a file link at the bottom of the page.
3. Wait. If a box pops up, it will say network error. A box might not even pop up.

**Comment by jmartin-sul** [comment]
suspect firewall issues since the argo boxes were recently rebuilt.  @julianmorley thought this was a reasonable suspicion, and is investigating.

**Comment by jcoyne** [comment]
Fixed by https://github.com/sul-dlss/puppet/pull/4978?

**Comment by andrewjbtw** [comment]
Not yet.

**Comment by justinlittman** [comment]
I don't know if this has been noted, but looks like it is hitting shib:
```
Preservation client error getting current version of druid:bb009sj6832: Preservation::Client.current_version for druid:bb009sj6832 got Found (302) from Preservation at https://preservation-catalog-prod-01.stanford.edu/v1/objects/druid:bb009sj6832.json: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://login.stanford.edu/idp/profile/SAML2/Redirect/SSO?SAMLRequest=lZJBT8JAEIX%2FSrP30m5BlA1tUuEgCUpD0YMXs%2B1O6SbLbt3Zov57S0GFC4nnefO9mTczRb5TDUtbV%2Bs1vLeAzvvcKY2sL8SktZoZjhKZ5jtA5kqWp49LFg1C1ljjTGkU8VJEsE4aPTMa2x3YHOxelvC8Xsakdq5BFgSNhU615wedX3LHldn6HUP4IR2g47oyVgxAtEFey6IwClw9QDTBwTAKslW%2BId68m1DqnvFH7kBSXyKkaDpDU0kFp%2F41CGmhdEGer4i3mMfkjfOxgLCsaESHEwpFVUxG9I6Pi1uYCCFoJ0NsYaEPaBeTKIxCPxz64XhDKRvesBF9JV52iuFeaiH19npmxVGE7GGzyfzjTi9gsd%2BnE5Bkekie9cb27BbXsfznACT5f9z4G%2Fc0ODM%2FTtKwp85tMc%2BMkuWXlyplPmYWuIOYUBIkx5bLF0q%2BAQ%3D%3D&amp;RelayState=ss%3Amem%3A8b69c241e6abcde4411f10fb6a5ea2c1db5ff8c91c54da90aeba91ede3b34203">here</a>.</p>
</body></html>
```
https://app.honeybadger.io/projects/49894/faults/59276322

**Comment by jcoyne** [comment]
Yes, we're waiting for this fix: https://github.com/sul-dlss/puppet/pull/4981

**Comment by andrewjbtw** [comment]
Looks like it's been fixed now. Just downloaded a couple of files.
