### ISSUE TITLE
registration form should never create duplicate source_ids 

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1845]
**Describe the bug**
Under some circumstances, the Argo registration form can create multiple druids for the same source_id. This should not be possible.

SDR items should never have duplicate source_ids, as the source_id is supposed to be a unique identifier applied to original source material (i.e. for digitized materials, no two physical items should have the same source_id). 

**Expected behavior**
The registration form should throw an error when registering an item to a source_id that already exists. Currently, there is a check for duplicate source_ids already in place, but there are circumstances where it does not catch this error.

**To Reproduce**
There are two ways to reproduce the behavior.

Method 1:
1. Go to the Argo item registration form.
2. Enter the same source id and label on multiple rows.
3. Click Register
4. More than one druid will be assigned to the same source_id

![duplicate-source1](https://user-images.githubusercontent.com/8975583/76054507-c6aee200-5f25-11ea-9120-9bfe41293646.png)

Method 2:

1. Go to the Argo registration page
2. Enter data to register items
3. Click Register
4. Watch druids get assigned
5. Within the next few seconds, click the registration button again
6. Keep clicking the register button in intervals of a few seconds
7. You can keep creating new druids for the same source_id

I was able to create 9 druids with the same source_id using this method. I probably could have created more but I stopped clicking.
https://argo-prod-b.stanford.edu/catalog?utf8=%E2%9C%93&q=%22duplicate%3Asource2%22

**User Impact**
Digitization and SDR deposit workflows rely on having a unique source_id for each druid. A common digitization workflow is to print out paper tracking sheets after registration that are used to track physical items together with their druids and source_ids as they undergo digitization. When source_ids are assigned erroneously, this work has to be paused.

**Additional information**
This issue was reported recently with a batch of ~75 source_ids where two druids got created for each source_id by accident. The users reported having accidentally clicked the "Register" button twice in short succession, and then found out they had two sets of druids for the same batch of source_ids. 

This may be a new issue. The registration form has thrown an error when registering to existing source_ids for as long as I've worked on SDR, but I don't recall whether it's caught the specific scenarios described above.

**Comment by jcoyne** [comment]
We are checking for duplicate source ids here:
https://github.com/sul-dlss/dor-services-app/blob/master/app/services/registration_service.rb#L75-L77

However, this depends on Solr being up to date, and as it depends on the message from Fedora through sul-mq to dor_indexing_app, there is some latency.

**Comment by jcoyne** [comment]
@andrewjbtw unfortunately, Fedora 3 doesn't have a way to create unique constraints, so there's no way for us to guarantee this until we migrate off of Fedora.  I've submitted a PR to dor-services-app to make it so that the window in which this can happen is narrower.

**Comment by andrewjbtw** [comment]
Thanks. So the potential for accidentally re-using a source_id must have always been there and just hadn't come up before.
