### ISSUE TITLE
Download descriptive metadata bulk action fails on large sets (9000+ druids)

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1874]
**Describe the bug**
The descriptive metadata bulk action fails when a request contains more than ~10000 druids. Watching the bulk action progress on the server, it looks like the job times out at 8 minutes and stops. But on the bulk action interface, it appears that the job is still in progress even thought it has stopped:

<img width="1021" alt="Screen Shot 2020-03-27 at 1 15 14 PM" src="https://user-images.githubusercontent.com/8975583/77796731-11a3ad00-702d-11ea-92de-87725bde6567.png">

The log lists all the druids processed up to the point where the job stopped and does not report an errror.

**User Impact**
Users cannot download descriptive metadata for large collections with one bulk action. This is currently a blocker for @arcadiafalcone 

**To Reproduce**
1. Go to Bulk Actions
2. Select download descriptive metadata
3. Enter a list of 10,000+ druids
4. Wait until bulk action stalls.

**Expected behavior**
This bulk action should continue to run until it has processed every druid.

**Additional context**
It looks like this job does not make use of background changes that were implemented to make virtual object jobs handle 10,000+ druids. Virtual objects used to run into an 8 minute limit but no longer have that issue.

**Comment by justinlittman** [comment]
Starting to suspect it might be a memory problem:
```

2020.03.30 12:58:30 INFO  -- [delayed_job:workers:delayed_job.1] check:memory(<1500Mb) [*1765Mb] => Fail
2020.03.30 12:58:30 ERROR -- [delayed_job:workers:delayed_job.1] NOTIFY: Bounded memory(<1500Mb): [*1765Mb] send to [:restart]
2020.03.30 12:58:30 INFO  -- [delayed_job:workers:delayed_job.1] schedule :restart (bounded memory(<1500Mb))
2020.03.30 12:58:30 INFO  -- [delayed_job:workers:delayed_job.1] => restart  (bounded memory(<1500Mb))
2020.03.30 12:58:30 INFO  -- [delayed_job:workers:delayed_job.1] switch :restarting [:up => :restarting] bounded memory(<1500Mb)
2020.03.30 12:58:30 INFO  -- [delayed_job:workers:delayed_job.1] executing: `bundle exec bin/delayed_job restart -i 1` with restart_timeout: 90.0s and restart_grace: 10.0s
2020.03.30 12:58:57 INFO  -- [delayed_job:workers:delayed_job.1] sleeping for :restart_grace 10.0
2020.03.30 12:59:07 INFO  -- [delayed_job:workers:delayed_job.1] load_external_pid_file: process <5940> from pid_file found and running (identity: ok) (delayed_job.1)
2020.03.30 12:59:07 INFO  -- [delayed_job:workers:delayed_job.1] switch :restarted [:restarting => :up] bounded memory(<1500Mb)
2020.03.30 12:59:07 INFO  -- [delayed_job:workers:delayed_job.1] <= restart
2020.03.30 13:02:54 INFO  -- [delayed_job:workers:delayed_job.0] check:memory(<1500Mb) [142Mb] => OK
```

**Comment by andrewjbtw** [comment]
Increasing the memory got the job further, but it still stalled at 17,759 out of 30,000+ druids.

For reference, this is how I'm testing:

1. Run this search
https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Acr247kt0623&f%5Bprocessing_status_text_ssi%5D%5B%5D=Accessioned

2. From the results page, click "Bulk Actions"
3. Click on "New Bulk Action"
4. Choose "Download Descriptive Metadata" from the drop down
5. Click on "Populate with Previous Search"
6. Wait a while. Eventually all 30,000+ druids will appear in the box.
7. Click "Submit"
8. Refresh the bulk actions page and watch the numbers increment for the job.
9. Wait to see if it stalls. It seems to stop around 8 minutes after it started (when I've sat there watching it in real time).

**Comment by justinlittman** [comment]
@andrewjbtw This is deployed in prod and ready for you to re-test. (It worked for me.)

**Comment by andrewjbtw** [comment]
Re-tested and it's fixed.
