### ISSUE TITLE
Restore Delete button functionality for bulk_jobs

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/argo#1882]
**Describe the bug**
In the bulk_jobs view, each row in the jobs table has a Delete button that doesn't do anything.

**User Impact**
Fixes non-functioning button

**To Reproduce**
1. Go to https://argo-stage.stanford.edu/apos/druid:qc410yz8746/bulk_jobs
2. Click on the **Delete** button for any of the jobs
3. Click the confirmation **Delete** button in the modal
4. Displays error page "The page you were looking for doesn't exist."

**Expected behavior**
Users shouldn't get confused about a non-functioning button in Argo

**Screenshots**
<img width="685" alt="Screen Shot 2020-03-31 at 12 34 30 PM" src="https://user-images.githubusercontent.com/71847/78062496-01047700-734c-11ea-8dbc-3ecfa88fad2e.png">

**Additional context**
n/a

**Comment by jcoyne** [comment]
@jermnelson why not "restore the delete function to the button?"

**Comment by jcoyne** [comment]
There is a bunch of code related to this in app/javascript/spreadsheet.js

**Comment by andrewjbtw** [comment]
It doesn't appear that anyone uses it or noticed that it wasn't working. I didn't know it wasn't working.

But I could see an argument for keeping it and making it work again.

**Comment by jermnelson** [comment]
@andrewjbtw, should I change this issue to restore delete functionality for bulk_jobs?

**Comment by andrewjbtw** [comment]
Yes, now that I've thought about it more. We do want to be able to clean up those lists, even though no one seems to be doing so regularly. I'm not sure how we'd do it another way.

**Comment by mjgiarlo** [comment]
@jermnelson @andrewjbtw Amended the ticket title/desc and am now working on it. Thanks for writing it up, y'all.
