### ISSUE TITLE
Bulk updates for tags do not appear immediately

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1884]
**Describe the bug**
Tags that are updated via the bulk updates interface are not reindexed after the update is run. The effect is to make it look like the tags were never updated. After the items are reindexed, the new tags appear.

**User Impact**
Users can be left thinking that their tag updates didn't work when the tags were actually updated correctly. They have to take an extra step of reindexing before they can use the tags.

**To Reproduce**
1. Go to the bulk updates page
2. Choose "Paste a druid list"
3. Paste in one or more druids into the box
4. Choose "Tags" under "Options that do not require versioning"
5. A "Change Tags" tags interface will appear below
6. Add a new tag or modify existing tags. Note that tags should be tab-separated.
7. Go to the druids that you updated.
8. Look at the tags. They'll probably be the old ones.
9. Reindex the druids.
10. See the new tags appear.

**Expected behavior**
Tag changes should be applied immediately.

**Additional context**
When editing tags for individual items, the tag changes appear immediately. Only bulk updates have this issue.

**Comment by justinlittman** [comment]
According to @mjgiarlo:
```
Mike Giarlo (he/him)  8:22 AM
As far as I can tell, not reindexing bulk tags was the behavior prior to the recent admin tags work. I could have misread that, though. Let me pull up a link.

Mike Giarlo (he/him)  8:24 AM
This behavior is super easy to change, btw, so it's not a worrisome change, unless we're worried about numerous sequential hits to the indexer service.
8:25
Here's what happens currently: https://github.com/sul-dlss/argo/blob/master/app/controllers/items_controller.rb#L212-L216
8:25
And you can see the reindex method on that controller does not reindex if a :bulk param is truthy: https://github.com/sul-dlss/argo/blob/master/app/controllers/items_controller.rb#L458
8:26
That's why 1884 is the case.
8:26
Here's what used to happen: https://github.com/sul-dlss/argo/blob/7a381993c3f9c1cd425be556031fd2f5c4cc9a1a/app/controllers/items_controller.rb#L212-L221
8:27
so, the object's identityMetadata was instantly saved in Fedora which presumably triggered a message to index it in Solr

Justin Littman  8:27 AM
Makes sense.

Mike Giarlo (he/him)  8:27 AM
and this was called: https://github.com/sul-dlss/argo/blob/7a381993c3f9c1cd425be556031fd2f5c4cc9a1a/app/controllers/items_controller.rb#L450-L453
8:27
that's where the "check bulk param" logic came from
8:28
but maybe it is a bogus check now.
```

**Comment by andrewjbtw** [comment]
Confirming that this is working.
