### ISSUE TITLE
[PROXY] write DevOpsDocs for sulmq

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#1891]
at present, there is no useful internal documentation for maintaining sulmq, the ActiveMQ instance that brokers reindexing requests from Fedora (and other services?) to dor_indexing_app (are there other consumers of sulmq messages?).

we should write a basic DevOpsDocs entry covering e.g. which things are deployed where, how it's configured, how to restart it if it gets wedged, what might be of interest in the logs, etc.

related repo:  https://github.com/sul-dlss/dor-camel-routes

the closest thing i have to relevant documentation is the capture of a terminal session where willy helped me restart the broker while suspending and then resuming the activeMQ web console (attached).  and those notes are almost 6 years old, and were a bit out of date last time i tried to use them, iirc (though i'm not very confident in that recollection).

[restarting_camel_from_karaf_-_terminal_demo_from_willy_2014-08-12.log](https://github.com/sul-dlss/argo/files/4418318/restarting_camel_from_karaf_-_terminal_demo_from_willy_2014-08-12.log)

**Comment by justinlittman** [comment]
I'd suggest that ActiveMQ is a basic service that should be documented by Ops. We don't write DevOpsDocs for Postgres or Redis.

Of course, it would be helpful to write a brief description of the role of ActiveMQ.

**Comment by jmartin-sul** [comment]
> I'd suggest that ActiveMQ is a basic service that should be documented by Ops. We don't write DevOpsDocs for Postgres or Redis.
> 
> Of course, it would be helpful to write a brief description of the role of ActiveMQ.

good point, that thought had crossed my mind too.  my recollection is that ActiveMQ maintenance has fallen more to developers than e.g. postgres or redis.  but i agree that doesn't necessarily make sense, and this might be a good chance to revisit that.

opinion from @julianmorley, since he was the one to lament the lack of DevOpsDocs that's ticketed here?

**Comment by peetucket** [comment]
Unclear if this piece of infrastructure needs DevOpsDocs

**Comment by aaron-collier** [comment]
From a camel-routes discussion from @mjgiarlo 👍 

Do you think it needs its own DevOpsDocs or might what's in DIA already suffice? https://github.com/sul-dlss/DevOpsDocs/blob/9a8d634fe1bc0db59daa4f6975fbdb305197dff2/projects/dor_indexing_app/operations-concerns.md#how-do-i-know-this-application-is-running-correctly (It's in DIA's stack, and is a small routing component.)

Going to close this for now.
