### ISSUE TITLE
Remediate objects with no source id

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1894]
Except for the special case of ETDs, objects in SDR should have source ids. Unfortunately, over 10,000 are missing source ids. This ticket is for the effort to correct that.

There are two steps I am taking:

1.. Work with depositors and content owners to remediate source IDs for other content. Source IDs for digitization refer to the original source materials and can't be supplied programmatically according to an arbritrary naming scheme.

2. Determine if EEMS items ever had source IDs or other unique identifier outside of the SDR identifiers. If not, create a source ID scheme and run a bulk update to add the ids to the items. EEMS is no longer active, so there's a finite set to fix. EEMS items do not have an original physical source to refer back to as source ID.

This ticket replaces https://github.com/sul-dlss/google-books/issues/455 which was created as a proxy while Argo was not on the zenhub board.

**Comment by andrewjbtw** [comment]
Steps taken so far:

[ ] Request for help sent to depositors via email
[ ] Queried PSM and reviewed documentation on EEMS process

**Comment by jcoyne** [comment]
@andrewjbtw I don't see any items without a source id. Can this be closed? https://argo.stanford.edu/catalog?f%5Bdata_quality_ssim%5D%5B%5D=missing+sourceId&search_field=text

**Comment by andrewjbtw** [comment]
I think so. One popped up in indexing yesterday but we should be good with just checking honeybadger at this point.
