### ISSUE TITLE
Resolve "reset-workspace" errors cleanly

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1896]
**Describe the bug**
When the reset-workspace step in the accessionWF fails with

`reset-workspace : unable to reach dor-services-app`

re-running the step generates a new error:

```
reset-workspace : Unprocessable Entity: 422 ({"errors":[{"status":"422","title":"Archive directory already exists","detail":"The archived directory /dor/workspace/tb/226/vr/7771/tb226vr7771_v10 already existed."}]}) for druid:tb226vr7771
```
That error cannot be resolved with a re-run of the step. 

**User Impact**
Druids with either of these errors cannot be resolved easily from Argo.

**To Reproduce**
1. Go to any of the items with reset-workspace errors right now
https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=accessionWF%3Areset-workspace%3Aerror
2. Re-run one of the steps
3. End up with the 422 error

**Expected behavior**
It should be possible to reset this step cleanly. 

1. If the problem is that dor-services-app is unavailable, then it should work after reconnecting
2. If the problem is that the archived directory already exists because the step partially ran earlier, and if the archived directory is supposed to exist, then the step should validate that things are correct and resume where it left off.

**Additional context**
Assuming that the archived directory that exists is supposed to exist, then the step can be set to completed. There is no way to do this in batch and it is potentially risky to do this if the accession is not complete as expected. This puts the burden of validating that the data is correct on the person resolving the issue rather than on the accessioning system, which should be able to handle it.

**Comment by ndushay** [comment]
In accessionWF:

![image](https://user-images.githubusercontent.com/96775/79798301-a7211c80-830d-11ea-9b5d-ff2b5bfdbee5.png)
