### ISSUE TITLE
Request QA VMs for testing separate from staging environments

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#1897]
Transferred from sul-dlss/google-books#80

Includes: 

- [x] preservation_catalog
- [x] common-accessioning 
- [ ] gis-robot-suite (+ Postgres box)
- [x] hydrus
- [x] hydra_etd
- [ ] was-registrar-app
- [x] sul-dor (Fedora)
- [x] sul-suri
- [x] sulmq
- [x] dor_indexing_app
- [x] dor-services-app (+ Postgres box + workers)
- [x] workflow-server-rails (+ Postgres box)
- [x] robot-console
- [x] sul-robots-redis
- [x] preservation_robots
- [x] argo (+ MySQL box)
- [x] dor-fetcher-service (decommissioned)
- [x] sdr-api
- [x] google-books
- [x] modsulator-app-rails
- [x] pre-assembly
- [x] sul_pub
- [x] technical-metadata-service (+ workers)
- [x] was-thumbnail-service
- [x] was_robot_suite

See: https://github.com/sul-dlss/operations-tasks/issues/2114

**Comment by peetucket** [comment]
From Rob:

So I can grasp this a bit better, I've created a server list of the services listed above:

sul-dor-*
sul-solr-* (x2 for load balancing)
dor-indexing-app-* (x2 for load balancing)
dor-services-webapp
dor-services-db
workflow-services-*
robot-console-*
common-accessioning-*
sul-robots-redis-*
preservation-robots-*
argo-webapp (x2 for load balancing)
argo-mysql
dor-fetcher-*
preservation-catalog-* (x2)
sdr-api-*
google-books-*
kurma-robots-*
kurma-db-*
sul-hydra-etd-*
sul-hydrus-*
modsulator-app-rails-*
sul-preassembly-*
was-registrar-app-*
was-downloader-*
was-thumbnail-service-*
was-robots1-*

That totals about 30 new servers to be built, including load balancer configs, storage mounts, etc.

**Comment by peetucket** [comment]
See more comment history in sul-dlss/google-books#80

**Comment by mjgiarlo** [comment]
At this point, my focus is on getting the ETD app and then Argo in QA.

- [ ] ETD app
  - [ ] shared_configs
  - [ ] puppet
  - [ ] capistrano
  - [ ] integration test works (through ETD app steps)
- [ ] Argo
  - [ ] shared_configs
  - [ ] puppet
  - [ ] capistrano
  - [ ] integration test works (through end)
