### ISSUE TITLE
Argo history section makeover

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#190]
Address significant usability issues with the current History display as shown on the Argo detail page. The goal is a history that adds full version information, is properly grouped by version with a proper numerical sort, that sorts out current from archived workflows, etc. Early thoughts on new layout ...

![argohistory](https://cloud.githubusercontent.com/assets/1824732/11189993/298c331a-8c48-11e5-9976-fa7a82f71bff.png)

**Comment by mejackreed** [comment]
#191 should be a prerequisite
