### ISSUE TITLE
Type "Object" missing from resource types in "Set content type"

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#1906]
In the "Set content type" options, for resources, the type "object" (used when a PDF is accessioned into a "book" object) is missing, making it impossible to use "Set content type" to update that resource to "document" or "file".

User Impact: forces the user to hand-edit the contentMD to achieve the desired results.

**To Reproduce**
1. Go to an item of type book that contains a PDF
2. Click on "Set content type" (after preparing the object)
3. Scroll down to 'Old resource type'
4. See that there is no type "Object"

**Expected behavior**
Expected behavior is to represent existing resource types within the drop down so that all can be edited if necessary.

**Screenshots**
![Screenshot 2020-04-15 08 25 27](https://user-images.githubusercontent.com/796990/79356012-48b20380-7ef3-11ea-8a13-e20f6533efe3.png)

![Screenshot 2020-04-15 08 25 11](https://user-images.githubusercontent.com/796990/79356133-6da67680-7ef3-11ea-88d8-6646fa59dcdc.png)

**Comment by andrewjbtw** [comment]
Has this been fixed but not deployed? I don't see 'object' in the content type drop down menus when I go to Argo.

**Comment by aaron-collier** [comment]
@andrewjbtw perhaps... #1912 says it fixed it, but that was 19 days ago, so I would assume it's deployed. 

I will try to verify and reproduce before reopenning.

**Comment by andrewjbtw** [comment]
Re-opening as the dropdowns for content type still do not show 'object'.

**Comment by peetucket** [comment]
The PR #1912 was closed without merging, unclear why.  It should have added it.  Let me look into it.
