### ISSUE TITLE
Argo branding needs rework

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#192]
In firefox "Argo" text is present

<img width="446" alt="screen shot 2015-11-16 at 10 24 10 am" src="https://cloud.githubusercontent.com/assets/1656824/11190746/36acb750-8c4c-11e5-9935-7de0424b3955.png">

**Comment by LynnMcRae** [comment]
I thought this showed in Safari as well, not not now.  

Please make the text larger so it has more presence in the upper left.

**Comment by LynnMcRae** [comment]
Would still like the specific font shown in #259, rendered as part of the image if needed per Jack's comments.

**Comment by mejackreed** [comment]
Cannot reproduce. Please open if still an issue.
