### ISSUE TITLE
Restore column selection functionality for reports view

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1920]
Argo's report view displays a list of columns. It used to be possible for users to interactively select specific columns to display in this view. This ticket is the restore that functionality.

**Additional background**

In fall 2019, column selection functionality ceased to work following a set of javascript upgrades made during the fall maintenance workcycle. As I understand it, some of the libraries the old functionality relied on are no longer maintained, and keeping the function in Argo as it was presented a security risk.

The ability to select columns for downloaded reports was restored last fall, but restoring in-browser column selection had to be deferred into the next maintenance work cycle owing to time and resourcing constraints.

**Comment by jcoyne** [comment]
The javascript library that supports the report and the registration is not something that is supported by its author any longer.  We really ought to look at replacing that script entirely.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/82082771-6cf13380-969d-11ea-9357-f98a528dcf04.png)
