### ISSUE TITLE
request VMs for automated dependency updates/deployments

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#1924]
we'd like to request a new VM for the infrastructure team:
- [ ] one from which we can run the automated dependency update script (https://github.com/sul-dlss-labs/sdr-deploy/).  this will provide a shared space for doing this work.  this is nice because it requires cloning many repos and SSHing into many VMs, both of which are a pain to do from an individual dev's laptop.  a shared space also means the initial cloning also has to happen once, instead of once for each person who runs the script.

this might be a good opportunity for the pairing we'd like to do with ops to see their process for writing terraform to spin up VMs.

neither of these VMs is directly for argo usage, but argo is our go-to repo for tickets without a natural home, so that's why i'm filing it there.

**Comment by aaron-collier** [comment]
Tracking: https://github.com/sul-dlss/operations-tasks/issues/2258

**Comment by jcoyne** [comment]
This description says "we'd like to request two new VMs for the infrastructure team:"  does that need to be changed?

**Comment by jmartin-sul** [comment]
fixed

**Comment by aaron-collier** [comment]
Setup: https://github.com/sul-dlss/puppet/blob/production/hieradata/node/sdr-deploy.stanford.edu.eyaml
