### ISSUE TITLE
wf grid view table should not use crazy custom styling

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#193]
Currently not adhering to responsive table

**Comment by mejackreed** [comment]
@blalbrit & @LynnMcRae How tied are we to this design? Colors, etc?

<img width="1062" alt="screen shot 2015-11-25 at 12 40 41 pm" src="https://cloud.githubusercontent.com/assets/1656824/11404813/e6f0cf80-9371-11e5-803a-c715295c7117.png">

**Comment by LynnMcRae** [comment]
@mejackreed asks "How tied are we to this design? Colors, etc?"  Depends on the "etc" I think.  Responsive design per se is not a priority in the 3.0 pass -- we've never had a complaint or a request to support narrow screens, while the table does grow past a minimum. But other than the colorful column headings, the tables themselves are rather vanilla? They would have the same content? Can be tweaked in standard ways (say, to keep the first column narrow)?  Or are there concerns about the page overall, with multiple tables?  btw, the final row -- Completed/archived workflows -- is broken I think, and could be removed for now.

**Comment by LynnMcRae** [comment]
as for column heading colors, they are nice, useful, appealing ... I would be sad to lose them.  Can responsive tables not have background colors in individual cells?

**Comment by mejackreed** [comment]
No they can, just wanted to see how tied we are to _those_ colors? I really feel like having a page element break your page layout is unacceptable:

<img width="805" alt="screen shot 2015-11-25 at 1 06 34 pm" src="https://cloud.githubusercontent.com/assets/1656824/11405388/66affa72-9375-11e5-95d8-b0c3a2cc2307.png">
 
And instead of maintaining our own table layout, and design code, why not just use the one that we get for free?

**Comment by LynnMcRae** [comment]
I don't get how "those colors" force the table to behave badly. Or are we taking about two unrelated things?  The table itself is just a table and has no requirement that precludes it from being created a better way afaik.

**Comment by blalbrit** [comment]
Colors are not strictly fixed, as far as I'm concerned. I think there was a notion that they carried a bit of visual meaning (red column header for errors), but what we get for free seems acceptable to me.
