### ISSUE TITLE
Having the full reindex query be repeatable

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#194]
We don't really have a good repeatable way to get the entire list of things to reindex.

**Comment by jmartin-sul** [comment]
@rosy1280 @LynnMcRae @blalbrit

in what order should the object types be reindexed?  e.g., uber APO, then APOs in general, then collections, etc.  something like that.

if no one knows off-hand, or we're unsure, there are email threads from last year when the index got wiped, and those might have useful info about what we did then.  we definitely ran into an issue with this, and had to re-run the indexing in full with the correct order.

**Comment by rosy1280** [comment]
Uber APO, agreements, APOs, collections, items. In that order.

**Comment by rosy1280** [comment]
Although maybe the workflow items also need to be indexed early? Perhaps Lynn remembers.

**Comment by jmartin-sul** [comment]
there are a few other types besides those, though i'm guessing order doesn't matter for all of it?  here are the object types in current use (from the model facet on argo prod):

info:fedora/afmodel:Dor_Item (838902)
info:fedora/dor:googleScannedBook (187505)
info:fedora/afmodel:Part (9028)
info:fedora/afmodel:Etd (3585)
info:fedora/afmodel:Hydrus_Item (3503)
info:fedora/afmodel:Eems (2793)
info:fedora/afmodel:PermissionFile (2433)
info:fedora/afmodel:Dor_Collection (1150)
info:fedora/afmodel:Dor_AdminPolicyObject (744)
info:fedora/afmodel:Hydrus_AdminPolicyObject (634)
info:fedora/afmodel:Hydrus_Collection (599)
info:fedora/afmodel:Eem (420)
info:fedora/afmodel:Dor_Set (34)
info:fedora/afmodel:Dor_WorkflowObject (22)
info:fedora/afmodel:agreement

the hydrus versions with their non-hydrus counterparts?  workflow objects before items?  what about sets?

i think dor-test has a few object types that dor-prod doesn't, guessing that won't be a big deal in our testing.

**Comment by rosy1280** [comment]
Uber APO, workflows, agreements, Hydrus Uber APO, All APOs (hydrus and non-hydrus), collections/sets (most sets are collections as well), items.  

Thinking about what information gets displayed, I think this is the best way to do reindexing.  The objects that you've put counts for that aren't mentioned in the above list can just be put into items.  Make sense?

**Comment by LynnMcRae** [comment]
Ben and I came up with the same list working independently. As for the kitchen sink of extra models that can be treated like items, I think you could do the googleScannedBook objects last if that helps divvy things up. And be sure to cast out duplicates; all "part" and "PermissionFile" objects are also "items" for instance.  Also, note that while we have 35 agreements per Object Type facet, we only have 3 instance of the "agreement" model.  I think the ObjectType facet is the better source for those distinctions.

**Comment by jmartin-sul** [comment]
great, thanks everyone.  that's what i was looking for.  might have follow up questions later.
