### ISSUE TITLE
New Blacklight 7 color palette for facets

### ISSUE THREAD

**Issue by astridu** [sul-dlss/argo#1941]
![image](https://user-images.githubusercontent.com/42216982/80426249-2f696980-889a-11ea-9628-267c6b852990.png)
1. For selected facet: header bg fill AND border = B3995D

2. For unselected facet:
a) header bg fill = F8F6EF
b) border = D2C295

3. For selected drop downs in search results, fill AND border = B6B1A9

**Comment by jcoyne** [comment]
@astridu 
<img width="941" alt="Screen Shot 2020-04-28 at 2 42 50 PM" src="https://user-images.githubusercontent.com/92044/80530431-9c463780-895e-11ea-89d6-49ad37c98c8f.png">

Bootstrap has the text color of the panels default to the same as the header color. Do you want to change that to something particular?

**Comment by astridu** [comment]
Yes, can you turn it to black? That color isn't accessible on a white background. Thanks!
