### ISSUE TITLE
[Blacklight 7] Anchor-style buttons should have text color of #fff

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#1948]
See the discrepancy here in the button text between the upper (`<a>`-style) button and the lower (`<button>`-style) button. Note that both do use both the `btn` and `btn-primary` classes.

![Screenshot from 2020-04-29 09-18-23](https://user-images.githubusercontent.com/131982/80620368-c2b9b080-89fa-11ea-896d-2acb5228ebaf.png)

Copying @astridu to confirm (or correct)!

Heads-up, @jcoyne

**Comment by jcoyne** [comment]
Thanks @mjgiarlo, it looks like this one was an aberation because it was an anchor without an `href` attribute.

**Comment by mjgiarlo** [comment]
Argo, an aberration? Nah, no way.
