### ISSUE TITLE
Show SearchWorks link on page if the item has been released

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1974]
The upper left corner of the Argo item show page has a space for useful links:

- Searchworks
- PURL
- FedoraUI
- FoXML
- Solr document

Currently, the SearchWorks link only seems to display if an item has a catkey. It does not appear to display if an item has been released to SearchWorks but does not have a catkey.

Example: https://argo.stanford.edu/view/mt574ws5287

Adding a link to SearchWorks when an item has been released would help users when checking on items from Argo, particularly during QC following a release.

**Comment by jcoyne** [comment]
@andrewjbtw the link seems to be based on the catkey, so we have no way of linking without it:

```
"http://searchworks.stanford.edu/view/#{catkey}"
```

**Comment by andrewjbtw** [comment]
This is a request for a way. It looks like for druids with no catkey, the SearchWorks URL uses the form:

https://searchworks.stanford.edu/view/{druid}

The example druid above is on SearchWorks at
https://searchworks.stanford.edu/view/mt574ws5287

**Comment by jcoyne** [comment]
@andrewjbtw currently there is no check for "released to searchworks" on that link.  Do we need to add that?

**Comment by andrewjbtw** [comment]
I think we do. It looks like the link will always work if there's a catkey, release or not, but once we add the druid URLs we'll need to check since something like 60% of druids aren't in SW.
