### ISSUE TITLE
Silent failures at shelve result in no files sent to Stacks

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1989]
**Describe the bug**
Sometimes the shelve step fails during accessioning and no files reach Stacks even if "shelve=yes". Accessioning does not report an error when this happens and all workflows eventually complete. The result is a purl that shows an error in the viewer.

**User Impact**
For accessioners, this creates a problem where accessioning appears complete but it is not. The problem on the purl may only be discovered later during QC or when a viewer encounters it.

For public users, the impact is not being able to view content online.

For repository administrators, this results in potentially time-consuming remediations. If the shelved file is not preserved (i.e. the file is a system-generated JP2 created solely for access purposes), then the file will need to be regenerated. It cannot simply be copied onto Stacks. This requires reaccessioning via re-running the assemblyWF.

Also, sometimes extra steps need to be taken to ensure the files get shelved during reaccessioning. The accessioning robots analyze the contentMetadata to determine whether to shelve files. If the contentMetadata indicates that a file has already been shelved, it will not be shelved during reaccessioning. This means that if shelving fails with no error message, then reaccessioning will fail to shelve any file that is already recorded as shelved in the contentMetadata - whether or not the file is actually present on Stacks. So fixing the problem requires manipulating the contentMetadata to treat all shelved files as new. This requires either setting rights to dark - which forces any shelved files to be unshelved - or complex hand-editing of the contentMetadata.

**Expected behavior**
If shelving fails, the failure should be reported and accessioning should not complete. 

Completing the accessioning workflow is especially a problem because it results in cleaning up the /dor workspace, which means that files that are not preserved are deleted. They then need to be regenerated in order to be shelved during a later attempt.

**Examples**
I've found examples with a variety of right statuses. All of these were first accessioned within the last 30 days. Note that because Stacks enforces restrictions on many of these items, it may be necessary to check for the actual druid tree on the Stacks server itself to verify if a file has been shelved.

World, no download
https://argo.stanford.edu/view/ms337hf3814
https://argo.stanford.edu/view/xr589mp6673
https://argo.stanford.edu/view/zs367qy7536

Stanford, no download
https://argo.stanford.edu/view/fr873gt3270

Location-restricted (spec, ars)
https://argo.stanford.edu/view/druid:fq133gd8884
https://argo.stanford.edu/view/druid:jf760tr7331
https://argo.stanford.edu/view/druid:gq367yn1958
https://argo.stanford.edu/view/druid:gy439tf3018
https://argo.stanford.edu/view/druid:hc232qh7707
https://argo.stanford.edu/view/druid:hm957th9926
https://argo.stanford.edu/view/druid:hn881wb4106
https://argo.stanford.edu/view/druid:hp315gk2007
https://argo.stanford.edu/view/druid:hw298qv7988
https://argo.stanford.edu/view/druid:hw454mt3143
https://argo.stanford.edu/view/druid:jk166rq1836
https://argo.stanford.edu/view/druid:qd597bh8245

**Comment by jcoyne** [comment]
On dor-services-app in production.log-20200502.gz
```
I, [2020-05-01T11:46:47.483883 #75750]  INFO -- : [a7f612b3-5b3e-47f2-bed8-d706a01e98bd] Started POST "/v1/objects/druid:ms337hf3814/shelve?lane-id=default" for 171.67.21.166 at 2020-05-01 11:46:47 -0700
I, [2020-05-01T11:46:47.485866 #75750]  INFO -- : [a7f612b3-5b3e-47f2-bed8-d706a01e98bd]   Parameters: {"lane-id"=>"default", "object_id"=>"druid:ms337hf3814"}
D, [2020-05-01T11:46:47.571616 #75750] DEBUG -- : [a7f612b3-5b3e-47f2-bed8-d706a01e98bd]   Event Create (0.5ms)  INSERT INTO "events" ("event_type", "druid", "data", "created_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["event_type", "shelve_request_received"], ["druid", "druid:ms337hf3814"], ["data", "{\"background_job_result_id\":1011380,\"host\":\"dor-services-prod.stanford.edu\",\"invoked_by\":\"common-accessioning\"}"], ["created_at", "2020-05-01 18:46:47.570469"]]
I, [2020-05-01T11:46:47.573842 #75750]  INFO -- : [a7f612b3-5b3e-47f2-bed8-d706a01e98bd] [ActiveJob] Enqueued ShelveJob (Job ID: 9593c882-48d6-469d-86d7-979b3e68e632) to Sidekiq(default) with arguments: {:druid=>"druid:ms337hf3814", :background_job_result=>#<GlobalID:0x00007fde80733ca8 @uri=#<URI::GID gid://dor-services/BackgroundJobResult/1011380>>}
```

Then on the worker box there is every indication things completed successfully:
```
[dor_services@dor-services-worker-prod-a log]$ zgrep 1011380 production.log-20200502.gz
D, [2020-05-01T11:49:16.538472 #13624] DEBUG -- :   BackgroundJobResult Load (0.5ms)  SELECT  "background_job_results".* FROM "background_job_results" WHERE "background_job_results"."id" = $1 LIMIT $2  [["id", 1011380], ["LIMIT", 1]]
I, [2020-05-01T11:49:16.539021 #13624]  INFO -- : [ActiveJob] [ShelveJob] [9593c882-48d6-469d-86d7-979b3e68e632] Performing ShelveJob (Job ID: 9593c882-48d6-469d-86d7-979b3e68e632) from Sidekiq(default) with arguments: {:druid=>"druid:ms337hf3814", :background_job_result=>#<GlobalID:0x000000000543a3c8 @uri=#<URI::GID gid://dor-services/BackgroundJobResult/1011380>>}
D, [2020-05-01T11:49:16.540802 #13624] DEBUG -- : [ActiveJob] [ShelveJob] [9593c882-48d6-469d-86d7-979b3e68e632]   BackgroundJobResult Update (0.6ms)  UPDATE "background_job_results" SET "status" = $1, "updated_at" = $2 WHERE "background_job_results"."id" = $3  [["status", "processing"], ["updated_at", "2020-05-01 18:49:16.539776"], ["id", 1011380]]
D, [2020-05-01T11:49:16.685038 #13624] DEBUG -- : [ActiveJob] [ShelveJob] [9593c882-48d6-469d-86d7-979b3e68e632]   Event Create (0.9ms)  INSERT INTO "events" ("event_type", "druid", "data", "created_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["event_type", "shelving_complete"], ["druid", "druid:ms337hf3814"], ["data", "{\"background_job_result_id\":1011380,\"host\":\"dor-services-worker-prod-a.stanford.edu\",\"invoked_by\":null}"], ["created_at", "2020-05-01 18:49:16.683593"]]
I, [2020-05-01T11:49:16.687885 #13624]  INFO -- : [ActiveJob] [ShelveJob] [9593c882-48d6-469d-86d7-979b3e68e632] Enqueued LogSuccessJob (Job ID: 716dbd51-104c-487c-a8c7-7482e7f8eb31) to Sidekiq(default) with arguments: {:druid=>"druid:ms337hf3814", :workflow=>"accessionWF", :background_job_result=>#<GlobalID:0x00000000053aaea8 @uri=#<URI::GID gid://dor-services/BackgroundJobResult/1011380>>, :workflow_process=>"shelve-complete"}
D, [2020-05-01T11:49:16.689655 #13621] DEBUG -- :   BackgroundJobResult Load (0.4ms)  SELECT  "background_job_results".* FROM "background_job_results" WHERE "background_job_results"."id" = $1 LIMIT $2  [["id", 1011380], ["LIMIT", 1]]
I, [2020-05-01T11:49:16.690185 #13621]  INFO -- : [ActiveJob] [LogSuccessJob] [716dbd51-104c-487c-a8c7-7482e7f8eb31] Performing LogSuccessJob (Job ID: 716dbd51-104c-487c-a8c7-7482e7f8eb31) from Sidekiq(default) with arguments: {:druid=>"druid:ms337hf3814", :workflow=>"accessionWF", :background_job_result=>#<GlobalID:0x0000000004ccbd58 @uri=#<URI::GID gid://dor-services/BackgroundJobResult/1011380>>, :workflow_process=>"shelve-complete"}
D, [2020-05-01T11:49:16.691903 #13621] DEBUG -- : [ActiveJob] [LogSuccessJob] [716dbd51-104c-487c-a8c7-7482e7f8eb31]   BackgroundJobResult Update (0.6ms)  UPDATE "background_job_results" SET "status" = $1, "updated_at" = $2 WHERE "background_job_results"."id" = $3  [["status", "complete"], ["updated_at", "2020-05-01 18:49:16.690919"], ["id", 1011380]]
```

**Comment by justinlittman** [comment]
Running through the code, this is the diff returned from PresCat:
```
2.7.0 :024 > deltas = shelve_diff.file_deltas
2.7.0 :025 > deltas
 => {:identical=>["1975-03.jp2"], :modified=>[], :deleted=>[], :copydeleted=>[], :copyadded=>[], :renamed=>[], :added=>[]} 
```
at https://github.com/sul-dlss/dor-services-app/blob/master/app/services/shelving_service.rb#L54

This would cause `workspace_content_pathname` to be nil triggering the silent failure in https://github.com/sul-dlss/dor-services-app/blob/master/app/services/digital_stacks_service.rb#L81 (although not really a failure; it's handling when there is nothing to copy to stacks).

**Comment by justinlittman** [comment]
I believe that there is a race condition between shelving and preservation. In this case, preservation was completed (May 1, 2020 2:46PM) before shelving (May 1, 2020 2:49PM). In this case, checking the `shelve_content_diff` returns no diffs since it is checking against the wrong version.

**Comment by justinlittman** [comment]
I suspect it can be fixed by making `shelve-complete` a prereq of `preservation-ingest-initiate`.

**Comment by jcoyne** [comment]
Alternately, this approach https://github.com/sul-dlss/argo/issues/1789#issuecomment-617730236 would knock out two birds with one stone.

**Comment by ndushay** [comment]
maybe this ticket shouldn't be in the review/qa column?

**Comment by andrewjbtw** [comment]
Huh, I believe this is done but was fixed via some workflow step changes that weren't linked to the ticket. I'm closing it.
