### ISSUE TITLE
Implement result sorting

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#199]
A Sort button has been added with options for Druid (default), Relevance, and "Creator and Title".  Questions...
- What drives relevance? some simple built-in behavior based on multi-word hits, exact vs stemming etc? 
  Is it useful out of the box?
- What is "Creator and Title" based on?

Here were additional requests from the JIRA ticket (will split to separate ticket based on discussion here)
- title 
- source-id (requested by digilabs) 
- old-to-new, new-to-old (by registration-date)

**Comment by mejackreed** [comment]
To answer your questions:

>What drives relevance?

Score, descending order. https://github.com/sul-dlss/argo/blob/develop/app/controllers/catalog_controller.rb#L131

This score seems to be calculated from these lines in our Solr config: https://github.com/sul-dlss/argo/blob/develop/solr_conf/conf/solrconfig.xml#L43-L72

**Comment by LynnMcRae** [comment]
Perhaps @atz or @suntzu can interpret and say what in an object would rank something higher or lower.  This is mainly so we know and can explain it to others, or eliminate it if not actually doing anything.  Argo would have only fairly generic relevancy requirements, like all word hits over some word hits, full string match over partial, etc. Not sure if these latter have any built in support.

**Comment by jmartin-sul** [comment]
@mejackreed's answer is more concrete than anything i could provide, but @atz can probably elaborate or give examples?

**Comment by mejackreed** [comment]
If we can kill relevance and we only want, title, source-id, and reg date, that makes things simpler

**Comment by LynnMcRae** [comment]
Let's kill relevance then; make sure druid stays in your list above!

**Comment by cbeer** [comment]
:-1: I'm surprised at the hate for search relevancy. It's a powerful tool for helping users find what they're looking for. Maybe Argo power-users don't need it (because they are only doing known item or collection queries), but for casual users (which I'd classify myself as..), being able to search for e.g. a title (and get relevant results!) can be really useful.

**Comment by mejackreed** [comment]
Ok so sorting should feature:
 - [ ] druid `id`
 - [ ] title `title_sort_ssi`
 - [ ] source-id `source_id_ssim`
 - [ ] registration date `originInfo_0_date_created_tesim`?
 - [ ] relevancy ????

**Comment by LynnMcRae** [comment]
No hate on relevancy here, just willing to omit it for now since Argo never had it and we have not stated any requirements so it shouldn't hold up this ticket.  I'd like to know what we are throwing into the keyword search since that's never been documented. Are any of the new MODS based values in the index being included in the keyword search? If the list contains title and non-title fields, then that's an obvious candidate for relevancy, that is author over subject names, then possibly abstract. But I'm guessing this is the basis for a new ticket and separate effort.

**Comment by LynnMcRae** [comment]
@mejackreed for registration date, that appears to be a work create date from the MODS, not the birthdate of the object.  Is the Fedora object creation date in the index somewhere?

**Comment by LynnMcRae** [comment]
did something with date created and results get promoted to argo-dev or is this a coincidence? I get this error on display there now:

Showing /opt/app/lyberadmin/argo/releases/20151117174220/app/views/catalog/_show_field_list.html.erb where line #7 raised:

argument out of range
Extracted source (around line #79):

def value_for_originInfo_date_created_tesim(args)
val = Time.parse(args[:document][args[:field]].first)
val.localtime.strftime '%Y.%m.%d %H:%M%p'
end

**Comment by LynnMcRae** [comment]
Relevancy ranking ticket #211

**Comment by blalbrit** [comment]
Closing for now - search sorting should be revisited in a future iteration of Argo depending on user needs.
