### ISSUE TITLE
Provide interface for creating (not just updating) embargos in Argo - and for setting access upon embargo release

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2009]
Users (particularly University Archives) need to be able to set embargos for items. Currently, there is no user-facing UI for this in Argo. Instead embargos need to be set via adding an embargo datastream administratively. As far as I know, this means directly interacting with Fedora.

There are two components to being able to set embargos in Argo:

1. Adding the ability to create an embargo from an Argo item page.
2. Adding the ability to add/edit embargos in bulk.

Users are currently able to set embargos from the Hydrus and ETD apps. If an item already has an embargo set, Argo provides a button on the left side of the item page that allows you to manage it. If an embargo is not set, the button does not appear.

And remember:  there's no "embargo" without "argo"

related to (could be concurrent with?) Argo #2674 - providing all allowed access levels upon embargo release.

**Comment by ndushay** [comment]
In addition to any unit and feature tests in Argo, this should get an infrastructure-integration-test:

- create an embargo, then check to see that it is correctly in index, in the (Fedora) rights.xml and embargo.xml, and in the cocina access.xml (?), and displays correct date on Argo item page, and is correct in the purl xml.
- update the embargo to a diff date and check that all of the above changed
- ?? remove an embargo ??  and check that all of the above changed.

Some of the model tests exist in the integration-tests:
- hydrus embargo test
- h2 embargo test

**Comment by jcoyne** [comment]
@ndushay while I understand the need to ensure the pieces of the system work together, I'm unsure why this feature would required a new integration test. We already have 4 separate tests that show that dor-services-app sends embargo data to purl.  We can within the bounds of the Argo test suite show that this sends the correct data to dor-services-app.  This feature change does not touch any other integration beyond dor-services-app.   Integration tests are very slow and we must be judicious over which tests we add there.

**Comment by andrewjbtw** [comment]
For the single object interface, we can make use of the space on the blue button list that's currently used by the "Update embargo" button:

<img width="242" alt="Screen Shot 2021-04-14 at 8 50 44 AM" src="https://user-images.githubusercontent.com/8975583/114740413-ad6a8e80-9cfe-11eb-823d-246b96a5f99f.png">

That button currently only appears when an embargo is active. Changes to make for the button:

- show it all the time
- if the there's no embargo, label it "Create embargo"
- if there is an embargo, label it "Manage embargo"
- if it can only have one name all the time, label it "Manage embargo"

The button currently pops up a modal that allows you to change an embargo date. To accommodate creating embargoes, it should be modified to present:

- a way to select the release date
- a menu to select the rights to be applied upon release

![image (1)](https://user-images.githubusercontent.com/8975583/114743673-c0329280-9d01-11eb-8d6b-a66857bd55e7.png)

**Comment by jcoyne** [comment]
I think this refactor will make this easier to implement: https://github.com/sul-dlss/argo/pull/2663

**Comment by ndushay** [comment]
This will use the DSA object update endpoint, per discussion in sul-dlss/dor-services-app/issues/2672

**Comment by ndushay** [comment]
this will require https://github.com/sul-dlss/dor-services-app/issues/2691 -- a way to specify the rights to be applied when an embargo is released.

**Comment by ndushay** [comment]
@jcoyne so will this need a change to dor-services-app, or should https://github.com/sul-dlss/dor-services-app/issues/2691 be closed?

**Comment by jcoyne** [comment]
@ndushay if we use the update endpoint, it already supports the rights to be applied, yeah?

**Comment by jcoyne** [comment]
@ndushay I'd close https://github.com/sul-dlss/dor-services-app/issues/2691

**Comment by ndushay** [comment]
@andrewjbtw:  DSA currently supports "world" "dark" or "stanford" for access rights.

@jcoyne suggests that we start with implementing those 3 in the pull down, and then add to it -- this means this ticket is actionable NOW.

I can make the following tickets:
- add other options to possible embargo release access here:  https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/embargo.rb -- @andrewjbtw can you please provide a list?
- change dor-services-app to allow the additional cocina access options
- ensure dor-services-client can send the appropriate access information for the additional supported cocina access options
- update Argo with the additional options in the pulldown and the code to support sending the correct information to DSA via DSC.
-

**Comment by andrewjbtw** [comment]
I'm not confident that a request to implement embargo releases to a not yet supported rights setting would be prioritized during non-SDR work cycle periods, so while we are in a work cycle, I'd like to get those cases covered. The supported settings should be all the object-level rights available on the rights menu.

**Comment by ndushay** [comment]
@andrewjbtw I can assure you that I will ticket the additional work and get it prioritized to be finished before the end of the work cycle.  :-).   I'll write the additional tickets right now and mark most of them as blocked by this ticket

**Comment by andrewjbtw** [comment]
I should add that arguably, an embargo should only support increasing rather than limiting access but

- it may be simpler to show the same rights menu here instead of customizing just for embargoes
- only citation-only and dark would be excluded if we excluded anything
- the idea was suggested for digital borrowing that items could be set to "expire" at the end of the quarter by automatically changing to citation-only or dark via embargo release. We have not been asked to implement this but it also has not been categorically ruled out.

**Comment by ndushay** [comment]
this is also related to some work JLitt is doing around sul-dlss/cocina-models#253
