### ISSUE TITLE
Improved interactions for Collection and APO facet navigation

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#201]
These facets have grown to be several hundreds of entries long (over 500), yet is often the first or primary means of limiting queries to the entries you want. Finding the name you want is a challenge that an alphabetized sort would not address, because you many not know/remember that Red-Dennis is "The Reid W. Dennis Collection ...", that it's "Glen McLaughlin Maps Collection -- Maps of Malta" but "The Glen McLaughlin Map Collection of California as an Island", that several collections end "....collection of the Revs Institute". Because of this, we have let the facet display grow arbitrarily large in order use the browser find (cmd-F) to do string matching. This is actually not a bad solution, but we assume could be improved. 

The "more" option built into blacklight is not suitable .. it will only support navigation to leading letters in a sub-divided alphabetical entry. One idea is a simple text entry box with some form of auto-complete behavior, dynamically offering matches based on string match anywhere in the value. Whether this supplements or replaces the full facet listing is a separate question, as the browse of a full list of available collections and APO can be useful sometimes.

**Comment by drh-stanford** [comment]
this sounds more like a core Blacklight feature as this problem is common to many Blacklight apps. maybe we could file an issue over there too

**Comment by justinlittman** [comment]
![2018-12-05_1159](https://user-images.githubusercontent.com/588335/49530230-d30d4080-f885-11e8-9c64-88eb841180cf.png)
