### ISSUE TITLE
Port "Set object rights" bulk update to bulk action

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2030]
**Existing update method**

This bulk update takes a list of druids and presents the user with the rights menu.

**When porting to bulk action**

The bulk action should offer the same interaction: a list of druids + the rights menu. The rights chosen from the menu will then be applied to the druids on the list.

**Comment by andrewjbtw** [comment]
https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/463636135

![bulk-object-rights](https://user-images.githubusercontent.com/8975583/153558852-ef7f122d-0f59-492a-8ac0-7c62a488102c.png)

**Comment by andrewjbtw** [comment]
As @lwrubel pointed out in another bulk action "port" ticket (#2031), in the existing bulk actions the druid box is the last box on the page and the menus are at the top. For consistency, the rights menu should be placed above the druid box on this action as well.
