### ISSUE TITLE
Support independent management of Use and Reproduction, Copyright and License statements

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#204]
These are bound in rights and established during registration based on the APO. We need both flexibility to alter/substitute any of these statements at registration time, as well as separate editing/setting of these values later as a remediation. 
- Provide values for any of the three to override APO default 
- Blue button on individual object showing old values and letting you edit them 
- Bulk action to replace these selectively from APO or set explicit values for any of these across a population

**Comment by blalbrit** [comment]
Specifically, could we do something like pair collections with collection-specific use & repro statements in adminMD so that if a user chooses a collection at registration, the appropriate U&R gets applied?

**Comment by andrewjbtw** [comment]
I'm not sure I fully understand all aspects of this ticket, but it seems like supporting this would reduce the need to edit datastreams (specifically, rightsMetadata) directly.

**Comment by jcoyne** [comment]
@andrewjbtw can we close this in favor of #2864, #2866, & #2867?

**Comment by andrewjbtw** [comment]
Now covered by the new UI and the bulk action for rights statements.
