### ISSUE TITLE
Improve reliability of item registration

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2043]
**Describe the bug**
Item registration via Argo is failing more frequently than it used to. In the past week, multiple batches of ~500 items registered as part of EVIS project work have run into ~15 errors per batch. These errors leave some druids created, but with "Unknown Status" and without the full set of datastreams and tags that should have been created.

**User Impact**
Users have to find the items that failed to finish registration, purge them, and then re-register those source_ids.

**Expected behavior**
Registration has never been error-less, but this is a higher frequency of errors than we've seen in the past.

**Comment by jcoyne** [comment]
I think this is mostly timeout errors: https://app.honeybadger.io/projects/49894/faults/63774660

**Comment by andrewjbtw** [comment]
This was addressed via some changes made to improve Google Books registration.
