### ISSUE TITLE
Published is always "pending" in lifecycle display

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2060]
**Describe the bug**
The lifecycle display is always showing "Published" as "pending":

![Screen Shot 2020-05-19 at 11 15 23 AM](https://user-images.githubusercontent.com/8975583/82363064-2ca5f400-99c2-11ea-829c-9392fc32da04.png)

**User Impact**
It's confusing but doesn't seem to be a sign of a functional problem. Publish seems to be happening successfully.

**Additional context**
This seems to have started after we removed the *-complete steps recently.

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/workflow-server-rails/pull/384 is a fix for new accession workflows.

It looks like this has been a problem for new accession workflows created in the last 2 weeks. @andrewjbtw is remediation of the existing workflows required? Doing some involves a minor amount of risk. (Happy to explain in more detail.)

**Comment by andrewjbtw** [comment]
This has been fixed and we decided that correcting the display of the lifecycles that show "pending" for published is not worth the time and risk, as there's no functional effect of doing so.
