### ISSUE TITLE
When setting an agreement from the APO edit form, any previous agreement is not removed from RELS-EXT

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#2061]
When fixing #787, I noticed that if you select a new agreement when editing an APO, the new agreement gets added to RELS-EXT but the previous agreement does not get removed, leaving with you multiple agreements like this in the RELS-EXT:

`<hydra:referencesAgreement rdf:resource="info:fedora/druid:xf765cv5573"/>`

The edit APO form in Argo just picks the first agreement found, making it look like it didn't change.

The agreement is set in Argo here: https://github.com/sul-dlss/argo/blob/master/app/forms/apo_form.rb#L42

The bug is likely in dor-services gem itself, some spots to explore:

https://github.com/sul-dlss/dor-services/blob/master/lib/dor/models/admin_policy_object.rb#L33-L37

**Comment by jcoyne** [comment]
Ref https://github.com/sul-dlss/dor-services/pull/704
