### ISSUE TITLE
WARC files have incorrect mime-type.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2069]
See for example https://argo.stanford.edu/view/druid:hr667xs8693

The mime-type is recorded as `application/octet-stream` but the mime-type for warc files should be `application/warc`

The tech-md service has recorded `application/gzip`, which is closer, but no bullseye.

**Comment by justinlittman** [comment]
Ultimately this comes from https://github.com/sul-dlss/WASMetadataExtractor/blob/master/src/edu/stanford/sulair/dlss/was/metadata/reader/WAReader.java#L47
