### ISSUE TITLE
BL7: Text box resizing on Bulk updates page

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2076]
On the Bulk Updates page, the text boxes can only be resized vertically rather than horizontally when dragging the bottom right corner of the text box to re-size.

Also, the top text box (the one that lists druids) does not resize itself when the window is made narrower. The text boxes in the lower part of the page do resize with the window width.

**Comment by jcoyne** [comment]
@andrewjbtw "text boxes can only be resized vertically" is the behavior of Bootstrap 4. I don't think that's a concern for this window, is it?

<img width="994" alt="Screen Shot 2020-06-01 at 10 50 19 AM" src="https://user-images.githubusercontent.com/92044/83427059-bb206980-a3f5-11ea-8c35-e101e25c970a.png">

Regarding the second point, this is the existing behavior of argo:

<img width="449" alt="Screen Shot 2020-06-01 at 10 57 25 AM" src="https://user-images.githubusercontent.com/92044/83427679-b60fea00-a3f6-11ea-8be6-712028e77f67.png">

**Comment by andrewjbtw** [comment]
Neither of these are essential, but the lack of horizontal text box resizing (via drag and drop) is noticeable for the tags and source_id bulk updates, where you need to paste data into the lower box. Maybe what's throwing me off about that display is the fact that the instructions extend so much farther to the right than the text box at certain window widths (like half of my 1920x1080 monitor).

I also just noticed that line wrapping in that box is making the display more confusing, though copying and pasting the data still gets the correct one druid per line. If that can be made to scroll horizontally with one druid per line, I think that would be enough.

![Screen Shot 2020-06-01 at 5 14 19 PM](https://user-images.githubusercontent.com/8975583/83466276-77485700-a42b-11ea-8af6-4d70cbdc6470.png)

On the responsive box resizing, I'm fine leaving it as it is. I like consistency between the behavior of the two boxes but it's not hugely important.

**Comment by jcoyne** [comment]
Okay, would it be okay to just have the text box be as wide as the screen?

**Comment by andrewjbtw** [comment]
Yes, I think that's ok.
