### ISSUE TITLE
BL7: Some text boxes and menus on Register APO form are not responsive

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2077]
On the Register APO form, the title box, agreement dropdown menu, and default use license dropdown menu do not get narrower when window is made narrower. 

Note that other boxes on the same page do adjust to page width.

**Comment by jcoyne** [comment]
@andrewjbtw Is this any different from what is currently in production?

**Comment by andrewjbtw** [comment]
I guess it's not. I didn't compare the two for this one, as it didn't seem important to fix this in the current version. This seems like a good opportunity to fix it, but it's more of a nice-to-have than anything essential.

**Comment by andrewjbtw** [comment]
This ends up looking much stranger than I thought it would, almost like viewing a mobile website on a desktop computer.

@astridu - do you think we should limit the menu and text box widths to a fixed length here?

**Comment by astridu** [comment]
Yes, these should be narrower lengths. They are too wide for regular browser width. However, they can still be responsive. I usually design on a grid with breakpoints so that you can define what the widths are at full browser width, tablet, then mobile.

**Comment by jcoyne** [comment]
I added some gutters, is that any better?  If we need to tweak more than that, we should probably have @astrid create the design.

**Comment by astridu** [comment]
Yes, this is better. thanks!

**Comment by andrewjbtw** [comment]
Yes, looks good to go.
