### ISSUE TITLE
BL7: Increase contrast on gray buttons on Register APO form

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2078]
The gray buttons for "Cancel", "Add", and "Remove" are so light I have a hard time distinguishing them as buttons. These probably should have more contrast. 

@astridu is there a shade you would recommend?

**Screenshot**

![Screen Shot 2020-05-29 at 4 20 33 PM](https://user-images.githubusercontent.com/8975583/83312796-8d0a1200-a1c8-11ea-9fe1-7d23a669df85.png)

**Comment by jcoyne** [comment]
This is the shade ($floral-white: #f9f6ef) that astrid recommended for "secondary" buttons

**Comment by astridu** [comment]
Can we use a different style for this button that's different from the facets? I'm proposing a white button with blue border around it (same blue as the button)
![image](https://user-images.githubusercontent.com/42216982/83448545-f7a89100-a406-11ea-92ed-16e2b377fc38.png)

**Comment by jcoyne** [comment]
Like this?
![Screen Shot 2020-06-01 at 4.05.44 PM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/0b8f9248-02bf-4954-b5f9-375df56a1b75)

And then when hovering?

![Screen Shot 2020-06-01 at 4.06.26 PM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/fda633e8-c79b-4033-b0c3-27c8e15bb22b)

**Comment by astridu** [comment]
That looks fine (with the gray for hover state). Thanks!

**Comment by andrewjbtw** [comment]
Looks good to me.
