### ISSUE TITLE
BL7: Move "collapse" arrow back to the left on show pages

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2079]
In Blacklight 6, the arrow to show that a section of a show page is collapsible/expandable is on the left of the gray bar:

![Screen Shot 2020-05-29 at 4 25 58 PM](https://user-images.githubusercontent.com/8975583/83313177-f0e10a80-a1c9-11ea-9ff3-b3e2bbc84cb1.png)

In Blacklight 7, this arrow is on the right hand side, where it collides with the MODS bulk loads button on APO pages. It might also collide with the "Download all files" option, but I don't think I've seen that new option deployed with BL 7.

If there's no reason it can't be on the left, moving the arrow back left seems like it would solve the problem. 

![Screen Shot 2020-05-29 at 4 25 27 PM](https://user-images.githubusercontent.com/8975583/83313180-f3436480-a1c9-11ea-9a5f-b1a62cf64ccf.png)

**Comment by jcoyne** [comment]
@andrewjbtw this was an intentional change so that it mirrors the design of the facet collapse.  Can we move the "MODS bulk loads" to the left sidebar instead?

**Comment by andrewjbtw** [comment]
Ideally, we would move the MODS bulk loads out to a bulk action and off the APO page altogether but that probably won't fit in this work cycle. I'm hesitant to move it and then move it again.

Could it stay in the right side of the bar but shift to the left of the arrow?

**Comment by jcoyne** [comment]
> Could it stay in the right side of the bar but shift to the left of the arrow?

I'll do that.

**Comment by andrewjbtw** [comment]
Looks good to me.
