### ISSUE TITLE
BL7: Odd shade of blue on the "Edit collections" modal for item pages

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2081]
On item pages, the modal for "Edit Collections" has an odd blue background.

<img width="826" alt="Screen Shot 2020-05-27 at 5 18 40 PM" src="https://user-images.githubusercontent.com/8975583/83313517-5d103e00-a1cb-11ea-8153-3dcb487c689a.png">

**Comment by jcoyne** [comment]
That blue stripe is actually present in production too, but less prominently:
<img width="895" alt="Screen Shot 2020-06-01 at 12 08 33 PM" src="https://user-images.githubusercontent.com/92044/83434775-b4e3ba80-a400-11ea-91d6-2aaa71417376.png">

**Comment by jcoyne** [comment]
Fixed on master and a rebase should fix the blacklight branch.
