### ISSUE TITLE
BL7: Workflow modal "Set to completed" button is out of proportion

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2083]
The "Set to completed" button in the workflow modal is out of proportion with the rest of the display:

<img width="803" alt="Screen Shot 2020-05-27 at 5 23 49 PM" src="https://user-images.githubusercontent.com/8975583/83313982-3c48e800-a1cd-11ea-92ad-4678e6cd17a9.png">

**Comment by andrewjbtw** [comment]
This might also be the case with the "set to waiting" button that users see when they don't have superadmin permissions.

**Comment by jcoyne** [comment]
By out of proportion, do you mean, the font size should be smaller?

**Comment by jcoyne** [comment]
Is this acceptable? 
<img width="1142" alt="Screen Shot 2020-06-01 at 11 50 09 AM" src="https://user-images.githubusercontent.com/92044/83432145-0fc7e280-a3fe-11ea-957e-ae9c9f45991a.png">

**Comment by andrewjbtw** [comment]
That looks fine to me.
