### ISSUE TITLE
BL7: Inconsistent layout for facet display header on search results

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2085]
Depending on the view, the display of selected facets at the top of search results pages either extends across the entire window or just across the section that shows the search results.

In results view, the selected facet display extends across the whole window:

<img width="1623" alt="Screen Shot 2020-05-27 at 3 21 44 PM" src="https://user-images.githubusercontent.com/8975583/83314179-17a14000-a1ce-11ea-97f8-9f9a2f6e4c31.png">

In workflow grid, and reports view, the selected facet display does not extend across the left sidebar:

<img width="1623" alt="Screen Shot 2020-05-27 at 3 22 25 PM" src="https://user-images.githubusercontent.com/8975583/83314220-4e775600-a1ce-11ea-9043-765cb11d1169.png">

In Profile view, the selected facet display appears in both places:

![Screen Shot 2020-05-29 at 5 06 59 PM](https://user-images.githubusercontent.com/8975583/83314371-e8d79980-a1ce-11ea-93a8-b30a49b4ba98.png)

I defer to @astridu's judgement on whether or not the selected facets should be displayed across the whole window, but I think it would be best if it's consistent across all views. Note that the results view also includes buttons for "Bulk Update", "Bulk Actions" and more, which does complicate that particular view.

**Comment by astridu** [comment]
I agree it should be consistent, and the pattern that seems to make the most sense for all the different layouts is to have the facets display below the search box and above the 'Limit your search' column and have it span across the page.

**Comment by andrewjbtw** [comment]
@jcoyne This is now fixed in 3 of the 4 views but the workflow grid still has the selected facets display only across the grid itself.

**Comment by jcoyne** [comment]
@andrewjbtw fixed the workflow display now.

**Comment by andrewjbtw** [comment]
Looks good, thanks.
