### ISSUE TITLE
Improve scalability of registration

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2089]
There's a definite user need to make item registration scale better and at least one project (EVIS, a large-scale newspaper digitization project) where registration is a pain point and bottleneck for accessioning.

There are two dimensions to scaling registration:

1. Increase the number of druids that can be registered at once.

- Users have found that they cannot register more than about 500 druids at once without starting to see some failures. There are some existing tickets to support registering larger batches: see https://github.com/sul-dlss/argo/issues/1488 and https://github.com/sul-dlss/argo/issues/1396 (for discussion of this and other bulk jobs)
- This could potentially be implemented using the existing form.

2. Allow registration of druids with different settings

- The registration form is set up to apply all of the same setting at the top of the form to every item in a batch. This means that the whole batch will have the same APO/Collection/rights/tags/etc.
- There is a user need to be able to register batches where some of these top-level settings are different for different items. 
- This probably requires a registration method that does not use the form.

**Example use cases**

1. A user needs to register 1000 druids with all the same settings. 
- This request would be satisfied by scaling the existing form. 
- They could fill out the form once.
2. A user needs to register 1000 druids, but some of the settings will differ. 
- They will need to fill out the form once per case. Let's say they're registering 50 druids per batch with 20 different combinations of settings. They have to fill out the form 20 different times. 
- The form supports this, but it's very time consuming.

**Comment by Mellen22** [comment]
The EVIS project recently had a collection to accession consisting of ~18,000 objects, which were registered with 30 batches. With this project I found that it takes approximately 20-30 seconds to switch between text view and table view. After this it takes about 2.5-3.5 minutes for registration to complete. 

We anticipate in the future that we will be getting large collections of objects consisting of many small collections that will need unique tags.

**Comment by andrewjbtw** [comment]
I've gone ahead and made the ticket for the first use case, which is scaling the existing form to handle larger numbers of druids: #2089

We are still gathering requirements for the second use case.

**Comment by andrewjbtw** [comment]
This has been accomplished via bulk action registration.
