### ISSUE TITLE
[PROXY] Consider decommissioning WAS Thumbnail service

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#2091]
Rather than migrate the WAS Thumbnail service, it is proposed to decommission it. WAS Thumbnail service has not been maintained and does not function properly.

If the WAS Thumbnail service is turned off, each seed will have a single thumbnail that is generated as part of the seed preassembly workflow.

Based on discussion with stakeholders, the following need to be considered to make this decision:
* How will PURL pages for seeds be rendered?
* How will Searchworks pages for seeds be rendered?
* How will Spotlight pages for seeds be rendered?

This will allow consideration of:
* Does the display of thumbnails on these pages need to be changed?
* Is the link to SWAP sufficiently prominent?
* Should we delete existing thumbnails generated by the WAS Thumbnail service?

Also, need to determine what steps need to be taken turn off the service. For example:
* Decommission the servers.
* Move the github repo to deprecated.
* Remove from dependency updates.
* Remove https://github.com/sul-dlss/was_robot_suite/blob/master/robots/was_seed_dissemination/update_thumbnail_generator.rb

**Comment by justinlittman** [comment]
I've set up a meeting with @anarchivist to discuss.

**Comment by justinlittman** [comment]
Examples:
* PURL: https://purl.stanford.edu/bb196dd3409
* Searchworks: https://searchworks.stanford.edu/view/bb196dd3409
* Exhibits: https://exhibits.stanford.edu/chinese-ngos/catalog/pp632vw4799

**Comment by ndushay** [comment]
I believe if was-thumbnail-service is decommissioned, then:
- we should decommission was-seed-dissemination wf (it only adds the thumbnail to was-thumbnail-service, I believe)
- we should decommission was-robot code for was-seed-dissemination
- update documentation for was-robot-suite
- update consul documentation (?)
- we should remove the setting from the shared_configs for was-robots

as well as
- migrating was-thumbnail-service code to sul-dlss-deprecated
- decommission was-thumbnail VMs
- clear out honeybadger errors?

It would be great to avoid leaving vestigial code, configs and documentation around.

**Comment by justinlittman** [comment]
The SWAP location is added here: https://github.com/sul-dlss/was_robot_suite/blob/master/template/wasSeedPreassembly/descMetadata.xslt#L28

Thus, `location displayLabel="Archived site" > url` can be considered a reliable location to get the link to SWAP for a seed. (cc @mejackreed )

**Comment by jvine** [comment]
[Embed UI proposal here](https://docs.google.com/document/d/1BOm7WnUFjFXtorFuliHaBLMO1CIVF0NDF9amZtNXbgE/edit?usp=sharing).

**Comment by anarchivist** [comment]
OK, just tracking here. I followed up with @andrewjbtw and @justinlittman on this given JV's mocks. The Access Team would like to work on a spike of the design, and we're sorting out how to get stakeholder feedback.

**Comment by mejackreed** [comment]
@sul-dlss/infrastructure-team The pull request https://github.com/sul-dlss/sul-embed/pull/1181 removes the direct dependency on the was-thumbnail service.

However, it does now add a call to the swap.stanford.edu timemap for a given WAS. This is down server side and will raise an exception if that service is unavailable.

**Comment by anarchivist** [comment]
Additional notes on cleanup, copied from the email thread:

@mejackreed 💬 
> As I understand it, the was-thumbnail-server didn’t house the thumbs but just dropped them on the stacks mount without any record of them in SDR. I’m not sure if we have other content like this (just dropped onto /stacks without a cleanup operation). It seems like part of the decommissioning work it would be nice to go and cleanup those created thumbs. Maybe the was-thumbnail-service database would have the needed information to do this cleanup? I’m not entirely sure of this, but I suspect this is what happening looking over that codebase.

@andrewjbtw 💬 
> I hadn’t realized that even the was-thumbnails were going to Stacks. In that case, I think we should clean that up. I’d to keep SDR’s (or Argo’s) record of what files are on Stacks consistent with what is actually on Stacks.

**Comment by andrewjbtw** [comment]
It turns out that we have an inconsistency between the auto-generated MODS created during web archive seed preassmebly and the MODS created when descriptive metadata is updated after accessioning. I've filed a ticket to make things more consistent, but this will involve some infrastructure development work: https://github.com/sul-dlss/was_robot_suite/issues/257

**Comment by mjgiarlo** [comment]
Closing proxy ticket, since we already have a dedicated ticket, and this work is nearly done.
