### ISSUE TITLE
The accessionWF should not run if there's an active assemblyWF

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2093]
**Describe the bug**
It is possible to run the accessionWF when the assemblyWF is still active. This can happen if an item is already at v1 or higher. 

**User Impact**
This is a serious problem because the accessionWF deletes files from the active workspace. So if an item has an active assemblyWF and the accessionWF will run, then the files that the assemblyWF is supposed to process will be deleted. 

At a minimum, this means that users will need to start over to accession the item. The worst case scenario is that data is actually lost - for example, if a user has already deleted their copy because they thought accessioning was complete.

**To Reproduce**
1. Find an item that has already been accessioned once and has an active assemblyWF. For example: https://argo-stage.stanford.edu/view/druid:kt849tp3820
2. See that the status is "Opened"
3. See that the button for "Close version" is active on the left
4. If you close the version, the accessionWF will run

**Expected behavior**
The assemblyWF is a part of accessioning, even if it's not part of the accessionWF. The accessionWF should only run if the assemblyWF has been completed.

**Additional context**
If this is the first version of the object and it has not been accessioned yet, there is a different problem. In this situation, the object status remains "Registered" until the accesionWF runs. That is also a serious problem, to be ticketed on its own - #2094

**Comment by andrewjbtw** [comment]
This problem happened recently with this item:
https://argo.stanford.edu/view/druid:bw780zz9194

You can see from the events data that the item was closed on 6/2. But it has had an active assemblyWF for over a week. I discovered this issue because I went to fix an error with the contentMetadata.xml file and discovered that the directory is now empty.

**Comment by peetucket** [comment]
Perhaps has to do with how we compute what "closeable" - which determines if the close button is argo is active.  If the close button is active, the user can close a version, which will kick-off accessionWF by default.

Closeable is defined in argo here:

https://github.com/sul-dlss/argo/blob/master/app/controllers/workflow_service_controller.rb#L81-L87

**Comment by peetucket** [comment]
Looks like it uses active lifecycles to decide.  If there an "opened" active lifecycle (from versioningWF) and NOT a "submitted" active lifecycle (from accessionWF), is it considered closeable.  Since assemblyWF has no lifecycles, it's status is effectively ignored in this computation.

**Comment by peetucket** [comment]
I don't have any quick ideas on how to change this easily -- I think the right solution is to add a lifecycle to assemblyWF and then confirm it is also not active when doing this computation.  But any existing objects with assemblyWF won't have the lifecycle, posing other problems when doing this check on existing objects...

**Comment by ndushay** [comment]
@peetucket thanks for your help;  I'm gonna explore a couple ideas.

**Comment by ndushay** [comment]
from https://github.com/sul-dlss/argo/pull/2099#issuecomment-639229968:

@jcoyne says:

>I believe this is just handling "should we show the button?" but we probably would also need this validation where the version is actually closed in order to fix #2093: https://github.com/sul-dlss/dor-services-app/blob/38aaaea039f928d9410513346d3654b52dec8bb8/app/services/version_service.rb#L82-L84

So in addition to the Argo PR, we will also need a dor-services-app PR, which is forthcoming.
