### ISSUE TITLE
Release bulk action jobs are not completing

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2104]
Multiple users are reporting that the Release objects bulk action is not completing. The bulk actions interface shows the jobs are processing but nothing seems to be happening.

Bulk actions known to have stalled in the past two days are

ReleaseObjectJob_10030
ReleaseObjectJob_10044

**Additional information**
I have not been able to determine a cause, but I found this in HB:
https://app.honeybadger.io/projects/49894/faults/62649217

One possibility is that the bulk action is running into problems when a list of druids contains a combination of items that have and have not been released once before. This can happen because users may submit a whole collection for release where some but not all items were previously released. There's no easy way to exclude the already-released items.

**Comment by ndushay** [comment]
looked at HB error, and the log file is there, and it has the right permissions, and it is linked to at the directory level, not the individual file level ... like all the other logs.  

Is it possible delayed job runs somehow with diff uid ????

**Comment by ndushay** [comment]
another thought:  what if job was running during log rotation -- would that cause the job to fail?  The timestamps of the errors in HB would suggest this is unlikely.

Unless the delayed job process itself held on to the file point to the workflow log file, and when that file was rotated, the HB time of occurrence somehow pertains to ... the delayed job process start time?

**Comment by aaron-collier** [comment]
So this is strange, the file not found error in WorkflowClient happens if the file is empty. Once I dropped a test log line the action ran fine.

**Comment by ndushay** [comment]
After pairing with Aaron, our thoughts:

We ssh'ed to argo-prod-02, and experimented in the rails console.  Aaron got the same failure when executing the line (https://github.com/sul-dlss/argo/blob/master/app/jobs/release_object_job.rb#L61) from `release_object_job` when the file was empty:

```
WorkflowClientFactory.build.create_workflow_by_name(current_druid, 'releaseWF', version: object.current_version)
```

However, when he went through the steps from WorkflowClientFactory (https://github.com/sul-dlss/argo/blob/master/app/services/workflow_client_factory.rb#L6-L7) , there was no problem, even tho the log file was the same, and still empty:

```
    logger = Logger.new(Settings.workflow.logfile, Settings.workflow.shift_age)
    Dor::Workflow::Client.new(url: Settings.workflow_url, logger: logger, timeout: Settings.workflow.timeout)
```

We also ran rails console on prod and were able to write log messages to an empty workflow_service.log file:

```
pry(main)> rel_ll = Logger.new(Settings.workflow.logfile, Settings.workflow.shift_age)
pry(main)> abs_ll = Logger.new(Rails.root.join(Settings.workflow.logfile), Settings.workflow.shift_age)
pry(main)> rel_ll.debug('relative logger message from naomi')
=> true
pry(main)> abs_ll.debug('absolute logger message from naomi')
=> true
```

then we tried to make the log empty again for experiments and we couldn't.  It kept getting this message after a `touch workflow_service.log`

```
[lyberadmin@argo-prod-02 log]$ cat workflow_service.log
# Logfile created on 2020-06-05 14:48:00 -0700 by logger.rb/66358
```

_You have entered the twilight zone_

So here are our stray thoughts:

- we hope this problem goes away with fresh deploys, but that seems unlikely based on the scattered occurrences over time.
- we didn't deploy Argo this week and maybe there's some process that's somehow hanging on to something?
- could it be that there is a problem with the log file being relative rather than absolute path??  That somehow when the Logger class gets spun up as in https://app.honeybadger.io/projects/49894/faults/62649217, that the log file can't be found because it's looking in the wrong directory?
- we could add an HB alert somehow to WorkflowClientFactory to get more context???

**Comment by ndushay** [comment]
Note:  Aaron re-ran the first job and it ran successfully.  Andrew is going to have the maps folks rerun the other job because it's a complex maps thing.  These are the only 2 failures we know of right now.

**Comment by andrewjbtw** [comment]
The maps folks reported the error occurred again. They are pasting in a list rather than running from a search, so that might make a difference even though it seems like it shouldn't.

**Comment by andrewjbtw** [comment]
This seems to be fixed. The two jobs we know had been stalling have now been completed. It's hard to test in production without changing actual data, so I'm going to close it now. We can re-open if it reoccurs.

**Comment by andrewjbtw** [comment]
I spoke too soon. The error is still occurring today.

**Comment by andrewjbtw** [comment]
There have been 6 release jobs run so far today and the logs indicate only one has completed:

```
----ReleaseObjectJob_10065/log.txt----
2020-06-08 16:41:51 UTC Starting ReleaseObjectJob for BulkAction 10065
2020-06-08 16:41:51 UTC Beginning ReleaseObjectJob for druid:pf136wk5009
2020-06-08 16:41:51 UTC Adding release tag for Searchworks
2020-06-08 16:41:52 UTC Release tag added successfully
2020-06-08 16:41:52 UTC Trying to start release workflow
2020-06-08 16:42:08 UTC Starting ReleaseObjectJob for BulkAction 10065
2020-06-08 16:42:08 UTC Beginning ReleaseObjectJob for druid:pf136wk5009
2020-06-08 16:42:08 UTC Adding release tag for Searchworks
2020-06-08 16:42:08 UTC Release tag added successfully
2020-06-08 16:42:08 UTC Trying to start release workflow
2020-06-08 16:42:51 UTC Starting ReleaseObjectJob for BulkAction 10065
2020-06-08 16:42:51 UTC Beginning ReleaseObjectJob for druid:pf136wk5009
2020-06-08 16:42:52 UTC Adding release tag for Searchworks
2020-06-08 16:42:52 UTC Release tag added successfully
2020-06-08 16:42:52 UTC Trying to start release workflow
2020-06-08 16:42:52 UTC Workflow creation successful
2020-06-08 16:42:52 UTC Finished ReleaseObjectJob for BulkAction 10065
```

The rest of the logs look like this:

```
----ReleaseObjectJob_10066/log.txt----
2020-06-08 16:46:52 UTC Starting ReleaseObjectJob for BulkAction 10066
2020-06-08 16:46:52 UTC Beginning ReleaseObjectJob for druid:bk506kr8679
2020-06-08 16:46:52 UTC Adding release tag for Searchworks
2020-06-08 16:46:52 UTC Release tag added successfully
2020-06-08 16:46:52 UTC Trying to start release workflow
2020-06-08 16:47:09 UTC Starting ReleaseObjectJob for BulkAction 10066
2020-06-08 16:47:09 UTC Beginning ReleaseObjectJob for druid:bk506kr8679
2020-06-08 16:47:09 UTC Adding release tag for Searchworks
2020-06-08 16:47:09 UTC Release tag added successfully
2020-06-08 16:47:09 UTC Trying to start release workflow
2020-06-08 16:47:52 UTC Starting ReleaseObjectJob for BulkAction 10066
2020-06-08 16:47:52 UTC Beginning ReleaseObjectJob for druid:bk506kr8679
2020-06-08 16:47:52 UTC Adding release tag for Searchworks
2020-06-08 16:47:53 UTC Release tag added successfully
2020-06-08 16:47:53 UTC Trying to start release workflow
```

One weird thing about those logs is it looks like each job is making multiple attempts for the same druid before either completing or failing.

**Comment by andrewjbtw** [comment]
Still coming up in the honeybadger logs, unfortunately, so I'm reopening: https://app.honeybadger.io/projects/49894/faults/62649217

**Comment by ndushay** [comment]
Could this be:
- needs absolute path
- stale sidekiq workers?
- gremlins?
- ???

**Comment by jcoyne** [comment]
There are delayed jobs that are still running from a month ago:
<img width="1082" alt="Screen Shot 2020-06-18 at 7 33 21 AM" src="https://user-images.githubusercontent.com/92044/85020524-15c7fe00-b136-11ea-9e81-a3c4b4e07a50.png">

**Comment by mjgiarlo** [comment]
@jcoyne can you report back on the above?

**Comment by jcoyne** [comment]
I killed those jobs. Made a PR to switch to Sidekiq #2127

**Comment by andrewjbtw** [comment]
Looks like the sidekiq switch fixed this. No recurrences of the error in almost three weeks. Closing.
