### ISSUE TITLE
Implement relevancy ranking for results

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#211]
In order to implement this, we need to know what solr fields contribute to the keyword index retrieval. Can I tell via the field naming conventions. 

This will let us designate some relevancy criteria, e.g., title/creator rank higher than subject/subject names; abstract ranks higher than note; identity data (like source ID) are very high but likely isolated.

**Comment by cbeer** [comment]
It may be easier to decide what fields we _want_ to be relevant. It seems like you've done part of that here, and we'd just need to map it to indexed fields.

**Comment by blalbrit** [comment]
Closing now. A future version of Argo should consider the search requirements afresh.
