### ISSUE TITLE
Small fixes to new "download all files" option

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2134]
**Describe the bug**
1. The "download all files" option in Argo is appearing on the left-hand side of the "Contents" title bar. But in stage testing it had appeared on the right-hand side. I think it's easier to see if it's on the right:

![Screen Shot 2020-06-23 at 12 25 31 PM](https://user-images.githubusercontent.com/8975583/85449578-c5dda280-b54c-11ea-87a4-86cceee1ae41.png)

2. Clicking on the option collapses the "Contents" list. If possible, clicking should leave the list open. This may have happened in testing but I didn't notice it.

**Comment by jcoyne** [comment]
@andrewjbtw I think this is because this feature was written for blacklight 6 and it didn't merge well with  blacklight 7.
