### ISSUE TITLE
Investigate creation of duplicate workflow values (?in bulk actions?)

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#2146]
# Background

Early in the morning on June 25th, bulk metadata jobs were submitted for a smaller number of geo-related APOs. We are not sure when, but at some point the robot backlog ticked up sharply, with a very large number of descriptive-metadata jobs in the accessionWF_default queue. All told, roughly 1 million new jobs were created.

# Steps Taken

The queue backlog has been hacked down (following steps documented in the [common-accessioning wiki](https://github.com/sul-dlss/common-accessioning/wiki)), and the queues are back to normal now (late afternoon, June 25th).

Despite @sul-dlss/infrastructure-team spending a couple hours pairing, we have not found the underlying cause yet, so this may recur. Particularly troubling: this caused no Honeybadger alerts, and there was no useful information in any or our logs. 

# Analysis

A proximate cause (not root cause) is multiple versions having been created for some workflow steps, possibly due to race conditions in the workflow service. In the meantime, we have determined that the workflow service ought to have a database constraint or at least a Rails validation preventing duplicate data from being created (this is now in place). These should at least result in exceptions that can bubble up in Honeybadger alerts. Related to this, there is some workflow data that needs hand remediating: https://robot-console-prod.stanford.edu/failed?start=80

The root cause is *suspected* to be in Argo, related to code in bulk actions (running in DelayedJob workers) making duplicate WF requests nearly simultaneously.

# Suggested actions

* Keep an eye on robot-console-prod queues (in the Resque UI)
* Ask Kim Durante for the data and steps she used to see if this can be reproduced in stage
* Remediate duplicate data in the workflow service to prevent further Honeybadger alerts

**Comment by ndushay** [comment]
https://argo.stanford.edu/view/pf286gp7757 appears to have an old accessionWF, with the `sdr-ingest-received` step.

**Comment by ndushay** [comment]
nearly all of these are a version 2 issue where version 3 processing has started ...

**Comment by ndushay** [comment]
question maybe @jcoyne can answer:  was there any sort of recent change to workflows or to common-accessioning that made duplicate workflows "suddenly" problematic?   Like, even if they are a number of versions back?  Possibly years back.

**Comment by jcoyne** [comment]
Yesterday we added extra validation to workflow server because we saw that duplicate steps could be created if workflows were created simultaneously.

**Comment by jcoyne** [comment]
I've fixed all the bad data that I've seen in prod.

**Comment by ndushay** [comment]
thank you, Justin!

**Comment by ndushay** [comment]
@jcoyne fixed the remaining bad data (I was doing some 1 at a times last night, but that was never going to scale), will hopefully provide a database level constraint now that no more bad data exists to avoid further problems.
