### ISSUE TITLE
Figure out why some Modsulator connections are timing out

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#2147]
Robert Rohrbacher is reporting Modsulator timeouts in Argo: `Error - there was an error within the MODSulator server           Net::ReadTimeout with #<TCPSocket:(closed)>` He has tried at least two times so far.

As FR, I took no action other than log spelunking. I can confirm that related errors are showing up in `log/delayed_job.log` on Argo-prod boxes. (These exceptions are eaten and logged; they do not go to Honeybadger. Should they? :man_shrugging:)

I'm not sure what we can do about this until/unless we get our hands on the data Robert is using (and/or the implicated druid(s) for more log spelunking on the modsulator-app-rails-prod side).

Worth noting that the `ModsulatorClient` class in Argo has a default timeout of thirty minutes. Perhaps the input data is ginormous?

cc: @andrewjbtw

**Comment by andrewjbtw** [comment]
Some information I've been able to track down:

Two modsulator-related honeybadger errors:
https://app.honeybadger.io/projects/49894/faults/65064204
https://app.honeybadger.io/projects/49894/faults/62477704 

APOs with modsulator timeouts on 6/25:
https://argo.stanford.edu/apos/druid:sz019vc3579/bulk_jobs (looks like it worked on a later attempt)
https://argo.stanford.edu/apos/druid:sq161jk2248/bulk_jobs (file: Rumsey_Maps928_MODS_Load.xml)

Log for failed upload on sq161jk2248 (found at `/workspace/bulk/druid:sq161jk2248/2020_06_25_20_05_57_527` on the Argo server) - this is the one that's failed multiple attempts
```
argo.bulk_metadata.bulk_log_job_start 2020-06-25 20:05pm
argo.bulk_metadata.bulk_log_user [redacted]
argo.bulk_metadata.bulk_log_input_file Rumsey_Maps928_MODS_Load.xml
argo.bulk_metadata.bulk_log_note For a set of objects with mismatched descriptive metadata
argo.bulk_metadata.bulk_log_internal_error Net::ReadTimeout with #<TCPSocket:(closed)>
argo.bulk_metadata.bulk_log_empty_response ERROR: No response from https://modsulator-app.stanford.edu/v1/normalizer
argo.bulk_metadata.bulk_log_error_exception Got no response from server
argo.bulk_metadata.bulk_log_job_complete 2020-06-25 20:35pm
```

**Comment by ndushay** [comment]
This resolved itself.  Maybe it was sidekiq going into production on Friday.   Closing.
