### ISSUE TITLE
Improve support for tracking sheets

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#217]
Tracking sheets are printed barcoded pages that the labs place in physical items being scanned for tracking the manual workflow. Several improvements are needed:
- they are available only after registration from that page
  - they should be a printable form of output at any time from a search result or detail page.
- it is somewhat fragile (Ben will know more)
- there is a request for full-page / half-page options

Output is presented in the form of a printable PDF, sample attached.

[Rumsey Map Collection - Batch 4 - Single Map-1.pdf](https://github.com/sul-dlss/argo/files/38159/Rumsey.Map.Collection.-.Batch.4.-.Single.Map-1.pdf)

**Comment by jmartin-sul** [comment]
should be easy enough to present a URL to the tracking sheet.  IIRC, i've manually visited it without any trouble when testing tracking sheet bugs in the past.

fun side note:  tracking sheet generation contains one of our more egregious reindexing hacks:
https://github.com/sul-dlss/argo/blob/70416658b95549881c847cf01f4b06a6775ed7d1/app/helpers/registration_helper.rb#L62-L66

**Comment by atz** [comment]
For a search result page, would you want the generated sheet to include the records on the page or the records from the query (resultset)?  The latter seems more powerful and more attuned to the data, but also more susceptible to a user crashing the process by mistakenly trying to print a 10,000-record PDF (or worse yet, succeeding!).  If we do the latter, we should enforce a max number of druids as a precaution.

**Comment by drh-stanford** [comment]
this sounds like something for the bulk actions framework

**Comment by andrewjbtw** [comment]
We now have a tracking sheet bulk action.
