### ISSUE TITLE
No warning given anymore when saving malformed XML for datastream (on the client side)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#2183]
**Describe the bug**
Per a report from one of our users, if malformed XML was entered when editing a datastream, a "warning would appear and it would not allow you to save your edits in the datastream until you fixed the XML."  But upon re-trying this just now, the user "can verify that the warning message is not showing up."  Instead, users get redirected to the library system status page (on prod, or a generic 500 error page on stage).  Also, the attempted edit isn't saved.

**User Impact**

Some of our datastreams can have lengthy and complex XML, and our systems sometimes necessitate editing them by hand.  As such, it's easy to produce malformed XML, and the loss of this check makes it easy to attempt to save bad XML, which results in getting bounced to a perplexing 500 error page and losing your edits.

**To Reproduce**
1. Open a datastream for editing (in the case we just saw, it was `descMetadata`)
2. Edit it so that the XML is no longer well formed (e.g. add an opening tag without a corresponding closing tag)
3. Try to save the datastream
4. Get a 500 error with no explanation (bouncing to system status page on prod, or generic 500 error page on stage).

**Expected behavior**

Upon attempting to save the bad XML, a warning is popped up, the XML as edited is retained but not saved, and the user is allowed to continue editing until well formed XML is produced.

**Screenshots**

e.g. you tried to close a `<mods>` open tag with a `</modsssssssss>` closing tag, hit update without realizing your mistake...

![Screen Shot 2020-07-14 at 2 32 39 PM](https://user-images.githubusercontent.com/7741604/87478645-fa3dff00-c5de-11ea-950c-33ef3d38d601.png)

and cryptic error message results...

![Screen Shot 2020-07-14 at 2 32 56 PM](https://user-images.githubusercontent.com/7741604/87478653-fc07c280-c5de-11ea-905c-961074f513d1.png)

**Additional context**

**Comment by jcoyne** [comment]
I'd take a look at this jquery hook and see if this event is ever triggered: https://github.com/sul-dlss/argo/blob/4c84648331e352cc35200c4ebb0060222de97cbc/app/javascript/packs/application.js#L65-L68

**Comment by jmartin-sul** [comment]
thanks @jcoyne!

**Comment by jmartin-sul** [comment]
see also:  https://app.honeybadger.io/projects/49894/faults/65681843

**Comment by peetucket** [comment]
We are now showing an error message to users as per this PR : #2194 after going to it the server, but it would be nice to see why the client side error message via the event noted above and the JS here doesn't seem to be working anymore: https://github.com/sul-dlss/argo/blob/master/app/javascript/modules/datastream_edit.js

**Comment by jcoyne** [comment]
<img width="558" alt="Screen Shot 2021-04-05 at 11 11 07 PM" src="https://user-images.githubusercontent.com/92044/113657765-41d05380-9664-11eb-8591-24a76395ab85.png">

A client side error message is shown now.
