### ISSUE TITLE
Items already released, will not be able to be released again because of duplicate workflow_server_rails records

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#2185]
**Describe the bug**
Items that have been released in one place, for instance SearchWorks, will not be able to be released elsewhere, EarthWorks. To my understanding this is caused by legacy data in workflow_server_rails and Argo users who release items will not be able to proceed further.

**User Impact**
Geospatial data cannot be indexed into EarthWorks .

Likely affected by the following >9,700 records and any other content that is released in multiple places.
https://argo.stanford.edu/catalog?f%5Bcontent_type_ssim%5D%5B%5D=geo&f%5Breleased_to_ssim%5D%5B%5D=Searchworks

The access team recently removed the gisDiscoveryWF from gis-robot-suite here: https://github.com/sul-dlss/gis-robot-suite/pull/329 in hope to bring process more inline with approved infrastructure approach.

Other impacts: Likely impacting any other SDR object that has already been released and releaseWF is run again on it. @cebraj reported a similar issue this morning. I would guess there will be many more reports of an issue like this where releaseWF was run previously.

**To Reproduce**
1. Go to any object in this collection not yet released to EarthWorks: https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Abq589tv8583
2. Release it to EarthWorks
3. Reported that the release tag has been added but the releaseWF fails
4. See error https://app.honeybadger.io/projects/58890/faults/65074065

**Expected behavior**
The releaseWF would complete and it would be published to purl xml without developer intervention.

**Comment by jmartin-sul** [comment]
i ran a couple scripts last week to try to get a sense of how much bad data we have.  seems maybe manageable?  probably a pain to clean up, but seems like just over 1200 affected druids.  hopefully there are patterns of bad data for which we can automate remediation.  it seems like only 24 of the entries are amenable to the automated cleanup script [from the wiki](https://github.com/sul-dlss/workflow-server-rails/wiki/Handling-uniqueness-errors#a-smarter-way).  but it's also possible that some of the druids where there are more than 2 of the same step fit a similar pattern of totally duplicative steps that don't need manual examination.

log file attached, test code below

### run a modified version of above-linked cleanup script, but just run to analyze existing bad data

#### results
* `grep "Removed" dupe_wf_steps.log | wc -l` -- 24 steps that could be cleaned up
* `grep "caught There are .*steps for" dupe_wf_steps.log | wc -l` - 1218 that cause the existing cleanup method to raise an error


```ruby
def logger
  Logger.new(Rails.root.join('log', 'dupe_wf_steps.log'))
end

def versions_with_dupe_steps(druid, wf_name)
  WorkflowStep.where(druid: druid,  workflow: wf_name).group(:process, :version).having('count(version) > 1').pluck('distinct(version)')
end

# call once with just the druid and wf_name to make sure the right things would get cleaned up, call again with "false" for the optional third param to actually do the cleanup
def check(druid, wf_name, is_dry_run = true)
  versions_to_remediate = versions_with_dupe_steps(druid, wf_name)
  return 'no duplicates found' unless versions_to_remediate
  logger.info "#{druid} #{wf_name} -- versions with duplicate steps: \n#{versions_to_remediate}"

  versions_to_remediate.each do |version|
    steps = WorkflowStep.where(druid: druid,  workflow: wf_name, version: version).order(:process, :id).pluck(:process, :id)
    # Double checking here.
    steps.group_by(&:first).each do |process, steps_for_process|
      raise "There are #{steps_for_process.count} steps for #{process}" unless steps_for_process.size == 2

      logger.info "#{'[would be]' if is_dry_run}Deleting #{steps_for_process.last.last}"
      WorkflowStep.find(steps_for_process.last.last).destroy unless is_dry_run
    end
    logger.info "#{'[would have]' if is_dry_run}Removed duplicate workflow (steps) for #{druid} #{version}"
  end
rescue => e
  msg = "caught #{e} for #{druid} #{wf_name}"
  puts msg
  logger.error msg
end

def workflows_for_druid(druid)
  WorkflowStep.where(druid: druid).pluck('distinct(workflow)')
rescue => e
  msg = "caught #{e} for #{druid}"
  puts msg
  logger.error msg
end

def check_workflows_for_druids(druid_check_list)
  druid_check_list.each do |druid|
    workflows_for_druid(druid).each do |wf_name|
      check(druid, wf_name)
    end
  end
end

check_workflows_for_druids(druids) # (actually iterated in chunks of about 100k to 500k using druids.slice)
```
### query all at once (took too long, killed in favor of looping over all druids, which completed in under an hour)

```ruby
WorkflowStep.group(:druid, :version, :workflow, :process).having('count(1) > 1').pluck(:druid)
```

### loop over every druid, see how much bad data each druid with the issue has

* log output for each affected druid like `found duplicate steps on bb338jh0716 [[version, nameofWF, step-name, count], ...]: [[1, "gisDiscoveryWF", "finish-gis-discovery-workflow", 2], [1, "gisDiscoveryWF", "generate-geoblacklight", 2], [1, "gisDiscoveryWF", "export-opengeometadata", 2], [1, "gisDiscoveryWF", "load-geoblacklight", 2]]`
* `grep "found duplicate steps on .*version, nameofWF" dupe_wf_steps.log | wc -l` -- 1226 affected druids

```ruby
def logger
  Logger.new(Rails.root.join('log', 'dupe_wf_steps.log'))
end

def dupe_steps_for_druid(druid)
  WorkflowStep.where(druid: druid).group(:version, :workflow, :process).having('count(1) > 1').pluck(:version, :workflow, :process, 'count(1)')
end

# just run this on every druid and log
def log_if_druid_has_dupe_steps(druid)
  query_result = dupe_steps_for_druid(druid)
  if query_result.present?
    msg = "found duplicate steps on #{druid} [[version, nameofWF, step-name, count], ...]: #{query_result}"
    puts(msg)
    logger.warn(msg)
  end
end

druids.each { |druid| log_if_druid_has_dupe_steps(druid) }
```

druids obtained by dumping druid lists from pres cat this past wednesday (my script for dumping druids from fedora's mysql is no longer working after the fedora VM rebuild).
[dupe_wf_steps.log](https://github.com/sul-dlss/argo/files/4952220/dupe_wf_steps.log)

**Comment by jmartin-sul** [comment]
this is the code that's throwing the error, according to the stack trace from honeybadger:  https://github.com/sul-dlss/workflow-server-rails/blob/f02b53b0d22afa80538815fd6d1bd0d7b445a01c/app/controllers/steps_controller.rb#L66

i would be inclined to transfer this issue to the workflow-server-rails repo, since WFS data is where we believe the issue lies, but i don't feel strongly about that.

**Comment by andrewjbtw** [comment]
Thanks for this analysis, I'm finally catching up with now. ~1200 druids doesn't seem so bad for remediation, but I'm surprised all of the problem workflows in the log file are GIS-related. When I've remediated items before, they've almost all had their duplicate steps in accessionWF and releaseWF. I wonder if there are still duplicates not being caught in other workflows?

On the cleanup side, the script on the wiki is great if the entire workflow is duplicated. But in some cases I've seen in the past the duplicate steps only cover part of the workflow and I'm not sure why. When that happens, the script raises an error at the first step that has only once instance and then stops. That's the safest thing to do, but it means manually looking and then removing the other duplicate steps afterwards.

**Comment by jmartin-sul** [comment]
> ~1200 druids doesn't seem so bad for remediation, but I'm surprised all of the problem workflows in the log file are GIS-related. When I've remediated items before, they've almost all had their duplicate steps in accessionWF and releaseWF. I wonder if there are still duplicates not being caught in other workflows?

yeah, i wasn't sure what to make of that.  i'd love if someone could check my SQL/AR queries, to see if they're doing the right thing.  pretty sure they are, and i did get the expected results when i ran spot checks on druids both with and without dupe workflow steps (which i sanity checked by running a simpler query that just listed all workflow steps attached to a given druid, sorted by version/workflow/step/status)

> On the cleanup side, the script on the wiki is great if the entire workflow is duplicated. But in some cases I've seen in the past the duplicate steps only cover part of the workflow and I'm not sure why. When that happens, the script raises an error at the first step that has only once instance and then stops. That's the safest thing to do, but it means manually looking and then removing the other duplicate steps afterwards.

i suspect that if we resourced investigating this problem a little more intentionally, we could find patterns that were similarly amenable to automatic remediation, besides what that script deals with.  e.g., i think that script will barf if it runs into an object with 3 or more duplicate completed steps for the same druid/workflow/version combo.  but that doesn't seem any less automatable in principle than the case the script already covers, we just haven't made the time to code that and test it.  similarly, maybe we'd be ok keeping one completed step, even if duplicate steps for the same workflow/version/druid combo had other statuses, like waiting (or, maybe that'd be too presumptuous, not sure).

**Comment by andrewjbtw** [comment]
Good point about the 3 or more repeated steps. I think those should be treated like the 2 steps. I feel like the goal at this point is just to get everything to one step per process per workflow per version.

But there are definitely druids with duplicates in other workflows. Some more have just started to stall in the accessionWF:

https://argo.stanford.edu/view/druid:cg949sm0705
https://argo.stanford.edu/view/druid:ff110sw1559
https://argo.stanford.edu/view/druid:kb859zg1361
https://argo.stanford.edu/view/druid:mb446rb5743
https://argo.stanford.edu/view/druid:qq225fq7890
https://argo.stanford.edu/view/druid:qv552sr1693
https://argo.stanford.edu/view/druid:tm309fq4104
https://argo.stanford.edu/view/druid:xh414zf6353

And more in the releaseWF:
https://argo.stanford.edu/view/druid:fj777tw5682

**Comment by andrewjbtw** [comment]
Also, one in the assemblyWF:
https://argo.stanford.edu/view/druid:dk200wf1681

**Comment by andrewjbtw** [comment]
Ok, so I just understood why the releaseWF has a different problem than the other workflows. So I'll create a different issue for non-releaseWF issues to keep those separate.

**Comment by andrewjbtw** [comment]
In terms of remediating duplicate steps, I've spent some time fixing some of the existing druids and I think I've worked out a way forward that shouldn't require a lot of first-responder/developer time. 

I propose that the `check` method [in the wiki for handling uniqueness errors](https://github.com/sul-dlss/workflow-server-rails/wiki/Handling-uniqueness-errors) be changed to the following:

```ruby
def check(druid, wf_name, is_dry_run = true)
  versions_to_remediate = versions_with_dupe_steps(druid, wf_name)
  return 'no duplicates found' unless versions_to_remediate
  puts "versions with duplicate steps: \n#{versions_to_remediate}"

  versions_to_remediate.each do |version|
    steps = WorkflowStep.where(druid: druid,  workflow: wf_name, version: version).order(:process, :id).pluck(:process, :id)
    # Double checking here.
    steps.group_by(&:first).each do |process, steps_for_process|
      if steps_for_process.size == 1
        # Do not delete if there's only one step
        puts "There's only #{steps_for_process.count} steps for #{process}"
      else
        # Only delete the last step if there's more than 1
        puts "#{'[would be]' if is_dry_run}Deleting #{steps_for_process.last.last}"
        WorkflowStep.find(steps_for_process.last.last).destroy unless is_dry_run
      end
    puts "#{'[would have]' if is_dry_run}Removed duplicate #{wf_name} #{process} step for #{druid} #{version}"
    end
  end
end
```

The change I made there is to replace the `unless` with an `if-then` that checks if there's only one step for a process, instead of checking that there's exactly 2 steps. 

- If there's only one step, then nothing is deleted. 
- If there's more than one step, then the last step in the list is deleted.
- So if there's 3 or more steps, the method could be run again until we're down to one step.

This change accounts for two conditions I've seen in the legacy data

1. There are 3 or more steps for the same workflow/process/version combination.
2. Only part of a workflow is duplicated. In the legacy data, there's a lot of accessionWF issues where there are duplicate steps for only part of the workflow, basically just up to 'sdr-ingest-transfer'. So when the method hits one of the non-duplicated steps, it just raises an error and stops. The change I'm suggesting allows it to pass over the unique steps and continue to delete the duplicate ones.

**Comment by andrewjbtw** [comment]
With the above change, I think I could work through the data by systematically going through lists of druids that have completed each of the workflows, i.e. check releaseWF for all released druids, assemblyWF for all that have run assembly, etc.

**Comment by andrewjbtw** [comment]
Also, I think I figured out why @jmartin-sul's analysis above didn't catch druids with other workflows beyond GIS. The list of druids looped over (on the server as `all_druids_4_wfs_query_2020-07-15`) isn't prefixed. You get different results if you query the workflow server with or without the prefix.

Most druids show no results without the prefix:

```
[3] pry(main)> workflows_for_druid('druid:dk200wf1681')
=> ["sdrIngestWF", "preservationIngestWF", "releaseWF", "versioningWF", "disseminationWF", "assemblyWF", "accessionWF", "preservationAuditWF", "digitizationWF"]
[4] pry(main)> workflows_for_druid('dk200wf1681')
=> []
```

But other druids do return results without a prefix:
```
[5] pry(main)> workflows_for_druid('zx586ff1839')
=> ["gisAssemblyWF", "gisDiscoveryWF"]
[6] pry(main)> workflows_for_druid('druid:zx586ff1839')
=> ["gisAssemblyWF", "gisDeliveryWF", "sdrIngestWF", "preservationIngestWF", "gisDiscoveryWF", "versioningWF", "disseminationWF", "assemblyWF", "accessionWF", "preservationAuditWF"]
```

Probably all the rows with unprefixed druids need to be dealt with, though I don't know that they're causing any active problems except for generating misleading data when we analyze things.

**Comment by jmartin-sul** [comment]
@andrewjbtw thinks he's resolved all of these using his above proposed cleanup modification.

**Comment by jmartin-sul** [comment]
i think this means we can now apply the DB constraint we wanted to add a while ago, see:
https://github.com/sul-dlss/workflow-server-rails/issues/221
https://github.com/sul-dlss/workflow-server-rails/pull/40

**Comment by mejackreed** [comment]
++ That's great to hear!

**Comment by andrewjbtw** [comment]
I think this was resolved via remediation.
