### ISSUE TITLE
Setting rights in argo to "citation only" does not work.

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#2190]
**Describe the bug**
Cannot change rights to citation only in argo.

**User Impact**
Users cannot change rights to citation only for an object.

**To Reproduce**

1. Open an object for versioning (if needed).
2. Click "Set Rights" on the left side nav.
3. Select "Citation only".
4. Click "Update".
5. See an error message "Invalid new rights setting."

**Expected behavior**
Rights need to change.

**Additional context**

Tried on stage with this object which is open and easy to test with:

https://argo-stage.stanford.edu/catalog/druid:cc243mg0841

It looks like it is possible to update to "Stanford", so its not a general case problem, but seems like only certain values.  Noticed that dor-services gem expects a value of "none" when setting the rights, but Argo sends a value of "citation-only" in the edit view:

https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/rights_metadata_ds.rb#L62-L75

Its not clear which one we want to change (looks like the value of "citation-only" is sprinkled throughout Argo).

**Comment by peetucket** [comment]
It looks argo deliberately sets the value to "citation-only" in the view for some reason:

https://github.com/sul-dlss/argo/blob/master/lib/constants.rb#L10-L12

**Comment by peetucket** [comment]
A recent commit that may have made the change when cocina registration was implemented:

https://github.com/sul-dlss/argo/commit/4972727465f270884c89f6f02b370fd7bbdc5f07

**Comment by peetucket** [comment]
@hannahfrost you first encountered this issue, is there an object that we should manually edit for now to set the rights the way you want them?  I'd like to wait for @jcoyne to weigh in when he is back before making code changes

**Comment by hannahfrost** [comment]
Thanks for the offer, @peetucket . I'll take you up on it :) In fact, I have a list. Will message you via Slack about it.

**Comment by hannahfrost** [comment]
Actually, @peetucket, would you prefer this to be ticketed here? The list of objects to be changed from world to citation-only is short:
nw514vv3406
gd757wk3233
hj611by0044
kp698rh8939
tt211nd1359

**Comment by peetucket** [comment]
Thanks, the ticket is best place for it (easy to refer back to, and easy to have others help if needed).  But this is a short list.

**Comment by peetucket** [comment]
I manually set those objects above to citation only.  I've noticed that PURL sometimes caches the public XML so it may take a couple hours to see the result.  I did one earlier and it is done now.

**Comment by hannahfrost** [comment]
Thanks, @peetucket.

**Comment by aaron-collier** [comment]
Tagging @jcoyne for input.
