### ISSUE TITLE
Argo pages load very slowly, especially the front page and workflow grid

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2193]
**Describe the bug**
The Argo home page and workflow grid load very slowly (60 - 90 seconds), especially when loading those pages without limiting results to a facet or search.

**User Impact**
It slows things down, and for people not accustomed to the slowness it looks like Argo may be down or not responding.

**To Reproduce**
Go to the argo home page.

**Expected behavior**
Argo has never been fast, but this is noticeably slower than it was. The problem seems to have come in within the past few months.

**Additional context**
Tags are a huge proportion of the load time. We've tried to address this with the following:

- We thought that the problem might be caused by the increasing number of unique tags assigned to Google Books, but we removed all of those tags and it hasn't increased the speed of the Argo home page. 
- there's a flag to add "no_tags=true" to the url that excludes the tag facet from loading. This helps load the page if you don't need to use tags, but many people use tags to group items so they need to see the tag facet to do their work.

**Comment by jcoyne** [comment]
Possibly fixed by: https://github.com/sul-dlss/argo/pull/2162

**Comment by peetucket** [comment]
Seems to be fixed by #2162
