### ISSUE TITLE
Integrate approach to report views

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#221]
The difference between Report View and Discovery Report used to be real, separate code addressing separate lists of fields (with overlap), basically a DOR vs MODS reporting distinction. Since they are both populated from the same superset of indexed fields, there could conceptually be just one report with multiple "views" simply a matter of default field selection. This would allow greater flexibility in column selection, and open up the possibly of additional "views" -- such as a request report on APO-specific fields. 

This would need a different way to invoke the report views than separate buttons, such as combining all view switching into a dropdown menu button.

**Comment by drh-stanford** [comment]
Is this moot now that the Discovery views are disabled?

**Comment by andrewjbtw** [comment]
Having started in 2019, I do not know what "Discovery view" is referring to here as I do not believe it is in Argo, unless it now goes by another name. 

@blalbrit is this still relevant to how Argo works or is it ok if I close it?
