### ISSUE TITLE
Setting rights to "dark" in Argo is failing

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2220]
**Describe the bug**
Setting an object's rights to "dark" is failing if any files in the object were previously published and/or shelved (i.e. there are files with "publish=yes" or "shelve=yes" in the contentMetadata).

Honeybadger error: https://app.honeybadger.io/projects/49894/faults/66958746

It looks like the system is validating that an item with rights set to dark does not have any shelved or published files. This is a good validation to have, but it will always fail if the system doesn't change the contentMetadata first when changing rights to dark. Users shouldn't be expected to edit the contentMetadata themselves to change the publish and shelve settings for all files, as that would require directly editing the XML. The act of setting rights to dark is supposed to apply contentMetadata changes automatically.

**User Impact**
It is not possible to set rights to dark via the set rights interface. This may result in delays in unpublishing purls. Time is usually a factor when purls are unpublished, since the most common reasons to set rights to dark are permissions or privacy issues, so a delay in applying these rights is a potentially serious problem.

**To Reproduce**
1. Go to an item in Argo that has 1) a published purl and 2) files available to access from the purl
2. Open the item for modification
3. Attempt to set rights to dark
4. The error will result in you being taken to the general library-status page
5. Check honeybadger

**Expected behavior**
Setting rights to dark should apply a change to the contentMetadata to set all files listed there to:

publish="no"
shelve="no"

This change should not affect the preserve status. That should remain "yes" or "no" according to how it was before the rights were set to dark.

**Additional context**
The expected behavior is how setting rights to dark has been applied since at least 2019, when I started at Stanford. Previously, when setting rights to dark, I'd see a corresponding change in the contentMetadata.

**Comment by jcoyne** [comment]
Original ticket for this feature was https://github.com/sul-dlss/dor-services-app/issues/768 and the feature was added https://github.com/sul-dlss/dor-services-app/commit/ec1af0dc4ac32dd508c6f3cbc22d52e0f0052948

**Comment by mjgiarlo** [comment]
@jcoyne @andrewjbtw So it sounds like there are two bits of work to do here:

1. Move validation in dor-services-app from before the update operations to after (but still before the save!), or split up validation such that some applies before and some after? https://github.com/sul-dlss/dor-services-app/blob/faaa0e3ddba559ded2e856e4adbc5247989220c9/app/services/cocina/object_updater.rb#L22-L43
2. In argo `set_rights`, re-generate content metadata to pass along to dor-services-app as `structural.contains` with updated shelve/publish values? https://github.com/sul-dlss/argo/blob/master/app/controllers/items_controller.rb#L212-L230

**Comment by mjgiarlo** [comment]
Or should the content metadata changes happen on the DSA side (not the argo side) whenever access is set to dark? Perhaps the second bullet above is not necessary.

**Comment by jcoyne** [comment]
@mjgiarlo I don't think we'd want to move validations at all.  We either don't want to have this validation, or we should mutate the contentMetadata to disable shelve/publish on all files.

**Comment by jcoyne** [comment]
@mjgiarlo I think mutating the contentMetadata should happen by the client (i.e. Argo) so that we can keep DSA a simple read/validate/write API.

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> > Or should the content metadata changes happen on the DSA side (not the argo side) whenever access is set to dark? Perhaps the second bullet above is not necessary.
> 
> @mjgiarlo I think mutating the contentMetadata should happen by the client (i.e. Argo) so that we can keep DSA a simple read/validate/write API.

OK, looking at the validator in more depth, this seems best and should allow the object to pass validation.

**Comment by andrewjbtw** [comment]
That looks like a good solution to me too.

I remember https://github.com/sul-dlss/dor-services-app/issues/768 but I thought it had been reverted because it immediately caused dark items to fail accessioning when coming through pre-assembly, and what I'd asked for was for pre-assembly to apply the correct settings, which it wasn't doing. Looking at Slack, I see the validation was just suspended at the time via commenting out: https://stanfordlib.slack.com/archives/C09M7P91R/p1585932670410900

**Comment by andrewjbtw** [comment]
Ok, after multiple close readings and then re-readings of https://consul.stanford.edu/display/chimera/Object+Rights+Overview and the exceptions described therein, I propose the following:

1. Setting rights to dark should have the client set publish/shelve to no on all files (as discussed above)

But also 2. we should not validate that files have publish/shelve = no when the rights are set to dark. That's because we can't rely on existing data to be consistent with this. The object rights scheme as currently designed leaves open the possibility of exceptions where some files are shelved even when rights are dark. This seems to be how web archive crawl accessioning works: WARCs get shelved, but no purl is created (only seeds, not crawls, get purls). There may be other cases I don't know about.

**Comment by jcoyne** [comment]
@andrewjbtw if we remove that validation, we have no mechanism to prevent new bad data from being created. Can we move the validation elsewhere?

**Comment by mjgiarlo** [comment]
For now, for this particular issue, can we "fix" the first bit (Argo should update contentMD when setting rights to dark) and delve into the second bit elsewhere? I am wondering if this second bit is FR-worthy or not.

**Comment by andrewjbtw** [comment]
I think the problem we have is that allowing for exceptions was built into the original rights modeling. From the Consul page linked above:

```
Exceptions are possibly based on custom settings, e.g., the shelving of "dark" objects for purposes other than PURL delivery, e.g., text mining.
```

So I don't think we have a way to tell programmatically when a dark object has a "legitimately" shelved file.

**Comment by mjgiarlo** [comment]
I hear ya. Are we currently getting errors related to this darkness validation in dor-services-app that are not related to this issue? Or is this to prevent against future errors?

**Comment by andrewjbtw** [comment]
@mjgiarlo We aren't seeing current errors, but there are many web archive crawl objects with shelved files and dark rights, such as: https://argo.stanford.edu/view/druid:bb077hj4590

I'm not sure what the intent is behind those settings or if new crawls will be getting the same settings as Peter starts accessioning web archives again.

**Comment by mjgiarlo** [comment]
@andrewjbtw :speech_balloon: 
> @mjgiarlo We aren't seeing current errors, but there are many web archive crawl objects with shelved files and dark rights, such as: [argo.stanford.edu/view/druid:bb077hj4590](https://argo.stanford.edu/view/druid:bb077hj4590)
> 
> I'm not sure what the intent is behind those settings or if new crawls will be getting the same settings as Peter starts accessioning web archives again.

OK, then in that case, may I ask that this be written up as a new issue and prioritized? Do we think it's worthy of FR attention or is it low enough priority that it can wait for a dedicated WC, a maintenance WC, or an unscheduled week? cc: @vivnwong
