### ISSUE TITLE
Support multiple collections in cocina.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2233]
currently the cocina model only supports an item belonging to a single collection:
```
"structural": {
  "contains": [],
  "hasMemberOrders": [],
  "isMemberOf": "druid:bc123df4567",
  "hasAgreement": "string"
}
```

however, Argo seems to support multiple collections right now.  Should we change argo such that each object may only belong to a single collection?
<img width="1157" alt="Screen Shot 2020-08-27 at 4 11 39 PM" src="https://user-images.githubusercontent.com/92044/91495312-01178d00-e880-11ea-8a0b-600ff4db2b14.png">

Or should we change cocina-models to support multiple collections per object?

**Comment by andrewjbtw** [comment]
We should support multiple collections per object. I had thought that there was only supposed to be one, but have learned over time that the system was designed to allow more. Some large projects already rely on this (many Revs items are in two collections) and there may be other cases I haven't come across yet.
