### ISSUE TITLE
Argo cannot change rights for collections

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2237]
**Describe the bug**
Trying to change rights for a collection via Argo's set rights button results in users being sent to the library status page.

**User Impact**
Changing collection rights can only be done by editing the rightsMetadata XML.

**To Reproduce**
1. Go to a collection object, e.g. https://argo.stanford.edu/view/druid:gd820bg1570
2. Open the object
3. Click on the set rights blue button
4. Pick a rights setting and click update
5. See the library status page

**Expected behavior**
Argo should be able to set rights to collections.

**Additional context**
The following rights-related functions seem to work:

- setting rights when registering a collection
- applying APO defaults to a collection
- setting rights for individual items

This bug may have been introduced with CDL-related changes but all rights options appear to generate the error, not just CDL rights.

**Comment by jcoyne** [comment]
I think this is fixed by #2208

**Comment by peetucket** [comment]
@aaron-collier confirmed this should be fixed by #2208 (CDL work) -- so let's wait until that is reviewed, merged and deployed and then verify again before further work is done.

**Comment by andrewjbtw** [comment]
I checked collections in stage and I'm not sure the problem is fully resolved. There's no error now, but the update isn't taking effect and the rights remain the same.

The druid I've been trying to update is this: https://argo-stage.stanford.edu/view/druid:gj743yv4606

**Comment by peetucket** [comment]
I tried updating that collection to "stanford" and the event seems correct, but the rightsMetadata XML datastream and cocina model representation don't change.

Events from the change:
```
{
  "host": "dor-services-stage.stanford.edu",
  "type": "http://cocina.sul.stanford.edu/models/collection.jsonld",
  "label": "French elections test",
  "access": {
    "access": "stanford",
    "download": "stanford"
  },
.....
```

Cocina model:
```
{
  "type": "http://cocina.sul.stanford.edu/models/collection.jsonld",
  "externalIdentifier": "druid:gj743yv4606",
  "label": "French elections test",
  "version": 2,
  "access": {
    "access": "world",
    "download": "world"
  },
```

**Comment by jmartin-sul** [comment]
@peetucket says this is hopefully fixed w/ deployment of CDL work (which should be on prod already)

**Comment by jmartin-sul** [comment]
@andrewjbtw will confirm

**Comment by peetucket** [comment]
I just tested this in prod against a test collection and it worked as expected.  Closing.
