### ISSUE TITLE
Improve navigation for collection drop-down list on Registration page

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#224]
Problem: Long lists of collections for some APOs are difficult to navigate when registering objects. Similar to issue of finding a specific collection in the long facet list.

Description (from Doris): 
Could we make the collection field an autocomplete field, or at least alphabetically sorted? Or enter in the druid for the collection? At the moment the collections appear in order of chronological creation and for an APO with many collections (such as the Special Collections APO) it really takes me a few minutes to scroll to find the one I'm looking for.

**Comment by andrewjbtw** [comment]
The collections list is now alphabetically sorted and if you type a couple of characters quickly, it will take you to that place on the list. Not quite an autocomplete, but an improvement over what it sounds like this used to do. 

I'm going to close this in favor of opening another issue if more improvements are needed, as I don't think the issues that motivated this ticket still apply - at least not in the same way.
