### ISSUE TITLE
Object stuck in accessionWF at end-accession step

### ISSUE THREAD

**Issue by cebraj** [sul-dlss/argo#2241]
druid:fj170xk4328 was being edited back in July by a metadata staff person and then I encountered it the other day to close the object and release it to Searchworks, but the object encountered an error at the technical-metadata step. I reran the step and the object then encountered an error at the end-accession step, and seems to be stuck there.

**User Impact**
Unable to close the object and send it through the releaseWF so the MARC record can be updated with the PURL in Searchworks.

**To Reproduce**
See accessionWF for druid:fj170xk4328

**Additional context**
I noticed this is a Hydrus object with the Free EEMs APO, I'm not familiar with the EEMs workflows but thought I'd note that!

**Comment by andrewjbtw** [comment]
This cleared up with a reset, though it took a couple of tries.

**Comment by cebraj** [comment]
Thanks again, Andrew!
