### ISSUE TITLE
2 objects in error state

### ISSUE THREAD

**Issue by cebraj** [sul-dlss/argo#2242]
**Description**
I uploaded descriptive metadata for about 6,000 objects (1,000 at a time) in the Road & Track collection, and after closing them I noticed 2 objects were still in 'In accessioning' state with an error at the end-accession step.

See:
druid:mf516wt4563
druid:mw167zy3254

**User Impact**
Cannot close version.

**To Reproduce**
See accessionWF for the objects above.

**Additional context**
I don't think these objects have been touched in a long time.

**Comment by andrewjbtw** [comment]
These cleared up with a step reset.

**Comment by cebraj** [comment]
Thank you Andrew! Sorry for the trouble when I could have rerun the step myself! Those errors looked intimidating! Object status looks good now.
