### ISSUE TITLE
Argo cannot update rights for registered Hydrus objects

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2248]
**Describe the bug**
Attempting to update the rights for a registered Hydrus object generates an error and the user ends up on the library system status page.

https://app.honeybadger.io/projects/49894/faults/67600377

**User Impact**
It's not possible to update rights for Hydrus items via Argo. This is sometimes necessary to fix problems with Hydrus objects that can't be fixed using the Hydrus form.

**To Reproduce**
1. Go to a registered Hydrus item in Argo https://argo.stanford.edu/view/zx944yv4526
2. Try to change the rights
3. See the rrror

**Expected behavior**
It should be possible to change the rights

**Additional context**
This problem seems to have started in the past few days. I changed the rights on a registered hydrus object last Tuesday (2020-09-08).

**Comment by peetucket** [comment]
From Justin: We need a special hydrus exception right here: https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/object_updater.rb#L110

**Comment by peetucket** [comment]
The underlying honeybadger alert from DSA: https://app.honeybadger.io/projects/50568/faults/67600382

**Comment by mjgiarlo** [comment]
@andrewjbtw This is still in the infra team FR list. Are you confident this is a thing of the past or does this need more attention?

**Comment by andrewjbtw** [comment]
This was fixed with that late Friday deploy and I've verified it. I didn't realize it was still on the list since the issue was already closed.

**Comment by mjgiarlo** [comment]
@andrewjbtw ok, thanks!
