### ISSUE TITLE
Add a confirming dialog as part of Purge

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#225]
Remarkably, if you press the Purge button it simply happens, without confirmation.  We need a simple  dialog alert for the user as to the object scope (being deleted from DOR/Fedora) and permanence (no recovery). Message:

Do you mean to permanently delete this object from DOR and the Repository? This action cannot be undone.

[yes] [no] or [ok] [cancel]

**Comment by mejackreed** [comment]
Are you seeing this on dev? I can't seem to replicate the behavior on a deployed server (don't have access to purge?), but locally I am getting the dialog box

**Comment by blalbrit** [comment]
@LynnMcRae - please verify.

**Comment by mejackreed** [comment]
Also to note we use the default alert dialogs here rather than rolling our own.

**Comment by mejackreed** [comment]
Verified that this is already implemented using native browser alert dialogs and default Rails way to enact this. Please reopen if needed for something else.
