### ISSUE TITLE
Lifecycle timestamps for all versions are given the dates from the current version when a new version is accessioned

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2252]
**Describe the bug**
When accessioning a new version of an item, all lifecycle timestamps are updated to the same dates as in the current version.
 
For example, this item that was first accessioned in 2017 now shows only 2020 dates:
https://argo.stanford.edu/view/druid:sq224vf9255

**User Impact**
It's not possible for Argo users to see the version history of objects, beyond the version names.

**To Reproduce**
1. Go to an object in Argo
2. Create a new version
3. See the timestamps for all versions get updated to the dates for the current version

**Expected behavior**
The lifecycle timestamps should not change for previous versions.

**Screenshots**
Here's a lifecycle excerpt from an item that was first created in 2017, now showing only 2020 dates

<img width="533" alt="Screen Shot 2020-09-18 at 9 28 46 AM" src="https://user-images.githubusercontent.com/8975583/93622115-6e0ad800-f991-11ea-9cc4-578287093181.png">

**Additional context**
We recently made changes that were intended to fix problems with lifecycle timestamps that might have instead caused this problem. See https://github.com/sul-dlss/argo/issues/2192

Also, I'm not sure this is reproducible in stage. It depends on if the stage workflow DB got the same change as the prod workflow DB.

**Comment by andrewjbtw** [comment]
See also https://github.com/sul-dlss/workflow-server-rails/pull/410

**Comment by mjgiarlo** [comment]
This issue is closed, but note that @andrewjbtw would like us to pursue correcting completed_at dates in production. I have asked @vivnwong to set up a 30-minute meeting for Andrew, myself, @jcoyne, and @peetucket at our earliest convenience.
