### ISSUE TITLE
Setting rights via Argo is failing for some druids

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2253]
**Describe the bug**
A large number of druids hit errors when trying to change rights in Argo today. This happened using both the bulk update and the blue button methods to set rights.

This looks like a related HB error: there's a very long 400 message for the items that errored on rights today: https://app.honeybadger.io/projects/49894/faults/67600377

This does not appear to be affecting all druids, just some. I've looked for a pattern and the closest I've gotten is that many failed objects have brackets in the title. But not all failed objects have brackets.

**User Impact**
It's not possible to change rights for these items except via individual XML edits. With hundreds of druids to update, that's not a good workaround.

**To Reproduce**
1. Go to an item where rights changes are failing, example: https://argo.stanford.edu/view/druid:bz093sn0901
2. Open the item for versioning if not already open
3. Try to set the rights with the blue button
4. See the library status page

**Expected behavior**
It should be possible to change the rights

**Additional context**
It doesn't seem to matter which rights setting you choose. I've tried world, dark, stanford. There's a lot of metadata in the error message that isn't even rights, so maybe this is a Cocina problem somewhere else in the items?

**Comment by mjgiarlo** [comment]
Seems like the DRO as passed to DSA (see HB alert) is not validating as a DRO per DSA OpenAPI spec: https://github.com/sul-dlss/dor-services-app/blob/master/openapi.yml#L968-L995

Check the JSON in the HB alert against the DRO schema.

**Comment by jcoyne** [comment]
The problem I'm seeing is:
```
7116 isn't one of in #/components/schemas/DescriptiveBasicValue/allOf/2/properties/value
```

**Comment by jcoyne** [comment]
I've confirmed a bug in the committee gem: https://github.com/interagent/committee/issues/286

**Comment by jcoyne** [comment]
In the meantime, I believe we can work around this by avoiding the use of all digits as an object title.

**Comment by jcoyne** [comment]
It's possible to fix if we backed this change out: https://github.com/sul-dlss/cocina-models/pull/144

**Comment by andrewjbtw** [comment]
It's not realistic to ask people to change titles. Note also there are examples that aren't all digits, like https://argo.stanford.edu/view/druid:yy778md9653

**Comment by jcoyne** [comment]
In the case of https://argo.stanford.edu/view/druid:yy778md9653 it looks like it's getting triggered on the non-sort character count, so actually the same bug.  I think we have to revert https://github.com/sul-dlss/cocina-models/pull/144 until https://github.com/interagent/committee/issues/286 is resolved.
```json
{"note":[{"value":"4","type":"nonsorting character count"}]}
```
