### ISSUE TITLE
Registration should always apply the default <use> and <copryight> statements from the APO defaultObjectRights

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2256]
**Background**
All objects are registered to APOs. All APOs include default rights settings to be applied to all objects under that APO. These default settings are expressed in a datastream called defaultObjectRights. The defaultObjectRights datastream contains a copy of a rightsMetadata datastream to be used when objects are registered to that APO using the APO default settings.

A typical rightsMetadata datastream contains 

- settings for machine-actionable access rights (enclosed in `<access>` tags)
- a use statement (enclosed in `<use>` tags)
- (optionally) a copyright statement (enclosed in `<copyright>` tags)

When a user registers an object, they can either

1. choose the APO default rights
2. choose a non-default rights setting

When choosing option 1 to use the default APO settings, the new objects are created with a rightsMetadata datastream that consists of all the settings in the APO defaultObjectRights. This is the expected behavior and is operating normally.

**The actual issue**
This issue is for what happens when choosing option 2: a non-default rights setting. Currently, when choosing a non-default setting at registration, the rightsMetadata for the newly registered objects contains

1. the appropriate `<access>` settings for the chosen rights
2. a blank set of `<use>` elements 
3. a blank `<copyright>` element

The `<use>` statement should be the one from the defaultObjectRights, not blank. The `<copyright>` statement should only be included if there is one in the defaultObjectRights.

**User Impact**
Users expect to have the APO default `<use>` and `<copyright>` (if present) statements from the APO in all cases, not just when using the `<access>` rights defaults. 

There is no way to fix the rights statements from Argo at scale, which makes it difficult to remediate this issue. The only safe option is to edit the rightsMetadata XML for each affected object. Other workarounds are possible, but risk causing even more problems.

**To Reproduce**
1. Go to the registration form
2. Register an object that doesn't have the default rights from the APO
3. Look at the rightsMetadata
4. See that it is missing the statements from the APO

**Expected behavior**
The `<use>` and `<copyright>` elements should match what it is in the defaultObjectsRights even when the `<access>` rights are different than the defaults.

**Example**
The [ARS APO](https://argo.stanford.edu/view/druid:bz845pv2292) contains the following defaultObjectRights datastream, with access rights of "world":

```xml
<rightsMetadata>
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <world/>
    </machine>
  </access>
  <use>
    <human type="useAndReproduction">Property rights reside with the repository. Literary rights reside with the creators of the documents or their heirs. To obtain permission to publish or reproduce, please contact the Stanford Archive of Recorded Sound at soundarchive@stanford.edu.</human>
  </use>
</rightsMetadata>
```

[This item](https://argo.stanford.edu/view/druid:bb034wm3873) was registered to ARS with access rights of "stanford (no-download)":

```xml
<?xml version="1.0"?>
<rightsMetadata>
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <group rule="no-download">stanford</group>
    </machine>
  </access>
  <use>
    <human type="useAndReproduction"/>
    <human type="creativeCommons"/>
    <machine type="creativeCommons" uri=""/>
    <human type="openDataCommons"/>
    <machine type="openDataCommons" uri=""/>
  </use>
  <copyright>
    <human/>
  </copyright>
</rightsMetadata>
```
Note that the default `<use>` statement is missing from the object. It should have the `<use>` statement from the APO.

**Additional context**
I haven't been able to pinpoint when this issue started, but based on discussions with longtime users like @oceanofsound it seems to be a recent issue.

**Comment by jcoyne** [comment]
Yes, we definitely had this with the legacy registration API, however it wasn't documented, so when we switched to the new cocina registration we lost this:

Old way:
https://github.com/sul-dlss/dor-services-app/blob/9288d205e22472a262aeebc81d1b359e7fa61e32/app/services/registration_service.rb#L131-L139

New way:
https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/object_creator.rb#L83-L89
