### ISSUE TITLE
changing rights on an object is changing the resource type in the contentMetadata

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2261]
**Describe the bug**
When changing the rights on an object, the resource type is also being changed for the files in the object. So far, I've seen this with media objects having their files changed from "video" or "audio" to resource type of "file".

Example from stage:
https://argo-stage.stanford.edu/view/druid:bf297qj6113

Before rights change, the resource type is "audio":
<img width="730" alt="Screen Shot 2020-09-28 at 12 53 51 PM" src="https://user-images.githubusercontent.com/8975583/94479560-d45dda80-0189-11eb-8441-1f8aa345ab79.png">

After changing rights from World to Stanford, resource type is now "file": 
<img width="730" alt="Screen Shot 2020-09-28 at 12 54 25 PM" src="https://user-images.githubusercontent.com/8975583/94479592-e770aa80-0189-11eb-881a-05d91b6331d2.png">

**User Impact**
The resource type + content type determine how items are presented on the purl in sul-embed. When the resource type is incorrect, the player shows an error. Users can't view items and staff who manage the content need to go into Argo and restore the resource types to fix the items.

**To Reproduce**
1. Go to an item in argo that is not already content type of "file", for example: https://argo-stage.stanford.edu/view/druid:cj740sw9922
2. Change the rights
3. See that the resource type is now file

**Expected behavior**
Changing rights should have no effect on resource type.

**Additional context**
Note that this only seems to affect resource type. Content type remains the same.

**Comment by jcoyne** [comment]
This bug is due to a round-trip through the Cocina data model.  We're losing this bit of data.
