### ISSUE TITLE
Changing an object's APO is failing for some web archive objects

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2270]
**Describe the bug**
When trying to change an object's APO, the user gets sent to the library system status page.

**User Impact**
User's can't change an object's APO.

**To Reproduce**
1. Go to https://argo.stanford.edu/view/druid:qy068kt3406
2. Make sure the object is open for versioning
3. Try to change the APO to "Stanford University - University Archives"
4. See the library status page

**Expected behavior**
The object should be assigned to the new APO after the change.

**Additional context**
HB is throwing two errors:
https://app.honeybadger.io/projects/49894/faults/67262678 (Argo)
https://app.honeybadger.io/projects/50568/faults/67262679 (dor services app)

The second honeybadger error is complaining about tags, but the tags don't appear to be a problem with these items unless there's some kind of invalid character in the tag fields that isn't visible in Argo.

**Comment by andrewjbtw** [comment]
Web archive seed https://argo.stanford.edu/view/druid:gc973jd4496 has the same issue.

As does this web archive seed on stage: https://argo-stage.stanford.edu/view/druid:qy692zw8223

**Comment by jcoyne** [comment]
The proximate cause is there is no `webarchive-seed` in this translation table.  https://github.com/sul-dlss/dor-services-app/blob/master/app/services/cocina/to_fedora/process_tag.rb#L8-L27  It looks to me like the result should be 'File' (thus the `Process : Content Type : File` tag).   @andrewjbtw can you confirm that?

**Comment by andrewjbtw** [comment]
This is an odd one. The seed objects just have one file, which is a thumbnail image with resource type "image". So that would point towards making the Process tage image, even though that seems weird. I think with "file" the jp2 might not be processed correctly.

**Comment by andrewjbtw** [comment]
The seed preassembly WF does the contentMetadata in the background as an XML file that gets brought into Fedora.

**Comment by andrewjbtw** [comment]
For posterity's sake, the solution we arrived at was to add a Process tag for the content type "webarchive-seed", which makes it consistent with other content types that also get Process tags.
