### ISSUE TITLE
Can't register to CDL rights

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2279]
**Describe the bug**
Registering an item with CDL rights isn't working. Attempts to register are generating this error:

`cdl-stanford isnt include enum in #/components/schemas/DROAccess/properties/access`

The error appears on the Argo registration form when you hover over the red alert triangle (see screenshot below).

**User Impact**
Digitization staff can't register objects to CDL rights. Objects have to be registered citation-only and changed later.

**To Reproduce**
1. Go to Argo registration form
2. Try to register with the "controlled digital lending (no-download)" rights
3. See error

**Expected behavior**
Registration should accept all the rights choices.

**Screenshots**
<img width="960" alt="Screen Shot 2020-10-12 at 3 40 25 PM" src="https://user-images.githubusercontent.com/8975583/95796403-a60bef00-0ca1-11eb-9104-99d7d2c8b30c.png">

**Additional context**
Changing the rights later seems to still be working. At least, I changed 3 items earlier in the day, before this error at registration was reported.

**Comment by justinlittman** [comment]
@andrewjbtw Can you test the fix on stage?

**Comment by andrewjbtw** [comment]
@justinlittman looks good, just registered a CDL object on stage.
