### ISSUE TITLE
"No object title" facet is reporting the wrong data

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2281]
**Describe the bug**
The "No object title" facet is reporting that over 2.6 million objects don't have a title, which is practically all of SDR. That can't be right.

**User Impact**
It's hard to find objects that actually don't have a title, which we need to find for remediation purposes, and to migrate to Cocina.

**Screenshots**

<img width="360" alt="Screen Shot 2020-10-15 at 9 57 21 AM" src="https://user-images.githubusercontent.com/8975583/96162406-590c6080-0ecd-11eb-9d89-b2ef4c7a9dc2.png">

**Comment by jcoyne** [comment]
It looks like this is looking for a blank `dc_title_ssi`:
```
                                        no_object_title: { label: 'No Object Title', fq: '-dc_title_ssi:*' },
```

However that field is no longer indexed.
