### ISSUE TITLE
Create collection from catkey is failing for certain catkeys

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2284]
**Describe the bug**

Creating a collection from the catkey 4082833 is failing. It seems to be related to Cocina descriptive metadata mapping.

The relevant HB error is: https://app.honeybadger.io/projects/50568/faults/68951103

**User Impact**
This blocks creating a collection from this catkey, which blocks being able to use the collection and release it to SearchWorks. There's also no useful warning or explanation of what's going on in the Argo interface when creating the collection fails.

**Expected behavior**
It should be possible to create a collection from any catkey.

**Additional context**
A number of other catkeys work. This seems specifically related to metadata, not a more systematic problem with the mechanics of creating collections. Other catkeys may fail for metadata reasons as well.

**Comment by jcoyne** [comment]
@andrewjbtw can you confirm that this is now resolved?

**Comment by andrewjbtw** [comment]
This has been addressed through improved mappings.
