### ISSUE TITLE
Retrieval from SDR or Stacks fails with a 500 / network error

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#2290]
When I click on the file-link to download a file from an item's content list, the action fails with a network error.

**User Impact**
Inability to retrieve required files.

**To Reproduce**
1. Go to https://argo.stanford.edu/view/druid:dw701xc8811
2. Scroll down into the content section
3. Click on any file (tiff for SDR retrieval, jp2 for stacks retrieval)

**Expected behavior**
File should begin to download to local machine.

**Screenshots**

![sdr_retrieve](https://user-images.githubusercontent.com/796990/97237509-7fbb7880-17a4-11eb-9315-007348372065.gif)

**Additional context**
Associated with https://app.honeybadger.io/projects/49894/faults/65949933

**Comment by andrewjbtw** [comment]
Added this to the first responder list. It looks like another problem with the Cocina representation.

**Comment by andrewjbtw** [comment]
On further inspection, this might be resolved with a sourceId update.

**Comment by vivnwong** [comment]
First Andrew or Ben will do the sourceID fix. I will not prioritize this for FR until Andrew sees the need of Dev time after the sourceID fix.

**Comment by justinlittman** [comment]
This problem seems resolved. Can it be closed?

**Comment by jcoyne** [comment]
I think this problem is resolved on the particular data pointed at above, but it does break for anything in https://argo.stanford.edu/catalog?f[data_quality_ssim][]=Cocina+conversion+failed  I this this is related to https://github.com/sul-dlss/dor-services-app/issues/1284 and will also require a change to the error handling code in Argos javascript.

**Comment by jmartin-sul** [comment]
copying in the argo backtrace detail for convenience and posterity:

        Dor::Services::Client::UnexpectedResponse: Internal Server Error: 500 (Response from dor-services-app did not contain a body. Check honeybadger for dor-services-app for backtraces, and look into adding a `rescue_from` in dor-services-app to provide more details to the client in the future)

            [PROJECT_ROOT]/app/controllers/files_controller.rb:106 :in `load_resource`

            104 
            105   def load_resource
            106     @cocina_model = Dor::Services::Client.object(params[:item_id]).find
            107   end
            108 end

        Full Backtrace

            [GEM_ROOT]/gems/dor-services-client-6.14.1/lib/dor/services/client/versioned_service.rb:34 :in `raise_exception_based_on_response!`
            [GEM_ROOT]/gems/dor-services-client-6.14.1/lib/dor/services/client/object.rb:61 :in `find`
            [PROJECT_ROOT]/app/controllers/files_controller.rb:106 :in `load_resource`
            [GEM_ROOT]/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:426 :in `block in make_lambda`
            [GEM_ROOT]/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:198 :in `block (2 levels) in halting`
            [GEM_ROOT]/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:34 :in `block (2 levels) in <module:Callbacks>`

**Comment by andrewjbtw** [comment]
I wrote up a separate issue for the general case of seeing "network error" in this situation: https://github.com/sul-dlss/argo/issues/2306

**Comment by andrewjbtw** [comment]
I am closing this as the specific issues that prevented this download have been addressed with improved Cocina mapping and error handling.
