### ISSUE TITLE
All objects in this collection button no longer works

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2297]
**Describe the bug**
It takes you to this page: https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Afh328wh9066

which seems to show all items.
<img width="744" alt="Screen Shot 2020-10-29 at 7 38 15 AM" src="https://user-images.githubusercontent.com/92044/97574761-b61e1100-19b9-11eb-80b7-dfd28b4a389a.png">

**Comment by andrewjbtw** [comment]
@jcoyne It looks like there might be a more general problem with aggregate searches turning up all druids. I got 2.6 million results for a Project tag https://argo.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=Fitch

<img width="731" alt="Screen Shot 2020-10-29 at 8 49 28 AM" src="https://user-images.githubusercontent.com/8975583/97598104-cd61fc00-19c3-11eb-8fd3-819dbec578fa.png">

**Comment by jcoyne** [comment]
Yes, it's also not working for "All objects with this APO".   It's possibly because these were not linking to defined facets and were just throwing solr fields at blacklight.  I believe I saw Chris wrote a change that prohibits this because it could leak data.

**Comment by andrewjbtw** [comment]
That must explain why getting all items in an APO using the APO facet does still work: https://argo.stanford.edu/catalog?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=%C3%87atalh%C3%B6y%C3%BCk

**Comment by andrewjbtw** [comment]
Did this come in with a recent Blacklight upgrade? It's a pretty significant problem from a user standpoint. Being able to click on links on an item page and get taken to a search is a huge part of how people get around in the system.

I'll need to send out a notice if it can't be reverted or resolved. cc @vivnwong

**Comment by justinlittman** [comment]
It appears the fq field is empty on the query: `"fq"=>[]`.

**Comment by peetucket** [comment]
The links on the item page are being generated via this helper: https://github.com/sul-dlss/argo/blob/master/app/helpers/value_helper.rb

As @jcoyne noted, they seem to be hardcoding specific solr fields to query on (e.g. https://github.com/sul-dlss/argo/blob/master/app/helpers/value_helper.rb#L91) which may no longer be correct or aren't working with the new version of Blacklight?  

If you try the find objects by following the path from the facet links (where it does work), you will see the difference.

e.g. for all objects in the collection, this is the query being run if you find the collection in the Collection facet:

https://argo.stanford.edu/catalog?all=true&f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=SITE+Archive+-+world

and this is the link generated by the helper on that item page to view the items in the collection:

https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Aqf495kg6879

Its similar situation for items in the APO and with the project tag.
