### ISSUE TITLE
Show a descriptive error message when metadata import from Symphony fails

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2303]
**Describe the bug**
There are at least three places where Argo imports metadata from Symphony:

1. Registration with a catkey
2. Refresh MODS for an item with a catkey
3. Create a collection from Symphony (i.e. from a catkey supplied when creating the collection)

If the metadata import does not map to Cocina, these steps will fail. Since we fixed our mappings last week, I have not been able to find a catkey that will generate a Cocina error, so I haven't been able to test exactly what happens. However, based on recent experience, it appears that a failure to import the metadata will send the user to the library status page with no explanation of what happened.

These two issues both stem from the same catkey and both led to the library status page until the mapping was updated:
https://github.com/sul-dlss/argo/issues/2284
https://github.com/sul-dlss/dor-services-app/issues/1227

**User Impact**
Users are not able to create or manage objects whose metadata does not map to Symphony. It is also frustrating to have Argo redirect to the library status page, as the library status page doesn't show anything about Argo or internal systems.

**To Reproduce**
As noted above, reproducing this error would require a catkey that won't map. The steps are different for each of these actions.

- For registration, this would be triggered by including a problematic catkey on the registration form
- For refresh MODS, this would be triggered by the individual or bulk action MODS refresh
- For create a collection from Symphony, this would be triggered from the Create a collection page, available as a blue button link on an APO page

**Expected behavior**
Argo should show a message that the metadata import failed. Details may not be available, but we should show some indication of what happened so that the user knows

1. that there was an error
2. that someone can look into it

**Additional context**
Resolving the issue could mean fixing the MARC, or it could mean fixing the mapping. It may not be possible to catch all MARC issues before import is tried, so we should have a way of handling this possibility gracefully.

**Comment by jcoyne** [comment]
@andrewjbtw I think we have fixed all the mapping issues.  I'm not sure there is a way to reproduce this issue at this time.

**Comment by andrewjbtw** [comment]
I believe this is now in place as improved error reporting has been implemented alongside the MODS/descMetadata validation. Closing this now as we don't have a known non-importable catkey record to test with. If it occurs again we can file a new issue.
