### ISSUE TITLE
Reduce limit for the tags facet to make load time of home page faster

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#2304]
**Describe the bug**

The home page of argo takes a long time to load, since we allow 9999 tags in the facet.  Reduce the number to 100 and force users to click more.

See https://github.com/sul-dlss/argo/blob/master/app/controllers/catalog_controller.rb#L63

Also see #2305 to improve the user experience

**User Impact**

The home page is really slow to load with 9999 tags shown.

**To Reproduce**

Confirm skipping tags is fast:

https://argo.stanford.edu/?no_tags=true

and loading tags is slow:

https://argo.stanford.edu

**Comment by vivnwong** [comment]
If we have to do this work, Andrew needs more time to define what are the most used tags. We should approach this in a regular WC.

**Comment by jcoyne** [comment]
Closed this because we implemented the lazy loading tags facet.
