### ISSUE TITLE
Instead of "network error" show a descriptive message when a modal won't load because of a Cocina issue

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2306]
**Describe the bug**
When an item doesn't have a valid Cocina representation, certain actions will pop up a window with a message that just says "Network error". These actions are:

- the "Set rights" blue button
- clicking on a file in the file list (under contents) to download a file

Since the issue isn't really a network error, show a message that indicates that it is related to Cocina.

**User Impact**
Users are blocked from the tasks they are trying to do, and are shown a misleading message. To the extent possible, a message like "network error" should be reserved for when there is a real network connection problem.

**To Reproduce**
I've made an object with a non-valid source id on stage for testing:
https://argo-stage.stanford.edu/view/druid:qv217cy9963

1. Go to the example item above
2. Click on "set rights" or try to download "testfile.txt"
3. See a window pop up with the message "network error".

**Expected behavior**
If the Cocina representation is the problem, the error message should indicate that.

**Screenshots**
This is the only message people see for this error:
<img width="1202" alt="Screen Shot 2020-11-03 at 12 29 54 PM" src="https://user-images.githubusercontent.com/8975583/98037395-55833f80-1dd0-11eb-9815-5465b643c213.png">

**Comment by jmartin-sul** [comment]
@andrewjbtw just want to confirm that this is still an issue?

@jermnelson just want to confirm that this is still unimplemented?

unassigning for now and putting back in ready, feel free to fix if that's wrong...

**Comment by andrewjbtw** [comment]
It's still an issue. It looks like at some point I fixed the source id in the example linked above, but I've now made it invalid again so that the Cocina mapping doesn't work. The "network error" now pops up again when you follow the steps to reproduce.

**Comment by jmartin-sul** [comment]
thanks, @andrewjbtw (we were just making sure the board was accurate during first responder handoff)

**Comment by ndushay** [comment]
fwiw, I have been poking at both of these, and I'm able to see where the cocina_model errors are being raised and to capture the messages, but I can't find where the "network error" lightboxes are coming from, nor change their content, nor avoid them.
