### ISSUE TITLE
Determine cause of Argo front page slowness

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2308]
**Describe the bug**
The Argo front page can take up to a minute to load. Maybe more if someone has not already gone through the Stanford login process, which always adds extra time.

**User Impact**
It slows users down and in a number of cases it's made people think Argo is actually down rather than slow. 

Individual item pages don't seem to be affected, and searches that don't return a lot of data in the facets seem to run fine.

**To Reproduce**
Go to the Argo front page and wait. Similar wait times affect the "expand to show all facets" display and the workflow grid.

**Expected behavior**
Argo isn't the fastest website, but it should load more quickly than a minute. 

**Additional context**
There's been some discussion about the cause of the slowness. Unfortunately, we've never benchmarked Argo performance during "normal" times so we do not have formal data for comparison.

There's a theory that the cause of the slowness is the number of tags that Argo has to load. This theory is based on the fact that when Argo is slow, the tags are the data that takes longest to load. Loading Argo without showing tags is much faster.

I do not think that we have sufficient evidence to support this theory because we did not measure Argo performance with and without tags during times when Argo has not been slow. The fact that Argo takes a long time to load tags when Argo is slow does not demonstrate that loading tags is the cause of Argo being slow. There could be a different underlying cause that slows down Argo, with slow loading tags being a symptom of that same cause, not the cause itself.

My experience with Argo this summer and fall suggests that tags are not the reason Argo has been slow. I use Argo every weekday, I load the workflow grid multiple times per day, and I always display the tags facet. If Argo had been uniformly slow all summer, I would have noticed it. Instead, Argo has been slow, then not slow, then slow again. No changes to tags have been made during these periods.

Consider the following, which is based on my experience plus user reports:

1. July: Argo took nearly a minute to load, very similar to the current issue
2. Early August up until the last week of October: Argo loaded much more quickly
3. Starting last week (late October) up until now: Argo back to loading slowly

That suggests to me that 

- a change made in early August sped up Argo performance and 
- a change made in late October slowed it down again

**Suggestion: look at componentized facets**

I went back through the change history, and this is what I found:

- Argo became noticeably faster after this pull request to componentize the facet configurations was deployed in early August: https://github.com/sul-dlss/argo/pull/2162/files (see discussion on Slack after the change was made: https://stanfordlib.slack.com/archives/C0EAZ09QF/p1596647909226600 )

- Argo became noticeably slower last week, which corresponds to another pull request that configured facets. But these new facet configurations do not appear to be componentized: https://github.com/sul-dlss/argo/pull/2299/files

I cannot be certain that this later change is the source of the performance issues, but changes to facet configuration do meet the following criteria:

1. The changes in early August were followed by an improvement in performance
2. The changes in late October were followed by a decrease in performance

I do not see any changes involving tags that correspond to performance changes during these periods, so I am not convinced that tags are the problem. If tags aren't the problem, then changing how we handle tags might not improve things substantially. And since changing how we handle tags by splitting some out into a new facet will have a highly visible and significant impact on users, I'm hesitant to make that change right now if a less visible configuration change will improve things substantially.

**Comment by jmartin-sul** [comment]
@aaron-collier just want to confirm that there's not currently work in progress on this?

unassigning and sending back to ready col...

**Comment by jcoyne** [comment]
I looked into these slow requests on newrelic and it looks like it's slow because it's spending all it's time drawing tags:
<img width="863" alt="Screen Shot 2020-12-02 at 11 18 01 AM" src="https://user-images.githubusercontent.com/92044/100911176-82d91100-3494-11eb-9796-9bb488120ded.png">

<img width="1132" alt="screen_shot_2020-12-02_at_11 24 17_am" src="https://user-images.githubusercontent.com/92044/100911357-bae05400-3494-11eb-9598-31aa2f1f09ca.png">


This is a profile trace. The percentage is time the server spends in one method in a 5 minute stretch. It is not percentage of a single request:
<img width="1280" alt="Screen Shot 2020-12-02 at 11 47 25 AM" src="https://user-images.githubusercontent.com/92044/100911175-82407a80-3494-11eb-9043-836d7ea519f9.png">

**Comment by jcoyne** [comment]
on every index page without filters selected there are 10,451 tags being drawn, you can see this by running this javascript on the page: `document.querySelectorAll('[role="treeitem"]').length`

**Comment by jcoyne** [comment]
https://github.com/sul-dlss/blacklight-hierarchy/pull/38 improves this (due to deprecation warnings being logged 10,500 times)

**Comment by andrewjbtw** [comment]
Closing this issue as we have improved the page loading from the code side. As we may have hit the limit of what we can do with the current approach to tags, I'll work with Astrid to see if we how we can redesign this to be more efficient and usable.
