### ISSUE TITLE
CDL: to support digital lending, make "barcode" a supported identifier field

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2315]
As implemented, the digital lending system requires an item's barcode to be specifically designated as an `otherId` in the identityMetadata for an object. This is necessary so that:

1. The barcode gets published to the PURL XML
2. The barcode gets included in the 856 field for the SearchWorks release
3. The barcode is unambiguously identified as a barcode, so no special parsing is required of the sourceId
4. The barcode connects the item to the Symphony circulation status, which relies on barcodes not catkeys

An example of an identityMetadata with a barcode for a digitally lent item:

```xml
<identityMetadata>
  <sourceId source="sul">36105231407466</sourceId>
  <otherId name="catkey">1718084</otherId>
  <otherId name="barcode">36105231407466</otherId>
  <objectLabel>The Arab apocalypse</objectLabel>
  <objectId>druid:dn829dw4771</objectId>
  <objectCreator>DOR</objectCreator>
  <objectType>item</objectType>
  <release what="self" to="Searchworks" who="bergeraj" when="2020-10-23T05:56:20Z">true</release>
</identityMetadata>
```
The above item has the following 856:

```marc
856 4 1 u| http://purl.stanford.edu/dn829dw4771 x| SDR-PURL x| item x| barcode:36105231407466 x| file:dn829dw4771%2Fdn829dw4771_0001.jp2 x| rights:cdl
```

**What does support for barcodes entail?**

1. A user can enter the barcode during Argo registration
2. A user can enter the barcode using a "blue button" on an Argo show page
3. A user can supply barcodes in bulk using a bulk action
4. The barcode is automatically entered as an `otherId` in identityMetadata
5. The barcode is included in the Cocina representation as a barcode (not just in source id)

Barcode support can be modeled on catkey support, which functions the same way in terms of data entry.

**How are barcodes entered right now?**

Someone (i.e. usually me) enters them directly into the identityMetadata via XML editing. This is workable for now, but does not scale.

**Why aren't catkeys enough?**

Digital lending requires management at the physical item level. Catkeys are conceptual and do not have a one-to-one relation to physical items. The library may have multiple copies of an item for a catkey, or in the case of serials it may have multiple different volumes that each have their own barcode but all share the same catkey.

**Comment by saseestone** [comment]
Adding a note here at @cbeer request that currently we are validating the barcode (must start with "36105") but that validation is causing an issue.  We have our first Special Collections item approved for CDL (rare book facsimile, in copyright).  That "barcode" is actually an Item ID stored in the Symphony record and has a pattern of [ckey-####] 

Example SW record: [https://searchworks.stanford.edu/view/6772719](https://searchworks.stanford.edu/view/6772719)
Barcode/Item ID: 6772719-1001

It's conceivable that we would also have this service for Business Library materials at some time.  Business barcodes begin with "2050"

**Comment by andrewjbtw** [comment]
Good catch. We have at least one business book in SDR already (not currently borrowable): https://argo.stanford.edu/view/druid:cp590xz6533
