### ISSUE TITLE
Sidekiq jobs (bulk actions) restart when Argo is redeployed

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2317]
**Describe the bug**
When Argo is redeployed, sidekiq jobs restart from the beginning.

**User Impact**
This delays the end of long-running jobs as they lose their progress. Some jobs may never complete if they take longer than a week as the dependency updates will cause another deploy.

In some cases, a job restart might be the source of errors as some jobs (open version, close version, create virtual object, purge objects, register druids) change druid states as they run and should not be re-run. 

**Expected behavior**
A bulk action should not restart unless there is an error that causes a restart.

**Additional context**
Bulk action 12635 is a reindex of over 400,000 druids that seems to be running fine but has restarted on two Mondays in a row.

**Comment by peetucket** [comment]
Here is the command called by capistrano when deploying that appears to restart sidekiq.  Looking into what the implications of disabling this would be and how to do it.

```
01:52 sidekiq_systemd:start
      01 sudo systemctl start sidekiq-* --all
    ✔ 01 lyberadmin@argo-stage-a.stanford.edu 0.224s
    ✔ 01 lyberadmin@argo-stage-b.stanford.edu 0.285s
```

**Comment by peetucket** [comment]
One potential implication of not restarting sidekiq on deploy is that that you may have cached out of date code in the sidekiq process.  It's not clear to me where that restart is coming from in capistrano, as we don't explicitly call or use the `capistrano-sidekiq` gem.

**Comment by peetucket** [comment]
Relevant documentation in the sidekiq wiki: https://github.com/mperham/sidekiq/wiki/Deployment

Basically, you can tell sidekiq to wait a bit for jobs to finish before stopping and starting, but it looks like this is typically a short amount of time (in seconds) and not to deal with jobs that take hours.

**Comment by peetucket** [comment]
More relevant documentation about alternate approaches to restarts and long-running jobs: https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts

Appears to be a Sidekiq Enterprise feature that allows you to simultaneously run old an version of the sidekiq process (for any long running jobs only) while starting up new processes with the new code

**Comment by mjgiarlo** [comment]
I'm not sure we can accommodate this with Sidekiq, unless we upgrade to Sidekiq Enterprise. The price of that service depends on how many "packs" we buy. I assume, though I am not certain, that if we only use Sidekiq Enterprise for Argo prod that we'd need one "pack" per box (so, two "packs"). That would come to $209 * 2/mth, so about $5K/yr.

An alternative would be to replace Sidekiq with resque-pool, which 😒

**Comment by andrewjbtw** [comment]
Thanks for looking into this further. Hannah, Vivian and I discussed this in our bug review and agree this should go into maintenance rather than being in the FR queue. I think if we don't go to a paid sidekiq, another approach could be to have bulk actions pick up where they left off instead of starting over completely. But I would expect that's not trivial work, plus different bulk actions operate differently.

**Comment by mjgiarlo** [comment]
I believe we now have a pattern for allowing sidekiq jobs to finish in deploys. Should we consider this for Argo? cc: @jmartin-sul @justinlittman @andrewjbtw

**Comment by mjgiarlo** [comment]
@jmartin-sul Super! Thanks for doing the legwork there. 😵 Do you think we can close this, @andrewjbtw ?

**Comment by andrewjbtw** [comment]
Yes, I meant to come back to close this. Now I will.
