### ISSUE TITLE
Display objects' rights on Argo Record and Search Results page

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#233]
Display the object's overall rights -- the basic world/stanford/citation/dark distinction that constitutes the "Access Rights" facet value -- both on the search results page (ie the list of objects that appear after searching/faceting) and on the record detail page.  Show it in the first column of data, above Status.

**Comment by andrewjbtw** [comment]
I would put a higher priority on displaying the rights on the Argo item page, as currently you have to look at the rights metadata XML when you're on the page.
