### ISSUE TITLE
Add No Workflow to Empty Fields facet

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#234]
When there are no workflow rows returns for an item at all. This will help identify anomalies and orphaned entries, especially in older data.

**Comment by andrewjbtw** [comment]
When there are no workflows, an item shows "Unknown Status" in the processing status facet. This was indeed helpful in remediation for the Fedora migration. Unless I'm wrong and there are cases where a druid can have no workflows and yet not appear under "Unknown Status", having a separate "No workflows" facet value would be redundant at this point.
