### ISSUE TITLE
Decouple from default collections

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2354]
When a collection is created in argo, the APO for that collection is updated to make the new collection a “default collection” (`//administrativeMetadata/registration/collection`). These nodes are what governs what collections show up when registering items. 

See: https://github.com/sul-dlss/argo/blob/main/app/controllers/registrations_controller.rb#L119
https://github.com/sul-dlss/dor-services/blob/1743ea8c144467d0167c333d34cfb62b9d2eb7ec/lib/dor/datastreams/administrative_metadata_ds.rb#L119-L143
https://github.com/sul-dlss/argo/blob/main/app/controllers/collections_controller.rb#L25

**Comment by peetucket** [comment]
Unclear if this will be covered in already existing tickets.

**Comment by jcoyne** [comment]
I think this is already done.
