### ISSUE TITLE
Add ability to create agreement objects

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2357]
To support accessioning agreement objects (see https://github.com/sul-dlss/pre-assembly/issues/743 ) we need to be able to register them. This ticket is to add the ability to register agreements. Currently, we can only register items or APOs. To register agreements we will need either a new form or a modification to the existing item registration form.

Being able to register agreements will help us detach the agreement creation process from Hydrus, which it currently uses: https://consul.stanford.edu/display/SDRA/Instructions+for+Creating+Agreements+Objects

This issue can be closed when both of these are done:
- agreements can be registered
- agreements can be uploaded (which "needs" rails 6 upgrade)

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/114784191-c17ab400-9d2f-11eb-92ce-61c0caa057b0.png)

**Comment by andrewjbtw** [comment]
In the background, the Agreement object should always get the following:

APO: https://argo.stanford.edu/view/druid:hv992ry2431 [Internal Systems Objects]
Rights: dark
Content type: file

If it's a step too far, we can go without the file upload and rely on https://github.com/sul-dlss/pre-assembly/issues/743 to supply the files.

The combination of this ticket and preassembly one will allow us to avoid Hydrus/H2 entirely when creating agreements.
