### ISSUE TITLE
Keyword searches that return no results direct to system status page

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2359]
**Describe the bug**
When searching in Argo, a keyword search that returns no results leads users to the system status page. This was first noticed when searching for druids that do not (or no longer) exist.

See for example a search for nw696zy4908 (no link because I'm not getting a URL out of it).

Searches that don't work seem to be associated with this error:
https://app.honeybadger.io/projects/49894/faults/73523532

**User Impact**
Instead of seeing no results, users see an error and are taken off of the Argo site.

**To Reproduce**
1. Search Argo for a term that doesn't exist

**Expected behavior**
If there are no results, the search should indicate that.

**Additional context**
Facets that return no results are working. And the problem may be intermittent. But it's consistent right now as I write this ticket.

**Comment by andrewjbtw** [comment]
Note that this applies to strings other than druid strings. I think it was first noticed with druids because they're more likely to be unique. But you can get the same error searching:

- nonexistentterm
- supercalifragilistic

**Comment by cbeer** [comment]
I suspect this was fixed up stream with https://github.com/projectblacklight/blacklight/pull/2416.
