### ISSUE TITLE
Users who should have edit permissions are only getting read-only permissions

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2366]
**Describe the bug**
Multiple users have reported that they cannot edit the datastreams for objects that they previously have been able to edit. Their workgroup and APO permissions have not changed, so the change seems to be in the background. 

This seems to affect users who are not members of any of the SDR administrative workgroups. There's a large set of users who are in only two workgroups:

1. `sdr:argo-access` (for the Argo front page)
2. A specific departmental or project workgroup such as `sdr:law-staff`

Previously, SDR users with these departmental workgroups could edit objects in APOs that authorize those workgroups. They are no longer able to make changes. 

The activities that users have reported being blocked from completing are:

1. bulk MODS uploads
2. datastream editing from Argo

**User Impact**
These users often only edit object metadata. They are blocked from doing their work.

**To Reproduce**
1. Go to Argo
2. Click on impersonate
3. Impersonate these two groups together: `workgroup:sdr:argo-access,workgroup:sdr:law-staff`
4. Make sure that Argo now shows the impersonation is active (indicated in the red header bar at the top)
5. Go to https://argo.stanford.edu/view/druid:bk541cp6048
6. Open the descMetadata datastream
7. See that it has no edit button
8. Go to the APO for that object https://argo.stanford.edu/view/druid:cf857tk2388
9. Click on its role metadata
10. See that sdr:law-staff is authorized in the APO and should be able to edit

**Expected behavior**
Users in workgroups authorized via APO should be able to edit datastreams for objects in that APO (with the exception of the datastreams that no one can edit in Argo).

**Additional context**
This seems to have stopped working for users in January 2021. In at least one case, I can see that the same user was able to edit the same objects in December 2020.

**Comment by jcoyne** [comment]
This looks to me like the APO may be indexed incorrectly.

The argo code is looking for fields like `apo_role_group_manager_ssim, apo_role_person_manager_ssim`. but the document itself has these fields: `"apo_role_group_dor-apo-manager_ssim", "apo_role_dor-apo-manager_ssim"`

**Comment by jcoyne** [comment]
This looks like it should work fine:
```

druid = 'druid:bk541cp6048'
cocina = Dor::Services::Client.object(druid).find
user = User.new
user.set_groups_to_impersonate(['workgroup:sdr:argo-access','workgroup:sdr:law-staff'])

ability = Ability.new(user)
ability.can? :manage_item, cocina
=> true
```
