### ISSUE TITLE
Ability to reset APO governance

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#237]
There are instances where we will need to reassign objects belonging to one APO to another APO (current use case is that there is an APO for Stanford Historical Photos Oversized but we want all of these objects to moved to the Stanford Historical Photos general APO). Need ... 
- a blue button for an individual item to set or reset the APO (will add if missing, else replace) 
- a bulk update functionality to reassign APO for a group of druids

People who should have this capability:
- SDR admins
- or someone with the manager role in target APO

**Comment by blalbrit** [comment]
Currently available as an item-level blue button and as a bulk action job.
