### ISSUE TITLE
media item updates made via Cocina API are breaking online streaming

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2373]
**Describe the bug**
When a media item is updated via Argo and the update runs through the Cocina API, the contentMetadata XML is modified in a way that breaks online streaming.

Specifically, an attribute of "thumb"="yes" is being added to the resource. This attribute appears to cause the embed viewer to look for a thumbnail file, which then fails.

Example: https://argo.stanford.edu/view/druid:bb690dq2040

The contentMetadata previously started with:

```xml
<contentMetadata objectId="bb690dq2040" type="media">
  <resource sequence="1" id="bb690dq2040_1" type="video">
    <label>In black and white. Episode 3: Toni Morrison</label>
```
After a change to the collection, the contentMetadata was rewritten to start with:

```xml
<contentMetadata objectId="druid:bb690dq2040" type="media">
  <resource id="bb690dq2040_1" sequence="1" type="video" thumb="yes">
    <label>In black and white. Episode 3: Toni Morrison</label>
```
The thumb="yes" seems to have been added via the Cocina roundtrip. This seems to direct the viewer to look for a thumbnail file that doesn't exist, resulting in a blank player.

**User Impact**
Users can't stream items after they have been modified this way. Argo users find that updates they make for other reasons  (such as adding a collection or a catkey) inadvertently break online streaming.

**Expected behavior**
Changes made in Argo that don't involve contentMetadata should not modify contentMetdata.

**Additional context**
We will need to find every media object that has this problem. It could be difficult to track down.

**Comment by jcoyne** [comment]
@andrewjbtw Isn't the jp2 file a thumbnail?  

```
  <resource id="bb690dq2040_1" sequence="1" type="video" thumb="yes">
    <label>In black and white. Episode 3: Toni Morrison</label>
    <file id="bb690dq2040_In_Black_and_White_3_-_Toni_Morrison_pm.mp4" mimetype="video/mp4" size="1548805125" publish="no" shelve="no" preserve="yes">
      <checksum type="sha1">3e2743518db44ad9a602c606081559b2c0c0bf7c</checksum>
      <checksum type="md5">783a89b13648b70d60d8b1db5c2a8181</checksum>
    </file>
    <file id="bb690dq2040_In_Black_and_White_3_-_Toni_Morrison_sl.mp4" mimetype="video/mp4" size="208585288" publish="yes" shelve="yes" preserve="yes">
      <checksum type="sha1">047cbe2cc53bc72b3a4c6f92d0518ebc962be752</checksum>
      <checksum type="md5">00861f83d92447f1dbfcaab362847ebf</checksum>
    </file>
    <file id="bb690dq2040_In_Black_and_White_3_-_Toni_Morrison_thumb.jp2" mimetype="image/jp2" size="176240" publish="yes" shelve="yes" preserve="yes">
      <checksum type="sha1">4c4b6b8d23a5d47d5ed5b35de73e5caad235dc2f</checksum>
      <checksum type="md5">2f8f3d24d46f6d8f79f7af957079a28a</checksum>
      <imageData height="480" width="640"/>
    </file>
  </resource>
  ```

**Comment by andrewjbtw** [comment]
I've made four videos on stage with different contentMetadata settings:

1. https://sul-purl-stage.stanford.edu/hc109wn2912 (follows current preassembly practice)

Result: thumbnail shows over video player on first page load. This is the expected behavior.

2. https://sul-purl-stage.stanford.edu/dy959mr6442 (image resource is separate, no thumb attribute)

Result: video player shows a frame, but not the thumbnail. Thumbnail shows if you click the three dots and look.

3. https://sul-purl-stage.stanford.edu/yt567fs7464 (image resource is separate and has thumb="yes")

Result: video player shows a frame, but not the thumbnail. The thumbnail is not accessible.

4. https://sul-purl-stage.stanford.edu/xn130pw5787 (video resource has thumb="yes", image resource is separate)

Result: viewer is blank.

Only the first option, the item that has the contentMetadata that preassembly creates via the normal media accessioning process shows the video in the player as expected: with the thumbnail frame over the video itself.

This leads me to believe that the thumb attribute should not be used for media items. I think the intent of the attribute was to make it possible to designate a specific page from a paged or multi-image object as the thumbnail for cases where a thumbnail would be more interesting than the item's cover.
