### ISSUE TITLE
Add blue button and bulk update for shelving

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#238]
Calls shelving service to shelve, or reshelve/unshelve as appropriate. Mainly for admin cleanup. This isn't as easy as other tasks like Publish since shelving requires content files for stacks to be in the workspace. A limited capability may be useful, but this might be coupled with a larger facility to check out files from SDR, rederive derivatives, etc.

**Comment by blalbrit** [comment]
In our current environment, this is rarely exercised - though point taken re: need for rederiving derivatives, prospectively.

Backlogging for now, though keeping for history.

**Comment by andrewjbtw** [comment]
Closing in favor of https://github.com/sul-dlss/common-accessioning/issues/733 and https://github.com/sul-dlss/argo/issues/2447
