### ISSUE TITLE
When a collection is moved to a new APO, add the collection to the default collections of the new APO and remove it from the defaults of the old collection APO

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2380]
Argo supports moving a collection object from one APO to another through the blue button and bulk job interfaces. When moving a collection from APO A to APO Z:

- [ ] the collection druid should be removed as a default collection from the administrativeMetadata datastream of APO A  
- [ ] the collection druid should be added as a default collection to the administrativeMetadata datastream of APO Z 

The administrativeMetadata is what is used to populate the list of collections for each APO in the dropdown menu on the item registration page.

Currently, when moving a collection from APO A to APO Z, the administrativeMetadata is left unchanged for both APOs. This leads users to edit the datastreams manually to make these changes. If the changes happen automatically, there would be no need for these edits.

related to https://github.com/sul-dlss/argo/issues/2354

**Comment by andrewjbtw** [comment]
To give some background (this is also going to live on a consul page in more detail):

**What does it mean for an object to be "under" or "governed by" an APO?**

All SDR items and collections must be governed by an APO, which basically means that they are governed by the terms and conditions as expressed in their APO and its related agreement (an actual legal document that is ultimately what's doing the governing). By policy, nothing can be accessioned into SDR without being governed by an APO.

For both items and collection objects, the relationship to the APO is stored in the RELS-EXT (in the Fedora model).

Example collection: https://argo-stage.stanford.edu/view/druid:sm682bf6616 This collection object has the following relationship in its RELS-EXT:

```xml
    <hydra:isGovernedBy rdf:resource="info:fedora/druid:xb798bb0947"/>
```

This relationship is also shown in the Argo UI:

<img width="737" alt="apo-display-for-persons" src="https://user-images.githubusercontent.com/8975583/111391571-1fa17200-8672-11eb-99bd-79b7aafafdcb.png">

**What's special about collection objects?**

The APO object stores a list of collections that are governed by that APO. This differs from what happens with items, where the item stores the APO relationship but the APO does not store the list of items under that APO.

Example: the APO druid referenced in the collection object above is here: https://argo-stage.stanford.edu/view/druid:xb798bb0947 

In that APO, the list of collections it governs is stored in the administrativeMetadata datastream, under the `<registration>` element:

<img width="377" alt="apo-in-admin-metadata" src="https://user-images.githubusercontent.com/8975583/111391676-57a8b500-8672-11eb-88e1-6bb95a58c9e7.png">

The purpose of storing the collection druid in the administrativeMetadata seems to be to populate the dropdown menu in the Argo registration form that appears when you select that APO for registration:

<img width="719" alt="apo-in-registration-form" src="https://user-images.githubusercontent.com/8975583/111392011-f9300680-8672-11eb-8828-1327eaa96a62.png">

If the collection druid is not in the administrativeMetadata for that APO, it does not appear on that menu.

**How is the collection <--> APO relationship created?**

When creating a new collection:

1. The RELS-EXT relationship is created in the collection object
2. The new collection druid is added to the administrativeMetadata of the APO

**What happens when you move a collection object to a different APO?**

This is where we run into the problem that this issue is supposed to address. There is a blue button/bulk job action that allows users to change the governing APO for collections or items. This action shows a dropdown list of APOs and you choose the one you want the object to have:

<img width="502" alt="set-governing-APO" src="https://user-images.githubusercontent.com/8975583/111394286-b0c71780-8677-11eb-9841-609d92e428ee.png">

When changing the APO this way:

1. The collection druid RELS-EXT is updated to refer to the selected APO
2. The previous APO administrativeMetadata is not updated to remove the collection from its list
3. The selected APO administrativeMetadata is not updated to add the collection to its list

The result is that the collection object shows that it is now governed by the newly selected APO, but the newly selected APO does not store any data about the collection. That means that when you go to the Argo registration form:

- you will still see the collection listed in the dropdown menu for the APO it started with
- you will not see the collection listed in the dropdown menu for the APO it is now under

The longstanding workaround for this problem has been for users to edit the administrativeMetadata in the APO objects so that the data matches the change of APO. To make it so that users don't need to do that anymore, the system should update the administrativeMetadata automatically in each APO (the previous APO + the newly selected APO) when an APO is changed.

**Is there anything else to be aware of?**

The Edit APO form allows you to manage the APO's "default collections". This means that you can choose a collection from a dropdown list and have it added as a new "default" collection for that APO, meaning that it is added to the `<registration>' list in the administrativeMetadata. You can also remove existing default collections.

<img width="917" alt="add-default-collection" src="https://user-images.githubusercontent.com/8975583/111395097-4adb8f80-8679-11eb-98c4-5d429b32ec17.png">

When you use the Edit APO form to manage the default collections:

- the APO administrativeMetadata is updated to add or remove a collection from the list
- the collection RELS-EXT is not updated to reflect any change in APO

The result is that you could add a collection as "default" to multiple APOs, even though only one of those APOs actually governs that collection. I'm not sure how to handle this situation.

**Is there an alternative way out of this complexity**

The administrativeMetadata list of collections just seems to be populating the Argo dropdown menus. Maybe there's another way we can achieve the same goal, which is to have those menus list the collections that are governed under each APO?

**Comment by ndushay** [comment]
If this is confusing, ask JCoyne for help.

**Comment by andrewjbtw** [comment]
Proposal: build the registration menu dropdown off of a query for which collections are within each APO. That should mean that when a collection is moved from one APO to another, the indexing will keep the menus in sync with the changes.

**Comment by ndushay** [comment]
This is showing in the review/qa column.   @aaron-collier is this a priority?  @jcoyne is this in progress?

**Comment by jcoyne** [comment]
@ndushay it's awaiting review by Andrew.

**Comment by andrewjbtw** [comment]
Closing as not implementable with our current data organization. Left a comment on the related PR: https://github.com/sul-dlss/argo/pull/2713#issuecomment-1240137573
