### ISSUE TITLE
Do not allow publish on "registered" objects

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2384]
**Describe the bug**
It turns out it's possible to publish registered objects. This can happen accidentally via 

- bulk action publish
- bulk action SearchWorks release
- clicking on the publish blue button

**User Impact**
Registered items are in-progress by definition and should not be considered ready for a public purl. There's no easy way to remove the purl if it's published while an object is registered, as we don't have an "unpublish" action. Unpublishing usually only happens if the accessionWF publish step is run. To unpublish you essentially need to set the object rights to dark and run accessioning, which is not a good option for an item that is still only registered.

**Expected behavior**
Only items that have been accessioned should be publishable.

**Additional context**
I've made the mistake of accidentally publishing registered objects myself.

**Comment by jcoyne** [comment]
Should this be in dor-services-app on the publish API?

**Comment by peetucket** [comment]
The code suggests we don't enable the Republish button on an item page unless the item has previously been published: https://github.com/sul-dlss/argo/blob/main/app/presenters/buttons_presenter.rb#L135-L142  It seems like this should prevent this scenario from occurring.  I need to investigate further.

**Comment by peetucket** [comment]
The blue button seems to be disabled correctly in a couple examples:

1. https://argo.stanford.edu/view/druid:bb034wm3873  -- Registered object, blue button disabled
2. https://argo.stanford.edu/view/druid:bc120zt0148 -- Accessioned object, blue button enabled

The check used to enable/disable the blue button calls the Workflow service and looks for the "published" workcycle.  The call succeeds in these two cases:

```
@workflow_client ||= WorkflowClientFactory.build;
[4] pry(main)> @workflow_client.lifecycle(druid: 'druid:bc120zt0148', milestone_name: 'published')
=> 2020-08-04 00:19:13 +0000
[5] pry(main)> @workflow_client.lifecycle(druid: 'druid:bb034wm3873', milestone_name: 'published')  
=> nil
```

It may be possible that the published lifecycle exists in objects that shouldn't have it, but that would be suprising.  Are there example druids where the blue "Republish" button is enabled but shouldn't be?

I'll look at the bulk actions next to see if we need a guard there too.

**Comment by peetucket** [comment]
It looks like we will want to guard in the bulk jobs against republishing/releasing objects that shouldn't be:

https://github.com/sul-dlss/argo/blob/main/app/jobs/republish_job.rb#L24-L31

and 

https://github.com/sul-dlss/argo/blob/main/app/jobs/release_object_job.rb#L34-L65

**Comment by peetucket** [comment]
As noted in #2477 (now closed) we will guard against this in dor-services-app, either here https://github.com/sul-dlss/dor-services-app/blob/main/app/jobs/publish_job.rb#L12 or here https://github.com/sul-dlss/dor-services-app/blob/main/app/controllers/objects_controller.rb#L90

**Comment by peetucket** [comment]
Actually, hold on -- if we guard in dor-services-app by simply checking if the object has been published/accessioned before, we would block publishing of new objects for the first time (i.e. calls made by accessionWF) since they all use the same DSA endpoint.  What we really want to guard against is user initiated calls from Argo, via the blue button (should already be done) and the bulk actions, right?  So in Argo?

**Comment by peetucket** [comment]
ok - re-opened Argo PR and added a couple tests
