### ISSUE TITLE
Descriptive Metadata Roundtripping

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2385]

**Comment by jcoyne** [comment]
Can  you explain what this means?  Because we use ActiveFedora, there is no way to do a non-destructive test of this like we did with descMetadata, where we mostly avoid using ActiveFedora.

**Comment by aaron-collier** [comment]
Nothing as of yet, this is a zenhub epic at this point as there are roundtripping concerns. We may end up closing this, or moving it to a different repo, but for now it will just be used to capture related tickets.
