### ISSUE TITLE
Refactor descmetadata_download_job to decouple from fedora 3

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2396]
- Replace call to fedora 3: https://github.com/sul-dlss/argo/blob/main/app/jobs/descmetadata_download_job.rb#L70
- Retrieve source descriptive metadata (https://github.com/sul-dlss/argo/blob/main/app/jobs/descmetadata_download_job.rb#L47) from dor-services-app (blocked by: https://github.com/sul-dlss/dor-services-app/issues/1885)

**Comment by jcoyne** [comment]
@aaron-collier the Dor::Services::Client.object(druid).metadata.descriptive service returns the public descriptive metadata which is not the same as the source descriptive metadata.
