### ISSUE TITLE
Enable users to choose a license for objects on a per object basis

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2403]
Users should be able to choose a license for objects on a per object basis.

Currently, the only way a user can set a license is to

- Apply the APO defaults
- Edit the rightsMetadata xml directly

See https://github.com/sul-dlss/argo/issues/2404 for the corresponding bulk action

**Comment by ndushay** [comment]
This requires a new design -- license is not displayed in the Argo page.

**Comment by jcoyne** [comment]
superseded by #2866
