### ISSUE TITLE
Enable users to set the license, copyright statement, and use and reproduction statement via a bulk action

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2404]
Users should be able to choose a license, set the copyright statement, and set the use and reproduction statement for objects via a bulk action.

Currently, the only way a user can set a license is to

- Apply the APO defaults
- Edit the rightsMetadata xml directly

![image.png](https://images.zenhubusercontent.com/5cd34fcc78dbc64ff177a010/1635bc9f-ee8e-40f4-8b29-0f4b2e5d96eb)

**Comment by mjgiarlo** [comment]
@andrewjbtw @aaron-collier This is marked as ready but I have questions:

* What licenses should be made available?
* Should they vary based on the object (type, collection, etc.)? 
* In what order should they be presented? 
* Is this work to be done in Argo or is upstream work (DSA, DSC, Cocina) required?

**Comment by andrewjbtw** [comment]
Taking the first three questions in order:

- There's a list of licenses in a menu in the Create APO and Edit APO forms. I think this is the only place in Argo where people can set licenses (besides editing XML). This bulk action should present the same list:
<img width="917" alt="Screen Shot 2021-03-19 at 12 01 19 PM" src="https://user-images.githubusercontent.com/8975583/111830289-f9b2e200-88aa-11eb-9942-f16109c95717.png">

- Licenses will apply only to items and collection objects. But all objects should work from the same list. The end goal here is to enable people to give specific objects licenses that differ from what they got from the APO. Currently, you have to edit the rightsMetadata datastream to do this.
- The order should be the same as the one in the menu on the APO forms (both menus should be the same)

The fourth question is more difficult to answer. There has been upstream work around mapping the license properties to Cocina because we weren't doing that before. I'm not sure where that stands.

More specific to the license menus, @peetucket picked up my ticket for making the menu consistent with what we show in H2 (see #2405) That has revealed some more questions about how we map license data to be consistent across systems.

As I understand it, the current state of things means this ticket is blocked if:

- we want to have it show an updated license menu (to match H2)
- we haven't modeled licenses yet so that they can be set via DSA

It's not blocked if:

- we carry over the menu as it currently exists and update that menu it separately
- setting the license can be done in a decoupled from Fedora way

**Comment by andrewjbtw** [comment]
In terms of design, this can be modeled off of the existing "Set governing APO" form, which has a dropdown menu and a box for a list of druids:
<img width="1160" alt="Screen Shot 2021-03-19 at 12 18 07 PM" src="https://user-images.githubusercontent.com/8975583/111831973-6038ff80-88ad-11eb-8e1c-d35fd2c0a600.png">

In that screenshot

- replace "New governing APO" with "Select license"
- replace the menu of APOs with the menu of licenses

**Comment by aaron-collier** [comment]
@mjgiarlo I don't think any upstream changes should be required as we should be able to set these values through the cocina update, but if you find that to not be true, I'd be happy to take a look.

**Comment by mjgiarlo** [comment]
@aaron-collier @andrewjbtw thanks! I switched to the Cocina JSON bug but I may pick this back up today.

**Comment by jcoyne** [comment]
Would we want to couple the UI of this with #2445 & #2446?

**Comment by justinlittman** [comment]
Clarification from standup: The UI in the description from this ticket represents the latest, which couples this ticket with #2445 and #2446.
