### ISSUE TITLE
Provide user interface to unpublish a Purl

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2411]
We have a "publish" action in Argo but not an unpublish action. The only way to unpublish seems to be to set rights to "dark" and then run the publish action, which is both counterintuitive and potentially risky because "dark" rights carry additional settings changes.

This is a problem when things are published accidentally as it's difficult to undo that action. 

We could mitigate this problem by preventing publish in circumstances where it clearly should be prohibited, such as when an item is registered (see #2384).

**Comment by astridu** [comment]
Change the 'Republish' red action button to a drop down that displays Republish and Unpublish options user can select.

![image](https://user-images.githubusercontent.com/42216982/112374897-e1263b80-8c9f-11eb-9943-5fce6ce0cfdc.png)

**Comment by jcoyne** [comment]
@andrewjbtw I'm not aware that purl has support for unpublishing a purl other than the workaround you stated.  We may need to work with the access team to develop an API for this.

**Comment by andrewjbtw** [comment]
The unpublish option to "Manage Purl" now covers this.
