### ISSUE TITLE
Decouple the catalog controller from fedora 3

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2415]
- [ ] Remove the dependency on F3 for authorizing view_metadata in the catalog controller.

**Comment by jcoyne** [comment]
Cocina doesn't keep a version history, so I'm not sure how you'd get that from cocina.

**Comment by aaron-collier** [comment]
@jcoyne thank you, I've removed that item and will ticket the versioning discussion separately.

**Comment by jcoyne** [comment]
@aaron-collier I think this ticket as written is blocked by that yet to be ticketed work around the version log.
