### ISSUE TITLE
Refactor collection_form to decouple from fedora 3

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2421]
Once a collection is created, retrieve the metadata from cocina instead of fedora 3 (Dor.find)

In order to decouple the [collection_form](https://github.com/sul-dlss/argo/blob/main/app/forms/collection_form.rb#L35), the abstract must be able to be written to cocina (stored as a descriptive value in Note with  type: `summary`, label: `Abstract`)

**Comment by jcoyne** [comment]
CollectionForm writes to  the abstract, so this is blocked until dor-services-app accepts updates to descMetadata

**Comment by aaron-collier** [comment]
@jcoyne now that we're writing descMetadata via the legacy API, I believe this is unblocked. If not, please re-tag.
