### ISSUE TITLE
Remove fedora 3 dependency from datastreams_controller

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2437]
https://github.com/sul-dlss/argo/blob/main/app/controllers/datastreams_controller.rb#L104

**Comment by aaron-collier** [comment]
Now that we have an API for requesting the datastreams through dor-services-app, this is unblocked.

**Comment by justinlittman** [comment]
@aaron-collier @andrewjbtw Does include getting rid of the ability to directly update datastreams that are not supported by the legacy endpoint?

https://github.com/sul-dlss/argo/blob/main/app/controllers/datastreams_controller.rb#L106-L114

The legacy endpoint supports:
```
datastream_names = {
      administrative: 'administrativeMetadata',
      content: 'contentMetadata',
      descriptive: 'descMetadata',
      geo: 'geoMetadata',
      identity: 'identityMetadata',
      provenance: 'provenanceMetadata',
      relationships: 'RELS-EXT',
      rights: 'rightsMetadata',
      technical: 'technicalMetadata',
      version: 'versionMetadata'
    }
```

**Comment by andrewjbtw** [comment]
Are those the same datastreams that show the edit button currently? We limited editing earlier, so many datastreams don't allow Argo-based updating already.

**Comment by justinlittman** [comment]
Here are the currently editable:
```
editable_datastreams:
  - RELS-EXT
  - descMetadata
  - identityMetadata
  - contentMetadata
  - versionMetadata
  - rightsMetadata
  - administrativeMetadata
```

**Comment by justinlittman** [comment]
So it seems like we can get rid of the ability to directly update datastreams that are not supported by the legacy endpoint.

**Comment by andrewjbtw** [comment]
I should also ask since I'm not sure of the full scope of this change: does this affect reading from datastreams that have been updated in Fedora outside of any Argo or system actions? 

For example, if I create an embargoMetadata datastream by sending a curl request to the Fedora API, will that still get picked up? I create/modify some datastreams directly by going straight to Fedora.

**Comment by justinlittman** [comment]
This will not affect reading from datastreams that have been updated in Fedora outside of Argo or system actions.
