### ISSUE TITLE
Enable users to edit the use and reproduction statement on a per object basis

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2443]
Users should be edit the use and reproduction statement for objects on a per object basis.

Currently, the only way a user can edit the use and reproduction statement is to

- Apply the APO defaults
- Edit the rightsMetadata xml directly

**Comment by andrewjbtw** [comment]
Requires moving to the new Argo show page design.

**Comment by jcoyne** [comment]
Superseded by #2867
