### ISSUE TITLE
Enable users to edit the copyright statement on a per object basis

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2444]
Users should be edit the copyright statement for objects on a per object basis.

Currently, the only way a user can edit the copyright statement is to

- Apply the APO defaults
- Edit the rightsMetadata xml directly

**Comment by andrewjbtw** [comment]
Requires moving to the new Argo show page design.

**Comment by jcoyne** [comment]
Superseded by #2864
