### ISSUE TITLE
Enable users to submit use and reproduction statements for a batch of objects via a bulk action

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2445]
Bulk action to do https://github.com/sul-dlss/argo/issues/2443

**Comment by jcoyne** [comment]
Do we have UI design for this?

**Comment by aaron-collier** [comment]
Now that I think about it, i don't think these actions can be coupled unless the changes are always coupled.

**Comment by jcoyne** [comment]
@aaron-collier why is that?
