### ISSUE TITLE
Remediate 4 Hydrus items that are not cocina compliant

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2458]
https://argo.stanford.edu/catalog?f%5Bdata_quality_ssim%5D%5B%5D=Cocina+conversion+failed&f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+Hydrus

- [ ] No object type: https://argo.stanford.edu/view/druid:zk639fq8654
- [ ] Collection https://argo.stanford.edu/view/druid:mq400hj7272
- [ ] Collection https://argo.stanford.edu/view/druid:mv453cq5726
- [ ] Collection https://argo.stanford.edu/view/druid:zk639fq8654

**Comment by peetucket** [comment]
I cannot find any evidence of these objects in Fedora, either via argo (gives 404s and the facet search results no results) or directly on the command line in dor-services-app.  Have they been purged from Hydrus?

on dor-services-app-prod:
```
2.7.0 :001 > i=Dor.find('druid:zk639fq8654')
Traceback (most recent call last):
        1: from (irb):1
ActiveFedora::ObjectNotFoundError (Unable to find 'druid:zk639fq8654' in fedora. See logger for details.)
2.7.0 :002 > i=Dor.find('druid:mq400hj7272')
Traceback (most recent call last):
        2: from (irb):1
        1: from (irb):2:in `rescue in irb_binding'
ActiveFedora::ObjectNotFoundError (Unable to find 'druid:mq400hj7272' in fedora. See logger for details.)
2.7.0 :003 >
```

**Comment by arcadiafalcone** [comment]
I purged these as part of data remediation. They had no content and no descriptive metadata.

**Comment by peetucket** [comment]
Thanks.  I'll close this then.
