### ISSUE TITLE
Remediate 1 University Archives item that is not cocina compliant

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2459]
https://argo.stanford.edu/catalog?f%5Bdata_quality_ssim%5D%5B%5D=Cocina+conversion+failed&f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+University+Archives+Scanning

It appears that the immediate problem is it has no descMetadata, but it also doesn't have any workflows: https://argo.stanford.edu/view/druid:hh126cq9832

**Comment by peetucket** [comment]
1. Added a MODs title to descMetadata datastream on the rails console and saved the object.
2. Added an accessionWF workflow in argo.

Note, this object has no contentMetadata and thus no content.

**Comment by peetucket** [comment]
It is now successfully accessioned and has a PURL.  But there is nothing there.

**Comment by andrewjbtw** [comment]
I added a contentMetadata since this was triggering an error for lack of content type. But it is still an empty object.
