### ISSUE TITLE
Remediate 6 ETDs

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2461]
These are all circa 2010 and have the following triple in RELS-EXT:
```xml
    <fedora:conformsTo rdf:resource="info:fedora/afmodel:Etd"/>
```
 https://argo.stanford.edu/catalog?utf8=%E2%9C%93&f%5Bdata_quality_ssim%5D%5B%5D=Cocina+conversion+failed&f%5Bdata_quality_ssim%5D%5B%5D=missing+sourceId&search_field=text&q=Temporary+Title

**Comment by peetucket** [comment]
These look quite purgeable

**Comment by andrewjbtw** [comment]
This was taken care of when we cleared out old "parts" objects. The search in the ticket no longer returns any items, so I'm closing it.
