### ISSUE TITLE
Does anyone know why we do this around_filter in DorController?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#249]
https://github.com/sul-dlss/argo/blob/develop/app/controllers/dor_controller.rb#L16-L28

Seems like some of our config stuff may remove the need of this?

**Comment by jmartin-sul** [comment]
i'm not sure this is doing the same thing as the webauth fakery in the `config/environments/dor_development.rb` setup, though it does look similar at first glance.  maybe it does?  maybe it was an early version of that (left is as cruft)?  definitely warrants investigation.

**Comment by drh-stanford** [comment]
This was removed in 1a0d29c0e358dc7c6d3cc482ebb21f246d83e6e2
