### ISSUE TITLE
Decouple collections_controller from Fedora 3

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2496]
https://github.com/sul-dlss/argo/blob/ba9a94a1f24e302ad2472da7110afc3e7b2a1354/app/controllers/collections_controller.rb#L9

Retrieve the APO from dor-services-app instead of directly from fedora.

**Comment by jcoyne** [comment]
Also here: https://github.com/sul-dlss/argo/blob/ba9a94a1f24e302ad2472da7110afc3e7b2a1354/app/controllers/collections_controller.rb#L19
