### ISSUE TITLE
Add ability to set embargo in the interface

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2498]
https://github.com/sul-dlss/argo/blob/ba9a94a1f24e302ad2472da7110afc3e7b2a1354/app/controllers/items_controller.rb#L118

We can currently set the embargo through dor-services-app but we do not expose it through the UI.

**Comment by andrewjbtw** [comment]
I'm ok with backlogging this for the work cycle but it remains a request.

**Comment by andrewjbtw** [comment]
Sorry, I confused this with https://github.com/sul-dlss/argo/issues/2009
