### ISSUE TITLE
update Solr queries in other codebases

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#251]
applications which assumed the Solr schema used by Argo 2.x and dor-services 4.x will need to be updated to use the new (Argo 3.x/dor-services 5.x) Solr schema.  E.g.:
https://github.com/sul-dlss/robot-master/blob/master/bin/robot-download-workflows#L45

this is actually not an issue which should result in changes to the argo codebase (since the changes in question have already been made there).  but since argo was the driver for the changes, this seems like a fine place to start tracking how it affects other applications.

i can clean up and post the results of a survey i sent out a while back to see how other codebases interact with solr and use dor-services.

**Comment by drh-stanford** [comment]
- [ ] See https://github.com/sul-dlss/dor-services/issues/136

**Comment by jmartin-sul** [comment]
i think this is superseded by the issue @drh-stanford just linked, so i'm closing this one.
