### ISSUE TITLE
Combine result view options into a dropdown choice

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#252]
We have 4 views/layouts for the results page, shown as buttons  buttons -- [Results Display] [Report Display] [Discovery Report] [Workflow Grid View]. These take up a lot of real estate which is shared with the serahc breadcrumbs, forcing the latter to wrap early and awkwardly. 
Do something akin to the searchworks view navigation:

![screen shot 2015-11-23 at 4 36 32 pm](https://cloud.githubusercontent.com/assets/1824732/11354456/7881cef4-9200-11e5-943b-00715635957c.png)

Our views can be called

    - View
        - normal
        - standard report
        - discovery report
        - workflow grid

**Comment by mejackreed** [comment]
Closed by #261
