### ISSUE TITLE
Apostrophe in label breaks cocina rendering

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2531]
Given an object with a label like "it's a test"  the cocina-model won't open and there is this javascript error:

<img width="739" alt="Screen Shot 2021-03-19 at 3 33 08 PM" src="https://user-images.githubusercontent.com/92044/111839566-fcbccb00-88c8-11eb-8732-efdda5399454.png">

**Comment by andrewjbtw** [comment]
I guess that answers why I couldn't see the Cocina for that object in the meeting. I've been using the SDR-API to pull the JSON directly and never noticed the issue before.

**Comment by mjgiarlo** [comment]
I should have a fix ready soon.
