### ISSUE TITLE
Investigate connection related build issues in CI

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2533]
See:
https://app.circleci.com/pipelines/github/sul-dlss/argo/1075/workflows/024fb812-c3da-40db-b799-db311cf4bcf2/jobs/2420

These look like different build failures from our earlier flappy tests.

**Comment by jmartin-sul** [comment]
difference in test failures between two runs for #2532:
<img width="1152" alt="Screen Shot 2021-03-19 at 3 47 40 PM" src="https://user-images.githubusercontent.com/7741604/111849350-9df85100-88ca-11eb-8e82-ef2748642037.png">

first run:
* Set governing APO when modification is allowed is successful
* Item manage release creates a new bulk action
* Item manage release has a manage release button
* ModsulatorJob perform delivers remotely-converted data
* Create an apo creates and edits an apo

second:
* Item manage release has a manage release button
* Item manage release creates a new bulk action
* Create an apo creates and edits an apo
* ModsulatorJob perform delivers remotely-converted data
* Bulk jobs view on the form for creating a new bulk job selecting a file to upload and selecting one of the radio buttons enables the submit button
* Set governing APO when modification is allowed is successful

**Comment by jmartin-sul** [comment]
all tests runs for that branch:  https://app.circleci.com/pipelines/github/sul-dlss/argo?branch=escape-cocina-json%232531

**Comment by jcoyne** [comment]
It's because of this change: https://github.com/sul-dlss/dor-services-app/commit/ea6ce21165c38bbd180357dc830ee9a839c7614b#diff-068532b2fac6f8a4ba8ed02d1dc6a88df1857b8bbe45ae5e5317ca239dcb1359R27  We can add a loop so that it waits for solr to be up before trying to write to it.

**Comment by jcoyne** [comment]
will probably be fixed by https://github.com/sul-dlss/dor-services-app/pull/2558

**Comment by jcoyne** [comment]
Seems to be fixed.
