### ISSUE TITLE
use "book (ltr)" and "book (rtl)" in the Argo "set content type" menus

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2534]
This is the last bit of work remaining from https://github.com/sul-dlss/argo/issues/2427

In the Argo registration form and in the Preassembly app, we've decided to include book reading order in the content type menus even though reading order is a subset of the "book" content type.

In Argo the content type menu still shows the generic "book", so it isn't possible to switch the reading direction of an existing book from within Argo itself without editing the datastream.

<img width="1160" alt="Screen Shot 2021-03-19 at 4 54 57 PM" src="https://user-images.githubusercontent.com/8975583/111852355-dc463e00-88d3-11eb-9789-d1ef800d9c10.png">

We should add "book (ltr)" and "book (rtl)" to this menu for now. Future interface improvements could give us a way to select reading order without treating it like a content type, but this strategy will work for our current system.

**Comment by jcoyne** [comment]
the reading direction is a totally different property than the content type and putting it in this menu would actually be much more challenging than creating a separate control for reading direction.  I'd recommend just proceeding for the correct UX here rather than adding a lot of complexity for something we don't ultimately want.

**Comment by andrewjbtw** [comment]
It's already in the other menus and will be deployed next week that way.

**Comment by jcoyne** [comment]
Yes, but those are for registration, not update, so it was a bit simpler. It used to just set a tag that the registration service would interpret. In the case of the registration we were intentionally trying not to change the UI, so we accepted more complexity.

**Comment by andrewjbtw** [comment]
The preassembly menu has been updated to include reading order now, so it's not just registration. Users will soon be able to accession books with a reading order set properly, but they will not be able to change the order of existing books. 

I don't disagree that it would be good to update the UI to signal that reading order is not itself a content type. However, I've received no assurances that we will make a more comprehensive update of the UI until 2022, and the ability to change reading order in Argo for individual items and for batches is a requirement for leaving Fedora. If we have to make a compromise to enable that, then we have to make a compromise.
