### ISSUE TITLE
Registration helper PDF generation does not separate data/query logic from presentation

### ISSUE THREAD

**Issue by atz** [sul-dlss/argo#254]

**Comment by LynnMcRae** [comment]
Is the PDF in support of tracking sheets? ergo connected to "Improve support for tracking sheets" #217

**Comment by atz** [comment]
Yeah, definitely related.  The code is so problematic because it has query logic, multiple reindexing loops and PDF building in the same 2 methods.  So this ticket is effectively a sub-part of #217.

**Comment by atz** [comment]
Notably, it doesn't even have a test file as a placeholder for the *idea* you might want to test it.

**Comment by aaron-collier** [comment]
This generally refers to no longer existent code: https://github.com/sul-dlss/argo/commit/7cfa0a970435f5a279fe9bc533c7f94753e87a7e and today: https://github.com/sul-dlss/argo/blob/master/app/helpers/registration_helper.rb
