### ISSUE TITLE
Replace ActiveFedora#Datastream in spec/requests/update_datastream_spec.rb

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2545]

**Comment by jcoyne** [comment]
This is a duplicate of #2437/#2535?

**Comment by aaron-collier** [comment]
I don't think it's necessarily a duplicate, but is part of them. I won't put this in ready as the PRs that are coming for those tickets will likely close this one.

**Comment by andrewjbtw** [comment]
Is this closeable now? The two tickets linked above appear to have been completed.
