### ISSUE TITLE
Support setting the barcode of an object through the user interface

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2547]
## Summary

In order to support controlled digital lending the repository manager needs to be able to set the barcode on an object.

## Requirement

In order to avoid editing the identityMetadata datastream directly, adding a barcode column on the registration form, adding a blue button for managing barcode (i.e. how catkey is managed), and adding a bulk action (i.e. manage catkey) would remove one of the use cases that requires editing identityMetadata today.

## Completion

When the barcode of an object can be set during registration, through a blue button on the object, and through a bulk action.

**Comment by jcoyne** [comment]
How is this different than #2549?

**Comment by jcoyne** [comment]
Superseded by #2865
