### ISSUE TITLE
Add manage barcode bulk action

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2550]

**Comment by jcoyne** [comment]
Is this "Update barcode on items when given a list of druids and corresponding barcodes"?

**Comment by andrewjbtw** [comment]
Yes.

**Comment by astridu** [comment]
When user selects 'Manage catkeys/barcodes', 3 radio buttons appear, and the corresponding fields appear below once radio button is selected. 
![image](https://user-images.githubusercontent.com/42216982/112362112-53dbea80-8c91-11eb-87bd-503ad451e785.png)
![image](https://user-images.githubusercontent.com/42216982/112362128-58a09e80-8c91-11eb-843b-6f12ba4bafa2.png)
![Uploading image.png…]()

**Comment by jcoyne** [comment]
@astridu can you show the "catkeys and barcodes" design too?

**Comment by astridu** [comment]
Yes, sorry, I had uploaded, but then forgot the upload CSV icon. I'll post the other 2 shortly.

**Comment by jcoyne** [comment]
What do we do if the CSV file is invalid?  Can you show that interaction too?

**Comment by jcoyne** [comment]
Should we offer a template CSV they can download so that all the headers are correct?

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/112365379-d1552a00-8c94-11eb-9252-8e28952768a0.png)

![image](https://user-images.githubusercontent.com/42216982/112365088-79b6be80-8c94-11eb-86eb-f81be49ee4b3.png)

**Comment by astridu** [comment]
@andrewjbtw I think it would be nice to allow users to download a template csv. What do you think?

**Comment by andrewjbtw** [comment]
Yes, that's a great idea.

**Comment by jcoyne** [comment]
@astridu  the errors we might encounter like this: "The barcode on line 7 is not valid.  You provided: 'foobar'"  We could potentially see thousands of these, so they won't all fit in that small area.

**Comment by astridu** [comment]
Sorry for the delayed response. Is it possible to do something like this where we list the errors in a scrollable box so we don't have to display thousands of lines in view?
![image](https://user-images.githubusercontent.com/42216982/112419871-684bd180-8ce9-11eb-940b-3d1daf460c41.png)

**Comment by justinlittman** [comment]
Here is my cut at a UI that is consistent with other bulk actions:
![image](https://user-images.githubusercontent.com/588335/113910919-5d904280-97a7-11eb-8ec7-575370b59ee8.png)
