### ISSUE TITLE
Support changing the rights of objects that differ from APO

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2551]
## Summary

Currently, in order to change rights related metadata on an object, including the license, the use and reproduction statement, and the copyright statement, the rightsMetadata datastream must be edited directly. 

## Requirement

Allow setting the license, the use and reproduction statement, and the copyright statement in the user interface.

## Completion

When there are bulk actions for managing object rights, including license, use and reproduction statement, and copyright statement.

**Comment by jcoyne** [comment]
What should the design for this look like?

**Comment by aaron-collier** [comment]
The designs will be added as we get the tickets to ready, for now, they aren't ready and will be fleshed out.

**Comment by andrewjbtw** [comment]
Closing this as it's been implemented in bulk actions and is covered in the upcoming show page designs.
