### ISSUE TITLE
(for remediation) Report of item druids with "accessCondition" in rightsMetadata

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2552]
Example: rightsMetadata for https://argo.stanford.edu/view/druid:bk689jd2364 contains:

`<accessCondition type="license">CC pdm: Public Domain Mark 1.0</accessCondition>`

This is not a valid way to store license information in rightsMetadata and results in the license not being mapped correctly to Cocina or displayed correctly on the Purl. These items must be remediated.

**Comment by andrewjbtw** [comment]
@justinlittman We didn't finish up the report during the week you were away. Is the cache ready to run this now?

**Comment by justinlittman** [comment]
Running now.

**Comment by ndushay** [comment]
@andrewjbtw would you want the code to error to honeybadger if it encounters this?
