### ISSUE TITLE
(for remediation) Report of druids with <human> and <machine> elements in rightsMetadata outside of <use> tags

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2553]
Example: https://argo.stanford.edu/view/druid:cc377hs8114 contains `<human>` and `<machine>` elements outside of a `<use>` element in the rightsMetadata XML. This is not a valid way to store this information and results in incorrect mappings to Cocina and incorrect display on the Purl.

This is incorrect:

```xml
  <human type="creativeCommons">CC-BY SA 4.0</human>
  <machine type="creativeCommons" uri="https://creativecommons.org/licenses/by-sa/4.0/">by-sa</machine>
  <human type="useAndReproduction">This material may be shared or adapted provided appropriate credit is given to the originator, and the same license is used.</human>
```

This is correct:

```xml
 <use>
    <human type="creativeCommons">CC-BY SA 4.0</human>
    <machine type="creativeCommons" uri="https://creativecommons.org/licenses/by-sa/4.0/">by-sa</machine>
    <human type="useAndReproduction">This material may be shared or adapted provided appropriate credit is given to the originator, and the same license is used.</human>
  </use>
```

We need to remediate items with this issue before we move off of Fedora.

**Comment by andrewjbtw** [comment]
Similar to #2552, we still need to run this report.

**Comment by justinlittman** [comment]
Running now.

**Comment by justinlittman** [comment]
Emailed report to @andrewjbtw

**Comment by ndushay** [comment]
@andrewjbtw would you want the code to notify honeybadger if it encounters this?
