### ISSUE TITLE
file downloads not working on stage

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2563]
**Describe the bug**
On Argo stage, clicking on a link to download a file is generating an error:
https://app.honeybadger.io/projects/49894/faults/67265992

```
There was a problem with your request.
Expected a successful response from the server, but got an error
GET /items/http:/files?id=
500: Internal Server Error
```

**User Impact**
It's not possible to download individual files.

**To Reproduce**
1. Go to a druid on stage https://argo-stage.stanford.edu/view/druid:kf385wg1920
2. Click on a file in the contents list
3. See the error

**Expected behavior**
A modal should pop up to allow downloads.

**Additional context**
The Download all files link seems to work, just not individual file downloads.

**Comment by jmartin-sul** [comment]
the file links are all being rendered incorrectly, as `https://argo-stage.stanford.edu/items/http:/files?id=`, hence

> Dor::Services::Client::UnexpectedResponse: Bad Request: 400 ({"errors":[{"status":"bad_request","detail":"#/components/schemas/Druid pattern ^druid:[b-df-hjkmnp-tv-z]{2}[0-9]{3}[b-df-hjkmnp-tv-z]{2}[0-9]{4}$ does not match value: http:, example: druid:bc123df4567"}]})

from https://github.com/sul-dlss/argo/blob/1b90383272775f4d9b73619146feaf682bc46016/app/controllers/files_controller.rb#L105-L107

**Comment by jcoyne** [comment]
It looks like this was introduced by https://github.com/sul-dlss/dor-services-app/commit/e48642b6867fae6be9924d5723c0f3677540181e This caused the identifiers to be opaque, but we were previously parsing meaning from those identifiers.
