### ISSUE TITLE
rightsMD inheritance in Argo-dev

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#257]
In testing on Argo-dev it looks like Collections created from the APO page (at time of APO creation) are not inheriting defaultObjectRights. To recreate:

1. go to register APO page
2. fill out form and add collection (in this case, I didn't use the catkey option)
3. complete registration including defaultObjectRights for APO
4. Collection object rights default to world/world with no human-readable statements and a bunch of empty elements

Open question: is this due to -dev environment, or an actual bug?

**Comment by drh-stanford** [comment]
I'm seeing the same thing on my development instance. I looked at the Argo code a bit and it's a bug... It's creating the collection before the `defaultObjectRights` is generated for the APO. I don't know whether it's parity or pre-existing.

**Comment by drh-stanford** [comment]
I've got a PR for this, but I'm blocked on determining whether it's setting the _default_ collection for the APO correctly... All I see in the administrative data stream is this:

```xml
<administrativeMetadata>
  <descMetadata>
    <format>MODS</format>
    <source>DOR</source>
  </descMetadata>
  <registration>
    <workflow id="accessionWF"/>
    <collection id="druid:rm295jq3277"/>
  </registration>
</administrativeMetadata>
```

**Comment by LynnMcRae** [comment]
These administrative values -- collection and workflow -- are not auto-applied-defaults the same way defaultObjectRights is copied from the APO automatically for any member created. Instead they populate the choice dropdowns on the Item Registration page, making any single choice a de facto default via the form, but not via the service.  A workflow or colleciton member ship has to be explicitly indicated on service calls and is not limited to the APO offerings (though it would be odd if they weren't the same set of values).  The values here also don't apply to collection objects as they are being made in the same way they apply to items, so they are not relevant to the defaultObjectRights inheritance issue at hand.

**Comment by drh-stanford** [comment]
ok, so if I understand correctly, the "default" collection for an APO is simply the first collection in the registration element. it's relevant as when the collection is registered during the register APO process, it makes the new collection the 'default' collection for that APO. (see https://github.com/sul-dlss/argo/blob/develop/app/controllers/apo_controller.rb#L106-L112), so in the PR it affects the testing and APO save behavior. I think that's all I need for this PR. thanks.
