### ISSUE TITLE
Unable to update APOs

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2571]
**Describe the bug**
Saving the "Edit APO" form to update an APO is hitting an error. I selected a new license for https://argo-stage.stanford.edu/apo/druid:bs395tx5720/edit and submitted the form and got an error.

Argo error: https://app.honeybadger.io/projects/49894/faults/78554790

**User Impact**
It's not possible to update APOs.

**To Reproduce**
1. Go to an APO
2. Submit an update
3. See error

**Expected behavior**
The form should be saved with the new changes.

**Comment by jcoyne** [comment]
I was unable to reproduce this. I went to https://argo-stage.stanford.edu/apo/druid:bs395tx5720/edit and was able to set the license.

**Comment by jmartin-sul** [comment]
it seems like @andrewjbtw and @jcoyne were both testing using the same argo and DSA code, as both deployments were on the same commit hash at 3:47 and 6:46 pm pacific.  which would fit with the remediated data hunch.

<img width="1106" alt="Screen Shot 2021-03-24 at 8 11 07 PM" src="https://user-images.githubusercontent.com/7741604/112413549-a216db00-8cdd-11eb-9ab5-d6dc570a55be.png">
<img width="1117" alt="Screen Shot 2021-03-24 at 8 10 16 PM" src="https://user-images.githubusercontent.com/7741604/112413566-a9d67f80-8cdd-11eb-9ee4-007f9ea8a230.png">
<img width="1111" alt="Screen Shot 2021-03-24 at 8 13 14 PM" src="https://user-images.githubusercontent.com/7741604/112413576-ad6a0680-8cdd-11eb-9462-2f802a187dd3.png">

**Comment by andrewjbtw** [comment]
I think this was the data remediation. I just updated the APO in a few different ways, using both stage agreements, and it works.
