### ISSUE TITLE
Agreements are being indexed as items

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2572]
**Describe the bug**
Agreement objects are being listed in Argo stage as "items" instead of "agreements" 

An agreement object has `<objectType>agreement</objectType>` in the identityMetadata. In stage, after reindexing, these are being listed as items:

See these two stage agreements:

https://argo-stage.stanford.edu/view/druid:dd327qr3670
https://argo-stage.stanford.edu/view/druid:fc962rq4671

**User Impact**
This is preventing new APO creation because agreement objects are not in the menu on the Create APO form: https://argo-stage.stanford.edu/apo/new

<img width="881" alt="Screen Shot 2021-03-24 at 4 31 46 PM" src="https://user-images.githubusercontent.com/8975583/112397097-a089ea80-8cbe-11eb-8e80-138683093d13.png">

**Expected behavior**
Agreement objects should remain agreement objects.

**Comment by jcoyne** [comment]
That is only 1/2 of what makes an agreement, it also needs to have the model assertion too, right?

**Comment by jcoyne** [comment]
I think this is still blocked by https://github.com/sul-dlss/dor-services-app/pull/2601

**Comment by andrewjbtw** [comment]
I'm seeing dd327qr3670 indexed as agreement now, but fc962rq4671 is still indexed as item. I think fc962rq4671 may still not have all the data it's supposed to have.

**Comment by andrewjbtw** [comment]
After adding

```
  <objectId>druid:fc962rq4671</objectId>
```

to the identityMetadata of fc962rq4671 it's now being indexed as an agreement.

**Comment by jmartin-sul** [comment]
closing this for now, as @jcoyne thinks it's fixed.  fix should be deployed to prod, so if @andrewjbtw's testing uncovers problems, we can reopen.

**Comment by andrewjbtw** [comment]
Yeah, I think it's fixed.
