### ISSUE TITLE
Cannot add a collection to an item

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2573]
**Describe the bug**
When trying to add a collection to an item, I get this error: "An error occurred adding or removing the collection." I've tried this with multiple items on stage. I see this in HB too: https://app.honeybadger.io/projects/49894/faults/78563890

<img width="1211" alt="Screen Shot 2021-03-25 at 9 13 24 AM" src="https://user-images.githubusercontent.com/8975583/112505877-6ebe6580-8d4a-11eb-8b0c-6c6252d3a7ef.png">

**User Impact**
Users can't put items into collections or change the collection an item is in.

**To Reproduce**
1. Go to an item like https://argo-stage.stanford.edu/view/druid:cc262xq5907
2. Make sure it's open for modification
3. Go to the "Edit Collections" blue button
4. Try to add a collection
5. See the error message pop up

**Expected behavior**
The collection selected is supposed to be added to the RELS-EXT for the item and to the appropriate Cocina field (hasMemberOrders, I think).

**Additional context**
Removing a collection does work.

**Comment by jcoyne** [comment]
Related to https://app.honeybadger.io/projects/49894/faults/78563890
