### ISSUE TITLE
New argo banner icon image

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#259]
This replacement image combines the shell with the word Argo in a specific font (Desdemona black) to avoid issues with separate text placement on screen. It assumes the bottom of the shell will be clipped as it is today.  Here's how it looks against red:

![argo-banner-on-red](https://cloud.githubusercontent.com/assets/1824732/11379858/8e902d42-92a7-11e5-9071-f52bf363ce06.png)

and the transparent image itself:

![argo-banner-icon](https://cloud.githubusercontent.com/assets/1824732/11379875/a12cc762-92a7-11e5-860d-281ae7dc799f.png)

I can prepare other sizes or variations as needed, or send the image file directly.

**Comment by mejackreed** [comment]
Prefer not to use an image for text, rather we would add the actual text. This way we don't have to deal with different screen resolutions and its more accessible.

**Comment by LynnMcRae** [comment]
that's fine, as long as it shows in all browsers :)  do you need the font? It's Desdemona Black, altered color obviously, a little off white with slight drop shadow added. It's also all caps with the A a slightly larger size (150 vs 136)

**Comment by mejackreed** [comment]
I'd prefer not to introduce a new font if possible. If this is absolutely necessary, than it is better achieved with a text only svg image.

**Comment by LynnMcRae** [comment]
github won't allow attaching an .svg file, unless there's a different way to attach it. I can send it to you.  I appreciate your text observations, but the lettering here is as much new icon art as text (we're thinking hex stickers), and the scaling challenges of the banner logo is pretty minimal to none I think. Just saying in the hopes of keeping this simple, but just tell me what you need.

**Comment by drh-stanford** [comment]
@LynnMcRae can you send me the .svg or Photoshop file for this?

**Comment by drh-stanford** [comment]
i believe you can attach `.zip` files to github issues if you want to put it here

**Comment by mejackreed** [comment]
If @LynnMcRae can provide a 152x52px transparent png, an easy implementation is just changing the blacklight scss variable: https://github.com/projectblacklight/blacklight/blob/b11cf399a1416b995322032031f5543a5387cc8c/app/assets/stylesheets/blacklight/blacklight_defaults.scss#L3

**Comment by mejackreed** [comment]
Here you go @drh-stanford 
![argo-logo](https://cloud.githubusercontent.com/assets/1656824/12524809/bcbd1da6-c114-11e5-826b-f939bebba250.png)

**Comment by drh-stanford** [comment]
This is what the navbar looks like at different browser widths. @mejackreed is there a way to prevent the newline break and go to the responsive menu thing in the first image below?

![screen shot 2016-01-22 at 4 25 14 pm](https://cloud.githubusercontent.com/assets/1861171/12526673/c5e3c8a2-c124-11e5-8302-4bb7c698c624.png)
![screen shot 2016-01-22 at 4 24 55 pm](https://cloud.githubusercontent.com/assets/1861171/12526675/c5e8098a-c124-11e5-901e-46298588a247.png)
![screen shot 2016-01-22 at 4 24 36 pm](https://cloud.githubusercontent.com/assets/1861171/12526672/c5e34918-c124-11e5-8f3f-8c8b9b1867df.png)
![screen shot 2016-01-22 at 4 24 14 pm](https://cloud.githubusercontent.com/assets/1861171/12526674/c5e65db0-c124-11e5-8204-80f89380c184.png)

**Comment by mejackreed** [comment]
@drh-stanford try setting this in `bootstrap-overrides.scss`

```scss
// Grid System
$grid-float-breakpoint: 992px;
```

From http://getbootstrap.com/customize/#grid-system
