### ISSUE TITLE
Update dor-services gem to correctly initiate workflow by name 

### ISSUE THREAD

**Issue by wmene** [sul-dlss/argo#26]
@jmartin-sul 

In order for the "Add Workflow" blue button to work correctly, the dor-services gem in master needs to get updated to 4.19.1

**Comment by atz** [comment]
Develop is on `~> 5.0`, so the next (big) merge/release will get there.

**Comment by atz** [comment]
@wmene is this the same problem we saw with the workflow handling last week?

**Comment by jmartin-sul** [comment]
FWIW, the currently deployed version of argo (2.13.6) is using versoin 4.19.1 of dor-services already
