### ISSUE TITLE
Can't remove tag: "Remediated By : 4.21.4"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2611]
**Describe the bug**
Attempting to remove the tag "Remediated By : 4.21.4" from https://argo.stanford.edu/view/druid:yx488yp0920 is getting a 500 error.
https://app.honeybadger.io/projects/49894/faults/68417597

**User Impact**
The tag can't be removed.

**To Reproduce**
1. Go to the druid
2. Click on "Edit tags"
3. Click the "X" next to the tag to remove

**Expected behavior**
The tag should be removed.

**Additional context**
Other tags on this same druid were removable, but not this one.

**Comment by andrewjbtw** [comment]
I also can't remove that tag from https://argo.stanford.edu/view/druid:mt447ry9798 

I wonder if this tag was never migrated from identityMetadata when the tag service was implemented. Removing it from identityMetadata has no effect now, so this tag is effectively un-editable.

This is the HB error I see: https://app.honeybadger.io/projects/49894/faults/68417597

**Comment by peetucket** [comment]
Could this be due to the ":" in the tag name causing issues with the rails routes... 

`dor-services-client` as used by Argo makes this call to `dor-services-app` which shows up in the logs as a 404 because Rails can't complete the route correctly:

```
I, [2021-04-12T14:49:32.449289 #20193]  INFO -- : [49ee820b-4e10-458d-91ba-b4b13b6e061f] Started DELETE "/v1/objects/druid:mt447ry9798/administrative_tags/Remediated+By+:+4.21.4" for 10.111.6.41 at 2021-04-12 14:49:32 -0700
F, [2021-04-12T14:49:32.450503 #20193] FATAL -- : [49ee820b-4e10-458d-91ba-b4b13b6e061f] ActionController::RoutingError (No route matches [DELETE] "/v1/objects/druid:mt447ry9798/administrative_tags/Remediated+By+:+4.21.4"):
```

`dor-services-client` escapes the tag when forming the API call: https://github.com/sul-dlss/dor-services-client/blob/main/lib/dor/services/client/administrative_tags.rb#L89

But the routing in dor-services-app doesn't appear to be routing this correctly.

**Comment by peetucket** [comment]
Not quite sure I understand why the colon in the URL in the log isn't escaped, as escaping it manually like the client does on the rails console seems to escape it:

```
2.7.0 :007 > CGI.escape('Remediated By : 4.21.4')
 => "Remediated+By+%3A+4.21.4"
```

**Comment by andrewjbtw** [comment]
The standard tag format is to have a ":" in it so that by itself shouldn't be an issue.

**Comment by jcoyne** [comment]
@peetucket Is there a delete route in DSA? I don't see it: https://github.com/sul-dlss/dor-services-app/blob/main/config/routes.rb#L26-L30

**Comment by jcoyne** [comment]
It's likely the dots in the tag. Rails doesn't handle that well by default. It thinks everything after the dot is a file extension.

**Comment by peetucket** [comment]
Ahh yes, the dots.  And they don't get URL encoded I guess.  I'll have a look at that tomorrow.  Thanks Justin.
