### ISSUE TITLE
Items with licenses that are not in the license menu are being reported as invalid Cocina and disappearing from facets and search

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2612]
**Describe the bug**
Items that have the following licenses in the rightsMetadata XML:
```xml
    <machine type="creativeCommons">none</machine>
    <human type="creativeCommons">no Creative Commons (CC) license</human>
```
```xml
  <human type="creativeCommons">Attribution-NonCommercial 4.0 International</human>
  <machine type="creativeCommons">by-nc-i</machine>
```
```xml
    <human type="creativeCommons">CC0 No Rights Reserved</human>
    <machine type="creativeCommons" uri="https://creativecommons.org/publicdomain/zero/1.0/">cc0</machine>
```
are being treated as having invalid Cocina representations, which then means that:

- the Argo show page doesn't render properly (top-level data like APO, collection, contents list is missing from display)
- they don't get indexed properly in the facets
- they can't be found in search

This looks like the HB error: https://app.honeybadger.io/projects/50568/faults/78630231

**User Impact**
These items cannot be managed or even found. It's as if they've ceased to exist. This also means that we cannot use the license facet to find items with license "none" to remediate them because they won't be there at all.

**To Reproduce**
1. Go to an item with license of "none", such as https://argo.stanford.edu/view/druid:sy486tp5223
2. See that the top-level display is missing the APO and other information
3. Scroll down and see that the contents list is blank
4. Search for the druid and see no results: https://argo.stanford.edu/catalog?utf8=%E2%9C%93&search_field=text&q=sy486tp5223

**Expected behavior**
Lack of a license should not cause so many other problems.

**Screenshots**
No APO, collection, or identity information on the show page:
<img width="1218" alt="Screen Shot 2021-03-30 at 2 58 58 PM" src="https://user-images.githubusercontent.com/8975583/113062592-d7517c00-9168-11eb-9ceb-2de70d3e7542.png">

Nothing displayed in the contents list:
<img width="1218" alt="Screen Shot 2021-03-30 at 3 02 29 PM" src="https://user-images.githubusercontent.com/8975583/113065989-92c8df00-916e-11eb-88df-1a546cb53cea.png">

**Additional context**
I will file an additional issue around the larger problem of what to do if an item fails Cocina validation. We can't just have them disappear or we wouldn't be able to manage them at all. I found this because it has an unusual rights setting and previously showed up in the Access Rights facet. Once it got reindexed and found to be invalid Cocina, it disappeared from the rights facet altogether.

**Comment by jcoyne** [comment]
@andrewjbtw I'm pretty sure the "none" license is invalid data possibly from a software bug.  The existing software handles `:none` (a ruby Symbol), but not the string `"none"`. 

Should we remediate the data there to be `<machine type="creativeCommons"></machine>`?


Regarding the second issue, `by-nc-i` is not a valid cc license code. The code should be `by-nc` for the license. See: https://creativecommons.org/licenses/by-nc/4.0/  Should we remediate that data?


Finally, 'cc-0' is not in our controlled vocabulary.  Should we add it? https://github.com/sul-dlss/dor-services/blob/1743ea8c144467d0167c333d34cfb62b9d2eb7ec/lib/dor/services/creative_commons_license_service.rb?

**Comment by andrewjbtw** [comment]
In order from what I think is easiest to most difficult:

1\. We should add cc-0 to the vocabulary

2\. For `by-nc-i` we need to be able to support the 4.0 version. If we go to `by-nc` we should insert the 4.0 URI and make sure that is what gets persisted in Cocina. All of the material with `by-nc-i` is in the Parker Manuscripts and I'm sure giving them this license was a deliberate choice.

3\. It's really not clear what's right or wrong for the "none" situation. In the Chimera docs, it says

>If no license is desired, the rightsMetadata should omit any empty declaration of either type, not produce a null or "None" value.

(bottom of the page here: https://consul.stanford.edu/display/chimera/Rights+metadata+--+the+rightsMetadata+datastream )

But the ETD app has always been sending a "none". The options seem to be to either omit the rights altogether or create a new code to indicate "none".

**Comment by andrewjbtw** [comment]
But the overall problem is that since these items are no longer getting the Cocina indexing, they are disappearing from the License facets (and other facets) altogether. So while we used to be able to find all "none", "by-nc-i" and "cc0" items in the facet, we can no longer do that.
