### ISSUE TITLE
Add CC0 to the Argo LICENSE_CODES list and license menus

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2617]
We have a small amount of data using a CC0 license. In rightsMetadata, that looks like:

```xml
 <human type="creativeCommons">CC0 No Rights Reserved</human>
    <machine type="creativeCommons" uri="https://creativecommons.org/publicdomain/zero/1.0/">cc0</machine>
```
Since that's a valid CC license with a valid URI, we should add it to the official list. Currently, we are marking items with this license as not having valid Cocina.

This ticket was split off of https://github.com/sul-dlss/argo/issues/2612

**Comment by jcoyne** [comment]
This will require changes to both argo and dor-services-app (and maybe dor-services).
