### ISSUE TITLE
add "View in new window" Cocina link to get full JSON for cocina

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#2618]
Since we now have collapsed Cocina by default in the record view, it can be a pain to get the full cocina.  If we add a link to this left navvy area:

![image](https://user-images.githubusercontent.com/96775/113218641-bbb3a780-9234-11eb-8d00-3f3c2b40c72e.png)

that opens a new window with something as simple as the raw JSON, that could be a help to us, the developers and to Andrew and others for troubleshooting.

**Comment by mjgiarlo** [comment]
@ndushay or how about some javascript (like suggested in https://github.com/caldwell/renderjson/issues/17) to expand all?

**Comment by ndushay** [comment]
I'd be open to an "expand all" as long as I can copy and paste it somewhere else.

**Comment by justinlittman** [comment]
I went with the original proposal because, you know, no javascript.
