### ISSUE TITLE
when creating an APO and collection at the same time, the collection is not assigned the APO defaults

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2619]
**Describe the bug**
I created this APO: https://argo-qa.stanford.edu/view/druid:xw841gj9531
At the same time I created this collection: https://argo-qa.stanford.edu/view/druid:bm413tb2218

The collection does not have the APO defaults for copyright, license and use and reproduction statement.

**User Impact**
The collection is created without any of the default rights.

**To Reproduce**
1. On QA, go to "Register APO"
2. Choose to create a collection at the same time
3. Fill in the statement fields and license so you know they're non-blank
4. See that the collection has none of those license/statement defaults

**Expected behavior**
The collection should get the APO default object rights. Except for the access rights to the collection object -- see below.

**Additional context**
There is one problem case with these defaults with respect to collections. The create collection sub-form allows you to choose the collection object rights. I think these rights override the APO default object rights for the "access" rights with respect to the collection object. This should continue to be the case.

**Comment by jcoyne** [comment]
@andrewjbtw this is the current behavior in production, right?

**Comment by andrewjbtw** [comment]
Current behavior in production is to assign all the statements + license when creating a new collection. This collection in stage that I created a couple of weeks ago has the statements from its APO: https://argo-stage.stanford.edu/view/druid:my577hk6407

**Comment by andrewjbtw** [comment]
You're right, that's the current behavior in production. I guess I've never noticed because creating both at the same time doesn't happen often. I would consider this a bug, since the usual method of creating collections does bring in the statements.

**Comment by jcoyne** [comment]
I think the problem in this case is that you have to create the collection first, and then it is made a default collection in the apo, but the apo defaults are usually applied at registration time.  So, the apo doesn't yet exist when the collection is created.

**Comment by andrewjbtw** [comment]
Right, it looks like a case of SDR trying to bootstrap something and not getting all of it right. But since it's not a regression, I don't think it should hold up the decoupling work.

**Comment by andrewjbtw** [comment]
Going to close this as not actionable. It's an open question as to whether collections should get some of the APO defaults. Collections use a different rights vocabulary (only world or dark) that has now been standardized in Cocina, and it's not always clear whether collections should have the same rights statements as items.
