### ISSUE TITLE
(QA testing) newly created collection stalls in accessioning with:  content-metadata : #/components/schemas/Access does not define properties: copyright 

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2620]
**Describe the bug**
In QA, collection accessioning is stalling when a collection has a copyright statement. See https://argo-qa.stanford.edu/view/druid:wr455zs4178

**User Impact**
Collections created from APOs that have default copyright statements will stall in accessioning.

**To Reproduce**
1. Go to an APO that has a default copyright statement https://argo-qa.stanford.edu/view/druid:xw841gj9531
2. Create a collection
3. See collection object hit error in accessioning

**Expected behavior**
The collection object should be accessioned.

**Comment by jcoyne** [comment]
This is because common-accessioning in qa has not received the updated cocina-models.  cc @mjgiarlo

**Comment by mjgiarlo** [comment]
@jcoyne Note to self: next time just update & deploy all the dang codebases when you make a backwards-compatible cocina-models release.

**Comment by mjgiarlo** [comment]
@andrewjbtw @jcoyne this should be fixed in QA now that I've deployed https://github.com/sul-dlss/common-accessioning/pull/750 there. Can you confirm?

**Comment by andrewjbtw** [comment]
Yes, this is fixed. Thanks!
