### ISSUE TITLE
(QA testing) when submitting the Edit APO form, the one default workflow on the form overwrites all other default workflows

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2621]
**Describe the bug**
In the current system, it's possible to enter more than one default workflow for an APO, but users have to edit the administrativeMetadata datastream to do this. The Register and Edit APO forms only allow users to choose one workflow from a dropdown list. What people usually do is select `registrationWF` when creating the APO, then come back and add to the administrativeMetadata via a datastream edit.

A typical combination of workflows might look like this in the XML:
```xml
<registration>
    <workflow id="registrationWF"/>
    <workflow id="goobiWF"/>
```
Current behavior in production when re-submitting the APO form is to leave the additional workflows in place. The form resubmission will change the workflow at the top of the list but doesn't overwrite the others.

In QA, the form is now overwriting the workflow list with the one workflow selected on the form. If you create an APO and then edit the administrativeMetadata to look like this:
```xml
<registration>
    <workflow id="registrationWF"/>
    <workflow id="goobiWF"/>
```
and then you re-submit the form with `registrationWF` selected, the adminstrativeMetadata will look like this afterwards:
```xml
<registration>
    <workflow id="registrationWF"/>
```
**User Impact**
This effectively undos the datastream edits people have made to add additional workflows, meaning they will have to redo them again to get them back. These default workflows are what show up in the "initial workflow" dropdown menu on the Argo registration page. Many APOs involve both Goobi and preassembly accessioning, so it's especially important to be able to choose goobiWF or registrationWF

**To Reproduce**
See steps above re: editing the datastream and resubmitting the form.

**Expected behavior**
The multiple workflow values should remain in place.

**Additional context**
I've filed a related ticket to change the form to allow multiple selections #2379 I had originally thought we'd hold it for the new designs, but perhaps instead we should modify the existing form to allow multiple selections. This would make things clearer for users and remove the need to edit the datastream to add or remove workflows.

**Comment by peetucket** [comment]
Note: these bugs were triggered by code in a PR: https://github.com/sul-dlss/argo/pull/2529

**Comment by andrewjbtw** [comment]
This is now working.
