### ISSUE TITLE
(QA testing) Adding a default collection to an APO via the APO form overwrites the collection list. It should append to the list.

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2622]
**Describe the bug**
Users can add default collections to APOs using the Edit APO form. The form option is labeled "Choose a default collection":

<img width="896" alt="Screen Shot 2021-03-31 at 5 10 24 PM" src="https://user-images.githubusercontent.com/8975583/113226119-359f5d00-9244-11eb-8100-67ec5f1f1a6a.png">

In production, choosing a collection here adds that collection the the list of collections in the administrativeMetadata for that APO. In QA, choosing a collection here is overwriting the list of collections with just the one collection chosen on the form.

An administrativeMetadata with multiple collections listed looks like this:

```xml
<registration>
    <workflow id="registrationWF"/>
    <collection id="druid:xz298sq1202"/>
    <collection id="druid:wr455zs4178"/>
  </registration>
```
**User Impact**
Overwriting the list makes it impossible to use the form to add collections to an APO. In production, there are APOs with 10+ collections listed in the APO. If those lists get overwritten, then all of those collections would need to be added back via datastream edits.

**To Reproduce**
1. Go to an APO with multiple collection like https://argo-qa.stanford.edu/view/druid:rn269yf4172
2. Edit the APO
3. Add a completely different default collection
4. See that there is only one collection

**Expected behavior**
The selected collection should be appended to the list of collections.

**Additional context**
Removing a collection does seem to operate as expected. Instead of removing all items listed, it just removes the single item chosen for removal.

**Comment by peetucket** [comment]
Note: these bugs were triggered by code in a PR: https://github.com/sul-dlss/argo/pull/2529

**Comment by andrewjbtw** [comment]
Adding and removing collections is now operating on one collection at a time, as expected.
