### ISSUE TITLE
(QA testing) Submitting the Edit APO form keeps re-creating version 1 on QA

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2628]
**Describe the bug**
When submitting the "Edit APO" form on an existing APO, the submission overwrites the versioning information and resubmits version 1.

**User Impact**
In stage or production, this would probably result in a version mismatch error. In QA, nothing seems to be checking for version mismatch and the APO keeps getting re-saved as v1.

**To Reproduce**
1. Go to an existing APO in QA
2. Resubmit the form
3. See the version history get reset to show version 1 is in progress
4. See the accesionWF run again on v1

**Expected behavior**
The Edit APO form should not automatically kick off accessioning. APOs should follow the same open and close logic as other objects and only start accessioning when the object is closed.

**Comment by jcoyne** [comment]
@andrewjbtw I believe the current production behavior is to kick off accessioning as soon as the APO is saved, is that not the case?

**Comment by andrewjbtw** [comment]
Only when creating the APO. When editing an APO it just returns to the show page after making the change.

**Comment by andrewjbtw** [comment]
This is now working.
