### ISSUE TITLE
Edit APO form loads the incorrect default object rights in the menu when rights are location-based

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2631]
**Describe the bug**
When the default object rights on an APO are location-based, the Edit APO form pre-populates the access rights dropdown with the value of "World".

APO https://argo-qa.stanford.edu/view/druid:vr838wn4827 has rights as location: Archive of Recorded Sound ("ars"):

<img width="538" alt="Screen Shot 2021-04-02 at 1 53 51 PM" src="https://user-images.githubusercontent.com/8975583/113453498-f6474c80-93ba-11eb-95f6-6f4b2c8f7dcd.png">

But when loading the Edit APO form, the menu shows "world" selected:
<img width="538" alt="Screen Shot 2021-04-02 at 1 55 26 PM" src="https://user-images.githubusercontent.com/8975583/113453574-242c9100-93bb-11eb-9bfc-8bbb4b0a177b.png">

**User Impact**
It would be easy to accidentally change the default object rights to world when editing the APO to change another value.

**Expected behavior**
The currently selected value should populate the menu.

**Comment by jcoyne** [comment]
@andrewjbtw it looks like this is the current behavior on prod too, right? https://argo.stanford.edu/apo/druid:jc903qt9117/edit

**Comment by andrewjbtw** [comment]
Oddly, that's defaulting to citation-only but it is the same issue. I thought I'd caught all the form default selection problems during last summer's maintenance but I must not have been as thorough in testing then as I've been recently.

**Comment by jcoyne** [comment]
Given that, I'm removing the "(QA testing)" tag.

**Comment by andrewjbtw** [comment]
Ok, but we should fix this before we take out XML editing if we're going to expect people to use the form.
