### ISSUE TITLE
"Back to search" link on Bulk Action page sometimes returns a "pids-only" search

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2645]
**Describe the bug**
This is an odd one. Under some circumstances, the "Back to search" link on the Bulk actions page links to a "pids-only" search result. The link is here on the "Bulk actions" page:

<img width="1225" alt="Screen Shot 2021-04-06 at 1 32 01 PM" src="https://user-images.githubusercontent.com/8975583/113774746-8a2b5800-96dc-11eb-8a1f-4c86fd610e0e.png">

When you first load the page, that link takes you back to your most recent search. But after submitting a bulk action, the page is reloaded and the link then goes to a "pids-only" search:

<img width="1001" alt="Screen Shot 2021-04-06 at 1 10 15 PM" src="https://user-images.githubusercontent.com/8975583/113774865-b47d1580-96dc-11eb-8adb-182c17609724.png">

**User Impact**
Since the pids-only search just lists druids, there's no link for people to follow to get back to their items.

**To Reproduce**
1. Go to bulk actions
2. Click on new bulk action
3. Choose something simple and non-destructive, like reindex
4. Enter a druid in the box
5. Submit the bulk action
6. Look at the "back to search" link again

**Expected behavior**
Back to search should be a regular search.

**Additional context**
This has probably been a problem for a while but not noticed. I don't think it's related to the work cycle.

**Comment by peetucket** [comment]
Very likely related to the "Populate with previous search" button on the bulk action page.  It didn't happen to be me when I don't use this button.  It looks like that button executes a blacklight based search adding on the "pids_only=true" parameter.  

See:

https://github.com/sul-dlss/argo/blob/main/app/views/bulk_actions/new.html.erb#L146
https://github.com/sul-dlss/argo/blob/main/app/search_builders/argo/custom_search.rb
https://github.com/sul-dlss/argo/blob/main/app/helpers/bulk_action_helper.rb

Meanwhile, the "Back to search" link uses a helper "link_back_to_catalog":

https://github.com/sul-dlss/argo/blob/main/app/views/bulk_actions/index.html.erb#L9

Added in this PR: https://github.com/sul-dlss/argo/pull/2003

I'm not sure what that does or where it is defined, but I'm guessing it has been keeping track of the search params and just blindly tacked on the "pids_only", which may need to stripped from there.
