### ISSUE TITLE
Page header inconsistencies

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#267]
A lot of great work moving to BL standard navigation and page elements, makings some remaining inconsistencies easy to spot. 

- the "You searched for" bar starts partway into the screen, above the data portion of the display in all cases but one ... on the WF Grid page it starts on the left edge above the "Limit your search"
- Is there a reason  "Start Over" and "Back to Search" are links and not buttons? I can't say there was any rationale for that in old Argo since it did both!
- The "Select View" button appears on both the left and right of its bar ... it should always be to the far right.
- In the case of the workflow grid, we currently have an extra element -- the link to the Robots/Job Status page on the far right of this bar. This could be placed far left if doable, or even moved down to be a lead-in element of the workflow-display portion of the screen since it is unique to that view.
- Bulk Update seems a greater challenge that can be addressed separately.  The common navigation elements added there are great for now.

![screen shot 2015-11-25 at 11 02 21 am](https://cloud.githubusercontent.com/assets/1824732/11407461/c7f0787e-9367-11e5-9307-baab3726370a.png)
![screen shot 2015-11-25 at 11 03 07 am](https://cloud.githubusercontent.com/assets/1824732/11407460/c7efd73e-9367-11e5-8130-103161feee40.png)
![screen shot 2015-11-25 at 11 03 37 am](https://cloud.githubusercontent.com/assets/1824732/11407458/c7ed1062-9367-11e5-98e5-66a8889088bf.png)
![screen shot 2015-11-25 at 11 20 21 am](https://cloud.githubusercontent.com/assets/1824732/11407459/c7ed4c8a-9367-11e5-8aca-14f4137eb595.png)
![screen shot 2015-11-25 at 11 36 58 am](https://cloud.githubusercontent.com/assets/1824732/11407651/e54c3e2a-9368-11e5-97e3-f3742d695e27.png)

**Comment by mejackreed** [comment]
>the "You searched for" bar starts partway into the screen, above the data portion of the display in all cases but one ... on the WF Grid page it starts on the left edge above the "Limit your search"

Good observation. Just a fluke, consistency can easily be shored up.

> Is there a reason "Start Over" and "Back to Search" are links and not buttons? I can't say there was any rationale for that in old Argo since it did both!

We are using the standard Blacklight controls here. No reason to change that as far as I can tell.

> The "Select View" button appears on both the left and right of its bar ... it should always be to the far right

Unfortunately trying to make this in the same location on each type of view page, can't be done without a larger refactor effort. I felt this was the best approach while limiting the exposure of us having to redo too many things.
