### ISSUE TITLE
support full embargo release rights possibilities (is this independent of #2009?)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#2674]
~~blocked by https://github.com/sul-dlss/dor-services-client/issues/217~~
~~which is blocked by https://github.com/sul-dlss/dor-services-app/issues/2705~~
~~which is blocked by https://github.com/sul-dlss/cocina-models/issues/253~~

Related to / concurrent with #2009:

Per sul-dlss/argo/issues/2009, we will need to support ALL flavors/nuances of access rights upon embargo release.

![image](https://user-images.githubusercontent.com/96775/114796228-4a501a80-9d45-11eb-99f5-94e049f1d7c4.png)

However, @andrewjbtw says:

> I should add that arguably, an embargo should only support increasing rather than limiting access but
> 
> - it may be simpler to show the same rights menu here as elsewhere instead of customizing just for embargoes
> - only citation-only and dark would be excluded if we excluded anything
> - the idea was suggested for digital borrowing that items could be set to "expire" at the end of the quarter by automatically changing to citation-only or dark via embargo release. We have not been asked to implement this but it also has not been categorically ruled out.

(so consider the above and double check with andrew before setting a PR ready for review ... but it's ok to lean towards "least effort", i would think)

So when you click the Update Embargo blue button on the left for an item, you get this:

![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/8a430df4-b505-4d48-9121-f81659139189)

and it needs to have a pulldown added like that (the same as?) for "Set Rights" blue button, so the user can indicate what the rights should be upon embargo release.   Do double-check with @andrewjbtw to be sure this is what he wants.

**Comment by ndushay** [comment]
@justinlittman @andrewjbtw  is this done?   Does argo now allow users to set any legal embargo release access?

**Comment by justinlittman** [comment]
It is for bulk action; I can't speak to the blue button.
