### ISSUE TITLE
Don't add <bookData> to contentMetadata for non-book object types

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2681]
**Describe the bug**
A `<bookData>` is being inserted into contentMetadata when you change a content type even if the object is not a book.

Example of before and after of changing content type:

Before:
```xml
<contentMetadata objectId="druid:mc733pr7221" type="document">
  <resource id="http://cocina.sul.stanford.edu/fileSet/772b7705-bb3c-4729-8a09-76ac5b7a46a6" sequence="1" type="document">
    <label/>
    <file id="placeholder.txt" mimetype="text/plain" size="99" publish="yes" shelve="yes" preserve="yes">
      <checksum type="sha1">24a4c34c6f799d9189c42e8eaca6fae593db5dd4</checksum>
      <checksum type="md5">92d8c1d8f8ab0bc2f464052292ba1aaa</checksum>
    </file>
  </resource>
</contentMetadata>
```
After:
```xml
<contentMetadata objectId="druid:mc733pr7221" type="file">
  <bookData readingOrder="ltr"/>
  <resource id="http://cocina.sul.stanford.edu/fileSet/772b7705-bb3c-4729-8a09-76ac5b7a46a6" sequence="1" type="file">
    <label/>
    <file id="placeholder.txt" mimetype="text/plain" size="99" publish="yes" shelve="yes" preserve="yes">
      <checksum type="sha1">24a4c34c6f799d9189c42e8eaca6fae593db5dd4</checksum>
      <checksum type="md5">92d8c1d8f8ab0bc2f464052292ba1aaa</checksum>
    </file>
  </resource>
</contentMetadata>
```

**User Impact**
Unclear. `<bookData>` is only meaningful within the book content type and seems to be ignored otherwise by the Access systems. But there may be some undesirable effect on the display if the systems start parsing the code differently.
 
**To Reproduce**
1. Go to an object like this test object (in prod): https://argo.stanford.edu/view/druid:mc733pr7221
2. Change the content type
3. See `<bookData>` is added.

**Expected behavior**
`<bookData>` should only be applied to books.

**Comment by jcoyne** [comment]
This appears to be happening because Argo is sending "hasMemberOrders" as:

```
      "hasMemberOrders": [
        {
        }
      ]
```

but non-book types should not be sending this at all.
