### ISSUE TITLE
Facet space and navigation issues

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#271]
Two possibly related usability issues

The top level facet values are indented with bullets, a significant waste of space taken away from facets with long values.  The default BL style does not do this (see http://demo.projectblacklight.org/) so I'm hoping it's something added we can remove.

Hierarchical tags in current Argo have obvious triangle controls to both indicate and open/close nested levels. Now you have to click somewhere near -- in open space to the right -- but not on the value to open up the next level. 

![screen shot 2015-11-25 at 3 59 40 pm](https://cloud.githubusercontent.com/assets/1824732/11412134/9711fdce-938d-11e5-920e-40f5a4ead2e4.png)

**Comment by mejackreed** [comment]
#283 also solved this issue.

<img width="260" alt="screen shot 2015-12-02 at 9 17 37 pm" src="https://cloud.githubusercontent.com/assets/1656824/11552498/279ba51e-993a-11e5-9cde-5ddba18f6ef3.png">
