### ISSUE TITLE
Deployment server should have passenger threads maxed out

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#273]
stage environment only has one passenger thread active. This should be scaled up to handle app requests.

**Comment by drh-stanford** [comment]
it looks like there's multiple threads (inside a single process?). the passenger config shows

```
  PassengerMaxPoolSize 30
```

@eefahy could you please verify that we're configured to do multiple Passenger processes on stage? it doesn't look like earthworks which has lots of (unix) processes.
