### ISSUE TITLE
Downloading reports from the bulk actions list changes the URL in the browser so that a refresh of the page redownloads the report

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2731]
**Describe the bug**
Each user has access to a page that lists all bulk actions they previously ran. Certain bulk action produce reports that can be downloaded from this page. After downloading a report, the URL in the browser address bar is updated to show the download link. This results in the report being re-downloaded when the user refreshes the page.

**User Impact**
Causes some confusion. Users will refresh this page to check on the progress of running jobs, so a "clean" refresh is a smoother experience.

**To Reproduce**
1. Go to https://argo.stanford.edu/bulk_actions
2. Run a Download Descriptive Metadata job
3. Wait for it to finish
4. See the download link appear on the list
<img width="1111" alt="Screen Shot 2021-04-29 at 10 28 57 AM" src="https://user-images.githubusercontent.com/8975583/116593291-c7e36100-a8d5-11eb-9d21-50f6556b67ee.png">

5. Download the metadata 

6. See that the browser URL now points to the download link
<img width="1111" alt="Screen Shot 2021-04-29 at 10 33 53 AM" src="https://user-images.githubusercontent.com/8975583/116593942-84d5bd80-a8d6-11eb-8a03-e5651dae6912.png">
7. Reload the page and see the file reload again

**Expected behavior**
Downloading shouldn't change the URL.

**Comment by peetucket** [comment]
#2734 fixes the log file downloads, see #2736 for the same fix for the reports referenced here
