### ISSUE TITLE
Some users are not seeing all of the APOs they're authorized to see in the registration form

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2741]
**Describe the bug**
I'm helping new users learn to use Argo and we noticed that the registration form isn't showing all of the APOs that they should be authorized to use for registration. They're able to see some APOs, but it's not clear why they can see those and not others:

<img width="411" alt="Screen Shot 2021-05-06 at 3 09 46 PM" src="https://user-images.githubusercontent.com/8975583/117371779-4fecdc00-ae7d-11eb-9afa-a4a514679e91.png">

They are also able to navigate to APOs that are not on their registration form list.

**User Impact**
Users are not able to add new druids using APOs they should be able to see.

**To Reproduce**
1. Impersonate a set of workgroups. The example I'm working from is someone with the following SDR workgroups.
```
workgroup:dlss:sdr-administrator,workgroup:sdr:accessioning,workgroup:sdr:admin-temporary,workgroup:sdr:administrator,workgroup:sdr:administrator-role,workgroup:sdr:argo-access,workgroup:sdr:cidr-staff,workgroup:sdr:hydrus-manager-role
```
2. Go to the registration form for items https://argo.stanford.edu/registration
3. See the limited list of APOs in the Admin Policy drop down (screenshot above)
4. See that the user can access items from an APO not on that drop down list, for example https://argo.stanford.edu/view/druid:mr208cj4487 which is under the APO: "Stanford University Libraries - General Collections"

**Expected behavior**
Users should be able to register items into all APOs they have permission to manage.

**Additional context**
May be related to https://github.com/sul-dlss/argo/issues/2688 where we fixed an issue where users couldn't see APO objects.

**Comment by jcoyne** [comment]
Is it always limited to 10?  A common solr error is using the default number of rows, which happens to be 10.

**Comment by andrewjbtw** [comment]
No, I see dozens. Even if it's the first 10, I'm pretty sure she should see a different set of 10.

**Comment by andrewjbtw** [comment]
It's possible the problem is the other way around and she's seeing data from APOs she shouldn't see, and the registration list is the one that's actually accurate for her permissions. The roles on the General Collections APO don't actually include anything on the impersonation list above:

https://argo.stanford.edu/view/druid:xk494bv8475

Maybe one of the administrator workgroups is getting a blanket level of access.

**Comment by jcoyne** [comment]
@andrewjbtw the `workgroup:sdr:administrator-role` group is the skeleton key.  If they are a member of that group they have unrestricted access.

**Comment by jmartin-sul** [comment]
good catch, was just about to look into this, and hadn't looked at the workgroup list yet.  but that is the super admin work group.

**Comment by jmartin-sul** [comment]
also, i'd agree with @andrewjbtw's snarkin on slack yesterday, there are some confusingly similar workgroup names in there that it'd be nice to disambiguate, particularly:

* workgroup:dlss:sdr-administrator
* workgroup:sdr:admin-temporary
* workgroup:sdr:administrator
* workgroup:sdr:administrator-role

vague recollection of `workgroup:dlss:sdr-administrator` being the old super admin role name, but would have to do some code archaeology to confirm that.

**Comment by andrewjbtw** [comment]
Does that mean there must be a different authorization check applied to the APO menu than to the item show page and search page views? I'm inclined to add users (or their staff workgroups) to the APOs they should see rather than have the administrator-role give them a blanket view of all APOs. Even if this means I'm adding workgroups to dozens of APOs.

**Comment by andrewjbtw** [comment]
I mean add them so that they can see the APOs in the menu. Not to change their membership in administrator-role. I think that membership is probably what's allowing many people to see Hydrus content in Argo.

**Comment by jmartin-sul** [comment]
> Does that mean there must be a different authorization check applied to the APO menu than to the item show page and search page views?

apparently?  i did notice a different (much smaller) set of APOs when i impersonated the group list in the description (which surprised me slightly since i'm in the super admin group).

> I'm inclined to add users (or their staff workgroups) to the APOs they should see rather than have the administrator-role give them a blanket view of all APOs. Even if this means I'm adding workgroups to dozens of APOs.

that for sure seems like the better approach to me, though yeah, could be a big pain to fix.

@andrewjbtw, in the description you mention "the registration form isn't showing all of the APOs that they should be authorized to use for registration."  can you give an example of something that should be showing up for the description's workgroup list that isn't?  (sorry if i missed it or if you already determined that's not the issue, that part was still unclear to me after re-reading the thread)

**Comment by andrewjbtw** [comment]
> can you give an example of something that should be showing up for the description's workgroup list that isn't? (sorry if i missed it or if you already determined that's not the issue, that part was still unclear to me after re-reading the thread)

The Stanford Libraries General Collections is a good example. They can see everything in that APO and it comes up in search but it's not on the APO registration menu.

**Comment by andrewjbtw** [comment]
Or it seemed like a good example. But they're not in any workgroup actually listed with a role in that APO. So they can see it because they're in administrator-role but they can't register into it because administrator-role isn't listed under that APO.

I think what the APOs in my screenshot have in common is they list one of the administrator workgroups in the APO roles.

**Comment by andrewjbtw** [comment]
Closing this in favor of simply adding new workgroups to the APOs that need them for the registration menu.
