### ISSUE TITLE
can we unpin addressable in Argo?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#275]
@drh-stanford indicates that this was a ruby 1.x issue, so maybe we can drop this constraint now that argo's on 2.x?
https://github.com/sul-dlss/argo/blob/develop/Gemfile#L3
https://github.com/sul-dlss/dor-services/pull/124

**Comment by mejackreed** [comment]
Do we even need it?

Seems it was added here: https://github.com/sul-dlss/argo/commit/7645f39bfeae1611f109bb6ddf38008c637c1885

A quick grep cannot find "addressable" anywhere in the repo

**Comment by cbeer** [comment]
It's a dor-services dependency:

https://github.com/sul-dlss/argo/blob/develop/Gemfile.lock#L16

On other projects, we pinned it because of a bad interaction with the `rdf` gem, I think, that got fixed in a later version of one of those.

**Comment by mejackreed** [comment]
@cbeer :+1:

**Comment by drh-stanford** [comment]
Yes, for context, I put a PR in dor-services here to unpin it: https://github.com/sul-dlss/dor-services/pull/124  And I'm wondering if I should put in a PR to Argo for it too...

**Comment by jmartin-sul** [comment]
ah, i bet it only ever got added directly to argo to pin it, since dor-services uses it.  that was my commit, and i remember pinning addressable, but i don't remember ever dealing with it other than to deal with that `frozen Addressable::URI` error.

**Comment by darrenleeweber** [comment]
There have been some changes in the RDF::URI from RDF.rb that diverge from Addressable::URI behavior.  If the Addressable gem is removed, it might have to be replaced with RDF::URI and then double check all the URI methods are behaving as expected.  See the RDF.rb README for release notes about how it differs from Addressable, i.e.
  - https://github.com/ruby-rdf/rdf#differences-between-rdf-10-and-rdf-11

"{RDF::URI} no longer uses the Addressable gem. As URIs typically don't need to be parsed, this provides a substantial performance improvement when enumerating or querying graphs and repositories."

**Comment by drh-stanford** [comment]
Thanks. When I remove the addressable pin, it'll pick up the 1.1.x version of `rdf` which no longer uses it, and then `webmock` can pick up the 2.3.6 or later version of `addressable` that it requires.
