### ISSUE TITLE
many objects with many files hit: end-accession : Net::ReadTimeout with #<TCPSocket:(closed)> 

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2752]
**Describe the bug**
I've noticed lately that objects with many files, mainly books or book-like objects, are frequently failing at the end-accession step with the same timeout error:

`end-accession : Net::ReadTimeout with #<TCPSocket:(closed)>`
https://app.honeybadger.io/projects/52894/faults/61477729

This seems to happen most often with books, which generally have more files than other objects because of all the page-level files.

**User Impact**
Items don't fully finish accessioning on their own. Someone has to reset this step, after which the error clears up.

**To Reproduce**
Steps to reproduce the behavior (this may not guarantee the error, but increases the probability):

1. Accession a book with > 2-300 pages (including OCR text and page-level pdf files)
2. See it hit this error at the end of accessioning

I ran two preassembly jobs recently that hit this error on multiple books. One batch was 48 books, the other was 24 books.
- Of the batch of 48, 23 hit this error (Friday night/Saturday morning)
- Of the batch of 24, 21 hit this error (last night).

**Expected behavior**
The end-accession step should complete successfully.

**Additional context**
The frequency of this error may have gone up during/after the recent Fedora workcycle. I noticed it on full book scans from course reserves but didn't report it at first because it was infrequent and I thought may have been related to the problem of Fedora disconnecting. But the latest errors seem to be specifically for this step, separate from other Fedora issues.

It may be that processing of certain steps is taking longer than before. Maybe there's a timeout limit that could be increased?

**Comment by peetucket** [comment]
It appears this robot step makes a synchronous call to dor-services-app, which means if the call takes too long, this is the likely result.

The end-accession robot call to dor-services-app: https://github.com/sul-dlss/common-accessioning/blob/main/lib/robots/dor_repo/accession/end_accession.rb#L21

The dor-services-client method: https://github.com/sul-dlss/dor-services-client/blob/main/lib/dor/services/client/workspace.rb#L29-L34

And the methods in dor-services-app that do the work: https://github.com/sul-dlss/dor-services-client/blob/main/lib/dor/services/client/workspace.rb#L29-L34

https://github.com/sul-dlss/dor-services-app/blob/main/app/services/cleanup_service.rb

I believe the solution to this is to move the cleanup into a job, which can run asynchronously and then notify the workflow when it is complete.  This is what we do for publish for example: https://github.com/sul-dlss/dor-services-app/blob/main/app/controllers/objects_controller.rb#L109-L116

**Comment by jcoyne** [comment]
I think this might be dangerous to do asynchronously, because if it takes a long time, a user might start adding new stuff into the workspace and then the job may start and delete the new content.

**Comment by peetucket** [comment]
Is there a way to add new content in Argo and have it be put into the workspace during accessioning?  You already can't open a new version until accessioning is complete.

**Comment by jcoyne** [comment]
@peetucket what's stopping people from using the workspace?  That's not mediated via versions being open or closed.  It's a free for all.

**Comment by peetucket** [comment]
That's true, though I would guess people use pre-assembly or one of the established pathways and don't go mucking around in the folder directly, but i won't invest much time in this until Andrew weights and we can discuss more...

**Comment by andrewjbtw** [comment]
I think Goobi can send data into that workspace without knowing what else is going on. My suspicion is this has been the cause of some mysterious errors in the past, if a goobi process is sent too soon after the previous one.

But I also think there is already a rename somewhere in these last steps because directories that are left behind after accessioning have suffixes like "_v1". But that might only be in the /dor/export location, not /dor/workspace or /dor/assembly

**Comment by peetucket** [comment]
I think that `_v1` stuff comes from the `reset-workspace` robot hitting this code: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/reset_workspace_service.rb  though I don't understand what the logic and workflows are.

**Comment by peetucket** [comment]
Suggested course of action for FR.  Investigate:

- [ ] sense for how often it happens (@andrewjbtw ?)
- [ ] how do we remediate when it happens (also Andrew?)
- [ ] why it might be happening (see my thoughts above as to a theory: https://github.com/sul-dlss/argo/issues/2752#issuecomment-864275507)

**Comment by peetucket** [comment]
See some linked PRs here when I started turning this into a job: sul-dlss/dor-services-app#2885, sul-dlss/dor-services-client#221, sul-dlss/common-accessioning#770

**Comment by ndushay** [comment]
long term solution (per discussion):  when we use a messaging service to communicate when steps are completed (e.g. rabbitMQ), this problem will be addressed.  Unfortunately, switching over to a messaging service is not a simple fix and will need to be part of a work cycle.

**Comment by andrewjbtw** [comment]
Would it be possible to increase the timeout limit as a short-term solution? This problem keeps occurring and my estimate on preassembly batches that I've run where I'm sending through books with page-level images and OCR is that it hits around 50% of the objects in the batch.

The process for dealing with the errors is to reset the workflow step and then it clears.

**Comment by jcoyne** [comment]
We could do this asynchronously as Pete has begun prototyping as long as we have this robot change https://github.com/sul-dlss/common-accessioning/pull/770/files#diff-e544dfb53854b51b7cc5b08acbda67a029681a43321e21129e970f418e12b05aR23 which marks it a no-op and the background job in DSA completes the workflow: https://github.com/sul-dlss/dor-services-app/pull/2885/files#diff-2730d0b3f03096d2bd235701ca05c1a7de69744fab9dd776393e938f9c9832dfR27-R30.  I think we should prioritize proceeding with these changes.

**Comment by ndushay** [comment]
@mjgiarlo see also https://app.honeybadger.io/projects/52894/faults/58687447

**Comment by peetucket** [comment]
Happened with the large object that we had to increase timeouts to get through the accessioning process: https://argo.stanford.edu/view/druid:rm242zg2446
https://app.honeybadger.io/projects/52894/faults/58687447

Could possibly increase the timeout for dor-services-client even more.... or turn into a long running job.

**Comment by peetucket** [comment]
I was able to manually get reset-workspace completed for `druid:rm242zg2446` by hitting the call directly on the common-accessioning console.  It is also pretty straightforward to make this call directly on the dor-services-app box.  If this occurs very infrequently, we could tackle manually when needed.  See https://github.com/sul-dlss/dor-services-app/wiki/Investigating-timeouts-from-large-objects-(many-files)

Something like this on DSA:

```
ResetWorkspaceService.reset(druid: 'druid:rm242zg2446', version: 1)
```

**Comment by justinlittman** [comment]
@andrewjbtw This is ready for testing.

* https://github.com/sul-dlss/dor-services-app/pull/4271
* https://github.com/sul-dlss/common-accessioning/pull/1011
* https://github.com/sul-dlss/dor-services-client/pull/310
