### ISSUE TITLE
Modsulator job should not retry when encountering incorrectly formatted druids in the input

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2789]
**Describe the bug**
Bulk metadata uploads in Argo accept input files as XLSX or CSV. One column in this input file asks for the druid, formatted without the "druid:" prefix. ([Modsulator field-level instructions](https://consul.stanford.edu/display/DIGMETADATA/Replayable+spreadsheet+field-level+guidelines))

When the value in this column is incorrectly formatted (includes the "druid:" prefix, or is not a druid at all), the Modsulator job hits an error because no druid can be found for that row: https://app.honeybadger.io/projects/49894/faults/80627999 

This error triggers sidekiq's automatic retries and the job keeps retrying repeatedly even though it will never succeed since there's no way to correct the data at this point in the process.

![Screen Shot 2021-07-27 at 12 29 00 PM](https://user-images.githubusercontent.com/8975583/127216064-d7d87ba2-42e9-4186-831c-14d758105c7f.png)

In the Argo interface, the job appears to be in progress and the error is not reported back to the user.

![Screen Shot 2021-07-27 at 12 28 30 PM](https://user-images.githubusercontent.com/8975583/127216098-c34fa5bb-b49d-4d02-b7a2-2f605d7431df.png)

Instead of retrying repeatedly, the job should either:

- Skip each row that has a bad value and continue to the end of the input file. Log the rows that were in error.

or

- Fail the job and report the issue back to the user. Ideally, log the rows that had the errors.

I think the first option was what used to happen before there were automatic retries, but I'm not 100% sure.

**User Impact**
Modsulator jobs appear to run indefinitely without an explanation. If users can see the error, they can correct their spreadsheet/CSV. People are left guessing what the problem is.

**To Reproduce**
1. Create a replayable spreadsheet where at least one row does not have a valid value for the druid
2. Submit this via Bulk MODS upload
3. See the error in HB and Sidekiq
4. See the job never complete in Argo

**Expected behavior**
The Modsulator job should process valid rows and report an error for invalid ones.

**Comment by peetucket** [comment]
@andrewjbtw  - I think I have fix for this in #2791 -- do you want me to deploy to stage so you can double-check there?  It should produce the first behavior you mentioned ("Skip each row that has a bad value and continue to the end of the input file. Log the rows that were in error.")
