### ISSUE TITLE
NoMethodError: undefined method `first' for nil:NilClass

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#2800]
See https://app.honeybadger.io/projects/49894/faults/79467245

**Comment by jmartin-sul** [comment]
the error is on line 81 here:
https://github.com/sul-dlss/argo/blob/b2f4710e3388ef3611d81566ee8467da595fed9e/app/controllers/items_controller.rb#L80-L85

perhaps wrapping `@cocina.structural.isMemberOf` in `Array()` would take care of the issue?  seems like `isMemberOf` is allowed to be `nil` in cocina_models?
* https://github.com/sul-dlss/cocina-models/blob/257f92d8fdf4cf5a77359dca372f43ced6fbc53c/lib/cocina/models/dro_structural.rb#L8
* https://github.com/sul-dlss/cocina-models/blob/257f92d8fdf4cf5a77359dca372f43ced6fbc53c/lib/cocina/models/request_dro_structural.rb#L8

**Comment by peetucket** [comment]
I'm not sure what's going on here... inspecting the HB alert shows the druid and the collection that threw the alert, and the data looks fine in that case (so the collection trying to be removed doesn't exist in this item, but that shouldn't throw an exception):

```
druid='druid:bv192kx5477'
collection = 'druid:ww480dh6613'
object_client = Dor::Services::Client.object(druid);
@cocina = object_client.find;
@cocina.structural.isMemberOf
=> ["druid:gs991hn1189"]

# this works fine
@cocina.structural.isMemberOf - [collection]
```

**Comment by peetucket** [comment]
We can certainly wrap in an array though just in case a nil is possible.

**Comment by peetucket** [comment]
Actually in writing a test for this it looks like 

`#/components/schemas/DROStructural does not allow null values`

and 

`#/components/schemas/DROStructural/properties/isMemberOf does not allow null values

So it is not clear how the data came into that state.  Perhaps this object had bad data that was now corrected?

**Comment by peetucket** [comment]
Ahh, but the `isMemberOf` can just be missing (not nil)...so maybe that is a thing to test

**Comment by peetucket** [comment]
See #2804 for a possible fix
