### ISSUE TITLE
Unable to open APO druid:qp256sh2346 for modification

### ISSUE THREAD

**Issue by caaster** [sul-dlss/argo#2810]
**Describe the bug**
When I try and open https://argo.stanford.edu/view/druid:qp256sh2346 for modification, after I click the "Open version" button - the APO is not in an opened state.

**User Impact**
I need to add an additional workgroup to this APO so that people in the workgroup can access the content in this APO via Argo, and complete their associated high-priority, time sensitive tasks

**To Reproduce**
1. Go to 'https://argo.stanford.edu/view/druid:qp256sh2346'
2. Click on 'Open for modification'
3. Click on 'Open Version'
4. See error - APO is not in Opened state as expected

**Expected behavior**
APO should be in Opened state as expected, so that I can edit the APO and add an additional workgroup

**Screenshots**
Self explanatory

**Additional context**
No other info needed afaik

**Comment by ndushay** [comment]
@caaster what if you click "Edit APO" instead on the left nav?

![image](https://user-images.githubusercontent.com/96775/132576500-51eb34c8-54d9-4d8b-81d2-0bc2b24fe4bf.png)

Also, maybe it was because I clicked "Edit APO" but ... I think the object is now in an open state?

Maybe everything was mysteriously slow?

I dunno.  I just hope it's fixed.  :-)

**Comment by ndushay** [comment]
Maybe you were doing this just as dependency updates were going in?  I couldn't deploy them to prod yesterday.

**Comment by ndushay** [comment]
Also, I see this in Honeybadger for the object in question:  

```
Dor::Services::Client::UnexpectedResponse: Unprocessable Entity: 422 ({"errors":[{"status":"422","title":"Unable to open version","detail":"Object already opened for versioning"}]})
```

**Comment by caaster** [comment]
Sure, I could have clicked on Edit APO -- but until I opened a new version and closed it, my Edit APO changes would not be saved.

That said, since you successfully opened the druid @ndushay - I was able to edit the APO, add the workgroup, and close the APO. So this seems fixed.
