### ISSUE TITLE
Most recently edited modal pops up after clicking Republish button and can't be closed

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2832]
**Describe the bug**
Under some circumstances, clicking on the "Republish" blue button on an Argo show page causes the most recently used modal to pop back up and it cannot be closed without reloading the page.

I made a video of the behavior. If you click on "Republish" without popping up any modals, everything works as expected and you just get a banner message about the republish action. But if you edit a datastream or use another modal, then the modal pops back up after you click on "Republish".

https://user-images.githubusercontent.com/8975583/137553005-08be1e4f-af7d-4d47-9922-a21ab7573460.mov

**User Impact**
This has been reported by a few users who have had to reload the page or open the druid in a new window after clicking on Republish and then not being able to close the modal.

**To Reproduce**
1. Go to an Argo show page
2. Click on a blue button that pops up a modal
3. Enter some data and submit it
4. Click republish button
5. See modal pop up again

**Expected behavior**
The Republish button should trigger a republish action in the background and reload the Argo page with a message saying the republish was successful. I believe the republish is still happening in this situation and the issue is just the modal popping up.

**Additional context**
As far as I can tell, if you open a modal but don't submit a change, this pop-up behavior will not happen. But I haven't checked that extensively. I have tested both datastream edits and other edits (such as the "open version" modal) and the modal pops up in both cases.

**Comment by jcoyne** [comment]
I think we need this change: https://github.com/sul-dlss/happy-heron/pull/1791
