### ISSUE TITLE
Help Button Icon Broken in Register APO form - Argo-stage

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#287]
![screenshot 2015-12-02 09 41 52](https://cloud.githubusercontent.com/assets/796990/11538900/ffe8d6c4-98d8-11e5-88f6-c761de47bdfb.png)

**Comment by mejackreed** [comment]
We should move this to an icon from glyphicons

**Comment by mejackreed** [comment]
Not only is image broken broken, but entire dialog doesn't open. This feature needs a rewrite.

**Comment by mejackreed** [comment]
See: https://github.com/sul-dlss/argo/issues/286#issuecomment-161512870

Broken in argo 3.x. Removing help icon across the board in favor of a better solution when needed.
