### ISSUE TITLE
Eliminate "complicated" category from Access Rights

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#288]
The specification for this facet show only the overall object rights -- World, Stanford, Citation or Dark, ignoring qualifying rules (e.g., no-download) or file-level exceptions (these were a hypothetical later enhancement with nested qualifying information).  A "complicated" category was introduced that seems to be ties to these qualifying condition, and has the undesired effect of removing them from the overall category -- world/stanford/etc -- that they actually belong in.   Eliminate the "complicated" distinction.

**Comment by jmartin-sul** [comment]
likely this ticket belongs on dor-services, since it's likely a result of the indexed value for a given object for the access rights field.

**Comment by atz** [comment]
:-1: 

The field indexed there is `rights_primary_ssi`, an intentionally single valued field.  Its point is to provide a *single* place to look for characterizing common behavior.  The 'complicated' value applies to the tiny fraction where world/stanford/dark does NOT adequately characterize it.  But this allows consuming applications to use one field for inclusion/exclusion in searches AND design behavior for 99.9925% of cases.  

While not currently widely used (or so we think, full indexing will tell), our rights metadata DSL includes expressivity for many kinds of restrictions.  We could have an object that was "world" readable restricted to a single IP, or "world" downloadable to a single IP.  Notably, these rules can be written such that no actual user/IP/agent could access them!  You propose to categorize such an object undifferentiatedly with the vast preponderance of objects that are truly world accessible.  Downstream applications would be required to use complex queries AND to know all possible future rights permutations to avoid mistakenly exposing data.  

Now, if you want to get into the details of rights for administrative purposes, where "complicated" resolves to the intersection of one of the recognizable baselines with other rules applied, we have `rights_characteristics_ssim` for that.  So for **druid:bb537hc4022**, for example:
```json
        "rights_primary_ssi": "complicated",
        "rights_characteristics_ssim": [
          "world_discover",
          "has_rule",
          "world|no-download",
          "profile:world1"
        ]
```

So my counter-proposal is to expose `rights_characteristics_ssim` as a facet if needed, or for us to generally understand that adding rules to <world> means it is categorically different than the common case.

**Comment by LynnMcRae** [comment]
The specs on consul proposed a means to address the complexity through hierarchical facets (deferred), so we'd get the summation of items in the overall world/stanford/citation/dark categories while accommodating any number of qualifying conditions.  I would have preferred that approach. The trouble with "complicated" is that you lose the distinction between world/stanford/group. I'd accept World-qualified, Stanford-qualified, Group-qualified.  Or perhaps your rights characteristics gives such a breakdown in even greater detail, which would be ok at this point if I can understand the domain of possible values and specify the vocabulary the users sees as facet values.

**Comment by LynnMcRae** [comment]
The current change from a undifferentiated "complicated" to more specific world_qualified or  stanford_qualified is a satisfactory resolution (I see this is dev, not stage ... I assume it will be part of the new prod index). If there is no more work pending here, I think we can close the issue.

**Comment by LynnMcRae** [comment]
I reindexed the complicated items in stage (duh!) and they now show the new values ....
![screen shot 2016-02-19 at 10 44 53 am](https://cloud.githubusercontent.com/assets/1824732/13185424/eac91f46-d6f5-11e5-96ad-d773cf58284d.png)
