### ISSUE TITLE
Upload CSV that updates structural metadata

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2887]
See https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/444556663/comments
There is an "Upload CSV" link in the "Content section".  When this is pushed and the user uploads a CSV file, the structure of the object should be updated.

The format of this CSV file will be specified by @andrewjbtw  as well as a list of validations.

@astridu will provide a mockup of what happens when this button is pushed an how to present any validation errors that occur.

**Comment by astridu** [comment]
I have to run this by @andrewjbtw, but looks like we could use this bootstrap component: https://mdbootstrap.com/docs/standard/plugins/file-upload/ (Accept Formats)

When user clicks the upload button:
![image](https://user-images.githubusercontent.com/42216982/145867058-60ad0f8b-03f5-4385-9caf-eb6f3f9bf658.png)

When user successfully uploads a file:
![image](https://user-images.githubusercontent.com/42216982/145867228-ac51fba1-3a92-45aa-8fcd-f33c12ce3cdf.png)

I'm not sure if this component also has any built in error UI?

**Comment by jcoyne** [comment]
@astridu should there be a submit button or does it submit as soon as they select a file?

**Comment by astridu** [comment]
If you drag and drop, it takes it automatically. If you select one from your computer, there is a button you have to click to submit it. 
![image](https://user-images.githubusercontent.com/42216982/145872536-1bb0ea86-0086-48fe-ac67-712199d99f0e.png)

**Comment by jcoyne** [comment]
@astridu that is just the button to select the file, but I'm talking about the button to submit the form.

**Comment by astridu** [comment]
If it can automatically upload when you select it or drag and drop it, that seems more efficient for the user.

**Comment by jcoyne** [comment]
@astridu that would be most efficient, but on a destructive operation like this, efficiency might not always be the best choice.

**Comment by astridu** [comment]
Let me talk to Andrew

**Comment by astridu** [comment]
Yes, we would like a submit button. Here are slightly revised sceens:

User clicks upload link and sees:
![image](https://user-images.githubusercontent.com/42216982/146618243-fc76fcea-aead-4fb6-85b9-ddeef3a2d4df.png)

User drags and drops or uploads file:
![image](https://user-images.githubusercontent.com/42216982/146618254-2d9aaf6f-f4d2-40a5-b8fe-0996de9e38fd.png)

User clicks cancel (the whole upload component goes away):
![image](https://user-images.githubusercontent.com/42216982/146618365-b22a3243-a288-4f65-954d-d44958f85681.png)

User clicks submit and encounters no errors (the green banner can either remain for certain # of seconds, or I can put an 'x' so user can make it go away):
![image](https://user-images.githubusercontent.com/42216982/146618299-1229e47e-6881-4207-b279-126782e11b8a.png)

User hits submit and encounters errors:
![image](https://user-images.githubusercontent.com/42216982/146618425-fc0065d6-9eb3-4909-a17a-24243bee4e6f.png)

**Comment by jcoyne** [comment]
@andrewjbtw what about file size.  What happens if they add a new file via the upload.  How will the size be known?

**Comment by andrewjbtw** [comment]
It's not possible to add a new file without going through the accessioning process. So an upload CSV that lists a file not already present should be rejected. At present, the CSV could only support changing settings, changing the order of resources, or removing content, which is what can be done with XML editing.

The XML editing won't stop you from adding a file but there will be an accessioning error immediately when you close the object since the file won't be found on the file system.
