### ISSUE TITLE
(bootstrap 5) "Add group" section has shifted on the Register/Edit APO form layout

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2890]
A minor change: on the Register/Edit APO form, the section for "Add group" has shifted:

Stage:

<img width="992" alt="Screen Shot 2021-12-13 at 9 44 59 AM" src="https://user-images.githubusercontent.com/8975583/145870145-72acf912-b5e8-4dbb-bfef-d5616cd7ee5f.png">

Prod:

<img width="852" alt="Screen Shot 2021-12-13 at 9 46 04 AM" src="https://user-images.githubusercontent.com/8975583/145870136-a88de249-6a56-4a87-ad22-b555e27ee33a.png">

I think the prod layout is easier to read since the form is right below the header.

**Comment by jcoyne** [comment]
@andrewjbtw it looks like the prod form was actually displaying incorrectly as it's markup is designed to support a layout like:
<img width="871" alt="Screen Shot 2021-12-13 at 1 35 04 PM" src="https://user-images.githubusercontent.com/92044/145876483-a721aec8-fe30-4f74-b440-5d29dc3930c1.png">


Is this how you want it, or do you prefer it on a line below (as it currently displays in prod).

**Comment by andrewjbtw** [comment]
All on one line actually does look better to me. We can keep it like that.
