### ISSUE TITLE
Information required about Argo's dependencies 

### ISSUE THREAD

**Issue by shubhanshu-gupta** [sul-dlss/argo#29]
I wish to run Argo as a hydra head. Please brief me more about the other dependencies which will enable me to do the same.

**Comment by atz** [comment]
The Gem dependencies are specified in the [Gemfile](https://github.com/sul-dlss/argo/blob/master/Gemfile).

While the develop branch is volatile and not currently deployable, it has a more updated [README](https://github.com/sul-dlss/argo/tree/develop).  Basically:

 - Java 1.8 (or newer) JRE (and JDK also on Mac OSX).
 - Ruby 1.9.3 (or newer).

The `rake jetty:clean` task downloads and installs the appropriate binaries for fedora and solr dependencies.

**Comment by shubhanshu-gupta** [comment]
The rake jettty:clean yields the following result for me:

rake aborted!
You are missing a solr configuration file: /home/shubhanshu/Argo/argo/config/solr.yml. Have you run "rails generate blacklight"?
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/blacklight-3.8.2/lib/blacklight.rb:67:in `solr_yml'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/blacklight-3.8.2/lib/blacklight.rb:56:in `solr_config'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/blacklight-3.8.2/lib/blacklight.rb:51:in `solr'
/home/shubhanshu/Argo/argo/lib/tasks/argo.rake:86:in `block (2 levels) in <top (required)>'
/home/shubhanshu/Argo/argo/lib/tasks/argo.rake:67:in `block in <top (required)>'
/home/shubhanshu/Argo/argo/lib/tasks/argo.rake:26:in `<top (required)>'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `block in load'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.21/lib/rails/engine.rb:425:in `block in load_tasks'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.21/lib/rails/engine.rb:425:in `each'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.21/lib/rails/engine.rb:425:in `load_tasks'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.21/lib/rails/application.rb:145:in `load_tasks'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/shubhanshu/Argo/argo/Rakefile:7:in `<top (required)>'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/bin/ruby_executable_hooks:15:in `eval'
/home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/bin/ruby_executable_hooks:15:in `<main>'


And upon doing rails generate blacklight, I get

/home/shubhanshu/Argo/argo/config/environment.rb:4:in `require': cannot load such file -- /home/shubhanshu/Argo/argo/config/environments/dor_development (LoadError)
        from /home/shubhanshu/Argo/argo/config/environment.rb:4:in `<top (required)>'
        from /home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.21/lib/rails/application.rb:103:in `require'
        from /home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.21/lib/rails/application.rb:103:in `require_environment!'                                           
        from /home/shubhanshu/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.21/lib/rails/commands.rb:25:in `<top (required)>'                                                   
        from script/rails:6:in `require'                                                                                                                                    
        from script/rails:6:in `<main>'

**Comment by atz** [comment]
```bash
cp config/environments/test.rb.example config/environments/test.rb
cp config/environments/test.rb.example config/environments/development.rb
cp config/dor.rb.example config/environments/dor_test.rb
cp config/dor.rb.example config/environments/dor_development.rb
cp config/database.yml.example config/database.yml
rails generate argo:solr
```

The generate step is not available on master branch, but it just populates `config/solr.yml` from this template: 
https://github.com/sul-dlss/argo/blob/develop/lib/generators/argo/solr/templates/solr.yml.erb
