### ISSUE TITLE
Results display issue with item in multiple collections

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#290]
This object, if displayed in a search result, shows its three collections as a comma delimited single string, but then repeats that string or each of the three occurrences, each time linked to one of the three individual collection objects.  
![screen shot 2015-12-02 at 11 36 35 am](https://cloud.githubusercontent.com/assets/1824732/11541787/055a59e2-98e9-11e5-84ef-21834b4c73f3.png)

Either display convention would be fine -- vertical or wrapped into a single comma delimited value, but there needs to be separate links for each. Would prefer each link on a new line for clarity with long collection names that might have commas.  This applies to the results displays as well as the detail disply, though there is a problem getting the detail display for this same record #289

**Comment by LynnMcRae** [comment]
From the RELS-EXT of the record in question:

<rdf:RDF xmlns:fedora="info:fedora/fedora-system:def/relations-external#" xmlns:fedora-model="info:fedora/fedora-system:def/model#" xmlns:hydra="http://projecthydra.org/ns/relations#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="info:fedora/druid:bb004bn8654">
    <hydra:isGovernedBy rdf:resource="info:fedora/druid:qv648vd4392"></hydra:isGovernedBy>
    <fedora-model:hasModel rdf:resource="info:fedora/afmodel:Hydrus_Item"></fedora-model:hasModel>
    <fedora:isMemberOf rdf:resource="info:fedora/druid:kz071cg8658"></fedora:isMemberOf>
    <fedora:isMemberOf rdf:resource="info:fedora/druid:nt028fd5773"></fedora:isMemberOf>
    <fedora:isMemberOfCollection rdf:resource="info:fedora/druid:gb045hv3517"></fedora:isMemberOfCollection>
    <fedora:isMemberOfCollection rdf:resource="info:fedora/druid:kz071cg8658"></fedora:isMemberOfCollection>
    <fedora:isMemberOfCollection rdf:resource="info:fedora/druid:nt028fd5773"></fedora:isMemberOfCollection>
  </rdf:Description>
</rdf:RDF>

druid:gb045hv3517 - The Spın̈al Tap Papers!!
druid:kz071cg8658 - The David Nadig Collection of the Revs Institute
druid:nt028fd5773 - Revs Institute

**Comment by mejackreed** [comment]
Should the links be a link to that item, or a link to a search of that item?
