### ISSUE TITLE
Display image resource properties in content section 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#2925]
Add "Height" and "Width" (see #3170 for a recent example touching this code)

Depends on #2891

Mockup: https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/444558684

**Comment by mjgiarlo** [comment]
I believe role has been done since #3170 (issue #3169).

**Comment by lwrubel** [comment]
Is it safe to assume that there will always be a height and width for images? If not, what should display in the case there is not that metadata?

**Comment by justinlittman** [comment]
Not safe to assume. Let's say leave it blank if no presentation metadata.
