### ISSUE TITLE
To support editing Cocina, the bulk descriptive metadata download should output in the form of a spreadsheet

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3009]
The bulk action to download descriptive metadata currently outputs a set of MODS XML files. As we are moving away from MODS and XML, this download should be updated to output in the format of the spreadsheet that users submit when updating metadata.

Additionally, outputting the metadata in the spreadsheet format will save multiple steps in the metadata update workflow. Currently, bulk edits of metadata involve outputting MODS and then transforming that into a spreadsheet using these tools: https://stanford-library-metadata.herokuapp.com/

@arcadiafalcone will supply the form the spreadsheet download should take.

**Comment by peetucket** [comment]
This is new functionality, not replacing existing functionality.
