### ISSUE TITLE
Add "Download CSV" of descriptive metadata for single-objects that outputs a spreadsheet

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3015]
For single objects in Argo, add an option (in the red buttons) to download a spreadsheet containing the descriptive metadata for that object. The goal is to give people an editable file that can then be uploaded directly to the object. The upload CSV will be ticketed separately.

This is intended to replace direct XML editing and to be more user-friendly than editing the Cocina JSON.

**Comment by jcoyne** [comment]
@arcadiafalcone do we have any existing code that maps MODS to the spreadsheet format?

**Comment by arcadiafalcone** [comment]
@jcoyne The closest thing for the replayable spreadsheet is here: https://github.com/sul-metadata/stanford-library-metadata/blob/main/apps/reverse_modsulator/reverse_modsulator.rb

**Comment by arcadiafalcone** [comment]
For more information see the notes and examples here: https://drive.google.com/drive/folders/17rZ7tXuJtxEtNiBZavujT9tchH7Q4tXp?usp=sharing
