### ISSUE TITLE
Add "Upload descMetadata" option for single-objects that inputs a spreadsheet 

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3016]
For single objects in Argo, add an option (in the red buttons) to upload a spreadsheet containing the descriptive metadata for that object. The download spreadsheet option has been ticketed as https://github.com/sul-dlss/argo/issues/3015 

This is intended to replace direct XML editing and to be more user-friendly than editing the Cocina JSON.

**Comment by andrewjbtw** [comment]
This option will be part of the expanded "Manage descriptive metadata" button (see #3017)
![upload-metadata](https://user-images.githubusercontent.com/8975583/153635956-fbe11c1a-6da0-428f-b37f-67d0500bbbde.png)

@arcadiafalcone will the upload spreadsheet be a subset of the replayable spreadsheet fields or should it be treated like the full spreadsheet, just with only one druid?

**Comment by jcoyne** [comment]
Can you also indicate on the design how errors should be displayed? Some of the errors that I can think of:
* No purl column was included (purl is a required field)
* No title column was included (title is a required field)
* No value was in the purl column
* No value was in the title column
* Provided a column like `title3:value`, but not `title1:value` or `title2:value`
* Provided a column like `note:parallelValue` which is not allowed because parallelValue is an array (it should be `note:parallelValue1`)

**Comment by arcadiafalcone** [comment]
Can we add the purl if not present, based on the druid?

I'm working on validation specs that will define errors.

**Comment by jcoyne** [comment]
> Can we add the purl if not present, based on the druid?

What if they have provided one, but it doesn't look right?  (e.g. `http` instead of `https`)? Should we just always ignore the purl column and just generate what we know it should be?

**Comment by arcadiafalcone** [comment]
I think that's preferable.

**Comment by astridu** [comment]
Dropdown
<img width="250" alt="image" src="https://user-images.githubusercontent.com/42216982/161172715-dd7ba6f3-3db2-4d3b-b3e8-ac821d87ff65.png">

**Comment by astridu** [comment]
Upload Cocina modal (@andrewjbtw Do you want any text on this page, or is this self-explanatory?)
https://mdbootstrap.com/docs/standard/plugins/file-upload/
<img width="913" alt="image" src="https://user-images.githubusercontent.com/42216982/161173456-5e5b2517-ae20-43f7-bde2-8dd1deea7efc.png">

**Comment by astridu** [comment]
You can also use the 'choose file' pattern since I see you've implemented that elsewhere. 
<img width="990" alt="image" src="https://user-images.githubusercontent.com/42216982/161176144-389fdc7a-b51c-4efb-98f1-0abc36c18ee7.png">

**Comment by andrewjbtw** [comment]
For the help text in the box, we have room to display “Upload Cocina descriptive metadata for Druid:aa12bb345” above the file upload prompt.

**Comment by andrewjbtw** [comment]
For error messages, if possible could we keep the modal active and display the error below the upload prompt? This would mean we’d need an ‘X’ or close button to close the modal since it would need to stick around.

**Comment by astridu** [comment]
<img width="888" alt="image" src="https://user-images.githubusercontent.com/42216982/161188752-0a428fd5-18cb-407c-b3a6-aeccb93cc479.png">
<img width="888" alt="image" src="https://user-images.githubusercontent.com/42216982/161188883-c9b8820c-cadc-42c1-af32-f986a200c5dc.png">

**Comment by jcoyne** [comment]
What should the design be if the upload is successful?

**Comment by astridu** [comment]
Do we have a pattern established for successful upload of a file or does the modal just close? It may be nice to have a "success" banner/message of some sort when the modal closes, but not necessary.

**Comment by andrewjbtw** [comment]
Current pattern on success (and error, for that matter) is to close the modal and put a banner on the top of the show page. That would work here for success since there wouldn’t be any reason to re-upload.

**Comment by arcadiafalcone** [comment]
Could we make the text "Upload Cocina descriptive metadata spreadsheet for druid:aa12bb345"?

**Comment by jcoyne** [comment]
@arcadiafalcone recently you asked for source_id to be added to the export spreadsheet.  Should the source_id in the spreadsheet be used to overwrite the source ID on the object this is uploaded to?

**Comment by arcadiafalcone** [comment]
No. The source ID should act the same way it does on the replayable spreadsheet - there for user reference and ignored for processing purposes.
