### ISSUE TITLE
Create a new show page red button for "Manage descMetadata" that combines multiple descMetadata features

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3017]
To support the multiple "button" actions needed to manage descriptive metadata, create a new red button on the Argo show page for managing descriptive metadata.

Button label: "Manage descMetadata"

Button action: The button should be like the "Manage Purl" button and open to a drop-down menu.

Menu options: The menu should include:

- Refresh descMetadata (already available)
- Digital serials form (ticketed as https://github.com/sul-dlss/argo/issues/3014, needs a label)
- Download CSV (https://github.com/sul-dlss/argo/issues/3015)
- Upload CSV (https://github.com/sul-dlss/argo/issues/3016)

**Comment by andrewjbtw** [comment]
The expanded "Manage descriptive metadata" button is now in the wireframe:
https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/461215225

![manage-metadata](https://user-images.githubusercontent.com/8975583/153629011-624e3070-cb82-4129-9932-df218c3355ec.png)

**Comment by jcoyne** [comment]
This has been completed
