### ISSUE TITLE
Can't set the default license to "none" using the APO license menu

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3018]
**Describe the bug**
The license menu on the Edit/Register APO form includes an option to select "none", meaning no license has been chosen. Choosing this option and saving the form is not having any effect. The previously selected license remains in place in the defaultObjectRights.

**User Impact**
It's not possible to remove a license when changing the APO defaults.

**To Reproduce**
1. Go to https://argo-stage.stanford.edu/apo/druid:sc012gz0974/edit
2. Choose "none" on the license menu
3. Submit the form
4. See that the license hasn't changed

**Expected behavior**
This should remove the license from the APO defaults.

**Comment by jcoyne** [comment]
I think this may
