### ISSUE TITLE
(new Argo interface) Show the default object rights on the APO page

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3022]
The default object rights should be displayed on the APO page, per Astrid's design.

<img width="635" alt="Screen Shot 2022-01-28 at 12 01 09 AM" src="https://user-images.githubusercontent.com/8975583/151509501-e164fbed-e6d2-4c5d-b0e3-43414cb00977.png">

This may come in a later phase of the Argo UI, depending on prioritization.

**Comment by andrewjbtw** [comment]
Full design: https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/446060026

**Comment by jcoyne** [comment]
@astridu what should display for "Access rights" if not in "edit mode"?

**Comment by mjgiarlo** [comment]
Should the access part also have information (if available) about the other three access-related settings: download, location, and CDL? Not sure if these were covered by the design. Could be done as follow-on work if we have design.

**Comment by andrewjbtw** [comment]
I think that will need another ticket. I hadn't expected the new rights menu + display to come in at this point in the workcycle. I think we can still account for all the values in a two-column display but it needs to be charted out.

**Comment by andrewjbtw** [comment]
If we don't go straight to the new rights display, the rights should display the values the current indexing displays for rights on show pages.
