### ISSUE TITLE
(new Argo UI) display workflow errors in the UI

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3027]
When there's a workflow error, this should be displayed above the Overview/Details grid and below the buttons:

<img width="1344" alt="Screen Shot 2022-01-28 at 10 44 11 AM" src="https://user-images.githubusercontent.com/8975583/151603770-6ae83eec-5354-41e0-8145-82d2fd88725c.png">

(This has been added to the wireframe here: https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/461215225 )

**Comment by peetucket** [comment]
Note: it looks like flash type alerts are currently displayed in the layout, which puts it above the title when on an item page.  I presume we want to move this down the page just for item detail view (which can easily be done conditionally).
