### ISSUE TITLE
(new Argo UI) Shift buttons to the left when there's no image

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3040]
In the new layout, the buttons should be aligned to the left when there's no thumbnail image. They're currently positioned where they would be if an image was present, resulting in whitespace on the left side of that part of the screen.
<img width="1367" alt="Screen Shot 2022-02-01 at 4 21 56 PM" src="https://user-images.githubusercontent.com/8975583/152073643-d37dd719-2866-446e-bd2d-23d31eb503dd.png">

@astridu's mock-up for the APO page shows an example with buttons on the left:
<img width="1367" alt="Screen Shot 2022-02-01 at 4 27 12 PM" src="https://user-images.githubusercontent.com/8975583/152073786-51bd2be1-f6f8-4ab0-a621-513bed86b32e.png">

**Comment by jcoyne** [comment]
That is for an APO. Astrid has asked for a frame with the title for an item with no thumbnail.
