### ISSUE TITLE
Move set previous catkey logic to argo

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#3057]
There is currently logic in the [catkey convenience method](https://github.com/sul-dlss/dor-services/blob/c2c7eeb84cfae6e84a7b636f2e08159838cfe699/lib/dor/datastreams/identity_metadata_ds.rb#L124-L140) that adds a previous catkey when a new catkey is set.

This logic should be applied when a catkey is changed.

Currently this logic is applied at the datastream class level in dor-services gem.  The logic needs to be moved to argo at the location where we update catkeys and needs to apply the change to the cocina model.

**Comment by peetucket** [comment]
My reading of the code (which I think I had a hand in writing) is that it already does this by detecting when the convenience method is setting a catkey on a record that already has one and the one being set is different.

Here are the tests: https://github.com/sul-dlss/dor-services/blob/main/spec/models/item_spec.rb#L204-L288

Is it not working correctly?
