### ISSUE TITLE
(new Argo UI) Display previous catkey?

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3060]
We don't have a dedicated place to store a previous catkey in the new Argo UI. One possibility would be to use the catkey row in the details grid. Or it could be left up to the Cocina display and not called out specifically in the UI grid.

Not a blocker for release but may need a brief discussion.

**Comment by jcoyne** [comment]
@andrewjbtw I believe we discussed that showing this in the cocina json model was sufficient to satisfy this.  Can this ticket be closed?

**Comment by andrewjbtw** [comment]
Yes, meant to close it Friday.
