### ISSUE TITLE
(new Argo UI) barcode entry can't be canceled

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3061]
The cancel button on the barcode entry form is not closing the form. 

https://user-images.githubusercontent.com/8975583/152443211-dc231bcf-65b7-4e20-9664-9d7ace66658a.mov

**Comment by jcoyne** [comment]
@andrewjbtw I don't think this is a problem when on this branch: https://github.com/sul-dlss/argo/pull/3055  I think @justinlittman deployed the main branch which is what you had been testing on.

**Comment by andrewjbtw** [comment]
This seems to be working in stage now.
