### ISSUE TITLE
"content" section for virtual objects shows double "druid:" prefix

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3088]
The content section for a virtual object shows the constituent druids that make up the virtual object. The links are supposed to take you to each constituent but a druid: prefix is showing twice, causing the links to be broken:

![Screen Shot 2022-02-09 at 10 20 28 AM](https://user-images.githubusercontent.com/8975583/153264928-81c1a67e-b3e2-43e1-810c-71f5bbe0b786.png)

I'm not sure whether this is supposed to be `druid:` prefixed at all or just show the druid. It probably doesn't make a difference as long as the link goes to the right page.

**Comment by jcoyne** [comment]
@andrewjbtw what is the druid of the virtual object here?

**Comment by andrewjbtw** [comment]
https://argo-stage.stanford.edu/view/druid:bf746ns6287

**Comment by jcoyne** [comment]
@justinlittman this problem is a result of changing the modeling for hasMemberOrder to be a druid rather than a resource ID with the format `kg748gk9672_1/1642a.jp2`

**Comment by edsu** [comment]
After talking to @jcoyne about this I gathered that this is something he would prefer to work out with @justinlittman.

**Comment by jcoyne** [comment]
In a zoom meeting, we discussed dropping the resource part and just having "From item druid:fm593yc9833"
