### ISSUE TITLE
NoMethodError: undefined method `description' for NilModel

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#3094]
See https://app.honeybadger.io/projects/49894/faults/80455296

**Comment by justinlittman** [comment]
I removed the agreement from `druid:bs736db1657` in QA:
```
<hydra:referencesAgreement rdf:resource="info:fedora/druid:bf024yb8975"></hydra:referencesAgreement>
```

Now the item page won't render in Argo, which means it can't be repaired.

**Comment by jcoyne** [comment]
The APO edit form edits cocina, but it you can't map to cocina, then you can't edit it. I don't know how to fix that other than edit the xml.

**Comment by jcoyne** [comment]
This looks like a problem in DSA: 

Cocina::Mapper::UnexpectedBuildError: #/components/schemas/AdminPolicyAdministrative missing required parameters: hasAgreement

**Comment by jcoyne** [comment]
@justinlittman now it is getting a 422 when calling DSA to get the versions from the object: https://app.honeybadger.io/projects/49894/faults/83976921  I'm not sure how to make this better.  What do we draw on the show page if we can't get a list of versions?  How do we know if the object is in a state to be modified or not?

**Comment by justinlittman** [comment]
@jcoyne @andrewjbtw As it currently stands, if an item is invalid (e.g., missing an agreement) or a user edits a datastream to create an invalid item, there is no way to correct this in Argo.

Correct me if I'm wrong, but that item could still be corrected from the Rails console. Is this acceptable in the interim?

**Comment by andrewjbtw** [comment]
Not sure if there is a separate ticket for this but my understanding from this morning's discussion is that we're going to look into preventing people from saving XML edits that could make an object invalid Cocina, similar to how we now prevent saving invalid MODS. If we can do that, I think it's ok to have to fall back to the console or Fedora to fix other issues that might come up outside of user editing scenarios.

**Comment by justinlittman** [comment]
Yes, that ticket is https://github.com/sul-dlss/dor-services-app/issues/3426

Closing this ticket.
