### ISSUE TITLE
 NoMethodError in catalog # show 

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#3098]
See https://app.honeybadger.io/projects/49894/faults/83990884

> NoMethodError: undefined method `classify' for nil:NilClass

This is for the APO that previously was missing an agreement. An agreement has been added and I've verified that Cocina will map without error.

**Comment by jcoyne** [comment]
See https://github.com/sul-dlss/argo/issues/3094#issuecomment-1035884898

**Comment by jcoyne** [comment]
I'm unable to reproduce this presently. It seems to be fine. https://argo-qa.stanford.edu/view/druid:bs736db1657

**Comment by justinlittman** [comment]
Yeah!
