### ISSUE TITLE
Show roles on the APO page

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3099]
https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/446060026
![apo-roles](https://user-images.githubusercontent.com/8975583/153636485-8f414dbb-d954-4a9a-b631-85694eef7a8b.png)

**Comment by jcoyne** [comment]
@astridu @andrewjbtw Does this ticket imply that we should take the "Add Groups" off of the existing APO Edit page? 

![Screen Shot 2022-02-22 at 1.42.15 PM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/f639821c-5971-475b-9b0a-5db019648f22)

**Comment by andrewjbtw** [comment]
It does, but I'd like to remove that Edit APO form when we've covered all of the actions on it rather than edit it incrementally.
