### ISSUE TITLE
Sulstats URL update

### ISSUE THREAD

**Issue by atz** [sul-dlss/argo#31]
Change SDR graph urls to use `https://sulstats.stanford.edu` instead of `http://sulstats-raw.stanford.edu`

Example:
```
https://sulstats.stanford.edu/render/?width=400&amp;height=300&amp;from=-3months&amp;target=stats.sdr.preservation.terabytes&amp;lineMode=connected&amp;title=SDR%20Preserved%20Terabytes&amp;hideLegend=true%22%20alt=%22sdr%20preserved%20terabytes%20graph%22%3E
```

Need to do the same for the indexer size, but that depends on pending whitelist of argo in webauth.

**Comment by jmartin-sul** [comment]
fixed in the configs.  fixing the link for the graphs, will commit that after lunch.

**Comment by jmartin-sul** [comment]
fixed on develop, deployed to argo-dev.  will merge back to master, tag, and deploy to prod later this evening.

**Comment by jmartin-sul** [comment]
merged to master and tagged.  deployed on argo-test.  will deploy on argo-prod tonight.
