### ISSUE TITLE
Argo indexing strict ordering

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#310]

**Comment by jmartin-sul** [comment]
total work in progress here, part of the way through writing the job to be used for testing, but haven't finished the test code and haven't started the actual code:  https://github.com/sul-dlss/argo/tree/delayed_job_groups

note to self and pushing up before winter break to make it a bit easier to remember where to pick back up in a couple weeks.

**Comment by andrewjbtw** [comment]
@jmartin-sul do you know if this is still relevant to how indexing works for Argo?
