### ISSUE TITLE
Show the pencil icon next to the "Project" row

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3103]
The pencil icon is not showing in the "Project" row in the details table on the Argo show page. The "Project" field is essentially a tag and editable using the Tags interface, but for consistency we should show a pencil next to it as well.

Note that there is a Cocina complication around the Project tag, which is in the Cocina model. Non-project tags are not in the Cocina model. I don't think that should affect the pencil icon but there is a separate discussion about Project tags that we should return to. I thought we had a ticket about the Project tag (in DSA or Cocina) that but I'm having trouble finding it.

**Comment by peetucket** [comment]
Just pop up full tags editing interface when pencil icon clicked.
