### ISSUE TITLE
show an error message if the user doesn't supply a version description for the object close (lock) action

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3109]
When closing (locking) an object, if the version description box is empty the user is sent to a 500 page. Instead, the user should be shown an error message explaining that description can't be left blank and then given the opportunity to enter the description again.

See https://app.honeybadger.io/projects/49894/faults/63481465

**Comment by jcoyne** [comment]
@andrewjbtw I suspect this is a recently introduced bug (in DSA). I don't believe that there used to be any requirement to provide a description.  Do you want to require a description?

**Comment by andrewjbtw** [comment]
I thought we required a description. It's possible this has been inconsistently enforced in our system, but I've gotten errors like `requires tag and description before it can be closed` for years. But I've also seen some druids that lack descriptions for versions and have wondered how those got made.

**Comment by justinlittman** [comment]
This requirement is in the VersionService and was present before the refactor: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/version_service.rb#L92

**Comment by jcoyne** [comment]
Oh good to know this isn't new.... i think that's good... or maybe it's bad that we've had this bug forever. 🙄
