### ISSUE TITLE
Improve contrast on the Argo show page placeholder frame

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3125]
The black text on gray background is a bit hard to read (placeholder shown if no image for an item on detail page)
<img width="278" alt="Screen Shot 2022-02-17 at 11 53 04 AM" src="https://user-images.githubusercontent.com/8975583/154560251-547d8ac5-be24-4251-8792-1b367dcedb9e.png">

**Comment by astridu** [comment]
Can we do a white box with black border?
