### ISSUE TITLE
Use and reproduction can't be cleared

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3134]
**Describe the bug**
I tried to clear the use and reproduction statement on https://argo.stanford.edu/view/druid:wm893ry9991 but it won't save if the box is empty. It will save changes, just not a blank.

I also tried to apply the APO defaults on the same druid but this did not clear the statement either. This druid is in the SDR Graveyard, which has defaults that don't include any rights statement or license. 

**User Impact**
Users have to resort to editing XML to take out the use and reproduction statement.

**To Reproduce**
1. Go to https://argo.stanford.edu/view/druid:wm893ry9991
2. Try to edit the use and reproduction statement to be blank
3. See that the statement reappears after clicking save.

**Expected behavior**
It should be possible to save a blank statement.

**Additional context**
I'm pretty sure this worked at some point before the new UI was released. I tried saving blanks in each of the new fields.

**Comment by andrewjbtw** [comment]
If the issue with applying APO defaults is separate from this, then I'll ticket that separately. I'm not sure if the problem is the saving in the Argo UI or something behind the scenes preventing that field from being cleared via Cocina-based edits. Editing the XML does work.

**Comment by jcoyne** [comment]
In the cocina-models, this is a required value, so clearing it is invalid. We must make this change in cocina-models first.

**Comment by andrewjbtw** [comment]
Has this always been required? Millions of items don't use it, including all Google books deposits. I'm surprised it's required since it shouldn't be, and surprised it's never come up before in validity checks.

**Comment by jcoyne** [comment]
It is currently omittable, but not nilable, so it can be nil initially, but it can't be set to nil once it has a value.
