### ISSUE TITLE
SetGoverningApoJob raises an error about a non-open version, just before opening a version

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#3164]
it should either just open the version or raise an error, but not both.

https://github.com/sul-dlss/argo/blob/b3c00ed5fe7aaaec89ea6d0ea71fd1bfa2ff7401/app/jobs/set_governing_apo_job.rb#L52

https://github.com/sul-dlss/argo/blob/b3c00ed5fe7aaaec89ea6d0ea71fd1bfa2ff7401/app/jobs/set_governing_apo_job.rb#L37

@andrewjbtw Which is the preferred way?

**Comment by andrewjbtw** [comment]
Opening the version is the better outcome. I think our newer bulk actions have been opening versions automatically, as does the bulk metadata upload. That's something we should make consistent once we've ported everything.
