### ISSUE TITLE
Don't display empty arrays in Cocina model descriptive metadata

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3178]
When viewing Cocina in Argo, some properties always display regardless of whether they have values or not. This makes the display harder to read and also makes it more difficult to copy the cocina for use in tests or documentation. Preferred behavior would be to display only properties with values.

Example of current display (gx929mp5413):
![image](https://user-images.githubusercontent.com/7491842/156211938-a40ac228-e0b8-4926-bd60-42ff3361f89a.png)

**Comment by ndushay** [comment]
### Notes

How do we know when empty arrays are meaningful?   Arcadia:  they are NOT meaningful in the description.

Our code is using the raw JSON coming out of rails.   

To fix this we would need to write some sort of display class or a shim or strip it out of the cocina source?

Having emptys in was a deliberate decision to make our code work better.

Possible approach:   in argo, just before display, we strip out the empties in description
