### ISSUE TITLE
Redirect users to a maintenance page during maintenance periods

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3180]
Similar to H2, redirect users to a maintenance page when Argo should be down for maintenance. 

There are enough Argo users that it is difficult to ensure that no one uses the system during a maintenance period. Occasionally, modifications to druids made during maintenance periods can cause downstream issues. It's safer if we can make the system inaccessible altogether during maintenance.

**Comment by justinlittman** [comment]
- [ ]  https://github.com/sul-dlss/operations-tasks/issues/2918 is to make the necessary Apache changes.
- [ ] https://github.com/sul-dlss/argo/pull/3207 is for the code changes.
- [ ] https://github.com/sul-dlss/DevOpsDocs/pull/560 is for the DevOpsDoc changes.
