### ISSUE TITLE
The button for "PURL" in the qa environment goes to the wrong place

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#3186]
The PURL button currently points at `https://purl-qa.stanford.edu/${druid}` but it should instead point at `https://sul-purl-stage.stanford.edu/${druid}`  We can do this because `/purl` is the same mount in qa as it is in stage.

**Comment by mjgiarlo** [comment]
Fixed by https://github.com/sul-dlss/shared_configs/commit/e2f65a426e7ab94d132f44e908e5c5a851454bc1
