### ISSUE TITLE
Use case-insensitive sorts

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3191]
Argo should use case insensitive alphabetical sorts. Many lists in Argo sort with the capital letters first, then the lower case:

- APO dropdown menu
- Argo facet lists
- Collections menu
- probably more places

It can be hard to find the term you're looking for when you're not sure it's capitalized or not.

**Comment by jcoyne** [comment]
This probably needs to be a separate field in solr that uses the LowerCaseFilterFactory.

**Comment by ndushay** [comment]
yes, facet fields are usually case sensitive and sort fields are usually NOT case sensitive.

and/or we could make more things lowercase ..

**Comment by ndushay** [comment]
This is superseded by #4188
