### ISSUE TITLE
Register Items page has broken javascript

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#320]
Reported originally by @drh-stanford here: https://github.com/sul-dlss/argo/pull/315#issuecomment-163004597

JavaScript functionality in the items registration page is broken, thus causing additional JavaScript to run.

**Comment by drh-stanford** [comment]
one console error is related to a data issue in our development fixtures  ```jquery.self-a714331225dda820228db323939889f149aec0127aeb06255646b616ba1ca419.js?body=1:9665 GET http://localhost:3000/registration/collection_list?apo_id=druid%3Aww057vk7675 500 (Internal Server Error)```

**Comment by drh-stanford** [comment]
![screen shot 2015-12-11 at 10 47 16 am](https://cloud.githubusercontent.com/assets/1861171/11752467/9776af6c-9ff4-11e5-96a4-7eb9af255e7c.png)

**Comment by mejackreed** [comment]
Yikes.. so sad we don't just use `document.title.present?`

**Comment by drh-stanford** [comment]
Hmm... it's not the same solr field as `.title` for some reason

**Comment by drh-stanford** [comment]
I removed the "MDtoolkit Form" list dropdown so the initial state for the screen looks like:

![screen shot 2015-12-11 at 11 51 45 am](https://cloud.githubusercontent.com/assets/1861171/11754046/b6e23020-9ffd-11e5-936e-3a12ae5baced.png)

**Comment by drh-stanford** [comment]
i've also made the Collection dropdown more fault-tolerant and it will show a "Unknown Collection (druid)" option if the collection registered in the APO is missing from both Solr and DOR, like so:

![screen shot 2015-12-11 at 11 54 16 am](https://cloud.githubusercontent.com/assets/1861171/11754115/09e75b56-9ffe-11e5-8a5e-a5745ecef06d.png)

**Comment by mejackreed** [comment]
Ah... `dc_title`

**Comment by drh-stanford** [comment]
it's `:dc_title_tesim` vs `:dc_title_ssi`... more mysterious

**Comment by drh-stanford** [comment]
We're seeing problems in stage. The APO and Collection pulldowns work, but the Register Item button exhibits incorrect behavior. The progress dialog is malformed and the error reporting (2nd column) is broken.

![screen shot 2015-12-16 at 10 43 36 am](https://cloud.githubusercontent.com/assets/1861171/11850527/b7f484e8-a3e2-11e5-8fc8-089c0a8a503f.png)
![screen shot 2015-12-16 at 10 44 15 am](https://cloud.githubusercontent.com/assets/1861171/11850530/bb898996-a3e2-11e5-9aee-2f81e2a3a1d9.png)

**Comment by drh-stanford** [comment]
The popup progress dialog still has broken style
