### ISSUE TITLE
Registering with a provided druid does not work

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#3203]
I'm not sure if this is a valid use case, but it looks like providing a druid no longer works:

When I put a druid on the registration form:
<img width="923" alt="Screen Shot 2022-03-07 at 12 06 16 PM" src="https://user-images.githubusercontent.com/92044/157092427-4edf564a-3532-4f64-83f0-bbf2d7a89e2d.png">

Then the registered object has a different druid from the one I provided:
<img width="711" alt="Screen Shot 2022-03-07 at 12 06 47 PM" src="https://user-images.githubusercontent.com/92044/157092437-ea2ca63d-46f7-41c3-9f8c-29691da236d5.png">

**Comment by jcoyne** [comment]
Andrew indicates that this is not a real use case, so the fix for this ticket would to not make the druid field editable on the registration form.

**Comment by andrewjbtw** [comment]
We will have to provide a new way to generate tracking sheets before we stop the registration field from being editable. That actually seems like a good case for a new bulk action, so I'll ticket that.

**Comment by andrewjbtw** [comment]
This ticket can be closed when we finish the registration form redesign.

**Comment by andrewjbtw** [comment]
Closing because I apparently meant to do that last year.
