### ISSUE TITLE
Update Create APO form to use the new multi-select access rights design for the default object rights

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3215]
The two-menu design is described in #2967

**Comment by jcoyne** [comment]
@andrewjbtw Do we want to modify the old form, or would it be okay to move this to an inline edit as in these designs? https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/446060026

**Comment by andrewjbtw** [comment]
We still need the form for new APOs. And after discussion with Astrid, I think we may need to keep the form even for editing the existing APOs. The adding/removing collections and the selecting registration workflows are both difficult to design around.
