### ISSUE TITLE
Show page takes a long time to render when there are many FileSets

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#3285]
Where "many" is > 600. 

For example http://argo.stanford.edu/view/druid:tr159nv3511 takes more than 14s to load when all the caches are warm:

 ![Screen Shot 2022-03-18 at 4.21.54 PM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/dd318a42-e30e-41fd-bd11-7e7dfc0383bf)

**Comment by justinlittman** [comment]
Might want to wait and see what happens once retrieving from postgres.

**Comment by andrewjbtw** [comment]
I'll put in some comparison druids in stage.

**Comment by jcoyne** [comment]
It looks to me like about 1/2 of the time is spent communicating with DSA:

```
puts Benchmark.measure { Repository.find(druid) }
  1.026480   0.027238   1.053718 (  4.947131)
=> nil
```

**Comment by jcoyne** [comment]
It looks like this (which is used to draw the milestones) is a pretty slow call:
```
puts Benchmark.measure { Dor::Services::Client.object(params[:id]).version.inventory }
  0.003771   0.000065   0.003836 (  3.148118)
```

**Comment by justinlittman** [comment]
Validation is expensive:
```
2.7.0 :013 > puts Benchmark.measure { Cocina::Models::DRO.new(h) }
  1.711061   0.003914   1.714975 (  1.716824)
 => nil
2.7.0 :014 > puts Benchmark.measure { Cocina::Models::DRO.new(h, false, false) }
  0.110524   0.000000   0.110524 (  0.110564)
 => nil
```

Wondering if there are some places in the code where validation can be skipped?

**Comment by justinlittman** [comment]
```
2.7.0 :017 > puts Benchmark.measure { Cocina::Models.without_metadata(cocina_with_metadata) }
  1.796796   0.000000   1.796796 (  1.796896)
 => nil
```

**Comment by justinlittman** [comment]
Also, maybe here: https://github.com/sul-dlss/dor-services-client/blob/main/lib/dor/services/client/versioned_service.rb#L45

**Comment by justinlittman** [comment]
Or we can try to speed up validation, maybe?

**Comment by jcoyne** [comment]
Could we have the validation optional in the dor-services-client for 'find'?

**Comment by peetucket** [comment]
Waiting on some optimizations being done and further testing.

**Comment by jcoyne** [comment]
Anything under 5s is pretty good. I'm closing.
