### ISSUE TITLE
It's possible to have unclosable versions

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#3286]
If you bulk open versions and do not provide a description, then try to bulk close them they will fail because they do not have a description.  It is possible to provide a description when closing a single item, but there is no mechanism for doing so on the bulk form.  If we added a description on the bulk form we would need to know if this description would overwrite or only be applied if one didn't already exist.

**Comment by andrewjbtw** [comment]
My proposal as a last resort: insert a generic version description if no description is present.

The name could be as simple as: "Version #{version number}", assuming we are able to determine the correct number.

**Comment by andrewjbtw** [comment]
To be clear, I mean insert the description when the "bulk close" runs. Users actually can supply a new version name in the close modal on the show page and we should leave that option open.

**Comment by andrewjbtw** [comment]
During planning this morning, the path we're going to pursue is to add an option to "bulk close" that will allow users to enter a description to apply to all items in the batch if they want (or need) to add one. The directions will make it clear that the description will overwrite any version description already there.

**Comment by andrewjbtw** [comment]
This should be addressed by #3493

**Comment by ndushay** [comment]
PR sul-dlss/dor-services-app/issues/3910 addresses the immediate problem of being able to close versions in DSA when description and/or "significance" is missing for the version.

There are a number of tickets to address missing data:
- sul-dlss/dor-services-app/3904 - use defaults for description and version when migrating from fedora to postgress
- sul-dlss/dor-services-app/3905 - require version tag and description fields in db 
- sul-dlss/dor-services-app/3905 - require version significance and description fields for VersionService.open
- sul-dlss/dor-services-app/3906 - require desc and significance parameters in DSA using ActiveRecord controls

**Comment by ndushay** [comment]
This is now done done.
