### ISSUE TITLE
Date facet widget says From...Through, but search is From...To

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#329]
For all the date facets UI says THROUGH, but search is TO, e.g., [2015-12-01T08:00:00.000Z TO 2015-12-02T08:00:00.000Z]

![screen shot 2015-12-09 at 12 00 58 pm](https://cloud.githubusercontent.com/assets/1824732/11697045/8dac96c4-9e6c-11e5-89c5-f461fe72ee9a.png)

An inclusive search is preferred over changing UI to TO and making user add a day.

**Comment by mejackreed** [comment]
I'm working on an update of this feature. One reason I'm inclined to change to Through is that is exactly what the Solr query is doing. So by using "To" we are actually telling the user more accurately what the feature does.

**Comment by LynnMcRae** [comment]
If we can't change the underlying query, then we have to tell the user the truth.  But we'd never design an inclusive beginning and non-exclusive end and call it a good UI choice.

**Comment by mejackreed** [comment]
So I don't think the end is non-inclusive... it just assumes that day at 8AM. The Solr `TrieDateField` we are using will only take a query specified like that. Since we are converting a less precise day to a date/time without a default time. We could set to the end of that day which may be the behavior you want?

**Comment by LynnMcRae** [comment]
I thought the 8AM was the 8 hour shift for UTC ... but yes, a query that is <= to the last millisecond of the day would do it.

**Comment by mejackreed** [comment]
Great thats what I did... https://github.com/sul-dlss/argo/pull/332/files#diff-47008aaa682de0130948b9f314652eeaR22
