### ISSUE TITLE
Improve Dublin Core view layout

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#330]
Labels on the left, values to the right for readability, like current Argo layout.  Compare View MODS layout.

![screen shot 2015-12-09 at 12 38 49 pm](https://cloud.githubusercontent.com/assets/1824732/11698204/51ef4428-9e72-11e5-8b6e-a2acd832dcf1.png)
![screen shot 2015-12-09 at 12 39 13 pm](https://cloud.githubusercontent.com/assets/1824732/11698206/51efea90-9e72-11e5-91e2-1031a96ad1da.png)
![screen shot 2015-12-09 at 12 40 08 pm](https://cloud.githubusercontent.com/assets/1824732/11698205/51efa6c0-9e72-11e5-833e-9f881ad7d447.png)

**Comment by drh-stanford** [comment]
Here are the revised stylings:

![screen shot 2015-12-16 at 4 23 46 pm](https://cloud.githubusercontent.com/assets/1861171/11857920/6e1fa86e-a411-11e5-91fd-afb30f2c1bed.png)
![screen shot 2015-12-16 at 4 23 35 pm](https://cloud.githubusercontent.com/assets/1861171/11857921/6e20a750-a411-11e5-8aa8-b13f6aaf8771.png)
