### ISSUE TITLE
Formatted workflow view, Diagram option not working

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#331]
On detail page, click on a workflow name in History (not the datastream) to see a formatted view, e.g., on https://argo-stage-b.stanford.edu/catalog/druid:bb019wf8338. 

The Diagram option at the top gets "Incomplete response received from application". This showed a graph of the workflow step dependencies and state.  Nice to have if it just needs to be stitched back in...can easily be omitted if problematic.

**Comment by drh-stanford** [comment]
The problem is that stage doesn't have graphviz installed. See https://sul-squash.stanford.edu/projects/argo/environments/staging/bugs/4

**Comment by drh-stanford** [comment]
@eefahy Erin, argo stage needs the `graphviz` package installed

**Comment by drh-stanford** [comment]
I've created SAR-3032

**Comment by drh-stanford** [comment]
graphviz is now installed in all environments, however, stage is working but prod is not.

**Comment by drh-stanford** [comment]
working in prod now.
