### ISSUE TITLE
Include access location in the structural CSV (import and export) -- and rename "rights_access" to "rights_view"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3327]
Updating the ticket for two requests:

1. add "rights_location" to the structural CSV

We need to support including a location in the structural metadata CSV. Currently you can choose "location-based" but there's no column for the actual location.

I had an idea about supporting this with just two columns but now that we're going to three selections for the access rights menu it will be more consistent to have three columns.

2. rename "rights_access" to "rights_view" since we've renamed that Cocina field.

**Comment by lwrubel** [comment]
@andrewjbtw what should the new column be named? `rights_location` or `location`?

**Comment by andrewjbtw** [comment]
For consistency with the other columns, let's go with `rights_location`.

It also looks like we should change `rights_access` to `rights_view` now that we've renamed the field. I'm happy to ticket that separately if that would be better.

**Comment by lwrubel** [comment]
I think that is simple enough to add into this ticket, but I'll let you know if it seems like it should be split out.

**Comment by ndushay** [comment]
Are these what this refers to?  I'm not finding where we import structural CSV data ...

![image](https://user-images.githubusercontent.com/96775/160905139-f5853e94-897d-4559-8a5d-ad994dbba4fe.png)


![image](https://user-images.githubusercontent.com/96775/160904988-a943393b-a707-4a33-ab70-b111e7813908.png)

**Comment by jcoyne** [comment]
Yes, those are the locations.  The Upload CSV button appears when the item is open for modification.

**Comment by ndushay** [comment]
@jcoyne - Edsu approved #3347

**Comment by ndushay** [comment]
Laura says "When I started on this issue, I was looking in Content /resources in Argo and the Download CSV / Upload CSV option. ... That’s where you’ll see the headers I was asking Andrew about in the issue."
