### ISSUE TITLE
adjust contents display on the item show page to handle long filenames

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3328]
Long filenames push the contents display on the Argo show page past the limits of the grid. Following the example of H2, we should truncate the visible filename in the contents display table so that the grid maintains a standard size. 

The filename should remain a link and users should be able to see the whole filename when they hover over the filename. Clicking on the link should continue to pop up a modal where the whole filename is visible.

**Screenshot**

This is an example made to illustrate the current problem. There are real prod filenames that push past the standard Argo width in similar ways.

![extended-contents](https://user-images.githubusercontent.com/8975583/165233693-1ff0a57b-fdb5-4bb7-8b01-1b994f0efc07.png)

**H2 example**

H2 has a hover feature that keeps filenames from breaking the grid:
<img width="1069" alt="Screen Shot 2022-04-25 at 10 29 37 AM" src="https://user-images.githubusercontent.com/8975583/165233873-02040649-7426-4a61-a631-a364abd85526.png">

**Comment by andrewjbtw** [comment]
link to stage example: https://argo-stage.stanford.edu/view/druid:st359nh5897

**Comment by jcoyne** [comment]
@andrewjbtw at narrow page widths, even short filenames are a problem:
<img width="950" alt="Screen Shot 2022-04-26 at 3 46 17 PM" src="https://user-images.githubusercontent.com/92044/165389487-f1aa4806-186a-4aea-a9dd-fa9e1657daf3.png">

The table is not an appropriate design for some screen widths. If you could specify which widths you want this to work for, that will be helpful.

**Comment by andrewjbtw** [comment]
I see I never replied on this. I think we'll have to come back to this because even desktop screen widths are variable, but I think it's reasonable for now to expect most Argo usage to be on desktops. I'm more concerned initially with the table having a consistent width.
