### ISSUE TITLE
Better error messages!

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#333]
Apparently any number of underlying conditions can result in a rather generic "Incomplete response received from application" or other not-too-helpful text.  We need the system to spill its guts more -- like stack trace information.  Cf prod. We've got nothing to hide from our in-house user base and need more information for diagnosing and making rational tickets.

**Comment by drh-stanford** [comment]
we're now sending all exceptions in stage to squash

**Comment by drh-stanford** [comment]
@jmartin-sul argo prod does not have the squash commit (4aedcf4c327fb190e045cffe30b891d9ed25ee0e ) deployed so squash isn't getting errors from prod. can you rebase and deploy when you're finished with indexing?

```
[44db16ee-2ca2-4e3d-8fa8-95fe6c1d8943] [2015-12-14 19:48:26.681] [failsafe_handler] 2015-12-14 11:48:27 -0800 - Error raised when reporting original error: (RuntimeError) You must set the :revision_file configuration if the code is not running in a Git checkout
```

**Comment by mejackreed** [comment]
Probably need prod updated with shared_configs with new api_key for squash

**Comment by drh-stanford** [comment]
the config looks almost up to date... it's missing the `DISABLE` flag so I did a PR on shared configs.

**Comment by drh-stanford** [comment]
prod is now working with squash. But our 500 errors still aren't displaying correctly. Just says ```Incomplete response received from application```

**Comment by mejackreed** [comment]
Yeah.. I think something is due to something configured weird between Passenger and Rails. Any ideas?

**Comment by drh-stanford** [comment]
The server is returning `502 Bad Gateway`

**Comment by mejackreed** [comment]
Ok.. I engaged @eefahy and at some point will get to it.
