### ISSUE TITLE
Update catkey form

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#3358]
See https://github.com/sul-dlss/cocina-models/pull/373

So that users can choose the "refresh" or "do not refresh" setting for any associated catkey.  See comments below with design.

**Comment by justinlittman** [comment]
This cannot be done until migration is completed (since nowhere to store this in Fedora).

**Comment by andrewjbtw** [comment]
I'm adding this to the design discussions with Astrid. Depending on timing, we could test this in a migrated environment in advance of the prod migration.

**Comment by andrewjbtw** [comment]
To support both

- multiple catkey entry
- designating one catkey as "refreshable" - meaning that it should be used to refresh the metadata from Symphony

the catkey entry form on the Argo item and collection show pages should be made into a modal:

<img width="571" alt="catkey-refreshable" src="https://user-images.githubusercontent.com/8975583/166501181-3f3d2520-4bb7-4ea2-8308-5386e9e7cc34.png">

In terms of interactions, all of these situations are allowed:

- no catkey at all: user can delete all of them and update
- one catkey, designated "Refresh"
- one catkey, designated "Do not refresh"
- multiple catkeys, only one designated "Refresh"
- multiple catkeys, all designated "Do not refresh"

The goals are:

- No more than one catkey should be designated "Refresh"
- Users can turn "Refresh" on or off even if there is only one catkey

The main use case for having a catkey but setting it to not refresh is the digital serials model. In this model, metadata is added in SDR that is not present in the original MARC, which is used to power the serials display in SW. Refreshing the metadata from MARC would overwrite the SDR-entered data. The "Do not refresh" setting enables users to turn refresh off for serials items while retaining the catkey association, which is needed for the releaseWF to operate correctly.

**Comment by andrewjbtw** [comment]
When the catkey is not being edited, the show page display should indicate the refresh status of any of the entered catkeys:
<img width="652" alt="catkey-refreshable-display" src="https://user-images.githubusercontent.com/8975583/166502157-16a710ec-1f45-48e0-b4fd-06829e4a862f.png">
