### ISSUE TITLE
Support Excel and ODS uploads for descriptive metadata

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3363]
For parity with current service. Downloads can remain CSV-only.

**Comment by jcoyne** [comment]
If we are to support Excel and ODS we need to know the strategy for which worksheets to import.  First one? All of them? One with a certain title?

Which versions of the Excel file format do you want to support?  Do we want/need xlsb or xlsm?  Do we want/need office365.com integration?

**Comment by arcadiafalcone** [comment]
It should be the same as the replayable spreadsheet - first sheet only, supporting xls and xlsx. I'd put Google Drive integration above office365, but neither is necessary.

**Comment by peetucket** [comment]
Modsulator is currently doing this, look at that an example.
