### ISSUE TITLE
Clarify label for descriptive metadata upload/download

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3364]
"Upload CSV" in the manage description menu may cause confusion as users could try to upload a replayable spreadsheet instead.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/161173628-1ececb91-2769-4fff-8e51-a80bde879df5.png)

**Comment by jcoyne** [comment]
When we say "cocina" we're typically talking about the JSON data model. I'm not sure these new labels clearly indicates that it is a spreadsheet that maps to cocina. This new phrasing may cause confusion in the future.

**Comment by arcadiafalcone** [comment]
Does "spreadsheet" fit after "Cocina" in the label? We'll be referring to it in general as the "Cocina spreadsheet," to distinguish it from the "replayable spreadsheet."

**Comment by andrewjbtw** [comment]
Works for me

**Comment by astridu** [comment]
yo tambien
