### ISSUE TITLE
Async rendering of techmd on show page

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#3369]
Currently, technical metadata is rendered on every show page, but hidden by a collapsed accordion. Technical metadata is only occasionally viewed. For this ticket, technical data should be loaded and rendered asynchronously only when the user expands the accordion.

The motivation for this is:
1. Reduce impact on the technical metadata server.
2. Improve rendering speed of the show page.

Please see @jcoyne to discuss approaches for authorizing the async requests without having to re-retrieve the cocina object.

**Comment by jcoyne** [comment]
Fixed by #3361
