### ISSUE TITLE
[argo/prod] Notice: Preservation client error getting content of gs729pv4864_sh.wav for druid:gs729pv4864 (version 2): Unable to reach Preservation Catalog - failed with Faraday::TimeoutError: Net::ReadTimeout with #<Socket:(closed)>

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/argo#3370]
## Backtrace

    line 62 of [PROJECT_ROOT]/app/controllers/files_controller.rb: rescue in preserved
    line 53 of [PROJECT_ROOT]/app/controllers/files_controller.rb: preserved

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/68052211)

**Comment by lwrubel** [comment]
Replicated by downloading the file from the UI; file is 1.25GB. LIkely a timeout issue.

**Comment by peetucket** [comment]
Likely due to slow client connections -- increasing timeouts may still cause issues with slow client connections.
