### ISSUE TITLE
Add bulk action for validating a Cocina descriptive metadata spreadsheet (without modifying any data)

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3373]
Outcome of a conversation with @arcadiafalcone and @astridu regarding bulk descriptive metadata upload: we should make a separate bulk action for descriptive metadata validation. This would allow people to check their metadata and get a report back on the entire sheet of druids before processing begins. 

**Details**

Bulk action menu location: Under "Generate reports"

The label should be: "Validate Cocina descriptive metadata spreadsheet"

Interaction: Provide a "submit" box to input the file.

Formats to support: Excel, ODS, CSV (same formats as the Bulk MODS upload currently accepts)

Help text: 
>**Validate a Cocina descriptive metadata spreadsheet**
>
>*Validates a Cocina descriptive metadata spreadsheet and checks problems with the metadata. Results will be available as a downloadable report.*

Implementation details for the log/report: @arcadiafalcone will provide more details on this.

**Additional information**

Validation will be part of the spreadsheet import bulk action (#3190) but that bulk action will process the druids right away. Having a separate validation action should reduce the chances of running into issue during updates because people will be able to revise their spreadsheet until it's valid beforehand.

**Comment by peetucket** [comment]
Note: if this work is done in the Argo codebase, may want to wait until #3363 is done (or coordinate the work), since that ticket is adding the gems needed to work with Excel files to Argo.  If this work is going to be done by making a call to modsulator app, that gem is already present there.
