### ISSUE TITLE
Validation specs for Cocina descriptive metadata spreadsheet upload

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3375]
Applies to #3373, #3190, #3016. This ticket describes validation and error messages for the uploaded spreadsheet, not for the Cocina JSON it generates.

**Comment by arcadiafalcone** [comment]
Failure errors (reject the spreadsheet as a whole, no further validation analysis):

Invalid file format: Only a CSV, Excel, or ODS file may be uploaded.
Druid column not found: The first column in the spreadsheet should have the header "druid" and contain valid druids.
Title column not found: At least one title column must be present.
Duplicate column headers: The header #{header} should occur only once.
Duplicate druids: The druid #{druid} should occur only once.

**Comment by arcadiafalcone** [comment]
Row processing errors (skip the row, continue validating/processing the spreadsheet):

Missing druid: Druid not present in row #{rowref}.

Invalid druid: Druid #{druid} not found.

Missing title: Druid #{druid} has no title value.

**Comment by arcadiafalcone** [comment]
Semantic/data quality errors (validate the rest of the row but do not ingest, continue validating/processing the spreadsheet):

When cell value is #NA, #REF!, #VALUE?, or #NAME?:
Value error: #{druid} has spreadsheet formula error in #{cellref}.

When cell value is 0:
Value error: #{druid} has 0 value in #{cellref}.

When date format does not match encoding:
Value error: #{druid} has invalid date format in #{cellref}.



date format does not match stated encoding (w3cdtf, edtf, iso)* - #{druid},#{cellref},Date does not match stated encoding.
parallelValue should contain at least two values - #{druid},#{cellref},Parallel value must contain multiple values.
associated name note in uniform title should match a contributor name#{druid},,Associated name in uniform title should match a contributor name.

**Comment by arcadiafalcone** [comment]
Date encodings

w3cdtf, edtf
Year:
YYYY (eg 1997)
Year and month:
YYYY-MM (eg 1997-07)
Complete date:
YYYY-MM-DD (eg 1997-07-16)
Complete date plus hours and minutes:
YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)
Complete date plus hours, minutes and seconds:
YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)
Complete date plus hours, minutes, seconds and a decimal fraction of a second
YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)

**Comment by jcoyne** [comment]
I have many questions and so as to not make this a mess, we should probably separate this out to one per ticket.

The first question I have is how do we know if a field is supposed to be encoded as a date vs a regular string? 
> When date format does not match stated encoding...
Where is the encoding stated?

> When cell value is 0
There is never a time we want "0" in a field?

> When parallelValue1 is present without sibling parallelValue2:
What if parallelValue3 (or any other than 1 and 2?) is present?

**Comment by arcadiafalcone** [comment]
Date encoding: Encoding here refers to the structure of the string, not to the data type. The encoding is stated in the metadata - event1.date1.value would have a corresponding event1.date1.encoding.value containing w3cdtf, edtf, etc.

Druid column not needed in single upload: That makes sense.

Value 0: I've never come across an instance of this being a valid value. More often it's a spreadsheet formula error.

Title: Yes, it should be in the model validation, but this is the error message to use in the validation report.

parallelValue: So long as parallelValue has a sibling, that's the main thing, regardless of the header digits.

**Comment by arcadiafalcone** [comment]
Type validation to occur in cocina-models gem. Source code validation a future consideration.

**Comment by justinlittman** [comment]
This has been broken into individual tickets, so closing.
