### ISSUE TITLE
move deployment prompt from argo to sdr-deploy

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#3383]
- [x] remove confirmation prompt in argo that makes you type `Andrew` to deploy
- [x] put same sort of prompt in sdr-deploy for now
- [x] uncomment argo from the sdr-deploy config

**Comment by jcoyne** [comment]
@jmartin-sul is #3346 part of this?

**Comment by jmartin-sul** [comment]
> @jmartin-sul is #3346 part of this?

ha, i'd forgotten about this PR, but yeah, i think so.
