### ISSUE TITLE
Move date facets to `DateRangeField`

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#339]
Rather than current `TrieDateField`. Will allow us to do things like:

```
[2000-11-01 TO 2014-12-01]
[2014 TO 2014-12-01]
```

**Comment by andrewjbtw** [comment]
@ndushay do you know if this is still relevant? If this is ultimately addressing a user-facing need, I could file a new issue for that need.

**Comment by jcoyne** [comment]
@ndushay I'm not sure we've stated what the user facing need is.

**Comment by andrewjbtw** [comment]
I think it's fair to close this at this point since the use case that went with it never made it into the ticket.
