### ISSUE TITLE
check that the filenames in a structural metadata CSV upload match actual files on Stacks or Preservation for that druid

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3396]
The structural metadata CSV has a column for filenames. We should make sure that the names entered in this column match the names of files actually accessioned for that druid. A failure to match will cause errors in the accesionWF and could result in files being taken out of the next version of the object, since that version will include only the files whose names match the metadata.

I can see a couple of ways to make sure the filenames in the CSV match files in the object:

1. Check against the previous Cocina or contentMetadata. You can't add files using a structural CSV so every file in the CSV must already have been included in the most recent version's structural metadata.
2. Check against the actual filesystem. This is more complicated because you have to check Stacks, preservation, or both depending on the "shelve" and "preserve" settings.

**Important note about removing files**

SDR's approach to file management leaves some ambiguity around removing files from the current version of an object. You can either set all three of publish/shelve/preserve to "no" or you can simply remove the file by uploading a structural CSV that does not contain a row for that file. (While datastreams still exist, you can also delete the XML.) 

The problem with removing the row for that file is that someone could accidentally remove a file by uploading an incomplete CSV and not realize it. We currently allow this with the one exception that you can't remove every file with a completely blank CSV.

The problem with setting publish/shelve/preserve to "no" is that the file will remain listed in the metadata even though you can't do anything with it. If someone comes by later and sets preserve to "yes", that is guaranteed to cause an error because the accessionWF will expect the file to be in `/dor/workspace` folder but the file won't be there. We currently allow changing all three settings to "no", and when you set the rights to an object to dark, it will create publish/shelve/preserve="no" settings for any file that was only on Stacks (where preserve was already "no").

I think we're stuck supporting both of these ways of handling removing files from an object until we can take another look at the how the workflows manage files. If we removed support for these methods, the only way to remove files would be to accession the entire object again, except for the files to be removed - possibly the most absurd removal scenario of all.

The upshot of this for validation is that:

- we should validate that the filenames in the upload CSV match files in the object
- we should not require that all files from the previous version be included in the next version

**Comment by jcoyne** [comment]
@andrewjbtw can you check that we're already doing this correctly? See https://github.com/sul-dlss/argo/blob/main/app/services/structure_updater.rb#L28

**Comment by andrewjbtw** [comment]
Confirmed that this check is already in place and I just hadn't triggered it with my earlier testing.
