### ISSUE TITLE
Bulk actions for large batches hit error in browser

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3413]
**Describe the bug**
When I submit a large batch for a bulk action, I see an error message in the browser. The bulk action actually does start running, but in stage I see a page like this after pressing submit:

<img width="1039" alt="Screen Shot 2022-04-07 at 8 55 52 AM" src="https://user-images.githubusercontent.com/8975583/162246394-06463353-ab1a-41bd-9ad1-c7155d4e1169.png">

In production, I may not see an error at all. Instead, my browser continues to show the "new bulk action" form even after the action has been submitted.

I haven't seen a honeybadger error when this issue happens. I'm also not sure how large a batch has to be to trigger it. I've generally seen it for lists of druids larger than 1000.

**User Impact**
It could lead someone to submit a bulk action twice, not realizing that it had already started running.

**To Reproduce**
1. Go to bulk actions
2. Submit a list of 1000+ druids. It doesn't seem to matter which bulk action runs as long as it's not a CSV one.
3. See either the error message or see that the browser stays on the bulk action form.

**Expected behavior**
Submitting a bulk action should take the browser back to the list of bulk actions.

**Comment by jcoyne** [comment]
I was able to duplicate this.  I noticed that it appeared to work on the application as I see the job is created and is working.  I see this 302 status in the logs:
```
I, [2022-04-07T10:26:47.572454 #32767]  INFO -- : [37e38cd0-f014-46a8-9b37-76e533d685de] method=POST path=/bulk_actions/reindex_job format=turbo_stream controller=BulkActions::ReindexJobsController action=create status=303 duration=33.10 view=0.00 db=6.91 location=https://argo-stage.stanford.edu/bulk_actions
```
But the browser is getting a 500 status error, which leads me to believe it's a load balancer issue:
<img width="1610" alt="Screen Shot 2022-04-07 at 12 29 26 PM" src="https://user-images.githubusercontent.com/92044/162262221-c3c20db0-5a38-4622-9d13-26b4e0e9416b.png">

**Comment by jmartin-sul** [comment]
Did a bit of troubleshooting today, and we observed:
* i reliably reproduced this with the reindexing job using a search that had 1750 results.  a reindexing job created from search with 143 results did not encounter the problem.
* according to the argo logs, the 303 redirect is returned immediately after the user successfully submits the job, before the job actually starts performing work, and is independent of the load that the job puts on argo or the rest of the system.
* to further disentangle that, i shut down argo's sidekiq workers, and submitted two 1750 druid reindexing jobs from a search result.  in both cases the same behavior occured (job submitted successfully according to logs, rails app logs show 303 redirect response from `POST` to bulk action create URL, argo stage responds to user request with a 500).  once i restarted the sidekiq workers, both jobs were picked up by stage-b, and worked off over the course of a few minutes.  the logs showed `RemoteIndexingJob` working through the druids, with negligible additional load on argo based on eyeballing `htop`.  both reindexing jobs completed without error.

so, it seems like argo is doing something wonky in its response that isn't apparent from the rails logs, or maybe there's some mismatch in expectations in interaction between argo sending a response and the load balancer passing it along.

i think the next things i'd try would be looking at the apache logs on the responding argo node for clues, and looking at... whatever logs might be relevant (🤷)... on the LB.

unassigning and moving back to ready for next week's FR.

**Comment by jmartin-sul** [comment]
picked this back up, paired a bit w/ @tallenaz  and @edsu, maybe have a solution: https://github.com/sul-dlss/argo/pull/3471

co-assigned @edsu, as first responder, in case there's more to do on this tomorrow, since i won't be able to work on it any more for the rest of the week.
