### ISSUE TITLE
Descriptive upload validation: title header

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#3439]
For both individual and bulk descriptive upload, at least one title column must be present.

When not present, "Title column not found" should be reported.

refs #3375

**Comment by arcadiafalcone** [comment]
titleN.value or titleN.structuredValueN.value with type = "main title" or "title".

**Comment by peetucket** [comment]
Is it safe to assume you wouldn't have a `title2:value` if you didn't have a `title1:value` ?  In other words, if `title1:value` and `title1.structuredValue1.value` is missing, is this sufficient to trigger an error?  Also, can you provide an example of what the "type" means for column headers?  I'm just trying to build some example CSVs to validate against in the spec (e.g. like this: https://github.com/sul-dlss/argo/blob/main/spec/services/description_validator_spec.rb#L10)

**Comment by peetucket** [comment]
Will do something like this : ```title1.value || (title1.structureValue1.type && title1.structureValue1.value)```
