### ISSUE TITLE
Descriptive upload validation: Validate cell values

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#3444]
For both individual and bulk upload:
* When cell value is #NA, #REF!, #VALUE?, or #NAME?, report "Value error: #{druid} has spreadsheet formula error in #{header}."
* When cell value is 0, report "Value error: #{druid} has 0 value in #{header}."

refs #3375

**Comment by justinlittman** [comment]
blocked by #3363

**Comment by peetucket** [comment]
Wait for https://github.com/sul-dlss/argo/pull/3477 as this PR has updates the class that this will be added to.
