### ISSUE TITLE
License facet should be built from rightsMetadata, not defaultObjectRights

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#345]
The facet values all come from APO defaultObjectRights and actual object license information is not indexed.  We want this from rightsMetadata only, not from objectDefaultRights as well. You can tell because the license facet disappears if you facet to Object Type = item, but not for Object Type = admin Policy

**Comment by drh-stanford** [comment]
This is an issue with `dor-services`... it gets the data from `defaultObjectRights` because it's assuming the item is an *APO*. Need to handle case when item is a regular item.

https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/models/editable.rb#L176-L180

**Comment by LynnMcRae** [comment]
To be clear, even an APO could have rightsMetadata that we'd want indexed (would always be Dark since we don't publish APOs). We never want the values from defaultObjectRights mixed in since they are only default settings, not active rights.  So be sure DOR Services wasn't limited here to APOs for some other reason (the APO form editing of default object rights?) and it was just poorly named.

**Comment by drh-stanford** [comment]
Right now, the `use_license_machine` field is generated by `Editable` here: https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/models/editable.rb#L52

My plan is to migrate that code to `RightsMetadataDS`

**Comment by drh-stanford** [comment]
See PR https://github.com/sul-dlss/dor-services/pull/142

**Comment by drh-stanford** [comment]
@LynnMcRae is there anyway in Argo to edit the `rightsMetadata` other than editing the XML directly?

**Comment by LynnMcRae** [comment]
@drh-stanford not really, or kinda sorta ... apart from resetting rights from APO (bulk update) there's a Set Rights button/bulk update but that only affects the core discover/read "access" rights portion. We'd like to introduce simple remediation tools for copyright, use&reproduction and licensing statements as well. That they are all smooshed up in one rightsMetadata schema a la METS/premis, and use/license further entangled under <use>, might have seemed like a good idea at the time -- they are often managed together -- it's better we starting thinking of them as more distinct albeit related.

**Comment by drh-stanford** [comment]
ok, that's consistent with what I'm seeing in the code. `dor-services` is smart about `defaultObjectRights` for APOs but that code hasn't yet been applied to `rightsMetadata`, so tools to edit/remediate `rightsMetadata` will need some to do some refactoring. The PR for this issue will correct only the indexing of the License facet.

**Comment by drh-stanford** [comment]
The PR for dor-services is merged. @jmartin-sul I'm not sure what the next steps are with this. did you want to wait to pull a new dor-services to see what other issues we might have with the index before we reindex again?

**Comment by jmartin-sul** [comment]
interesting question, hadn't thought about it... i guess i was planning to try and index the things that seem to be missing, before doing a full reindex, so maybe let's wait till the next full reindex?  that might be in january, at this point.

**Comment by drh-stanford** [comment]
@jmartin-sul  do we have plans to reindex again?

**Comment by jmartin-sul** [comment]
yes, last week i'd planned to start a full reindex either today or tomorrow, thanks for the reminder...

**Comment by jmartin-sul** [comment]
finally started a reindexing run last night on argo-prod-b.  my very rough estimate is that it'll take around another 40 to 45 hours.  there are more indexing errors than usual, it seems mostly timeouts for specific druids.  it should be easy enough to identify those for further investigation and reindexing attempts based on `log/indexer.log`.  there were just under 500 errors with about 15% processed, so should be just under 4000 errors if we keep that pace up.

**Comment by jmartin-sul** [comment]
the reindex finished, but had enough errors that i think it should be re-run once those errors have been investigated and fixed.  see issue #491.
