### ISSUE TITLE
Error showing embargoed item

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#346]
https://argo-dev.stanford.edu/catalog/druid:bs277kf6370

Can't show any embargoed item in stage w/o generic "Incomplete information received from application"

![screen shot 2015-12-10 at 3 40 16 pm](https://cloud.githubusercontent.com/assets/1824732/11731952/57a27b64-9f54-11e5-8d31-d79f12c2dfc8.png)

**Comment by mejackreed** [comment]
@LynnMcRae Can an item have more than one embargo release date?

**Comment by LynnMcRae** [comment]
@mejackreed Only one embargo will exist.  Just FYI, embargo is one of two automated rights management needs. They are handled by a nightly job invoking DOR embargoable services using information in the embargoMetadata datastream. This is typically just a matter of replacing the embargo-based rights with a set of post-embargo rights. The one more complicated use-case is ETDS -- an ETD might have an explicit student embargo of, say, 6 months, but an imposed stanford-only for 2 years based on a choice to limit visibility to 20%/snippet in Google (needs revisiting since we're no longer sending ETDs to Google). There's also an in-principle/by-policy 50 year timeout on "dark" materials, but I think we can leave that for a later sprint :)
