### ISSUE TITLE
Don't show the "manage serials" option on collection objects

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3460]
Only items can be used with the digital serials model. Collection pages currently show the "manage serials" option under the "manage description" menu so that link should be removed.

**Comment by ndushay** [comment]
@andrewjbtw - can you give an example collection record that shows this option?   It seems to be conditional upon there being a catkey (?)  -- does that ever happen for collection records?

**Comment by ndushay** [comment]
https://argo.stanford.edu/view/druid:bb810ym7436 ?
