### ISSUE TITLE
Spreadsheet upload: title note disappears on roundtrip

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3467]
Tested in stage - bc663tz5987

Source cocina snippet:
```
{
    "title": [
        {
            "structuredValue": [],
            "parallelValue": [],
            "groupedValue": [],
            "value": "Title 1",
            "identifier": [],
            "note": [
                {
                    "structuredValue": [],
                    "parallelValue": [],
                    "groupedValue": [],
                    "value": "Title 1 note",
                    "identifier": [],
                    "note": [],
                    "appliesTo": []
                }
            ],
            "appliesTo": []
        },
```
Round trip:
```
{
    "title": [
        {
            "structuredValue": [],
            "parallelValue": [],
            "groupedValue": [],
            "value": "Title 1",
            "identifier": [],
            "note": [],
            "appliesTo": []
        },
```
[spreadsheet_upload_test.xlsx](https://github.com/sul-dlss/argo/files/8476819/spreadsheet_upload_test.xlsx)

**Comment by jcoyne** [comment]
@arcadiafalcone in the original spreadsheet you specified `:` as the path separator, but in the sample spreadsheet it uses `.`.  Which is correct?

**Comment by arcadiafalcone** [comment]
It should be `.`.

**Comment by jcoyne** [comment]
The `associated name` also needs to have an associated contributor: https://github.com/sul-dlss/dor-services-app/blob/12056ac8c1deed14eea2c927c724545dab7ffce7/app/services/cocina/to_fedora/descriptive/name_title_group.rb#L22-L25

I think that the best way to test is to download a spreadsheet and then make changes to it without adding new columns.
