### ISSUE TITLE
Upload descriptive spreadsheet for single object should close modal when successful

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3474]
Currently a successful single upload leaves the modal open with only a "Cancel" button:
![image](https://user-images.githubusercontent.com/7491842/163232371-5cea5411-8aa8-4fb2-b0ac-109d0f8f55b8.png)

If the upload is successful with no error messages, the modal should close and banner message indicating success should display. @andrewjbtw will provide banner text.

**Comment by jcoyne** [comment]
Fixed by #3483
