### ISSUE TITLE
register_agrement_spec reported as flaky in circleci

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#3481]
I frequently see failures in circle (and locally) for `spec/features/register_agreement_spec.rb`

```
Failure/Error: expect(page).to have_text 'Agreement created', wait: 20
  expected to find text "Agreement created" in "We're sorry, but something went wrong.\nIf you are the application owner check the logs for more information."
./spec/features/register_agreement_spec.rb:22:in `block (2 levels) in <top (required)>'
./spec/support/feature_errors.rb:24:in `block (3 levels) in <top (required)>'
./spec/support/feature_errors.rb:13:in `respond_without_detailed_exceptions'
./spec/support/feature_errors.rb:23:in `block (2 levels) in <top (required)>'
```

And CircleCI has tagged it as flakey:

![Screen Shot 2022-04-13 at 1 44 23 PM](https://user-images.githubusercontent.com/2294288/163267283-d4fe10e9-a6c6-44c1-9fe3-a2af3c2a635b.png)

**Comment by justinlittman** [comment]
Does this occur when there is a cocina models mismatch or some other problem?

**Comment by jcoyne** [comment]
Yes, this happens when the cocina models in SDR-API are ahead of Argos.
