### ISSUE TITLE
Show informative messages when replayable spreadsheet uploads fail on type validation

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3482]
**Describe the bug**
As long as the replayable spreadsheet remains in use, the error log displayed in the Argo interface should show a useful message so users can tell what happened. Ideally, the message should include a way to identify which piece of data triggered the error

Earlier today, a user submitted a spreadsheet that failed type validation on every druid but the only message reported to Argo was "Exception":
<img width="775" alt="Screen Shot 2022-04-13 at 2 14 23 PM" src="https://user-images.githubusercontent.com/8975583/163271919-70bafef5-e102-4a9e-85cf-9931df21e428.png">

There actually was useful information in the back end. The `log.txt` file (found in the logs on the Argo filesystem at `/workspace/bulk/druid:yf767bj4831/2022_04_13_19_05_50_945`) includes these lines, not shown to the user:

```
Bad Request: 400 ({"errors":[{"status":"400","title":"Bad Request","detail":"Unrecognized types in description: description.form6"}]}) for druid:cn059yy9682
```
Ideally, that message would be shown to the user. Even better would be for it to show where to find the unrecognized type in the submitted spreadsheet, such a cell reference (if available) or the actual term that was entered. Most people will not know what `description: description.form6` refers to.

**User Impact**
Users can't tell why something failed or how to fix it. It's also hard to identify if the error is actually the result of a bug, such as a missing term or typo in the term list.

**Expected behavior**
The replayable spreadsheet interface has a place to show error messages like this. I think what might have happened is that as validation has moved further into the core of the system, the messages are not coming back out to the UI.

**Additional context**
This is particularly important to show to users as the type validation is new and it may take some time to get used to seeing it happen.

**Comment by andrewjbtw** [comment]
FWIW, I can't seem to find any HB error notification for this spreadsheet. I only know what happened because Jessica reported it on Slack.

**Comment by jcoyne** [comment]
@andrewjbtw Is this still an issue? I see this when I upload an invalid desc spreadsheet:
```
2022-04-14 14:25:03 UTC Starting DescriptiveMetadataImportJob for BulkAction 1729
Line 2: Line 2: Import descriptive metadata failed Cocina::Models::ValidationError Unrecognized types in description: description.contributor1.name1.structuredValue1 for druid:bb041bm1345 (2022-04-14 14:25:03 UTC)
2022-04-14 14:25:03 UTC Finished DescriptiveMetadataImportJob for BulkAction 1729
```

**Comment by jcoyne** [comment]
Ah, this is for the APO bulk upload.

**Comment by jcoyne** [comment]
@andrewjbtw @arcadiafalcone currently the template spreadsheet defines constratints for certain fields that prevent this error (e.g. name.type), but there is no constraint in the "Physical Description (phX:form)" columns.  Should there be?

**Comment by jcoyne** [comment]
@andrewjbtw I can't duplicate this problem.  Can you give me the spreadsheet you were using?

**Comment by andrewjbtw** [comment]
Based on discussion in standup, it's not going to be possible to get back to the cell reference where the invalid data was found. But it sounds like we can get the more detailed message out to the UI in place of the generic "Exception" message.

**Comment by andrewjbtw** [comment]
This is the file that triggered the original error: [SC0407_undergraduate_admissions_recordings_minimal_mods_FOR_UPLOAD.xlsx](https://github.com/sul-dlss/argo/files/8492234/SC0407_undergraduate_admissions_recordings_minimal_mods_FOR_UPLOAD.xlsx)

I think column NS is where the issue was[?].

**Comment by jcoyne** [comment]
@andrewjbtw I was able to use that sheet to update https://argo-stage.stanford.edu/view/druid:sn705ft3744 . I used the row that was for cn059yy9682 and just changed the druid.  So I'm not sure we still have a problem.

**Comment by andrewjbtw** [comment]
Based on discussion in planning meeting, we should test this with MODS valid but Cocina invalid metadata.

**Comment by andrewjbtw** [comment]
With Arcadia's help, I made a new replayable spreadsheet that can reproduce this error: 
[valid-mods-not-cocina.xlsx](https://github.com/sul-dlss/argo/files/8498771/valid-mods-not-cocina.xlsx)

The data that's the problem here is:
| no1:note | no1:type |
| -------- | ---------|
| xyz | query

I uploaded this spreadsheet to update: https://argo-stage.stanford.edu/view/druid:bb024hc8991

The Argo UI shows just the error: "Exception"

![Screen Shot 2022-04-15 at 3 38 11 PM](https://user-images.githubusercontent.com/8975583/163649972-a221c7c2-8754-4221-a454-40c4e72f550c.png)


In the Argo bulk action logs, I see this for log.csv:
```
"Job started","2022-04-15 22:25pm
"
"Number of records","1
"
"Exception","druid:bb024hc8991
"
"Job finished","2022-04-15 22:25pm
"
"Druids loaded","0"
```

For log.txt, I see:
```
argo.bulk_metadata.bulk_log_job_start 2022-04-15 22:25pm
argo.bulk_metadata.bulk_log_user bergeraj
argo.bulk_metadata.bulk_log_input_file valid-mods-not-cocina.xlsx
argo.bulk_metadata.bulk_log_xml_timestamp 2022-04-15 22:25pm
argo.bulk_metadata.bulk_log_xml_filename valid-mods-not-cocina-MODS.xml
argo.bulk_metadata.bulk_log_record_count 1
argo.bulk_metadata.bulk_log_xml_only false
argo.bulk_metadata.bulk_log_error_exception druid:bb024hc8991
Bad Request: 400 ({"errors":[{"status":"400","title":"Bad Request","detail":"Unrecognized types in description: note1 (query)"}]}) for druid:bb024hc8991
[long additional error message not included]
argo.bulk_metadata.bulk_log_job_complete 2022-04-15 22:25pm
```

If we can get that 400 error into the Argo UI, I think that would address this ticket. The invalid term "query" appears in the message, which gives users something to look for. I think when this ticket was originally filed, the invalid term was not being included in the message.

**Comment by jcoyne** [comment]
@andrewjbtw this is ready to be tested:
![Screen Shot 2022-04-18 at 10.32.39 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/417c4e4d-2c96-441f-94ba-b104618cc5c0)
