### ISSUE TITLE
For structural file upload, display validation errors

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#3485]
To replicate, for an object with dark rights, change the file rights to world and re-upload.

Expected:
* Validation error is displayed to user.
* No HB alert.

Actual:
![image](https://user-images.githubusercontent.com/588335/163379677-24a11104-b60e-4c54-a3a2-a71693d57149.png)

https://app.honeybadger.io/projects/49894/faults/84972823

**Comment by andrewjbtw** [comment]
Should each possible structural validation error get its own ticket? I previously filed https://github.com/sul-dlss/argo/issues/3387 but I think the PR must have addressed only that specific error.

**Comment by jcoyne** [comment]
no, we do need to ensure that whenever we do a `@cocina.new(some_params)` we do catch the error.

**Comment by jcoyne** [comment]
@andrewjbtw this was caused by moving the dark validator into cocina-models. https://github.com/sul-dlss/cocina-models/issues/377
