### ISSUE TITLE
Add "Update version description" bulk action

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3493]
Add a bulk action that uses the exact same form for the UI as the "Open for modification" bulk action but that only changes the version name and description and does nothing else. This is meant to address #3286, the problem where some versions can't be closed because they have no version descriptions.

This bulk action should only run on items that are already Opened. It should not change item status.

As much as I'm loathe to keep adding bulk actions, after discussion with Astrid we concluded that this is preferable to adding version description logic to the "Close" bulk action. The Close bulk action is not meant to rename versions.

**Comment by jcoyne** [comment]
@andrewjbtw what should happen if the user adds a closed item to the list of druids?

**Comment by ndushay** [comment]
I assume "rename version" was deliberately chosen over "describe version" or "provide version description" ?

**Comment by andrewjbtw** [comment]
We could call it "Update version description". I don't want to call it something that assumes no description is there. Even though it's meant to address the bug with versions that lack description, I imagine someone might use it in other ways. Like they made a different update than they'd originally intended and are changing the version name to match.

**Comment by ndushay** [comment]
happy to use "Update version description" -- it cleaves more closely to what is in the UI now, I believe.

**Comment by ndushay** [comment]
We are going in a completely different direction to address #3286;  PR sul-dlss/dor-services-app/issues/3910 addresses the immediate problem of being able to close versions in DSA when description and/or "significance" is missing for the version.

There are a number of tickets to address missing data:
- sul-dlss/dor-services-app/3904 - use defaults for description and version when migrating from fedora to postgress
- sul-dlss/dor-services-app/3905 - require version tag and description fields in db 
- sul-dlss/dor-services-app/3905 - require version significance and description fields for VersionService.open
- sul-dlss/dor-services-app/3906 - require desc and significance parameters in DSA using ActiveRecord controls
