### ISSUE TITLE
Validate catkey input

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3512]
I'm not sure if there are rules for the form of a catkey, but if there are, we should validate the catkey on input. I was able to enter "6671606sdfdsf" as a catkey and did not see an error until I tried to refresh: 
https://app.honeybadger.io/projects/50568/faults/78580607

**Comment by andrewjbtw** [comment]
I see that we do send a different message when a catkey cannot be found in Symphony, so a validation must be taking place somewhere that distinguishes between valid catkeys that cannot be found and invalid catkeys. 

Maybe catkeys just have to be integers?

**Comment by justinlittman** [comment]
@jcoyne Can this be closed?
