### ISSUE TITLE
bulk action (cocina spreadsheet):  descriptive metadata import needs to open a new object version if object is not already open

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3522]
(reported by @arcadiafalcone )

**Describe the bug**
The bulk descriptive metadata import seems to be updating description on closed ("Accessioned") objects without doing any versioning. It looks like the update is being made (based on the events log) but since the object isn't opened or closed, the Purl isn't updated and the change isn't sent to preservation.

See for example: https://argo.stanford.edu/view/ch756cz0314 

The events log shows an update was made today but the version history doesn't indicated any change since 2018. The object should have been opened via the bulk action.

That druid was on a large import this morning where the log says all updates were made successfully: see `/workspace/bulk/DescriptiveMetadataImportJob_19028` on the Argo server.

**User Impact**
The purl and related records in Access systems will not get updated without using the versioning process and users can't tell that the druid was updated when they look at the object later. 

**Expected behavior**
Following the behavior for the replayable spreadsheet/modsulator, bulk descriptive metadata import should:

- check if the input matches what's already there - don't make the update if the input matches
- check the object status
- if the status is "Accessioned" a new version should be opened
- the version description should be `“Descriptive metadata upload from <filename>”`
 
**Additional context**
Per discussion with @arcadiafalcone, the job should also close the objects following the update but I can ticket that separately.

**Comment by ndushay** [comment]
This is about making the bulk action akin to modsulator with respect to opening the version.

**Comment by andrewjbtw** [comment]
Yes - this is the bulk action "upload a descriptive metadata spreadsheet" for the cocina-based spreadsheet. The modsulator/replayable spreadsheet operates this way currently.

**Comment by jcoyne** [comment]
I'm a bit confused as to why this is a "bug".  The versioning behavior was never specified in https://github.com/sul-dlss/argo/issues/3190

**Comment by ndushay** [comment]
- In the bulk action context, all objects to NOT need to be in the same APO, but in the modsulator context, they do. 
- in the bulk action context, updates are happening in native cocina;  in Modsulator the spreadsheet creates MODS
- here there (may be???) a merge, but in Modsulator there is no merge, just a replace.

- here we are free, but in Egypt we were slaves (sorry - Passover reference)

**Comment by peetucket** [comment]
Just to note that #3524 describes closing the version after applying the update ... it is also in the ready column, but is probably very closely related to this and may be worth doing together
