### ISSUE TITLE
Add click-to-expand functionality to display long errors in the banner message

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3523]
I'm not sure if we've always done this, but error messages in the Argo page banners are being truncated. This is preventing users from being able to see the information they need to fix the issue when the later part of the message contains that information. 

Example:

![truncated-error](https://user-images.githubusercontent.com/8975583/163869405-775be71e-540b-4d44-99c6-277dd1da2f8f.png)

If users could click to see the whole message it would split the difference between the long messages that contain user-facing information and the long messages that seem to be more like stack traces.

**Comment by jcoyne** [comment]
I believe these were truncated in the first place because long messages in the flash can overflow the cookie.

**Comment by andrewjbtw** [comment]
Oh, that's right. I remember having cookie issues in Argo a lot more often in the past. Is there a way to get the whole message without impacting the cookies?

**Comment by jcoyne** [comment]
I'm sure we can do something... I just want whomever picks up this ticket to be aware of why it's truncating.
