### ISSUE TITLE
Users are getting a "forbidden" screen when trying to reach an Upload MODS page

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3532]
Two users have reported this morning that they can no longer reach the "Upload MODS" page they previously had been able to reach. It could be doing a permissions check that previously wasn't being done.

Specifically, both users have reported the experience on different APOs:

- Go to an APO page like https://argo.stanford.edu/view/druid:xs835jp8197
- Click on the "Upload MODS" button
<img width="1335" alt="Screen Shot 2022-04-19 at 12 51 42 PM" src="https://user-images.githubusercontent.com/8975583/164084606-a0cf6d4f-d027-4c90-8700-e4bacfe842c5.png">
- Get a forbidden message

**Additional context**

Other users have reported being able to see the Upload MODS button. I believe the difference between users who can see the "Upload MODS" and users who can't is that the users who can are in the "administrator" workgroup and the users who can't are not.

I think this change may have come with this week's dependency updates because one user definitely accessed Upload MODS last Friday.

**Expected behavior**

Any user who can see an APO page should also be able to see the Upload MODS interface linked from that page.

**Comment by jcoyne** [comment]
It appears that all these groups should have manage rights:
![Screen Shot 2022-04-19 at 3.16.30 PM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/20df27dc-fbf8-4128-a088-c90ef004aaf4)

**Comment by andrewjbtw** [comment]
Could there be a hidden connection to this? https://github.com/sul-dlss/cocina-models/issues/393#event-6420921196

**Comment by andrewjbtw** [comment]
I'm not sure any other permission change has been made recently.

**Comment by jcoyne** [comment]
no, it's not that.  The problem is that `load_resource` is not working here:
https://github.com/sul-dlss/argo/blob/main/app/controllers/bulk_jobs_controller.rb#L7
