### ISSUE TITLE
Fix versioning in ApplyModsMetadata

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#3538]
Currently, ApplyModsMetadata optionally changes the version of an item (using the VersionService). However, it doesn't update the cocina object with the new version. This means that it will overwrite the changed version when performing an update.

Instead, it should mutate the cocina object with the new version. See `GenericJob.open_new_version`.

**Comment by jcoyne** [comment]
Doesn't the mods metadata service use the mods endpoint (not the update API)? I don't see why the version service result matters in this case.

**Comment by justinlittman** [comment]
Yes.
