### ISSUE TITLE
Use the descriptive title instead of the object label (i.e. the Cocina label) on tracking sheets

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3547]
Tracking sheets are usually generated by registering a druid and then pressing the "Tracking sheets" button on the registration form. This generates a PDF containing these fields:

- druid
- object label
- project name
- tags
- source id

Following the example of https://github.com/sul-dlss/dor-services-app/pull/3791 we should use the descriptive title to generate a title for tracking sheets instead of using the label.

**Why**

As discussed elsewhere (for example, https://github.com/sul-dlss/dor-services-app/issues/3760) the "label' field is never updated after registration. All places we've found where "label" is still used are places where users expect to see the title. This leads to confusion when people update a title and don't see the change reflected in the data display.

In this case, a user updated some descriptive titles after registration and expected to see the updated title when they regenerated their tracking sheets, only to see the same label.

**Comment by justinlittman** [comment]
Hint: Use Cocina::Models::Builders::TitleBuilder

**Comment by peetucket** [comment]
Looks like the tracking sheet is generated purely from Solr documents, and not pulling from the model itself (either Fedora or cocina).  So hopefully this just means tracking down the correct Solr field to pull from.  

See https://github.com/sul-dlss/argo/blob/main/app/models/track_sheet.rb#L96

**Comment by peetucket** [comment]
Found the solr field generated with `Cocina::Models::Builders::TitleBuilder` and have a PR now.
