### ISSUE TITLE
Session hangs after Impersonate

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#355]
In new stage today, press impersonate at top of page, enter just workgroup:dlss:developers and press Impersonate button. The session will not return and a new session hangs unless you clear your browsing data. This happened to me and was reproduced by DarrenH, both using Chrome.

**Comment by mejackreed** [comment]
Pretty sure this has to do with https://github.com/sul-dlss/argo/issues/321 .

**Comment by LynnMcRae** [comment]
Agreed. Typically sdr admins bypass all that, Impersonate takes us through it. dlss developers are in practically every APO in DOR

**Comment by LynnMcRae** [comment]
Closing this since it's just falling into another issue.
