### ISSUE TITLE
No way to back out of impersonate page

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#356]
You can't cancel/close/quit/leave the impersonate form with no action except via the back button. A minor  issue given its limited audience.

**Comment by mejackreed** [comment]
How would you otherwise leave that page?

**Comment by mejackreed** [comment]
Or how would you want to leave that page?

**Comment by LynnMcRae** [comment]
What are my options :)  Like any other formlet, I would expect a submit-like(i.e. Impersonate)/cancel pair of buttons. Is this a modal on an underlying page it could return to, or is context lost except for the back button? The prod impersonate is like this, so it's not parity, and only affects sdr admins, should there not be an obvious easy choice.

**Comment by mejackreed** [comment]
Ah.. this is a page, not a modal. It potentially gets wonky with the session by doing this in a modal. Maybe we can redirect back to the referrer (page clicked impersonate from)?

**Comment by mejackreed** [comment]
What should the cancel button do?

**Comment by LynnMcRae** [comment]
Makes sense it's not a modal since any underlying page might not be valid under impersonation so any positive action needs to restart the session.  Maybe cancel could just do the same, but if it can just go back to the page from whence it came, that would make the most sense.

**Comment by atz** [comment]
This seemed fixed as of my Monday demo, right?
