### ISSUE TITLE
MODS view on Argo show page shouldn't display <br /> tags

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3598]
The MODS display that pops up in Argo when you click on the MODS button 

<img width="178" alt="Screen Shot 2022-04-27 at 4 08 36 PM" src="https://user-images.githubusercontent.com/8975583/165646047-6e86fffe-ac5c-4183-8f03-bcaf680603f9.png">

shows `<br />` tags in the text, like so:

-----
<img width="1127" alt="Screen Shot 2022-04-27 at 4 08 07 PM" src="https://user-images.githubusercontent.com/8975583/165646019-5073e37f-cd73-4c99-ad8b-7516705afc64.png">

-----

Argo should render these as line breaks, which is what the Purl is doing at the same places. 

Example above taken from: https://argo-stage.stanford.edu/view/druid:bb009qd5948

**Comment by jcoyne** [comment]
I filed a ticket https://github.com/sul-dlss/mods_display/issues/107 for this issue.

**Comment by andrewjbtw** [comment]
Thanks - I wondered which code base was the relevant one here.
