### ISSUE TITLE
Remove "Fedora UI" button

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3599]
Post-migration, we can finally remove this:

<img width="178" alt="Screen Shot 2022-04-27 at 4 45 38 PM" src="https://user-images.githubusercontent.com/8975583/165648987-e34b7a81-ba22-4478-8da1-331a2acfef64.png">

**Comment by justinlittman** [comment]
We're going to re-purpose this button. Post-migration, when you click it a virus will be delivered to your computer.
