### ISSUE TITLE
Potentially move argo poster outside of codebase?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#36]
I was asked to add this in, but it doesn't seem to really make sense.

https://github.com/sul-dlss/argo/commit/7a96163c317d437e4722176d2235f622a4e4b00f

Maybe put this somewhere in the wiki? or on consul?

Might help increase the travis test times

**Comment by atz** [comment]
:+1:

**Comment by jmartin-sul** [comment]
yeah.  :+1:   this seems like an odd thing to have in the codebase.  i guess it seems like a public facing document, hence the desire to have it on github or someplace similar?  but it also seems like a weird thing to have taking up space when you clone the repo.
