### ISSUE TITLE
Recognize parallel titles as valid titles when uploading the Cocina descriptive CSV (single and bulk)

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3600]
**Describe the bug**
The Argo cocina descriptive spreadsheet upload appears to be rejecting CSVs with parallel titles. I'm trying to upload metadata with the following header row:

`source_id,title1.parallelValue1.structuredValue1.type,title1.parallelValue1.structuredValue1.value,title1.parallelValue1.structuredValue2.type,title1.parallelValue1.structuredValue2.value,title1.parallelValue2.value,title2.parallelValue1.type,title2.parallelValue1.value,title2.parallelValue2.type,title2.parallelValue2.value,note1.type,note1.value,purl`

This is a scaled down version of the descriptive spreadsheet you can obtain from downloading the descriptive metadata for https://argo.stanford.edu/view/gn988hy1229 I have not changed the title headers but I did remove many other columns to isolate the issue.

When I try to upload that spreadsheet I get the error "title column not found"
<img width="777" alt="Screen Shot 2022-04-27 at 5 38 59 PM" src="https://user-images.githubusercontent.com/8975583/165653567-e82eaa58-a128-4eae-aade-746ae994e490.png">

**User Impact**
It's not possible to update metadata that uses parallel titles.
 
**To Reproduce**
1. Go to https://argo-stage.stanford.edu/view/druid:bc217ky7586
2. Download the cocina descriptive spreadsheet for that item
3. Upload the spreadsheet you just downloaded
4. See the error

**Expected behavior**
Parallel titles should be treated as valid.

**Additional context**
There may be other title structures that Argo needs to account for when determining validity.

**Comment by jcoyne** [comment]
Is this the same as #3593?

**Comment by andrewjbtw** [comment]
I don't think so - this problem still occurs on stage even with that fix deployed. I think it's because the path in this case is

`title1.parallelValue1.structuredValue1`

instead of

`'title1.structuredValue1`
