### ISSUE TITLE
Manage serials form hits errors for items with parallel title

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3601]
**Describe the bug**
I tried to fill out the "Manage serials" form for https://argo-stage.stanford.edu/view/druid:bc217ky7586 but I get sent to a 500 page when I submit the form. The error in HB is: 

https://app.honeybadger.io/projects/49894/faults/85142442

I suspect this might be related to the item having a parallel title because updating https://argo-stage.stanford.edu/view/druid:bb016xs8671 with the same data works as expected.

**User Impact**
It's not possible to use the serials form with items that have parallel titles.

**To Reproduce**
1. Go to https://argo-stage.stanford.edu/view/druid:bc217ky7586
2. Click on Manage description
3. Choose Manage serials
4. Enter data for at least one of the "part name" or "part number" fields. You don't have to fill in every box, but you can't leave all three blank. I tried a few combinations, including:
<img width="747" alt="Screen Shot 2022-04-27 at 6 04 25 PM" src="https://user-images.githubusercontent.com/8975583/165656071-f54cadd4-bd88-4596-a9e3-cecf5fd34994.png">

5. Submit the form
6. Get redirected to the 500 error page

**Expected behavior**
The serials metadata should be added to the Cocina.

**Additional context**
This example is based on a prod object that uses the same catkey and has serials metadata: https://argo.stanford.edu/view/gn988hy1229 

The serials metadata on that prod object was added via the "Bulk MODS upload" method and then mapped into Cocina from there. I have not been able to add the serials metadata in stage using a Cocina-only approach.

**Comment by justinlittman** [comment]
@andrewjbtw Can you please specify how the title should be updated to add the serials info in this case?

**Comment by andrewjbtw** [comment]
I think that's a question for @arcadiafalcone . 

It does look like there is already a mapping from MODS. I was able to add serials metadata by using the modsulator to update this item: https://argo-stage.stanford.edu/view/druid:bb880jh1275
