### ISSUE TITLE
access rights:  when existing location-based is changed to download = none ...

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#3628]
For an item, start with this as access rights:

(**Please add to access_rights integration test**)

![image](https://user-images.githubusercontent.com/96775/166309314-e72ef50f-d5d6-4e24-bbaf-129f3edbb2ff.png)

change to download to "none" for location based:

![image](https://user-images.githubusercontent.com/96775/166309394-8eff583a-6666-41c7-8ead-6728dd4976f8.png)

And you can no longer see the location ...

**Comment by ndushay** [comment]
somewhat related to #3627

**Comment by jcoyne** [comment]
@ndushay this is the expected behavior. The location only shows if view or download is set to location.

**Comment by ndushay** [comment]
It's the expected behavior, but follow the sequence above and I believe there may be an indexing error.

**Comment by ndushay** [comment]
nope - I'm just wrong.
