### ISSUE TITLE
Include druid column in single-item descriptive metadata spreadsheet download

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3632]
Per discussion with @andrewjbtw, to make single-item spreadsheet consistent with bulk spreadsheet, and prevent issue where user tries to run single-item spreadsheet through validation and gets a failure because the druid column is not present. Druid should appear as the first column in the spreadsheet.

**Comment by andrewjbtw** [comment]
This is covered in https://github.com/sul-dlss/argo/issues/3618 which I think is merged but not deployed yet.
