### ISSUE TITLE
stop using the "editing a cell" warning that stops people from registering from the form

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3649]
When users have a cursor active in a cell, they get this warning:

<img width="486" alt="Screen Shot 2022-05-04 at 11 33 56 AM" src="https://user-images.githubusercontent.com/8975583/166817224-84cd98ee-2617-4277-af9f-42c3500b1a96.png">

I don't think it serves a purpose anymore and we should remove it. We're going to replace the form altogether soon but I've been getting feedback from users that this is interfering with their work because it's less clear how to "lock" cells now than it was before, when there was a "lock" button.

**Comment by jcoyne** [comment]
I think this will be addressed by #3610

**Comment by andrewjbtw** [comment]
Right, the overall redesign will address this. But that won't go out for a while longer.
