### ISSUE TITLE
Tags are not being added to newly registered items

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3650]
**Describe the bug**
Tags are not being assigned to newly registered items, with the exception of the project tag. If you enter any tags in the "Tags" boxes on the registration form, they are not carried over to the druids being registered.

**User Impact**
Users have to go back and add tags later.

**To Reproduce**
1. Go to the registration form
2. Fill it out, including tags in the "Tags" box
3. Register
4. See that the druids do not have the tags from the Tags box. The Project tag (in the Project box) is being included, but not the other tags.

**Expected behavior**
Tags should be assigned to the new druids.

**Additional context**
This seems to have started this morning.

**Comment by peetucket** [comment]
Likely because of changes made here: https://github.com/sul-dlss/argo/pull/3637/files  ..... looking into it

**Comment by peetucket** [comment]
Found the problem - just a small typo.  Trying to see if I can improve the testing here.
