### ISSUE TITLE
Refresh the show page after a descriptive metadata upload

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3656]
After uploading a descriptive metadata CSV on an Argo show page, the item is reindex but the show page itself isn't refreshed. This makes it look like the data hasn't changed when it actually has.

To reproduce:

1. Go to an item show page
2. Download the Cocina descriptive spreadsheet via the "Manage Description" button
3. Change something that will be visible on the show page, like the title
4. Upload the spreadsheet
5. See the "success" message
6. See that the display hasn't changed
7. Refresh the page (but don't reindex)
8. See the change in display

**Comment by peetucket** [comment]
Note: I couldn't see the new metadata showing up in localhost without re-indexing (maybe just needed to wait longer before hitting refresh).   i also just changed the title ... forcing a re-index does seem to fix it though (in #3661)
