### ISSUE TITLE
Add "back to search results" to show pages

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3657]
Add back the "back to search results" link that used to appear when you look at individual search results.

I'm not sure when the link disappeared from the top of the show pages, but it may even have been last year. I'll admit that I don't remember what it looked like, but it may have been near the "previous" and "next" links.

<img width="1339" alt="Screen Shot 2022-05-05 at 9 43 14 AM" src="https://user-images.githubusercontent.com/8975583/166974037-a837ef08-1c21-4f05-9ae9-187bae3c7290.png">

I can tag this as "design needed" if necessary, but if there's a standard Blacklight way to do this that's consistent with the current design that's probably enough to meet the need.

**Comment by justinlittman** [comment]
How about like this @andrewjbtw ?
![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/baf95b83-52d0-4b8a-ba01-109c75016c3c)

**Comment by jcoyne** [comment]
I'm pretty sure I removed that because it wasn't in the new designs (see https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/461215225). I thought that its removal was part of the new design.
