### ISSUE TITLE
Show an icon or other indication that data is being loaded when Argo lazy-loads a show page section

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3664]
A few of the show page sections now do some lazy-loading. I'm finding the delay on some pages long enough to worry that something is missing from the display. The lazy-loading has helped performance, so I think keeping it and adding an indicator would be better than making the whole page wait to load.

I'm not sure if this is a complete list, but I think these all lazy-load now:

- contents section (loads by default, and the one I'd prioritize first)
- cocina model section
- events
- technical metadata

**Comment by jcoyne** [comment]
Consider using bootstrap placeholders: https://getbootstrap.com/docs/5.1/components/placeholders/
