### ISSUE TITLE
Validate that a purl supplied on the Cocina descriptive metadata spreadsheet matches the druid for the item

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3669]
The Cocina descriptive metadata spreadsheet includes a column for the purl of the druid being updated - not to be confused with purls for related items. We should validate that when a user submits the spreadsheet with a purl column, the purl in that column matches the druid being updated.

If it turns out that we validate this already, feel free to close this ticket. But I'm not sure that we do.

Also, if the validation of the purl fails, we should return an error message to the user. 

- For the bulk upload, the message should go to the log
- For the individual item, it should be reported in the error message box on the modal

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/cocina-models/blob/main/lib/cocina/models/validators/purl_validator.rb
