### ISSUE TITLE
Replayable spreadsheet (the MODS-based one) times out when there are many (3-4000+) rows

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3680]
Reported on the dlss-aaas channel: a spreadsheet with ~4400 rows failed MODS upload with the error:

`Net::ReadTimeout with #<Socket:(closed)>`

This is an unusually large spreadsheet but not the largest set that has ever been processed before.

I checked this spreadsheet in stage and got the same result. It looks like if the initial step in processing the spreadsheet takes more than 30 minutes, then there's a timeout error. This first step may have changed recently as a result of the changes needed to make the replayable spreadsheet detect whether the resulting update would or would not change the existing data. Could the replayable spreadsheet upload now be analyzing the whole sheet initially where before it only went row by row? Or could this always have been a problem? 

I was able to upload a 2000 druid spreadsheet without an error. That whole job, including the updates, took more than 30 minutes. But no individual step took more than 30 minutes, which may be how it avoided the timeout. I'm trying to work out what's the largest spreadsheet we can currently process. I suspect it will be around 3000 rows.

**Comment by justinlittman** [comment]
Can you try this again now that cocina models released with performance improvements?

If still a problem, can you provide steps to reproduce in QA or stage?

**Comment by andrewjbtw** [comment]
I tried again and got the same error. To reproduce:

1. Go to the bulk MODS upload interface: https://argo-stage.stanford.edu/apos/druid:sc012gz0974/bulk_jobs
2. Click on "Submit new file"
3. Select this file [3500-lines.csv](https://github.com/sul-dlss/argo/files/8682923/3500-lines.csv)
4. Select "Spreadsheet input, load into objects"
5. Submit
6. Wait 30 minutes
7. See the job status of "Completed with system errors"

**Comment by justinlittman** [comment]
Here is the log:
```
argo.bulk_metadata.bulk_log_job_start 2022-05-12 18:11pm
argo.bulk_metadata.bulk_log_user bergeraj
argo.bulk_metadata.bulk_log_input_file 3500-lines.csv
argo.bulk_metadata.bulk_log_internal_error Net::ReadTimeout with #<Socket:(closed)>
argo.bulk_metadata.bulk_log_empty_response ERROR: No response from https://modsulator-app-stage.stanford.edu/v1/modsulator
argo.bulk_metadata.bulk_log_error_exception Got no response from server
argo.bulk_metadata.bulk_log_job_complete 2022-05-12 18:41pm
```

This indicates that the problem is the call to the Modsulator app timing out, so it has nothing to do with any Argo changes. I will increase the timeout.

However, it seems fragile to have such a long-running synchronous call to the Modsulator app. Possible alternatives:
* Make the call asynchronous: Modsulator provides a job token and Argo periodically checks the status of the job using the token until completed.
* Splitting the spreadsheet up into smaller pieces and calling Modsulator with a smaller piece.
* Moving the mapping into Argo so no API call is required.

**Comment by andrewjbtw** [comment]
Closing because the replayable spreadsheet will be retired.
