### ISSUE TITLE
Using the workflow grid to reset multiple errored steps is not working

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3697]
**Describe the bug**
When I click on the "reset" link from the workflow grid, I see a blue progress bar appear near the top of the Argo window but the process never finishes and now workflow steps get reset.

A typical reset link from https://argo.stanford.edu/report/workflow_grid :

<img width="1208" alt="Screen Shot 2022-05-17 at 12 09 03 PM" src="https://user-images.githubusercontent.com/8975583/168891504-7b3d6457-ba2f-446a-ac0b-fba1e100b1ef.png">

I took a video of what happens when I click the link. It's subtle but you can see a blue line extend from left to right just above the Argo header:

https://user-images.githubusercontent.com/8975583/168892087-d0fe89b6-c266-4e4f-8eb8-b7f3a6df69fb.mp4

Eventually the bar crosses the screen and nothing else happens.

**User Impact**
It's not possible to use Argo to reset multiple steps at once. You either need to open each item's show page and go to the workflow modal to reset each step one at a time, or you have to go to the workflow server itself and use a rake task or the rails console to process a batch in a loop.

**To Reproduce**
1. Go to the workflow grid link above
2. Click on the reset link - probably safest to keep trying the "end-accession" step in my screenshot above
3. See the progress bar but no other effect.

**Expected behavior**
The steps corresponding to the reset link should all be reset back to a status of "waiting", which then leads them to run again. When this works properly, the workflow grid page is reloaded and a banner appears indicating that the steps were successfully reset.

**Additional context**
I'm not sure when this stopped working. I reset batches of steps on a weekly basis so it either stopped working this week or late last week. It has not worked at all this week.

**Comment by peetucket** [comment]
Step 1:

Tried clicking the reset link for publish in -qa at https://argo-qa.stanford.edu/report/workflow_grid?f%5BobjectType_ssim%5D%5B%5D=item

Firefox developer tools shows a POST request but no headers/response/request info, and the rails log shows nothing incoming.  So perhaps the request is never being sent to the server.

**Comment by peetucket** [comment]
Replicated in stage, but seemed to see a endless loop of solr queries when I hit the reset button.  Perhaps related to the endless loop of queing seen yesterday?

**Comment by peetucket** [comment]
`byebug` in localhost shows this line https://github.com/sul-dlss/argo/blob/main/app/controllers/report_controller.rb#L49 goes into an infinite solr loop on my laptop: `ids = Report.new(params, current_user:).druids`

**Comment by peetucket** [comment]
It looks like we get stuck here: https://github.com/sul-dlss/argo/blob/main/app/models/report.rb#L200-L216 because incrementing the page doesn't appear to have an impact (i.e. in localhost I have one druid, but that one druid gets returned from solr in the response no matter what the page param is, leading to an infinite loop)

**Comment by peetucket** [comment]
Changing the `page` param is not making it through to the query generated by `SearchService` in Blacklight.

So there appears to be an issue with blacklight 7.25.1, since when we rolled back to the 7.24.0 and it started working as expected.

Suspect bug in search state in blacklight

**Comment by peetucket** [comment]
We think this is resolved by not having an infinite loop in solr from Blacklight.

If it does happen again, we need to:

1. Reboot argo
2. Throttle HB
3. Remove all of the associated events for the affected druids
