### ISSUE TITLE
bin/dor-indexer is junk, doesn't compile

### ISSUE THREAD

**Issue by atz** [sul-dlss/argo#37]
It is syntactically impossible that anything is using this file.  There's an empty if statement that gets closed, then an elsif method on its own.  Also the rescue/ends don't match up.  

Recommend deletion.

Since `dor-indexerd` runs `dor-indexer`, then I don't see that it could run either.  Also, its options handling are crude.  The help message is misleading.   

Recommend deletion for both.   These scripts are from 2012 and we get results a different way now.

**Comment by jmartin-sul** [comment]
+1

**Comment by atz** [comment]
In general, the **intent** of having argo consume the outstanding reindex event queue may be desirable.  But this we're better off scrapping this and starting over.
