### ISSUE TITLE
argo-prod-b -- Tags facet is incomplete?

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#371]
Compare lists from prod and current prod-b 
![screen shot 2015-12-15 at 11 29 04 am](https://cloud.githubusercontent.com/assets/1824732/11821621/4cce7278-a31f-11e5-967e-a82d915c7feb.png)
![screen shot 2015-12-15 at 11 29 20 am](https://cloud.githubusercontent.com/assets/1824732/11821627/4e373924-a31f-11e5-9b4d-b151f83019ae.png)

In case this is some interaction with the facet count limit, this should be another facet that shows all entries rather than goes through "more" since I imagine the hierarchical behavior is incompatible with more.

**Comment by jmartin-sul** [comment]
my first thought is to blame issue #380, though maybe that's not the whole story.

**Comment by LynnMcRae** [comment]
I think the list on the front page is being truncated by the 10-item limit which counts all levels:
![screen shot 2016-01-03 at 10 20 40 pm](https://cloud.githubusercontent.com/assets/1824732/12084444/429b58b8-b268-11e5-8445-63a2bab1b71c.png)
Can be fixed by just removing limits on the number of facets shown as it will only display the top level?

**Comment by mejackreed** [comment]
I don't think so. This is using Blacklight hierarchy, and that facet doesn't have a limit set on it. Seems like some more investigation into Blacklight hierarchy is needed.

**Comment by LynnMcRae** [comment]
Maybe the fix isn't that simple, but the clipping at 10 entries is real since the tags shown change as the search is narrowed ...
![screen shot 2016-01-04 at 9 58 56 am](https://cloud.githubusercontent.com/assets/1824732/12096614/5e2ae1e4-b2cb-11e5-92cd-52b29575e3e0.png)
![screen shot 2016-01-04 at 10 00 10 am](https://cloud.githubusercontent.com/assets/1824732/12096615/5e2cedea-b2cb-11e5-9973-9c4b96a4d3ce.png)

**Comment by drh-stanford** [comment]
I'm not able to reproduce what you're seeing in the Tag facet. This is what I see currently on argo prod b:

![screen shot 2016-01-07 at 1 32 10 pm](https://cloud.githubusercontent.com/assets/1861171/12183323/186024b0-b543-11e5-84bd-56afe530640e.png)

**Comment by drh-stanford** [comment]
I was successful in fixing this on my laptop by adding `limit: 999999` to the facet configuration for the tags field.

![screen shot 2016-01-07 at 1 47 28 pm](https://cloud.githubusercontent.com/assets/1861171/12183692/485c0268-b545-11e5-968e-81282d7ae35f.png)

However, the current Argo doesn't specify a limit, so I'm not sure what's going on exactly. Perhaps Blacklight hierarchy added a limit of 10 facets at some point.

https://github.com/sul-dlss/argo/blob/master/app/controllers/catalog_controller.rb#L67

**Comment by drh-stanford** [comment]
It looks like the source of the problem is our configuration with Solr for argo b. The main argo index doesn't have `facet.limit` defined in the defaults. (the solrconfig.xml files are significantly different btw).

![screen shot 2016-01-07 at 2 06 33 pm](https://cloud.githubusercontent.com/assets/1861171/12184076/ebda524e-b547-11e5-8f5f-896d25636441.png)

**Comment by drh-stanford** [comment]
I have a patch that would explicilty raise the facet limits in the code, but I think the configuration fix might be more appropriate.

```
--- a/app/controllers/catalog_controller.rb
+++ b/app/controllers/catalog_controller.rb
@@ -71,7 +71,7 @@ class CatalogController < ApplicationController
     # exploded_tag_ssim indexes all tag prefixes (see IdentityMetadataDS#to_solr for a more exact
     # description), whereas tag_ssim only indexes whole tags.  we want to facet on exploded_tag_ssim
     # to get the hierarchy.
-    config.add_facet_field 'exploded_tag_ssim',               label: 'Tag',                 partial: 'blacklight/hierarchy/facet_hierarchy'
+    config.add_facet_field 'exploded_tag_ssim',               label: 'Tag',                 limit: 9999, partial: 'blacklight/hierarchy/facet_hierarchy'
     config.add_facet_field 'objectType_ssim',                 label: 'Object Type',         limit: 10
     config.add_facet_field 'content_type_ssim',               label: 'Content Type',        limit: 10
     config.add_facet_field 'rights_primary_ssi',              label: 'Access Rights',       limit: 10
@@ -83,9 +83,9 @@ class CatalogController < ApplicationController
     config.add_facet_field 'current_version_isi',             label: 'Version',             limit: 10
     config.add_facet_field 'processing_status_text_ssi',      label: 'Processing Status',   limit: 10
     config.add_facet_field 'released_to_ssim',                label: 'Released To',         limit: 10
-    config.add_facet_field 'wf_wps_ssim',                     label: 'Workflows (WPS)',     limit: 10, partial: 'blacklight/hierarchy/facet_hierarchy'
-    config.add_facet_field 'wf_wsp_ssim',                     label: 'Workflows (WSP)',     partial: 'blacklight/hierarchy/facet_hierarchy'
-    config.add_facet_field 'wf_swp_ssim',                     label: 'Workflows (SWP)',     partial: 'blacklight/hierarchy/facet_hierarchy'
+    config.add_facet_field 'wf_wps_ssim',                     label: 'Workflows (WPS)',     limit: 9999, partial: 'blacklight/hierarchy/facet_hierarchy'
+    config.add_facet_field 'wf_wsp_ssim',                     label: 'Workflows (WSP)',     limit: 9999, partial: 'blacklight/hierarchy/facet_hierarchy'
+    config.add_facet_field 'wf_swp_ssim',                     label: 'Workflows (SWP)',     limit: 9999, partial: 'blacklight/hierarchy/facet_hierarchy'
     config.add_facet_field 'has_model_ssim',                  label: 'Object Model',        limit: 10
```

**Comment by drh-stanford** [comment]
@jmartin-sul does the above patch look ok to you, or should we delete/change the `facet.limit` from our Solr configuration? what's your thoughts?

**Comment by mejackreed** [comment]
I would say :+1: might as well do it. Since we are following that pattern else where :crying_cat_face:

**Comment by jmartin-sul** [comment]
yeah, i'm :+1: on this.  i don't have enough knowledge of solr config stuff to comment on that as a solution, but maybe @atz has an opinion there?  but i'm fine with this patch, despite the generally less than ideal nature of hardcoding huge limits like this.
