### ISSUE TITLE
KeyError: key not found: "argo.bulk_metadata.bulk_log_xml_filename"

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#3728]
## Backtrace

    line 126 of [PROJECT_ROOT]/app/models/user_log.rb: fetch
    line 126 of [PROJECT_ROOT]/app/models/user_log.rb: desc_metadata_xml_file
    line 35 of [PROJECT_ROOT]/app/controllers/bulk_jobs_controller.rb: block (2 levels) in show

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/85840756)

**Comment by andrewjbtw** [comment]
Closing this because the error is no longer in the HB history and I'm not sure what this refers to anymore. We can open a new ticket if it happens again.
