### ISSUE TITLE
Update catkey CSV bulk action to allow catkeys to be marked as refreshable or non-refreshable

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3735]
I thought I'd ticketed this in the last workcycle but apparently not. We need to include catkey refreshability in the update catkey bulk action. One approach we could take is to modify the CSV to add an optional Refresh column and then apply these rules:

1. Only the first catkey column (if the user enters multiple columns) can be designated "refresh"/"do not refresh"
2. Any additional catkey columns are automatically "do not refresh" (since only one catkey can be refreshable)
3. If the user submits a CSV with only "Druid,Catkey" as the headers, assume the catkeys are refreshable
4. If the user adds submits the headers "Druid,Catkey,Refresh" then use the "Refresh" column to set the refreshability

That's much more complicated than the current CSV but it does preserve the existing behavior for CSVs that only include "Druid,Catkey".

As for the "set catkeys via form" - I wonder if it's finally time to retire that and only keep the CSV. I think it's going to get harder to maintain both actions, plus adding refreshability as an option to the form-based action seems like a difficult challenge.

**Comment by ndushay** [comment]
So this is part of SDR migration carryover?

**Comment by andrewjbtw** [comment]
Yes, I think we should consider it carryover. The refreshable status was added post-migration near the end of the WC since we couldn't persist the field in Fedora.
