### ISSUE TITLE
(new registration form) Validate barcode format during form entry on the new Argo registration form

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3748]
**NOTE** This issue depends on the new registration form.

When a user enters a barcode on the new Argo registration form, validate that it matches an allowable pattern (defined in the cocina model). This should follow the example of how the form handles source id validation. Users should not be able to submit the form with a barcode that is not valid.

Currently, submitting an invalid barcode will take the user to a 500 error page.

Must be a PR against PR #3684 or must be done separately after PR #3684 is merged -- either way.

**Comment by ndushay** [comment]
possibly close enough to #3744 to warrant working on both together ...

**Comment by ndushay** [comment]
Andrew has signed off.
