### ISSUE TITLE
(new registration form) improve response to "catkey not found" errors during registration

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3750]
**NOTE** This issue depends on the new registration form.

Currently, when someone using the new registration form enters a catkey that is valid (in terms of format) but is not found in Symphony, the following happens:

- the registration form data is submitted for registration
- the items on the form that have all the required data get registered correctly
- the items on the form where the Symphony catkey lookup fails do not get registered
- the user sees an error message about the catkey(s) that could not be found
- the user is kept on the registration form page
- the user is given no indication that some items were registered successfully and some were not
- it is not possible to re-use the registration form page to fix the issue

This is a confusing situation, as the user is left needing to figure out what was registered and what wasn't. They can't resubmit the form after correcting the catkey because the successfully registered items will have been assigned the source ids from the first attempt, leading to source id conflicts. So they have to figure out what was registered, purge those items, and start over.

It would be preferable to do one of the following. I'm not sure which is the most feasible.

Option 1: fall back to the "label" field for the item where the catkey was not found and register the druid under that label.

- this allows the batch to succeed (in terms of creating druids for every item)
- this makes it possible for users to update the item that failed catkey import from the item show page

Option 2: do not register any item in the batch until verifying the every catkey on the input form will be found in Symphony, and show the user a message on the form if the catkey cannot be found (similar to error messaging around source id)

- this would prevent batches from partially succeeding because of catkey issues: if the batch is submitted, all data should be registered successfully (barring unrelated issues like network errors)
- this would give people a chance to fix data while filling out the form

Option 3: if registration partially succeeds, come up with a UI to show what has succeeded and what has failed. 

We currently have a UI for success (when every item submitted gets registered) and we have a UI for preventing invalid input (i.e. people do not progress past the form) but we don't have a UI for partial success. 

Must be a PR against PR #3684 or must be done separately after PR #3684 is merged -- either way.

**Comment by ndushay** [comment]
possibly close enough to code in #3749 to warrant working on both together.
