### ISSUE TITLE
Registration form: do not require label if a catkey is provided

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3773]
If a valid catkey is provided when registering an item, the title will be taken from the catkey metadata import rather than from the label. In the old registration form, you were supposed to always enter a label but the form apparently did not actually enforce that rule if you entered a catkey. It turns out some frequent Argo users got used to entering only a catkey and no label.

The new form is now enforcing a rule to enter a label whether or not there is a catkey. This has resulted in some confusion where people who are used to entering only a catkey are not sure which field will actually be used to make the title: the catkey or the label. If we can set the form to require a label OR a catkey, it would remove that confusion.

Functionally speaking, registration will take the Symphony title over whatever is entered in a label, which is the expected result.

**Additional context**

My guess is that in the old form, the intention was to always require a label to guard against situations where a catkey couldn't be retrieved. In those case, registration could take the title from the label if both catkey and label were entered. I remember seeing issues when I started where items didn't have titles, almost certainly because catkey metadata did not get imported successfully.

The new form now validates the catkey, so we should not have the same issue where a catkey cannot be imported, so the label shouldn't be needed to guard against a missing title.

**Comment by justinlittman** [comment]
Blocked until https://github.com/sul-dlss/argo/pull/3775 is completed.

**Comment by andrewjbtw** [comment]
I just approved #3775, so I believe this will become unblocked shortly.

**Comment by mjgiarlo** [comment]
@aaron-collier I assume we can unassign this from you.

**Comment by andrewjbtw** [comment]
IIRC, this went into backlog because it ran past the time-basedness of a previous workcycle but otherwise should be ready.
