### ISSUE TITLE
Register DOR Items using CSV upload don't follow the content type set in the screen

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/argo#3805]
I set content type as webarchive-seed in https://argo-stage.stanford.edu/registration and upload items using CSV 
![Screen Shot 2022-07-19 at 11 12 05 AM](https://user-images.githubusercontent.com/1050899/179820777-26470cea-c373-4b23-b9c6-d016881c33bf.png)

The items registered as item instead of webarchive-seed 
[test-reg.csv](https://github.com/sul-dlss/argo/files/9143669/test-reg.csv)
![Screen Shot 2022-07-19 at 11 19 52 AM](https://user-images.githubusercontent.com/1050899/179821427-3b649801-f1f1-4324-9f02-5c4ccaa88ecf.png)

**Comment by edsu** [comment]
Is this similar to #3802? I wonder do we need to add `webarchive-seed` to this list?

https://github.com/sul-dlss/argo/blob/main/app/services/registration_csv_converter.rb#L7-L14

@aaron-collier when you were working on this was there a logic to types to include?

**Comment by andrewjbtw** [comment]
I believe it's the same issue. Basically, it looks like if you use the CSV upload for registration, the content type will always be set to file when it should be set to whatever the user chose on the actual menu. 

I don't quite follow what work has been done on this already, but essentially the expected outcome is that the choices selected on the registration form are applied to the druids registered via the CSV. That seems to be happening for every value except for content type.

**Comment by aaron-collier** [comment]
this is a duplicate and fixed in https://github.com/sul-dlss/argo/pull/3804 but not yet deployed to prod I believe. I will leave open until deployment.

**Comment by peterchanws** [comment]
Hope the fix can deploy soon because it prevent me to register large batch of items.

**Comment by aaron-collier** [comment]
@peterchanws the fix has been deployed to production.

**Comment by peterchanws** [comment]
@aaron-collier Thanks.

**Comment by andrewjbtw** [comment]
@peterchanws it should work on stage now, if you want to try again.
