### ISSUE TITLE
Add mechanism to prevent specific collections from appearing in the "set collection" dropdown menu

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3825]
[This is related to the work to remove the hydrus/nonhydrus collection distinction. This issue may also overlap with #3819 which refers to decommissioned collections only.]

**The problem**

There are over 2600 collections in SDR. This set includes:

- collections that remain regularly used and added to
- collections that have been decommissioned and should never be used again
- "Hydrus" collections that pre-date the use of the "Stanford Research Data" collection and would not be created as separate collections today

Having all of these collections presents an interface problem: when moving an item from one collection to another, Argo users are presented with a single dropdown menu that lists every single collection to which they have access. For some users, this currently means seeing a list of 1200+ collections in the dropdown menu. The list will get even longer once we completely remove the Hydrus/nonHydrus distinction because currently Hydrus collections are not included in the list.

If we can reduce the number of collections in the list to only those collections that we think are "active", that would go a long way towards reducing the potential to make mistakes when moving items from one collection to another. In the current situation, when two collections have the same or a similar title, it can be difficult to choose the "correct" collection from the menu. In most cases, only one of those similarly-titled collections should be used and the rest should be considered inactive or decommissioned.

In the future, when nonHydrus and Hydrus collections appear on the same list, we will greatly increase both the length of the "set collection" list and the number of similarly-titled collections. I've identified over 150 pairs of Hydrus and nonHydrus collections where the collection titles are nearly identical, but where it's likely that only the non-Hydrus collection should be considered current and active. 

There are likely many additional "Hydrus collections" that contain only a small number of druids that should be considered "closed" to future deposits. In the early period of Hydrus, many collections were created that took in only a few items. Current practice would be to add new self-deposit items to an existing collection unless there were a compelling reason to create a new collection.

**The request**

Instead of showing every single collection in the dropdown menu, we should implement a way to prevent specific collections from appearing in the list. Categories of collection to be excluded from the list include:

- decommissioned collections
- collections for which we no longer expect new deposits (mainly legacy Hydrus collections that would need to be identified)

Ideally, it would be possible for Argo admins to manage this set of exclusions themselves, rather than maintain a hard-coded list somewhere. One way to do it, at least in the short run, would be to modify existing practice and use tags for this purpose.

The "set collection" dropdown list currently excludes collections that contain a "Project : Hydrus" tag. Instead of using that tag, we could use a different one, created solely for the purpose of excluding collections from the "set collection" menu. This may not be the ideal approach in the long run, but does seem like something that could be implemented within the H2 workcycle.

With the tag approach, I would anticipate:

- allowing (formerly) Hydrus collections into the "set collection" dropdown
- tagging decommissioned collections to remove them from the dropdown
- tagging other collections (such as legacy Hydrus collections that receive no new items) as inactive to keep them from the dropdown

Taking the tag approach would allow us to keep the impact of these changes within Argo. No objects would be modified (only their tags) and H2 would continue to function the same way. The difference would only appear in the Argo interface.

**Comment by jcoyne** [comment]
@andrewjbtw do you have a suggested name for this tag?

**Comment by andrewjbtw** [comment]
If there's no reason to keep the tag abbreviated, I think we should give it a name that helps explain what it means.

I think something like:

`collection status : inactive`

We can treat any collection that doesn't have that tag as "active" rather than explicitly tag everything else. There's already a separate tag approach for decommissioned objects that we can leave alone, and then I can add the new inactive collections tag to all of them.

**Comment by lwrubel** [comment]
Could you confirm that the "set collection" menu is the one in the bulk action to "set collection"? Does this also apply to the dropdown when you edit the collection on a single item ("add collection")?

**Comment by jcoyne** [comment]
@lwrubel yes, this is for both.
