### ISSUE TITLE
Show message in Argo UI when a CSV/spreadsheet upload contains non-UTF-8 characters

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3826]
**Describe the bug**
When users upload a descriptive metadata CSV in Argo that contains characters that are not valid UTF-8, an error is reported to HB that says something like:

`CSV::MalformedCSVError: Invalid byte sequence in UTF-8 in line 14.`
https://app.honeybadger.io/projects/49894/faults/87480814

This error does not get reported back to the Argo UI and it looks to the user like nothing has happened.

**User Impact**
Users don't know there was an issue with parsing their CSVs and may keep retrying with no success before either giving up or asking for help.

**To Reproduce**
1. Go to Bulk Actions
2. Click on "upload descriptive metadata spreadsheet"
3. Upload a spreadsheet that contains a non-UTF-8 character.
4. See nothing happen except an HB alert

**Expected behavior**
Argo should display an error message, similar to the fix for https://github.com/sul-dlss/argo/issues/3809 (about the same issue with registration CSVs).

**Additional context**
I don't know if there's a global way to address this for all of our CSV upload interfaces. I can try to track down other places this might be an issue, such as the structural metadata CSV (because filenames or resource labels may include non-ASCII characters).

**Comment by lwrubel** [comment]
@andrewjbtw it's possible to put an error message in the bulk actions UI for an error that's raised for any bulk action when the job is being set up. This is what it could look like for that CSV error:

![Screen Shot 2022-08-24 at 2 07 54 PM](https://user-images.githubusercontent.com/1619369/186491710-eb820d05-2bb3-473f-9753-91c033b2afe1.png)

Would something like this be acceptable as a start?

**Comment by andrewjbtw** [comment]
Yes, that looks good!
