### ISSUE TITLE
add web UI for monitoring/managing delayed jobs

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#384]
two existing options are:
https://github.com/ejschmitt/delayed_job_web
https://github.com/thebestday/delayed-web

i tried the latter, because it had a more recent commit, and was a rails engine as opposed to a sinatra app (so i guessed it might fit more easily into a rails app).  however, the functionality that it provides out of the box seems a bit limited for managing hundreds or thousands of jobs as opposed to tens of jobs.  and from a glance at the code, there doesn't seem to be much in the way of options for easily expanding what it does.  since it seems easier to just manage jobs from the command line than to use the delayed-web gem, i'm going to pull the commit that added it (https://github.com/sul-dlss/argo/commit/8a2ec30a17b757652f970554215f4b8b52ca03a6) from the profiling_and_indexing_improvements branch.

i haven't tried the first of option (delayed_job_web), but would like to at some point, as the UI looks like it might be more fully featured.

either way, we should also limit access to argo super users, which i also hadn't had a chance to do in the basic testing i did of delayed-web.

**Comment by cbeer** [comment]
I'm curious which one you end up picking -- we just rolled our own for exhibits.stanford.edu, but we'd happily switch if one of these options works out good.

**Comment by tingulfsen** [comment]
@cbeer Would you be able to point us to the code you use for this purpose in exhibits? I'd be interested to see how you monitor the jobs.

**Comment by cbeer** [comment]
Not well, but it mostly works: https://github.com/sul-dlss/exhibits/blob/master/app/controllers/delayed_jobs_controller.rb

**Comment by tingulfsen** [comment]
Thanks! Do you make any attempts at detecting failed jobs? I couldn't see anything in there with a cursory look. Also, do you just use DelayedJob directly or with ActiveJob?

**Comment by cbeer** [comment]
We're using `ActiveJob` with the delayed jobs adapter. Failed jobs just stick around with an exception.
