### ISSUE TITLE
Make maps using digital serials model not refreshable

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3862]
I've identified about 5300 objects in the map collections that use the digital serial model and therefore should not be refreshed from source, as that would overwrite metadata added in Argo. For these objects, `identification.catalogLinks.refresh` should be set to `false`.

Druid list:

[maps_do_not_refresh.txt](https://github.com/sul-dlss/argo/files/9687562/maps_do_not_refresh.txt)

**Comment by andrewjbtw** [comment]
@arcadiafalcone this should now be possible with the Bulk action to update catkeys via a CSV, though I have not tested it for items that already have catkeys.

>Please note that each row should have headers for:
>
>   Druid (required)
>   Catkey (optional). May be repeated if an item is associated with multiple catkeys.
>   Refresh (optional). Set to "true" to indicate descriptive metadata is refreshable from first catkey; set to "false" to >indicate descriptive metadata is not refreshable.

Assuming these items only have one catkey per druid, what that would look like is a CSV in this form:

```
druid,catkey,refresh
bc123df456,123456789,false
````

Since only the first catkey can ever be refreshable, any additional catkeys would already be marked as do not refresh but would need to be included in the CSV in order to avoid being taken out via the bulk action.

**Comment by peetucket** [comment]
I've just fired off a script to do it, looks like this:

```
# frozen_string_literal: true
#
druids = CSV.parse(File.read('tmp/maps_do_not_refresh.txt')).flatten

num = druids.size
error = 0
skipped = 0
updated = 0

druids.each_with_index do |druid, i|
  puts "#{i+1} of #{num}: #{druid}"
  object_client = Dor::Services::Client.object(druid)
  cocina = object_client.find

  if cocina.identification.catalogLinks.size > 1
    puts "***ERROR: more than one catalog link"
    error += 1
  elsif cocina.identification.catalogLinks.first.refresh
    change_set = ItemChangeSet.new(cocina)
    change_set.validate(refresh: false)
    change_set.save
    updated += 1
  else
    skipped += 1
    puts "***SKIPPED: refresh is already false"
  end
end

puts "Updated: #{updated}, skipped: #{skipped}, error: #{error}"

```

**Comment by peetucket** [comment]
I ran a test first and it found some that were already false, those won't be touched, and a single one that had two links (one was a previous catkey), fixed that one separately.  Currently going through the rest right now.

**Comment by peetucket** [comment]
All done.  Sorry if I stepped on the self-service option.

**Comment by andrewjbtw** [comment]
No problem. Just wanted to mention it now exists. But I have to update Consul.
