### ISSUE TITLE
Better view of hierarchical file content in Argo

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#3881]
For objects accessioned with hierarchy (e.g. via pre-assembly), the file content display area in Argo currently shows a flat list of files with paths.

Here is one example of how it currently looks (https://argo-qa.stanford.edu/view/druid:dt568vs5903):

![Screen Shot 2022-11-10 at 9 45 15 AM](https://user-images.githubusercontent.com/47137/201168768-0a2889f6-700d-443d-8757-ab63af331e2d.png)

Explore the possibility of a better display, e.g. something like this:

![Unknown](https://user-images.githubusercontent.com/47137/201168257-1a31924a-ec06-47b8-8127-4e0ded6b3fb5.png)

We will need to deal with the challenge that additional metadata is currently displayed for each file in Argo -- unclear how this would work with a hierarchical folder display.

**Comment by mjgiarlo** [comment]
@peetucket Is this ready or is it blocked because it is still needing design?

**Comment by peetucket** [comment]
I believe Astrid and Andrew were still discussing, perhaps @andrewjbtw can let us know if he thinks this is still blocked or not?

**Comment by andrewjbtw** [comment]
Sill blocked for design.

**Comment by astridu** [comment]
Add a section after the content that shows the folder hierarchy "View content in folder hierarchy". This section is closed by default and can be expanded by user. 

https://invis.io/YQ132HXFX2GR#/471282400_argo_File_Hierarchy

**Comment by justinlittman** [comment]
That design will fairly easy to implement.
