### ISSUE TITLE
Maintenance page doesn't appear in prod

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3883]
**Describe the bug**
Argo has a maintenance page that we've deployed successfully in stage, but during prod maintenance this morning we weren't able to get it to appear. Users saw either the library status page or a different 503 page.

We should determine why the page didn't appear. A very similar page did get displayed in H2.

The maintenance page has a message that looks like this:

<img width="682" alt="Screen Shot 2022-11-08 at 3 58 53 PM" src="https://user-images.githubusercontent.com/8975583/201179936-435b1335-1130-4ff0-b682-0622340cbf41.png">

**Comment by mjgiarlo** [comment]
My speculation is that this happens when a user without a current Shib session on the Argo boxes hits Apache, but I can't substantiate that. Would be good to log out of shib on Argo (there's a magic link, I believe, and Ops can help with that?) in stage or QA, throw up a maintenance page, and then tail apache and app logs and try to hit argo in the browser.

**Comment by mjgiarlo** [comment]
@andrewjbtw FR board-worthy?

**Comment by andrewjbtw** [comment]
Seems like a good idea to take advantage of the fact that we're already thinking about it to put it on the FR Board.

**Comment by mjgiarlo** [comment]
@andrewjbtw I'll do it.

**Comment by peetucket** [comment]
From Mike in Slack in https://stanfordlib.slack.com/archives/C09M7P91R/p1674759282510539: 

```
I believe the library status page wiring-up is done in the load-balancer and it happens when a server returns 
particular HTTP statuses---and if the maintenance page is working, it should return an HTTP status that 
does not cause the LB to redirect to the library status page
```

**Comment by peetucket** [comment]
This is where the changes were made to code and apache config: https://github.com/sul-dlss/argo/issues/3180#issuecomment-1061769127 and https://github.com/sul-dlss/puppet/pull/7783/files

**Comment by mjgiarlo** [comment]
If we conclude that Shib is part of what's causing the user to see the library status page (or an empty error page), I wonder if we need an Apache change that adds the maintenance URL as an exception to shib. (Might we already do this for OkComputer URLs?)

**Comment by peetucket** [comment]
I can confirm that the cap maintenance page returns a status of 503:

```
argo (main)$ curl -v https://argo-qa.stanford.edu/
*   Trying 171.67.37.122...
* TCP_NODELAY set
* Connected to argo-qa.stanford.edu (171.67.37.122) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; O=Stanford University; CN=argo-qa.stanford.edu
*  start date: Dec  8 00:00:00 2022 GMT
*  expire date: Dec  8 23:59:59 2023 GMT
*  subjectAltName: host "argo-qa.stanford.edu" matched cert's "argo-qa.stanford.edu"
*  issuer: C=US; ST=MI; L=Ann Arbor; O=Internet2; OU=InCommon; CN=InCommon RSA Server CA
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: argo-qa.stanford.edu
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< Date: Thu, 26 Jan 2023 21:49:11 GMT
< Server: Apache/2.4.41 (Ubuntu)
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Expires: Wed, 01 Jan 1997 12:00:00 GMT
< Cache-Control: private,no-store,no-cache,max-age=0
< Content-Length: 428
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
< Set-Cookie: BIGipServer~SULAIR~argo-qa_https=285634314.47873.0000; path=/; Httponly; Secure
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<p>Additionally, a 503 Service Unavailable
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
```

**Comment by peetucket** [comment]
I'm noticing that changes made to puppet for h2 to support maintenance pages (see https://github.com/sul-dlss/puppet/commit/eb6a34d8c6c4324daecfa78a3703b972d65ba31f) are not in argo puppet config (see https://github.com/sul-dlss/puppet/blob/production/hieradata/node/argo-prod-01.stanford.edu.eyaml) ... though of note, those changes don't seem to be in *any* environment argo puppet configs, yet the maintenance page does work in argo-qa.

Perhaps those changes are not required, but are important for the interaction with how the LB decides when to do a redirect to the library status page?  

Will ask ops if they have ideas.

**Comment by tallenaz** [comment]
I don't see the changes anymore, in, for example, h2's hieradata in any environment. Does the maintenance page still work for h2?

**Comment by jcoyne** [comment]
> I can confirm that the cap maintenance page returns a status of 503:

That wasn't the maintenance page, that was apache's 503 error page.

**Comment by tallenaz** [comment]
I see: we switched to `cap_maintenance` at https://github.com/sul-dlss/puppet/commit/eb6a34d8c6c4324daecfa78a3703b972d65ba31f

**Comment by peetucket** [comment]
> > I can confirm that the cap maintenance page returns a status of 503:
> 
> That wasn't the maintenance page, that was apache's 503 error page.

In browser it was showing the expected maintenance page though.

**Comment by peetucket** [comment]
> I see: we switched to `cap_maintenance` at [sul-dlss/puppet@caf7c6e](https://github.com/sul-dlss/puppet/commit/caf7c6edb848227e8ea3ca9f3a8bd44861a5bf36)

Oh whoops, sorry for the goose chase.  So argo is consistent with H2 then in puppet

**Comment by tallenaz** [comment]
Per https://github.com/sul-dlss/argo/issues/3883#issuecomment-1405674659 I believe the library-status page wiring is done in the load balancer in the virtual server's HTTP Profile. There's slightly different profiles set between argo_stage and argo_prod and argo_qa. Here's a mapping of the profile names:

argo_stage: dlss_default_http_profile
argo_qa:    : dlss-no-redirect
argo_prod : dlss-no-redirect

(They all have the library status page set as the fallback host, but are different in other ways) If things are working in stage, I have one question and one suggestion: is the maintenance page working in argo-qa? If not, we could try setting the profile there to the same as argo_stage. If that helps, it could mean we need to switch the profile in argo_prod as well.

**Comment by peetucket** [comment]
Ok, here is what I learned.  Argo-qa and argo-stage both currently work as expected, BUT, you need to be web-authed first.  If you aren't, you get a generic 503 page.  If you are, you get the expected maintenance page.

**Comment by peetucket** [comment]
I have not yet tested argo-prod (webauth and not) to avoid disruptions, but perhaps that would be an interesting test.  But need to do that in coordination with Andrew.

**Comment by mjgiarlo** [comment]
@peetucket It sounds like maybe we have arrived here?

> If we conclude that Shib is part of what's causing the user to see the library status page (or an empty error page), I wonder if we need an Apache change that adds the maintenance URL as an exception to shib. (Might we already do this for OkComputer URLs?)

Thanks for working on this!

**Comment by tallenaz** [comment]
The general approach to lift shib for a directory is [here](https://github.com/sul-dlss/puppet/blob/production/hieradata/node/example-rails-mysql.stanford.edu.eyaml#L121-L139)

**Comment by peetucket** [comment]
@tallenaz should i take a stab adding this to argo-qa puppet and see if it works?

**Comment by tallenaz** [comment]
@peetucket feel free to. Let me know if you want me to take a look at anything

**Comment by peetucket** [comment]
@tallenaz : something like this?  https://github.com/sul-dlss/puppet/pull/9085/files

Can you apply this change to argo-qa without merging the puppet PR to see if it actually works?

**Comment by mjgiarlo** [comment]
@peetucket 💬 
> @tallenaz : something like this? [sul-dlss/puppet#9085 (files)](https://github.com/sul-dlss/puppet/pull/9085/files)
> 
> Can you apply this change to argo-qa without merging the puppet PR to see if it actually works?

The branch can't contain any hyphens or underscores. It's a weird puppet constraint. More on that and how to apply branches: https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/puppet_prs.md

**Comment by tallenaz** [comment]
Sorry I'm late to this, but @peetucket you might need `shibboleth_optional: true` as well.

**Comment by peetucket** [comment]
We tested in argo-qa and it seems to work.  PR here for all environments: https://github.com/sul-dlss/puppet/pull/9086

One question that we still don't know until we test in prod is if the LB will stay see the nice maintenance page as a problem (since it has a 503 status) and still redirect to the library status page.  Not sure how to address that part.

**Comment by peetucket** [comment]
Ok, change applied in all environments and tested in qa and stage.  Still need to test in -prod (need to coordinate with @andrewjbtw to find a time to do this) and see what happens with the load balancer and the library status page.

**Comment by mjgiarlo** [comment]
@tallenaz Do you know what the behavior is in the load-balancer (for Argo in particular) for when to redirect to the library status page? Is it based on HTTP status alone? Or?

**Comment by tallenaz** [comment]
I'm not 100% sure, but from what I can gather from the load balancer, the profiles for all argo envrionments have the library-status page set as the fallback host, but no profile has "Fallback on Error Codes" set.

I see other profiles not used on argo, where there are recognizable HTTP status codes set for "Fallback on Error Codes".

That said, I don't know enough about how the profile works to say for sure. Someone else in Ops might be able to give a better answer.

**Comment by mjgiarlo** [comment]
@peetucket @andrewjbtw Worth keeping this issue open or can we close? Do we want to set up a maintenance page test in prod?

**Comment by andrewjbtw** [comment]
I was thinking about testing this next week? Maybe on Friday start or end of the day when it might not be that busy.

**Comment by mjgiarlo** [comment]
@andrewjbtw OK, cool. @aaron-collier is FR next week.

**Comment by andrewjbtw** [comment]
@peetucket I realized I never came back to this in February and now you're already FR again. Would you be able to test late in the day Friday (tomorrow)?

**Comment by peetucket** [comment]
Tested on 3/24/2023 in prod and worked fine in both authed and private (non-authed) windows.  Maintenance page seen in both cases.
