### ISSUE TITLE
Upgrade Remediation/Reaccessioning Workflows for Geospatial Data

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/argo#3909]
Enhancements to Geospatial Data Curation WorkFlows

1. Create simpler workflow for reaccessioning geospatial data

Reaccessioning of geospatial data involves multiple steps. Reaccessioning is required when a change is required to an object's data and/or metadata. The _gisAssembly_ and  _gisDelivery_ workflows can only be initialized once within Argo for Version 1 each object. All subsequent versions must follow the instructions [here](https://consul.stanford.edu/display/SULAIRGIS/HOWTO+-+Accession+layers) under "Automation outside of Argo" for remediation. These steps require the data curator to perform the following tasks:

- Open new object version in Argo
- Make necessary change(s) to data and/or metadata
- Package data/metadata into a 'DRUID/temp' folder
- Load data onto the staging environment
- Open a terminal, ssh into server, initialize robot env
- Run 2 workflow commands (gisAssembly, gisDelivery)
- Reload GeoServer
- Close object version
- Delete objects from server

Current source of geospatial metadata in SDR: cocina-geographic. Formerly: geoMetadata
 
2. Allow for changes to an item's geospatial metadata without having to reaccession data

A large number of remediation tasks involve changes to only an object's XML metadata. However, the current process by which metadata are remediated involves several data-instensive steps (see reaccessioning tasks listed above). Allowing for changes to be made to the metadata only would simplify remediation.

User story: As a data curator, I would like to be able to make changes to an item's geospatial metadata without having to interact with the data.

**Comment by thatbudakguy** [comment]
Marked as "analysis needed" pending further discussion about whether & how this involves the GIS robots, etc.

**Comment by andrewjbtw** [comment]
Thanks for filing this. Generally speaking, the vast majority of metadata-only updates to SDR objects can be done by using Argo alone. It would be good to know if the GIS workflows have to be re-run because that's the only way we have to get the metadata processed or if some of the workflow steps do other things when reaccessioning - like move files or push data to external servers. That could affect whether Argo could handle this update by itself.

**Comment by thatbudakguy** [comment]
> some of the workflow steps do other things when reaccessioning - like move files or push data to external servers

I think this is almost certainly the case for GIS data; we have to push some files to our GeoServer so that Earthworks can point to them and clients can request them using WMS/WFS and other GIS-specific protocols. I believe that process is handled in https://github.com/sul-dlss/gis-robot-suite.

**Comment by edsu** [comment]
The latest thinking is that we'd like GIS curators to be able to use Preaccessioning to stage updated files and trigger re-accessioning. This will involve figuring out how to get Preaccessioning to start the correct workflow and have it run to completion.
