### ISSUE TITLE
Hierarchy display  bug

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#3918]
When @peetucket was re-using the file hierarchy service logic in H2, he discovered an error when there are multiple directories at the same level.

The purpose of this ticket is to make a comparable correction in Argo.

**Comment by peetucket** [comment]
So how is depth computed in Argo?  To be less confusing when comparing to Argo code, I will leave rename to "depth" in the H2 PR.

**Comment by justinlittman** [comment]
The rendered components are hierarchically nested so there is no need to know the depth. (Unlike H2 where it is a list of components with variable indentation.)

**Comment by peetucket** [comment]
Ahh right - while H2 components are still rendered in a nested way, Argo does an HTML list while H2 does table rows.
________________________________
