### ISSUE TITLE
Registration Form: replace Symphony catkey with FOLIO HRID

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3938]
Registering an object with the FOLIO HRID should add the HRID to the identification metadata and import descriptive metadata from FOLIO.

**Comment by ndushay** [comment]
There will be a period when we will be using something like feature flags;  If it is possible to add both the ckey and the HRID to the cocina model during that period, that would be optimal.

**Comment by ndushay** [comment]
There will be a period when we will be using something like feature flags;  this should only display when "folio" is active and "symphony" is not active.

Not sure what should happen if both are active ...

**Comment by mjgiarlo** [comment]
Closed by #3969
