### ISSUE TITLE
Edit catkey Bulk Actions: Replace Symphony catkey with FOLIO HRID

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3939]
The "Edit catkeys and barcodes" and "Edit catkeys and barcodes from CSV" bulk actions should use FOLIO HRIDs instead. All instances of "catkey" in the user interface should be replaced with "FOLIO ID".

Entering a new FOLIO HRID should add the ID, type, and refresh status to the object's identification metadata.

Validation should expect FOLIO HRID pattern and display an error message to the user if validation fails.

Changing or removing a FOLIO HRID should change the type of the previous HRID to "previous folio".

As with catkeys, only one HRID should have refresh set to true.

See https://github.com/sul-dlss/dor-services-app/issues/4326 for sample Cocina identification metadata.

**Comment by ndushay** [comment]
There will be a period when we will be using something like feature flags;  this should only display when "folio" is active and "symphony" is not active.

Not sure what should happen if both are active ...

**Comment by mjgiarlo** [comment]
Closed by #3969
