### ISSUE TITLE
 "Refresh MODS from catkey" Bulk Action: replace Catkey with FOLIO HRID

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3940]
The bulk action "Refresh MODS from catkey" should be changed to "Refresh description from FOLIO ID" and import metadata from FOLIO.

**Comment by ndushay** [comment]
There will be a period when we will be using something like feature flags;  this should only display when "folio" is active and "symphony" is not active.

Not sure what should happen if both are active ...

**Comment by mjgiarlo** [comment]
Closed by #3969
