### ISSUE TITLE
[SPIKE] Item Show Page display and "Manage catkey" dialog: Replace Symphony catkey with FOLIO HRID

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3941]
When clicking on the pencil to open the "Manage catkey" dialog, the dialog entry should take a FOLIO HRID instead of a catkey. All "catkey" labels in the dialog box and show page should be changed to "FOLIO ID". The FOLIO HRID should be displayed on the show page instead of the catkey.

Entering a new FOLIO HRID should add the ID, type, and refresh status to the object's identification metadata.

Validation should expect FOLIO HRID pattern and display an error message to the user if validation fails.

Changing or removing a FOLIO HRID should change the type of the previous HRID to "previous folio".

As with catkeys, only one HRID should have refresh set to true.

See sul-dlss/dor-services-app#4326 for sample Cocina identification metadata.

THE CURRENT ACTION FOR THIS TICKET (02/23/23):

Determine the level of effort to implement features like this behind a feature flag. If this proves burdensome (time-consuming, messy code, etc.) please consult with @ndushay and/or @justinlittman before proceeding further.   It is hoped that we can use the feature flag approach, but it is feared that it will be too yucky to do so.

**Comment by ndushay** [comment]
There will be a period when we will be using something like feature flags;  this should only display when "folio" is active and "symphony" is not active.

Not sure what should happen if both are active ...

**Comment by justinlittman** [comment]
See https://github.com/sul-dlss/argo/pull/3959 for the implemented feature flag.

**Comment by justinlittman** [comment]
This is marked as a spike because we would like to determine the level of effort to implement features like this behind a feature flag. If this proves burdensome (time-consuming, messy code, etc.) please consult with @ndushay before proceeding further.

**Comment by justinlittman** [comment]
https://argo-qa.stanford.edu/view/druid:bb408qn5061 is a QA item that has both catkeys and HRIDs.
