### ISSUE TITLE
Item Show Page "Refresh" in "Manage description": Replace catkey with FOLIO HRID

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss/argo#3942]
The "Refresh" function in the "Manage description" menu on the item show page should use the FOLIO HRID to import metadata if refresh is set to true. If refresh is set to false, an error message should be displayed to the user.

**Comment by ndushay** [comment]
There will be a period when we will be using something like feature flags;  this should only display when "folio" is active and "symphony" is not active.

Not sure what should happen if both are active ...

**Comment by mjgiarlo** [comment]
Closed by #3969
