### ISSUE TITLE
APO default object rights can be set to invalid combinations

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3944]
**Describe the bug**
It is possible to set the default object rights stored in an APO to invalid combinations. This results in errors when the APO rights are applied to new or existing objects, since those objects must have valid rights. The APO should only use valid rights.

Example: when setting an APO default rights to citation, the download value should be set to dark. But it's possible to end up with an APO that combines:

view: citation
download: world

https://argo-stage.stanford.edu/view/druid:jb300vj1568
```json
"administrative": {
    "accessTemplate": {
      "view": "citation-only",
      "controlledDigitalLending": false,
      "copyright": null,
      "download": "world",
      "useAndReproductionStatement": null,
      "license": null
    },
```

I think what is happening is that only the "view" value is changed when setting the default rights to citation. The "download" value is left alone. So if the download was previously "world", then you get "citation" + "world". And if the download was previously "dark" you get the correct value of "citation" + "dark".

**User Impact**
It is not possible to create valid objects using an APO that contains invalid object rights.

**To Reproduce**
1. Go to https://argo-stage.stanford.edu/view/druid:jb300vj1568
2. Click on Edit APO
3. Change the rights to world using the menu
4. Save the change
5. Edit APO again
6. Change rights to citation
7. Save the change
8. Look at the Cocina
9. See that the download is still "world" 

**Expected behavior**
The default object rights should be constrained to only allow valid values. The menu for default object rights should follow the same logic and validation rules as the menu for item access rights.

**Additional context**
I have not checked other rights values. But if the default object rights are validated before being saved, that should account for any other issues there might be.

**Comment by jcoyne** [comment]
Could this move to cocina-models.  There should be a validator that prevents this setting in the cocina.
