### ISSUE TITLE
Create virtual object bulk action is not creating a virtual object

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3945]
**Describe the bug**
The create virtual object bulk action is not creating a virtual object. It looks like something is going wrong with the Cocina generation. Data is being updated but not in the right way.

Example: this virtual object should have three constituents
https://argo-stage.stanford.edu/view/druid:bg223jp4081

In the Cocina, there are two entries for `member` under `hasMemberOrders`
```json
"structural": {
    "contains": [],
    "hasMemberOrders": [
      {
        "members": [],
        "viewingDirection": "left-to-right"
      },
      {
        "members": [
          "druid:ys486qx8708",
          "druid:jz099cp6957",
          "druid:pt509sf4746"
        ]
      }
    ],
    "isMemberOf": []
  },
```
The empty array in the first list of members should have been replaced by the second list of members, which does look correct. 

Argo and the publish system for the Purl/Embed/etc. must be reading the empty array and treating this object as having no content, as Argo shows an empty content section and the Purl XML metadata includes no contentMetadata.

**User Impact**
It's not possible to create virtual objects. There's no manual way to do so.

**To Reproduce**

Create a new virtual object. There should be an integration test for this. It's a series of steps to do it via Argo and Preassembly. I can write them up if it's helpful but if the test covers it that would be better.

For the example above, this CSV line should produce the right order for the virtual object (it's what I'm submitting):
`druid:bg223jp4081,druid:ys486qx8708,druid:jz099cp6957,druid:pt509sf4746`

**Expected behavior**
There should only be one list constituents for the virtual object. I think with one list, then the other parts of virtual object creation should work: publishing to the Purl with the correct structure in the public XML/JSON that the Access apps need to render the object.

**Additional context**
I wonder if changes made to support hierarchy had an unintended effect on structural metadata.

**Comment by mjgiarlo** [comment]
@andrewjbtw Maybe it's interesting or maybe not: our integration tests have been successfully creating virtual objects in QA recently, e.g. https://argo-qa.stanford.edu/view/druid:vs841yz2744 and https://argo-qa.stanford.edu/view/druid:hp892sm4366. The structural metadata on these lacks a viewing direction, though, which also may be interesting?

**Comment by andrewjbtw** [comment]
I saw the integration test was succeeding and wondered if that meant there's something about the test that isn't representative of the steps that manually creating the virtual object would go through.

**Comment by andrewjbtw** [comment]
In the manual process, it looked like everything was working up until the bulk action:

1. Accession a few images
2. Accession an "empty" druid
3. Run the bulk action on a CSV

To start clean, you have to accession a few new druids. But unless I've completely forgotten how to do this (possible!) the CSV from my example should produce the correct result when things are working. It shouldn't really be necessary to start over with new druids.

**Comment by mjgiarlo** [comment]
@andrewjbtw I can walk through this tomorrow, but it's late in the day so for now: https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/virtual_object_creation_spec.rb Who doesn't love reading Ruby code at the end of the day?

**Comment by andrewjbtw** [comment]
@mjgiarlo Good catch on the viewing direction. I removed it from https://argo-stage.stanford.edu/view/druid:bg223jp4081 and then re-ran the spreadsheet and it works. So maybe the process is skipping the existing members list if it's non-empty.

Since we want to support viewing direction, I wonder if I should file a separate ticket or update this one to say that it doesn't work when an order is set. The registration form defaults to prompting you for a direction. Image doesn't technically require it but book does.

**Comment by mjgiarlo** [comment]
@andrewjbtw I'll start looking into the viewingDirection thing. I think it's fine to use this issue for that. I'll get started in the morning. 😃

**Comment by mjgiarlo** [comment]
@andrewjbtw Do you have a sense of when/how the viewing direction was set on the "empty" object?

**Comment by mjgiarlo** [comment]
@andrewjbtw I might also want to kick this off by writing and running a report against prod to gain a sense of how many objects have multiple member orders in place. (My hypothesis is that most have only one, but I want to be sure.)

**Comment by andrewjbtw** [comment]
Registration form.

**Comment by mjgiarlo** [comment]
@andrewjbtw If I've written my report properly, I'm now seeing 0 objects in QA, stage, and prod with more than one member order. So perhaps this is a registration form bug like you mentioned. I'll get to work on reproducing this.

**Comment by mjgiarlo** [comment]
@andrewjbtw If you see this recur in any environment, it means we need to deploy DSA. I would expect Monday's deploys to fix this.
