### ISSUE TITLE
Add Folio Instance HRID to Argo displays

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#3949]
The Argo solr index, as of PR sul-dlss/dor_indexing_app/pull/939, will have the field `folio_instance_hrid_ssim`

This `folio_instance_hrid_ssim` should be leveraged in Argo, analogous to how `catkey_id_ssim` is used in Argo;  note that `catkey_id_ssim` .

Test by looking at search results, at show pages and at any other places where you add the field.  Have Arcadia and Andrew do thorough testing, too.

**The desired result of this ticket is**:
 a PR that can be deployed to prod now, allowing us to see and use folio ids, without interfering with current functionality of Argo.

Wrinkles:
- there may need to be additional ticket(s) for ways we _cannot_ currenty expose `folio_instance_hrid_ssim`without breaking Argo or confusing users in production.
- there may be a need to put some or all of the new code behind the feature flag for "folio"
- sul-dlss/dor_indexing_app/pull/939 has to be deployed to the environment being used (and it's been merged to prod, so after Mon 2/27/23, there shouldn't be a need to check) (stage, qa)
- getting a list of objects in (stage or qa) that have folio identifiers, or creating these (via DSA rails console?)
- ensuring those objects are indexed (reindex bulk action?  reindex individual action?)

**Comment by ndushay** [comment]
![image.png](https://images.zenhubusercontent.com/5d89272aae87b600015057e7/569610ec-f152-45c2-a892-5cb6bc67149e)

**Comment by mjgiarlo** [comment]
Closed by #3969
