### ISSUE TITLE
Large collections timeout when publishing

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3972]
**Describe the bug**
Collections with many items are timing out at the publish step. Publish takes a long time for these collections because when a collection is published, all of the items within the collection also get republished. Republishing the items is done so that changes to the collection title get picked up on the item Purl. Because Purls are created from static XML, the XML has to be updated for each item in a collection so that the item Purl displays the correct title when a collection is changed.

Some collections have hundreds of thousands of items and take hours to republish. I'm not sure why HB hasn't alerted again since last night, but I see multiple collection druids where publish jobs have restarted again this morning. This is the HB error:
https://app.honeybadger.io/projects/50568/faults/88229792

Druids affected include:
- https://argo.stanford.edu/view/gw676ck6589 (70,000 items)
- https://argo.stanford.edu/view/gh795jd5965 (180,000 items)
- https://argo.stanford.edu/view/nt028fd5773 (460,000 items)

Unfortunately, there are actually three publish jobs running on gh795jd5965. I hit the "publish" button multiple times before I realized why publish was taking so long. 

**User Impact**
Updating collection objects stalls when collections are large. If using the accessionWF to update the collection, accessioning doesn't finish.
**To Reproduce**
1. Go to a collection with hundreds of thousands of objects.
2. Click on "Manage purl" and "Publish"
3. Wait for a long time
4. See republish head into sidekiq retries.

**Expected behavior**
Collection objects should eventually finish republishing, however long that takes.

**Additional context**
The "Google Books" collection has 2.9 million items. It's not clear it can republish successfully.

We may need to reconsider our approach to publishing collections. However, as long as purls are composed of static data, republishing every item in a collection will be necessary in order to update collection titles on item purls.

**Comment by andrewjbtw** [comment]
For what it's worth, I'm publishing these druids because I'm trying to get Cocina JSON onto the purl system. I'm not even trying to change any data stored in SDR, just distributing the data in the format that we created last year in the Cocina migration.

**Comment by justinlittman** [comment]
Possible solutions (not mutually exclusive):
* Add retries to post to PURL fetcher.
* Increase resources (CPU, RAM) of PURL fetcher server.
* Decrease concurrency of PublishJob (will require assigning to own Sidekiq process).

**Comment by justinlittman** [comment]
![image](https://user-images.githubusercontent.com/588335/224411357-1fd11b64-90e2-4c94-988f-47311ba74b62.png)

**Comment by justinlittman** [comment]
This seems enough under control that I'm going to close.

**Comment by andrewjbtw** [comment]
It's not fixed, so I'm reopening it. I killed the jobs that were failing for a while, then tried again and they still aren't finishing.

**Comment by andrewjbtw** [comment]
Suggestion from today's meeting about purl-fetcher and publishing: split collection publishing into individual jobs rather than one big job that starts over from the beginning each time.

To consider: how to queue up large numbers of publishing without trying up DSA for accessioning. One approach would be to put collection-initiated publishes into the lower priority lane, similar to how Google Books was done.
