### ISSUE TITLE
Turn on folio integration in QA environment, across apps

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/argo#3973]
The goal of this ticket is to set up the QA environment to be using Folio instead of Symphony. Although this ticket is in the Argo repo, shared_configs for all apps that have folio toggles should be updated. 

Document here which shared_configs have been changed and any other toggles (if they exist) that need to be switched.

**Comment by justinlittman** [comment]
In DSA:
```
enabled_features:
  read_folio: true
  sync_cataloglinks: false
```

**Comment by justinlittman** [comment]
In Google Books:
```
catalog_record_id: 'folio'
```

**Comment by justinlittman** [comment]
Also, any application that uses Folio client will need appropriate configuration in shared_configs.

**Comment by peetucket** [comment]
In Hydra ETD:

```
catalog_record_id: 'folio'
```

**Comment by peetucket** [comment]
See https://github.com/sul-dlss/shared_configs/pull/1918/files and https://github.com/sul-dlss/puppet/pull/9214 for an example of how to configure the Folio client gem (this is for Google Books, which is already done).  It involves both adding settings to shared_configs and a change to puppet to pull the password from vault.

**Comment by mjgiarlo** [comment]
In Argo:
```
enabled_features:
  folio: true
```

**Comment by lwrubel** [comment]
Puppet PRs:
* DSA: https://github.com/sul-dlss/puppet/pull/9234
* hydra_etd: https://github.com/sul-dlss/puppet/pull/9233
* (Google Books already done)

Shared_configs:
* DSA: https://github.com/sul-dlss/shared_configs/pull/1921
* hydra_etd: https://github.com/sul-dlss/shared_configs/pull/1922
* google-books: https://github.com/sul-dlss/shared_configs/pull/1923
* (Argo already done)

**Comment by lwrubel** [comment]
Document for each app in one consolidated place (Google Doc?) what settings and in which apps settings need to be updated.

**Comment by lwrubel** [comment]
Documented in this Google Doc: https://docs.google.com/document/d/11D4bmqoE59SzsasJJoCs4eXV2fNVJXus5Keofbb72bg/edit#
