### ISSUE TITLE
Test Argo functionality in QA that touches Folio to gauge how "done" Argo is

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#3976]
This is likely incomplete or incorrect, but here's an initial stab at the affected functionality:

- [ ] Display Folio Instance HRIDs on show page for item
- [ ] Display Folio Instance HRIDs on show page for collection
- [ ] Add and edit Folio Instance HRID (refresh=true) on show page, without affecting any existing catkeys
- [ ] Add and edit Folio Instance HRID (refresh=false) on show page, without affecting any existing catkeys
- [ ] "Edit Folio Instance HRIDs and barcodes" bulk action
- [ ] "Refresh MODS from Folio Instance HRID" bulk action
- [ ] "Edit Folio Instance HRIDs and barcodes from CSV" bulk action
- [ ] Ensure SearchWorks link is pointing at the right identifier
- [ ] Refresh metadata from Folio on the show page
- [ ] Register an item with a Folio Instance HRID
- [ ] Test reports
- [ ] Test track sheets

I suspect this is an @andrewjbtw and @arcadiafalcone issue, but I didn't want to pre-assign them until they were ready to have at this.

**Comment by lwrubel** [comment]
Covered by https://docs.google.com/document/d/1wdNo980l9Yzwu5b_areUH4qavyafwUER-ppRhmBkGlA/edit#. 

@mjgiarlo OK to close this while work in progress and documented there?

**Comment by mjgiarlo** [comment]
@lwrubel Sounds good to me. :)
