### ISSUE TITLE
Cocina descriptive metadata downloads: when sorting notes, null displayLabels and/or types should be treated as having the same value.

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3978]
(Note: I've rewritten this ticket to reflect the discussion below.)

Per @arcadiafalcone in the comments below, when sorting note fields for the Cocina descriptive metadata download spreadsheet (in the Bulk actions, not related to the Modsulator)

>null displayLabels and/or types should be treated as having the same value.

The current sorting logic is leading to a really odd-looking display where each note field is placed in a new column:

<img width="1378" alt="Screenshot 2023-03-08 at 3 26 44 PM" src="https://user-images.githubusercontent.com/8975583/223875837-de080abc-66d1-4747-b66f-fce25856b100.png">

**User Impact**
Oddly-organized spreadsheets make it even harder to work with descriptive metadata. It's very difficult to read over the notes fields when they sprawl horizontally like this.

**To Reproduce**

I was able to create a set of druids that reproduce this behavior in the staging environment.

1. Load the items under the [project tag "note field numbering issue"](https://argo-stage.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=note+field+numbering+issue) 
3. Click on the "Bulk actions" link from the search result (not the link in the top red bar)
4. Create a new bulk action
5. Choose "Download descriptive metadata spreadsheet"
6. Open the CSV
7. Scroll to the right and see the weird note field alignment

**Expected behavior**
The numbering of notes should start at 1 for each druid.

**Additional context**
I did test re-importing a spreadsheet that looks like this in stage and fortunately it doesn't create 15 notes when the first note field is numbered "15", so the problem may be just in the export function. Importing metadata seems to be functioning as expected.

**Comment by justinlittman** [comment]
This can be reproduced with just `druid:cb331st0877` and `druid:bt560sc8552`.

Based on my reading of the code, this works as intended -- note grouping is performed based on `displayLabel` and `type`. These notes have `value` but not these other attributes, hence are not grouped together.

Perhaps @jcoyne knows the reason for this grouping logic?

**Comment by mjgiarlo** [comment]
https://github.com/sul-dlss/argo/issues/3734#issuecomment-1154543426

**Comment by mjgiarlo** [comment]
@justinlittman 💬 
> This can be reproduced with just `druid:cb331st0877` and `druid:bt560sc8552`.
> 
> Based on my reading of the code, this works as intended -- note grouping is performed based on `displayLabel` and `type`. These notes have `value` but not these other attributes, hence are not grouped together.
> 
> Perhaps @jcoyne knows the reason for this grouping logic?

This is more or less the "spec:" https://github.com/sul-dlss/argo/issues/3734#issuecomment-1154543426

**Comment by andrewjbtw** [comment]
Flagging this for @arcadiafalcone - should the sorting logic be modified to account for this situation?

**Comment by arcadiafalcone** [comment]
Yes, null displayLabels and/or types should be treated as having the same value.

**Comment by andrewjbtw** [comment]
I rewrote the ticket description to make it clearer that the request is for new sorting logic to account for this situation.

**Comment by mjgiarlo** [comment]
I'm going to suggest that it may be best if someone on @sul-dlss/infrastructure-team who is not me takes the lead on this to get the grouper classes in more brains. Happy to be pulled in for pairing.
