### ISSUE TITLE
Bulk reindex to pick up Folio as a metadata source

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#3979]
Blocked by https://github.com/sul-dlss/argo/issues/3977 and https://github.com/sul-dlss/dor_indexing_app/issues/946

Also blocked by prod not having been backfilled yet (https://github.com/sul-dlss/dor-services-app/issues/4326 ?)

This should be done in QA, staging, and production.

**Comment by mjgiarlo** [comment]
NOTE: This is still blocked in prod, but is doable in QA and stage.

**Comment by justinlittman** [comment]
I suspect that the data migration in prod will force the reindex on its own.

**Comment by mjgiarlo** [comment]
@justinlittman Yeah, it could be there's no work to do for this issue specifically, and the issues this one blocks could instead be blocked by the data migration.

**Comment by lwrubel** [comment]
@ndushay to look at Argo prod and confirm whether reindexing occurring automatically.

**Comment by mjgiarlo** [comment]
> @ndushay to look at Argo prod and confirm whether reindexing occurring automatically.

In theory, refreshing https://argo.stanford.edu/?all=true&multivalued=true every so often should show the `Metadata Source (Multi)` facet with the counts gradually increasing. I am not seeing that facet now which indicates (I think?) that nothing has yet been indexed with the `metadata_source_ssim` field.

**Comment by mjgiarlo** [comment]
If I'm mistaken about that... there's probably a better strategy.

**Comment by andrewjbtw** [comment]
The solr documents can be viewed from Argo and I'm seeing `metadata_source_ssim` populated in at least some of them: https://argo.stanford.edu/view/druid:bb000fk1989.json

Could the new facet display not be deployed yet?

**Comment by mjgiarlo** [comment]
It looks like it should be. I'm not sure. But if we're seeing that field populated, then great!

**Comment by mjgiarlo** [comment]
@justinlittman has a handful of items to migrate, and then I think we should flip the multi-valued flag ON in prod to gauge the current state of the reindexing. (I'd work with @andrewjbtw to schedule that. Possibly in a week or three.)

**Comment by andrewjbtw** [comment]
Has the new facet ever appeared in Argo prod? I've tried "folio=true" and "multivalued=true" and I've never gotten it to show up.

**Comment by mjgiarlo** [comment]
@andrewjbtw Not that I've seen. I can't explain why `multivalued=true` doesn't appear to flip this on in prod, which is part of why I'm eager to flip on the flag in prod and check it out.

**Comment by andrewjbtw** [comment]
It's ok with me to turn it on. I'm just concerned about the possibility of not having either "metadata source" for a while.

**Comment by mjgiarlo** [comment]
We're going forward with multi-valued metadata sources now that reindexing is done and all envs look copacetic. Closing.
