### ISSUE TITLE
Generate "MODS view" from Cocina mapped to MODS XML

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#4001]
As part of our [cross-team work to "Cocinize" the Access stack](https://docs.google.com/document/d/1xeU8JcMOKwgfu2xoOZRNijdngShA2x895h6LRGCpwSU/edit#), we are moving logic about mapping Cocina to "public XML" out of dor-services-app and into purl-fetcher. In support of that work, we should no longer generate the item MODS view (which formats descriptive metadata in a modal using the `mods_display` gem) using public XML. Instead, it should be generated from MODS mapped from Cocina (via `cocina-models` gem).

Once this is done, feel free to either do the following tech debt removal as part of this issue, or create new, ready issues:
- [ ] Remove `MetadataController#descriptive` endpoint in DSA (☝🏻 is/was the only consumer)
- [ ] Remove `Dor::Services::Client::Metadata#descriptive` method in DSC (☝🏻 is/was the only consumer)

**Comment by mjgiarlo** [comment]
This view in Argo uses DSA to transform Cocina descriptive metadata into the descriptive/MODS subset of public XML. This differs from the "Cocina MODS," if you will, in the following ways ([code](https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/public_desc_metadata_service.rb#L28-L32)):

* For items belonging to a collection, add the collection's title and purl URL (as a MODS `relatedItem` node)
* For items that are constituents (i.e., of "virtual objects"), add the "parent's" title and purl URL (as a MODS `relatedItem` node)
* For items with a DOI in identification metadata, add the DOI (as a MODS `identifier` node)
* Add the license, copyright statement, and use and reproduction statement from access metadata (as MODS `accessCondition` nodes)

**Comment by mjgiarlo** [comment]
Following from ☝🏻, if we switch Argo to use MODS mapped directly from Cocina descriptive---instead of public XML MODS---for the Argo "MODS view," the following elements will no longer displayed:

* the item's collection title
* the item's DOI
* the item's virtual object parent info (title + purl URL), assuming it's a constituent

And losing that information is not acceptable per our users. At the same time, it is more cost than benefit to consider generating the current "MODS view" directly from Cocina, given how much logic from `mods_display` we'd have to borrow, duplicate, and adapt. And it's important for this "MODS view" to approximate what users will see on the purl page and in SearchWorks. Thus, I don't know what options we have other than not taking on the work described in this ticket.

Do we have other options worth considering? @jcoyne @sul-dlss/infrastructure-team

**Comment by mjgiarlo** [comment]
@justinlittman If folks agree with what I wrote above, then I think moving the logic into Argo is better than leaving it in DSA since it lets us remove this functionality from the repository API and put it closer to where it's used.

**Comment by mjgiarlo** [comment]
Tossing the issue over to you, @justinlittman, since you've got a handle on all this. 🏆

**Comment by justinlittman** [comment]
Done
