### ISSUE TITLE
Set up connection between Argo -stage and newly migrated Goobi -stage

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/argo#4005]
The Goobi servers are being migrated as part of the Operations team server migration work. There is a new server for Goobi -stage, and will be one for Goobi -production as well. In the past, the two systems (Goobi -stage and Argo -stage) were connected, so that a user would be able to register an item in Argo -stage, process the files using Goobi -stage, and accession into Argo -stage, to ensure the end-to-end workflow was working as expected. With the new server, the connection needs to be re-established. 

Ticket outlining the work for the server migration: https://github.com/sul-dlss/sul-goobi/issues/325

**Comment by dinahhandel** [comment]
I have tested the connection between Goobi -stage and Argo -stage and it appears to be working as expected. Should we close the ticket following the successful production connection @jmartin-sul ?

**Comment by jmartin-sul** [comment]
> I have tested the connection between Goobi -stage and Argo -stage and it appears to be working as expected. Should we close the ticket following the successful production connection @jmartin-sul ?

yeah, i can't think of anything else to do once the prod cutover is done, sounds right to me.
