### ISSUE TITLE
Selecting a facet via "more" interaction doesn't take you to a search result

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#402]
Open a facet that requires "more", e.g. SW Region.
![screen shot 2016-01-04 at 10 45 14 am](https://cloud.githubusercontent.com/assets/1824732/12097378/44d421b0-b2d0-11e5-8c0b-f46c3851cebd.png)
Open up "more' and pick a value, e.g. Scotland.  You are left on a screen that is an expansion of the tag layout, not an actual search result page.
![screen shot 2016-01-04 at 10 46 23 am](https://cloud.githubusercontent.com/assets/1824732/12097441/916bfa0c-b2d0-11e5-8518-3d8540db8772.png)

**Comment by drh-stanford** [comment]
The problem here is that the "more" modal dialog is going to the `/catalog/facet` route when you click on a value.
