### ISSUE TITLE
Revisit Folio feature flag implementation

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#4025]
https://github.com/sul-dlss/argo/blob/main/app/controllers/application_controller.rb#L39 changes the value across the entire app, not just in the context of the request, so we need a new solution for being able to flip on Folio on a per-request basis.

**Comment by mjgiarlo** [comment]
Assuming this is a useful feature. If not, will close.

**Comment by andrewjbtw** [comment]
@mjgiarlo is this closeable? I remember we did something to change how the feature flag was implemented but I'm not sure if that addressed this issue.
