### ISSUE TITLE
Folio cutover: Turn off metadata refresh on show page

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4031]
NOTE: If possible, implement this behind a "ils-cutover-in-progress" feature flag.

During the period where both Symphony and Folio are unavailable, the "Refresh" option under the "Manage description" button on the Argo item and collection show pages should be grayed out, even when the object is opened for versioning.

<img width="268" alt="Screenshot 2023-06-08 at 4 38 46 PM" src="https://github.com/sul-dlss/argo/assets/8975583/bf45412c-a083-4e78-936f-2e2c608b76e0">

**Comment by andrewjbtw** [comment]
I like that idea. It's fine with me assuming a label that long fits into the space.

**Comment by justinlittman** [comment]
For what is worth: For bulk actions, I went with "DISABLED: Refresh".
