### ISSUE TITLE
Thumbs on the result page are rather small

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#404]
They seem disproportionately tiny to me ... we have room to show larger?
![screen shot 2016-01-04 at 11 20 24 am](https://cloud.githubusercontent.com/assets/1824732/12098196/6d05353e-b2d5-11e5-9101-1b5fe8d07dc7.png)

compare thumb on detail page
![screen shot 2016-01-04 at 11 22 55 am](https://cloud.githubusercontent.com/assets/1824732/12098208/89a03b94-b2d5-11e5-8d41-e8c5d3dbff00.png)

**Comment by mejackreed** [comment]
We do. This is currently using some legacy helper method stuff. I think we can do this in a better IIIF way.
