### ISSUE TITLE
technical metadata won't display for media items

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4041]
**Describe the bug**
When users click on the technical metadata section of an Argo page for media items, an error displays:

```
Technical Metadata connection failed: Unexpected response (500) from technical-metadata-service for druid:bb042zq5720: {"id":"invalid_response","message":"#/components/schemas/AvMetadata/properties/encoded_date Value: \"2019-05-29T06:00:22\" is not conformant with date-time format"}
```
![Screenshot 2023-06-28 at 11 18 15 AM](https://github.com/sul-dlss/argo/assets/8975583/25616ce6-9c23-410f-8402-f70398861207)

**User Impact**
Users can't get any of the technical metadata information for media items.

**To Reproduce**
1. Go to a media item like: https://argo.stanford.edu/view/druid:bb042zq5720
2. Click on the technical metadata section
3. See error

**Expected behavior**
The technical metadata is supposed to display.

**Additional context**
I don't see a honeybadger error so it's not clear when this happened. A user reported it today but it may have been present for a while. I don't think there's a problem with technical metadata generation itself, just the display. Many of the items with a problem were accessioned quite a while ago.

**Comment by jcoyne** [comment]
I believe this is because `2019-05-29T06:00:22` doesn't include a time zone. See https://www.rfc-editor.org/rfc/rfc3339#section-5.6

**Comment by aaron-collier** [comment]
It's strange that on the TechMd server side it shows as a 200:
```
I, [2023-06-28T13:08:30.722246 #4046892]  INFO -- : [98763b5a-732d-4efc-907d-3fd2c83db85c] Processing by TechnicalMetadataController#show_by_druid as JSON
I, [2023-06-28T13:08:30.722305 #4046892]  INFO -- : [98763b5a-732d-4efc-907d-3fd2c83db85c]   Parameters: {"druid"=>"druid:bb042zq5720"}
I, [2023-06-28T13:08:30.736062 #4046892]  INFO -- : [98763b5a-732d-4efc-907d-3fd2c83db85c]   Rendered technical_metadata/show_by_druid.json.jbuilder (Duration: 10.3ms | Allocations: 3327)
I, [2023-06-28T13:08:30.736353 #4046892]  INFO -- : [98763b5a-732d-4efc-907d-3fd2c83db85c] Completed 200 OK in 14ms (Views: 8.8ms | ActiveRecord: 2.9ms | Allocations: 3831)
```
