### ISSUE TITLE
Document reset process for sdr-api

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#4049]
In the sdr-api README, create a new top-level section called `Reset Process (for QA/Stage)`, and in that section document the following:

- [ ] Verify what needs resetting (deleting) is the following:
  * Database: `sdr` (Postgres) on `localhost`
    * Can re-create user records by either using the CLI documented in the README or us
  * Files: `/globus/sdr_ingest/{qa,stage}/uploads/`
  * Redis: `localhost`
  * Globus mount ❓ 
- [ ] Determine what needs re-seeding (re-creating) in the app
- [ ] Determine what needs re-seeding in SDR (e.g., APOs, collections, agreements, & canonical objects)
- [ ] Determine how to reset and re-seed ☝🏻 (e.g., DB drop/create/migrate, specific DB table drops, `rm -rf`, export/import steps)

**Comment by justinlittman** [comment]
An approach for recreating Users is to pg dump and restore the single table.
