### ISSUE TITLE
Displaying objects without APOs (like Google Scanned Books)

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#405]
https://argo-stage-b.stanford.edu/catalog/druid:bb003xz2305

Good news (maybe) is that we are seeing our error page.  Bad news is no clue as to the problem; no link to additional diagnostic data.  We need this, in stage and even in prod.  This is not a public application so some exposure of plumbing when things go badly wrong will make things a lot easier.

**Comment by LynnMcRae** [comment]
A more global problem with argo-stage at the moment?  Getting lots of errors displaying records now ...
https://argo-stage-b.stanford.edu/catalog/druid:bb006jh5661
https://argo-stage-b.stanford.edu/catalog/druid:bb120qq6105
https://argo-stage-b.stanford.edu/catalog/druid:bb122qt4829

**Comment by drh-stanford** [comment]
To see the diagnostics for the error page, you have to visit `sul-squash.stanford.edu`. Navigate to Argo, then Staging, then sort by most recent occurence. This will show you all the diagnostics for the error.

This particular problem is logged here, for example:

  https://sul-squash.stanford.edu/projects/argo/environments/staging/bugs/11

It looks like the search service might be down? @jmartin-sul ?

**Comment by drh-stanford** [comment]
In stage, `bb003xz2305` doesn't appear to have an APO associated with it. Neither does `bb006jh5661`. This looks to be the problem -- the item has no APO and thus the checks for whether you have permissions to access the item are failing.

**Comment by drh-stanford** [comment]
This code here:

  https://github.com/sul-dlss/argo/blob/develop/app/models/user.rb#L40

needs to be more robust in how it handles missing APOs. RIght now it throws a cryptic exception all the way out to rails.

**Comment by drh-stanford** [comment]
This is likely related to https://github.com/sul-dlss/argo/issues/334

**Comment by LynnMcRae** [comment]
I think the problem occurs for Google Scanned Books, which pre-date APOs so they have none. There's a task somewhere on the back-burner to assign them one (druid:wk434ht4838) but no progress on it to date.

**Comment by blalbrit** [comment]
Closing of this ticket depends on data remediation for Google books (add APO - ticket to be added in remediation queue). This is not a blocker for Argo release (from a code perspective), but from a "we don't want stuff to break" perspective we'll address the data issue outside of the Argo team.

**Comment by drh-stanford** [comment]
is this a duplicate of #334?

**Comment by LynnMcRae** [comment]
I had understand it not to be a duplicate, but since the other ticket had the extra wrinkle of killing indexing, we may find that once it is fixed Argo in fact has the same difficulty displaying an entry with a bad APO reference as with none at all.

**Comment by LynnMcRae** [comment]
his is good in prod
