### ISSUE TITLE
Document reset process for preservation_robots

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#4051]
In the preservation_robots README, create a new top-level section called `Reset Process (for QA/Stage)`, and in that section document the following:

- [ ] Verify what needs resetting (deleting) is the following:
  * Files: `/dor/export/`, `/services-disk-stage/store-100/`, `/services-disk-stage/store1/`, `/services-disk-stage/store2/`
  * Redis: `redis://sul-robots-redis-{qa,stage}.stanford.edu:6379/`
- [ ] Determine what needs re-seeding (re-creating) in the app
- [ ] Determine what needs re-seeding in SDR (e.g., APOs, collections, agreements, & canonical objects)
- [ ] Determine how to reset and re-seed ☝🏻 (e.g., DB drop/create/migrate, specific DB table drops, `rm -rf`, export/import steps)

**Comment by jmartin-sul** [comment]
closing in favor of a single ticket for resetting the preservation service as a whole, per infra dev planning discussion yesterday, since it makes more sense to approach preservation_catalog and preservation_robots together (morphing the existing pres cat ticket, #4052).
