### ISSUE TITLE
Document reset process for gis-robot-suite

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#4057]
In the gis-robot-suite README, create a new top-level section called `Reset Process (for QA/Stage)`, and in that section document the following:

- [x] Verify what needs resetting (deleting) is the following:
  * Files: `/var/geoserver/local/raster/geotiff/`, `/var/geomdtk/current/stage/`, `/var/geomdtk/current/tmp/`, `/var/geomdtk/current/workspace`, `/var/geomdtk/current/export/opengeometadata/edu.stanford.purl`
    * listed as the dirs for which contents should be wiped in [the gis-robot-suite readme PR](https://github.com/sul-dlss/gis-robot-suite/pull/624).
  * Redis: `redis://sul-robots-redis-{qa,stage}.stanford.edu:6379/`
    * will be wiped as part of the larger SDR reset process that encompasses all the apps
- [x] Determine what needs re-seeding (re-creating) in the app
  - nothing to re-seed
- [x] Determine what needs re-seeding in SDR (e.g., APOs, collections, agreements, & canonical objects)
  - just the APO that integration tests use, which is tracked in a different part of the overall SDR reset process
- [x] Determine how to reset and re-seed ☝🏻 (e.g., DB drop/create/migrate, specific DB table drops, `rm -rf`, export/import steps)
  - just `rm -rf` the contents of the above listed directories

**Comment by justinlittman** [comment]
Wondering if any of the geo servers need to be reset?

**Comment by mjgiarlo** [comment]
Do you think we can take up the geoserver question as part of #4063 so the person who picks up this issue can focus on state held by the robots?
