### ISSUE TITLE
Document reset process for common-accessioning

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#4060]
In the common-accessioning README, create a new top-level section called `Reset Process (for QA/Stage)`, and in that section document the following:

- [ ] Verify what needs resetting (deleting) is the following:
  * Files: `/dor/assembly/`, `/data/hydrus-files/`, `/dor/workspace`
  * Redis: `redis://sul-robots-redis-{qa,stage}.stanford.edu:6379/`
- [ ] Determine what needs re-seeding (re-creating) in the app
- [ ] Determine what needs re-seeding in SDR (e.g., APOs, collections, agreements, & canonical objects)
- [ ] Determine how to reset and re-seed ☝🏻 (e.g., DB drop/create/migrate, specific DB table drops, `rm -rf`, export/import steps)

**Comment by justinlittman** [comment]
Nothing requires separate documentation.
