### ISSUE TITLE
Document reset process for robot-console

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#4062]
In the robot-console README, create a new top-level section called `Reset Process (for QA/Stage)`, and in that section document the following:

- [x] Verify what needs resetting (deleting) is the following:
  * Redis: `redis://sul-robots-redis-{qa,stage}.stanford.edu:6379/`
- [x] Determine what needs re-seeding (re-creating) in the app
- [x] Determine what needs re-seeding in SDR (e.g., APOs, collections, agreements, & canonical objects)
- [x] Determine how to reset and re-seed ☝🏻 (e.g., DB drop/create/migrate, specific DB table drops, `rm -rf`, export/import steps)

**Comment by aaron-collier** [comment]
Robot console is quite basic and does not directly link to a db/storage/etc, so resetting will be easy. One consideration will be when or if to clear redis, but that can be part of the process documentation.
