### ISSUE TITLE
Figure out how to reset Access team components

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#4063]
Feel free to split this into smaller tickets.

* purl
* stacks
* purl-fetcher
* exhibits
* arclight
* searchworks (+ indexer)
* earthworks
* media server (wowza)
* image server (canteloupe)

**Comment by mjgiarlo** [comment]
From Andrew:

> If it makes things easier on the Access systems, I think it would be do-able to make everything dark and unrelease before deleting anything.
> Or if that’s the best way to check what impact there might be.

**Comment by justinlittman** [comment]
Based on standup discussion, backlogging until @mjgiarlo is back.

**Comment by ndushay** [comment]
We'll do a bulk unrelease/darken to deal with access team projects;  this can be closed.

**Comment by jcoyne** [comment]
Unrelease and darken is not sufficient as it will cause a bunch of orphan data to remain on the image/video/geo/stacks servers.

**Comment by mjgiarlo** [comment]
@jcoyne 💬 
> Unrelease and darken is not sufficient as it will cause a bunch of orphan data to remain on the image/video/geo/stacks servers.

Our understanding is that the unrelease step should remove data from SearchWorks & EarthWorks, and that the darken step should remove files from the stacks, both operating against current SDR objects in QA and stage. Though we are not aware of any way to remove data from the geoserver, and at the same time we don't know anyone who actively uses the geo stage instance other than the Infra integration test for geo objects, plus the only geo objects on stage are from said integration test.

Are you thinking this is insufficient for _current_ SDR objects? We're all ears re: other steps we should consider running.

Or are you more concerned with SDR data _orphaned by past QA & stage resets_? We would like to avoid blocking an otherwise thoroughly planned reset due to past less-thoroughly-planned ones.

**Comment by jcoyne** [comment]
> darken step should remove files from the stacks

Can you show me where the file removal happens?  My assumption was that this just changes the access metadata.

**Comment by mjgiarlo** [comment]
@jcoyne 💬 
> Can you show me where the file removal happens? My assumption was that this just changes the access metadata.

IIRC, that happens here via the `PruneService`: https://github.com/sul-dlss/dor-services-app/blob/main/app/services/publish/metadata_transfer_service.rb#L21

**Comment by jcoyne** [comment]
I don't see where that touches anything in stacks. Doesn't PruneService just clear out the working druid tree?

**Comment by ndushay** [comment]
https://github.com/sul-dlss/dor-services-app/blob/main/app/services/shelving_service.rb#L31

calls

https://github.com/sul-dlss/dor-services-app/blob/main/app/services/digital_stacks_service.rb#L9

**Comment by mjgiarlo** [comment]
@ndushay has the right info above. You're right that the PruneService only clears the PURL documents.

**Comment by jcoyne** [comment]
@ndushay I don't see where/how that removes dark files from stacks. Can you show me?

**Comment by andrewjbtw** [comment]
I don't know where it is in the code but making something dark changes shelve and publish to "no" and the files get removed when accessioning runs. It looks like the stacks directory gets left behind.

**Comment by mjgiarlo** [comment]
FWIW, I just made an object dark in stage and it removed its file from stacks, confirming what Andrew has found to be true. It would be good for us to better understand how/when this is done. cc: @sul-dlss/infrastructure-team

**Comment by jcoyne** [comment]
Do we need to make sure the derivatives in the image server cache are purged or are we okay if these are still served after the underlying object is deleted?  How about video derivatives made by the streaming server?

**Comment by andrewjbtw** [comment]
Those are both prod questions, since making something dark is part of how we process takedown requests. I have not heard reports of content persisting too long after being made dark.
