### ISSUE TITLE
CatalogRecordIdsController - add comment

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#4093]
Setting up argo for the ILS switch was a GIANT PR #3969.

I confess I don't understand the CatalogRecordIdsController;  perhaps it is still useful/needed.  If so, please do a PR that adds a comment to clarify the context in which the controller is used;  if not, please make a PR to remove it.

**Comment by justinlittman** [comment]
It is the controller for CRUDing catalog record ids.

<img width="1149" alt="image" src="https://github.com/sul-dlss/argo/assets/588335/b1db4651-e69a-4e2d-af84-484a5598fd0d">

**Comment by ndushay** [comment]
can you please do a PR with a comment?  Or am I being ridiculous?

**Comment by justinlittman** [comment]
I did add a comment: https://github.com/sul-dlss/argo/commit/ee176c00889b921395591ff3361da8c56cecc61e
