### ISSUE TITLE
Add facet to identify items that have DOIs and/or ORCIDs

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4096]
It would be very useful to be able to identify all items in SDR that:

1. Have a DOI
2. Have at least one ORCID in the metadata
3. Have other identifiers like RORs if we're supporting them

Open questions:

- What to name the facet ("Identifiers"?)
- Whether we can identify items where the DOI was manually assigned prior to the H2-DOI workflow

**Comment by ndushay** [comment]
facet name has been chosen:  "identifiers"

We need to :
- probably no solr config changes for argo ... use a "dynamic" field name
- code in dor-indexing-app to do the indexing
- adjustments to argo so the facet is displayed - this is blacklight configuration with many levels of indirection in Argo -- this is likely an excellent pairing opportunity

See ORCID id extraction helper in ?orcide client gem? or ask JLitt where this code lives.


We have a small number (< 20) of DOIs assigned by hand.  Naomi thinks these are hardcoded somewhere (cocina-models?   dor-services-app?  h2?).   Amy has the list, too.

**Comment by peetucket** [comment]
See https://github.com/sul-dlss/orcid_client/blob/main/lib/sul_orcid_client/cocina_support.rb#L22-L25 for code that adds ORCIDS

Examples with ORCID and DOI: https://purl.stanford.edu/yr775yn6440

**Comment by peetucket** [comment]
ORCID Example:

```
"description": ⊖{
        "title": ⊕[1 item],
        "contributor": ⊖[
           ⊖{
                "name": ⊕[1 item],
                "type": "person",
                "status": "primary",
                "role": ⊖[
                   ⊖{
                        "value": "author",
                        "code": "aut",
                        "uri": "http://id.loc.gov/vocabulary/relators/aut",
                        "source": ⊕{2 items}
                    }
                ],
                "identifier": ⊖[
                   ⊖{
                        "value": "0000-0003-3863-3762",
                        "type": "ORCID",
                        "source": ⊖{
                            "uri": "https://orcid.org"
                        }
                    }
                ]
            },
```

DOI example:

```
    "identification": ⊖{
        "catalogLinks": [],
        "doi": "10.25740/yr775yn6440",
        "sourceId": "hydrus:object-7030"
    },
```
