### ISSUE TITLE
Differences in title between results and detail

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#411]
Here's a good set of data that illustrate the situation:

![screen shot 2016-01-04 at 3 51 28 pm](https://cloud.githubusercontent.com/assets/1824732/12104043/86942cd6-b2fc-11e5-98bf-2c304f54156b.png)

Note the title on the results page vs the detail page:

![screen shot 2016-01-04 at 3 51 39 pm](https://cloud.githubusercontent.com/assets/1824732/12104048/941aee3a-b2fc-11e5-92b0-1a07d120b3d0.png)
![screen shot 2016-01-04 at 3 51 58 pm](https://cloud.githubusercontent.com/assets/1824732/12104047/9418b52a-b2fc-11e5-8ef8-4e610d5168ea.png)

This touches on a fairly long standing problem we've had with handling an object's title because of three potential sources ... descMetadata, DC, and Fedora's object label. A fourth source, <objectLabel> in identityMetadata, is long abandoned and can be ignored. The background is this ...

We rely on descMetadata as the best/proper source of title. In particular, <title> from MODS. Recognizing that MODS may not be present (or always be what's in descMetadata), we said we'd try to have dc:title reflect an object's current/correct title, making that a second choice for accurate title.  Finally, the fedora label is a fallback for brand new objects lacking any descriptive metadata. It should only be used in the absence of the others.

While the data in this collection should be remediated to eliminate the difference between MODS and DC, this is still a weak area.  What SOLR field does Argo use for the results vs detail page? If it is indeed solr for both, then they should likely be the same, unless there is a chance either or both could end up without a title showing.

Setting this as a question for now since it needs more analysis.

**Comment by mejackreed** [comment]
It seems as if both "index" and "show" views are configured to use the `dc_title_ssi` field for displaying of titles. See: https://github.com/sul-dlss/argo/blob/develop/app/controllers/catalog_controller.rb#L24 & https://github.com/sul-dlss/argo/blob/develop/app/controllers/catalog_controller.rb#L27. 

Yet in the "show" view we use a custom method to render something else which includes an artisanal display of the following fields: 
 - `public_dc_creator_tesim`
 - `dc_creator_tesim`
 - `public_dc_title_tesim`
 - `dc_title_tesim`
 - `obj_label_tesim`
 - `originInfo_place_placeTerm_tesim`

https://github.com/sul-dlss/argo/blob/develop/app/helpers/dor_object_helper.rb#L24-L32

What approach would you like to take here?

**Comment by LynnMcRae** [comment]
Index is the search results page and Show is the detail page? The set of fields creates a short bibliographic citation, which is shown in both places in production Argo ...
![screen shot 2016-01-07 at 9 15 41 am](https://cloud.githubusercontent.com/assets/1824732/12177080/4d119820-b51f-11e5-9d5c-587d44bf05a8.png)
![screen shot 2016-01-07 at 9 15 55 am](https://cloud.githubusercontent.com/assets/1824732/12177079/4d0e1eb6-b51f-11e5-83ef-8ee05d023a78.png)

Unlike the typical Blackllight application, where a title only needs to head the listing because bibliographic details follow in both views, this is the only place in Argo where the bibliographic content is summarized for identification and recognition. So I'd like to keep that in both places.

**Comment by mejackreed** [comment]
@LynnMcRae yes sorry about the mixed vocab use :) .. 

index = results
show = detail

So the idea here is to use the citation for both view titles, correct?

I don't think this will be a problem at all, implementing using the Blacklight `Presenter` pattern. https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View#title_field

**Comment by LynnMcRae** [comment]
yes, citation for both view titles.

**Comment by LynnMcRae** [comment]
There is a backlog bug that didn't get moved to github concerning multiple titles for one object, as shown here:
![screen shot 2016-01-07 at 2 48 44 pm](https://cloud.githubusercontent.com/assets/1824732/12185074/e32bb5e2-b54d-11e5-9c4d-c02e765094a0.png)

coming from here I believe:
![screen shot 2016-01-07 at 2 48 14 pm](https://cloud.githubusercontent.com/assets/1824732/12185140/1d3a327c-b54e-11e5-80cb-ab23a8efd704.png)

We'd rather just show the main title, which could mean the first instance of that solr field, or the explicit _0_ instance from here.
![screen shot 2016-01-07 at 2 46 41 pm](https://cloud.githubusercontent.com/assets/1824732/12185181/539def48-b54e-11e5-8c30-3296653b94fc.png)

Not a +1 priority for sure so could be moved to a separate backlog ticket if not addressed here.

**Comment by mejackreed** [comment]
I'm not sure what this means?

I've already created a fix for this issue using the citation method you mentioned #427. Do we want that citation created differently?

**Comment by LynnMcRae** [comment]
yes, this is a tweak to the rules of creating the citation. Happy to move it to it's own ticket.
