### ISSUE TITLE
Modal error display

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#412]
Not a bug (beyond something hiccuping in stage) but rather just sharing this image of the modal for a formatted workflow when something -- I'm guessing WF services -- aren't working. Maybe you haven't seen it or would just like to see it in action ...
![screen shot 2016-01-05 at 12 17 37 am](https://cloud.githubusercontent.com/assets/1824732/12110542/0e3d0064-b342-11e5-9240-3ad40984d55a.png)

**Comment by mejackreed** [comment]
Can you send a link of where this is happening please? Everywhere? dev? stage?

**Comment by LynnMcRae** [comment]
Stage only, for any attempt to display a workflow. But WF seems to be back up now so this isn't happening.
