### ISSUE TITLE
Disentangle web-archiving-stacks QA/stage mounts

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/argo#4127]
Currently, qa and stage environments use the same `/web-archiving-stacks` and `/was_unaccessioned_data` shared mounts. This means that was-pywb-stage and was-pywb-qa end up using the same CDXJ indexes and warcs, which can be confusing since the content was accessioned in different environments by upstream apps. 

As part of QA/stage reset, set up a new NFS share for stage, mounted at `/web-archiving-stacks` for:
- [x] was-pywb-stage
- [x] was-robots1-stage
- [x] common-accessioning-stage-a
- [x] common-accessioning-stage-b
- [x] sul-preassembly-stage
- [x] was-registrar-app-stage

**Comment by edsu** [comment]
I noticed that `sul-preassembly-stage` and `was-registrar-app-stage` were missing from the list.

**Comment by edsu** [comment]
These web archiving environments also share `/was_unaccessioned_data` (updated description).

**Comment by edsu** [comment]
I added an ops ticket to create the two new storage locations for Stage: https://github.com/sul-dlss/operations-tasks/issues/3450

**Comment by edsu** [comment]
The new mounts are up! I'm going to run integration tests in both environments to see what's broken.

**Comment by edsu** [comment]
I had to create some directories and touch some files to get the stage integration tests to pass:

```
$ mkdir -p /web-archiving-stacks/data/indexes/cdxj/
$ mkdir -p /web-archiving-stacks/data/collections/
$ mkdir -p /web-archiving-stacks/data/indexes/cdxj_working/
$ touch /web-archiving-stacks/data/indexes/cdxj/level0.cdxj
$ touch /web-archiving-stacks/data/indexes/cdxj/level1.cdxj
$ touch /web-archiving-stacks/data/indexes/cdxj/level2.cdxj
$ touch /web-archiving-stacks/data/indexes/cdxj/level3.cdxj
```

The QA environment worked fine.
