### ISSUE TITLE
"Download all files" option can crash Argo when invoked on large objects

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4133]
**Describe the bug**
It looks like downloads of large objects from Argo using the "download all files" option to create a zip can crash Argo.

The associated HB error is: https://app.honeybadger.io/projects/49894/faults/65734574

Multiple attempts to download [this object](https://argo.stanford.edu/view/sj917wc8897) (the one in the HB error) have resulted in one or both Argo nodes locking up, with Ops needing to reboot.

I replicated that object in stage and tried to download it and that crashed argo-stage: https://argo-stage.stanford.edu/view/druid:sc263ks6367

Total preserved size for that object is 20 GB.

**User Impact**
Argo becoming unstable is a problem for anyone. For the user who tries to download the files, they don't see that something has gone wrong. The browser just spins.

**To Reproduce**
1. Go to my test object: https://argo-stage.stanford.edu/view/druid:sc263ks6367
2. Try to download all files
3. Leave the browser tab open and attempting to download
4. Wait for Argo to crash

It may take more than one download attempt in close succession to cause a crash.

**Expected behavior**
We've always had problems downloading large zips but I don't remember Argo crashing if it timed out. In testing with hierarchical files back in January, I attempted to download large zips and don't remember Argo crashing. But I'm not sure I downloaded up to 20 GB.

**Additional context**
H2 had a similar problem with single-file downloads that we fixed recently. Argo single-file downloads don't cause crashes.

**Comment by ndushay** [comment]
JLitt thinks there are more and less memory efficient ways to do this;   "zipline" and "zipxxxx" ... see what is used elsewhere.

For testing, Andrew has an object in stage that will "take down stage"

**Comment by peetucket** [comment]
Possible gems referenced in discussion:

https://github.com/WeTransfer/zip_tricks  
https://github.com/fringd/zipline
