### ISSUE TITLE
Response modal from Reindex has display issues

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#415]
The response from reindexing blue button is to show status plus the entire resulting new solr doc.  It has some formatting issues, cosmetic only, but perhaps including this big wad of data seems pointless given we can view the solr document directly from the detail page now.  Omit it? Just give status=ok vs error?

![screen shot 2016-01-05 at 3 44 46 pm](https://cloud.githubusercontent.com/assets/1824732/12130951/7c576130-b3c3-11e5-82ff-893378210340.png)

**Comment by mejackreed** [comment]
What is helpful to you? It's easy to do the "status: ok". Is anyone going to read through the solr doc?

**Comment by LynnMcRae** [comment]
just a final status, positive or negative.  If you want the solr doc you have access to it any time from the detail display.

**Comment by mejackreed** [comment]
Ok I think the work here is to remove the modal entirely and just use flash messages as we do other places to show an action's status.
