### ISSUE TITLE
Update Embargo modal problems

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#416]
https://argo-dev.stanford.edu/catalog/druid:bs277kf6370

Press the Update Embargo button .... the button goes dark (it's processing) but nothing happens for quite a long time for me.  When the form finally shows up, it looks like this:
![screen shot 2016-01-05 at 3 53 01 pm](https://cloud.githubusercontent.com/assets/1824732/12131117/a67a7136-b3c4-11e5-91d8-724312410b5e.png)

The Cancel button does nothing. The update works but the underlyiong screen should be refreshed to show the new date. (note new date of 4/1/17 in upper right metadata, old date still showing in lower left)
![screen shot 2016-01-05 at 3 56 21 pm](https://cloud.githubusercontent.com/assets/1824732/12131160/0b7a40e8-b3c5-11e5-9f9e-3350183f2f76.png)

**Comment by drh-stanford** [comment]
I'm seeing the corrrect, modern modal dialog on the current develop branch:

![screen shot 2016-02-08 at 2 24 16 pm](https://cloud.githubusercontent.com/assets/1861171/12901326/d95a5272-ce6f-11e5-8233-51ee3cfa8e0f.png)

I do see a couple other problems though. The date picker is broken:
![screen shot 2016-02-08 at 2 24 37 pm](https://cloud.githubusercontent.com/assets/1861171/12901343/f52335e6-ce6f-11e5-8304-c8f0c20c766f.png)

And the form submission isn't working on the developer fixtures:

![screen shot 2016-02-08 at 2 25 23 pm](https://cloud.githubusercontent.com/assets/1861171/12901364/0ad62560-ce70-11e5-8423-c3a9089d0290.png)

**Comment by drh-stanford** [comment]
The lower left embargo date isn't showing up because the index isn't being synchronously update and that data comes from the index right now

**Comment by drh-stanford** [comment]
@LynnMcRae can you provide an example druid that has valid `rightsMetadata` and `embargoMetadata` for an embargoed item? 

The code in dor-services is looking for the `embargoReleaseDate` in `rightsMetadata` which seems wrong to me, and failing if it doesn't see it. See https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/models/embargoable.rb#L71-L73

**Comment by LynnMcRae** [comment]
@drh-stanford let's chat briefly in the morning for context. Embargo is controlled via the embargoMetadata datastream, where embargo date changes should be first recorded.  This date is copied into the rightsMetadata only during the period in which it is in effect; it is what actually puts the item in embargo and creates the Embargoed status. I think the rights copy is the indexed date that the embargo maintenance process reads when it does its query to wit "find all items currently embargoed with a date less than today".

**Comment by drh-stanford** [comment]
how does one actually set the embargo information for an item? is that a scriptie or robot or Argo?

**Comment by LynnMcRae** [comment]
I think there's a dor service method for that in the embargoable concern. There doesn't seem to be a web services exposure if this page from Willy is up to date -- https://consul.stanford.edu/display/chimera/REST+mappings+for+dor-services+gem

**Comment by drh-stanford** [comment]
I'm not seeing it anywhere. There's an example rightsMetadata here: https://github.com/sul-dlss/dor-services/blob/e1f68a3a02586f04dd2f380e9018a8be2a96d112/spec/dor/embargoable_spec.rb#L39

but no code that writes to rightsMetadata.

@blalbrit in production, how does one set an embargo for an item? is it done prior to accessioning?

**Comment by LynnMcRae** [comment]
there's an "update_embargo(new_date)", line 63 in dor-services/lib/dor/models/embargoable.rb

That lets you change an embargo date. Not seeing where you would set an embargo in the first place.

**Comment by LynnMcRae** [comment]
The blue button only lets you update an embargo already in place, because setting embargo means building an embargoMetadata datastream and establishing before and after rights.  In argo-stage you can open the Embargo Release Date facet and see 7 examples there, e.g., https://argo-stage-b.stanford.edu/catalog/druid:gt473qx0315

**Comment by LynnMcRae** [comment]
Those examples seem to be past their embargo date so they don't show an active embargo ... I will set one up for you. I do notice it activates the Update Embargo Date button after the embargo is no longer in effect, which leads to an error.  I will do a separate ticket for that (not a blocker)

**Comment by LynnMcRae** [comment]
An ETD that is currently under embargo.

https://purl.stanford.edu/bj707wq1478
https://argo.stanford.edu/catalog/druid:bj707wq1478

**Comment by LynnMcRae** [comment]
Note that the date picker is also broken in the same way for the date related facets. Should there be a separate ticket for those?

**Comment by drh-stanford** [comment]
Yeah looks like it's a app-wide problem. I'd say another ticket makes sense.
