### ISSUE TITLE
releaseWF (update-marc) failing for folio HRID a14260154

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4174]
**Describe the bug**
There are two druids associated with FOLIO HRID a14260154 and both are failing at the update-marc step of the releaseWF. I've retried the steps a few times over a period of a few days and I don't think it's a FOLIO performance problem.

The error messages seem to refer to fields in the data:

For https://argo.stanford.edu/view/druid:rt427mn4843:
>update-marc : problem with update-marc (BackgroundJob: 29146910): {:errors=>[{:title=>"Update MARC error", :detail=>"Unexpected response: 400 {\"message\":\"Parameter 'fields[8].content' must not be null\",\"type\":\"-1\",\"code\":\"BAD_REQUEST\"}"}]} 

For https://argo.stanford.edu/view/druid:yv907rt4675
>update-marc : problem with update-marc (BackgroundJob: 29146911): {:errors=>[{:title=>"Update MARC error", :detail=>"Unexpected response: 400 {\"message\":\"Parameter 'fields[6].content' must not be null\",\"type\":\"-1\",\"code\":\"BAD_REQUEST\"}"}]} 

**User Impact**
The MARC record is not being updated for these items.

**To Reproduce**
1. Go to one of the druids above in Argo
2. Retry the update-marc step
3. Wait a while

**Comment by lwrubel** [comment]
When I look at the source record in Folio, there are some odd-looking empty 050 and 052 fields: https://folio.stanford.edu/inventory/viewsource/8247ae7a-c3f3-5d1c-9d30-4291c74ab529?qindex=hrid&query=a14260154&sort=title. When retrieving the MARC JSON from the quickMarc API, it shows these fields as:
```
{
      "tag": "050",
      "indicators": [
        "\\",
        "4"
      ],
      "isProtected": false
    },
    {
      "tag": "052",
      "indicators": [
        "\\",
        "\\"
      ],
      "isProtected": false
    },
    {
      "tag": "052",
      "indicators": [
        "\\",
        "\\"
      ],
      "isProtected": false
    },
    {
      "tag": "245",
      "content": "$a [Oostbevelandpolder aan de Oosterschelde.]",
      "indicators": [
        "1",
        "0"
      ],
      "isProtected": false
    },
```
Note how there is no `content` field in the tag JSON, as there is for the 245. Is this valid MARC? Might be the reason why sending that MARC JSON back is causing these errors.

**Comment by ndushay** [comment]
@andrewjbtw will contact the right person (or close to it) that can fix the data.

**Comment by andrewjbtw** [comment]
Source MARC record has been remediated and release has now succeeded. For future occurrences of errors like this, who to contact will depend on who is responsible for the content in question. In this case, I ultimately contacted the person who recently released the record. Fortunately, there should be a sunetid associated with each release.
