### ISSUE TITLE
[WIP] Governing items by non-existing APOs causes Rails exception display

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/argo#418]
In an attempt to reproduce #334 using instructions from @drh-stanford (update the RELS-EXT datastream so a regular item is governed by a non-existing APO) I get the dreaded Rails exception display. This is likely related to #405 - while I realize that Argo cannot always be robust in the face of willfully or accidentally invalid input, I don't think this error is even remotely useful to anyone.

![rels-ext-bug](https://cloud.githubusercontent.com/assets/3740294/12157653/16b4adc2-b488-11e5-8303-747c29657ed1.png)

**Comment by tingulfsen** [comment]
I just had a conversation with @LynnMcRae about this.

Reindexing should not fail if the APO is invalid. It should succeed, and then populate the "Admin Policy" title field with a canonical message such as "APO not found" or just populate it with the druid itself. Clicking on this title field link should just take you to the regular "Object Not Found" page that you currently get when attempting to access a druid that doesn't exist.

So there is more work to be done on this, and #334 and #405

**Comment by LynnMcRae** [comment]
Per #334, same rules for faulty APO or collection reference that gets expanded to a title. I think this will also appear in facet behavior, where we'd see the placeholder we chose listed there -- individual druids vs canonical "not found" text. I think I'd prefer to see the druids as the title substitution, so bad boys would be listed separately but together (by the "druid:" prefix) in the facet. They should be rare regardless.

**Comment by jmartin-sul** [comment]
since that would require change in indexing behavior, that also implies a change in a `to_solr` method in dor-services.

**Comment by jmartin-sul** [comment]
also, :+1: to the suggestion of showing the druid in the field instead of a generic "APO not found"
