### ISSUE TITLE
Question: what is the "last modified" facet indexing?

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4184]
Argo has a facet labeled "Last modified" - how is "modified" defined for purposes of this facet? I'm evaluating facets for usefulness and I don't know what this one is supposed to be indexing.

<img width="418" alt="Screenshot 2023-09-22 at 5 46 40 PM" src="https://github.com/sul-dlss/argo/assets/8975583/1a733fdc-4eaf-42b6-9302-bbd8fcf18d04">

**Comment by andrewjbtw** [comment]
Argo has a facet labeled "Last modified" - how is "modified" defined for purposes of this facet? I'm evaluating facets for usefulness and I don't know what this one is supposed to be indexing.

**Comment by justinlittman** [comment]
This is the time the database record for the item in DSA was last updated. Ultimately, here is where it comes from: https://github.com/sul-dlss/dor-services-app/blob/main/app/models/repository_record.rb#L20

**Comment by andrewjbtw** [comment]
Thanks. I'll have to think about whether that provides value that we don't get from "last accessioned".
