### ISSUE TITLE
Remove the "Last submitted" and "Last ingested" facets

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4185]
These two facets don't provide useful information.

<img width="418" alt="Screenshot 2023-09-22 at 5 51 31 PM" src="https://github.com/sul-dlss/argo/assets/8975583/54de1f86-4061-4441-aa10-b6cb2b057b54">

**Comment by ndushay** [comment]
a before and after screen shot in the PR would make review easier.
