### ISSUE TITLE
Source id: Support searching for partial matches

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4194]
As noted in #687, it's possible to search for source ids in Argo, but you have to enter the source id in its entirety and put the whole string in quotation marks. Many users would benefit from being able to get results based on partial matches.

Examples

[Exact match on "sul:M2549_2022-326_yock"](https://argo.stanford.edu/catalog?search_field=text&q=%22sul%3AM2549_2022-326_yock%22) - 1 result

[Search for just M2549](https://argo.stanford.edu/catalog?search_field=text&q=m2549) - no results

Since we have to have limits to how partial a partial match can be - it would be absurd to search for 'M' or '25' - I propose that we consider a partial match to be:

- taken from the part of the string after the colon (not "sul")
- the partial match has to start with the same characters as the exact match ("M2549" but not "yock")

I'm open to other possibilities based on what solr may actually support.

**Context**

Source ids often represent a very compressed form of collection metadata. In the example above, M2549 is a manuscript collection number. In Argo, the manuscript collection number may be entered only in the source id and nowhere else depending on how an item is described. Being able to search for partial matches in source ids would increase users ability to find materials in Argo.

**Comment by ndushay** [comment]
Some values (to help with tokenization):

```
branner:virtualShanghai_Buildings.shp
branner:virtualShanghai_Prefectures_1909_V1.shop
Archiginnasio:Bassi_Box10_Folder1
Archiginnasio:Bassi_Box10_Folder2_Item1
Archiginnasio:Bassi_Box10_Folder2_Item3.14
BNF:Francais24440
BNF:NAF_6223
BNF:f_fr_1149
CAL_ARCH:13130070
Revs:2012-015GHEW-CO-1980-b1_1.16_0007
branner:EStat_hemp_DataQuality_HarvestedArea.tif
evis:IRAQ-1953-12-07_01
googlebooks:stanford_36105012204280
sul:M2856_2022-330_CM001_e7f849d171bcdfbe87faf52b28e5c3cd
radarFilm:53_p2_0003525_0003549-reel_begin_end.tiff
sul:CSt-078-2312
sul:PC0139_2018-037_Packard_Bldg_stairwell_2014_13_4892
sul:PC0139_2018-037_Pomegranate_Battery_Fig1_A_680x270
sul:PC0170_s3_UC_Davis_2005-09-17_183220_095
sul:SC0280_1983-020_b03_f01_027
sul:SC0280_2010-092_earthquake_damage_b01_f02_i002
sul:SC0280_s1_ss1_hh_57c
sul:sc1125_s02_b50_08-0924-1b_siepr
sul:sc1125_s2_b47_i10-1014-2b
sulair:M1711_Series4_Box5_Folder4
sulcons:8552-RB_Miscellanies_agabory,Before treatment photos

```

**Comment by ndushay** [comment]
existing fieldTypes:
- text
- text_ws
- textNoStem
- text_en

**Comment by ndushay** [comment]
text:

<img width="526" alt="image" src="https://github.com/sul-dlss/argo/assets/96775/8dc0274e-0a08-4f40-a2f6-6baae19adfcf">

Revs:2012-015GHEW-CO-1980-b1_1.16_0007

text_ws: 

<img width="402" alt="image" src="https://github.com/sul-dlss/argo/assets/96775/e720dc08-3730-4d31-b05c-5d91558cf063">

textNoStem:

<img width="1055" alt="image" src="https://github.com/sul-dlss/argo/assets/96775/e08beb25-7955-4100-bbd2-124fc5edd161">

text_en:

<img width="572" alt="image" src="https://github.com/sul-dlss/argo/assets/96775/883d9261-c916-4b98-847c-43b543a83a1f">

**Comment by ndushay** [comment]
I think we want **textNoStem**

<img width="1242" alt="image" src="https://github.com/sul-dlss/argo/assets/96775/66665a3d-ce4c-4a8d-9668-8e2286990793">

**Comment by ndushay** [comment]
- sul-solr config files updated for source id tokenized field, and for experimental searcher
    - [x] argo_qa
    - [x] argo_stage
    - [ ] argo_prod
- dor_indexing_app populates new field `source_id_text_nostem_i` with tokenized source id
   - [x] argo_qa - via deployed branch
   - [x] argo_stage - via deployed branch
   - [ ] argo_prod
- [ ] have way to use experimental searcher for side-by-side comparisons for Argo
- [ ] dor_indexing_app change merged to main
    - [ ] deployed to prod
- [ ] argo solr prod `source_id_text_nostem_i` has begun populating
- [ ] argo solr prod field has been populated
- [ ] update Argo solr and/or app to use new field for searching by default.

**Comment by ndushay** [comment]
Progress report on indexing:

<img width="803" alt="image" src="https://github.com/sul-dlss/argo/assets/96775/15dc19c5-15ca-4d34-8e4e-346747171584">

vs

<img width="694" alt="image" src="https://github.com/sul-dlss/argo/assets/96775/cfa27e79-691e-43c3-b6ee-612192a26bd9">

**Comment by ndushay** [comment]
Everything has been indexed since Oct 20 (from Solr query looking for oldest docs), so this is good to go.

**Comment by ndushay** [comment]
The work was done as:  https://github.com/sul-dlss/argo/issues/4231

Andrew wants to vet this;  this can go out stealthily as he intends to make a page for "searching strategies" or some such.
