### ISSUE TITLE
Solr cluster:  how do we deploy updates to our config files (schema.xml, solrconfig.xml, etc)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#4219]
Find out what is needed to get configuration file updates deployed to our Solr cluster.

I don't know where this documentation is;  you may want to check for READMEs and wikis in the sul-solr-configs repo, check devops docs, check developer playbook, and/or ask in the access channel.    It may be useful to add documentation for this, if it doesn't exist.

It's possible it's automagic, but I doubt it.

https://github.com/sul-dlss/sul-solr-configs/blob/master/README.md 

https://github.com/sul-dlss/sul-solr-configs/actions (seems to be a form of CI)

Some links below;  implication is we do something with zookeeper ...
https://github.com/sul-dlss/DevOpsDocs/blob/master/projects/sul-solr/operations-concerns.md

**Comment by justinlittman** [comment]
Make an update in https://github.com/sul-dlss/sul-solr-configs and then https://github.com/sul-dlss/sul-solr-configs#updating-configurations

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/dor_indexing_app/pull/1030 documents this.

**Comment by ndushay** [comment]
https://stanfordlib.slack.com/archives/C060ZTZRV/p1696953688615349 - I asked in slack, too.

**Comment by ndushay** [comment]
https://github.com/sul-dlss/sul-solr-configs#updating-configurations explains how to update the config files, not how to deploy these updates.  If it happens automagically, then that should be noted.  I even looked in github actions.

**Comment by ndushay** [comment]
Also https://stanfordlib.slack.com/archives/CJ0DQ8QSD/p1696954069757099 in ops channel.

**Comment by justinlittman** [comment]
Doesn't the README say that Ops does it?

**Comment by ndushay** [comment]
> Doesn't the README say that Ops does it?

See the slack thread.  Tony says he hasn't done it in years.  Access says Chris Beer is the only one who does it.

**Comment by ndushay** [comment]
Okay, PR was merged into sul-solr-configs to put info in the README.  I also did two PRs to further clarify stuff about Solr config for SolrCloud in the README:

- https://github.com/sul-dlss/sul-solr-configs/pull/273
- https://github.com/sul-dlss/sul-solr-configs/pull/274

I am now closing this as we have the answer, and it is documented in a place we would hopefully look.
