### ISSUE TITLE
add collection druid to search fields

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#4228]
@andrewjbtw please confirm that you want the items for a collection to be in search results for a collection druid.

Note that this is likely the bare druid as well as the druid with a prefix (copy field?  or do in dor_indexing_app.

strings for bare druid and for prefixed druid???

We will need to
1. index to the appropriate fields (use copy fields): schema.xml for copy fields, dor_indexing_app for others (dor-indexing-app)
2. wait for new fields to populate 
3. change solrconfig.xml to use new fields (sul-solr-configs) and test (argo)
4. stop indexing to old fields, if there are any
5. remove old fields from index, if there are any

**Comment by andrewjbtw** [comment]
I had not anticipated doing this. I'm not sure it's a good idea to change existing behavior where a search for a druid turns up exactly and only that druid.

**Comment by ndushay** [comment]
closing.
