### ISSUE TITLE
Left-side layout questions for Show view

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#423]
Is it possible to pin the max size of the left-sidebar containing the blue buttons?  While this looks reasonable ...
![screen shot 2016-01-07 at 9 52 24 am](https://cloud.githubusercontent.com/assets/1824732/12178135/bd2f314e-b524-11e5-81d7-96c71143dbb8.png)

Things start to look a bit silly the wider the buttons get, and I'd rather capture more of a wider screen for the body of the page.
![screen shot 2016-01-07 at 9 52 39 am](https://cloud.githubusercontent.com/assets/1824732/12178159/dfefe4f8-b524-11e5-9ee5-00c7d4c338f0.png)

It would be good to reduce or eliminate the double spacing of the "View in separate page" links. Could they be put in a box or something, very lightly ruled perhaps a la the separating line, the same width as the buttons, in order to visually square off the entire left sidebar?

**Comment by mejackreed** [comment]
WRT to the pinned size. We currently use the default Blacklight column layout to determine when these things break. The link list and button list will fit themselves to this column space automatically. Blacklight default column layout is "3" for the sidebar and "9" for the body. Long story short, we can't configure these until we get on to a later version of Blacklight which most likely we won't in this work.

We could change the button types that are appearing which would not string them out too long, but this wouldn't give you the desired additional body space. The reality here is we don't use a fixed size layout so close to break point edges things may look a bit strange.

WRT to the double spacing... I'm not really sure what you mean here. This is just another Bootstrap element type we are using. Maybe using them together isn't the best approach here?

**Comment by LynnMcRae** [comment]
I think fixing the size of the buttons (if that's what you are saying) would be nice to address the cosmetic angle, while I appreciate the sidebar growth question itself is a separate issue that can wait. I do note that the formula for the index/results page is a little different.  As for the stuff above the buttons, here's a mockup of what I mean for a cleaner, tidier look...
![sidebar](https://cloud.githubusercontent.com/assets/1824732/12179701/2da31d52-b52d-11e5-9393-bc17557f0a01.png)

**Comment by blalbrit** [comment]
@mejackreed @LynnMcRae - confirming that if this is really just a small shift in layout proportions, we'd like to make it part of the release - wanted to verify before making it a blocker

**Comment by mejackreed** [comment]
It's not a small shift in layout proportions. I would argue for not touching this until you prioritize upgrading Blacklight to latest 5.x release.

**Comment by andrewjbtw** [comment]
Blue buttons are no longer a thing in Argo.
