### ISSUE TITLE
Enable users to copy the facet data that shows values and counts

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4234]
We've received user feedback on Argo discovery and reporting that

- some users would like to be able to copy the value and count data that appears for each facet
- copying and pasting that data doesn't work well because it doesn't include a delimiter between the value and the count

For example, copying value and count data here:
> <img width="1160" alt="Screenshot 2023-10-12 at 11 01 51 AM" src="https://github.com/sul-dlss/argo/assets/8975583/5ee1f764-3a5e-46ff-831b-62ad16b957fa">

Comes out like this in a text file:

```
A Test Collection for Honors Theses Revised2Africana Librarians Council (ALC) Information Resources1Archive of Recorded Sound/Music Library - Supplemental Materials4Ashizawa family collection1BIOHOPK 47: Introduction to Research in Ecology and Ecological Physiology8BIOHOPK185: student videos12BIOHOPK185: time-series data4Berman Archive - test collection

```

And like this in a spreadsheet program

> 
<img width="669" alt="Screenshot 2023-10-12 at 11 07 28 AM" src="https://github.com/sul-dlss/argo/assets/8975583/f54c4a29-7d81-4293-9123-8c21262a0517">

Would it be possible to insert a tab before the count numbers? That would allow people to paste into spreadsheets and separate the values and counts into different columns.

**Comment by peetucket** [comment]
I've done some research here and don't have any easy solutions.  My findings are below:

1. Facets are rendered by Blacklight, so altering the HTML markup in the facets requires a change to the blacklight gem itself.
2. The facets are rendered by Blacklight as `<ul><li>` lists.
3. Copy and pasting the facet values/counts into Excel from any browser never splits the values out (as described in the ticket).
4. Copy and pasting the facet values/counts into a text editor DOES split the values apart, but only when using Chrome, Safari and Edge browsers.  Firefox fails to split as described the ticket.
5. If you use one of the browsers that does split the values when pasting into a text editor, you can then immediately copy the pasted text from the text editor, paste into Excel and ask it to split into columns, and this works as expected.
6. I experimented with adding a tab character (`&#9;`) into the HTML right before the facet value via Firefox DevTools and then Firefox worked the same as the other browsers (paste into text editor was ok, but not directly into Excel).

So... depending on the frequency with which this is done, could:

(1) see if users can use Chrome/Edge/Safari when doing this, and then use a text editor as a middle ground.
(2) make a change to Blacklight to add tab characters before facet values (to get same behavior in Firefox, assuming it doesn't break other formatting)
(3) look for other more complicated solutions ... which could be things like adding "export facet list" as a new Blacklight feature

**Comment by peetucket** [comment]
I'm experimenting with a different solution now which would add a "copy/paste" button that would turn the facet values/counts from the modal facet window into some formatted text on your clipboard.
