### ISSUE TITLE
cleanup specialized view logic for viewing derived Dublin Core metadata

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#425]
Re: `view/:id/dc` route. The view logic for the faux datastream `full_dc` looks like a technical debt issue (i.e., should just be a format toggle between human and XML rather than using a fake datastream name). 

https://github.com/sul-dlss/argo/blob/develop/app/views/catalog/_aspect_partials/_ds.html.erb#L26-L38

![screen shot 2016-01-07 at 11 02 01 am](https://cloud.githubusercontent.com/assets/1861171/12179865/2023e94e-b52e-11e5-855b-ba0f19ea7cd5.png)

Clicking 'View XML' leads to

![screen shot 2016-01-07 at 11 02 12 am](https://cloud.githubusercontent.com/assets/1861171/12179871/2827db5a-b52e-11e5-9011-5b4883fca529.png)

**Comment by mejackreed** [comment]
:+1: yep.. didn't dive into that stuff to touch it. Great catch
