### ISSUE TITLE
view-component gem is pinned ... and probably no longer needs to be

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#4255]
view-component gem is pinned for old and unclear reasons;   

https://github.com/sul-dlss/argo/commit/cf7206ee3021b946e3a0f959955bbb7bff198197

I posit we can unpin it and run with the current version.  But what do I know.

Obviously, argo would need to pass integration tests as well as CI.

**Comment by mjgiarlo** [comment]
The reason: it broke the build.

**Comment by justinlittman** [comment]
closed by #4297
