### ISSUE TITLE
 Missing 3D files on Stacks

### ISSUE THREAD

**Issue by edsu** [sul-dlss/argo#4261]
When retrieving 3D objects from Stacks for testing as part of https://github.com/sul-dlss/sul-embed/issues/1486 I discovered that the following files listed in published Cocina on PURL are not in Stacks when they should be:

- https://stacks.stanford.edu/file/druid:cw713nf4297/cw713nf4297_low.obj
- https://stacks.stanford.edu/file/druid:dx131fq2748/dx131fq2748_low.mtl
- https://stacks.stanford.edu/file/druid:dx131fq2748/dx131fq2748_low.obj
- https://stacks.stanford.edu/file/druid:hj807bj3315/hj807bj3315_low.mtl
- https://stacks.stanford.edu/file/druid:hj807bj3315/hj807bj3315_low.obj
- https://stacks.stanford.edu/file/druid:hv910hq2054/hv910hq2054_low.mtl
- https://stacks.stanford.edu/file/druid:hv910hq2054/hv910hq2054_low.obj
- https://stacks.stanford.edu/file/druid:kn053vd9828/kn053vd9828_low.mtl
- https://stacks.stanford.edu/file/druid:kn053vd9828/kn053vd9828_low.obj
- https://stacks.stanford.edu/file/druid:kw931zk7194/kw931zk7194_low.mtl
- https://stacks.stanford.edu/file/druid:kw931zk7194/kw931zk7194_low.obj
- https://stacks.stanford.edu/file/druid:mj575mr0028/mj575mr0028_low.mtl
- https://stacks.stanford.edu/file/druid:mj575mr0028/mj575mr0028_low.obj
- https://stacks.stanford.edu/file/druid:mk604sq8055/mk604sq8055_low.mtl
- https://stacks.stanford.edu/file/druid:mk604sq8055/mk604sq8055_low.obj
- https://stacks.stanford.edu/file/druid:mr889mt6604/mr889mt6604_low.mtl
- https://stacks.stanford.edu/file/druid:mr889mt6604/mr889mt6604_low.obj
- https://stacks.stanford.edu/file/druid:ng599cp8067/ng599cp8067_low.mtl
- https://stacks.stanford.edu/file/druid:ng599cp8067/ng599cp8067_low.obj
- https://stacks.stanford.edu/file/druid:nn143mb2991/nn143mb2991_low.mtl
- https://stacks.stanford.edu/file/druid:nn143mb2991/nn143mb2991_low.obj
- https://stacks.stanford.edu/file/druid:nr501pr5854/nr501pr5854_low.mtl
- https://stacks.stanford.edu/file/druid:nr501pr5854/nr501pr5854_low.obj
- https://stacks.stanford.edu/file/druid:pf224qt8732/pf224qt8732_low.mtl
- https://stacks.stanford.edu/file/druid:pf224qt8732/pf224qt8732_low.obj
- https://stacks.stanford.edu/file/druid:qg865md6137/qg865md6137_low.mtl
- https://stacks.stanford.edu/file/druid:qg865md6137/qg865md6137_low.obj
- https://stacks.stanford.edu/file/druid:qs187qh6138/qs187qh6138_low.mtl
- https://stacks.stanford.edu/file/druid:qs187qh6138/qs187qh6138_low.obj
- https://stacks.stanford.edu/file/druid:qw462sq8382/qw462sq8382_low.mtl
- https://stacks.stanford.edu/file/druid:qw462sq8382/qw462sq8382_low.obj
- https://stacks.stanford.edu/file/druid:rm209dn1639/rm209dn1639_low.mtl
- https://stacks.stanford.edu/file/druid:rm209dn1639/rm209dn1639_low.obj
- https://stacks.stanford.edu/file/druid:ry623qd1528/ry623qd1528_low.mtl
- https://stacks.stanford.edu/file/druid:ry623qd1528/ry623qd1528_low.obj
- https://stacks.stanford.edu/file/druid:sx729zw3968/sx729zw3968_low.mtl
- https://stacks.stanford.edu/file/druid:sx729zw3968/sx729zw3968_low.obj
- https://stacks.stanford.edu/file/druid:tv716wv3552/tv716wv3552_low.mtl
- https://stacks.stanford.edu/file/druid:tv716wv3552/tv716wv3552_low.obj
- https://stacks.stanford.edu/file/druid:tz363tx2275/tz363tx2275_low.mtl
- https://stacks.stanford.edu/file/druid:tz363tx2275/tz363tx2275_low.obj
- https://stacks.stanford.edu/file/druid:vj979rh4173/vj979rh4173_low.mtl
- https://stacks.stanford.edu/file/druid:vj979rh4173/vj979rh4173_low.obj
- https://stacks.stanford.edu/file/druid:vr995fg5919/vr995fg5919_low.mtl
- https://stacks.stanford.edu/file/druid:vr995fg5919/vr995fg5919_low.obj
- https://stacks.stanford.edu/file/druid:vt819fk1397/vt819fk1397_low.mtl
- https://stacks.stanford.edu/file/druid:vt819fk1397/vt819fk1397_low.obj
- https://stacks.stanford.edu/file/druid:wy419wt0225/wy419wt0225_low.mtl
- https://stacks.stanford.edu/file/druid:wy419wt0225/wy419wt0225_low.obj
- https://stacks.stanford.edu/file/druid:xr923qq8878/xr923qq8878_low.mtl
- https://stacks.stanford.edu/file/druid:xr923qq8878/xr923qq8878_low.obj
- https://stacks.stanford.edu/file/druid:xs224nv8477/xs224nv8477_low.mtl
- https://stacks.stanford.edu/file/druid:xs224nv8477/xs224nv8477_low.obj
- https://stacks.stanford.edu/file/druid:yn696tc5228/yn696tc5228_low.mtl
- https://stacks.stanford.edu/file/druid:yn696tc5228/yn696tc5228_low.obj
- https://stacks.stanford.edu/file/druid:zs853gr1088/zs853gr1088_low.mtl
- https://stacks.stanford.edu/file/druid:zs853gr1088/zs853gr1088_low.obj

The missing files means that sul-embed is unable to render them, for example:

https://purl.stanford.edu/vt819fk1397

![Screenshot 2023-11-03 at 3 50 19 PM](https://github.com/sul-dlss/argo/assets/33829/f9712e1f-17da-4b7d-bf74-e6cf4ea254a5)

It appears that these items do actually have the files in question, for example:

https://argo.stanford.edu/view/druid:vt819fk1397

The ticket was created here in Argo because it's likely that some curatorial actions will be required to get the files out where they need to be.

**Comment by andrewjbtw** [comment]
I believe I've gotten all of those files onto Stacks now.

**Comment by edsu** [comment]
Yes, they are all there now! Sometime I'd like to understand how you fixed it. I see from Argo version history it looked like a two step process?
