### ISSUE TITLE
New "Project" and "Tag" facets do not provide access to full facet hierarchy

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4273]
**Describe the bug**
Changing the Project and Tag facets has changed the behavior of the facets in a subtle way that is preventing users from accessing all top-level Project and Tag values from the Argo home page.

The problem is that the facet only shows values up to a certain point and then shows a "more" link:

Project facet:
> <img width="443" alt="Screenshot 2023-11-13 at 8 55 24 AM" src="https://github.com/sul-dlss/argo/assets/8975583/78c9eea0-0456-4955-b69c-9a850c59805f">

Tag facet:
><img width="443" alt="Screenshot 2023-11-13 at 8 56 18 AM" src="https://github.com/sul-dlss/argo/assets/8975583/4877bc86-596e-49fd-bbd1-d3802ff66e0b">

When you click on the "more" link, you get the same facet list in a modal with the same "more" link at the same place:

<img width="443" alt="Screenshot 2023-11-13 at 9 08 57 AM" src="https://github.com/sul-dlss/argo/assets/8975583/b4cdfa91-305f-4b2f-888d-0d28fde025ec">

Clicking on that sends you to the same modal with the same problem, forever. You can never get past the point in each list where the "more" link appears.

I'm not sure exactly what the previous cut-off point was for the "more" link but @oceanofsound reports that he used to be able to get at least as far as the SMPL tag, and that he never previously clicked on the "more" link. 

From what I remember, I also never clicked on the "more" link outside of looking at it when testing something. Unfortunately, stage does not have enough tags to trigger the "more" link so we didn't see the before and after there.

**User Impact**
Users have to find other strategies to get to the tag (Project or nonproject) they want. That might include searching for an item that has the appropriate tag, then clicking on the tag from there.

**To Reproduce**
1. See above: go to the Argo home page and expand the facets

**Expected behavior**
It should be possible to get to the full first level of the tag hierarchy. I know that in the previous implementation, you couldn't find all the tags from the Argo home page if you descended into a hierarchy but you could get to all (or almost?) all of the first-level tags. 

**Additional context**
Is there a depth first vs. breadth first setting? That is, is there a choice between loading the first N tags regardless of hierarchy or the first N tags measured by level of nesting. If there is, we should prefer loading all the first-level tags, then the next level, then the next, until the limit of tags to load is reached.

**Comment by ndushay** [comment]
should be fixed by #4274.

(how the heck did we get to over 4000 argo issues and PRs?)

**Comment by andrewjbtw** [comment]
Sadly, this was not fixed by #4274.

**Comment by andrewjbtw** [comment]
Some more information I've gathered on what has and has not changed

- the tag sidebar has always been limited to 9999 tags, but it's not clear how the "first" 9999 are gathered
- in the past, low-frequency tags, defined as tags used by only a small number of items, did not appear on the homepage
  - for an example, [see this conversation](https://stanfordlib.slack.com/archives/C0EAZ09QF/p1695326365754789) on the #dlss-aaas Slack channel
  - in that example from earlier this year, on the Argo home page, only two subtags were visible in the hierarchy of `DPG : SRWC-DPG Imaging
   - > <img width="529" alt="Screenshot 2023-11-13 at 4 23 41 PM" src="https://github.com/sul-dlss/argo/assets/8975583/b8fec03e-1bc7-4fe5-83f5-263437c0fc23">
- but currently, on the Argo home page, many more subtags are visible in the hierarchy of `DPG : SRWC-DPG Imaging
  - > <img width="390" alt="Screenshot 2023-11-13 at 4 21 40 PM" src="https://github.com/sul-dlss/argo/assets/8975583/b7d83928-1312-47d3-93cf-f176197e885e">
  - and generally speaking, the Project and Tag facets in the Argo sidebar show many tags where the number of items that use them is < 5

That leads to some questions: if Argo has always been using a limit of 9999 tags, what determines which tags make up the 9999? Could they be sorted or filtered differently than before?

I can imagine these two criteria would give dramatically different results:

- sort the list of tags alphabetically and show the first 9999
- sort the list of tags by frequency of use and show the first 9999

It looks like in the past some criteria led to low-frequency tags not displaying in the sidebar on the homepage, and only displaying when a search was limited in such a way that the low-frequency tags made it into the top 9999. If so, then we should change the criteria for the 9999 to match what was there before.

**Comment by ndushay** [comment]
aha - the inner results need to be sorted by frequency, but the outer ones need to be sorted alphabetically???
