### ISSUE TITLE
Incorrect collection titles on Create/Edit APO pages

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4275]
**Describe the bug**
The Edit APO page shows a list of "default" collections for the APO. A default collection is a collection that shows up as associated with the APO on the registration form dropdown menu. Users can selectively add and remove default collections from APOs.

Some of the collection titles displayed in this list on various APOs is wrong. It appears that when a collection title is changed, the change is not reflected in the display on the APO page.

Example: 

1. Open the Miller Library Special Collections APO edit page: https://argo.stanford.edu/apo/druid:xn852bm7072/edit

2. Look at the first collection title on the list. It says "Edward F. Ricketts Bibliographic Cards". This is incorrect.
> <img width="789" alt="wrong-title-apo-page" src="https://github.com/sul-dlss/argo/assets/8975583/c27127d5-6728-41dc-a637-3ede8a03780c">

3. Click on the link to view that collection page, where you can see that the collection actually has the title: "Pacific Biological Laboratories -- Bibliographic Cards". That's the title that should show in the Edit APO page.

>  <img width="1522" alt="correct-title-collection-page" src="https://github.com/sul-dlss/argo/assets/8975583/489da4f6-8bc1-4505-b64c-60ba2b532f62">

4. I think what's happening is that the Edit APO page is showing the "label" from Cocina:
> <img width="689" alt="cocina-label" src="https://github.com/sul-dlss/argo/assets/8975583/e410d976-d450-4645-8a98-2cab9294761a">

What should be showing is the title. The label is a legacy of Fedora and probably should not have been incorporated into the cocina model. The label is set once at registration time and never changed again. The title can be changed at any time and Argo should reflect that change.

**User Impact**
It's confusing and makes it difficult to see if a change in the collection list was made correctly.

**Expected behavior**
The current collection title should be shown. Since the APO stores the collection druid behind the scenes, it should be possible to get the current title using the metadata already available.

**Additional context**
This might be related to something @ndushay mentioned with respect to the Solr field for `obj_label_tesim`. We tried to remove that field and found it was being used somewhere on APO pages and in a couple of other places. Since that field indexes the cocina label, this might be where it's being used..

**Comment by ndushay** [comment]
@mjgiarlo i think you did the original work ... do you want to take this?   (no particular reason why you should)

**Comment by mjgiarlo** [comment]
@ndushay That has long since leaked through the cracks in my memory banks, so 🤷🏻‍♂️
