### ISSUE TITLE
Descriptive metadata import should validate relatedResource.type

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4280]
**Describe the bug**
Argo descriptive metadata spreadsheet import is accepting invalid values for `relatedResources*.type`. For example, the controlled vocabulary for `relatedresources.type` ([see full list](https://github.com/sul-dlss/cocina-models/blob/main/docs/description_types.md)) accepts `has other format`. But spreadsheet import is allowing uploads with `has other formats`. This then leads to errors.

Example on stage: 
- spreadsheet: [descriptive-tv115gn2241.csv](https://github.com/sul-dlss/argo/files/13385499/descriptive-tv115gn2241.csv)
- argo link: https://argo-stage.stanford.edu/view/druid:tv115gn2241

**User Impact**
Users should be notified of metadata validation errors at the time of import. Without that, hidden errors cause problems later in accessioning including preventing items from being made accessible on the purl.

**Comment by justinlittman** [comment]
Type validation is currently disabled until Arcadia completes remediation of bad types.

**Comment by andrewjbtw** [comment]
Just confirmed that type validation is now catching the issue (using the example spreadsheet provided in the ticket description). Closing.
