### ISSUE TITLE
Ignore CSV trailing lines that are blank except for commas and whitespace

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4316]
**Describe the bug**
When a CSV has rows that contain commas but no content other than whitespace, Argo reports an error at registration. Argo should ignore these blank lines if they come at the bottom of a CSV registration import.

The problem on the user side is that spreadsheet programs don't do a good job visually indicating when a spreadsheet has empty rows at the bottom of the sheet. For example, a spreadsheet with rows 1-10 filled in could:

- have only 10 rows
- have 15 rows but rows 11-15 are blank

In many common spreadsheet programs (Excel, Google sheets, etc.) those spreadsheets will be visually equivalent. The user only finds out they have extra rows if they save as CSV and then inspect the CSV in a text editor.

**User Impact**
This issue causes seemingly mysterious registration errors. To the user, the spreadsheet looks complete. But Argo reports an error message that suggests data is missing.

**To Reproduce**
1. Go to https://argo-stage.stanford.edu/registration
2. Select "Upload CSV" on the lower part of the page
3. Upload this CSV
[registration-stage-blanks.csv](https://github.com/sul-dlss/argo/files/14186373/registration-stage-blanks.csv)

<img width="1540" alt="Screenshot 2024-02-06 at 1 49 06 PM" src="https://github.com/sul-dlss/argo/assets/8975583/d5144837-c8d5-47e4-9847-f0565fcb4df4">

**Expected behavior**
Argo should ignore rows with no content at the end of the CSV. It makes sense to catch blanks that are in the middle of the CSV because that should also be a visible problem for the user creating the CSV. Because of the nature of how people copy and paste from CSVs, it's important to catch blanks in the middle of the CSV because it will throw off row alignments if the user copies from the registration report back into their original CSV.

**Comment by ndushay** [comment]
Is it okay if we ignore LINES that have nothing but empty space and commas, even if they are in the middle of the spreadsheet?  That will avoid having logic to determine if a blank line came from the end of the spreadsheet.

**Comment by ndushay** [comment]
Answer:  
<img width="389" alt="image" src="https://github.com/sul-dlss/argo/assets/96775/41da2574-c099-4b81-9ce5-818b2c531219">
