### ISSUE TITLE
Show a more informative error message when refresh metadata from FOLIO HRID triggers a validation error

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4326]
**Describe the bug**
When attempting to refresh metadata from a FOLIO HRID fails because of a validation error, a generic error message is posted to Argo:

> An error occurred while attempting to refresh metadata: Internal Server Error: 500 (Response from dor-services-app did not contain a body. Check honeybadger for dor-services-app for backtraces, and look into adding a `rescue_from` in dor-services-app to provide more details to the client in the future). Please try again or contact the #dlss-infrastructure Slack channel for assistance. 

At the same time, another error message is posted to HB that has more details: https://app.honeybadger.io/projects/50568/faults/104757394
> Cocina::Models::ValidationError: Blank value in description: note4.parallelValue2.structuredValue8

We should post the more detailed error message directly to Argo so users can see it.

Additionally, if this error is triggered in a bulk action metadata refresh, the more detailed error message should be posted to the log.

**User Impact**
Users have no way to tell what's wrong with the metadata refresh. When a validation error occurs in refresh, it's usually a sign that something didn't work in the MARC-MODS-Cocina mapping.

**To Reproduce**
1. Go to https://argo-stage.stanford.edu/view/druid:cg802fy9063 which is currently connected to a FOLIO HRID that will fail refresh
2. Click on "Manage description" and then choose "Refresh"
3. See the generic error
4. Check HB and see the more detailed error in dor-services-app

**Expected behavior**
Argo should display the more detailed error message if refresh is done on a show page. Argo should post the more detailed error message to the bulk action log if the error is triggered with bulk action refresh.

**Additional context**
In other contexts, Argo is able to show the more detailed error message. For example, if you try to register to the same FOLIO HRID, you get the validation error message:

<img width="885" alt="Screenshot 2024-02-27 at 10 27 18 AM" src="https://github.com/sul-dlss/argo/assets/8975583/b7a2093f-ea5d-4fe7-9376-8cfa9cbfcde6">

**Comment by justinlittman** [comment]
@andrewjbtw [druid:cg802fy9063](https://argo-stage.stanford.edu/view/druid:cg802fy9063) no longer produces the error on main, so I suspect either the Folio record or the mapping problem has been fixed:
![image](https://github.com/sul-dlss/argo/assets/588335/314a617c-c0db-4eee-bb67-6cf0832ac7fb)

**Comment by andrewjbtw** [comment]
The mapping may have been fixed here: https://github.com/sul-dlss/cocina-models/pull/690

**Comment by andrewjbtw** [comment]
We think this has been fixed.
