### ISSUE TITLE
Strip leading and trailing spaces from user-entered tags and Project tags

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4327]
**Describe the bug**
When a user enters a tag, strip any trailing or leading spaces. Users enter tags in the following places:

- registration form
- object show page
- bulk action tag import

Currently, we don't appear to strip tags.

**User Impact**
Leading and trailing spaces are causing tags to facet separately when to a human eye they look like they should be the same.

**To Reproduce**

I made three items in stage that use variations of the same tag of "a : tag":

- one has a leading space
- one has a trailing space
- one has no extra spaces
 
1. Go to this search result, which contains all three items https://argo-stage.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=trailing+leading+space+tag+testing
2. See the three different tags in the facet:

>  <img width="1200" alt="Screenshot 2024-02-27 at 10 55 59 AM" src="https://github.com/sul-dlss/argo/assets/8975583/0c089301-ff1a-400c-b8fa-8be90561e075">

**Comment by mjgiarlo** [comment]
@andrewjbtw To fix this, I think the simplest way would be to add a line to DSA that normalizes admin tags to strip leading and trailing spaces. It's a small and easy change to make. 

That doesn't help with currently persisted bad data in prod, though. From the prod console, there appear to be 49 unique tag labels that have the problematic whitespace:

```ruby
> TagLabel.where("tag LIKE '%\s' OR tag LIKE '\s%'").count
 => 49 
```

And here's a count of how many administrative tags are currently using each tag label with leading/trailing whitespace:

```ruby
> TagLabel.where("tag LIKE '%\s' OR tag LIKE '\s%'").uniq.map { |label| "'#{label.tag}' has #{label.administrative_tags.count} instances" }
=> ["'Project : Magario Diaries ' has 63 instances",
 "'Project : Digital BookPlates ' has 240 instances",
 "'Project : Project : Catalhöyük : Images : Batch 1 ' has 4 instances",
 "'Project : SC1074 su audio : 1/4\" audio tape ' has 1 instances",
 "'Project : Catalhöyük ' has 1 instances",
 "'LAB : MAPS ' has 1 instances",
 "'Project : Maps - Stanford General Collections : Batch 7 ' has 5 instances",
 "'DPG : Patron Request ' has 1 instances",
 "'Project : Catalhöyük : Images : Batch 1 ' has 4 instances",
 "'Project : MOL : restricted until 2019 ' has 0 instances",
 "'Project : Maps - Stanford General Collections : Oversized Maps : Smith Map 1815 ' has 1 instances",
 "'webarchive : repetition of rm735mz8077 ' has 1 instances",
 "'webarchive : repetition of gv741ns3784 ' has 1 instances",
 "'webarchive : repetition of kc309vp5351 ' has 1 instances",
 "'webarchive : repetition of cd761cx9726 ' has 1 instances",
 "'webarchive : repetition of rx753hg6434 ' has 1 instances",
 "'Project : Stanford Oral History  ' has 1 instances",
 "'webarchive : repetition of gy940qn2223 ' has 1 instances",
 "'webarchive : repetition of vk400mp3419 ' has 1 instances",
 "'webarchive : repetition of jv409fh0824 ' has 1 instances",
 "'DPG : Exhibits : Hohbach Hall : Hohbach Hall Opening ' has 3 instances",
 "'Project : SC1118 philosophy : born digital audio : 2022-07 : ' has 0 instances",
 "'Project : M2175 mol : restricted until 2019 ' has 1 instances",
 "'DPG : Earth Sciences  ' has 1 instances",
 "'JIRA : PROJQUEUE-613 ' has 1 instances",
 "'DPG : Digitization Project : Edwards ' has 1 instances",
 "'Project : M2710 roszak : b85 ' has 33 instances",
 "'DPG : Workflow : Accession_Content_Expedited_OCR ' has 1 instances",
 "' Process : Content Type : 3D' has 0 instances",
 "'Format : DPG : unbound archival object ' has 2 instances",
 "' DPG : 3D Imaging : Photogrammetry' has 0 instances",
 "' Project : 3D Lithics' has 0 instances",
 "' DPG : Archaeology Center : Hodge' has 0 instances",
 "' JIRA : PROJQUEUE-292' has 0 instances",
 "' DPG : 3D Imaging : David Scanner' has 0 instances",
 "' Project : Project : 3D Lithics' has 0 instances",
 "' JIRA : PROJQUEUE-295' has 0 instances",
 "' JIRA : PROJQUEUE-299' has 0 instances",
 "' Registered By : dhandel' has 0 instances",
 "' Format : DPG : 3D' has 0 instances",
 "' DPG : 3D Imaging : Artec Space Spider' has 0 instances",
 "' Project : Leland Stanford, Jr. Archaeology Exhibit' has 0 instances",
 "' JIRA : PROJQUEUE-267' has 0 instances",
 "' DPG : Stanford Archaeology Center : Hodge' has 0 instances",
 "' DPG : Exhibits : Collecting in Life and Death: The Curatorial Legacy of Leland Stanford, Jr.' has 0 instances",
 "' SUAC : Stanford University Archaeology Collections' has 0 instances",
 "' JIRA : PROJQUEUE-291' has 0 instances",
 "' Project : canonical objects' has 0 instances",
 "'Project : M2952 seikaly : audio cassette ' has 34 instances"
```

Here's a potential plan I'd like to get your thoughts on, @andrewjbtw and @justinlittman (who I think worked on the `TagLabel` design way back when):

1. Check how many `AdministrativeTag` instances the "bad" `TagLabel` instance has
    1. If 0 related `AdministrativeTag` instances, delete it.
    2. If 1 or more related `AdministrativeTag` instances, check to see if the normalized form of the tag (without the leading/trailing whitespace) has a `TagLabel` instance.
        1. If not, update the "bad" `TagLabel` instance in place.
        2. If so, point all related `AdministrativeTag` instances at the normalized `TagLabel` instance and delete the "bad" `TagLabel` instance.

**Comment by andrewjbtw** [comment]
@mjgiarlo sounds like a good plan to me.

**Comment by mjgiarlo** [comment]
This is now done. I will deploy the latest in `main` to all envs once the cocina-models 0.95.1 deploys have gone out.
