### ISSUE TITLE
Handle `DorController#reindex` for non argo clients

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#433]
Should probably be moved to a `POST`. Updates need to happen with other services that use this an indexing endpoint.

**Comment by jmartin-sul** [comment]
elaboration on the rest of jack's suggested solution in issue #434 (which i filed before seeing this, so maybe close that one as a dupe?).

**Comment by drh-stanford** [comment]
The `sulmq` routing does a GET so it would need to change to a POST.

**Comment by jmartin-sul** [comment]
i'd be in favor of having sulmq POST, if it doesn't seem risky in terms of unforseen regression.
