### ISSUE TITLE
Replayable spreadsheet fails to process UTF-8 CSVs

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4344]
**Describe the bug**
Uploading a UTF-8 CSV to the replayable spreadsheet results in an error message:

<img width="1075" alt="Screenshot 2024-03-12 at 8 52 31 PM" src="https://github.com/sul-dlss/argo/assets/8975583/7a3cf32e-5144-4652-8b70-36220fba380d">

When the same CSV is saved as an Excel file, the replayable spreadsheet works as expected.

**User Impact**
Users who don't normally work with Excel have trouble importing metadata that uses languages that require UTF-8 encoding (like CJK languages) in CSV files.

**To Reproduce**
1. Go to https://argo-stage.stanford.edu/apos/druid:jf408cd6262/bulk_jobs
2. Click on "Submit new file"
3. Upload this UTF-8 CSV (created on a Mac) 
[utf8-replayable.csv](https://github.com/sul-dlss/argo/files/14581872/utf8-replayable.csv)
4. Choose "Spreadsheet input; load into objects"
5. Submit
6. See the error

If you resave that same file in XLSX format, the import will work.

**Expected behavior**
The import should be able to handle UTF-8 CSVs.

**Additional context**
So far, I've only confirmed the bug in the replayable spreadsheet for Mac-created CSVs but it was originally reported by users who had created their CSVs on Windows. I'm going to see I can get a sample from them.

I also attempted to reproduce this error with the new Cocina spreadsheet import and did not have the same problem. However, some Windows users have reported the same issue there. Previous work was done on supporting Mac-created CSVs: https://github.com/sul-dlss/argo/issues/3352 so I would expect them to work.

**Comment by lwrubel** [comment]
Resolved via https://github.com/sul-dlss/modsulator-app-rails/pull/381
