### ISSUE TITLE
Create Collection blue button does not work

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#436]
It can't get to the form ...
![screen shot 2016-01-08 at 6 23 44 pm](https://cloud.githubusercontent.com/assets/1824732/12213843/46277d6a-b635-11e5-99d1-11ee64fc3014.png)

I tried it using the Chit Chat Club APO https://argo-dev.stanford.edu/catalog/druid:qh637kf2429

**Comment by drh-stanford** [comment]
I believe this is a problem with the registration service. The error message is not informative but I believe it's source is here: https://github.com/sul-dlss/argo/blob/develop/app/controllers/apo_controller.rb#L202

**Comment by drh-stanford** [comment]
As an aside, @LynnMcRae when you Create a Collection, it currently assigns the new collection as the default collection of the APO. Is that expected? 

See https://github.com/sul-dlss/argo/blob/develop/app/controllers/apo_controller.rb#L214

This is what also happens in production, see https://github.com/sul-dlss/argo/blob/master/app/controllers/apo_controller.rb#L180

**Comment by drh-stanford** [comment]
The problem here is bad data in this APO -- it has a collection that doesn't exist in the `administrativeMetadata`

![screen shot 2016-01-20 at 12 56 51 pm](https://cloud.githubusercontent.com/assets/1861171/12462844/4df2a29c-bf75-11e5-948d-0c8760c65867.png)

**Comment by drh-stanford** [comment]
The form does not format as a modal dialog, and there's 2 pull downs for the rights

![screen shot 2016-01-20 at 1 03 49 pm](https://cloud.githubusercontent.com/assets/1861171/12463039/4fb836d6-bf76-11e5-916e-29af8a831b57.png)

**Comment by drh-stanford** [comment]
here's what the corrected forms look like:

![screen shot 2016-01-21 at 5 38 25 pm](https://cloud.githubusercontent.com/assets/1861171/12500203/df865dc0-c065-11e5-8748-e8a996d1b9eb.png)
![screen shot 2016-01-21 at 5 38 25 pm](https://cloud.githubusercontent.com/assets/1861171/12500204/e1b41ac4-c065-11e5-836b-2cc9f7c343bf.png)

**Comment by drh-stanford** [comment]
the PR switches the form to modal dialogs, like so:

![screen shot 2016-01-22 at 12 43 57 pm](https://cloud.githubusercontent.com/assets/1861171/12522501/ef471a9c-c105-11e5-87c4-afc0beb47071.png)
![screen shot 2016-01-22 at 12 43 46 pm](https://cloud.githubusercontent.com/assets/1861171/12522502/ef4b1df4-c105-11e5-9680-7415b9cc8ef6.png)
