### ISSUE TITLE
Change Argo State Service to use Version Service

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#4394]
Instead of using local logic.

**Comment by jcoyne** [comment]
Can you add more context to this ticket?

**Comment by justinlittman** [comment]
Context: Currently, there is versioning logic spread throughout multiple code bases. The goal of the "normalize versioning phase" of this workcycle is to consolidate as much of that logic as possible behind the DSA versioning status endpoint and reduce local versioning logic.

The goal of this ticket is to use the VersioningService (which gets status from the DSA versioning status endpoint) instead of existing local logic for the StateService. In addition, there are been related refactoring to make the StateService have a single responsibility, viz., driving the user lock/unlock/etc. versioning interaction.

**Comment by mjgiarlo** [comment]
@justinlittman Is https://github.com/sul-dlss/argo/pull/4401 connected to this issue?

**Comment by justinlittman** [comment]
@mjgiarlo Related but not connected.
