### ISSUE TITLE
Ops implications for work to be done for Argo to prod updates

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#440]
@atz Has been working on updating and enumerating the code that uses dor services https://github.com/sul-dlss/dor-services/issues/136 . Ops needs to be keyed in to what specific updates need to happen (+ ordering) for argo to go to prod.

@sul-dlss/devops

**Comment by mejackreed** [comment]
Also related to #490

**Comment by drh-stanford** [comment]
duplicate of #490
