### ISSUE TITLE
Update versioning in the ApplyModsMetadata

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#4403]
The logic should be:
1. If the item is not open and is not openable? then skip it.
2. If the item is not open then open a new version.
3. Update the cocina.

The item is NOT closed after updating the cocina.

The VersionService should be used for getting status and performing versioning operations; local logic for determining version status based on workflows should be removed.

**Comment by justinlittman** [comment]
Hold for testing by @andrewjbtw.

**Comment by lwrubel** [comment]
Is it correct that if the item is either open or `openable?` it should not be skipped?

**Comment by justinlittman** [comment]
That sounds right.

**Comment by andrewjbtw** [comment]
Yes.

If it's open, update the metadata.
If it's not open but it is openable, open it and then update the metadata.
