### ISSUE TITLE
EEMs and ETD workflows

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#441]
What can go down, and when?

**Comment by mejackreed** [comment]
Ping @sul-dlss/devops

**Comment by mejackreed** [comment]
EAMS/ETDS < ruby 1.8.7 big issue

**Comment by LynnMcRae** [comment]
I took a look at the EEMs and ETD workflows for Erin to document what they did and look for anything that might depend on SOLR fields. My goal was to describe their functionality, but I also didn't see anything in cursory code review that looked suspicious. Just read and write of datastreams and files.

eemsAccessionWF

1. register-object -- Register new objects in DOR

   No robot: Bootstrap step to initiate workflow, auto-completed

2. submit-tech-services -- Submit to Tech Services

   No robot: Passive step to record submission status for metadata unit processing

3. eems-transfer -- Transfer content to workspace

   Robot: Moves uploaded files from EEMs workspace to DOR workspace

4. submit-marc -- Send stub MARC record to Symphony

   Robot: Creates stub MARC record from MODS, places it in dropoff file for Symphony

5. check-marc -- Check for creation of MARC record

   Robot:
   - runs daily to check Symphony to see if MARC record has been created from stub (via web services call to Symphony).
   - Records catkey in identityMetadata.

6. catalog-status -- Monitor status of MARC record for completion

   Robot:
   - runs daily to see if MARC record has completed cataloging (via web services call to Symphony)
   - if so, simply completes so remaining WF can proceed
   
7. other-metadata -- Other metadata

   Robot:
   - Creates contentMetadata from directory.
   - Creates rightsMetadata from EEMs metadata

8. start-accession -- Start common-accessioning

   Robot: Initiate common accessioning


etdAccessionWF

1. register-object -- Register object in DOR

   No robot: Bootstrap step to initiate workflow, auto-completed

2. submit -- Student submits completed ETD

   No robot: status recorded by ETD app to statisfy prereqs for later steps

3. reader-approval -- Faculty reader has approved (signal from PeopleSoft)

   Robot:
   - asynch process responds to Oracle Service Broker message from Student system
   - Just completes this step to satisfy prereqs for later steps

4. registrar-approval -- Final Registrar approval (signal from PeopleSoft)

   Robot:
   - asynch process responds to Oracle Service Broker message from Student system
   - Just completes this step to satisfy prereqs for later steps

5. submit-marc -- Transfer stub MARC record to Symphony (drop off directory)
6. check-marc -- Daily check to see if MARC record has been created in Symphony
7. catalog-status -- Monitor Symphony status until Cataloging is done

   See identical 3 steps in EEMS workflow above.

8. other-metadata -- Generate content, technical and rights metadata

   Robot:
   - Creates contentMetadata from directory.
   - Creates rightsMetadata from ETD metadata

9. start-accession -- Transfer control to Common Accessioning

   Robot: Initiate common accessioning

10. google-transfer -- Transfer PDF and MARCXML to Google account dropoff directory (no longer run)
11. binder-transfer -- Transfer PDF to binder drop off directory for bound physical copy

    Robots: Data transfer steps run manually at the end of each quarter.

**Comment by drh-stanford** [comment]
We need to update the robot and lyberservices VMs to use ruby 2.x. right now they're on 1.9.3.

**Comment by mejackreed** [comment]
Might be useful for #490

**Comment by drh-stanford** [comment]
We should archive Lynn's work and close this one as #490 duplicates this.

**Comment by blalbrit** [comment]
Non-actionable ticket - this seems to have been for sprint-specific information purposes.
