### ISSUE TITLE
"Create collection" button/modal/function should automatically handle APO versioning

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4410]
Argo users should be able to use the "Create collection" function without having to open an APO first.
<img width="1485" alt="Screenshot 2024-04-12 at 2 28 34 PM" src="https://github.com/sul-dlss/argo/assets/8975583/b79f91d5-f2fc-435d-8bbc-e67ec7f615ce">

But the function updates the APO Cocina because it adds the new collection druid to the `collectionsForRegistration` list in the administrative metadata. Under the new approach to versioning, the APO object will need to be opened for this change to take place.

Request:

- Create collection button remains active even when object is locked
- Create collection modal allows user to create collection as is done now
- Submitting the modal functions the same way to the user
- Somewhere in that sequence, either while the user is editing or after they submit the form, the APO versioning is taken care of on the system side
- Version description should be "Created new collection: ${collection_druid}"

If it's not possible to insert the collection druid into the version description, just go with "Created new collection".

**Comment by justinlittman** [comment]
Slight clarification: The collection button should be active when the object is open or openable; otherwise, it should be inactive.
