### ISSUE TITLE
Argo links to files are not working when files are in a hierarchy

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4427]
**Describe the bug**
Argo shows "file not found" errors for links to files that are in a hierarchical arrangement. This is a problem for both the stacks and the preservation links.

**User Impact**
Argo users can't download individual files from items that use hierarchy. The link to download a zip of the preserved files does work.

**To Reproduce**
1. Go to https://argo-stage.stanford.edu/view/druid:fx702cp4356
2. Click on any of the file download links
3. Try the stacks and preservation links
4. See file not found errors

**Expected behavior**
The links to individual files should work.

**Additional context**
We needed to do something with the URLs to make these file links work when we first launched hierarchy. This seems like a regression.

**Comment by mjgiarlo** [comment]
It looks like a feature we never implemented AFAICT.
