### ISSUE TITLE
Add new OCR bulk action (argo)

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#4449]
Bulk action to initialize OCR for a set of objects.

Users need to provide some OCR related information, which will set workflow variables and/or update cocina.

See https://docs.google.com/document/d/1ScvlgCI-YhyV2LaaDLTVOWTvuGe4bM1tmgzVbAHTDw8/edit#heading=h.bafslbs3xknn

Only allow OCR to be started if it should be possible (i.e. limit by object type and object content type)

(Workflow list: https://github.com/sul-dlss/argo/blob/main/app/helpers/apo_helper.rb)

But started OCR will not just require starting `ocrWF`, it will also require setting the appropriate workflow variables, as shown in pre-assembly here: https://github.com/sul-dlss/pre-assembly/blob/5cc6ad439e3447408cdee37bc0aafae57158b7f4/app/services/start_accession.rb#L9-L16

**Comment by jmartin-sul** [comment]
From discussion yesterday: if the list includes more than one content type, as long as at least one content type is OCR-able, it will OCR the OCR-able ones, and log a message about the ones it skipped.

Language in requirements doc updated to be agnostic to content type (to allow for mixed content types).
