### ISSUE TITLE
Silent failure trying to add a workflow

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#4450]
<img width="1249" alt="Screenshot 2024-05-22 at 11 01 02 AM" src="https://github.com/sul-dlss/argo/assets/92044/6772b3ba-f871-4c9a-b713-50ee7feccfd5">

The "add" button doesn't appear to do anything.

The console shows an API request was made that came back with a 422, but the UI didn't show any message to the user:
```
XHR POST
https://argo-stage.stanford.edu/items/druid:fb146xw8568/workflows
[HTTP/1.1 403 Forbidden 260ms]
registrationWF already exists!
```

If I unlock the object, I'm able to add a workflow, but then it errors with:
<img width="1335" alt="Screenshot 2024-05-22 at 11 06 45 AM" src="https://github.com/sul-dlss/argo/assets/92044/fbf80abf-e2d4-4940-8ba0-f4967101a827">

Once you get to this situation, the object seems stuck as you can no longer "lock" it.

**Comment by andrewjbtw** [comment]
What do you mean you can't lock it? The icon shows as active for me but I haven't tried to lock it. It's different from when the button is inactive.

Also, you should only add a workflow if you know you have to add a workflow, and you know you're in a situation where you can add a workflow. That button has very few guardrails. Why were you trying to add a workflow?

**Comment by jcoyne** [comment]
I was just testing the interface because I knew we changed the guards we placed around starting workflows.  Regardless of whether you should or should not do something, a system should have a UI that tells you "You can't do that because ..."

**Comment by andrewjbtw** [comment]
I have a more constructive suggestion than my last comment: we can remove accessionWF entirely from the add workflow dropdown list. Now that Registered items are closeable, there's no use case I can see for adding accessionWF.

**Comment by justinlittman** [comment]
@andrewjbtw Can we also remove registrationWF?

**Comment by justinlittman** [comment]
Actually, let's keep the scope of this ticket just surfacing the error to the user. Removing workflows from dropdown will be ticketed elsewhere.

**Comment by jcoyne** [comment]
Screenshot 2024-05-22 at 3.55.56 PM

Adding this workflow when you aren't supposed to eventually leads to version mismatches in preservation.

**Comment by justinlittman** [comment]
See https://github.com/sul-dlss/argo/issues/4441
