### ISSUE TITLE
Update setting rights forms to show current APO's default

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#446]
Originally described in a follow on comment in https://github.com/sul-dlss/argo/issues/429#issue-125500022

Lynn McRae said:

>Ideal would be to match the presentation shown under Item Registration (including the indication of which setting matches the APO default), but that is secondary. It is only important to replace the "none" with the proper term.  The "Set object rights" bulk operation drop-down may share this problem, but that button is not currently active so I can't verify.

![screen shot 2016-01-07 at 2 27 01 pm](https://cloud.githubusercontent.com/assets/1824732/12184594/02a0c758-b54b-11e5-9740-5ad2b5eff1fd.png)
![screen shot 2016-01-07 at 2 28 09 pm](https://cloud.githubusercontent.com/assets/1824732/12184593/02a00d72-b54b-11e5-898c-322c3b86d08e.png)

**Comment by andrewjbtw** [comment]
I looked into this and this ticket is for the set rights menus on:

- the item page
![Screen Shot 2020-05-13 at 10 24 00 AM](https://user-images.githubusercontent.com/8975583/81844561-1ef4f800-9504-11ea-8aa4-3d07715ac74f.png)

- the bulk update page
![Screen Shot 2020-05-13 at 10 24 56 AM](https://user-images.githubusercontent.com/8975583/81844573-21efe880-9504-11ea-82c4-6c1391869d78.png)

**Comment by andrewjbtw** [comment]
The desired behavior is for the menu to indicate what's the APO default setting. The rights menu on the register items page already does this:

![Screen Shot 2020-05-13 at 10 27 38 AM](https://user-images.githubusercontent.com/8975583/81844841-8e6ae780-9504-11ea-81b7-3fcb45b938cd.png)

**Comment by aaron-collier** [comment]
After discussion with @andrewjbtw, it likely isn't possible to highlight the default for an APO in bulk update because we're not likely to have a single APO to go based on.
