### ISSUE TITLE
Items should not be editable while workflows are running

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#4470]
Argo should disable any editing (opening/closing/pencil icons) while accessioning is running, i.e. while ocrWF, assemblyWF, accessionWF are running.  This prevents you from making changes to an object that is about to be closed, which could introduce problems with you editing files, etc. from under running processes or causing race conditions.

May be already in progress in versioning workcycle check with other team.

see https://github.com/sul-dlss/argo/pull/4460 and https://github.com/sul-dlss/argo/pull/4458

**Comment by jmartin-sul** [comment]
Actionable, but the first action is to see whether this should be done as part of work in progress (the PRs linked in the description), or if this ticket's described work is already in progress in that work.
