### ISSUE TITLE
Add new text extraction fields to the Argo structural CSV

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4473]
Users should be able to edit the new text extraction Cocina fields via the Argo structural CSV. The fields should not be required.

I can see pros and cons to exposing these fields to editing but if we don't, any updates to the values would need to go through a request for developer help.

**Comment by peetucket** [comment]
Is this the CSV file you can download here:

![Image](https://github.com/sul-dlss/argo/assets/47137/99bf6483-61b2-49ce-b20a-81a27922a282)

And used in the `Export structural metadata` and `Import structural metadata` jobs?

**Comment by peetucket** [comment]
if so, looks like the changes would be to `StructureUpdater` and `StructureSerializer` classes

**Comment by andrewjbtw** [comment]
Yes, that's the one.
