### ISSUE TITLE
Prevent malformed titles in Cocina spreadsheet uploads

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/argo#4492]
See: https://app.honeybadger.io/projects/50568/faults/108793688

```
"title" => [{
      "structuredValue" => [
        {
          "value" => "Bulletin of the Monterey Audubon Society",
        },
        {
          "type" => "subtitle",
        }
      ],
```

It is currently possible if you have a typo in a column header in your spreadsheet to generate malformed titles. One example is above, where some structured title parts have a value without a type and a type without a value. These spreadsheet uploads succeed, and then items get stuck in accessioning and cannot be indexed (see HB alert above). The one time we saw this happen, it was in a single collection and 130 items were affected, so we hand-remediated the Cocina JSON in DSA prod, but ideally we would be able to flag this earlier. Look into how we might do this before accessioning begins, ideally before Argo accepts the spreadsheet. If you want a sample bad spreadsheet, you can ask Amanda W.

See https://stanfordlib.slack.com/archives/C0EAZ09QF/p1718988097815579

**Comment by peetucket** [comment]
header was `"title1.structuredValue12type" instead of "title1.structuredValue2.type"`

**Comment by peetucket** [comment]
To replicate: 

- first used the bulk action "Validate cocina descriptive metadata spreadsheet", which said it was fine (it is not)
- then used the "Upload descriptive metadata spreadsheet" bulk action and that's where the failure happened

**Comment by peetucket** [comment]
Bad spreadsheet
[MPAS Scans - cocina-upload.csv](https://github.com/user-attachments/files/16059361/MPAS.Scans.-.cocina-upload.csv)

**Comment by peetucket** [comment]
Another example: https://docs.google.com/spreadsheets/d/1UsG7CXV-ZBTD4jZKD4bGfDx5wkho3ChQCa22LbWdD8Q/edit?gid=0#gid=0

**Comment by peetucket** [comment]
Action is to verify that each `titleX.structuredValueX.type` has a corresponding `titleX.structuredValueX.value` (where X is an integer). If you have one without the other, this is a validation error in `DescriptionValidator`

**Comment by mjgiarlo** [comment]
@sul-dlss/infrastructure-team @arcadiafalcone @andrewjbtw I'm wondering if we might want deeper validation of description values as well, at some point. I know that work is ongoing to remediate items that will run afoul of [this held PR](https://github.com/sul-dlss/cocina-models/pull/681/files), but as Laura has observed this does not catch other known bad values.

Currently, this is a valid DRO even with the changes in the PR above: 

```ruby
titles = [{ structuredValue: [{}] }]
dro = Cocina::Models::DRO.new(label: 'foo', version: 1, externalIdentifier: 'druid:dc213hf8976', type: Cocina::Models::ObjectType.object, structural: {}, identification: { sourceId: 'sul:foo' }, access: {}, administrative: { hasAdminPolicy: 'druid:jh768hf7866' }, description: { title: titles, purl: 'https://purl.stanford.edu/dc213hf8976' })
 => #<Cocina::Models::DRO cocinaVersion="0.98.0" type="https://cocina.sul.stanford.edu/models/object" externalIdentifier="druid:dc213hf8976" label="foo" version=1 access=#<Cocina::Models::DROAccess view="dark" download="none" location=nil controlledDigitalLendi...
```

Should we be allowing description values like the titles above in Cocina?

**Comment by peetucket** [comment]
Is it possible for there to be `title2.structuredValueX.type`, `title2.structuredValueX.value`, `title3.` etc etc. ?   is there a limit to the number of `titleN` pairs?  do we have to check for matching values across each possibility?

**Comment by arcadiafalcone** [comment]
+100 more validation - speccing this out is one of my goals for the near future.

Any titleX.structuredValueY.type should have a corresponding titleX.structuredValueY.value (where X and Y are integers). In practice I suspect X maxes out at 10 or fewer, but the schema doesn't limit the number of recurrences.

**Comment by arcadiafalcone** [comment]
@mjgiarlo An object with only an empty title should not be valid. There should be at least one title..value (where .. is nothing or any combination of structuredValue and/or parallelValue) that is not null or an empty string.

**Comment by jcoyne** [comment]
@arcadiafalcone I think this is a place where having a more concrete model (rather than DescriptiveValue) for title parts would be helpful.  Then the OpenAPI spec could validate this.

**Comment by mjgiarlo** [comment]
Vivian has alluded to a future work cycle where we can consider changes (improvements, simplifications, what have you) to the Cocina descriptive model. I suspect we'll want to build on this discussion at that point.

**Comment by peetucket** [comment]
1. I'll keep the scope of this ticket focused on the initial problem of the mismatched headers columns, leaving any other potential title validation for future work (though not ticketed at the moment).
2. FYI @arcadiafalcone, I believe the header columns in this fixture file we have in our code are not valid according to the new logic: https://github.com/sul-dlss/argo/blob/main/spec/fixtures/files/bulk_upload_descriptive.csv   Can you verify to be sure it is ok for me to update the fixture file?    Specifically, it has a `title2.structuredValue2.type` column without a corresponding `title2.structuredValue2.value` column, which the new validation is flagging.

**Comment by mjgiarlo** [comment]
> 1. I'll keep the scope of this ticket focused on the initial problem of the mismatched headers columns, leaving any other potential title validation for future work (though not ticketed at the moment).

👍🏻

> 2. FYI @arcadiafalcone, I believe the header columns in this fixture file we have in our code are not valid according to the new logic: [`main`/spec/fixtures/files/bulk_upload_descriptive.csv](https://github.com/sul-dlss/argo/blob/main/spec/fixtures/files/bulk_upload_descriptive.csv?rgh-link-date=2024-07-02T20%3A55%3A30Z)   Can you verify to be sure it is ok for me to update the fixture file?    Specifically, it has a `title2.structuredValue2.type` column without a corresponding `title2.structuredValue2.value` column, which the new validation is flagging.

The structure in the fixture has the following headers:

```
title2.structuredValue2.structuredValue1.type
title2.structuredValue2.structuredValue1.value
title2.structuredValue2.structuredValue2.type
title2.structuredValue2.structuredValue2.value
title2.structuredValue2.type
title2.type
```

Is it true that the value corresponding to `title2.structuredValue2.type` is the sum of what's in `title2.structuredValue2.structuredValue1` and `title2.structuredValue2.structuredValue2`, and the value corresponding to `title2.type` is `title2.structuredValue1` and `title2.structuredValue2`?

**Comment by peetucket** [comment]
> Is it true that the value corresponding to `title2.structuredValue2.type` is the sum of what's in 
 `title2.structuredValue2.structuredValue1` and `title2.structuredValue2.structuredValue2`, and the value corresponding to  `title2.type` is `title2.structuredValue1` and `title2.structuredValue2`?

I think this makes the validation trickier, no?

My current simplistic code is also ignoring the `title2.structuredValue2.structuredValue2.type` pairing with `title2.structuredValue2.structuredValue2.value`  (it is really focused specifically on the `titleX.structuredValueY.type` format)

**Comment by mjgiarlo** [comment]
> > Is it true that the value corresponding to `title2.structuredValue2.type` is the sum of what's in
> > `title2.structuredValue2.structuredValue1` and `title2.structuredValue2.structuredValue2`, and the value corresponding to  `title2.type` is `title2.structuredValue1` and `title2.structuredValue2`?
> 
> I think this makes the validation trickier, no?

Yes, I think it does. FWIW, the real item on which this fixture was based seems to have changed to a different structure in the meantime: https://argo.stanford.edu/view/druid:tj960jy9783

![Screenshot from 2024-07-02 14-25-15](https://github.com/sul-dlss/argo/assets/131982/bea47d77-00ff-45c1-8d5f-06294bc7226c)

**Comment by arcadiafalcone** [comment]
@mjgiarlo Your fixture update is correct.

**Comment by arcadiafalcone** [comment]
I can't think of a valid instance offhand when `titleX.structuredValueY.structuredValueZ` would appear (but there are more things in heaven and MARC Horatio, etc.). It is possible that it's an artifact of a previous uniform title mapping, as that one went through a few iterations before it settled, and the main challenge was linking together the name-title structure when both the name and the title might be internally structured as well.

**Comment by peetucket** [comment]
OK, thanks - will update the fixture file and leave the validation as is in the PR.
