### ISSUE TITLE
Display descriptive metadata for user version

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#4495]
On the user version details page, the MODS button should display the descriptive metadata for the user version.

<img width="790" alt="image" src="https://github.com/sul-dlss/argo/assets/588335/b95efa89-3289-4472-80f5-6e46466e132b">

**Comment by lwrubel** [comment]
This currently uses ModsDisplay to render subheadings and values. Should this just render the descriptive section of the cocina, or is there a mapping to subheadings?

**Comment by justinlittman** [comment]
Mapping to subheadings. If my understanding is correctly, the mapping is performed by posting the cocina to purl fetcher.

**Comment by lwrubel** [comment]
@andrewjbtw requests that the button be labelled "Description".
