### ISSUE TITLE
/catalog vs /view status

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#450]
Long ago when we first switched from vuFind to blacklight for Searchworks we tried to switch from /catalog to /view as a general trend away from "we just support the library catalog".  Thus there is code in Argo that allows the user to specify /view in place of /catalog, though I think there is no longer anything that attempts to rewrite /catalog to /view when exposing URLs.  This is a fine status quo.

This ticket is to record that bit of history in case issues come up with the implementation of /view alternatives (and to close off corresponding JIRA tickets)

**Comment by blalbrit** [comment]
Closing as a likely no-op.

**Comment by mejackreed** [comment]
Seems like still a relevant question though that's not answered. Might be useful to keep open for historical reasons. The code goes down both paths in different places. From a maintainablility perspective it would be good to standardize, so the next team isn't confused.

**Comment by andrewjbtw** [comment]
Closing this as it seems like it's more for documenting a past decision.
