### ISSUE TITLE
Use user version data for overview and details section when displaying user version details page

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/argo#4515]
<img width="1330" alt="image" src="https://github.com/sul-dlss/argo/assets/588335/ab3e54b1-0202-4c3b-bff9-6fb9f4beb2fc">

Also, all edit buttons should be removed.

----
Differences from current version show page:

- "Released to": show a message "Older versions are not released"
<img width="431" alt="Screenshot 2024-07-03 at 8 58 50 AM" src="https://github.com/sul-dlss/argo/assets/8975583/21095fa9-b680-427b-857f-7363809a14fc">

- Do show "processing status": it will be the "{system version} Accessioned"
- Show the same Project/tags that are show on all versions.

**Comment by justinlittman** [comment]
Per @andrewjbtw, processing status and release to are not necessary.

**Comment by andrewjbtw** [comment]
Sorry, after discussing with Astrid, I've revised the ticket. I updated the main description.
