### ISSUE TITLE
Don't show lock icon on version pages (outside of the HEAD version)

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4519]
We are not using the lock/unlock icon/metaphor for old user versions, so don't show the lock icon on those show pages.

The lock/unlock icon is for managing the opening and closing of versions. If I understand the model correctly, it will only apply to the HEAD version or the current system version.

([Figma link](https://www.figma.com/proto/XjubCohES3rE8xSQpiNghq/Versioning?page-id=0%3A1&node-id=320-782&viewport=-2707%2C299%2C0.25&t=qxaxfTWyA5QqTX1p-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=320%3A782&show-proto-sidebar=1))

**Comment by justinlittman** [comment]
Clarification: The lock icon should not be displayed when a user version view (`argo_show_presenter.user_version_view?`). That will handle "outside of the HEAD version".
