### ISSUE TITLE
Bulk "Apply APO Defaults" and versioning

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#452]
There is a Bulk Update action to "Apply APO defaults" that will copy rightsMetadata defaults from the governing APO(s) to the druids.  We have it in the category of "Requires versioning" mainly as a general reminder that anything that can update core parts of the object should be versioned.  Thus a natural thing to do would be to "Prepare objects" by opening a new version if the object is not already open for modification.

Question: does this bulk update replace rightsMetadata blindly or does it check to see of the rightsMetadata already matches the defaults? If the latter, we might be opening new versions without a need. If the former, we should optimize the updates by checking, and have the bulk update itself open a new version only as needed without the user "preparing" all target objects first. The spreadsheet upload feature is smart like this.

**Comment by tingulfsen** [comment]
I just checked this, and eventually it is the reapplyAdminPolicyObjectDefaults() method in Dor Services that is called:

https://github.com/sul-dlss/dor-services/blob/efa422c5624b1554d1fed6acd5062ac058b1642e/lib/dor/models/governable.rb#L60-L62

I didn't find any checks  to see if the rightsMetadata already matches the defaults before calling that function - and the function itself obviously just sets the rightsMetadata directly by assignment. So it would appear that pressing the "Apply APO defaults" button does a straight copy with no checks beforehand.

**Comment by LynnMcRae** [comment]
Given this facility is targeted at applying a global change in rights to a population, rather than some remedial attempt to update outliers, this is probably ok for now.  There are other tickets concerning more granular control and other issues over rights management, so we can likely address a set of rights-related things together at a future date.

**Comment by blalbrit** [comment]
Closing as non-actionable.
