### ISSUE TITLE
Argo history link should link to pages for all versions

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4521]
The Argo item show page has a history section that lists all versions of an item. When we enable the display of previous versions, that list should link to each of the versions. Do not show a link for the version currently being viewed (system version 5 in the screenshot below):

<img width="558" alt="Screenshot 2024-07-03 at 5 01 28 PM" src="https://github.com/sul-dlss/argo/assets/8975583/372c81f6-c36f-42eb-b1dd-1d15462875f8">

The current click behavior of that list is odd because clicking on a title collapses the section, which can be disorienting. Instead, change the collapse behavior:

- Add an icon for expand/collapse to the left of the version description (see wireframe)
- Do not collapse the list when someone clicks on the title - only expand/collapse via the icon

([Figma link](https://www.figma.com/proto/XjubCohES3rE8xSQpiNghq/Versioning?page-id=0%3A1&node-id=320-782&viewport=-2707%2C299%2C0.25&t=qxaxfTWyA5QqTX1p-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=320%3A782&show-proto-sidebar=1))

**Additional notes**

- Versions that we can't render: I don't think we can show old versions that pre-date the new versioned model. If a previous version isn't available, don't put a link in the text. We'll need to communicate that limit to users. It's my understanding from planning discussion that we will be able to show old (system) versions going forward.

- Content types: we're limiting the initial use of public versions to the "file" content type. This is largely because there are many questions around what we can render in the viewers. Argo has no viewers, so it should theoretically be possible to show old system versions regardless of content type. Please correct me if I'm wrong.

**Comment by justinlittman** [comment]
When did system version display get added to the scope of this WC? All of our Argo and DSA work has been on the assumption that we would be displaying user versions, but not system versions.

**Comment by andrewjbtw** [comment]
It was discussed in planning before the workcycle began and the suggestion that it would be possible based on the new model came from the developer side.

**Comment by justinlittman** [comment]
Yes, we said it was possible. However, possible is different from in-scope, especially when we've proceeded with the specs that we had.

**Comment by andrewjbtw** [comment]
This is why I said in Slack this would need some discussion in the next planning.

**Comment by justinlittman** [comment]
Super.

**Comment by aaron-collier** [comment]
From planning: on file list for previous versions show the file list but do not provide links.

**Comment by justinlittman** [comment]
Blocked by https://github.com/sul-dlss/dor-services-app/issues/5147
