### ISSUE TITLE
If the latest user version == the latest system version, do not link to the latest user version on the version history list

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4527]
We currently link all the user versions in the version history list. When the latest user version is also the latest system version we end up with:

- the "traditional" Argo show page that displays the lock icon and all the usual editable functionality
- the specific user version URL that looks like an "old" version where all editing has been turned off

Unlike Purl, there's no use case for an Argo user version URL that corresponds to the latest version of the item. The only need for user version URLs is for showing previous user versions.

**The request**
Do not link to the latest user version if it corresponds to the latest system version. In the screenshot below that would mean:

- link to "Public version 1"
- show the text for "Public version 2" but do not link it

> <img width="690" alt="Screenshot 2024-07-09 at 3 41 22 PM" src="https://github.com/sul-dlss/argo/assets/8975583/320e478a-b01d-4991-bbc3-afe7593c92ec">

**Comment by justinlittman** [comment]
@andrewjbtw Should there be a user version banner on latest object version = latest user version page?

**Comment by andrewjbtw** [comment]
No, I think it will be clearer if the current (system + user) version only has the lock and the usual editing controls. That way the banner will only be associated with old versions.
