### ISSUE TITLE
Add "withdraw" button to previous user version page

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4528]
When an item has multiple user versions, we need to support the ability to withdraw an older version. An older version may be withdrawn for a number of reasons: author's request, third-party takedown, etc. The mechanics of the approval of a withdrawal request is outside the scope of SDR applications. This will not be self-service for depositors and won't be supported in H2. Instead, similar to other takedowns of ETD or H2 items, the request will go through email and be approved that way.

We are supporting this in Argo because there is the potential to add user version creation to Argo in the future. We do not want to implement it only in H2 and then find that we need to implement it again in Argo. This also allows H2 to operate only on latest versions rather than on the whole history of an item.

**The withdraw interface**

Argo users will be able to handle withdrawal requests through a "Withdraw" button on the Argo interface. ([Figma](https://www.figma.com/proto/XjubCohES3rE8xSQpiNghq/Versioning?page-id=0%3A1&node-id=320-782&viewport=-2707%2C299%2C0.25&t=qxaxfTWyA5QqTX1p-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=320%3A782&show-proto-sidebar=1))

<img width="1092" alt="Screenshot 2024-07-09 at 5 10 02 PM" src="https://github.com/sul-dlss/argo/assets/8975583/89abf234-aed6-49c4-96b7-35464754c072">

 The button should only display under the following conditions:

- The page is an "old" user version page. The latest user version cannot be withdrawn. 
- The item has not already been withdrawn. If the item has already been withdrawn, see "Restore" below
- If there is only one user version, there should not be a "Withdraw" button
- If the page is not a user version page, there should not be a "Withdraw" button

When a user clicks on the "Withdraw" button, pop up a confirmation box. In the box, display this message:

> Are your sure you want to withdraw this version? Once you withdraw this version, the Purl will no longer display it.

**What happens when you withdraw**

When a version is withdrawn, 

- a tombstone page should replace that version's page on the Purl. (This is ticketed separately.)
- links to files (versions of files) specific to that version should no longer return the files (404 or Access forbidden)
- files (versions of files) specific to that version can remain on Stacks as long as they can't be accessed

**Argo show page for a withdrawn version**

Once a version has been withdrawn, the show page for that version should:

- Display a modified banner indicating the version has been withdrawn
- Show a "Restore" button where the "Withdraw" button was displayed

([Figma](https://www.figma.com/proto/XjubCohES3rE8xSQpiNghq/Versioning?page-id=0%3A1&node-id=541-1014&viewport=-2707%2C299%2C0.25&t=qxaxfTWyA5QqTX1p-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=541%3A1014&show-proto-sidebar=1))

<img width="1092" alt="Screenshot 2024-07-09 at 5 23 55 PM" src="https://github.com/sul-dlss/argo/assets/8975583/7981c697-95c9-4747-afca-9ab84ea43f82">

**Restoring a version, aka un-withdrawing**

We should also support restoring a withdrawn version. Especially while the feature is new, we may find that we need to restore a version that had been withdrawn. Putting this in the Argo UI will make it easier to correct possible mistakes.

Restoring a version will be like withdrawing a version. When the user clicks the restore button, show a dialog box with this message:

> Are your sure you want to restore this version? Once you restore this version, it will become visible on the Purl again.

Restoring the version should mean:

- the tombstone is replaced by the original Purl page
- the links to files should be re-enabled
- since the files will have remained on Stacks, no additional shelving should be required

**Additional context**

Withdraw/restore apply only to old user versions. The following cases are different in significant ways:

***Full takedown of all versions + a message about the item on the latest version.***

In this case, we would withdraw all old versions and create a new latest version with a message. I've been creating tombstones like this for content with DOIs since DataCite requests that we do not take pages down completely. Instead, the DOI resolves to a page that indicates that content has been removed (or moved to a new URL).

***Actual file deletion and other exceptional requests***

For example, if we need to remove files for privacy reasons. This will likely take some manual work, as it does now in these situations. We also have had one or two takedowns where we went as far as making an effort to de-list items from search engines. We should not even show a tombstone purl under that circumstance.

***Takedowns of items that are not using "user" versioning***

We will continue to have collections materials (not H2, ETD, etc) where we will take the items down by changing the rights to dark. That operation should continue to remove the Purl and not leave a tombstone behind.

**Comment by justinlittman** [comment]
Blocked by needing to support withdrawing in purl-fetcher.

**Comment by astridu** [comment]
Please see these mockups for latest design (updated the yellow banner to conform to the new banner styles we defined)
Older version: https://www.figma.com/proto/XjubCohES3rE8xSQpiNghq/Versioning?page-id=0%3A1&node-id=320-782&viewport=-12727%2C-3675%2C1&t=Q8XjDGjx2EhhCXEa-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=320%3A782&show-proto-sidebar=1
Withdrawn version: https://www.figma.com/proto/XjubCohES3rE8xSQpiNghq/Versioning?page-id=0%3A1&node-id=541-1014&viewport=-12727%2C-3675%2C1&t=Q8XjDGjx2EhhCXEa-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=541%3A1014&show-proto-sidebar=1

**Comment by justinlittman** [comment]
The scope of this ticket is to add the Withdraw and Restore buttons and have them update the User Version in DSA by invoking the user version update endpoint.

**Comment by justinlittman** [comment]
Blocked by https://github.com/sul-dlss/dor-services-app/issues/5136
