### ISSUE TITLE
Add agreement references to Identity section of displays

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#453]
Request from Rosy from https://jirasul.stanford.edu/jira/browse/ARGO-216

We list any objects Admin Policy and Collection membership (if any) in the list of fields shown in the Identity portion of the display.  The request is to show any referencesAgreement relationship in the same manner, labeled "Agreement".  This can be a general change for all objects though it would only appear for APOs since they are the only objects that use this relationship.

Note that agreement druid is not currently dereferenced to a separate title field in the solr doc.

**Comment by blalbrit** [comment]
Backlogging for now - future iterations of admin dashboard would hopefully handle display of agreement relationships more gracefully.

**Comment by andrewjbtw** [comment]
This remains a need as it requires multiple steps to identify the agreement connected to each APO.

**Comment by andrewjbtw** [comment]
Closing in favor of https://github.com/sul-dlss/argo/issues/3528
