### ISSUE TITLE
Update button visual design in Argo (this is a design component)

### ISSUE THREAD

**Issue by astridu** [sul-dlss/argo#4530]
Current buttons
1. Primary filled
<img width="182" alt="image" src="https://github.com/sul-dlss/argo/assets/42216982/cbe59519-a7fb-4fc8-a83c-e001f98b0943">

2. Secondary outline 
<img width="151" alt="image" src="https://github.com/sul-dlss/argo/assets/42216982/ead88469-5631-401e-86de-af06a7b0f382">

3. Primary disabled
<img width="182" alt="image" src="https://github.com/sul-dlss/argo/assets/42216982/493f87e3-3d95-45ee-9def-453146e68821">

4. Secondary disabled
<img width="151" alt="image" src="https://github.com/sul-dlss/argo/assets/42216982/81b8316c-5dc1-4a81-8bcd-03fcfc431366">

Proposed buttons
1. Primary filled buttons (digital blue base 006CB8, on hover = digital blue dark 00548F)
They have a default state and hover state. (the mockup below shows an icon which is optional)
<img width="86" alt="image" src="https://github.com/sul-dlss/argo/assets/42216982/b93e579e-ad69-49e9-bc12-e4d6c20d616d">

2. Secondary outline buttons (digital blue base 006CB8, on hover = digital blue dark 00548F)They have a default state and hover state. (the mockup below shows an icon which is optional) 
<img width="88" alt="image" src="https://github.com/sul-dlss/argo/assets/42216982/ef51ffc5-fb87-4160-a61e-e784a5069afc">

3. Primary disabled: Same button as described in 1 above, but no interactive elements (no hover or while pressing states). Background color is 50% black.
<img width="132" alt="image" src="https://github.com/sul-dlss/argo/assets/42216982/0e1853ff-e0f7-4863-b981-17eb68778a2d">

4. Secondary outline buttons: Same button as described in 2 above, but no interactive elements (no hover or while pressing states). Outline is 50% black and text is 50% black, no fill. 
<img width="132" alt="image" src="https://github.com/sul-dlss/argo/assets/42216982/e0d3d3b3-9906-428d-a31b-9f8f81c0d73e">

**Comment by astridu** [comment]
Saw these on stage, and they look really good. Sorry to do this to you, but we made a couple tweaks to the hover state for the blue buttons, and also refined the colors for the disabled buttons.

1. Hover state for filled button now has an underline:
<img width="146" alt="image" src="https://github.com/user-attachments/assets/7d45d492-c1dc-4804-bab0-8f9618cbba58">

2. Hover state for outline button now has an underline:
<img width="146" alt="image" src="https://github.com/user-attachments/assets/14ac651e-59fe-4e8e-a779-43722b863bb5">

3. Primary disabled: Same button as described in 1 above, but no interactive elements (no hover or while pressing states). Text is 80% black, Background color is 10% black, Stroke is 20% black.
<img width="254" alt="image" src="https://github.com/user-attachments/assets/c728bb14-3e36-4991-8b3e-e3da46304b2c">

5. Secondary outline buttons: Same button as described in 2 above, but no interactive elements (no hover or while pressing states). Outline is 50% black and text is 60% black, white fill.
<img width="254" alt="image" src="https://github.com/user-attachments/assets/fa7784fe-79db-432b-84d5-0d20bbdc485c">

Thank you for your patience!

**Comment by jcoyne** [comment]
@astridu is there a reason these designs to not match the DLSS components?  Are we no longer trying to have a component library? https://www.figma.com/design/K1syTsalaB1nlRftgOi0Pw/DLSS-Components?node-id=9-729&t=IVwOqWSNzSAHAPGu-0

**Comment by astridu** [comment]
@justinlittman I just checked the buttons on stage, and the disabled button colors look just slightly off. Is it better if I define them as hex colors?
-Primary outline buttons - disabled: Stroke=C0C0BF ; Fill=EAEAEA ; Text=585754
-Secondary outline buttons - disabled: Stroke=979694 ; Text=767674
Apologies, and thank you for your continued patience.

**Comment by jcoyne** [comment]
We may want to look at this https://github.com/sul-dlss/argo/pull/4539 to get all of the new component styles at once.

**Comment by jcoyne** [comment]
@astridu what should active buttons (e.g. open dropdown buttons) look like?  How about `:focus-visible` buttons?

**Comment by astridu** [comment]
Great questions. We just covered this in our DLUX meeting an hour ago. We decided on the following:

1. Active buttons will look like the hover state (the darker color)
2. We decided to use the browser default for focus on buttons, unless you have another suggestion.

**Comment by jcoyne** [comment]
@astridu For focus on buttons, bootstrap already overrides the focus state, so we have to pick something. We can't rely on a default.
