### ISSUE TITLE
Update table visual design in Argo (punting to the next workcycle)

### ISSUE THREAD

**Issue by astridu** [sul-dlss/argo#4531]
Current tables look like this:
<img width="572" alt="image" src="https://github.com/sul-dlss/argo/assets/42216982/8f3788e8-8fb2-41b4-9356-e593b6d766d7">

Our updated table style looks like this:

- Table title is H2 (semibold 28pt).
- Labels are bold.
- Descriptions are paragraph style.
- Gray lines under each row (black 30%) 
- 15pixel padding on left and right margins
- 9pixel padding in each row above and below text
- 25pixel space inbetween label and description columns

![image](https://github.com/sul-dlss/argo/assets/42216982/6f9512e1-f033-4513-b170-260c16b32eaf)

**Comment by justinlittman** [comment]
@astridu Is this specifically for Overview and Details table on item show page?

**Comment by astridu** [comment]
I also wanted to change the table styles for the workflows page, but I need Andrew's approval first.

**Comment by astridu** [comment]
> @astridu Is this specifically for Overview and Details table on item show page?

@justinlittman Andrew doesn't want to change the workflows page so we'll leave that as is. Can we change the table styles for the Overview, Details, and the Lifecycle and Workflow tables that appear under the History section?
