### ISSUE TITLE
Update the visual design of the section dividers on the Argo item pages (not a design component)

### ISSUE THREAD

**Issue by astridu** [sul-dlss/argo#4535]
Current design:
<img width="1313" alt="image" src="https://github.com/user-attachments/assets/e1d45bd7-5f8d-4706-871e-419983d7965a">

Proposed design:
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/9afb81a0-d962-4b6a-80ae-15ec2ec15247">

1. Font size: Semibold 28pt
2. Background color: EAEAEA
3. The corners have a 4pt radius.
4. The carat icon at the end is pointed down when the section is collapsed and pointed up when the section is expanded.

**Comment by justinlittman** [comment]
Please use Bootstrap icons for the caret.

**Comment by astridu** [comment]
All the icons I'm using are now from the Bootstrap library. Let me know if you can't find one.

**Comment by astridu** [comment]
@jlittman Same with this one. I updated to hex color.
