### ISSUE TITLE
Banner for old versions in Argo

### ISSUE THREAD

**Issue by astridu** [sul-dlss/argo#4608]
We are requesting a few refinements to the banner that appears for old versions of items in Argo:

1. Specify if version is a system or public version in the text:
-Current: You are viewing an older version.
-Proposed: You are viewing an older {system, public} version.

2. Add a link to the current version in the banner:
- Current: There is a link by the title to get back to the latest version, but we think it will be easier to locate if it's in the banner. 
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/3a282703-24b5-44c0-b7c0-635a5c2ada01">

- Proposed: Add link to latest version into banner-- "You are viewing an older {system, public} version. [View latest version.](https://argo.stanford.edu)" --- this link should go to the latest version
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/5364115f-bd50-4f8b-b22b-64603e28920d">

3. Visual design:
- Current: Looks like the banner is in the old visual style.
<img width="1304" alt="image" src="https://github.com/user-attachments/assets/be689281-526d-4b77-8631-f7ff7e4dac9a">

- Proposed: Use the visual style from the component library
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/5364115f-bd50-4f8b-b22b-64603e28920d">

**Comment by justinlittman** [comment]
@astridu Is the "View latest version" supposed to open in a new tab as the box-arrow-up suggests? The component library uses a right pointing arrow but these designs show a left pointing arrow. Is that intended?

**Comment by justinlittman** [comment]
Also, should the existing "Back to current" link be removed?

**Comment by justinlittman** [comment]
Blocked by https://github.com/sul-dlss/argo/pull/4601

**Comment by astridu** [comment]
Copying @andrewjbtw on my response in case he wants to change any of these:
1. Yes, open a new tab window
2. Use whatever is in the component library. I grabbed this from a mockup so it might be old.
3. Yes, back to current link should be removed. 
Thank you!

**Comment by justinlittman** [comment]
Super. Thanks for considering @astridu.
