### ISSUE TITLE
Consolidate constants

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/argo#462]
There is a relatively new file in `lib/constants.rb`, so how does that practice compare with other `config/initializers/*.rb` such as https://github.com/sul-dlss/argo/blob/develop/config/initializers/permissions.rb?  Is there a consensus on using the `lib/constants.rb` in favor of the initializers?  Should the permissions initializer move into `lib/constants.rb`?  Does the same argument apply to a one liner like https://github.com/sul-dlss/argo/blob/develop/config/initializers/indexer.rb?

What’s the general rails-y way to do this?  Is it `lib/constants.rb` or `config/initializers/*.rb`?  (I wonder if the permissions initializer was created by a rails generator or if it belongs to a rails gem.  I don’t see any evidence of the latter.)

**Comment by darrenleeweber** [comment]
The sulpub app uses a similar pattern to the `lib/constants.rb`, see
https://github.com/sul-dlss/sul-pub/blob/develop/config/application.yml
https://github.com/sul-dlss/sul-pub/blob/develop/lib/settings.rb
https://github.com/sul-dlss/sul-pub/blob/develop/app/helpers/authentication_helper.rb#L6-L7

**Comment by darrenleeweber** [comment]
There are also Argo settings in
https://github.com/sul-dlss/argo/blob/develop/config/settings/test.yml

**Comment by mejackreed** [comment]
Argo stuff in settings are something different than the constants being discussed consolidated.

**Comment by jmartin-sul** [comment]
agreed on constants vs settings.  settings are environment specific or likely to be tweaked over time, constants should be the constant things that we imagine will change very slowly or not at all.  i can see how there could be gray area, but i don't think any of the things we're looking at are in it.

**Comment by jmartin-sul** [comment]
which is to say, the permissions initialization clearly seems like a constant to me, and the log file thing clearly seems like a setting.  but the log file constant appears to be unused, and is misleading now that we've got other log file stuff in settings, so i just pushed a branch that drops it, and will create a PR shortly...

**Comment by darrenleeweber** [comment]
https://github.com/bbatsov/rails-style-guide#configuration

**Comment by mejackreed** [comment]
Yep, we are also using the config gem here and that has a specific pattern of approach to follow for configuration.

**Comment by jmartin-sul** [comment]
we did purposefully move away from the `config/environments` approach to the `config/settings/*.yml` approach (albiet via `config/environments` for old settings where we didn't want to replace all the existing references).  i personally prefer the new approach, since it's a bit easier to have the config in a different (private) repo.  the extra indirection adds a bit of overhead when settings in the private repo change, but my gut feeling is that the decoupling and clear separation of instance specific settings makes it easier to setup new instances on both laptops and VMs (and it also feels easier to change a specific local setting temporarily while keeping track of how it deviates from the "official" config).

**Comment by darrenleeweber** [comment]
For example, consider the code in:
`config/settings/test.yml`
```yaml
FEDORA_URL:   'http://fedoraAdmin:fedoraAdmin@localhost:8983/fedora-test'
SOLRIZER_URL: 'http://localhost:8983/solr/test'
```
and `config/environments/test.rb`
```ruby
Argo::Application.configure do
  # stuff
  Argo.configure do
    reindex_on_the_fly      Settings.REINDEX_ON_FLY
    date_format_str         Settings.DATE_FORMAT_STR
    urls do
      mdtoolkit             Settings.MDTOOLKIT_URL
      purl                  Settings.PURL_URL
      stacks                Settings.STACKS_URL
      stacks_file           Settings.STACKS_FILE_URL
      dor_services          Settings.DOR_SERVICES_URL
      workflow              Settings.WORKFLOW_URL
      dpg                   Settings.DPG_URL
      robot_status          Settings.ROBOT_STATUS_URL
      modsulator            Settings.MODSULATOR_URL
      normalizer            Settings.NORMALIZER_URL
      spreadsheet           Settings.SPREADSHEET_URL
    end
    bulk_metadata_directory Settings.BULK_METADATA.DIRECTORY # Directory for storing bulk metadata job info
    bulk_metadata_log       Settings.BULK_METADATA.LOG       # Bulk metadata log file
    bulk_metadata_csv_log   Settings.BULK_METADATA.CSV_LOG   # Bulk metadata log file in CSV format for end users
    bulk_metadata_xml       Settings.BULK_METADATA.XML       # Bulk metadata XML output file
  end
end
```

Is the YAML file overkill?  Why not put that content in `config/environments/test.rb`?  Or, why is it in the YAML file instead?

**Comment by jmartin-sul** [comment]
well, now that you point that out, we do sort of have to use that config pattern to set up dor-services.  but in that specific example, i think the things there could be referenced directly from settings in the app.  that'd take some work to change, and might be worth it at some point, but doesn't seem worth it now.

looks like we commented simultaneously, but my explanation for why we should stick with settings yml files instead of putting everything straight in `config/environments` is in my prior comment.

**Comment by darrenleeweber** [comment]
FWIW, consider the sul-pub project use of YAML with a `defaults` block followed by env-specific blocks, see
https://github.com/sul-dlss/sul-pub/blob/develop/config/application.yml

The entire `application.yml` file is overridden by a similar file in our private shared_configs repo.

**Comment by mejackreed** [comment]
Yep, we did that as an initial stop gap because we didn't know what the configs _should_ be per environment. This was the shortest/quickest way to bridge the gap to what we were doing to the config gem approach.

**Comment by darrenleeweber** [comment]
I was not aware of this, quoting the https://github.com/bbatsov/rails-style-guide#yaml-config:
"Since Rails 4.2 YAML configuration files can be easily loaded with the new config_for method:"
  `Rails::Application.config_for(:yaml_file)`
Seems neat.

**Comment by mejackreed** [comment]
Yep its cool. Just rethinking the config approach seemed a bit different than the intent around constants. Good discussion though.
