### ISSUE TITLE
Descriptive metadata bulk jobs (bulk action and replayable spreadsheet) should not close items that have never been accessioned

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#4623]
We have two descriptive metadata update methods that automatically close items as they are processed:

- bulk action upload of cocina spreadsheet
- replayable spreadsheet

Until the versioning model was changed to allow closing Registered items, these updates would only close Opened items, which are items that already have a version 1. Items that were in a Registered state were updated with new metadata but not closed.

Since the change in the versioning model, the descriptive bulk actions have been closing Registered items. This is resulting in two problems:

- Purls are published with no content because metadata updates accession them with no files
- Metadata and accessioning staff who rely on filtering what have traditionally been considered "unaccessioned" items - items with no files - are not able to filter accurately because items no longer have "Registered" status after being accessioned via metadata updates

**Request**

We should prevent metadata updates from automatically closing and publishing items that have never been accessioned. I'm not sure of the best way to do this, as returning to a special "Registered" status may not be an option.

**Comment by justinlittman** [comment]
So if object version = 1 then don't close?

**Comment by andrewjbtw** [comment]
Yes, I think that will cover it.
