### ISSUE TITLE
Change reset link back to red

### ISSUE THREAD

**Issue by astridu** [sul-dlss/argo#4629]
Sorry, I know I requested to change this to blue, but Andrew says he prefers it in red because it helps him scan the page for errors. 

On the All Workflows page:
<img width="893" alt="image" src="https://github.com/user-attachments/assets/b38af59f-8789-4063-8419-6d7095a9c6b3">

**Comment by jcoyne** [comment]
@lwrubel just revert https://github.com/sul-dlss/argo/commit/8292de199e2f86bb1f9b0727f61cddabbc239c0a
