### ISSUE TITLE
.htaccess generation logic should be broken out and tested

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#469]
currently, this is all inline in the rake task:
https://github.com/sul-dlss/argo/blob/develop/lib/tasks/argo.rake#L286

it'd be better if this code were a more traditionally encapsulated method.  write tests for the method, call the method from the rake task.  method probably goes in `/lib/` or something, maybe in a new class of its own.

**Comment by blalbrit** [comment]
The link in the description now 404s. Closing this ticket.
