### ISSUE TITLE
There's an <em> in my tab; and an inverted argo shell

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#481]
The tab label for detail display, e.g., https://argo-stage.stanford.edu/catalog/druid:bb004bn8654 has an odd \<em> insertion .... see old/new
![screen shot 2016-01-27 at 2 05 50 pm](https://cloud.githubusercontent.com/assets/1824732/12630066/7a7bf2b6-c4ff-11e5-9887-01d223e59666.png)

In both the favicon shows the argo shell upside down from the way it is now shown in our new header bar. Can it be flipped? I can provide an image if needed.

Marking this as blocker only as an indication of its anticipated inclusion in the release, at least for the unwanted tag.

**Comment by LynnMcRae** [comment]
I am happy showing the constructed citation that Argo uses as the titling string for it's display up here in the tab, but minus the html markup. An alternative would be to isolate the title by using whatever Argo grabs for the title within the citation, but there's no reason to make it different.

**Comment by mejackreed** [comment]
Argo grabs multiple titles to construct the citaiton: https://github.com/sul-dlss/argo/blob/3ba2b55d83c8371aeebda5e555de3771dc9f5f6b/app/helpers/dor_object_helper.rb#L5-L9

**Comment by LynnMcRae** [comment]
that means :title is already populated and could be used in the tab label as is? would you prefer that to a de-htlml-ized citation? I'm good either way
