### ISSUE TITLE
Show external file references in the Contents section of detail display

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#485]
For regular contents, the display looks like this 
![screen shot 2016-02-01 at 10 30 30 am](https://cloud.githubusercontent.com/assets/1824732/12726953/4d2f6508-c8cf-11e5-8e17-37596ac3fe41.png)

based on this kind of content metadata:
```
<contentMetadata type="image" objectId="bg730rr6720">
  <resource type="image" sequence="1" id="bg730rr6720_1">
    <label>Image 1</label>
    <file id="bg730rr6720_00_0001.tif" mimetype="image/tiff" size="31691632" preserve="yes" publish="no" shelve="no">
      <checksum type="md5">c3c03bf5e14d0726a53dce2e1e9b6d2a</checksum>
      <checksum type="sha1">c29a20b265844c7c053321903bf2dc8e4456b5df</checksum>
      <imageData width="2639" height="4000"/>
    </file>
    <file id="bg730rr6720_00_0001.jp2" mimetype="image/jp2" size="2001433" preserve="no" publish="yes" shelve="yes">
      <checksum type="md5">b9c58466d95922be4b86c2e778ee6eb7</checksum>
      <checksum type="sha1">33936e8e9c1f47e99ac73666ab0ec49d18d0e032</checksum>
      <imageData width="2639" height="4000"/>
    </file>
  </resource>
  <resource type="image" sequence="2" id="bg730rr6720_2">
```

For virtual resources, that are defined by an `<externalFile>` tag instead of a `<file>` tag, we get this:
![screen shot 2016-02-01 at 10 31 53 am](https://cloud.githubusercontent.com/assets/1824732/12726972/68ded180-c8cf-11e5-968d-dc6213426ec8.png)

Here's the start of content metadata:
```
<contentMetadata objectId="hj097bm8879" type="image">
  <resource id="hj097bm8879_1" sequence="1" type="image">
    <externalFile fileId="2542A.jp2" objectId="druid:cg767mn6478" resourceId="cg767mn6478_1"/>
    <relationship objectId="druid:cg767mn6478" type="alsoAvailableAs"/>
  </resource>
  <resource id="hj097bm8879_2" sequence="2" thumb="yes" type="image">
    <externalFile fileId="2542B.jp2" objectId="druid:jw923xn5254" resourceId="jw923xn5254_1"/>
    <relationship objectId="druid:jw923xn5254" type="alsoAvailableAs"/>
  </resource>
  <resource id="hj097bm8879_3" sequence="3" type="image">
```

Suggest a formatted display of the external file information under resource like so:
```
Resource (1) image 
    External file: 2542B.jp2 (from druid:jw923xn5254, resource "jw923xn5254_1)
```
Optionally the external object reference could be a link to that object in Argo. The file itself does not need to be linked for access like a regular file (might be nice someday, but an unnecessary complication to start with).

**Comment by drh-stanford** [comment]
The solution to this issue depends on a dor-services PR to get merged and ported to the 5.x branch: https://github.com/sul-dlss/dor-services/pull/128

**Comment by drh-stanford** [comment]
I dug into the Argo code a bit and this may not require the dor-services PR to fix.

The code in question is here:

https://github.com/sul-dlss/argo/blob/develop/app/views/catalog/_show_sections/_default_contents.html.erb#L52-L84

One question for @LynnMcRae is whether you need the file size listed for external files? Both preservation size and for individual files? The externalFiles also have labels, do you need to see those?
That is the resolution of the externalFiles looks like this -- where each resource has its own label:

```
<contentMetadata objectId="hj097bm8879" type="map">
  <resource id="hj097bm8879_1" sequence="1" type="image">
    <label>Cover: Carey's American atlas.</label>
    <externalFile fileId="2542A.jp2" objectId="druid:cg767mn6478" resourceId="cg767mn6478_1" mimetype="image/jp2">
      <imageData width="6475" height="4747"/>
    </externalFile>
    <relationship objectId="druid:cg767mn6478" type="alsoAvailableAs"/>
  </resource>
  <resource id="hj097bm8879_2" sequence="2" thumb="yes" type="image">
    <label>Title Page: Carey's American atlas.</label>
    <externalFile fileId="2542B.jp2" objectId="druid:jw923xn5254" resourceId="jw923xn5254_1" mimetype="image/jp2">
      <imageData width="3139" height="4675"/>
    </externalFile>
    <relationship objectId="druid:jw923xn5254" type="alsoAvailableAs"/>
  </resource>
</contentMetadata>
```

**Comment by LynnMcRae** [comment]
@drh-stanford We only need to display what is resident in content metadata, so no need to go looking for extra data like file size as it's not data resident in this object.  Label is actually there however, but I was assuming it would have already been displayed on a line of its own before formatting the <file> or <externalFile> lines. See first image in ticket.

**Comment by drh-stanford** [comment]
Here's what PR #571 implements -- the hyperlink goes to the show page for that child item.

![screen shot 2016-02-22 at 3 47 47 pm](https://cloud.githubusercontent.com/assets/1861171/13237037/62a0d52a-d97d-11e5-8277-daf0ae08089d.png)
