### ISSUE TITLE
Create deployment plan (script)

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#490]
We need a step by step sequencing of how the argo deployment will work. Argo, Dor Services, Dor Indexer.. and more!

Prerequisites:
 - [x] Update caml routes to handle multiple message receivers (I believe @cbeer did this already)
 - [ ] Have Argo 3.x deployed on production servers [prod-b]
 - [ ] Have dor_indexing_app deployed
       - [ ] legacy (dor-services 4.x) [prod]
       - [ ] current (dor-services 5.x) [dev, stage, prod]
 - [x] Install ruby 2.x on lyberservices [test, prod]
 - [ ] reindex argo prod

Upgrade steps in order:
 - [ ] Update caml routes to point to legacy and current dor_indexing_app deploys
 - [ ] Deploy `dor-services-app` with 5.x [dev, test, prod]
 - [ ] Upgrade robots to 5.x [dev, stage, prod]
     - [ ] Shutdown all robots
     - [ ] Deploy/reconfigure `robot-master`
     - [ ] Deploy/reconfigure `common-accessioning, assembly, item-release, gis-robot-suite`
     - [ ] Deploy/reconfigure `was-seed-dissemination, was-crawl-dissemination, was-crawl-preassembly, was-seed-preassembly, was-dissemination`
     - [ ] Start up all robots
 - [ ] ... other stuff
 - [ ] swap cores (now current index into name of old core)
     - [ ] stop writes
     - [ ] swap cores
 - [ ] Switch over DNS to argo 3.x prod

Upgrade steps out of critical path:
 - [ ] Deploy `dor-utils` with 5.x (listed as derelict https://github.com/sul-dlss/dor-services/issues/136#issue-121313213)

**Comment by drh-stanford** [comment]
We need to do this for dev/test/stage/prod environments, right? Are we planning to do them all concurrently or in sequence?

**Comment by mejackreed** [comment]
Maybe validate our upgrade script in dev, use stage as a dry run. Then go prod?

**Comment by jmartin-sul** [comment]
i like the idea of using dev as an initial place to validate the plan, then stage as a dry run, then prod after we get those two figured out.

are there services that don't run in dev (or stage) which run in prod?  other env differences that we might have to account for when testing the plan out?

**Comment by mejackreed** [comment]
Maybe we should put in the initial comment the env's that each thing has? I updated dor_indexing_app with a reference.

**Comment by drh-stanford** [comment]
Re: Thu meeting. We decided on Mon Feb 29th for the switchover. We also decided to skip the dev environment for now since it's so haphazard. @eefahy might have whiteboard photos for plan. Anything else not reflected in the checklist above?

**Comment by atz** [comment]
By the title of this ticket, we're done.  The plan is created.  I guess we'll leave this open until the deployment happens?

**Comment by atz** [comment]
For MON/TUES (Feb 29th/ March 1st):
- [ ] make sure argo3-prod index is ready (@jmartin-sul)
- [ ] camel routes to dor-indexing-app-pro (@cbeer) 
- [ ] redeploy dor-indexing-app-prod-a,b (@atz)
- [ ] redeploy argo-prod-a,b (@atz)

For WED (March 2nd):
- [ ] Shut down argo-prod (@tallenaz)
- [ ] Deploy dor-services-app to lyberservices-prod (@jmartin-sul)
- [ ] Deploy (almost) all robots (@drh-stanford)
- [ ] **DNS switchover**: `argo` -> `argo-lb` (@tallenaz)

- [ ] Modsulator update maybe? (@tingulfsen)

**Comment by jmartin-sul** [comment]
since @tingulfsen was asking questions about what to update for dor-services-app (presumably on test), i signed him up for the prod part.  since it came up in the context of pre-assembly testing, i signed him up for the pre-assembly config change too.  though @peetucket might be a more appropriate assignee since he's the primary maintainer on that (and i could do it if need be, since i did it on lyberservices-test recently).

**Comment by jmartin-sul** [comment]
a bit of shuffling on the task list in light of what's been done and what remains.

**Comment by ndushay** [comment]
I believe this is done so I am closing.  If I am wrong, please re-open.
