### ISSUE TITLE
investigate reindexing errors

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#491]
a full reindex was done on argo-prod-b last friday, and completed on sunday, but there were many errors.  some were failures to connect to remote services, but some appeared to be solrization errors.  we should investigate those errors and fix any problems in dor-services indexing.

once the indexing errors are fixed, we should run a full reindex again on argo-prod-b.

**Comment by jmartin-sul** [comment]
a full reindex was started early this past saturday (just after 1 am), and finished just after 1 am this morning.  there were some errors along the way, but it looks successful enough that we're planning to use it as the index for the recent deployment of Argo 3.0.

BulkReindexer was used on lists fed to PidGatherer from files, assembled from the old argo prod solr collection (to facet by object type for workflows, apos, etc) and from a dump of IDs in production fedora (to get the full list of objects that exist for indexing).  these extra steps are because risearch still doesn't return complete results.

workers were run on argo-prod-a and argo-prod-b (though workers were run on -a alone for the first few hours).  at first, we ran with 16 workers on each, but when -a started swapping on monday afternoon, the workers were killed, and we restarted with 12 on each machine (again, with just -a for a while, until i felt that was reasonably stable).  there were around 8000 network errors when the workers were shut down monday afternoon (all other shutdowns and restarts were graceful).  errored objects were re-queued, and the errors from then on looked like they had prior in the run (i.e. deterministic based on the object being indexed instead of on network conditions, and occurring at a rate between 0.5% and 0.8%).

workers were monitored using the eye job monitoring gem, configured to restart any worker consuming more than 1.5 GB of memory.  this was mostly reliable through monday afternoon, though one or two manual interventions were required when babysitting showed workers consuming > 1.5 GB.  after the monday afternoon pause, i tuned the eye config a bit, to give a 90 second timeout and 10 second grace period for worker start/stop/restart.  i also upped the polling interval to once every five minutes, and made one failure (instead of two) trigger a restart.  when running 12 workers per machine with the updated eye config, eye didn't fail to keep the workers within the stated limits (other than the short period for each where the worker had gone over but polling had yet to detect it).  no more memory incidents occurred, though obviously there were a lot of independent variables at play here, so it's hard to attribute that to one condition or change.

some workflow objects initially failed to index, because their solrization involved an expensive workflow service query.  this query was deemed unnecessary and was removed, after which the objects indexed successfully (https://github.com/sul-dlss/dor-services/pull/192, https://github.com/sul-dlss/argo/pull/628).

the current index is short by about 3000 items.  i've copied the logs from the indexing run.  using a modified version of a sed script i got from @atz to extract IDs for things that errored monday afternoon, i should be able to get a list of everything that errored, along with a collection of lines of code on which indexing occurred.  my hope is that bad data and bad indexing code can be fixed over the coming week, and we can attempt to reindex those items.  there were also items which were created on argo prod between when the lists were collected for bulk reindexing and now, so we'll have to diff solr with the current fedora pid list to see what else should be caught up.

since dor-indexing-app and dor-indexing-app-legacy are both getting queued requests from fedora and other services to reindex things, edits made from here on out should be indexed as expected.

more investigation to come, and some actual numbers re: error rate and throughput.

apologies for the rambling info dump, i wanted to capture those details somewhere, as i suspect lessons learned during this reindexing will come in handy in the future.

**Comment by blalbrit** [comment]
@jmartin-sul - do you have a list of druids that @LynnMcRae and I can investigate further with?

**Comment by jmartin-sul** [comment]
lists of errored druids sent to @blalbrit and @LynnMcRae on slack

**Comment by blalbrit** [comment]
one object in the two lists failed to be found in Fedora: druid:zr393wq3086

**Comment by jmartin-sul** [comment]
@blalbrit and @LynnMcRae found that most of the errors were ETDs with "old style" dc metadata datastream contents.  touching the datastreams and resaving them updated their structure and allowed them to be indexed.  other inexing problems seemed to be related to non-existent collection references and hydrus collections with bad data for the dc title field that was previously used to get the denormalized `collection_title_ssim` field for objects in collections.  both of those collection reference issues should be fixed in what is now the latest dor-services (5.6.0).  dor-indexing-app has been upgraded to use that version of dor-services, and has been deployed to prod.  upgraded argo should be deployed to prod soon.

**Comment by jmartin-sul** [comment]
hydrus items have been reindexed on prod, and it appears that the right hydrus collection titles are showing up in the facet.

**Comment by blalbrit** [comment]
Think we can close this ticket now?
