### ISSUE TITLE
Better consolidated status reporting for bulk actions

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#499]
Is it the same set of statuses we use for spreadsheets? Spreadsheet loading has an interpretive key that would be nice to include (a version of). Picture of its implementation shown below.
 Only need to show total and if/how many errors ... "Total / Errors"

See https://github.com/sul-dlss/argo/issues/136#issuecomment-178312739

**Comment by andrewjbtw** [comment]
I am closing this as I think the current bulk action display covers this.

<img width="1346" alt="Screen Shot 2020-04-16 at 5 36 28 PM" src="https://user-images.githubusercontent.com/8975583/79519474-d92e3800-8008-11ea-9530-1302b02b0e93.png">
