### ISSUE TITLE
Correct HTTP status codes on exceptions

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#500]
For example, in items_controller we return 403 Forbidden error codes for application logic or malformed client requests (should be 400 Bad Request)

See examples here:

https://github.com/sul-dlss/argo/blob/develop/app/controllers/items_controller.rb#L463
https://github.com/sul-dlss/argo/blob/develop/app/controllers/items_controller.rb#L547
https://github.com/sul-dlss/argo/blob/develop/app/controllers/items_controller.rb#L562-L568

**Comment by aaron-collier** [comment]
The links above are out of date, but I believe this is referring to areas like:

https://github.com/sul-dlss/argo/blob/master/app/controllers/items_controller.rb#L376

where a 403 is returned for the argument error and it should be 400 (:bad_request)
