### ISSUE TITLE
integrate spreadsheet uploads into new bulk actions framework

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#501]

**Comment by LynnMcRae** [comment]
This also involved the (desired) migration of the capability from being APO based to being person-based and the update of APO checking from a simple test of whether it matches the current-APO 9which the user had privileges to get to) to an individual rights test on each druid as done for other Bulk Actions.

**Comment by andrewjbtw** [comment]
Still relevant in 2020 but we should make tickets for each spreadsheet use case. Currently, only the virtual objects bulk action created in fall 2019 includes spreadsheet functionality. 

The MODS bulk upload also included spreadsheet functionality but is not in the same part of the interface as the bulk actions.

**Comment by andrewjbtw** [comment]
Closing in favor of individual tickets for different actions using spreadsheets.
