### ISSUE TITLE
Reporting views - issues with column selection modal

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#503]
For both reporting views, the title bar is empty and the background is transparent
![screen shot 2016-02-09 at 9 08 07 am](https://cloud.githubusercontent.com/assets/1824732/12924047/0e633946-cf0d-11e5-8239-2fa2ad02df3d.png)

**Comment by mejackreed** [comment]
Can you give paths to these?

**Comment by LynnMcRae** [comment]
do you mean clicking on the "Columns" button at the bottom of either reporting view?

**Comment by mejackreed** [comment]
Yep.. path (relative url) and process to recreate. Sorry wasn't immediately clear how to recreate the bug to me. After your comment, I now understand :)

**Comment by drh-stanford** [comment]
This is suspiciously similar to the Date Picker problem in the Embargo modal dialog #416 . I tried the z-index fix for that one but it didn't work.
