### ISSUE TITLE
Discovery report - column issues

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#504]
The Discovery report view needs work as most of the columns no longer work but can be replaced with data from new facet fields:

Druid
- good

Druid
- This shows a sequence number but starts back at one after 20 entries, see attachement. Drop from column selection.

Display Title, Sort Title
- Only the second seems to be working (Sort title).  Replace both with just one labeled "Title", same as the other report view.

Format
- Replace with three columns from SW Resource type, SW Genre and MODS Resource Type

Topic Search, Subject All
- Drop these two columns

Topic Facet
- Replace with SW Topic facet

Geographic Facet
- Replace with SW Region facet

Era Facet
- Replace with SW Era facet

Language Facet
- Replace with SW Language Facet
- Don't know where the "(none)" comes from in current report; not needed

Pub Date Sort, Pub Date Group Facet, Pub Year Facet, Pub Date Display
- replace all 4 with one that shows SW Date facet

For all columns coming from facets, use just the name of the facet without adding the word facet to the end, i.e. "SW Language", not "SW Language Facet"

![screen shot 2016-02-09 at 9 15 31 am](https://cloud.githubusercontent.com/assets/1824732/12924861/4f33197a-cf10-11e5-8308-c99f1fdd277e.png)

**Comment by mejackreed** [comment]
Seems kind of straightforward. Most likely the biggest hurdle here will be adding tests for this previously untested code.

**Comment by drh-stanford** [comment]
Closed from removal in #512.
