### ISSUE TITLE
Republish leads to non-exitable flash message

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#506]
![screenshot 2016-02-09 11 53 30](https://cloud.githubusercontent.com/assets/796990/12928706/df541758-cf23-11e5-9499-40f3195236e5.png)

**Comment by mejackreed** [comment]
Would be good to know what rev of software this happened. Might have already been addressed by @drh-stanford

**Comment by drh-stanford** [comment]
Yes, the current stage deploy is 37d0689170f4fd311c459ca52cbf88190237a316 which is before the Republish fixes were merged. So, this issue should be fixed on the next deploy. If not, please reopen.
