### ISSUE TITLE
Comments on new Bulk Actions screens

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#507]
- [ ] No way to back out of main screen. Either a Back button or the "Return to search" navigation
- [x] Should preselect the only radio button available
- [ ] Label button "Populate from current search" not ...previous...
- [ ] Disable submit button until there is a druid list

**Comment by mejackreed** [comment]
> No way to back out of main screen. Either a Back button or the "Return to search" navigation

It's not assumed that a user can always be coming from the search here. Do we need to offer a back button that duplicates browser functionality?

> Label button "Populate from current search" not ...previous...
Similar to previous comment. You aren't always guaranteed to come here directly from a search. Can you think of something better than "current"?

> Disable submit button until there is a druid list
Is this really a blocker?

**Comment by LynnMcRae** [comment]
The Bulk Actions button is only offered on a search results page right now, and the only expectation is to use the current search until we offer access to search history. Am I missing something?

**Comment by mejackreed** [comment]
Yes, users can get to that page by visiting the url directly. Because we don't offer that link, doesn't mean someone doesn't bookmark it or power use it frequently. Can we make that expectation that they will always come from a search?

**Comment by LynnMcRae** [comment]
I just made all my feedback an extension of the current overall blocker ticket without trying to over analyze or second guess easy vs hard. It's all negotiable.

**Comment by mejackreed** [comment]
Gotcha.. So is this really a blocker? Or something we really would like to have. Re: Should we prioritize fixing this, figuring out how we are going to launch.. etc?

**Comment by LynnMcRae** [comment]
Yes, we don't generally support jumping into Argo places directly without navigating there except for results and displays; we're certainly comfortable saying all bets are off for forms.  if/when we offer, say, a top of the screen way to initiate a Bulk Action apart from search (like for a druid list), it would need to know to offer search history or user-provided list based on context in the absence of a current search.

**Comment by LynnMcRae** [comment]
I would not call the submit button a blocker because it's not something we expect the user to do.  It's just not good to have such UX bombs in there in general, given it leads to a system error.

**Comment by blalbrit** [comment]
I think the bulk action screens have evolved to a point where this ticket is superseded. We would want a UI/UX review before an Argo revamp.
