### ISSUE TITLE
Indexing should succeed with a bad APO or collection reference

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#510]
We are unable to index/reindex any object with a bad APO or collection reference in RELS-EXT, which makes it difficult to view or repair them. It would be sufficient to simply place the druid in where the de-referenced titles would be; that provides a visual clue in the UI that the APO or Collection reference is bad.  Need to consider the APO and Collection names as shown on the results page, detail page, and facet list, which all might come from the same SOLR field.

This may be behind #334 and if changed, may address those issues.

**Comment by jmartin-sul** [comment]
reopening, as per https://github.com/sul-dlss/dor-services/pull/162#issuecomment-190570087

**Comment by jmartin-sul** [comment]
to be fair, i think this same problem occurs on argo 2.x*.  as such, this does not seem necessary to achieve feature parity, and i'd be in favor of not letting this block the release (which is to say, this doesn't seem like it should have the "blocker" tag).

* see https://jirasul.stanford.edu/jira/browse/ARGO-361 ("improve reindexing failure error message").  it appears that issue never got moved to github, for whatever reason.

**Comment by LynnMcRae** [comment]
I agree, at this hour we might delay for a significant feature not working but not for a flaw not-yet-resolved (a blocker as a critical fix). We're are working on time for follow-through on this release, recognizing it's not likely to be perfect out of the gate, so I'd like to keep the few outstanding critical items marked somehow. In this case it was theoretically working. Not so?

**Comment by LynnMcRae** [comment]
The state of this issue is this

1. objects with a bad APO druid reference in RELS-EXT/isGovernedBy index now ... they substitute the druid value for the APO title that cannot be fetched.  
2. Objects with a bad Collection druid reference in RELS-EXT/isMemberOfCollection still get an indexing error (Object not found). The same fix applied to bad APO druids should be applied here.

My test objects:

stage    
   bad-apo	gd670yn8743	
   bad-collection	pb502qg7296
	
dev
   bad-APO	dx356sv3797
   bad-collection	gp463pt5864

**Comment by jmartin-sul** [comment]
PR for proposed fix here:  https://github.com/sul-dlss/dor-services/pull/201

needs input as to the desired behavior, and should probably be deployed and tested on stage.
