### ISSUE TITLE
Remove "edit" link from Content portion of detail display

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#523]
This shows up for any object that is editable -- registered or opened -- with content.  See https://argo-dev.stanford.edu/catalog/druid:qs553rb8234

![screen shot 2016-02-16 at 10 35 07 am](https://cloud.githubusercontent.com/assets/1824732/13086653/fcffaec8-d498-11e5-84f5-f91a627f128c.png)

**Comment by drh-stanford** [comment]
does that also mean removing all the associated functionality which is available from the (edit) link? There's a bunch of stuff in there (See https://github.com/sul-dlss/argo/blob/develop/app/views/items/resource.html.erb)

**Comment by LynnMcRae** [comment]
That's a call for you guys to make. There is a useful set of functionality represented by that code, but it was never quite completed. Who knows when and under what circumstances we'll get back to it.  Jack had some opinions I think, about benefits/expedience of keeping/removing inert code this week.

**Comment by mejackreed** [comment]
I'd vote for removing the dead route, and dead partials associated with it. If there is a github ticket for adding this functionality later, we can link the removal commit to that ticket. That way later on down the line we can easily find the old code. 

I prefer not maintaining code that isn't executed or used. And that way we don't have to have this discussion, or a future argo dev doesn't have to spend the time figuring out what the heck that thing is.

**Comment by drh-stanford** [comment]
I prefer removing the code too, but I wanted to make sure that dialog is no longer needed. 

There's at least a few routes I see that would be candidates for removal: `resource`, `add_file`, `replace_file`, `delete_file`.

**Comment by mejackreed** [comment]
I think `add.png` can also be removed.
