### ISSUE TITLE
Continuing Indexing Errors Post-Registration in -stage

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#531]
1) User registers x number of objects
2) Objects appear in Fedora
3) Objects do not appear in Argo
4) User is forced to manually reindex all objects in order to get them to appear in Argo

**Comment by drh-stanford** [comment]
Are they any error messages during Step 1?

**Comment by drh-stanford** [comment]
It looks like we don't explicitly index the object after we call the RegistrationService. 

https://github.com/sul-dlss/argo/blob/develop/app/controllers/dor/objects_controller.rb#L9

**Comment by LynnMcRae** [comment]
We used to explicitly reindex after registration to make it immune from indexer backlog, and because we needed any immediate reruns to correctly perform the "Is this source ID already used" check (a solr lookup) that is part of registration. Was the immediate reindex removed?

**Comment by drh-stanford** [comment]
i don't see any assignee for this blocker... @jmartin-sul are you still looking into this? if not, i could take it

**Comment by jmartin-sul** [comment]
not at the moment, all yours, if you wouldn't mind.

**Comment by drh-stanford** [comment]
In digging through the old code, I found that after each registration of a new item, the `update_index` call is made (via dor-services 4.19.1)

   https://github.com/sul-dlss/dor-services/blob/v4.19.1/lib/dor/services/registration_service.rb#L120

This only happens if `ENABLE_SOLR_UPDATES` is enabled. In looking at current prod Argo, this flag is disabled:

```
$ cat initializers/activefedora_solr_updates.rb 
...
self.class.const_set('ENABLE_SOLR_UPDATES', false)
```

so current Argo is relying on the reindexing pipeline to index newly registered objects as far as I can tell.

**Comment by drh-stanford** [comment]
In new Argo and 5.x dor-services, the registration is also relying on the reindexing pipeline for newly registered objects.

  https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/services/registration_service.rb#L138-L139

So, the question to @LynnMcRae is do we want to keep this behavior (as current Argo has -- see above comment), or do we want to enable synchronous indexing on newly registered objects? The 5.x registration code does indeed check the solr index for a source id duplication:

  https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/services/registration_service.rb#L70

**Comment by LynnMcRae** [comment]
Yes, I believe the synchronous indexing was done to solve a problem which would come back without it. Adding @blalbrit for confirmation.

**Comment by LynnMcRae** [comment]
This JIRA ticket that raised the issue originally was https://jirasul.stanford.edu/jira/browse/ARGO-105 ... we shall ignore the fact that any work done was not reflected in the ticket itself though I know there was followup. I shall close that ticket :)

**Comment by blalbrit** [comment]
Confirming @LynnMcRae that synchronous indexing was done to solve a problem... etc. Basically a second thumbs-up. The lab staff need real-time immediate indexing at registration in order to generate tracking sheets for the objects they are registering - for instance.

**Comment by drh-stanford** [comment]
Ok, I've created PR #553 that implements synchronous indexing.
