### ISSUE TITLE
refactor the Contents view

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#536]
The `default_contents.html.erb` needs refactoring. It's not DRY and has some anti-patterns for MVC.

Some comments on how we might revise the view:
- We really shouldn't be assigning variables in the view like this. This is an actual use case for moving logic to a helper.
- There is a big opportunity to break this out into multiple partials. I could see something like _default_contents_resource.html.erb and _default_contents_file.html.erb. Each of those individual partials could be passed the locals it needs to render properly.
- ContentMetadata resources could be broken out into their own classes. This would be useful for testing purposes and maintainability. sul-embed does something similar here with its Resources and ResourceFile classes generating objects based off of purlxml: https://github.com/sul-dlss/sul-embed/blob/master/app/models/embed/purl.rb#L138-L204

**Comment by aaron-collier** [comment]
Closed in: https://github.com/sul-dlss/argo/commit/9fe948b979d85501d0ce0398665ebf277f4bff79
