### ISSUE TITLE
Diagram View Modal in Workflows - No way to close? (-stage)

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#537]
Once the "diagram view" is open from within a workflow, there is no "close" box in the modal, and clicking outside the modal won't close it either.

Steps:
1. Item view (https://argo-stage-b.stanford.edu/catalog/druid:cg733xc6142)
2. Click on specific workflow:
![screenshot 2016-02-17 17 22 35](https://cloud.githubusercontent.com/assets/796990/13130744/230c19b4-d59b-11e5-9360-81bf6e25da72.png)
3. Choose "diagram view"
![screenshot 2016-02-17 17 22 50](https://cloud.githubusercontent.com/assets/796990/13130748/2f98ed24-d59b-11e5-8a0e-b6e2e144e8b2.png)
4. Can't close.
![screenshot 2016-02-17 17 09 58](https://cloud.githubusercontent.com/assets/796990/13130675/c3d4f74a-d59a-11e5-853e-26c328c7746a.png)

**Comment by mejackreed** [comment]
Yep... became difficult to enable this. At one point I asked how much we use that diagram... and it was deemed not crucial. See duplicate ticket:
https://github.com/sul-dlss/argo/issues/430

And context:
https://github.com/sul-dlss/argo/pull/410#issuecomment-169790316

**Comment by blalbrit** [comment]
Closing as duplicate. Thanks for the reminder Jack.
