### ISSUE TITLE
Update embargo date-time with zone?

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/argo#545]
Rubocop complains about:
```
app/controllers/items_controller.rb:243:37: C: Do not use DateTime.parse without zone. Use one of Time.zone.parse, DateTime.current, DateTime.parse.in_time_zone, DateTime.parse.utc, DateTime.parse.getlocal, DateTime.parse.iso8601, DateTime.parse.jisx0301, DateTime.parse.rfc3339, DateTime.parse.to_i, DateTime.parse.to_f instead.
    @object.update_embargo(DateTime.parse(params[:embargo_date]))
```
How is this to be resolved?  What date-time should be used for an embargo update?  Also, how does this interact with the datastore settings (if any could modify the ruby code assumptions)?

**Comment by mejackreed** [comment]
Seems like the `update_embargo` method assumes UTC of whatever "date" is passed in. https://github.com/sul-dlss/dor-services/blob/a1c8adb08755461767a6ae0c6cdebaeb309c929e/lib/dor/models/embargoable.rb#L72

So for a user submitting a date, should that date be local or UTC?

**Comment by darrenleeweber** [comment]
@LynnMcRae - what time zone should an embargo update take?

**Comment by LynnMcRae** [comment]
I believe the situation is this.  What was required for embargoing was a calendar date. It is not a moment in time where the UTC offset or local reference is critical. It simply says if you submitted your ETD on July 1 with a one year embargo, we prime the "last day of embargo" with July 1 of the following year and embargoes are released shortly after midnight local time. What we see in the current data is a timestamp like 
```
<releaseDate>2016-06-25T07:00:00Z</releaseDate>
```
I believe to appease the gods of datetime stamps and date arithmetic while avoiding false precision. As long as the embargo release query works properly -- anything still under embargo with an embargo release date before "today" -- then the time and timezone are functionally irrelevant. The current form of the data works in this regard.
