### ISSUE TITLE
Investigate resource editing capability

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#566]
Legacy argo had the ability to edit resource files. This feature unfortunately did not work and was unwieldy. Feature removed in c7f72ab5860ba538e1af6e6b7eb4f5dded4b2805 #565. 

If implemented in the future, would need some design work, updated patterns.

**Comment by andrewjbtw** [comment]
This is still relevant but should be split into new tickets for the different aspects of the work. It looks like the previous functionality included:

1. Editing resource labels
2. Editing attributes like publish/shelve/preserve

**Comment by andrewjbtw** [comment]
This is now covered by structural metadata editing functionality.
