### ISSUE TITLE
Separate workflow actions in ItemsController

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/argo#580]
While trying to debug the feature spec for workflow_service_create, try using this:

```
expect_any_instance_of(ItemsController).not_to receive(:add_workflow)
visit add_workflow_item_path item.pid
```

It blows up.  This means the UI display is calling that method to create the display before any form is submitted, I think. (edited)

So I think that means this method is taking on the responsibility of both a `new` and a `create` action, maybe?  At a guess, wondering whether the workflow actions need to be broken out into a separate controller from the `ItemsController`?

Or at least two actions like `ItemsController#workflow_new` and `ItemsController#workflow_create`? 
Other controller methods are `ItemsController#workflow_*`, i.e.

```
$ ack-grep 'def.*workflow' app/controllers/items_controller.rb 
  def workflow_history_view
  def workflow_view
  def workflow_update
  def add_workflow
```

Checking params on each call to the existing `ItemsController#add_workflow`:

On `new` it has only:

```
> params
=> {"controller"=>"items", "action"=>"add_workflow", "id"=>"druid:hj185vb7593"}
```

On `create` (or ‘Add’ button click), it has:

```
> params
=> {"utf8"=>"✓", "wf"=>"accessionWF", "controller"=>"items", "action"=>"add_workflow", "id"=>"druid:hj185vb7593"}
```

**Comment by darrenleeweber** [comment]
Appreciate considerations from @drh-stanford who may have worked most on WFS and ItemsController.

**Comment by drh-stanford** [comment]
As I remember the line ```return unless params[:wf]``` in `ItemsController#add_workflow` will cause the Add Workflow form to be generated (the UI). Then (on form post) when `wf` is passed in, it will actually create the workflow. Is that the question at hand?

The workflow_view, etc. stuff has to do with the display of the individual workflows (i.e., it shows the status for each process step, etc.)

**Comment by darrenleeweber** [comment]
I submit there *should* be separate controller actions for `new` vs. `create` in any Rails app.  The use of one parameter check, i.e. `return unless params[:wf]`, in one method to differentiate these actions is not at all clear as to it's purpose and the meaning of the method as a whole.  I argue that this method *should* be broken up into something like `object_workflow_new` and `object_workflow_create`.

**Comment by darrenleeweber** [comment]
See also commentary in #564 although not specifically a solution of this issue.  While working on Argo, often noticing strange inconsistent behavior in the specs for this feature.
