### ISSUE TITLE
Barby symbologies not installed

### ISSUE THREAD

**Issue by atz** [sul-dlss/argo#6]
Post-install message from barby:

**\* NEW REQUIRE POLICY ***
Barby no longer require all barcode symbologies by default. You'll have
to require the ones you need. For example, if you need EAN-13,
require 'barby/barcode/ean_13'; For a full list of symbologies and their
filenames, see README.

So we need to determine which secondary gems we need and start requiring them explicitly.  List at:
https://github.com/toretore/barby/blob/master/README

**Comment by aaron-collier** [comment]
This looks to have been closed some time ago: https://github.com/sul-dlss/argo/commit/6dfa0c8fa9ed25bed4c1dce75eca4be40fa7da0a
