### ISSUE TITLE
embargo_update must be an authorized action

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/argo#622]
Issue to track and ensure that `ItemsController#embargo_update` is included in a `before_action` for authorized access so that it short-circuits all the `after_action` activity when it's not authorized (otherwise it will save and reindex unnecessarily).

**Comment by darrenleeweber** [comment]
Currently, it is not in the `before_action` for authorization in
https://github.com/sul-dlss/argo/blob/master/app/controllers/items_controller.rb#L9

**Comment by darrenleeweber** [comment]
A retrospective note:  An alternative solution to #624 is to remove `embargo_update` from all the `after_action` and have it call them directly after it checks `is_admin`, if it’s really important that only `is_admin` can be authz for that action.

**Comment by darrenleeweber** [comment]
@LynnMcRae - is it really important that ONLY `is_admin` can update embargo?  Is it OK for anyone with a role allowed to manage the item content to update the embargo too?

**Comment by LynnMcRae** [comment]
"is it really important that ONLY is_admin can update embargo?"

Was that how it was coded? I can't see that was ever a requirement. According to roles and permissions page (https://consul.stanford.edu/display/chimera/Repository+Roles+and+Permissions), embargo management is an update action no different that any others, for sdr-admins and apo-managers.

**Comment by darrenleeweber** [comment]
OK, from https://consul.stanford.edu/display/chimera/Repository+Roles+and+Permissions, it appears that `manage embargo` has the same access roles as `manage contents`.  The current before action filter allows any `is_admin` and then any role that can `manage_content`.  So that implementation seems to meet the requirements.  The details depend on the roles (misnamed groups) in
https://github.com/sul-dlss/dor-services/blob/master/lib/dor/models/governable.rb#L87-L89
So, it allows: `['dor-administrator', 'sdr-administrator', 'dor-apo-manager', 'dor-apo-depositor']`
