### ISSUE TITLE
Report Download Function - omits Admin Policy ID column (others?) on download

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#627]
https://argo-lb.stanford.edu/report?f%5BobjectType_ssim%5D%5B%5D=workflow and click 'download' . Did work in prod.

Needs further testing to determine which other columns are being dropped.

List of columns
- Admin Policy ID 
- Catkey

**Comment by mejackreed** [comment]
When you say "Did work in prod" do you mean legacy argo 2.x ?

Currently investigating and the same result happens in v3.0.0-rc.1 and v3.0.0-rc.2

**Comment by blalbrit** [comment]
@mejackreed Yes - works in legacy argo 2.x. Not a blocker to release.

**Comment by mejackreed** [comment]
A few things happening here:

`@field` assigning here doesn't compare symbols and strings correctly. Some field names are strings some are symbols. https://github.com/sul-dlss/argo/blob/master/app/models/report.rb#L169
