### ISSUE TITLE
Reconcile movable and non-movable modals

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#633]
Starting this ticket with an observation ... 

Datastream modals are not movable.  A click and move in the modal highlights text and allows copy of text

Workflow, View DC, View MODS, Modsulator log, and other modals are movable.  A click and move will move the modal.  You lose the ability to copy text from such a window (this is not good).

Can model movement be constrained to the title bar on the modal?  Want to make sure we resolve this before going all one way or the other.

**Comment by mejackreed** [comment]
> Can model movement be constrained to the title bar on the modal? Want to make sure we resolve this before going all one way or the other.

Yes this is possible.

**Comment by drh-stanford** [comment]
Would that solve the "You lose the ability to copy text from such a window (this is not good)." problem?

**Comment by mejackreed** [comment]
Yes

**Comment by jcoyne** [comment]
@aaron-collier I think we should close this as won't fix. This comes from the days before we used bootstrap modals.
