### ISSUE TITLE
Purge is enabled for an object in accessioning

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#634]
In stage, object druid:cz273df8849is in accessioning but the Purge button is enabled.  It should oinly be available for "Registered" objects.

<img width="854" alt="screen shot 2016-03-02 at 2 49 11 pm" src="https://cloud.githubusercontent.com/assets/1824732/13478465/0a12e5b4-e086-11e5-8eb6-3ef5f1ee82d3.png">

**Comment by drh-stanford** [comment]
Just to be clear, purge is limited to objects that are Registered *only* -- no other lifecycles achieved?

**Comment by LynnMcRae** [comment]
The Registered=pending here indicates the initial workflow did not record a lifecycle=registered event, or more likely there was no workflow prior to accessioning to declare that lifecycle. 

If the object has not yet been accessioned in this condition, the Processing Status is calculated as "Unknown Status" for the facet -- we have about 47k old objects in this condition. We would like both Registered and Unknown Status to be considered synonymous and treated the same for Purge, the important fact being it has never been accessioned which would have passed it into the un-purgable Preservation Core.

btw, we went back and forth on whether the Processing Status should collapse them, but opted for it to reveal the discrepancy rather than hide it, with the possibility of adding the registered lifecycle into the history

**Comment by drh-stanford** [comment]
@LynnMcRae can an object be purged if it's being versioned? for example if the status were "v5 Registered"?

**Comment by LynnMcRae** [comment]
The definition of Registered should preclude that ... any state that allows an object to be modified after v1 is by definition "Opened". Thankfully the Argo facets bear this out:
![screen shot 2016-03-09 at 3 29 42 pm](https://cloud.githubusercontent.com/assets/1824732/13654292/35eb2f1c-e60c-11e5-909d-30736300405b.png)

If you wanted to add a v1 check as a belt or suspender, that's fine too.

**Comment by drh-stanford** [comment]
Ok I have a PR open which determines the state of the Purge button based on the Processing Status facet. If it's "Registered" or "Unknown Status" then the Purge button is enabled; otherwise it's disabled.
