### ISSUE TITLE
Should have standard label for View MODS modal

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#635]
If you look at the "View Dublin Core" modal, there's a stock title and the body shows druid and the dublin core, starting with title. 
<img width="845" alt="screen shot 2016-03-02 at 3 34 44 pm" src="https://cloud.githubusercontent.com/assets/1824732/13479524/5be837da-e08c-11e5-8cd8-d25829ae40bb.png">

View MODS however puts the work title in the title bar, and the rest of the MDOS in the body.
<img width="854" alt="screen shot 2016-03-02 at 3 34 03 pm" src="https://cloud.githubusercontent.com/assets/1824732/13479517/42b4f5be-e08c-11e5-8bad-43f08c1b7dbb.png">

The Dublin Core approach is preferred.

**Comment by mejackreed** [comment]
Any suggestions on what the label should be?

**Comment by LynnMcRae** [comment]
Generally (but not uniformly) we label the modal the same as the label of the button that got you there? "View MODS" would be fine here I think.

**Comment by mejackreed** [comment]
:cool:

**Comment by andrewjbtw** [comment]
I think this functionality has been removed from the interface.

**Comment by LynnMcRae** [comment]
@andrewjbtw View MODS is still a feature, at the top of the detail display, still not consistent with other modal views.

**Comment by andrewjbtw** [comment]
My mistake. I must have gotten so used to scrolling right past that part of the page that I stopped noticing it.
