### ISSUE TITLE
Add "All Workflows" link to global navigation

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#64]
We eliminated the little table icon in the facet list that took you to a view of all workflows for all objects on the front page -- essentially the workflow view with all items found. Expand the row of global links at the top of pages to be 

   ...  All Workflows | Register Items | Register APO 

"All Workflows", if picked from anywhere but the home page, should act as a Start Over (results/facets cleared) with the all-workflows view.

**Comment by drh-stanford** [comment]
So the new header links will look like this:

![screen shot 2015-11-19 at 3 48 55 pm](https://cloud.githubusercontent.com/assets/1861171/11288031/162a41b0-8ed5-11e5-82c2-d6b1a5256a48.png)

**Comment by mejackreed** [comment]
I'm a little concerned about adding another thing to this navigation bar. Now this may be feature parity with legacy argo, but maybe a different navigation structure is needed?

**Comment by mejackreed** [comment]
Oops didn't see the PR for this already... maybe revisit?
