### ISSUE TITLE
Consolidate WFS helpers

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/argo#640]
Migrating some WFS helpers from controller private methods into new `DorObjectWorkflowStatus` utility.

Referring to helpers like those in:
https://github.com/sul-dlss/argo/blob/master/app/controllers/items_controller.rb#L709-L727
https://github.com/sul-dlss/argo/blob/master/app/controllers/workflow_service_controller.rb#L80-L89
https://github.com/sul-dlss/argo/blob/master/app/controllers/workflow_service_controller.rb#L39-L89

**Comment by darrenleeweber** [comment]
Related to recent work in https://github.com/sul-dlss/argo/pull/636

**Comment by darrenleeweber** [comment]
A refactor consideration is whether the common helper methods could and should be consolidated into the `Dor::WorkflowService` itself.  If so, it makes sense to remove the wrapper class.

**Comment by darrenleeweber** [comment]
Areas in the code that use the `Dor::WorkflowService` are:
```
ack-grep 'Dor::Config.workflow.client' app/
app/models/dor_object_workflow_status.rb
22:    Dor::Config.workflow.client

app/controllers/items_controller.rb
134:    @history_xml = Dor::Config.workflow.client.get_workflow_xml 'dor', params[:id], nil
191:      Dor::Config.workflow.client.get_workflow_status params[:repo], *args.take(3)
193:      Dor::Config.workflow.client.update_workflow_status params[:repo], *args
717:    Dor::Config.workflow.client.get_workflow_status('dor', object.pid, 'accessionWF', task)
721:    Dor::Config.workflow.client.get_lifecycle('dor', object.pid, stage)
725:    Dor::Config.workflow.client.update_workflow_status('dor', object.pid, 'accessionWF', task, status)

app/controllers/report_controller.rb
73:      Dor::Config.workflow.client.update_workflow_status(

app/controllers/workflow_service_controller.rb
40:    Dor::Config.workflow.client.get_lifecycle('dor', params[:pid], task)
44:    Dor::Config.workflow.client.get_active_lifecycle('dor', params[:pid], task)

app/helpers/dor_object_helper.rb
92:    Dor::Config.workflow.client.get_lifecycle('dor', pid, 'accessioned')
```

**Comment by mejackreed** [comment]
@darrenleeweber and @mejackreed have paired up to consolidate the logic out of WorkflowServiceController in https://github.com/sul-dlss/argo/tree/consolidate-wfs-logic

**Comment by cbeer** [comment]
:clap:
