### ISSUE TITLE
The link to the SOLR doc offered on the detail page is broken

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#645]
It creates a link that looks like this:

https://argo.stanford.edu/select?q=id:%22druid:tm388wy6148%22&wt=json&indent=true

and you get a "The page you were looking for doesn't exist." doesn't exist. I'm at home but on VPN in case that has anything to do with it.

**Comment by drh-stanford** [comment]
The link probably should just go to the blacklight endpoint: namely `/catalog/<druid>.json`

**Comment by jmartin-sul** [comment]
also, it looks like the code is getting the hostname for the solr URL from the deprecated `Dor::Config.solrizer`, which might have something to do with it:
https://github.com/sul-dlss/argo/blob/021a90037f29bb4298fcad321d02acde120e3f05/app/helpers/argo_helper.rb#L163
