### ISSUE TITLE
Argo off campus access no longer requires vpn

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#646]
I assume this was not intentional.

**Comment by mejackreed** [comment]
ping @sul-devops-team

**Comment by jmartin-sul** [comment]
i think it's been this way for a while?  i remember going to argo.stanford.edu at some point last year, and being surprised that it worked when i noticed i wasn't actually connected to the VPN.

**Comment by atz** [comment]
If this changed, it would be in the network configuration and presumably unrelated to our code release or deployment.  This restriction is not implemented or configured in Argo, so Github is likely not the optimal venue for this ticket.

**Comment by mejackreed** [comment]
sar ticket for this?

**Comment by cbeer** [comment]
We also should consider whether requiring VPN actually provides additional security beyond that offered by WebAuth.

**Comment by LynnMcRae** [comment]
Discussed with @eefahy who will take this forward and add vpn.

**Comment by eefahy** [comment]
I discussed the issue with operations who do not see the VPN requirement as necessary, however, they strongly encourage us to auth via a workgroup. In that case, this is related to #469 & #138 & #129 ?

**Comment by jmartin-sul** [comment]
yup, i think this is related to all of those things (and 469 actually looks like a dupe of 129).

we do perms checks via workgroups at the moment, though i don't know that there's a single workgroup that everyone logs into to gate access in the first place?  but you have to be in a workgroup that argo recognizes (i.e. a workgroup listed in an APO) to be let into argo in the first place.

**Comment by LynnMcRae** [comment]
No VPN required
