### ISSUE TITLE
Hydrus items are all indexed into a "Hydrus" collection rather than into the collection they actually belong to

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#647]
I noticed the Hydrus Collection facet only had two entries 
![screen shot 2016-03-04 at 8 53 24 am](https://cloud.githubusercontent.com/assets/1824732/13533841/29611aa0-e1e7-11e5-85d0-5b1b5625be9d.png)

There should be nearly as many Hydrus collections as there are Hydrus APOs -- hundreds.

See for example https://argo.stanford.edu/catalog/druid:jv545yc8727
![screen shot 2016-03-04 at 9 00 05 am](https://cloud.githubusercontent.com/assets/1824732/13533922/86e5d508-e1e7-11e5-9fa4-166a8c495a06.png)

It claims to be in a collection called Hydrus, but if you look at RELS-EXT or follow that link to https://argo.stanford.edu/catalog/druid:hn807kb3349, you will see that the collection name is "Center for Computer Research in Music and Acoustics (CCRMA)"
![screen shot 2016-03-04 at 9 05 08 am](https://cloud.githubusercontent.com/assets/1824732/13534276/27707f04-e1e9-11e5-84f3-c440dc982168.png)

So it seems to be a problem with the name lookup for indexing.  A repot shows the right Collection ID is being indexed, but not under the correct name. 
![screen shot 2016-03-04 at 9 08 15 am](https://cloud.githubusercontent.com/assets/1824732/13534169/b656f636-e1e8-11e5-837a-1b2ffb99c1ff.png)

I don't know why 72 of them seem to be indexed properly for the "Stanford Research Data" collection.

**Comment by blalbrit** [comment]
I just saw this too - I'm hoping it's an indexing issue that will clear up? I'll try reindexing a few of those collections manually.

**Comment by blalbrit** [comment]
No change post-manual indexing.

**Comment by jmartin-sul** [comment]
strange... not what i'd expect from the code, and not the way it is in stage.  though it's also this way in the prod_b solr collection.  which would suggest a regression introduced in december or january?  will investigate...

**Comment by jmartin-sul** [comment]
currently, the value for this field is obtained from DC title for the related object (APO or collection).  in the case of the collections with this problem, the DC title is actually "Hydrus".  that problem does not seem to exist on stage, hence the discrepancy.

i ran this by lynn and ben this afternoon.  they determined that the right field to use is `mods/titleInfo/title` in `descMetadata`, which appears to have the value we want in all situations.  i'll modify dor-services to use that field.  once that's tested and appears to be working, we should:
* release a new version of dor-services
* point argo to the latest dor-services
* release a new version of argo
* deploy the latest argo to prod
* reindex all the hydrus objects

lynn and ben were confident that the DC title will not differ in this way for non-hydrus objects, and that it is unnecessary to reindex everything.
