### ISSUE TITLE
Some required columns missing from report view

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#648]
Current list includes:

Registration Date (missing from report)
Admin Policy (present online but dropped in downloaded report)

Will add to the list as I find more. Related to #627 ?

**Comment by LynnMcRae** [comment]
We eliminated the Hydrus/non-Hydrus flavors of Collection and APO from the report, offering simple Collection and APO columns -- silly to make the user chose based on population and it didn't accommodate mixed content well. Not to mention it led to either an ambiguous un-qualified "Collection" or "APO", or worse, to the horrible nomenclature of "Non-Hydrus XXXX" to distinguish the regular set of objects.

**Comment by LynnMcRae** [comment]
Registration Date corresponds to the value in the "Registered" facet, and for consistency that should also be the column name.

**Comment by drh-stanford** [comment]
Old Argo had a registration date and datetime -- which was actually showing the preservation date (see https://github.com/sul-dlss/argo/blob/2.x-stable/app/models/report.rb#L125-L130).

Should I assume that you actually want a datetime and that it's not shown by default? like so,

```
      {
        :field => 'registered_dttsim', :label => 'Registered',
        :proc => lambda { |doc| render_datetime(doc['registered_dttsim'])},
        :solr_fields => ['registered_dttsim'],
        :sort => true, :default => false, :width => 100
      },
```

**Comment by drh-stanford** [comment]
Also, I see `Admin Policy` already there in production. Can you be more specific on that?


![screen shot 2016-03-07 at 3 05 03 pm](https://cloud.githubusercontent.com/assets/1861171/13586477/fed6e5a8-e475-11e5-9ccd-1e7378276869.png)

**Comment by LynnMcRae** [comment]
For registration date, we want registered_earliest_dttsi since the lifecycle milestone may be declared by more than one workflow at different times, making registered_dttsim multi-value. e.g., 

"registered_dttsim": [
"2014-01-22T18:55:42Z",
"2014-03-03T20:24:07Z"
],
"registered_earliest_dttsi": "2014-01-22T18:55:42Z",
"registered_latest_dttsi": "2014-03-03T20:24:07Z",

The report date formatting is like this "2012-04-30 07:45PM"

**Comment by LynnMcRae** [comment]
The issue with the Admin Policy column is that it is present online but dropped from the downloaded version of the report.

**Comment by drh-stanford** [comment]
Looks like the download piece is related to https://github.com/sul-dlss/argo/issues/627
