### ISSUE TITLE
Technical Metadata requires contentMD for non-content-bearing objects

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#651]
See https://argo.stanford.edu/catalog/druid:vg409xn8030 for example.

@LynnMcRae - can you articulate this further?

**Comment by LynnMcRae** [comment]
It's a mystery. The contentMetadata step completes ok -- it's really a no=op when there is no content and no contentMetadata datastream. The technicalMetadata robot looks for files in the DOR workspace as identified by contentMetadata, but never had a problem before with the lack of that datastream. We checked that there was no phantom /content directory for this druid in the workspace that might have triggered some consistency error.

**Comment by drh-stanford** [comment]
This exception is thrown here: https://github.com/sul-dlss/dor-services/blob/master/lib/dor/models/itemizable.rb#L36

I've dug around a bit but that specific code doesn't seem to have changed in quite a while. There were code changes for how we contact the SDR but that's after the exception is thrown.

**Comment by drh-stanford** [comment]
There's not much information in the logs... 
```
INFO [2016-03-04 15:07:07] (12003)  :: druid:vg409xn8030 processing
D, [2016-03-04T15:07:08.017151 #12003] DEBUG -- : Loaded datastream list for druid:vg409xn8030 (67.2ms)
D, [2016-03-04T15:07:08.096452 #12003] DEBUG -- : Loaded datastream profile druid:vg409xn8030/RELS-EXT (77.2ms)
D, [2016-03-04T15:07:08.166174 #12003] DEBUG -- : Loaded datastream content druid:vg409xn8030/RELS-EXT (63.8ms)
D, [2016-03-04T15:07:08.237034 #12003] DEBUG -- : Loaded datastream profile druid:vg409xn8030/workflows (65.5ms)
ERROR [2016-03-04 15:07:08] (12003)  :: Missing contentMetadata datastream
```

**Comment by drh-stanford** [comment]
@LynnMcRae do you happen to know when this worked last? Did it break in our deployment last week, or earlier?

**Comment by drh-stanford** [comment]
@atz @darrenleeweber can you please take a look at this PR sul-dlss/dor-services#197. I cannot figure out why the technical-metadata robot is failing here as the code doesn't seem to have changed functionally in a very long time. The code path starts here https://github.com/sul-dlss/dor-services/blob/master/lib/dor/services/technical_metadata_service.rb#L11

**Comment by darrenleeweber** [comment]
The most recent changes are likely related to using `Sdr::Client` in
https://github.com/sul-dlss/dor-services/blob/master/lib/dor/services/technical_metadata_service.rb#L101

**Comment by drh-stanford** [comment]
That's what I thought -- that it's related to `Sdr::Client` -- but I've reviewed sul-dlss/dor-services@854924e a bunch of times and I'm not seeing any change in functionality.

**Comment by darrenleeweber** [comment]
Perhaps the techMD robot should first check for content or get smarter about handing non-content objects in this method at https://github.com/sul-dlss/dor-services/blob/master/lib/dor/services/technical_metadata_service.rb#L48-L53.  Is there a common way to detect a non-content object?

**Comment by drh-stanford** [comment]
The technical-metadata robot runs after the content-metadata robot so we can use the existence of a contentMetadata datastream as the way to detect a non-content object. We can use that information as you suggest in TechnicalMetadataService, but the vexing thing to me is how it ever worked in the first place ???

**Comment by drh-stanford** [comment]
The last working technical-metadata was with dor-services 4.22.3. Since then the SDR client migrated from directy SDR contact in 4.x to proxied via dor-services-app. I have a PR for a fix in dor-services 5.x. https://github.com/sul-dlss/dor-services/pull/197 . I haven't found evidence of why it would/would not work in the first place on 4.22.3, but the PR fixes it based on my best understanding of the code.

**Comment by LynnMcRae** [comment]
It appears we are also dying on the shelving when there is no contentMetadata datastream -- see https://argo-stage.stanford.edu/catalog/druid:fp730ff8020. While we expect DOR items to be bearing content, they are not required to do in general nor as a prerequisite to accessioning. 
![screen shot 2016-03-23 at 11 34 33 am](https://cloud.githubusercontent.com/assets/1824732/13996506/45755428-f0eb-11e5-8ecd-16fab5a7daf2.png)

**Comment by LynnMcRae** [comment]
Has the initial fix, for technical-metadata. been deployed to stage?  We need ready work available in stage to do effective testing and verification. I can make the same issue with the shelve step a separate ticket if needed.

**Comment by drh-stanford** [comment]
I'm not aware of it being deployed anywhere. The PR (https://github.com/sul-dlss/dor-services/pull/197) is still open awaiting review.

**Comment by LynnMcRae** [comment]
Sorry, I read more into the Ready label than is intended I imagine. Should I do a separate ticket for the same problem with the shelve robot?

**Comment by drh-stanford** [comment]
I'd say yes. Although the error message is the same, it likely has a different code path and reason for the failure.

**Comment by LynnMcRae** [comment]
ok, new issue #697

**Comment by ndushay** [comment]
We will soon cut a new release of dor-services gem which will include sul-dlss/dor-services/pull/197, and then we will deploy a version of argo to dev or stage with that fix to ensure that it addresses this issue.

**Comment by blalbrit** [comment]
Just verified that this is still not fixed in -stage:

<img width="1074" alt="screenshot 2016-03-30 11 49 23" src="https://cloud.githubusercontent.com/assets/796990/14153652/87298fa6-f66d-11e5-95a0-f29126f3c889.png">

**Comment by drh-stanford** [comment]
My only other thought is that it's somehow related to the `SdrClient` code -- that's the major difference between dor-services 4.22.3 and 5.x. It was contacting the SDR API directly then -- see https://github.com/sul-dlss/dor-services/blob/v4.22.3/lib/dor/models/itemizable.rb#L42

**Comment by tingulfsen** [comment]
We believe that a fix is required within dor-services, and that when the fix is made, common-accessioning will need to be updated.

**Comment by LynnMcRae** [comment]
More precisely, there is a fix already in dor-services that the robots need to be upgraded to? This may be all that is required to verify the fix works.

**Comment by ndushay** [comment]
the common-accessioning robot has been upgraded to dor-services 5.7.0 to get the fix, and has been deployed to stage.

**Comment by ndushay** [comment]
@drh-stanford deployed to prod, so closing this.
