### ISSUE TITLE
Squash eating notification emails in production

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#653]
such as https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/72:

```
An email alert about this bug was sent to jdeering@stanford.edu.
```

**Comment by drh-stanford** [comment]
@eefahy @tallenaz is this something your can configure in squash -- a default notification email? i looked around in the settings, etc. and couldn't find anything. i did notice that jdeering is the project owner.

**Comment by eefahy** [comment]
Thanks to @mejackreed I was just about to change the email notifications to the argonauts list, so hopefully this is resolved.

**Comment by drh-stanford** [comment]
we're seeing these emails on argonauts now... thanks.
