### ISSUE TITLE
Bulk Upload Failing

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#655]
First report, see attached log. I can investigate further, but could use assistance. @shelleydoljack has been trying.
[log.txt](https://github.com/sul-dlss/argo/files/161919/log.txt)

**Comment by LynnMcRae** [comment]
Shelly's input file (though her original file extension was .xml)
[SC1010newMODS.txt](https://github.com/sul-dlss/argo/files/162226/SC1010newMODS.txt)

**Comment by tingulfsen** [comment]
What was the APO under which the upload was attempted? That would be useful to know for debugging this.

**Comment by LynnMcRae** [comment]
Shelley's case is at https://argo.stanford.edu/catalog/druid:wc567ts3569/bulk_jobs_index, but we're pretty certain this is a victim of the SDR Services call that is timing out when attempting to open a new version as part of the upload, so stand by.

**Comment by jmartin-sul** [comment]
calls to SDR on argo prod should be working again.
