### ISSUE TITLE
find_desc_metadata_file throwing TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#656]
Argo is throwing a `TypeError: no implicit conversion of nil into String` in catalog_controller here:

```
def find_desc_metadata_file(job_output_directory)
    File.join(job_output_directory, bulk_job_metadata(job_output_directory)['argo.bulk_metadata.bulk_log_xml_filename'])
end
```

for more details see:
  https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/83

**Comment by LynnMcRae** [comment]
A possibility that this is me trying to get at a non-existed XML file out of a failed bulk upload job found https://argo.stanford.edu/catalog/druid:wc567ts3569/bulk_jobs_index (the sdoljack attempt at 2016-03-07 11:37am)

**Comment by andrewjbtw** [comment]
Closing this as too much time has passed to re-investigate it as is. if the underlying problem recurs, it will get captured in honeybadger and/or user reporting and a new ticket filed.
