### ISSUE TITLE
reindex is throwing undefined method downcase

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#657]
app/controllers/dor_controller.rb:27 is throwing `NoMethodError: undefined method 'downcase' for nil:NilClass` on https://argo.stanford.edu/dor/reindex/druid:xy392gj7445

The line is from dor-services here `dor-services-5.5.2/lib/dor/datastreams/identity_metadata_ds.rb:108`

```
      (prefix, rest) = tag.text.split(/:/, 2)
      prefix = prefix.downcase.strip.gsub(/\s/, '_')
```

For details see https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/80

**Comment by atz** [comment]
This should be a dor-services ticket, right?
