### ISSUE TITLE
reindex is throwing Nokogiri::XML::XPath::SyntaxError

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#658]
The exception says `Undefined namespace prefix: //dc:title` last from our code in `dor-services-5.5.2/lib/dor/datastreams/simple_dublin_core_ds.rb:27`

For example, on https://argo.stanford.edu/dor/reindex/druid:gw799cx7583

For details see https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/72

**Comment by LynnMcRae** [comment]
The very large majority of new index errors came from old ETD objects where Fedora, at the time, was producing Dublin Core metadata in the DC datastream that is no longer valid.  These have been updated and now successfully index.
