### ISSUE TITLE
More efficient indexer backlog count display/retrieval

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#66]
right now, the indexer backlog is shown in the header bar of argo, which is on most argo pages. displaying this count requires a network call to sulstats on the backend, and if this takes a long time to return, it will delay page rendering, because the request is made in the ruby code that delivers the page. 

as per joe's suggestion the other day, one way around this would be to have the count retrieved in an AJAX page element, so that it could be fulfilled without blocking the rendering of the rest of the page. a link could be provided to a page that would block until the count returned, in case someone really specifically wanted to see the count. but it doesn't seem reasonable to hold up every page request for that count. 

another idea would be to cache the count and refresh it every so often (say any time it's requested and the cached value is more than a minute old). this would make the displayed count lag a bit, but that seems acceptable, and again, a more accurate count could be obtained by means other than argo's header, if the backlog was what was really specifically desired.

**Comment by mejackreed** [comment]
I would argo that both approaches are needed:

 - split out `index_queue_depth` to its own class
 - create a separate `IndexQueueController`
 - Use ajax to make request to `IndexQueueController`
 - Cache `IndexQueueController` responses
