### ISSUE TITLE
Argo is unable to authenticate to the DOR workspace: Net::SSH:AuthenticationFailed

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#660]
This is when where it provides access to content files from the detail page ...

![screen shot 2016-03-08 at 10 59 32 am](https://cloud.githubusercontent.com/assets/1824732/13612830/60fb16f2-e51e-11e5-9a05-6177e0f37103.png)

"We want to be able to get the file in stacks currently"
"We want to be able to get the most recently preserved file"
"We want to get the currently active file in the workspace (for some high profile use cases, e.g. ETDs)"

**Comment by drh-stanford** [comment]
@sul-devops-team Argo prod needs sftp access to lyberservices-prod where it can access the /dor/workspace files. See https://github.com/sul-dlss/dor-services/blob/master/lib/dor/models/contentable.rb#L77

**Comment by atz** [comment]
Should be strictly a system configuration issue, not a code issue.

**Comment by atz** [comment]
Closing, since it is duplicated in #666

**Comment by ndushay** [comment]
linked to #666

**Comment by ndushay** [comment]
The "right" solution:
- [ ] change dor services gem to ...
- [ ] devops would like to know the actual requirements / box /network dependencies  of the dor-services gem (e.g. no longer need a direct connection to SDR) -- it needs to be able to ssh as lyberadmin hook to lyberservices-prod;  it may or may not require a mount to /dor/workspace on the box utilizing the dor-services gem.

**Comment by mejackreed** [comment]
Here are the relevant places where the links are created:

https://github.com/sul-dlss/argo/blob/master/app/views/items/_file.html.erb

And they call this action in the controller:

https://github.com/sul-dlss/argo/blob/master/app/controllers/items_controller.rb#L241-L247

**Comment by ndushay** [comment]
do sshkeys so we can do the ssh stuff.

**Comment by eefahy** [comment]
I added argo-prod-*'s public key to the `authorized_keys` file on `sul-lyberservices-prod` @LynnMcRae would you mind checking out the file functionality for this? I would also like to know if I should also add keys on `sul-lyberservices-test` & `-dev` ?

**Comment by LynnMcRae** [comment]
Good news is that we got rid of the red error message.
Bad news is we still don't have access to the workspace:
![screen shot 2016-03-17 at 9 41 13 am](https://cloud.githubusercontent.com/assets/1824732/13853596/a360c458-ec24-11e5-8375-dcfe1660a355.png)

Dev and test should get the fix for consistency once we've worked this out.

**Comment by LynnMcRae** [comment]
Ah, I think we just have a misleading message here.  It is saying the file itself is not available from the workspace because in fact it is not there. Here's a successful case:
![screen shot 2016-03-17 at 10 10 58 am](https://cloud.githubusercontent.com/assets/1824732/13854442/be612208-ec28-11e5-9fea-c036eacfac82.png)

**Comment by eefahy** [comment]
OK. Cool. I added the keys to the appropriate `authorized_keys` files so this should be good to go. @LynnMcRae may I close this issue?

**Comment by ndushay** [comment]
closing this ticket.  Assuming it works or will work in prod; we will reopen this issue (or make a new one) if this is not true.
