### ISSUE TITLE
Empty admin tag causes indexing failure

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#663]
Some of the objects that failed reindexing had an empty \<tag/> element in identityMetadata which prevented the object from being indexed.  The affected objects have been identified and are being fixed, so nothing urgent, just an indexing vulnerability.

**Comment by atz** [comment]
Probably should be ticketed on dor-services?

**Comment by LynnMcRae** [comment]
Closed, moved to https://github.com/sul-dlss/dor-services/issues/212
