### ISSUE TITLE
RSolr::Error::Http - [NUMBER] Service Unavailable Error

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#664]
This is happening in numerous places:

https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/85
https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/86
https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/87
https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/88

@sul-devops-team is the Solr cluster having availability issues?

**Comment by cbeer** [comment]
Haven't seen this lately.
