### ISSUE TITLE
Provide basic error information when an error occurs 

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#667]
The lack of basic on screen information about errors that occur has already shown to be a serious impediment to our effective support for Argo. Not all error messages are the best they could be, but the ability to recognize timeouts from class/method errors from data issues, spotting patterns and trends by familiar fingerprints is essential. I think the fact that ours is a data driven environment and a lot of data issues arise is part of why this is essential for Argo.

A good parallel is the information we get whenever a workflow step fails ... the status and essential exception information is recorded in the workflow and presented with the workflow information. We would be crippled without that information if all the WF said was "Sorry ..." :) . It's not the full stack trace that's important to us (though often the developer asked if we can send that as well) ... it just happened to follow the basic error information that we used to see and interpret.

DarrenH suggests we have basic error information on an Argo version of the "Sorry" page and offers this (from #524)

If we want to develop a customized error page, we can implement a config.exceptions_app class that generates an error page that has some information. For example, there is a gem called exception_handler that provides for dynamic error page generation.

Right now, we use the Rails 4 default that just returns static HTML for production mode. As far as I know we don't really have the ability to show that same stack trace screen that you see in development mode. In other words, this issue would be new code development, not just a configuration change.

A related problem is that we have in the code base lots of places where we return a 500 status error when it really should be a 4xx error or even a 2xx with a flash notice (i.e., we know what the error is so it's really not a 500 error -- which is a panic error).

**Comment by mejackreed** [comment]
Thanks for outlining the problem @LynnMcRae. I think we need to have a discussion with @sul-devops-team and security to determine the best way forward to handle this.

I'm interested in unpacking this further in a discussion. This problem really highlights some of the historical unknown ways that Argo is used and hopefully we can come to a better solution.

**Comment by atz** [comment]
I agree we can improve the reporting of various errors to the user.  Hopefully such reporting would be decreasingly relevant as we reduce the number of runtime exceptions.  

Please note: revealing full stack traces is not a thing production web applications should do.  This is a security consideration and a well established engineering practice.  Even if we build particularized messaging, there should be a catch-all for unrecognized exceptions that is generic, which is basically what we have now.

**Comment by ndushay** [comment]
This is more of an ethos than an actionable ticket.   Lynn likes it as a story.

**Comment by aaron-collier** [comment]
As this is a 4 yo "story" ticket, I'm going to close this and work with @andrewjbtw to open any new/actionable tickets that may still exists related to this.
