### ISSUE TITLE
Argo searches giving unexpected results (quicksearch)

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#669]
The default blacklight behavior for parsing quicksearch is OR-ing of terms I believe, and that seems to be the new Argo behavior.  We think Argo was doing default AND-ing instead and that this is the preferred behavior.  We've had a few reports of lost specificity of searching and this may be the reason. John is checking old Argo configs, so this is just to record the feedback issue for investigation.

**Comment by blalbrit** [comment]
DPG staff have started to populate an example list @mejackreed with examples of old searches and desired results: https://docs.google.com/document/d/1h0wcEZ0SHsFnIcQ3tDmtojezJ8bw7DAMYaHASKLuuL0/edit

**Comment by LynnMcRae** [comment]
We need to resolve this. I'm pretty sure we switched back to a Blacklight default inadvertently but that still needs to be confirmed.

**Comment by mejackreed** [comment]
The way I understand the issue (and I may be wrong) but this feels like an issue with indexing and there may need to be a reindex. Not under the purview of Blacklight as far as I can tell.

**Comment by jmartin-sul** [comment]
my guess (which @ndushay is helping me test at the moment) is that it's an issue with the solr configs.  this says that "The OR operator is the default conjunction operator":  https://cwiki.apache.org/confluence/display/solr/The+Standard+Query+Parser

notice that we overrode that behavior by setting `q.op` to `AND` in the old argo solr config:
https://github.com/sul-dlss/sul-solr-configs/blob/master/argo/solrconfig.xml#L734-L769

but we don't do that in the new one:
https://github.com/sul-dlss/sul-solr-configs/blob/master/argo3_prod/solrconfig.xml#L24-L77

it is also possible that we're stemming things that we were searching as whole phrases before, which would require both indexing code fixes and reindexing.  but my guess is that most of the above described issues can be solved via solrconfig.xml changes.  discussing w/ naomi and trying to figure out what the right way to fix the config is.

pinging @atz since he did a lot of this solr config stuff for argo.

**Comment by jmartin-sul** [comment]
two other things:
* as @ndushay pointed out, the search handler from old argo is using the lucene parser, but the new one is using edismax
* our default blacklight search config specifies dismax as the parser:
```
module BlacklightConfigHelper
  def self.add_common_default_solr_params_to_config!(config)
    config.default_solr_params = {
      :'q.alt' => '*:*',
      :defType => 'dismax',
...
```

**Comment by ndushay** [comment]
@ndushay  will look through google doc  and:

- [ ] compare old behavior to new
- [ ] determine if there is a quick workaround for the problem (e.g. "DIGREP-294" in quotes)
- [ ] identify the search behavior diffs where there is no known workaround.

**Comment by ndushay** [comment]
case 1:   DIGREQ-820

The query string is a jira ticket number.   In order to find it now, there is a workaround:   "JIRA : DIGREQ-820"  - quotes required, exact string required (caps, JIRA space colon space  prefix)

**Comment by ndushay** [comment]
case 2:  Beasts and Books

**Comment by ndushay** [comment]
@LynnMcRae will go back to the original prob report and see if there is more info about why Boolean was implicated originally.

**Comment by LynnMcRae** [comment]
OK, I think the boolean angle is a red herring, at least in part. There is clearly implicit ANDing at play here (in prod):

Search / result

William / 40,642
Tucker / 155
William Tucker / 28
William Hill Tucker / 527

Dennis / 594
Reid / 324
Dennis Reid / 62
Dennis W Reid / 107

map / 66,698
arkansas / 444
map arkansas / 208
map of arkansas / 32,598

beasts / 60
books / 191,661
beasts books / 35
beasts and books / 108,018

I suspect one factor at play is possible new relevancy behavior. Note the expanded result with 3 terms instead of 2 despite seeming more precise. I think there's multi-word relevancy behavior introduced at 3 or more words .... exact (3-word) matches come first, then less-relevant 2-word matches (true?).  This behavior would have had a similar effect on a tokenized 3-part tag.

I thought relevancy matching would put the 3-way match at the front of the result but that doesn't seem to be the case (try Reid W Dennis). We can add this to the overall search behavior analysis, but I don't think we have a critical issue with basic boolean behavior.

**Comment by ndushay** [comment]
@LynnMcRae   yes yes - this is all about the mm setting for dismax.

"Minimum "Should" Match: specifies a minimum number of fields that must match in a query."   From http://archive.apache.org/dist/lucene/solr/ref-guide/apache-solr-ref-guide-4.10.pdf

I analyzed actual data in SearchWorks ( http://discovery-grindstone.blogspot.com/2011/12/stopwords-in-searchworks-to-be-or-not.html ) to determine that 

Over 50% of the query strings for SearchWorks are 1 or 2 terms.
Over 75% of the query strings are 1, 2 or 3 terms.
Over 90% of the query strings for SearchWorks have 6 or fewer terms.

So our mm setting in SW is  6<-1 6<90%, which translates to:  for 1 to 6 clauses, all are required; for more than 6 clauses, 90% (rounded down) are required.

argo3 setting is currently:  2<-1 5<-2 6<90%

**Comment by ndushay** [comment]
@LynnMcRae   I have a PR in for  argo-stage and argo-dev  to change the Solr mm setting.  Once that goes into production, if it looks ok, I can make the PR to change the Solr mm setting for production argo.

**Comment by ndushay** [comment]
case 3:  Stanford Publications
  same as case 1 and 2:  the data is in a tag as  "Project : Stanford Publications"

**Comment by ndushay** [comment]
case 4:  M0997_S1_B152

The query string is a sul spec call number for:  Cabrinety box 152

this information is stored in identityMetadata as the source id (e.g., slightly diff example)
```xml
<identityMetadata>
  <sourceId source="sul">M0997_S1_B127_018</sourceId>
```
Old behavior: it would find the objects in this box only

New solr field for sourceId:  source_id_ssim  -   String field.

Why old way worked:
Solr field sourceId_t  existed and was in qf for quicksearch (which was defType dismax).  Also dor_id_t, identifier_t

Why new way doesn't work:
Solr fields:
- source_id_ssim
  -- a String so it must be an exact match, with sul: prefix thus:  ```sul: M0997_S1_B152_111```
  -- https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/identity_metadata_ds.rb#L11
- dor_id_ssim
  - exact string without attribute prefix thus:   ```M0997_S1_B152_111```
  - not in qf fields
  - https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/identity_metadata_ds.rb#L91-L96
- dor_id tesim
  - tokenized searchable!
  - without attribute prefix 
  - **in qf fields**
  - https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/identity_metadata_ds.rb#L93
- identifier_ssim
  -- a String so it must be an exact match, with sul: prefix thus:  ```sul: M0997_S1_B152_111```
  - not in qf fields
  - https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/identity_metadata_ds.rb#L94
- identifier_id tesim
  - tokenized searchable!
  - with attribute prefix
  - **in qf fields**
  - https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/identity_metadata_ds.rb#L94

**Comment by LynnMcRae** [comment]
Naomi, here are some 1,2,3,4,5 term search samples that work in both stage and prod.  As I think you indicated, the difference between 2-3 words is surprising because partial matches there have the biggest impact, very big if there's a noise word like "and" in there.   Hope these help.

STAGE

beasts / 9
burden / 65
beasts burden / 0
beasts of burden / 72
small beasts of burden  / 13
small beasts of burden named roy / 11

medieval / 96
manuscript / 1012
fragments / 92
medieval fragments / 3
medieval manuscript / 26
medieval manuscript fragments / 34

matthew / 129
mark / 171
matthew mark / 3
matthew and mark / 221
luke / 21
john / 3,257
luke john / 3
matthew mark luke / 4
matthew mark john / 68
matthew mark and john / 54
mark luke john / 29
matthew mark luke john / 1

PROD

beasts / 60 
burden / 190
beasts burden / 0
beasts of burden / 233
small beasts of burden  / 33
small beasts of burden named roy / 14

medieval / 917
manuscript / 12,650
fragments / 759
medieval fragments / 248
medieval manuscript / 233
medieval manuscript fragments / 459

matthew / 1407
mark / 4003
matthew mark / 56
matthew and mark / 3360
luke / 171
john / 23142
luke john / 91
luke and john / 16018
matthew mark luke / 67
matthew mark john / 605
matthew mark and john / 452
mark luke john / 461
matthew mark luke john / 42
matthew mark luke and john / 40

**Comment by ndushay** [comment]
case 5:  ars0021

This is a collection number for the Stanford Recital Collection;  it is in a  MODS note field in the descMetadata in the APO object.  (cj857zs2426).

It is in the collection member objects as a tag in the identity metadata:
```xml
<identityMetadata>
  <tag>Project : ARS0021 recital : dat</tag>
```

A search on "stanford recital collection"  (with quotes)  gets 813 results:   
- https://argo.stanford.edu/catalog?utf8=%E2%9C%93&q=%22stanford+recital+collection%22

Looking at one of these objects, I see a tag of  "Project : ARS0021 recital : dat"  (no quotes).   

Clicking on that tag link, we also get 813 results:
- https://argo.stanford.edu/catalog/druid:bb980rx0621?f[tag_ssim][]=Project+%3A+ARS0021+recital+%3A+dat
- tag_ssim is a string field, as case 1-3

Clicking on the project link, we also get 813 results:
- https://argo.stanford.edu/catalog?f[project_tag_ssim][]=ARS0021+recital+%3A+dat
- Solr field project_tag_ssim is a string field

**Comment by ndushay** [comment]
further info:  argo2  sends   defType=dismax  to Solr from quicksearch box;  so does argo3.   Argo2 searches different fields, tho, that have different text tokenization, etc.   It is the field "analysis" differences and which fields being searched that is responsible for most of the diffs in behavior between 2 and 3

**Comment by ndushay** [comment]
@LynnMcRae @blalbrit  closing this in favor of  #685, #686 and #687
