### ISSUE TITLE
Add new content types to item registration drop-down

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#67]
add 

   media (formerly audio and video)
   software 

to content type drop-down in argo registration. These are simply new values for the resulting Process tag that goes in identityMetadata. Alphabetize the list.

**Comment by drh-stanford** [comment]
@LynnMcRae  like this?

![screen shot 2015-12-11 at 2 23 17 pm](https://cloud.githubusercontent.com/assets/1861171/11757013/cf54822e-a012-11e5-8221-6c9d81bf565b.png)
