### ISSUE TITLE
Bulk Actions "Paste a druid list" Requires Druid Prefix - Need to make this consistent with other "Paste a druid list" which allow both prefixed and non-prefixed druids

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#676]
Situation:

User pastes in list of druids for download in Bulk Actions. Download fails without druid: prefix. Succeeds if druid: prefix included.

Desired behavior:

Exactly like every other "paste a druid list" screen in the app - allow both prefixed and non-prefixed druid lists.

**Comment by blalbrit** [comment]
Per @mejackreed , this functionality (allowing both prefixed and unprefixed lists) was not a known requirement. Changing this to "nice to have" future work.

**Comment by blalbrit** [comment]
related to #134

**Comment by peetucket** [comment]
Is this in the "Bulk Actions" area with the "Download Descriptive Metadata" action?  Or "Bulk Updates" with something else (don't see a download update action there).  

I tried in localhost and received no validation when pasting druids in the Bulk Actions box (it took even non druid numbers).
