### ISSUE TITLE
Some objects with a MODS Creator appear in Empty Field facet as lacking creator

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#677]
From Shelley via Argo feedback:

"Interestingly, all of these records have a creator in the MODS yet they appear in the “No MODS Creator” facet:

https://argo.stanford.edu/catalog?f[empties][]=no_public_dc_creator&f[nonhydrus_collection_title_ssim][]=Peninsula-Times+Tribune%2C+Stanford+University+photographs%2C+1959-1992+%28inclusive%29%2C+1970-1992+%28bulk%29&page=1

I suspect maybe it’s because the name type is “corporate” instead of “personal”. "

Here's an example from the top of that result: https://argo.stanford.edu/catalog/druid:bb001dq8600, with a clear creator designated in MODS <name>:

```
  <name type="corporate" authority="local">
    <namePart>Peninsula-Times Tribune.</namePart>
    <role>
      <roleTerm type="text" authority="marcrelator" valueURI="http://id.loc.gov/vocabulary/relators/cre">Creator</roleTerm>
    </role>
  </name>
```

Is it name type as Shelley muses? a case sensitivity?  See https://consul.stanford.edu/display/ARGO/Empty+Fields+facet which has this:

MODS creator role
- no descMetadata/mods/name with no <role> sub-element, or
- no descMetadata/mods/name/role/roleTerm with
  - type=text and value=author or creator (case insensitive) or
  - type=code and value=aut or cre
- (you may be able to just ask the MODS Gem for a creator)

**Comment by ndushay** [comment]
Work Estimate
- [ ] analysis:   2 hours
- [ ] coding fix:  undetermined
- [ ] reindexing required?   undetermined

**Comment by LynnMcRae** [comment]
It appears we are looking at the mapping of MODS to DC as a means of determining creator from contributor.  This is a mistake; the mapping rules there have considerable weaknesses -- no implicit creator, not case insensitive, breaks with terminating punctuation (Symphony source records have a period at the end of "Creator.".  We want the rules from our own MODS gem determination per the spec (MODS Display rule) that assume implicit creator when there is no role or for usage=primary, considers both Author and Creator role, etc. See https://consul.stanford.edu/display/chimera/MODS+display+rules. Here are examples I collected:

- Name(s) with no explicit role, mix or personal and corporate (implicit creator), from Symphony
     https://argo.stanford.edu/catalog/druid:bb030hd9468 - 4 personal names
     https://argo.stanford.edu/catalog/druid:zz951ky1684 - 6 personal names
     https://argo.stanford.edu/catalog/druid:hq717kb3926 - 1 corporate name
     https://argo.stanford.edu/catalog/druid:bb041rw8875 - 1 corporate name - mods: namespace prefix
     https://argo.stanford.edu/catalog/druid:bb084hb8014 - 2 corporate names
     https://argo.stanford.edu/catalog/druid:hq677cc6883 - 1 personal, 1 corporate
     
- Mix of implicit creator (no role) with explicit other roles
     https://argo.stanford.edu/catalog/druid:hq802fp1263 - personal and corporate implicit creator, 5 advisor roles
     
- extraneous character in role (terminating punctuation coded in Symphony)
     https://argo.stanford.edu/catalog/druid:hq708bb8562
        -- <roleTerm type="text">creator.</roleTerm> from MARC "100 1  a| I͡Akobson, Leonid, e| creator."
        
- Original MODS, Explicit creator, corporate, capitalized "Creator" -- <roleTerm type="text"...>Creator</roleTerm>
     https://argo.stanford.edu/catalog/druid:bb001dq8600 
     https://argo.stanford.edu/catalog/druid:bb184nr3047
     https://argo.stanford.edu/catalog/druid:bb288vq2084
     
- Multiple names with role=Author
     https://argo.stanford.edu/catalog/druid:bb060nk0241
     
- A rare one that works because of relator code "cre"
          https://argo.stanford.edu/catalog/druid:bb203fy4994

**Comment by LynnMcRae** [comment]
I think we can defer this item as an immediate MUST HAVE.  Ultimately we want the empty fields facet, and a future Collection Profile based on this data, to support digital collection QA, and there are still ragged edges around the designation of Creator.  Image collections for instance record Photographer, which is not assumed to be creator unless there's a usage=primary.  I want to vet such practice with the metadata folks to make sure they get a facet determination that supports their needs.

**Comment by blalbrit** [comment]
+1 to the priority change and analysis @LynnMcRae

**Comment by cbeer** [comment]
The current `no_public_dc_creator` field uses the MODS -> DC XSLT for calculating values.  

In dor-services 5.17.0, we also added indexing for the Stanford MODS `main_author_w_date`, and propose to use it in #883 (pending a full reindex)

**Comment by LynnMcRae** [comment]
well at least the name of the field -- no_public_dc_creator -- is accurate, but useless.  Is that field currently the basis for the No MODS Creator value in the Empty Fields facet? As the facet values imply,  Empty Fields values relating to descMetadata were supposed to be based on MODS, not DC -- their purpose was to reveal MODS issues and be the complement to a positive indexed value/facet also from MODS. See https://consul.stanford.edu/display/ARGO/Empty+Fields+facet for their specification.

I think the entirety of any solr field with "dc" in the name is perhaps now an unwanted anachronism. Can we look into eliminating those fields if we haven't already done so with the indexing improvements? We will need a properly named complement to no_public_dc_creator based in essence on the absence of main_author_w_date?

**Comment by cbeer** [comment]
Yes, that's the intent with #883.
