### ISSUE TITLE
Create an argo indexing diagram for documentation purposes

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#678]

**Comment by jmartin-sul** [comment]
did it on a whiteboard just now, took a picture.  any opinion on where this should live and what it should be named?  can't attach files to github issues, though it should prob go in the argo codebase anyway.

**Comment by mejackreed** [comment]
In the wiki?

**Comment by blalbrit** [comment]
+1 @mejackreed

**Comment by jmartin-sul** [comment]
![dor_indexing_diagram](https://cloud.githubusercontent.com/assets/7741604/14167432/29601274-f6d0-11e5-9bae-f3481960842a.jpg)

**Comment by jmartin-sul** [comment]
"can't attach files to github issues" was not my most observant moment.

**Comment by jmartin-sul** [comment]
wiki entry:  https://github.com/sul-dlss/argo/wiki/Fedora-to-Solr-Indexing-Diagram

feel free to reopen if this needs more fleshing out.  the image isn't super-easy to read, but if you right-click and select "View Image", you get a larger version.
