### ISSUE TITLE
Investigate whether Argo needs a direct mount of the dor/workspace

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#679]
Related to #666

**Comment by mejackreed** [comment]
ping @eefahy

**Comment by LynnMcRae** [comment]
I adjusted the title for clarity, to what I hope this ticket is about!

**Comment by jmartin-sul** [comment]
while argo doesn't use the setting for the mount location directly, it does appear that dor-services uses that setting.  argo uses `Settings.CONTENT.BASE_DIR` set `content.content_base_dir` in the `dor_ENV.rb` config files.  dor services uses that setting in a few places in `Dor::Contentable`, e.g.:
https://github.com/sul-dlss/dor-services/blob/v5.6.0/lib/dor/models/contentable.rb#L74

it is possible that not all of the dor-services methods in contentable that use that setting actually also get used by argo.  but it seems like at least that particular dor-services method (`get_file`) is used by argo.

**Comment by mejackreed** [comment]
@cbeer did y'all look at this during your past sprint?

**Comment by cbeer** [comment]
Only briefly. It certainly appears that it uses sftp to access content remotely.

**Comment by blalbrit** [comment]
The main place I would think to check would be in the file retrieval parts of the item content view. If content were available in the workspace (and it usually is not), it would be linkable like the preservation and stacks copies are:

<img width="918" alt="screenshot 2016-11-29 07 37 15" src="https://cloud.githubusercontent.com/assets/796990/20716355/c66be0c0-b606-11e6-8c12-b39e3dffd800.png">

**Comment by blalbrit** [comment]
Not sure there is any remaining action in this ticket. Please reopen if I've misread it.
