### ISSUE TITLE
Add "media" to bulk update and blue button item update for content type changes

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#68]
These are presented in a drop-down menu currently. Accompanying resource types in an associated drop-down are "audio" and "video"

**Comment by blalbrit** [comment]
@mejackreed We think this is done, will verify in stage and close if complete.

**Comment by LynnMcRae** [comment]
Nothing new showing for bulk update: 
![screen shot 2016-02-03 at 10 47 50 am](https://cloud.githubusercontent.com/assets/1824732/12793101/b3951b9a-ca63-11e5-9279-8977d42f9de1.png)

Nor for blue button on one item:
![screen shot 2016-02-03 at 10 49 13 am](https://cloud.githubusercontent.com/assets/1824732/12793130/dce507ee-ca63-11e5-9382-47bcb9c7166f.png)
