### ISSUE TITLE
use whenever to setup Argo's .htaccess generation cron job

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#683]
New Argo was deployed without this, perhaps never had it.  John and Erin have a plan.

**Comment by jmartin-sul** [comment]
the plan is to use the whenever gem to set up the cron job on deployment:
https://github.com/javan/whenever

**Comment by ndushay** [comment]
wait - this is a new ticket added to must-haves.  No fair!

**Comment by jmartin-sul** [comment]
the command to be executed is `rake argo:htaccess`

**Comment by jkeck** [comment]
Closed by #703
