### ISSUE TITLE
adjust mm Solr setting to improve argo search results

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#685]
from Lynn, in #669:
"We've had a few reports of lost specificity of searching ..."

It turns out both argo2 and argo3  send  defType=dismax  as an argument to Solr, so neither is really using boolean.   I have confirmed this from Solr log entries.   John also confirmed:  "our default blacklight search config specifies dismax as the parser:
```ruby 
module BlacklightConfigHelper
  def self.add_common_default_solr_params_to_config!(config)
    config.default_solr_params = {
      :'q.alt' => '*:*',
      :defType => 'dismax',
```
 
Argo2 searches different fields, tho, that have different text tokenization, etc. It is the field "analysis" differences and which fields being searched that is responsible for most of the diffs in behavior between 2 and 3.

I think the main thing is to tweak the mm setting in Solr.  See Lynn's remarks in separate comment below as a confirmation.

mm, or Minimum "Should" Match: specifies a minimum number of fields that must match in a query." From http://archive.apache.org/dist/lucene/solr/ref-guide/apache-solr-ref-guide-4.10.pdf

I analyzed actual data in SearchWorks ( http://discovery-grindstone.blogspot.com/2011/12/stopwords-in-searchworks-to-be-or-not.html ) to determine that

Over 50% of the query strings for SearchWorks are 1 or 2 terms.
Over 75% of the query strings for SearchWorks are 1, 2 or 3 terms.
Over 90% of the query strings for SearchWorks have 6 or fewer terms.

So our mm setting in SW is 6<-1 6<90%, which translates to: for 1 to 6 terms/clauses, all are required; for more than 6 clauses, 90% (rounded down) are required.

argo3 setting is currently: 2<-1 5<-2 6<90%

This implies that argo3 is currently only requiring all terms for 1-2 term queries, all but one term for 3-5 term queries, and 90% of the terms for 6 or more term queries.

grew out of #669

**Comment by ndushay** [comment]
I have a PR in for argo-stage and argo-dev to change the Solr mm setting to be the same as what we use in SearchWorks. Once that is deployed, if it looks ok on argo-stage and/or argo-dev, I can make the PR to change the Solr mm setting for production argo. See sul-dlss/sul-solr-configs#51

**Comment by ndushay** [comment]
from Lynn:

Here are some 1,2,3,4,5 term search samples that work in both stage and prod.  As I think you indicated, the difference between 2-3 words is surprising because partial matches there have the biggest impact, very big if there's a noise word like "and" in there.   Hope these help.

STAGE

beasts / 9
burden / 65
beasts burden / 0
beasts of burden / 72
small beasts of burden  / 13
small beasts of burden named roy / 11

medieval / 96
manuscript / 1012
fragments / 92
medieval fragments / 3
medieval manuscript / 26
medieval manuscript fragments / 34

matthew / 129
mark / 171
matthew mark / 3
matthew and mark / 221
luke / 21
john / 3,257
luke john / 3
matthew mark luke / 4
matthew mark john / 68
matthew mark and john / 54
mark luke john / 29
matthew mark luke john / 1

PROD

beasts / 60 
burden / 190
beasts burden / 0
beasts of burden / 233
small beasts of burden  / 33
small beasts of burden named roy / 14

medieval / 917
manuscript / 12,650
fragments / 759
medieval fragments / 248
medieval manuscript / 233
medieval manuscript fragments / 459

matthew / 1407
mark / 4003
matthew mark / 56
matthew and mark / 3360
luke / 171
john / 23142
luke john / 91
luke and john / 16018
matthew mark luke / 67
matthew mark john / 605
matthew mark and john / 452
mark luke john / 461
matthew mark luke john / 42
matthew mark luke and john / 40

**Comment by ndushay** [comment]
slightly related to #535

**Comment by ndushay** [comment]
changes deployed to argo-dev and argo-stage indexes.   If @LynnMcRae and/or @blalbrit like them, I will make the same changes to argo production.

**Comment by LynnMcRae** [comment]
Ben and I verified the behavior is good and provides meaningful precision when searching for titles. That it matches the time-tested SW settig is also reassuring.

**Comment by ndushay** [comment]
I just created the PR for sul-solr-configs.   When devops deploys that PR and reloads the argo3_prod  index, then this change will be in production.
