### ISSUE TITLE
source id searches require exact match

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#687]
1 reported desired search functionality issue for the argo 3 rollout (see #669) was about source_id searching.

From Ben:
"DPG staff have started to populate an example list with examples of old searches and desired results: https://docs.google.com/document/d/1h0wcEZ0SHsFnIcQ3tDmtojezJ8bw7DAMYaHASKLuuL0/edit "
##### M0997_S1_B152

The query string is a sul spec call number for:  Cabrinety box 152

this information is stored in identityMetadata as the source id (e.g., slightly diff example)

``` xml
<identityMetadata>
  <sourceId source="sul">M0997_S1_B152_001</sourceId>
  <objectId>druid:tx838qh5865</objectId>
  ...
  <tag>Project : Cabrinety</tag>
```

Old (or maybe just desired) behavior: it would find the objects in this box only

New solr field for sourceId:  source_id_ssim  -   String field.

Why old way may have worked:
Solr field sourceId_t  existed and was in qf for quicksearch (which was defType dismax).  Also dor_id_t, identifier_t.   _t fields used a tokenization that split on the underscore.  
- See https://sul-solr-c.stanford.edu/solr/#/argo_test/analysis?analysis.fieldvalue=M0997_S1_B152_001&analysis.fieldtype=text&verbose_output=0 

Why new way doesn't work:
Solr fields:
- **source_id_ssim**
  - a String so it must be an exact match, with sul: prefix thus:  `sul: M0997_S1_B152_001`
  - https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/identity_metadata_ds.rb#L11
- **dor_id_ssim**
  - exact string without attribute prefix thus:   `M0997_S1_B152_001`
  - not in qf fields so not searched by quicksearch
  - https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/identity_metadata_ds.rb#L91-L96
- **dor_id_tesim**
  - tokenized searchable, but due to how field is analyzed  M0997_S1_B152_001 becomes the single token `m0997_s1_b152_991`  
    - https://sul-solr-c.stanford.edu/solr/#/argo3_prod_shard1_replica1/analysis?analysis.fieldvalue=M0997_S1_B152_001&analysis.fieldtype=text_en&verbose_output=0
  - without attribute prefix 
  - in qf fields, so searched by quicksearch - but lowercase only and must have item number suffix
  - https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/identity_metadata_ds.rb#L93
- **identifier_ssim**
  -- a String so it must be an exact match, with sul: prefix thus:  `sul: M0997_S1_B152_111`
  - not in qf fields (NOT searched by quicksearch)
  - https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/identity_metadata_ds.rb#L94
- **identifier_id_tesim**
  - tokenized searchable, but due to how field is analyzed  sul: M0997_S1_B152_001 becomes the two tokens `sul` and  `m0997_s1_b152_001`  
    - https://sul-solr-c.stanford.edu/solr/#/argo3_prod_shard1_replica1/analysis?analysis.fieldvalue=sul%3A%20M0997_S1_B152_001&analysis.fieldtype=text_en&verbose_output=0
  - with attribute prefix
  - in qf fields
  - https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/identity_metadata_ds.rb#L94

So both the String fields and the tokenized fields don't break up the M0997_S1_B152_001 into multiple tokens in them, seemingly requiring an exact match.

sending Solr `q=dor_id_tesim:m0997_s1_b152*`  (note wildcard) returns 37 results.  Typing the wildcard into the quicksearch box does NOT work.  

These quicksearches do not work:
- M0997_S1_B152
- m0997_s1_b152
- M0997_S1_B152*
- m0997_s1_b152*
- M0997 S1 B152 (no quotes)
- m0997 s1 b152  (no quotes)
- "M0997 S1 B152"
- "m0997 s1 b152"

**Comment by ndushay** [comment]
these are the fields searched for quicksearch, sent to Solr via qf param, configured somewhere in argo:

  "qf"=>"text^3
    creator_tesim
    dc_creator_tesim
    dc_identifier_druid_tesim
    dc_title_tesim
    dor_id_tesim
    extent_ssim
    identifier_tesim
    lifecycle_ssim
    obj_label_tesim
    obj_state_tesim
    originInfo_place_placeTerm_tesim
    originInfo_publisher_tesim
    public_dc_contributor_tesim
    public_dc_coverage_tesim
    public_dc_creator_tesim
    public_dc_date_tesim
    public_dc_description_tesim
    public_dc_format_tesim
    public_dc_identifier_tesim
    public_dc_language_tesim
    public_dc_publisher_tesim
    public_dc_relation_tesim
    public_dc_rights_tesim
    public_dc_subject_tesim
    public_dc_title_tesim
    public_dc_type_tesim
    scale_ssim
    source_id_ssim
    tag_ssim
    title_tesim
    topic_tesim",

**Comment by ndushay** [comment]
It is my understanding that source_id was never promised as a searchable thingy, so this is an enhancement request.  Perhaps this id should be an identifier in the mods?

**Comment by LynnMcRae** [comment]
DOR Registration has to do an exact match query on Source ID to guard against registering the same object twice.  So a source ID search must have been there before  and needed going forward .There's a good chance we don't have a test for that behavior to make sure it is doing its job.

**Comment by ndushay** [comment]
So what actions should be taken based on this ticket, and what are their priorities (and should they be in this or separate tickets?)

Note that Solr is perfectly happy to index something as a string and again as a tokenized field - searchworks does that all the time ... but purposefully, not hither-thither.

**Comment by ndushay** [comment]
Note that Solr is perfectly happy to index something as a string and again as a tokenized field - searchworks does that all the time ... but purposefully, not hither-thither.

**Comment by andrewjbtw** [comment]
From the linked document, it sounds like the desired functionality here is to be able to search on a partially formed source id. More specifically, the example searches seem to be for

[start of source id, stopping short of the full string]

rather than for 

[any string within source id, not necessarily starting with the first characters in the source id]

**Comment by ndushay** [comment]
does "first characters" always mean the start of the string (and not a part after a colon)?

**Comment by andrewjbtw** [comment]
Starting from after the colon.

**Comment by ndushay** [comment]
closing this in favor of #4194
