### ISSUE TITLE
Register/edit APO - error when no license selected

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#69]
The UI represents no choice/none as "Citation only" which doesn't make sense / has no definition. Choosing it leads to a system error -- "is not a valid license code". Make the first choice something like "-- none --" and have the code skip adding license information rather than getting an error.

**Comment by drh-stanford** [comment]
Here's what the error looks like:

![screen shot 2015-11-03 at 3 18 46 pm](https://cloud.githubusercontent.com/assets/1861171/10924794/3889c7ba-823e-11e5-86b8-6410eb6133fe.png)
