### ISSUE TITLE
defaultObjectRights datastream encoding should be utf-8

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#691]
This can lead to a number of errors if the contents contain utf-encoded characters -- errors in apply APO defaults, DS editing, indexing

@caaster:
> I just tried to run a bulk versioning job in Argo on 998 Rumsey objects (with 7K more to go!!). I prepared 998 objects for bulk versioning, opened all of the objects successfully, then selected “Apply APO defaults”. Every single object returned the following error

the error @caaster saw in the UI was just the generic error that's seen on individual bulk operation failures.  more info was captured in squash:
https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/101

it's an `ArgumentError`, specifically `invalid byte sequence in UTF-8`.

example request that should reproduce it:  GET https://argo.stanford.edu/items/druid:qm823bk3782/apply_apo_defaults?bulk=true

the part of the stack trace involving DLSS code:
```
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/active-fedora-6.7.3/lib/active_fedora/om_datastream.rb:113
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/dor-services-5.6.0/lib/dor/datastreams/rights_metadata_ds.rb:57
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/dor-services-5.6.0/lib/dor/models/governable.rb:63
app/controllers/items_controller.rb:635
```

though the line where the error ultimately occurs is way down in equivalent-xml (`equivalent-xml-0.6.0/lib/equivalent-xml.rb:85`).

**Comment by jmartin-sul** [comment]
@blalbrit and @LynnMcRae:  cathy says this "strikes [her] as a blocker overall"

it dies making these calls:
https://github.com/sul-dlss/argo/blob/v3.0.2/app/controllers/items_controller.rb#L633-L637
https://github.com/sul-dlss/dor-services/blob/v5.6.0/lib/dor/models/governable.rb#L62-L64
https://github.com/sul-dlss/dor-services/blob/v5.6.0/lib/dor/datastreams/rights_metadata_ds.rb#L54-L58

the middle of those calls is:
`rightsMetadata.content = admin_policy_object.datastreams['defaultObjectRights'].content`

and the error message is:
"ArgumentError:  invalid byte sequence in UTF-8"

the example object above is druid:qm823bk3782, which has an APO of druid:sq161jk2248 ("David Rumsey Map Collection").  does the `defaultObjectRights` datastream look ok for druid:sq161jk2248?

**Comment by LynnMcRae** [comment]
Making it a post-release must-have for now mainly to identify it as in the "it broke with this release" category.

**Comment by blalbrit** [comment]
@jmartin-sul The defaultObjectRights md stream looks okay to me. There are two <use> stanzas where I would expect one, but that doesn't seem to have any impact on the issue. I have also tested "Apply APO defaults" on other APOs and am getting the same error.

**Comment by blalbrit** [comment]
The (presumed) underlying dor-services call throws no error when run from console: https://github.com/sul-dlss/dor-services/blob/590242e00e3f0e85dd4adeb81f5abadd629e3451/lib/dor/models/governable.rb#L62

**Comment by blalbrit** [comment]
and actually, @jmartin-sul and @LynnMcRae I take that back. The swap that underlies the method (https://github.com/sul-dlss/dor-services/blob/590242e00e3f0e85dd4adeb81f5abadd629e3451/lib/dor/models/governable.rb#L63) works just fine BUT calling the method named at line 62 introduces an encoding error: `=> "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n\n<rightsMetadata>` which then causes the failure: `Loaded datastream content druid:bb034jd1828/rightsMetadata (85.5ms)
output error : string is not in UTF-8`

**Comment by LynnMcRae** [comment]
Maybe just a coincidence, but I can't edit the defaultObjectsRights datastream for this object, but I can for other APOs.  Perhaps that error will tell us something here? See #692

**Comment by LynnMcRae** [comment]
Per Ben above, we seem to have switched away from utf-8 encoding.  You can see the change here as well:
![screen shot 2016-03-21 at 10 28 48 am](https://cloud.githubusercontent.com/assets/1824732/13927669/db933634-ef4f-11e5-838c-7f3c20445445.png)

**Comment by atz** [comment]
8859-1 is LATIN1.  Not sure anything relevant changed.  I suspect the APO just has the old encoding already in it.

**Comment by blalbrit** [comment]
@atz I would agree - but we're seeing this across multiple APOs. Any other possibilities you can think of?

**Comment by atz** [comment]
https://argo.stanford.edu/catalog/druid:hv992ry2431

If you look at the Uber APO's defaultObjectRights, it has the LATIN1 encoding.  So that seems like where it would come from.

**Comment by blalbrit** [comment]
yep - makes sense. Any idea why *now* this is causing update failures where it has not for the last several years?

**Comment by LynnMcRae** [comment]
@atz do you know how Fedora determines/stores the encoding of a datastream?  It's not in the FoXML that I can see, beyond the FoXML itself being explicit utf-8.   Why do these defaultObjectRights datastreams (only 2 so far that I know of) show up in edit/re-apply as ISO-8066-1 while other datastreams seem happy to go implicit utf-8 (as far as we can tell)?

**Comment by LynnMcRae** [comment]
The defaultObjectRights of the uber APO is the source of rightsMetadata for APOs, and they look fine.  The defaultObjectRights datastream is established/edited by our APO Registration form.  Could it be in there somewhere? Itemlevel rightsMetadata created from these defaults are ok, I imagine because it's just a copy of the XML itself into a fresh datastream, nothing clone-like.

**Comment by atz** [comment]
@blalbrit I don't know.  My *guess* is we started enforcing UTF8 on write.  Possibly somewhere that used to serialize and deserialize the datastream was replaced with direct content assignment.

In dor-services via `git blame spec/datastreams/default_object_rights_ds_spec.rb` I find:
```
23f0a399 (Darren Hardy  2015-11-20 17:49:42 -0800  78)   it 'is human-readable XML' do
23f0a399 (Darren Hardy  2015-11-20 17:49:42 -0800  79)     subject.normalize!
23f0a399 (Darren Hardy  2015-11-20 17:49:42 -0800  80)     expect(subject.content).to eq('<?xml version="1.0" encoding="ISO-8859-1"?>
```

Which is to say, as of November, we added a test that seems to explicitly expect LATIN1.  In that commit https://github.com/sul-dlss/dor-services/commit/23f0a399#diff-78e7c6904e6aca2b3a1c9fb3170c847cR97 , we added a `content` method that seems to overwrite the underlying content method that presumably is otherwise inherited from OmDatastream.  That seems problematic.  The intent seems to be to make the *persisted* version of the content pretty.

**Comment by LynnMcRae** [comment]
Yes, there's XML normalization going on for consistent repository objects, elimination of artifacts like empty tags as well as final formatting. I assume there's a mix of ways XML gets into Fedora that explains why this seems to be a limited problem.  Can we just make it assume/force utf-8 as a fix?

**Comment by atz** [comment]
The point is that we overwrote an internally important method with one intended for convenient external consumption.  I would remove that and force the external consumers to a marginally less convenient call.

**Comment by LynnMcRae** [comment]
I assume you mean normalize XML farther upstream so to speak, not while persisting it? We've normalized MODS for some time now without known ill effect, but I'll find some recent objects and verify.

**Comment by LynnMcRae** [comment]
Here is an APO in stage with a utf-8 encoded character in defaultObjectRights but put away as iso-8859-1:
https://argo-stage.stanford.edu/catalog/druid:bj961cc4982

**Comment by LynnMcRae** [comment]
We'd like to understand how and where in Fedora the datastream encoding is determined here.  There's nothing in FoXML or in any admin view that suggests we have control over this apart from the global utf-8 encoding that applies to the FoXML.

**Comment by LynnMcRae** [comment]
Example in prod -- https://argo.stanford.edu/catalog/druid:sb559ym0369

**Comment by atz** [comment]
This is the [datastream](https://sul-dor-test.stanford.edu/fedora/objects/druid:bj961cc4982/datastreams/defaultObjectRights/content).  Note that charset is not specified.  The DS is retrieved via HTTP like:
```
GET https://sul-dor-test.stanford.edu/fedora/objects/druid:bj961cc4982/datastreams/defaultObjectRights/content
```
Response Headers include:
```
Content-Type:text/xml
```

According to https://www.ietf.org/rfc/rfc3023.txt, **Text/xml with Omitted Charset** (our case):
```
   This example shows text/xml with the charset parameter omitted.  In
   this case, MIME and XML processors MUST assume the charset is "us-
   ascii", the default charset value for text media types specified in
   [RFC2046].  The default of "us-ascii" holds even if the text/xml
   entity is transported using HTTP.

   Omitting the charset parameter is NOT RECOMMENDED for text/xml.  For
   example, even if the contents of the XML MIME entity are UTF-16 or
   UTF-8, or the XML MIME entity has an explicit encoding declaration,
   XML and MIME processors MUST assume the charset is "us-ascii".
```

So if you want UTF-8, the XML must declare it so.  It violates spec to "assume" it.  What we have now, upon retrieval we properly assume it is US-ASCII (as we MUST), but the data contains a (non-ASCII) copyright character, so the encoding is busted.  The only spec-compliant solution is to fix the data.

**Comment by LynnMcRae** [comment]
I understand that encoding is missing. If Fedora included the XML header as "content", we should see 

   \<?xml version="1.0" encoding="utf-8"?>

And what might be (or rather I assume is) missing from a PUT is 

   Content-type: text/xml; charset="utf-8"

Are we doing this correctly for other datastreams, like descMetadata where there's lots of encoded foreign characters? What I am puzzled by is I find no place in the FoXML where it seems to store or accommodate knowledge of the charset at the datastream level.  The FoXML itself is declared UTF-8

view-source:https://sul-dor-test.stanford.edu/fedora/objects/druid:bj961cc4982/objectXML

but there are no embedded \<?xml> headers inside any Fedora object.  So how do these examples -- same content in test and prod, get away with their unicode encoded characters.

https://sul-dor-test.stanford.edu/fedora/objects/druid:bf371nq9572/datastreams/descMetadata/content
https://sul-dor-prod.stanford.edu/fedora/objects/druid:bb016nw8128/datastreams/descMetadata/content

How does Fedora understand them, and not have a problem with us putting them in and correctly getting them out, with nothing I see to differentiate them from the defaultObjectRights example? Or are we getting away with some input/output illusion that preserves the values somehow?  I sort of assumes the datastream inherited the overall FoXML encoding, 'cause the data had to live as one big happy XMl document internally.  Or is there a difference between CONTROL_GROUP X and M? Should we be seeing 'MIMETYPE="text/xml; charset=utf-8"' everywhere?

I'm probably missing something obvious but I have to admit I am puzzled.

**Comment by tingulfsen** [comment]
The solution to this issue has two parts:

- We need to fix the defaultObjectRights datastream for the affected APOs by forcing their encoding to be UTF-8 and replacing the offending characters (such as \xAD) by their corresponding codepoints.
- We need to fix dor-services such that it correctly sets the XML encoding. See pull request sul-dlss/dor-services#209

**Comment by LynnMcRae** [comment]
@atz Joe, to clarify my question.  I am trying to figure out the essential differences between your defaultObjectRights example:

GET https://sul-dor-test.stanford.edu/fedora/objects/druid:bj961cc4982/datastreams/defaultObjectRights/content 

and this example:

GET https://sul-dor-test.stanford.edu/fedora/objects/druid:bf371nq9572/datastreams/descMetadata/content

...which is also text/xml, with no charset, but with unicode encoded characters that go in and out of Fedora quite happily.  Is the issue not inside Fedora itself, which perhaps sees a string like "&#x302;" as just a series of ASCII characters in this case (tho the & would have to be XML encoded as &amp;, yes?)? Is it that we've introduced assertions and triggered checks in our code that puts defaultObjectRights in and takes it out, and that's where we're in trouble?

Something causes Argo to show the encoding when editing defaultObjectRights:
![screen shot 2016-03-25 at 6 04 04 pm](https://cloud.githubusercontent.com/assets/1824732/14057122/1c1c6006-f2b4-11e5-98d9-fa56f33e4964.png)

but show no XML header for any other datastream.  I was trying to figure out how Fedora "knew" it was ISO-8859-1 since there isn't a hint of it in the FoXML, but now I think it's Argo that's making that assertion both on output since the GET shows no encoding.

I don't think my understanding of this is critical to making this one datastream work again in the short term, so we can chat more next week.  But I think you are on to some more global issues on how we are handling UTF-8 encoded data in general.

**Comment by ndushay** [comment]
The default object rights datastream is the ONLY datastream that was using the nokogiri-pretty gem, so it would be the only datastream that was getting the wrong charset explicitly put into the datastream XML.  We believe that #209 fixes the problem with the code, and will be in place when argo is deployed with a new release of dor-services gem (post v 5.6.0).   

As for the rights datastreams that now have an incorrect encoding ... those will need to be fixed, but this humble commenter is not sure how to identify them or how to fix them.

**Comment by tingulfsen** [comment]
I've reached out to @blalbrit who will work on fixing the existing broken datastreams.

**Comment by ndushay** [comment]
We will soon cut a new release of dor-services gem which will include sul-dlss/dor-services#197, and then we will deploy a version of argo to dev or stage with that fix to see if it addresses this issue.

**Comment by ndushay** [comment]
@blalbrit @LynnMcRae  this still needs verification before closing, even though we are deploying the fix to production shortly.

**Comment by LynnMcRae** [comment]
This is in production and has also been verified there.
