### ISSUE TITLE
Spreadsheet/MODS upload in stage fails to update objects, no errors logged

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#693]
See https://argo-stage.stanford.edu/catalog/druid:ws024gz0298/bulk_jobs_index

The first (earlier) attempt labeled "Testing" was a spreadsheet convert&load.  The conversion was fine (see XML) but no objects got loaded.  No errors indicated in the log.

The second run used the output from the first to do just a MODS load.  Same result ... zero successes, no indication of error in the log.

**Comment by tingulfsen** [comment]
@LynnMcRae would you be able to share the spreadsheet with me? Even via email? That would be really helpful to debug this.

**Comment by LynnMcRae** [comment]
@tingulfsen Isn't the spreadsheet saved with the job?  Here it is regardless...
[xls-argo-stage.xlsx](https://github.com/sul-dlss/argo/files/183222/xls-argo-stage.xlsx)

**Comment by LynnMcRae** [comment]
Verified in stage. Of 5 test objects, two were registered and saved, one properly skipped because item was in accessioning, and 2 failed because of #696, a separate issue. Report and log show the expected information.

One anomaly.  The newly submitted job does not automatically show up in the history on the page (no underlying page refresh), which is ok.  But when I refreshed the page, I got a "Sorry, something went wrong".  I simply send the page request again and it worked fine. I have reproduced this twice.  I don't know if there's a window when constructing the page might be vulnerable, of something with reload per se. This alone would not make it to the critical list so I will make it a separate ticket unless there's a ready explanation or fix.

**Comment by LynnMcRae** [comment]
Link to squash for page reload error - https://sul-squash.stanford.edu/projects/argo/environments/staging/bugs/31

**Comment by tingulfsen** [comment]
Thanks, the squash page looks useful.

**Comment by tingulfsen** [comment]
@LynnMcRae could you start a separate ticket for the squash error you just posted? I have so many different threads going on and I would like to keep them separate if possible. I think the fix is probably easy though.

**Comment by LynnMcRae** [comment]
you bet, since the screen refresh issue is not a showstopper

**Comment by ndushay** [comment]
@tingulfsen will prepare a PR to merge the code fix from the appropriate branch to master.  Since the fix is already verified, once it is in master, it can be deployed to argo prod.
