### ISSUE TITLE
Shelve robot fails for objects with no content - solved with #651 ?

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#697]
(We hope this will be solved by DH's PR  sul-dlss/dor-services#197  for  #651 where the technical-metadata robot has the same issue)

Objects with no content, and therefore no content metadata, are getting an error in the shelve step of accessioning.  No contentMetadata = no content = no files to shelve, but there may be a diffs evaluation step involved in case this is a later version of the object with content that should be removed from the digital stacks.

![45755428-f0eb-11e5-8ecd-16fab5a7daf2](https://cloud.githubusercontent.com/assets/1824732/14003089/73cf9992-f10d-11e5-9c14-b5cb861101f2.png)

**Comment by ndushay** [comment]
We will soon cut a new release of dor-services gem which will include sul-dlss/dor-services/pull/197, and then we will deploy a version of argo to dev or stage with that fix to see if it addresses this issue.

**Comment by LynnMcRae** [comment]
The robot step for object druid:fp730ff8020 still fails in stage with "Missing contentMetadata datastream" error

**Comment by ndushay** [comment]
the common-accessioning robot has been upgraded to dor-services 5.7.0 to get the fix, and has been deployed to stage.

**Comment by ndushay** [comment]
@drh-stanford deployed to prod, so closing this.
