### ISSUE TITLE
Conflicting statuses being reported in index

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#698]
On a daily basis, we're seeing misleading statuses on some objects due to the Argo indexes being out of sync (for example: accessioned objects re-appearing as "in accessioning", remediated objects appearing as "error", etc.).

Specific example:

Object: druid:fj900yy4220
Processing status facet = "In accessioning"
Object status = "V1 accessioned"

![screenshot 2016-03-24 09 39 15](https://cloud.githubusercontent.com/assets/796990/14023978/4fda1494-f1a4-11e5-9334-a1967ed9dd4f.png)

This appears to be happening because of conflicting solr information:

see below:

**Comment by cbeer** [comment]
What is still consuming the old argo indexes? I thought we had accounted for all the known services.

**Comment by blalbrit** [comment]
@cbeer - @LynnMcRae suggests that I'm looking at the wrong two cores. Can you tell me which cores I *should* be looking at?

**Comment by blalbrit** [comment]
nm - I see it across solr-a and solr-b. assume we're looking at the argo-b core as "prod" data.

**Comment by LynnMcRae** [comment]
These are for stable objects that are not being processed. They properly show Accessioned one day, then random handfuls show up as In accessioning or Unknown Status the next (and for several days in a row), leading to the suspicion it was an out of sync index issue showing up across load-balanced sessions. But it seems to be a deeper issue if the two prod solr cores agree and differ from the display.

**Comment by blalbrit** [comment]
Thanks to @ndushay , it looks like solr-c,-d,and-e are the solrs, and I've got the right core now. The issue seems to come from:

![screenshot 2016-03-24 09 54 57](https://cloud.githubusercontent.com/assets/796990/14024489/9420824e-f1a6-11e5-901c-1660f11d2212.png)

**Comment by blalbrit** [comment]
recharacterizing ticket title

**Comment by blalbrit** [comment]
reindexing objects will clear the discrepancy - but the problem keeps recurring on different objects within the collection

**Comment by blalbrit** [comment]
This seems to be triggered by adding tags to the identityMD - causing an update and legitimate reindexing that mistakenly flips status to "in accessioning" for one of the fields.

**Comment by ndushay** [comment]
for the record, the production index is called argo3.    argo_b   should be removed - it's dead.   I have already made some issues for dealing with sul-solr argo index confusion and old argo boxes:

#680 - remove argo_b Solr index  <-- could be done now ...
#681 - decommission argo-test   (and its index)
#682 - decommision argo (and its index) 

but before doing those, it would be nice if sul-solr-config changes sul-dlss/sul-solr-configs#51 and sul-dlss/sul-solr-configs#52  could be deployed so we could move on to testing and possibly deploying them to production.

**Comment by ndushay** [comment]
2406 objects in this state:

Solr query to see these objects with particular conflicting statii:

ids only, first 10:
- https://sul-solr-c.stanford.edu/solr/argo3_prod_shard1_replica1/select?fq=processing_status_text_ssi:%22In%20accessioning%22&fl=id&fq=status_ssi:*Accessioned

see statii, first 10:
- https://sul-solr-c.stanford.edu/solr/argo3_prod_shard1_replica1/select?fq=processing_status_text_ssi:%22In%20accessioning%22&fl=id,status_ssi,processing_status_text_ssi&fq=status_ssi:*Accessioned

**Comment by blalbrit** [comment]
And have confirmed that a manual reindex on a given object clears the conflict:

https://argo.stanford.edu/catalog/druid:fw120yr4606.json

**Comment by jmartin-sul** [comment]
just to clarify, since it wasn't clear whether this was pointed out (though naomi's last comment implies it):  argo uses the `argo3_prod` solr collection.  the legacy (argo 2.x) collection is `argo` (and i believe it is no longer getting updated, because dor-indexing-app-legacy-prod was decommissioned, IIRC).  the `argo_b` solr collection was the original argo 3.x solr collection, used to test indexing for the move to prod, but we ended up deciding to create a new collection with a better name since we intended to build the argo 3 index from scratch again for the actual deployment.

**Comment by jmartin-sul** [comment]
which is to say, nothing actually uses `argo_b` anymore, and it was never in production.  i think that one can safely be deleted (but i think we should keep `argo` around for just a bit longer, just in case)

**Comment by blalbrit** [comment]
thanks @jmartin-sul - so it looks like the argo3 shards are on solr-c and solr-e. @ndushay has produced a nice list of about 2406 objects in the two-status state, each of which can be cleared by reindexing. The question is now how we are getting objects reflecting two statuses - and the answer *seems* to be that editing an individual datastream in an object causes a status flip in the processing_status_text_ssi and _code_ssi for some reason.

**Comment by ndushay** [comment]
@blalbrit   so will there be a new ticket for   "The question is now how we are getting objects reflecting two statuses - and the answer seems to be that editing an individual datastream in an object causes a status flip in the processing_status_text_ssi and _code_ssi for some reason."  ?   Or will this ticket become that ticket?

Either way, it seems that this will NOT be promoted to must-have ???

**Comment by blalbrit** [comment]
@ndushay - we're still analyzing. Agree that a new ticket would be good if the problem moves forward.

**Comment by blalbrit** [comment]
Old issue from Argo indexing work several years ago. Closing.
