### ISSUE TITLE
Screen refresh issue after bulk upload

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#699]
For bulk upload, newly submitted jobs do not automatically show up in the history on the page (no underlying page refresh), which is ok. But when I refreshed the page, I got a "Sorry, something went wrong". I simply send the page request again and it worked fine. I have reproduced this twice. I don't know if there's a window when constructing the page might be vulnerable, or something with reload per se. 

Link to squash for page reload error - https://sul-squash.stanford.edu/projects/argo/environments/staging/bugs/31

**Comment by blalbrit** [comment]
@LynnMcRae - I haven't received any further reports of this bug. Can you confirm whether or not this is still a valid issue? If not, we can close it.
