### ISSUE TITLE
Bulk download can get its Success count off if there is any error during processing

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#711]
Note counts from the two large runs in stage:
![screen shot 2016-03-30 at 4 04 15 pm](https://cloud.githubusercontent.com/assets/1824732/14160422/2484e89a-f691-11e5-9be4-b6c052eaa889.png)

In both cases, there was a single timeout error in the course of the run, which seems to be related:
![screen shot 2016-03-30 at 4 06 15 pm](https://cloud.githubusercontent.com/assets/1824732/14160476/7504c272-f691-11e5-996f-4228c6b52023.png)

**Comment by ndushay** [comment]
FYI, I *think* @tingulfsen 's mistaken commit to master branch was to fix this, and is now deployed in production.  Check and see if it's fixed?

**Comment by blalbrit** [comment]
No further reports of this happening. Closing.
