### ISSUE TITLE
Delayed Jobs are not terminated correctly when timing out?

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/argo#721]
Set Delayed::Worker.max_run_time to a value that is obviously too short, such as 5 minutes. Then start a descriptive metadata download job that will run longer than that.

When doing this, I've observed some strange behavior. It appears that the application is attempting to stop the currently running job, then restart it. However, I do not believe that the original job is actually stopped. The 'lsof' command shows that the original job is still writing to the log file, and the success column on the index page for the job starts fluctuating wildly.

As long as the maximum runtime is set high, and we don't run jobs that are too large (I've tested up to 75k objects), we should not run into this problem. However, in the future we need to do some more serious debugging to find out what the underlying problem is.

**Comment by jcoyne** [comment]
We are no longer using DelayedJob (we moved to Sidekiq)
