### ISSUE TITLE
Cannot version Google Scanned Books

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#723]
This is a known limitation due to the age of the Google Scanned Book objects, which don't conform to the current DOR item model, e.g., lack of objectType. An attempt to do so in Argo will get a system error, e.g.,  https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/148

The proposed solution is to update the objects to get them in line.

**Comment by blalbrit** [comment]
This is a data fix, not an Argo code fix. Will reflect in accessioning/remediation ticket.
