### ISSUE TITLE
Argo gets system error on non-XML datastreams

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#724]
Recording a perfectly reasonable limitation since current DOR models only stored XML metadata in datastreams.  The ETD application creates child objects which store PDFs in a datastream for use by the app.  These datastreams cannot be displayed in Argo via the XML modal display, logically enough. 

We could enhance Argo to recognize such datastreams by mime-type to avoid a system error, though it is not urgent as these child objects are not typically encountered or managed in Argo and will eventually go away.

**Comment by andrewjbtw** [comment]
As SDR moves away from XML and datastreams, this may stop being relevant. Especially if ETD PDFs are the only instance of non-XML datastreams.

**Comment by jcoyne** [comment]
@andrewjbtw we've removed those datastreams from the ETD app.

**Comment by andrewjbtw** [comment]
I am closing this as we are not using any new non-XML datastreams and are going to move away from datastreams altogether as part of SDR evolution.
