### ISSUE TITLE
Admin policies not in Object Type facet or quicksearch for non-admin

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#726]
We recently extended the scope of what a person could see/manage from "all items governed by an APO" to the APO itself when permission is granted via a dor-apo-manager or -viewer role.  This works fine when following a direct link to an APO, but it does not include searching by quicksearch or facet.  For instance, if impersonating workgroup:sul:map-staff, I can see the APO

https://argo.stanford.edu/catalog/druid:xw330hm5827

I can also use the Admin Policy facet to find all items governed by this APO, and from those items I can navigate to the APO.  But you see no APOs listed under the Object Type facet, nor does a search for "druid:xw330hm5827" or "xw330hm5827" yield a result.

Access is access and should include all aspects of the user experience, including search.

**Comment by hannahfrost** [comment]
Not able to confirm that this is still a bug because I could not access this APO while impersonating that workgroup.
