### ISSUE TITLE
Purge no longer deletes the solr doc

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#728]
Test object druid:np266dm3062 in prod Argo can be found via a search and shows on a result page based on solr, but if you try to show the detail page you get "Object not found" because it was purged.

It's possible the part of purge that deletes a doc from solr is pointing to the wrong solr code since the new index?

**Comment by blalbrit** [comment]
As of today, bulk purge is successfully removing the solr docs - based on user feedback, so is individual purge.

**Comment by LynnMcRae** [comment]
Tested in stage with success!
