### ISSUE TITLE
ItemsController#close_version fails on workflow objects

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#729]
https://sul-squash-prod.stanford.edu/projects/argo/environments/production/bugs/161#history

error message is `undefined method`close_version' for #<Dor::WorkflowObject [DESCRIPTION]>`

stack trace is:

```
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/activemodel-4.2.5.2/lib/active_model/attribute_methods.rb:433
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/active-fedora-6.7.3/lib/active_fedora/base.rb:44
/opt/app/lyberadmin/argo/shared/bundle/ruby/2.2.0/gems/dor-services-5.8.0/lib/dor/models/identifiable.rb:50

app/controllers/items_controller.rb:400
```

my guess as to what's happening, and why we didn't see this before (as far as i'm aware, this is a new issue):
- recently, `ItemsController` was fixed so that it used `Dor.find` to load objects, instead of `Dor::Item.find`, so that the object is loaded as its actual type, instead of always being loaded as an `Item`.  that was done because APOs were being loaded as items, and then indexed to solr as the wrong type.  as we can see here, this is yet another example of `ItemsController` being used to deal with non-item objects (since it does general things like updating datastreams and closing versions, which apply to more than just items).
- [`Dor::WorkflowObject`](https://github.com/sul-dlss/dor-services/blob/v5.8.0/lib/dor/models/workflow_object.rb) isn't [`Versionable`](https://github.com/sul-dlss/dor-services/blob/v5.8.0/lib/dor/models/versionable.rb), and so doesn't have the `close_version` method.
- since `ItemsController` used to load everything as a [`Dor::Item`](https://github.com/sul-dlss/dor-services/blob/v5.8.0/lib/dor/models/item.rb) (by using `Dor::Item.find` instead of `Dor.find`), everything it dealt with was `Versionable`, and so the `close_version` method was available.  so my guess is that fixing issue #725 caused this regression.

my proposed fix would be to make workflow objects versionable in dor-services (since it appears that we want to version them).  then to upgrade argo to the new dor-services once that fix is released.

theory and suggestion pending testing, of course, but that all feels like a reasonable place to start investigating.

**Comment by LynnMcRae** [comment]
Agree to making workflow objects versionable. All DOR objects are repository objects and should support versioning, accessioning, etc, even internal system objects since we want the opportunity to track changes by version.

**Comment by blalbrit** [comment]
+1 to this.

**Comment by mjgiarlo** [comment]
@jmartin-sul we're no longer using a workflow datastream. close?
