### ISSUE TITLE
Workflow grid - status reset button problem on workflows related to repo = sdr

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#73]
when you make a call to reset a step you must indicate the repo associated with that step. compare: 

Dor::WorkflowService.update_workflow_status 'sdr', druid, 'sdrIngestWF', 'verify-agreement', 'waiting' 
Dor::WorkflowService.update_workflow_status 'dor', druid, 'accessionWF', 'provenance-metadata', 'waiting' 

Note the distinction between sdr and dor in the call. When this feature was implemented in Argo, the repo variable was hard coded into Argo, see the code below: 
https://github.com/sul-dlss/argo/blob/cb68582b783bd0593a1cb412918cb767800edddb/app/controllers/report_controller.rb#L76 
The reset button logic needs to reference the appropriate repo; similar to what (I think) is being done here: 
https://github.com/sul-dlss/argo/blob/48c1b6071f7852e299d2ea9b7e7fa7a64866cf74/app/helpers/workflow_helper.rb#L34

**Comment by drh-stanford** [comment]
@LynnMcRae i just want to make sure that you're talking about these reset buttons in the UI:

![screen shot 2015-11-12 at 9 57 17 am](https://cloud.githubusercontent.com/assets/1861171/11126428/caa59aca-8923-11e5-867c-9fddf73f91b0.png)

is there any other place the "reset" functionality appears in Argo other than the above window?

**Comment by drh-stanford** [comment]
The HTML for that button already has `repo=sdr` in it:

```html
<form accept-charset="UTF-8" action="https://argo.stanford.edu/items/druid:cq146nt4106/workflows/sdrIngestWF" class="dialogLink" method="post">
<div style="margin:0;padding:0;display:inline">
<input name="utf8" type="hidden" value="✓">
<input name="authenticity_token" type="hidden" value="1HY5GrbbHtCS9Vt4fLsWPCI95LeSO45yuukHKnoSMi4="></div>
<input id="process" name="process" type="hidden" value="transfer-object">
<input id="status" name="status" type="hidden" value="waiting">
<input id="repo" name="repo" type="hidden" value="sdr">
<button name="button" type="submit">set to waiting</button></form>
```

And the controller uses that repo parameter: https://github.com/sul-dlss/argo/blob/develop/app/controllers/items_controller.rb#L139 so the bug lurks deeper I think :-/

**Comment by LynnMcRae** [comment]
Just verified with Ben, it is the reset on the Grid view, not the formatted view of item-level workflows. The "reset" link in the attached picture.
![screen shot 2015-11-12 at 10 06 09 am](https://cloud.githubusercontent.com/assets/1824732/11126734/334c58ec-8925-11e5-8b7d-cdc445271009.png)

**Comment by drh-stanford** [comment]
The problem here is that `render_workflow_reset_link` is not passing the repo into the `/report/reset` route, nor is `ReportController#reset` taking a repo parameter to pass to `Dor::WorkflowService.update_workflow_status`

**Comment by drh-stanford** [comment]
Here's what the modification to the `/report/reset` route might look like:

```
diff --git a/app/controllers/report_controller.rb b/app/controllers/report_controller.rb
index c204bfa..642994e 100644
--- a/app/controllers/report_controller.rb
+++ b/app/controllers/report_controller.rb
@@ -68,10 +68,11 @@ class ReportController < CatalogController
   # an ajax call to reset workflow states for objects
   def reset
     return unless request.xhr?
+    @repo = params[:reset_repo] || 'dor'
     @workflow = params[:reset_workflow]
     @step = params[:reset_step]
     @ids = Report.new(params, ['druids']).pids params
-    @ids.each { |pid| Dor::WorkflowService.update_workflow_status 'dor', "druid:#{pid}", @workflow, @step, 'waiting' }
+    @ids.each { |pid| Dor::WorkflowService.update_workflow_status @repo, "druid:#{pid}", @workflow, @step, 'waiting' }
     ### XXX: Where's the authorization?
   end
 ```

**Comment by mejackreed** [comment]
@LynnMcRae How can we know what repo the step is associated with?

**Comment by blalbrit** [comment]
@mejackreed all steps in the sdrIngestWorkflow are associated with the sdr repo. or are you asking more generically?

**Comment by mejackreed** [comment]
Is that the only workflow that is associated with SDR? Is everything else dor?

**Comment by blalbrit** [comment]
I believe so - will double-check.

**Comment by blalbrit** [comment]
Checking workflow objects in Argo: https://argo.stanford.edu/view?controller=report&f%5BobjectType_facet%5D%5B%5D=workflow

In the workflow definition datastream, the repo is specified for each workflow.

22 of these. Let me see if I can just pull out a summary for verification.

**Comment by blalbrit** [comment]
I'm not seeing that we've indexed these in a way that makes summary easy.

**Comment by mejackreed** [comment]
Let me ask another question:

Does one assign the repo by creating the workflow definition datastream?

**Comment by drh-stanford** [comment]
Yes, a workflow's repo is defined in the `workflowDefinition` datastream of the workflow object.  You can see an example here:  

  https://argo.stanford.edu/view/druid:bb163sd6279/ds/workflowDefinition

```xml
<workflow-def id="sdrIngestWF" repository="sdr">
...
</workflow-def>
```

**Comment by drh-stanford** [comment]
if you need a list of all workflow definitions, you can get them from the Solr index using `objectType_t:workflow` and `fl= id,workflow_name_s`, then you can fetch the data from Fedora, like so:  

```ruby
#{FEDORA_URL}/objects/#{druid}/datastreams/workflowDefinition/content
```

There's some example code that does it here: https://github.com/sul-dlss/robot-master/blob/master/bin/robot-download-workflows#L45

in theory, they are all cacheable as they change rarely, if ever.

**Comment by mejackreed** [comment]
Gotcha.. thanks thats super helpful. I'm just trying to grock where this logic _should_ live. A quick browse around dor services doesn't seem to have it. So that piece of information just sealed the deal on how I will approach it.

**Comment by jmartin-sul** [comment]
minor correction to the above solr field names:  you'd actually want to use  `objectType_ssim` and `workflow_name_ssim` (@atz entirely rooted out use of the `_s` and `_t` suffixes, AFAIK).

**Comment by jmartin-sul** [comment]
also:  just filed an issue to track updating solr field names in other codebases, with the above robot-master line as an example:  https://github.com/sul-dlss/argo/issues/251

**Comment by mejackreed** [comment]
Yep I don't think this is an issue here now as I'm using this call to get the repo:

`Dor::WorkflowObject.find_by_name([workflow]).definition.repo`

**Comment by drh-stanford** [comment]
yeah, sorry the code I pointed to above is using dor-services 4.x
