### ISSUE TITLE
Metadata Upload Fails on Large Numbers of Objects

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#731]
Example, with a spreadsheet of 252 items, system errors are reported (Net::ReadTimeout on the Modsulator server). Running smaller batches of the spreadsheet work fine. History available here: https://argo.stanford.edu/catalog/druid:sb559ym0369/bulk_jobs_index (see Sri Lanka spreadsheet attached).

![screenshot 2016-04-20 10 17 54](https://cloud.githubusercontent.com/assets/796990/14683787/6dee8d0a-06e1-11e6-83d8-41dd715a59fa.png)

[SriLanka_BulkUpload.xlsx](https://github.com/sul-dlss/argo/files/228446/SriLanka_BulkUpload.xlsx)

**Comment by tingulfsen** [comment]
I've done a little investigation, but the nature of this problem has proven to be quite difficult to track down. I think I'll need some input from @blalbrit and @LynnMcRae to figure out how to proceed, with respect to how much time we should devote to this.

**Comment by LynnMcRae** [comment]
Here is a MODS/XML file of 500 records that fails (from Robert Rohrbacher, April 28):

> Hello,
> 	I'm trying to load a batch of 600 MODS records for the Rumsey Map Collection. I got system errors (https://argo.stanford.edu/catalog/druid:sq161jk2248/bulk_jobs_index)
> 
> Robert
> 

Note I have changed the file extension from .xml to .txt so I could upload it here.
[Batch4_1st.txt](https://github.com/sul-dlss/argo/files/241575/Batch4_1st.txt)

**Comment by blalbrit** [comment]
Just tested this on production files using the Batch4_1st file listed above from Robert.

Results are:

<img width="903" alt="screenshot 2016-05-26 20 51 12" src="https://cloud.githubusercontent.com/assets/796990/15597311/c794390e-2383-11e6-9d60-9a22f42d9842.png">

**Comment by blalbrit** [comment]
re: above comment, this can be found at https://argo.stanford.edu/catalog/druid:sq161jk2248/bulk_jobs_index
