### ISSUE TITLE
Report view fails to show objects in results for certain facet combinations

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#733]
This search: https://argo.stanford.edu/catalog?f%5BobjectType_ssim%5D%5B%5D=collection&f%5Bregistered_date%5D%5B%5D=days_30&f%5Bsource%5D%5B%5D=hyrdus&page=1&per_page=50

produces:

![screenshot 2016-04-21 09 21 45](https://cloud.githubusercontent.com/assets/796990/14716569/68cf0da6-07a2-11e6-899c-f37f219affdb.png)

**Comment by LynnMcRae** [comment]
The Object Source facet seems to be the report killer.  If used alone, which gets a result of 5000+, you get
![screen shot 2016-04-21 at 9 36 18 am](https://cloud.githubusercontent.com/assets/1824732/14717127/cd9edec6-07a4-11e6-82ae-e3f61b96d3ea.png)

We've seen something like this in the past, when the "Within N days" facets used to kill reporting, though I never understood the how or whys of it.

**Comment by blalbrit** [comment]
Results disappear when switching from results view to report view. Facets applied: collection, processing status, empty fields.
 
Arcadia Falcone
Metadata Coordinator
Stanford University Libraries
arcadia@stanford.edu
(650) 498-8058

**Comment by blalbrit** [comment]
The following combination also results in a null set:

https://argo.stanford.edu/catalog?f[empties][]=no_collection_title&f[exploded_tag_ssim][]=Project+:+M0733+ginsberg

**Comment by cbeer** [comment]
`empties`, `object_source`, and `registered_date` are queries facets and the user parameters are not being correctly translated to their underlying solr queries. I don't see where the `Report` model brings in the configuration that makes that possible.
