### ISSUE TITLE
MJF bulk upload failing

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#735]
This is on APO https://argo.stanford.edu/catalog/druid:jc903qt9117/bulk_jobs_index

Per @shelleydoljack 
I tried a file of 100 records and got this system error: 

"Job started","2016-04-25 14:22pm" 
"Note","File of 100 MODS records for MJF." 
"Error - the uploaded file was lost","No such file or directory @ rb_sysopen - /workspace/bulk/tmp/MJF_file_1.xml.2016_04_25_21_22_12_375" 
"Exception","Got no response from server" 
"Job finished","2016-04-25 14:22pm" 
"Druids loaded","0"

**Comment by tingulfsen** [comment]
I'm very disappointed by this...can we get the offending spreadsheet file for debugging purposes?

**Comment by blalbrit** [comment]
@shelleydoljack - can you attach your spreadsheet to this ticket for further analysis?

**Comment by shelleydoljack** [comment]
[MJF_MODS_druids.xml.zip](https://github.com/sul-dlss/argo/files/242906/MJF_MODS_druids.xml.zip)

Attaching the big file I'm trying to load. I also have the file broken up into 100-records-per-file files that I've tried running and failed. Do you want that one too?

**Comment by shelleydoljack** [comment]
Here's the 100-records-per-file files:
[descMDfiles.zip](https://github.com/sul-dlss/argo/files/242911/descMDfiles.zip)
