### ISSUE TITLE
Registration/accessioning of an object as CitationOnly produces empty contentMD on publish

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#736]
This causes embed to attempt to display content. Desired behavior would be no content metadata for citation-only objects.

See: https://purl.stanford.edu/bj883by0423

**Comment by LynnMcRae** [comment]
This is covered by https://github.com/sul-dlss/dor-services/issues/97

**Comment by blalbrit** [comment]
Problem fixed through Embed.
