### ISSUE TITLE
Provide visual indication of insufficient user permissions on search result

### ISSUE THREAD

**Issue by AstridJS** [sul-dlss/argo#740]
Hi! 
We have staff helping search for items in Argo, to see if they have been digitized or provide PURL links, and sometimes they will report out that they do not exist -- for some, I personally digitized them and know they exist. It became clear that the problem was the page for insufficient permissions access and the page for no result yielded is the same:

"No results found for your search
Try modifying your search
    Use fewer keywords to start, then refine your search using the links on the left.

Thank you for taking this feedback into account!

**Comment by mejackreed** [comment]
Thanks for submitting the issue. I don't think it sounds like we would be able to accommodate customized per result information about permissions to view the item.

We could however add a better message, something like:

```
No results found for your search
Try modifying your search
Use fewer keywords to start, then refine your search using the links on the left
You may not have permission to view items you are searching for
```
