### ISSUE TITLE
Bulk Update of tags does not copy forward existing tags for pasted druid list

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#741]
When doing a bulk tag update (the Tags button), the current set of tags should seed the box with existing values so they can be augmented, edited or removed. This works when "Get druids from search" is used, but the update box is empty for a pasted druid list.

**Comment by oceanofsound** [comment]
2019 update: this is still a problem. As a user who occasionally works on content registered by other people, the ability to bulk add tags makes retrieval much easier. However, with this functionality broken, it can be very difficult to corral a set of objects without manually going to each one and adding a tag.
