### ISSUE TITLE
Report view - drop redundant Admin Policy and Collection columns

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#75]
When the facets split into DOR and Hydrus lists, the split versions were added as reporting columns and included in the default report. Only the "all" column makes sense, as the appropriate APO and Collection title should show according to the druid, with column headings "Admin Policy" and "Collection"

**Comment by drh-stanford** [comment]
@LynnMcRae Hi, I'm not sure I'm understanding the issue here. Specifically, I'm not sure what you mean for the "all" column. Here's what I'm seeing in production for the report view with the default columns and the column selector:

![screen shot 2015-11-17 at 4 36 56 pm](https://cloud.githubusercontent.com/assets/1861171/11229370/793803e2-8d49-11e5-88de-8b6c5fc419fe.png)


![screen shot 2015-11-17 at 4 37 59 pm](https://cloud.githubusercontent.com/assets/1861171/11229387/985df042-8d49-11e5-9ff1-43b46fcd85ed.png)

**Comment by drh-stanford** [comment]
and for a Hydrus Collection:

![screen shot 2015-11-17 at 4 43 46 pm](https://cloud.githubusercontent.com/assets/1861171/11229476/6d283c56-8d4a-11e5-8b67-73296f8b2009.png)

**Comment by LynnMcRae** [comment]
At the moment I can't see a report because argo-dev gives me:

Sprockets::Rails::Helper::AssetFilteredError in Report#index
Showing /opt/app/lyberadmin/argo/releases/20151117174220/app/views/report/index.html.erb where line #3 raised:

Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( ui.jqgrid.css )` to `config/initializers/assets.rb` and restart your server
Extracted source (around line #3):
              
<% content_for :head do %>
  <%= javascript_include_tag 'report' %>
  <%= stylesheet_link_tag 'ui.jqgrid' %>
  <script type="text/javascript">
    report_model = {
      total_rows: <%= @response['response']['numFound'] %>,

**Comment by LynnMcRae** [comment]
In your screen shot, note that it offers both a Collection column and a Hydrus Collection column.  For a report, an item is or isn't in a collection regardless of the type of collection (based on isMemberOfCollection relationship), so there should be only one column that shows collection membership, just as there is only one Collection ID column, not two columns each for separate flavors of collection forcing you to include two columns for coverage.

When I did the ticket, there was also an "Admin Policy" and"Hydrus Admin Policy" -- same issue.  But that seems to have gone away?  The one Admin Policy column should be about the isGovernedBy relationship regardless of the type of APO. Can you confirm that is the case?

**Comment by LynnMcRae** [comment]
Not sure what the "All" column refers to, maybe there were 3, either/or/all columns at the time.  Sorry I didn't get a screen shot. We just want single (combined hydrus and non-hydrus) Collection, Collection ID, Admin Policy and Admin Policy ID columns.

**Comment by mejackreed** [comment]
Re: bug see #212

**Comment by drh-stanford** [comment]
With PR #212 in, I can now see the issue as shown in these screenshots:

![screen shot 2015-11-18 at 11 28 53 am](https://cloud.githubusercontent.com/assets/1861171/11251798/cad85b4a-8de7-11e5-9c79-5c5ebe6748d2.png)
![screen shot 2015-11-18 at 11 29 04 am](https://cloud.githubusercontent.com/assets/1861171/11251799/cbea6d70-8de7-11e5-8284-3d99b0819c02.png)

**Comment by jmartin-sul** [comment]
i believe you want to use `apo_title_ssim`.  IIRC, only hydrus APOs have the `hydrus_` version, and non-hydrus APOs have the `nonhydrus_` version, but all APOs should have the one without the qualifying prefix.

**Comment by drh-stanford** [comment]
Here's what the fix looks like:

![screen shot 2015-11-19 at 3 24 55 pm](https://cloud.githubusercontent.com/assets/1861171/11287598/bfac7ff4-8ed1-11e5-9c87-d070baff60aa.png)
