### ISSUE TITLE
Argo access rights facet should include <agent> and <location> flavors

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#753]
The access rights facet currently shows these values

   world_qualified
   world
   dark
   citation
   stanford
   stanford_qualified

Where qualified currently means the presence of the no-download rule (presumably other rules if we define more).

This facet does not include indication of <agent> or new <location> restrictions. These should be added as simple separate facet values since they act indipently from the others. That is, the presence of either of these in rightsMetadata should be indexed as "Location {value}" or "Agent {value}" for the facet.

**Comment by blalbrit** [comment]
![screenshot 2019-01-09 14 32 38](https://user-images.githubusercontent.com/796990/50932798-8932ef80-141b-11e9-96e0-0fa7c052ca61.png)

Seems to have been implemented as spec'd.
