### ISSUE TITLE
Role-based access stopped working with solr 6.1 upgrade

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#759]
at least we believe the two must be connected.  Try impersonating any workgroup that should give a users lots of stuff:

   workgroup:dlss:pmag-staff
   workgroup:sdr:dpg-staff
   workgroup:dlss:pmag-staff

If we can figure out why impersonate doesn't work, we willprobably know why user's role-based access doesn't work either.

**Comment by cbeer** [comment]
Probably related to https://issues.apache.org/jira/browse/SOLR-8812, although our current practice seems.. wrong. I'm surprised to see those filters in the `q` parameter, instead of an `fq`.
