### ISSUE TITLE
Register Items - Admin Policy pulldown is empty

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#766]
related to solr 6.1 change I presume.

**Comment by jmartin-sul** [comment]
this appears to be happening on prod too, so my initial suspicion is that this isn't a regression due to the fixes implemented yesterday, but will investigate.

**Comment by jmartin-sul** [comment]
this looks like another instance of the thing that @cbeer fixed yesterday with the query refactoring seen in PR #760.

at first glance, the culprit appears to be:
https://github.com/sul-dlss/argo/blob/master/app/helpers/registration_helper.rb#L3

invoked from:
https://github.com/sul-dlss/argo/blob/master/app/views/items/register.html.erb#L11
