### ISSUE TITLE
Datastream edit - system error on bad XML input

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#78]
A mistake when editing a datastream's XML in the lightbox will lead you to a system error screen -- RuntimeError in ItemsController#datastream_update. Better if you could tell the user they had invalid XML without leaving the edit context, so they don't lose their work.

**Comment by drh-stanford** [comment]
is this a bug or enhancement?

**Comment by LynnMcRae** [comment]
It's bad UI behavior as a start. I put it in the bug category because I think we should be avoiding "system error" (and any subsequent logging/alert/whatever we consider a measure of instability in the app) as the end point of any catchable/anticipated error condition. I should probably +1 it as well since it's also a pain in the neck when it hits you.

**Comment by drh-stanford** [comment]
For "invalid XML" I can only check to see if it can be *parsed*, not whether it's valid according to a schema. I've made a PR that uses `jQuery.parseXML` to check whether the XML can be parsed before allowing you to submit the form.

**Comment by LynnMcRae** [comment]
That is great for now.  Fedora doesn't actually schema check, but it barfs if the XML is not well formed, and hand edits are susceptible to such errors.

**Comment by drh-stanford** [comment]
here's what the revised datastream XML editor looks like on error. Note the style changes of a monospace font and blue submit button.

![screen shot 2015-12-16 at 12 50 31 pm](https://cloud.githubusercontent.com/assets/1861171/11853635/01045990-a3f4-11e5-8da0-f1e394fc8a2a.png)

**Comment by LynnMcRae** [comment]
Why the switch to monospaced font?  It's not been an issue, but I'll need to see it live.

**Comment by drh-stanford** [comment]
The prior page uses monospace to display the XML, so the Edit page also uses monospace now. We can reopen if you find it problematic.

**Comment by LynnMcRae** [comment]
My bad. I thought the prior screen was not-monospaced, but that was just from a quick glance. It is a cleaner and more readable font however, even at a smaller size.  I'm failing at figuring out the actual fonts in use however.
![screen shot 2015-12-16 at 5 44 16 pm](https://cloud.githubusercontent.com/assets/1824732/11859413/5a4d4888-a41f-11e5-8d39-213d9df155c2.png)
![screen shot 2015-12-16 at 5 46 44 pm](https://cloud.githubusercontent.com/assets/1824732/11859417/637d4c6e-a41f-11e5-91e2-737dc87ff7b1.png)

The display form in prod also word-wraps in both display and edit, while the new display hard wraps at the right margin. Word wrap is preferable.  These can perhaps wait, assuming we'll be able to do some small measure of UI polish near the end.
