### ISSUE TITLE
Add facet for error messages

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#780]
Currently, we can see large numbers of objects error out at a specific workflow step. It would be ideal to be able to facet on error messages to isolate specific sets for remediation.

**Comment by jcoyne** [comment]
@andrewjbtw is this still needed?

**Comment by andrewjbtw** [comment]
Closing this because we've greatly reduced the volume of errors and error messages, so the need to distinguish them via faceting has also been reduced.
