### ISSUE TITLE
Task that maintains Argo .htaccess does not process sunetids

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#782]
The current task to maintain the Argo .htaccess file -- argo/lib/tasks/argo.rake -- only processes workgroup references to create "Require privgroup" and "WebAuthLdapPrivgroup" statements. But individuals can be named in roles like so:

```
  <roleMetadata>
     <role ...> 
       <person>
          <identifier type="sunetid">[sunetid]</identifier>
       </person>
```

Where [sunetid] is just the sunetid value, like "lmcrae". These should be translated into "Require user [sunetid]" and "WebAuthLdapUser [sunetid]" in the .htaccess file.

**Comment by LynnMcRae** [comment]
According to Kam, because we have "AuthType WebAuth" we only need the simple "Require privgroup|user" statements, not the WebAuthLdapPrivgroup or WebAuthLdapUser ones, so those should be omitted.

**Comment by cbeer** [comment]
We will need `WebAuthLdapPrivgroup` in order for mod_webauthldap to send the the list of matching privgroups to the application. We don't need `WebAuthLdapUser`, though (if that's even a thing?), as we always get the user id.

**Comment by LynnMcRae** [comment]
see also https://github.com/sul-dlss/argo/issues/919 in case we revise the method for Argo's front door access.

**Comment by blalbrit** [comment]
I believe this is no longer relevant after move to shib and user maintenance through workgroups exclusively.
