### ISSUE TITLE
Add blue button & bulk update actions for "Manage Catkey"

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#785]
Quite often, objects need to be associated with a catkey after the fact. This enhancement would allow a user to add a single catkey to a single object, or to add catkeys to a list of objects produced either by a search or a pasted druid list.

The desired action would be to:
1) add catkey to identityMD if missing
2) change or delete existing catkey as needed
3) do NOT automatically refresh descMD from source (the association with catkey could be for purely organizational needs, not descMD needs), be offer an option to do so?

Normal prepare/close version process should handle the republish process. This would be an action that requires versioning.

**Comment by blalbrit** [comment]
@LynnMcRae This was completed on a per-item basis. Did we lose the bulk action work based on available developer time? If so, I'll update the ticket to reflect that so that we don't lose track of it.

**Comment by LynnMcRae** [comment]
Maybe split the bulk work off to a new ticket? We had an easy path to adding a blue button, but a bulk action would mean adding a new, and very desirable, pattern to bulk actions what could allow import of any number of predefined tuples or small sets of druid+related data, even if we only established the pattern with catkey import.

**Comment by LynnMcRae** [comment]
Maybe split the bulk work off to a new ticket? We had an easy path to adding a blue button, but a bulk action would mean adding a new, and very desirable, pattern to bulk actions what could allow import of any number of predefined tuples or small sets of druid+related data, even if we only established the pattern with catkey import.

**Comment by blalbrit** [comment]
👍 Great - so I'll close this ticket (the single-item catkey stuff is in production) and start a new ticket for a new bulk action.
