### ISSUE TITLE
Problem with population of dropdown lists in APO editing screen

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#787]
Per Geoff Willard:

If you take an APO (any APO probably), you’ll notice that when you bring up the edit screen the dropdown values for ‘Agreement’ and ‘Default Object Rights’ are always SPEC/UA and World respectively. If you make changes and save, the changes will persist, and the APO will respond correctly on the registration screen. However, if you go back into the APO to edit it, you may be fooled thinking you forgot to set the correct agreement or default rights. Or worse, you go in to make some other change, save it, and then don’t realize that you’ve inadvertently changed the agreement and default rights. Strange!

**Comment by andrewjbtw** [comment]
Fixing this will reduce the amount of direct XML editing people do on APOs, since people often work around the form by updating datastreams directly in order to avoid changing other APO settings.

**Comment by peetucket** [comment]
Looks like the default APO is now "1947 Partition Archive" (probably just alpha ordering by default and pick the first).

**Comment by peetucket** [comment]
It looks like the default rights are set correctly based on what is in the object.  

This object, for example, has the defaultObjectRights for "read" set to "Stanford", and it correctly selects this in the drop-down menu when you edit the APO: https://argo.stanford.edu/view/druid:bj961cc4982

This object correctly default to "world": https://argo.stanford.edu/view/druid:gc579md6928

Still looking at the agreement

**Comment by peetucket** [comment]
I'm going to keep this open until I can verify the fix

**Comment by peetucket** [comment]
This is fixed, but due to an issue with multiple agreements being set in an object, the drop-down menu for agreements will continue to show the first one in the object.  A bug for multiple agreements being set when changing agreements on this form is at #2061
