### ISSUE TITLE
Eliminate rspec 3 deprecation warnings

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#79]
Per John: there are a couple of deprecation warnings after the upgrade from rspec 2 to rspec 3 (actually, there are probably many instances of deprecated usages, but only two broad categories of usage which were warned about).

**Comment by mejackreed** [comment]
I'm not getting any rspec deprecation warnings anymore. Ok to close?

**Comment by jmartin-sul** [comment]
i think so, this was created from an old jira ticket, IIRC
