### ISSUE TITLE
Bulk Update: Set object rights - "none" should be "citation only"

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#791]
Currently, the choices in the drop down for the "Set object rights" action in Bulk Update include world, stanford, none, and dark. "None" is not helpful for our users and stakeholders, esp. b/c we describe this option as "Citation Only" in all of our documentation and Argo facets:
- https://consul.stanford.edu/display/DLSSDOCS/Discovery+and+Delivery+Options+for+Stakeholders
- https://consul.stanford.edu/display/chimera/Object+Rights+Overview

![bulkupdate_setobjectrights](https://cloud.githubusercontent.com/assets/796990/17938886/c16e1a1e-69dc-11e6-856b-0dbe6cfbc3bb.JPG)

**Comment by LynnMcRae** [comment]
Hopefully to be addressed in https://github.com/sul-dlss/argo/issues/796
