### ISSUE TITLE
Close Version dialog - additional spaces at beginning and CR added in version description

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#792]
Per user @nullhandle 

"After I’ve opened a version of an object for modification and entered a version description, when I go to close the object, six spaces have been prepended to my version description comment."

This issue has been verified.

**Comment by LynnMcRae** [comment]
An unseen additional error is the addition of a CR at the end:

```
<versionMetadata objectId="druid:hq740dq1933">
  <version versionId="1" tag="1.0.0">
    <description>Initial Version</description>
  </version>
  <version versionId="2" tag="1.1.0">
    <description>Add 3 missing permissions files&#xD;
    </description>
  </version>
</versionMetadata>
```
