### ISSUE TITLE
Report View: Download problems with druid list

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#794]
In a collection with more than x items, if you go to "report view" from anything other than page 1 of the paginated results, then on-screen the list of druids looks correct but, when downloaded, the first y druids are replaced by the druids at the top of page z (whichever page you were on in the results view), leading to a list of druids that is missing y number of druids and has y number of duplicate druids.

[See Lynn's screenshots below for an example. The original example in this ticket was a search that no longer returns results.]

**Comment by LynnMcRae** [comment]
Here are pictures showing another example:
![screen shot 2016-11-10 at 11 37 45 am](https://cloud.githubusercontent.com/assets/1824732/20191436/4ca41ab2-a73a-11e6-9b2d-5c76782d6e4a.png)

the downloaded data:
![screen shot 2016-11-10 at 11 38 01 am](https://cloud.githubusercontent.com/assets/1824732/20191448/5834854c-a73a-11e6-885f-a5f7afc1d4ed.png)

**Comment by hannahfrost** [comment]
This is still an active bug.

**Comment by andrewjbtw** [comment]
I believe this bug remains active. Will need to re-verify before moving up the priority list.

**Comment by andrewjbtw** [comment]
Verified that this remains an active bug.
