### ISSUE TITLE
openDataCommons licenses do not appear in the License facet

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#795]
The pddl, odc-by, and odc-odbl licenses do not seem to be appearing in the License facet.

See license specs here: https://consul.stanford.edu/display/chimera/Rights+metadata+--+the+rightsMetadata+datastream

Example: https://argo.stanford.edu/catalog/druid:bs363kb7165

**Comment by mejackreed** [comment]
This feels like an indexing issue with dor-services

**Comment by jmartin-sul** [comment]
yeah, dor-services is what i'd suspect
