### ISSUE TITLE
Tag links on show page metadata do not work

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#802]
I'm not sure what the expected behavior here should be, but currently they add search params to a show page url

```
https://www.example.com/catalog/druid:aa111bbb1111?f%5Btag_ssim%5D%5B%5D=Process+%3A+Content+Type+%3A+Book+%28flipbook%2C+ltr%29
```

This just links to the show page, rather than to a search of the tag. Is that what should happen?

**Comment by LynnMcRae** [comment]
nope, the druid should not be in there after /catalog.  Compare the project link which is correct (though specific to the project tag)
