### ISSUE TITLE
Bulk release

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#806]
Requires SDR admin role or APO manager role
I believe the use case is for white-listing or black-listing items only and should not apply to collection druids.  But since the point is the ability to drop in a druid list, have the processing skip (with a skipped status or message) any druid that is not object type "item".
The Item dialog above should suffice minus the line about current release state and with these choices:
( * ) Release this item regardless of release status of any collection it is in
(  ) Do not release this item regardless of release status of any collection it is in

**Comment by mejackreed** [comment]
@LynnMcRae what do the different options need to do in the background? Do they change the various attributes?

**Comment by blalbrit** [comment]
@mejackreed A few thoughts after testing in the -dev environment from me and @LynnMcRae:
- We can comment on design in -dev, but will need to see this in -stage to be able to test functionality
- change action title from "Release Items" to "Manage Release to Searchworks" (not elegant but...)
- change current radio button / dialog box section to (where the target choice is in a dropdown list):
![release](https://cloud.githubusercontent.com/assets/796990/18803155/76259770-81a2-11e6-8227-1e8d3e3271f3.png)

I think that about covers it - once you've got the Bulk Action available in -stage we can test further.

**Comment by LynnMcRae** [comment]
I think the Bulk action can still be just "Manage Release" so that won't have to change later.  Since the choice of target today is only Searchworks, that could be a one-item pulldown anticipating growth, or just static text until there more.

**Comment by mejackreed** [comment]
Re: Select Dropdown -> So I didn't put the targets in a single select, but in a multi-select box, for the future case where we would want to release it to multiple targets. Should that not be the case?

**Comment by mejackreed** [comment]
I'm not clear about the radio buttons. Do you want the radio buttons removed? The radio buttons are how we choose `true` or `false`

**Comment by LynnMcRae** [comment]
We intended release to be one target at a time. It's uncertain when we might get a even a second target and whether there would be any advantage to letting them be named together.  For instance, Revs and SW do not intersect.

**Comment by LynnMcRae** [comment]
the radio buttons stay, I think Ben was referring to the layout of the area they occupy per illustration.

**Comment by blalbrit** [comment]
yep - what @LynnMcRae said - sorry that wasn't clearer. just realign radio buttons and target choice like Lynn's diagram shows.

**Comment by mejackreed** [comment]
Gotcha! Perfect guys thanks for clearing it up. I'll push the changes early Monday.

**Comment by mejackreed** [comment]
I ended up preferring a vertical rather than horizontal approach. That felt a bit more stepwise of what needs to happen. Is that ok?

## horizontal
![screen shot 2016-09-26 at 8 58 29 am](https://cloud.githubusercontent.com/assets/1656824/18835097/7544c282-83c7-11e6-9e0f-994da4ca40c8.png)
## vertical
![screen shot 2016-09-26 at 8 58 14 am](https://cloud.githubusercontent.com/assets/1656824/18835096/754480ce-83c7-11e6-82fe-48a772d3050b.png)

**Comment by LynnMcRae** [comment]
Looks good to me . One detail...since we are acting only on items not collections, please use item instead of object in the labels.

**Comment by blalbrit** [comment]
@mejackreed - vertical looks great to me, and I agree with Lynn's label change.

**Comment by mejackreed** [comment]
WRT label change. This functionality _will_ release collection objects. (and try for anything else too). Thats why I left object there and not item. It doesn't only work on items. 

Though it will only release self, for any type of object. Does this change things?

**Comment by LynnMcRae** [comment]
Objects is ok then, but makes me want to state the rules in the convenient footnote text.   We have 

* this will override any collection release instructions

What about 

* for items this overrides any collection release instructions; for a collection this releases the collection object itself, not its members

**Comment by blalbrit** [comment]
@LynnMcRae - wordy, but clear. thank you for that.
