### ISSUE TITLE
INDEXING.md needs some updates

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#808]
- in the gotchas section, there's mention of memory leaks, and that we might be able to control this by using eye, but that manual intervention is needed for now.  this is no longer true:  we've been using eye to monitor delayed job workers and restart workers that consume too much memory, and this seems to be working well.
- add a short section to the top explaining the simple use case of just queuing up a list of druids (e.g. from a text file) using the console, since that's a common use case (and a more common use case than using the PidGatherer, for most people).

**Comment by jcoyne** [comment]
This document has been updated in the last workcycle.
