### ISSUE TITLE
Release tag history doesn't show all releases

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#809]
The history uses DorServices `release_tags` method, which interestingly enough doesn't return all release tags.

**Comment by LynnMcRae** [comment]
Perhaps a naming ambiguity ... my guess is that it produces the net release tags -- the latest setting for each target -- that is added to the Public XML as <releaseData>

**Comment by mejackreed** [comment]
Unfortunately I don't think its that smart to produce the "latest"

**Comment by mejackreed** [comment]
Some complexities involved here. The underlying dor-services api doesn't really provide the functionality as expected here. 

Should we?:
 - just parse the raw `identityMetadata` in Argo for display and understanding
 - add the needed functionality in dor-services
 - model release tags in argo
 - model release tags in dor-services

**Comment by LynnMcRae** [comment]
Personally I think just a straight XML to HTML transform of the raw tags would be the quickest/easiest solution. This is from someone who almost always prefers shared infrastructure service support for things. But it's just one small slice of an event/workflow/lifecycle-described history that deserves better DOR Services support in general, with ties into the creation of Provenance, and we don't need to go there now.
