### ISSUE TITLE
"gotchas" for using dor-services-app web service calls in Argo

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#813]
I just wanted to document some of the gotchas I've learned over the past few days using dor-services-app web services calls instead of local dor-services gem methods. See: https://github.com/sul-dlss/argo/pull/811

One of the main motivators for not using the dor-services gem was to remove the dependency for new features. IE.. we could update the gem in the app, without changing the behavior of the feature. This theoretically could work, but then we would have to maybe have multiple versions of dor-services-app (I digress). 

One of the pain points here I experienced was having to write a local Argo client to interface with the dor-services-app. This wasn't difficult, but just seemed like a bunch of extra work. Could there be efficiencies gained by having a dor-services-app-client gem? Or are we going in circles now even more?

Another pain point, is that dor-services-app is dumb to permissions. For the Release Object Job in Argo we had to pass through some webauth info, and then check permissions inline for every object. https://github.com/sul-dlss/argo/pull/811/files#diff-7584acc5a9e36d89d948133e0b60d66aR62 This works, but feels a bit strange and I'm not sure what a better solution is.

Just wanted to put down some of the thoughts I had down while they are fresh.

**Comment by LynnMcRae** [comment]
Can we talk about the permissions stuff more at your convenience? It is true that we create the web services access for ourselves, that is, for internal use ... by trusted apps like Argo or people like Ben with full privileges wielding his powers responsibly. Essentially SDR Admin level privs with access controls by certs or passwords. Is it essentially the background job workers that have made this a pain point? That they are now called on to enforce the same role-based permissions that the Argo app itself already knows how to do (has the information to do so)?

We have talked about eliminating the "drop in a druid list" approach in favor of "create a search result from a druid list", and then only allowing bulk actions against a search result. This would naturally filter the druid list based on permissions, and enable other incredibly useful things like reporting from your own druid list.

**Comment by LynnMcRae** [comment]
btw, I am in part asking because we are starting to work with Goobi developers for new digitization lab management processes which will need to register and read DOR objects. We want them to work through the Web Services APIs of course, but without global permissions. Our best idea so far is an intermediate service to proxy requests and apply some form of "and its a goobi managed object" filtering if more straight forward APO based privileges are not enough. This is all very preliminary.

**Comment by mejackreed** [comment]
Re: external API permissions, that is quite concerning and it seems like no part of our infrastructure have those capabilities.

Happy to discuss some of these issues at length with team and Argo devs. But my concern is that APO based permissions checking needs to happen differently globally if we are moving towards more web service based functionality.

**Comment by tingulfsen** [comment]
Let me know if you guys are going to meet about this, I'm not sure I understand all the implications - but I do think I should stay on top of Argo as much as possible.

**Comment by LynnMcRae** [comment]
Tommy, we have questions for you about how you do the same permissions checking for modsulator running as a background job.

**Comment by blalbrit** [comment]
@mejackreed - is this primarily historical information at this point (which could be moved out of a ticket), or is this something you think needs to stay active in the backlog?

**Comment by jcoyne** [comment]
Client gem created.
