### ISSUE TITLE
investigate replacement for delayed_job (resque-pool?  sidekiq?)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#816]
others in DLSS have had success using sidekiq for managing async job queues.  try using that as a possibly more robust solution for job management in argo (which currently uses delayed_job).

**Comment by drh-stanford** [comment]
You can look at the `discovery-dispatcher` repo for a DLSS sidekiq implementation

**Comment by blalbrit** [comment]
@jmartin-sul - would you consider this an ongoing concern, or is this closable?

**Comment by jcoyne** [comment]
I think we should keep this open.

**Comment by ndushay** [comment]
We have #966 which is to switch to sidekiq -- @jmartin-sul do we still have problems due to delayed_job or is this something we can/should ignore for SDR Fall 2019?

**Comment by ndushay** [comment]
@jmartin-sul says

- if we move, we should move to resque-pool
  - for thread safety
  - for consistency
  - sidekiq requires thread-safe code, argo prob doesn't have that

resque-pool is more robust than delayed-job

We if we make this change, we should do it separately from adding new async methods, or moving things to async methods (?)

Moving things to async has more user value at this time than refactoring how we use ActiveJob.

**Comment by ndushay** [comment]
@blalbrit @andrewjbtw @hannahfrost - John makes an excellent point and suggests this question:

would you rather:   
- A.  create new async bulk actions (moving existing bulk sync actions, creating brand new bulk actions)   

OR  

B.  be able to push more than ~500 objects through at a time?  (accommodate bulk actions for very large collection of objects: #1388

**Comment by jmartin-sul** [comment]
my hesitation to both add new Bulk Action features and to port argo's background job management away from DelayedJob comes from the infrastructure teams experience debugging the workflow service re-write while also doing other Argo and infrastructure maintenance at the same time.  my recollection (not being directly involved in that work) was that it made it hard to determine which line of work introduced particular bugs or regressions.  @jcoyne, @justinlittman, or @aaron-collier would be able to speak more concretely to that concern, i think.

**Comment by andrewjbtw** [comment]
@jmartin-sul can this be closed? We use sidekiq now for Argo bulk actions. Does this ticket cover any other background jobs?

**Comment by jmartin-sul** [comment]
@andrewjbtw i think this is done, closing!
