### ISSUE TITLE
consolidate deployment scripts for load balanced instances to single script for whole instance

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#817]
currently, the cap deploy scripts for prod and stage require a separate invocation for each host in the load balanced instance, i.e. there are scripts for both prod-a and prod-b, as well as stage-a and stage-b.

IIRC, this is due to some buggy interaction between capistrano and squash, possibly squash's deployment reporting?  i can't remember exactly at this point.  we stumbled on the issue during one of the dry runs for the argo 3 release.  since it felt like crunch time, the easiest thing in the moment was just to use separate deploy scripts for each host.

but this is inconvenient, and we'd like to fix the issue.  even if this is a problem with squash for which we can't figure out a workaround, we're planning to switch to honeybadger as an error reporting tool for argo, which we'd expect/hope would not replicate the squash bug.  so this might be an easy fix once honeybadger is in place.

**Comment by atz** [comment]
@jmartin-sul: Closing this since it no longer seems to be true. (Both `a` and `b` are referenced in the same `prod.rb` deploy script.)

**Comment by jmartin-sul** [comment]
@atz ah yeah, this got fixed a while ago, thanks!
