### ISSUE TITLE
Remove "none" as an option for "Metadata Source" dropdown on registration form

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#819]
I'm not sure what the purpose of this is, but we always want "auto" at this point so that at least MODS will be generated from the registration label.

@LynnMcRae - am I missing a reason we would want to register an object without a descMD stream?

**Comment by LynnMcRae** [comment]
I think the option was there for any source that supplies the descMetadata during assembly ... like converted Rumsey data, and maybe it was (or still is?) easier to supply a missing data stream than to override a stub one? Not sure that makes sense these days.

**Comment by blalbrit** [comment]
I don't think that makes much sense anymore (except for maybe Revs, but maybe not even there @peetucket ?). Given spreadsheet upload, and the fact that registering with "none" as staff often do, leads to an additional remediation effort just to get the content accessioned.

**Comment by peetucket** [comment]
What happens when you make that choice?  Revs registers during pre-assembly so would be unaffected.  If you pre-registered and then used pre-assembly, I think you can still specify the MD source in the pre-assembly config.

**Comment by LynnMcRae** [comment]
I think one consequence is tied in with our sorry handling of Fedora label and "object label" as a stand-in for a descMetadata supplied title when that datastream is missing, which I'm guessing is one reason Ben would like to see that option go away.

**Comment by blalbrit** [comment]
Right - currently what happens is that no stub descMD gets created and the registration label does not get subbed in for mods:title. The object gets to the descriptive-metadata step in accessioning and fails (since that step is checking for the datastream). We then have to go back in and remediate the object - creating a stub descMD stream with the label as title - in order for it to complete accessioning.

I've only ever seen descMD=none chosen in error, no one has ever done this deliberately as far as I can tell, so I want to remove the choice on the registration page.
