### ISSUE TITLE
update shared_configs, settings.yml

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#820]
In the process of setting up okcomputer a number of settings came into question.

Probably/possibly defunct:
- ~~DPG_URL  (possibly not yet used, rather than defunct?)~~ removed 2017-09-19
- ~~MDTOOLKIT_URL~~ removed 2017-09-19
- CONTENT.SDR_SERVER_URL
- ~~STATUS_INDEXER_URL~~ it's used?
- ~~METADATA.EXIST_URL ??~~. gone.

There seems to be some duplication between the CONTENT section and the STACKS section.

Another note:
- STACKS_URL  seems to be used for thumbnails for display (?)

**Comment by ndushay** [comment]
Is this anything we need to keep?  STACKS.DOCUMENT_CACHE_HOST

**Comment by mejackreed** [comment]
I think these are mostly dor-services configs that were just brought over en masse when we consolidated configuration approach. (for historical context)

**Comment by ndushay** [comment]
I've dealt with most of these.  Closing
