### ISSUE TITLE
Move MODS/Bulk upload from APO based action to global Bulk Action

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#822]
Confining upload actions to an APO, though it provided a shared APO-level history, proved to be less useful than a consolidated history of a person's actions via Bulk Actions. We'd also like to eliminate this as the odd man out in our bulk services.  Moving this will require:
- UI changes of course ... dropping the "MODS bulk loads" button from the APO view and adding the service to Bulk Actions
- Eliminating the APO check currently in the service and supporting the (shared?) APO-based permissions check per druid.
- Converting/moving the current file-system (or DB?) based artifacts to join them with the Bulk Actions history.
- Explore adding an informational line to the event history as a means to share the actions of others for any given object?

**Comment by andrewjbtw** [comment]
Will need to generate new tickets for each part of this if it fits into the 2020 maintenance work cycle scope.

**Comment by andrewjbtw** [comment]
The new Cocina-based spreadsheet works through the bulk actions and will eventually replace the old MODS-based spreadsheet entirely.
