### ISSUE TITLE
Argo reports use Windows CRLF on download

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#83]
This applies to the "Download" button at the bottom of a Report View. For example on this page:
https://argo.stanford.edu/report?controller=catalog&f%5Bwf_wps_facet%5D%5B%5D=swIndexWF

Generally transparent when viewing the data, but scripted processes can fail unless converted to unix linefeeds. They should be vanilla unix-LF instead?

**Comment by drh-stanford** [comment]
this should be fixed now.
