### ISSUE TITLE
Bulk MD Upload - logging & status broken

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#833]
The MODS Upload Page status & logs appear to be broken. Formerly successful runs are now showing 0 success, status = "system error" and logs are borked. This is particularly relevant to https://argo.stanford.edu/catalog/druid:kz949yf0754/bulk_jobs_index - but may extend to other APOs as well.

![screenshot 2016-10-11 09 07 32](https://cloud.githubusercontent.com/assets/796990/19278524/61ce5016-8f92-11e6-82f8-020ab5b99f27.png)
![screenshot 2016-10-11 09 05 59](https://cloud.githubusercontent.com/assets/796990/19278535/66af551c-8f92-11e6-89ab-f30458d22c40.png)

**Comment by blalbrit** [comment]
Reported by user:

For SHPC, the bulk MODS loads from 11:43 am on 9/29 on show 0 success, system errors status, and a nearly empty log, none of which were the case when the loads originally ran (I have local spreadsheets with the original log info) – and the timestamp for the load has the same time of day but a couple of days after the load actually ran.
 
From what is in the log, it looks like it’s pointing to the wrong location for the log info?
 
Best,
Arcadia

**Comment by tingulfsen** [comment]
I think the jobs are being re-run automatically a couple of days later, based on what I'm seeing in the server directories. Maybe there's a misconfiguration somewhere?

**Comment by tingulfsen** [comment]
So to expand a little - I think the workaround for the moment is for users to download the results and save them as soon as possible after the job is complete. Unfortunately we can't rely on the results being easily accessible through the Argo UI until this bug is fixed.

That being said, it looks like the converted XML files etc still reside on the server and could potentially be manually retrieved from there in exceptional cases.

**Comment by blalbrit** [comment]
Thanks for this analysis @tingulfsen . We'll add this to a future Argo sprint as a "must have" as currently tagged. I appreciate the time you took to sleuth the problem.

**Comment by hannahfrost** [comment]
@arcadiafalcone Do you know if this bug still exists in Argo?

**Comment by arcadiafalcone** [comment]
@hannahfrost It doesn't appear to be still happening, so far as I can tell.
