### ISSUE TITLE
The "Change Source ID" button should let you set the source ID if it's missing

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#84]
... but this situation currently gets you an error on submit

**Comment by mejackreed** [comment]
Started digging into this. What is happening (only on deployed apps):

1. `enforce_versioning` before filter is executed and returns false.

This only should return true if the object is in a state that allows it to be modified. States that will allow modification are:
 - has not been submitted for accessioning
 - has an open version
 - has sdr-ingest set to hold

Or should return true if
 - object workflows include: [`accession2WF`,  `accessionWF`]
 - `sdr-ingest-transfer` is `"hold"`

@LynnMcRae Are there some objects where these conditions should be true?

**Comment by mejackreed** [comment]
@LynnMcRae Also is this logic false? Should it be changed to something else?

**Comment by LynnMcRae** [comment]
There should be a common modifiable check in DOR Services that is based on status/lifecycle for all the buttons. The first two conditions are accurate (basically status "registered" or "open", though the way the first bullet above says it would include any v1 "Unknown status").   The condition should not be based on any WF by name, and we need to remove the 'sdr-ingest-transfer is "hold"' exception if that still exists (both it and accession2WF are artifacts that dealt with a particular problem a few years back).
