### ISSUE TITLE
Encoded newline characters disappear when editing XML

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#85]
Data entered into long text fields in our metadata, e.g., MODS notes or abstract, is treated as unformatted text. This means it will ignore whitespace (essentially by presenting it as html), including linefeeds in the data. Desired linefeeds must be encoded in the data as a `&#x10;` or `&#xA;`. When these are added to XML edited in Argo (when editing a datastream), they get translated as linefeeds in the resulting XML, that is ... 

   `<note>paragraph1&#xA;&#xA;paragraph2</note>`

becomes 

```
<note>paragraph1 

paragraph2</note>
```

and disappear if updated again.

Other encoded characters seem to be preserved, e.g., `&gt;` or `&amp;`

Newline encoding can be either `&#xA;` or `&#10;`

**Comment by atz** [comment]
I don't think this came through entirely.  Please identify the expected encoded linefeeds again using markdown syntax, i.e. backticks like:
```
`encoded thing`
```
Or give a more descriptive attribution.

**Comment by LynnMcRae** [comment]
Sorry for the multiple updates.  It needed a combination of backticks for the encoded characters and escaped \<note> tags to properly show how it displays.

**Comment by drh-stanford** [comment]
The FoXML does not have the `&#xA;` entities in it. They are getting stripped at some point...

![screen shot 2015-12-17 at 3 38 50 pm](https://cloud.githubusercontent.com/assets/1861171/11885179/501178fc-a4d4-11e5-97b8-185352ce0d8e.png)

**Comment by drh-stanford** [comment]
It looks like ActiveFedora is not taking the content verbatim when it saves it to Fedora. Instead it calls `Nokogiri::XML::Document.parse(new_content).to_s`. So it not preserve the linefeeds.

https://github.com/projecthydra/active_fedora/blob/v6.7.3/lib/active_fedora/om_datastream.rb#L110

```
[4] pry(main)> doc = Nokogiri::XML.parse('<speak>Hello&#xA;World</speak>')
=> #(Document:0x3ff1e2acc0c4 { name = "document", children = [ #(Element:0x3ff1e27f94f0 { name = "speak", children = [ #(Text "Hello\nWorld")] })] })
[5] pry(main)> doc.to_s
=> "<?xml version=\"1.0\"?>\n<speak>Hello\nWorld</speak>\n"
[6] pry(main)> 
```

So this is an issue with ActiveFedora.

**Comment by drh-stanford** [comment]
@LynnMcRae I've made the changes on our end to fix this problem in #395, but unless we debug and patch ActiveFedora, I don't think we'd be able to fix this problem. We're on a old (2013) ActiveFedora release -- 6.7.3 whereas 9.7.0 is the current.

@atz what's your thoughts on trying to debug, patch, and cut a new 6.7.x release of ActiveFedora. I'm not sure whether we'd need to upgrade to 6.7.8 (the latest) first -- cut in mid-2014 -- https://github.com/projecthydra/active_fedora/releases/tag/v6.7.8. We're also on rubydora 1.6.5 which is old (2013).

**Comment by drh-stanford** [comment]
I logged an issue with ActiveFedora (#962) to see what they say about preserving whitespace entities.

**Comment by drh-stanford** [comment]
They say it's a problem at the Nokogiri level and marked wontfix.

**Comment by drh-stanford** [comment]
@LynnMcRae can you be more specific about the data entry for these fields? Is this happening in Argo, or elsewhere?

**Comment by mejackreed** [comment]
Going to put this off until later

**Comment by drh-stanford** [comment]
is this still a +1? i'm not sure there's anything we can do here without addressing the data entry process
