### ISSUE TITLE
Enable bulk edit of resource labels

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#853]
Hi,

I'd like to request a new feature for Argo: bulk upload capability for display tag remediation.

With the current tools, we have to create display tags manually, which is labor-intensive.  It would be ideal to make the process more efficient so that we can continue to create useful, detailed metadata for our scholarly audience.  

My use-case is our collection of atlases in the SDR.  When you view a purl for an atlas the image display tags read simply as Image 1, Image 2, etc., unless we add our own custom-designed tags, such as abbreviated titles.  Inserting these titles requires copying and pasting one at a time in the contentMetadata in a record in Argo.  

Can this be done in a faster smoother way?

Thanks!

Best,

Emily
(___)
Emily Prince, Map Cataloger

**Comment by andrewjbtw** [comment]
Definitely still needed, but potentially complex because of the way resources and objects can be structured. I'm tagging this for a future look at resource label editing altogether.

**Comment by peetucket** [comment]
Not needed if we can update structural metadata
