### ISSUE TITLE
Add "Searchworks" link when an item is released to Searchworks

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#859]
We have a series of related links in the upper left of the detail display -- to PURL, FoXML, SOLR. It would be nice to have Searchworks there  as well.  The link would be be there only if the current released-to-searchworks status was true (per facet value). It would be based on catkey if present, else druid.

**Comment by andrewjbtw** [comment]
Closing in favor of https://github.com/sul-dlss/argo/issues/1974 as there is now a spot for a SearchWorks link in Argo, but the request to have the link display when an item is released remains active. Current behavior seems to be to display the link if there is a catkey.
