### ISSUE TITLE
Add Blacklight's number-of-item-per-results-page choice feature

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#86]
With choices 10, 20, 50, 100 per SW? Currently Argo defaults to 10 with no choices. SW defaults to 20. Do we want to up the Argo default to match?

**Comment by mejackreed** [comment]
Does this solve a problem that users report?

**Comment by LynnMcRae** [comment]
Ben originated the request so will know more. It's more a convenience for sure; I included in our first set of tickets with the thought it might be a built-in blacklight feature we could just expose (or not hide).

**Comment by blalbrit** [comment]
When examining many of our larger collections, the time spent paging through 10-objects at a time (given Argo's responsiveness or lack thereof) can be highly problematic and inefficient. This solves a user-facing problem that has been chronic since we started putting collections > 10 into DOR.

**Comment by mejackreed** [comment]
I can definitely understand that need. Though my concern is that this may actually decrease page load speed by adding more objects. @atz @jmartin-sul do the index views make calls to Dor?

**Comment by blalbrit** [comment]
yep - if default remained at 10, but we had the option to load more, that would satisfy the need

**Comment by LynnMcRae** [comment]
I trust John will confirm, but like Searchworks, the results page is generated solely from solr. Only the detail page and obvious things like forms reference the DOR object directly.

**Comment by jmartin-sul** [comment]
i'm pretty sure lynn is correct there, though not 100% positive without looking at the code and doing a bit of testing.  can investigate if/when we do this.
