### ISSUE TITLE
Release controls in Argo can overlap release workflows

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#861]
There should only be one active instance of a workflow for a druid ... instantiating more than one confuses robots and prerequisites and archiving and creates a mess. Apparently this restriction is not baked into the workflow services themselves. The Add Workflow button uses a method in Argo that checks this:

https://github.com/sul-dlss/argo/blob/dd5d9d70d91b8504dc4052b37779bf6e1f6d2cef/app/controllers/items_controller.rb#L633-L642

Release needs to check this as well and not do more than one releaseWF at a time.

**Comment by mejackreed** [comment]
When you say "release needs to check this" do you mean the release bulk action?

If so, how can we prevent this from happening in the future? Can we make changes to robots, or something from within dor-services app that knows about wf state?

**Comment by hannahfrost** [comment]
@justinlittman @jcoyne Is it possible that this old bug has been resolved with the new workflow service?

**Comment by justinlittman** [comment]
@hannahfrost With the current workflow service, when a new instance of a wf is created an existing instance is for that version is deleted.

Based on this, I'm going to close but feel free to re-open if you disagree.
