### ISSUE TITLE
[argo/production] NoMethodError: undefined method `new_object?' for #<Dor::Item:0x...>

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#863]
## Backtrace

    line 66 of [PROJECT_ROOT]/app/controllers/items_controller.rb: prepare

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49894/faults/31639800)

**Comment by blalbrit** [comment]
This is currently breaking some bulk & individual update functionality associated with versioning
