### ISSUE TITLE
Argo indexes collections as "collection" and "set" for Hydrus collections

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#877]
example https://argo.stanford.edu/view/druid:kq696sh3014

This has only one object type declared in identityMetadata -- collection -- and only one model -- afmodel:Hydrus_Collection.  But the objectType field in the index adds "set", which then gets displayed, showing values for objectType not actually in the record. The indexing logic apparently only does this for Hydrus collections, not DOR collections (e.g., https://argo.stanford.edu/catalog/druid:bb810ym7436).  This is an error.  The index should reflect the actual object declarations only.

**Comment by cbeer** [comment]
I see two `objectType` values in that specific record (comments for syntax highlighting purposes here.):

```xml
<identityMetadata>
<!--  <sourceId source="Hydrus">collection-hfrost-2013-01-31T20:34:02.368Z</sourceId>
  <objectId>druid:kq696sh3014</objectId>
  <objectCreator>DOR</objectCreator>
  <objectLabel>History of Media Preservation in Research Libraries</objectLabel> -->
  <objectType>collection</objectType>
<!--  <adminPolicy>druid:rz646cy2429</adminPolicy>
  <otherId name="uuid">8c8d78ec-6be5-11e2-a045-0050569b3c6e</otherId>
  <tag>Project : Hydrus</tag> -->
  <objectType>set</objectType>
<!--  <tag>Remediated By : 3.24.3</tag> -->
</identityMetadata>
```

**Comment by LynnMcRae** [comment]
well I'm blind, or just didn't look for instances of the tag separated in the XML. I've checked a handful of other Hydrus collections to confirm that is a consistent pattern.
