### ISSUE TITLE
Collection drop-down no longer functional on registration page

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#882]
Per stakeholder feedback (and confirmed), the collection drop-down on the item registration page in Argo has become non-functional (perhaps as of Thursday/Friday last week). I have tested across multiple APOs and am seeing the same behavior for all of them.

"Hi all,

I'm having some trouble with the registration module this morning.  I'm trying to register some items for the Rumsey collection, but the collection object won't appear in the dropdown menu (see attached screenshot).   Usually, if I wait a little bit or refresh the page I can get it to show up, but I've tried that a few times and it doesn't seem to be working this morning.  Please advise

Thank you!

Meagan"
![thumbnail_registration_collection_dropdown_not_working](https://cloud.githubusercontent.com/assets/796990/20274607/0c937da6-aa4a-11e6-9d1c-ea09ca04139e.jpg)

**Comment by cbeer** [comment]
Fixed in https://github.com/sul-dlss/shared_configs/commit/abca74a8e1810db5da86177416b077597a0af5d2.
