### ISSUE TITLE
Add 'no-download' clause to any location based rightsMD updates

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/argo#884]
Location = spec and location = music (along with any future locations) should have a 'no-download' option just like the 'World' and 'Stanford' selections. Both the bulk update screen and the registration screen should be updated. 

Geoff

**Comment by blalbrit** [comment]
To clarify a bit further, what is required is:

On https://argo.stanford.edu/items/register , please add:

- Location spec (no-download) and
- Location music (no-download) to
![screenshot 2016-11-15 09 58 25](https://cloud.githubusercontent.com/assets/796990/20317300/4be9034c-ab1a-11e6-8106-7fd135302469.png)

and do the same for the blue button "Set object rights" in the bulk update screen and *also* (not stated above) for the blue button "Set rights" on the individual item view.

@LynnMcRae can you add to the spec that all future locations will require the same treatment?

**Comment by andrewjbtw** [comment]
@oceanofsound @blalbrit Is this still an active need? I'm expecting the answer to be yes, but since the ticket is over three years old I want to make sure that this hasn't been addressed in another way, such as preventing downloads via the configuration of the authorized computers rather than from the Stacks restrictions.

**Comment by oceanofsound** [comment]
Yes, this would still be nice to have. All the ARS and SPEC reading room material really should be switched to 'no-download,' and right now that's not easy to do. I can't speak to the authorized computers (other than my own) though - I'm not sure if they prevent downloads in some way.

**Comment by andrewjbtw** [comment]
This is now covered by the new rights menu.
