### ISSUE TITLE
Bulk Update: "Get druids from search" does not work when using one of the Empty Fields facets

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#887]
Example Query:

https://argo.stanford.edu/view?f%5Bempties%5D%5B%5D=no_object_title&f%5Bprocessing_status_text_ssi%5D%5B%5D=Unknown+Status&f%5Brights_descriptions_ssim%5D%5B%5D=dark

Go to Bulk Update

Choose "Get druids from search"

Nothing happens.

**Comment by mejackreed** [comment]
This part of the code is extremely fragile and untested. I recommend porting the actions over to the new bulk actions framework or at least using the new `populate_druids` approach.

```
<a class='btn btn-primary' data-populate-druids="<%= catalog_index_path(search_of_pids(@last_search)) %>" data-target='#pids'>
  Populate with previous search
</a>
```

**Comment by hannahfrost** [comment]
Just tested this and it is no longer a bug.
