### ISSUE TITLE
relocate all Solr queries to a single class

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/argo#895]
we have a variety of techniques for issuing Solr queries and they are spread throughout the codebase. it would help to have an `Argo::SearchService` class where we could at a minimum keep them to help reduce confusion.

here's some examples:

- https://github.com/sul-dlss/argo/blob/master/app/helpers/apo_helper.rb#L35
- https://github.com/sul-dlss/argo/blob/master/app/helpers/registration_helper.rb#L10
- https://github.com/sul-dlss/argo/blob/master/lib/tasks/argo.rake#L7
- https://github.com/sul-dlss/argo/blob/master/lib/pid_gatherer.rb#L51
- and more...

**Comment by jcoyne** [comment]
Agreed, but this seems more like a good design goal rather than something that should be a ticket.
