### ISSUE TITLE
Include Hydrus declared DOR roles in Argo permissions logic

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#909]
There are three kinds of roles defined:
- system level roles, e.g., sdr-administrator
- DOR-flavored roles intended for DOR-APO managed roles in Argo
   - their names start with "dor-"
   - e.g., dor-apo-manager
- Hydrus-flavored roles intended for use by Hydrus-APO declared roles
   - their names start with "hydrus-"
   - e.g., hydrus-apo-manager

When interpreting roles, the Hydrus app only pays attention to roles declared in Hydrus-APOs. In a logical symmetry, Argo only pays attention to roles (apart from system-level roles) declared in DOR-APOs, that is, only those with a RELS-EXT declaration of Dor::AdminPolicyObject (see https://github.com/sul-dlss/argo/blob/ac6483915e12ca0cfe4735ca8bab907d962e97c7/app/models/ability.rb). 

Unfortunately, this means that a DOR-flavored role declared in Hydrus will not have the desired effect of enabling access to related materials in Argo. This is a critical issue now that library-curated materials are being deposited in Hydrus that require parallel Argo access for curators, metadata unit, etc. Think EEMs transition for one.

The work suggested is that  Argo respond to the kind of roles only, rather than the source of the roles. This includes real-time permissions (including Impersonate) as well as the information passed to the .htaccess file for initial app access.

**Comment by LynnMcRae** [comment]
Information from earlier JIRA ticket https://jirasul.stanford.edu/jira/browse/ARGO-412:

Hydrus items are only accessing in Argo to DOR Admins. In a few cases, we would like to grant vewing access in Argo to individual SUL staff who are not DOR Admins. Adding them in roleMetadata does not seem to work, and we don't understand why.
This ticket addresses the world to figure out what is preventing an individual added to the APO from seeing the collection and its items in Argo.

Here is an APO whose roleMetadata has been modified along the lines we think should work:
https://argo.stanford.edu/catalog/druid:sn206hs6490

**Comment by LynnMcRae** [comment]
Related ticket #909

**Comment by jcoyne** [comment]
@andrewjbtw can we close this since Hydrus has been effectively decommissioned?

**Comment by andrewjbtw** [comment]
No longer relevant.

**Comment by andrewjbtw** [comment]
NB: There is permissions work to be done related to the Hydrus Ur-APO but I think that can be via workgroups and the still-existent Hydrus Ur-APO.
