### ISSUE TITLE
Bulk Action: Paste in Druid List - Allow for both druid-prefixed and non-druid-prefixed lists

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#912]
Currently pasting in druid:cz887nd5476 works, but pasting in cz887nd5476 does not. All bulk update paste-ins allow both prefixed and non-prefixed druids - this should be the same.

**Comment by mjgiarlo** [comment]
@andrewjbtw I tried the "Download Descriptive Metadata" bulk action on both `druid:bq653yd1233` and `bq653yd1233` and they both worked. Can you verify that this work is still needed? Or maybe I'm not reproducing it correctly.

**Comment by andrewjbtw** [comment]
I think this may have been addressed while working on virtual objects. I have not tested with every bulk action type but the ones I've tested have not required the druid prefix.
