### ISSUE TITLE
Alternate approach to Argo front door access

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#919]
We currently maintain a .htaccess file for the Argo app in near realtime that represents all workgroups currently references as roles across all APOs. It's kinda clunky and hacky and messy in that it's constantly updating the production server environment – but it works.

Alternate:  explore workgroup API described at

   http://www.programmableweb.com/api/stanford-university-workgroup
   https://web.stanford.edu/dept/as/mais/applications/workgroupapi/api.html

to maintain a single "sdr:argo-access" workgroup instead of the .htaccess file. A single workgroup could be statically referenced in the .htaccess file; it would no longer have to be constantly updated.

**Comment by LynnMcRae** [comment]
Workgroup API documentation now at https://uit.stanford.edu/developers/apis/workgroup

**Comment by blalbrit** [comment]
I believe this has been superseded by work done to migrate to shib.
