### ISSUE TITLE
Source IDs entered with extraneous spaces

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#920]
If you enter a source ID on the Item Registration page with space around the colon separating the source name from value, you get extraneous spaces in the value,e.g., 

https://argo.stanford.edu/view/druid:xt646hg1011
   <identityMetadata>
       <sourceId source="sul "> SC0340_1991-030_CMU</sourceId>

The trailing space in the "source" attribute and the leading space in the value should be stripped.

**Comment by hannahfrost** [comment]
@blalbrit I haven't tested this to know if it remains a bug. But do you know if this is currently a nuisance for our users?

**Comment by blalbrit** [comment]
@hannahfrost - I _think_ this was mostly solved by discouraging the practice of intentionally putting spaces around the colon. I'm not sure there was anything done in the code. I haven't had a complaint about this in a while, but most people aren't searching or sorting on sourceID as far as I know.
