### ISSUE TITLE
Support exclusion facets

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#921]
This is an enhancement that has broad potential value across faceted queries, so our hope is that it might emerge in Blacklight so that Argo could simply take advantage of it. This ticket is to record our interest in such a feature.

Use case – sometime multiple data values overlap across records. Normal facets allow you to find those items in a category with a value, but not those that lack a value. Example, for the Object Type facet:

   Object Type
     collection (586) [X]
     set (406)

Since every collection should be a set, but not every set will be a collection, the second number should be higher than the first. It would be useful to be able to exclude the 406 to find which ones are missing the "set" relationship. Even the simpler case of, say, excluding object-type=collection or content-type=book after a keyword search would be valuable.

The facility would be potentially useful in any facet that is multi-valued in source records.

from https://jirasul.stanford.edu/jira/browse/ARGO-320

**Comment by andrewjbtw** [comment]
This would be extremely useful for data remediation and there are also known use cases for regular work.

Example:

Find all items in a given collection/APO that have _not_ been released to Searchworks.

Users currently perform this search by:

1. Exporting a report of all items in the facet
2. Exporting a report of all items in the face that have been released to Searchworks.
3. Diffing the two reports

For certain types of material (i.e. ETDs) the reports are so large it can take multiple attempts to download them. It would be much more time-effective for everyone to be able to do this within Argo.

**Comment by andrewjbtw** [comment]
Questions:

1. Could we pick the top exclusions requested?
2. Are there Blacklight examples with exclusions already implemented.

**Comment by ndushay** [comment]
Here is the design https://projects.invisionapp.com/share/B813BT2Q9MRH#/screens/474829031_exclude

**Comment by andrewjbtw** [comment]
Closing in favor of https://github.com/sul-dlss/argo/issues/4222
