### ISSUE TITLE
Prevent (or warn) if duplicate collection object is being created

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#927]
Problem: We don't currently check for uniqueness when registering a collection object from a catkey
Desired solution: Warning (or prevention) that a duplicate collection is being created
Description (from Doris):

Also, could there be an alert if one person tries to create a collection that already exists? Astrid just mentioned to me (she's reading over my shoulder) that she and Geoff have done this before, it's come up for me as well.

**Comment by blalbrit** [comment]
Additional suggestion from @arcadiafalcone : "The collection name display should include the collection druid for disambiguation purposes"

This might allow for preventing duplication as well.

**Comment by justinlittman** [comment]
Some additional details from @arcadiafalcone:

An identifier is:
> The identifier for a marc record in the symphony ils. corresponds to the unique part of the record url in searchworks. "registering from a catkey" means that a) the description from the marc record is converted to mods to create the descMetadata and b) the purl for the digital object gets inserted into the marc record so that it will display on that record page in searchworks (and the derived mods record will not appear in searchworks)

How to create a collection: https://consul.stanford.edu/display/DLSSDOCS/Argo+-+How+to+create+and+apply+a+collection+object
