### ISSUE TITLE
Support independent setting/editing/remediation of rights-related declaration

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#928]
Currently we allow the Visibility parts of rightsMetadata (\<access type="discover | read">)to be reset (blue button, bulk), or we can do a wholesale refresh of rightsMetadata from the APO defaults.  What we lack is independent facilities for these four rights-related declarations:

- **Copyright** (\<copyright>)
- **License**  (\<use>\<machine type="creativeCommons | openDataCommons">)
- **Use and Reproduction** (\<use>\<human type="useAndReproduction">)
- **Restrictions on Access**  (\<use>\<human type="restrictionOnAccess">)(new) 

[note there are variations in spelling/casing/etc for "useAndReproduction" and "restrictionOnAccess"]

We need support for editing or remediating (bulk) each statement separately. We also need support for APO based defaults that support choices of applicable statements to avoid an artificial and undesirable split of APOs for collections just to get alternative statements like Use and Reproduction.

**Comment by LynnMcRae** [comment]
Subsumes https://jirasul.stanford.edu/jira/browse/ARGO-195 about reconciling the labeling of rights-related features

**Comment by andrewjbtw** [comment]
This is relevant to ongoing discussions of use cases where users directly edit XML.

**Comment by jcoyne** [comment]
@andrewjbtw will this be resolved by #2629

**Comment by andrewjbtw** [comment]
Not entirely. We still need the per-object ability to edit these without going through rightsMetadata XML editing: https://github.com/sul-dlss/argo/issues/2444 https://github.com/sul-dlss/argo/issues/2443

**Comment by jcoyne** [comment]
@andrewjbtw I'm going to close this ticket as the tickets you referenced are going to be the relevant fixes.
