### ISSUE TITLE
Allow targeted bulk updates on single-valued MODS fields that repeat across objects

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#931]
For example - update language across collection or sub-set of a collection.

**Comment by blalbrit** [comment]
Question - are there use-cases for this that are not being satisfied by spreadsheet upload. If there are - is another solution allowing targeted column replacements within spreadsheet.

**Comment by blalbrit** [comment]
Export/import is the other possible path for this. Export selected MODS fields and then import replacements.

**Comment by arcadiafalcone** [comment]
A possible use case - uploading initial metadata via replayable spreadsheet, then later updating names or subject headings with authorized terms and corresponding attributes (authority, authorityURI, valueURI) after authority work has been done.

**Comment by andrewjbtw** [comment]
Closing this as we are no longer on MODS. We could open a subsequent ticket for updating Cocina fields if we determine that's a feature we should build.
