### ISSUE TITLE
Allow addition of specific MODS fields in bulk (or individual)

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#932]
Per Arcadia, an increasing use-case is the following:

After metadata has been created for a set of objects, it is discovered that additional fields are desired or required for those objects. It would be desirable to be able to just insert those MODS elements into the existing records rather than exporting the MD, modifying the XML, and re-uploading.

**Comment by andrewjbtw** [comment]
Closing this because we're no longer on MODS but we could open a subsequent ticket referring to Cocina.
