### ISSUE TITLE
Add new locations to Argo rights pulldown menus

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#934]
Add new locations to Access Rights pulldown menus. The new locations are:

- ars
- art
- hoover
- m&m

Making them available as a choice can preceede their actual implementations, handled separately. The list of current and upcoming locations can be found at https://consul.stanford.edu/display/chimera/Rights+Metadata+Locations

The choices are defined here ... https://github.com/sul-dlss/dor-services/blob/6f5b2a590c4189f6a5400446f18714ee73f62102/lib/dor/datastreams/rights_metadata_ds.rb#L54-L63

and processed generically here ... https://github.com/sul-dlss/dor-services/blob/6f5b2a590c4189f6a5400446f18714ee73f62102/lib/dor/datastreams/rights_metadata_ds.rb#L109-L112

**Comment by LynnMcRae** [comment]
Based on code references above, this belongs in dor-services instead? No actual Argo code changes?
