### ISSUE TITLE
Get replayable spreadsheets ready for load balancing

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/argo#94]
We would like to load balance Argo. Currently, the replayable spreadsheets/bulk metadata upload functionality uses a regular directory to save its work and inputs. Investigate and implement necessary changes for this to work with a load balanced Argo (i.e. running on more than one server).

**Comment by tingulfsen** [comment]
I just spoke to Erin about this, and we've decided to just have all the production servers talk to the same NFS mount. In theory, it should just work...

**Comment by LynnMcRae** [comment]
Think could help open up the possibility of saving information about bulk updates in general. Nothing to think about now, just mentioning a future possibility while I had the thought.

**Comment by tingulfsen** [comment]
I am closing this issue for now. The various servers for stage and dev have been set up with shared directories that should work fine. Let's reopen the issue later if we have problems.
