### ISSUE TITLE
Update code references for MODS from 3.4 to 3.6

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#942]
This ticket refers only to those places where we generate the MODS header that currently looks like this

<mods:mods xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-4.xsd" version="3.4">

The two references to "3.4" just need to change to 3.6.  The places we know need looking at are:
- When an object is first registered, an initial descMetadata datastream is created with stub MODS just for the title. 
- Modsulator creates MODS from a spreadsheet

Both ideally get the needed document header from one place, perhaps 
https://github.com/sul-dlss/mods/blob/master/lib/mods/constants.rb#L3

Note that there is code to call a versioned XSLT for the MARC to MODS conversion. This should be left at 3.4 until a 3.6 XSLT is installed.

**Comment by jmartin-sul** [comment]
FWIW, dor-services actually appeared to be using MODS 3.3.  see sul-dlss/dor-services#313

**Comment by jmartin-sul** [comment]
will prob also want to fix this?  
```ruby
@xsd ||= Nokogiri::XML::Schema(File.read(File.expand_path(File.dirname(__FILE__) + '/xml/mods-3-4.xsd')))
```
https://github.com/sul-dlss/argo/blob/master/app/helpers/items_helper.rb#L9
