### ISSUE TITLE
Getting a working index on argo-stage against dor-test

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#95]
Potential for pursuing improvements that @lmcglohon saw with commitWithin

**Comment by jmartin-sul** [comment]
elaborated by #194 and #195

**Comment by drh-stanford** [comment]
@jmartin-sul can we close this one now?

**Comment by jmartin-sul** [comment]
@drh-stanford: yup, we can close this.  #195 also, i think.  #194 should probably stay open till the indexing improvements get merged back from their topic branch.
