### ISSUE TITLE
Encoded character display issue in Argo web page titles

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#959]
See https://argo.stanford.edu/view/druid:mr163sv5231, where an encoded ampersand in the web page title becomes "\&amp;amp;" instead of "&".
![screen shot 2017-03-22 at 1 02 00 pm](https://cloud.githubusercontent.com/assets/1824732/24218271/cbf68854-0eff-11e7-8b8b-c593f36ba777.png)

**Comment by aaron-collier** [comment]
No longer valid.

**Comment by jcoyne** [comment]
This is still a problem: https://argo.stanford.edu/view/druid:mr163sv5231

**Comment by aaron-collier** [comment]
Ah, same as before. I was looking at the title on the page, not the tab... Need more ☕

**Comment by andrewjbtw** [comment]
Possibly fixed in Blacklight 7.
