### ISSUE TITLE
Set background job priorities to start at 1 not 0

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/argo#964]

**Comment by jmartin-sul** [comment]
this was filed based on behavior i remember observing a while back, but it seemed to me that the `delayed_job` machinery uses priority `0` to indicate jobs that it is currently executing (i.e., it seemed that a job would get its priority set to `0` when execution started).  we currently use `0` as our highest priority (relative priority decreases as priority number increases).  we should probably default to `1` as our highest priority, and number up from there for lower priority jobs.

like i said, old observation, might not hurt to re-test and/or find documentation or source code that supports this observation before making changes based on it.
