### ISSUE TITLE
Blue buttons that are disabled based on available object info end up hitting a URL that 404s

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/argo#968]
in some places, `check_url` (as defined in some of the button hashes returned by `ArgoHelper#render_buttons` for use by `_button_link_list.html.erb` and `button_checker.js`) isn't a URL, but a boolean.  the result is that the `check_url` field can also act as a disabled flag for occasions where the decision to enable the button or not can be made using info already available from the object, as opposed to needing to reach out to e.g. workflow service.

https://github.com/sul-dlss/argo/blob/master/app/helpers/argo_helper.rb#L87
```ruby
buttons << {
  url: set_governing_apo_ui_item_path(id: pid),
  label: 'Set governing APO',
  check_url: !object.allows_modification?
}
```

with the boolean usage, if `check_url` is `false`, the button is enabled, because whether the button is disabled on page load is determined by (https://github.com/sul-dlss/argo/blob/master/app/views/items/_button_link_list.html.erb#L15):
```ruby
link_to button[:label], button[:url], class: "btn button btn-primary #{'disabled' if button[:check_url]}", data: button_data
```

and no request is made, because `check_url` is only added to `button_data` if it's truthy (https://github.com/sul-dlss/argo/blob/master/app/views/items/_button_link_list.html.erb#L11-L13):
```ruby
if button[:check_url]
  button_data[:check_url] = button[:check_url]
end
```

if, `check_url` is `true`, the button is disabled, the value for `check_url` is added to `button_data`, and the javascript that makes the remote call to enable the button will try the URL `true` (and of course get a 404; https://github.com/sul-dlss/argo/blob/master/app/assets/javascripts/modules/button_checker.js#L25):
```javascript
$('a.disabled[data-check-url]').buttonChecker();
```

since the response is a 404, the button never gets enabled, and nothing misleading happens in the UI.  but there's an unnecessary network request and 404, and the code's a little confusing.  not a big deal at all, and not a bug functionally, just a bit of a rough edge that i stumbled across.  feels worth sanding down if time allows.  i was thinking something like the addition of a simple `disabled` flag field at the same level as the `check_url` field in the button hash.  then change the `link_to` in the template to do `#{'disabled' if (button[:check_url] || button[:disabled])}`.  then swap the non-URL uses of the `check_url` field to use the `disabled` flag instead, and add a test for the new flag (in _button_link_list.html.erb_spec.rb, i think).

FWIW, i totally perpetuated this usage with the "Set governing APO" button (PR #958, didn't get to fixing this thing as part of that).

**Comment by mejackreed** [comment]
Can you say more about this?
