### ISSUE TITLE
Make DOR Workflow Services log be configurable.

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/argo#97]
Currently, the log file for DOR workflow services is written straight into the Argo main directory. Change so that the location can be configured, and store the file in the log/ directory by default.

**Comment by tingulfsen** [comment]
Pull requests are in for DOR Services to configure this.

**Comment by atz** [comment]
DOR PR's are merged.

**Comment by mejackreed** [comment]
@tingulfsen is this still in progress?

**Comment by atz** [comment]
`config/settings.yml` has
```
DOR_SERVICES_LOGFILE: 'log/workflow_service.log'
```
But the file still gets created in root dir with just the auto-header line:
```
# Logfile created on 2015-11-10 18:52:49 -0800 by logger.rb/1.2.8
```

So there may be an issue with timing the configuration before Dor invokes DWFS with the default config.

**Comment by atz** [comment]
@mejackreed: note, sorta janky name for the setting since this is really a dor-workflow-service specific logfile and dor-services has plenty of other logs it should be generating.

**Comment by drh-stanford** [comment]
i agree re: naming since it's a `workflow` service setting in `Dor.configure`. See here: https://github.com/sul-dlss/argo/blob/develop/config/environments/dor_development.rb#L18

Maybe `Settings.WORKFLOW_LOGFILE`, etc. to match `Settings.WORKFLOW_URL`.

**Comment by drh-stanford** [comment]
See PR #185 for the renaming issue

**Comment by mejackreed** [comment]
Is this still valid?
