### ISSUE TITLE
Background Release job too successful

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#972]
A Release job for 6900 objects already has 10697 successes suggesting some replay or resubmission? a counting issue?  It may still be out there running. 

![pastedimage](https://cloud.githubusercontent.com/assets/1824732/24673008/9c4a9bc8-192b-11e7-953b-265e235dbb22.png)

**Comment by tingulfsen** [comment]
@jmartin-sul and I have been investigating this, and we think that this particular job was restarted after partially completing. It was first run at Mon, 27 Mar 2017 15:45:17 UTC +00:00 and ultimately stopped abruptly at Tue, 28 Mar 2017 10:07:09 UTC +00:00.

We think the success count was simply incremented by each successive run of the job, leading to a success count greater than the total number of processed druids. This would imply that some druids ran multiple times.

It's tricky to correlate the Delayed Job framework's logs with our own application logs, so this is based on circumstantial evidence - but we have seen at least one job fail and get restarted during the relevant time interval.

Is it dangerous to re-run the release operation for any druid?

**Comment by LynnMcRae** [comment]
"Is it dangerous to re-run the release operation for any druid?"

Nope, no problem. The sw-indexer will just reindex the same stuff again.
