### ISSUE TITLE
Changing rights to "dark" should also prune the stacks dir for the object

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#977]
Like when decommissioning an object, a change to "dark" should remove the content from stacks.

In the decommission process, we use: 
Dor::DigitalStacksService.prune_stacks_dir 'druid:ng000nd5495'

@LynnMcRae - I'm labeling this a bug b/c I don't think there was an intention to keep the shelved material when changing to "dark" (though a change to "citation only" should). If you had a specific reason to keep the shelved material for "dark" objects, let me know.

**Comment by LynnMcRae** [comment]
the specs say "unpublish and unshelve" (https://consul.stanford.edu/display/chimera/Decommissioning+DOR+objects).

We do allow the shelving of files that themselves are not published, e.g., an unpublished OCR file in a resource with a published image might be used for text mining. It's worth asking again if we should allow any shelving of files from dark objects. Google scanned books was the canonical use case for this when we were saving the texts for mining without making PURLs for them, but we aren't doing that any more. If a future need comes up, we might support it though an explicit access level that isn't "discover"?   Another option is to have decommission change any shelve=yes to shelve=no, or have shelving and publish cognizant of a decommissioned state as a factor in their processing.  I like that they go explicitly "dark" however.

**Comment by blalbrit** [comment]
I would prefer "dark" to mean "dark" - with no accessible content, even thumbnails. We now have "citation only" which could be used when we want to shelve but not publish content.

**Comment by LynnMcRae** [comment]
I think it also means that public stacks per se is should not be the destination for materials "shelved" for internal use. The google scanned books were shelved into a separate partition that stacks.stanford.edu did not know about, the locked stacks as it were. Note however that the definition of access=discover is that it controls the publication of the purl or not, not the disposition of materials in the stacks, so by today's rules decommission should change shelve=yes to shelve=no. I like hardening the definition of dark (discover/none) and supporting internal shelving for future cases if needed in some explicit rights-aware way, like a new access type.

**Comment by tingulfsen** [comment]
Per @blalbrit - there are two ways of changing the rights: Use the blue button ("Set rights") or set rights via bulk update. The desire is for any stacks content to be deleted when the rights are set to dark.
