### ISSUE TITLE
Manage Catkey is not trimming leading/trailing spaces from input

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#981]
Recording them as part of the value has bad consequences for downstream processes that use the value to link records, e.g., SW understanding digital collection membership in released collections. 

Example in stage:
![screen shot 2017-04-21 at 4 16 25 pm](https://cloud.githubusercontent.com/assets/1824732/25298842/ed9b797c-26ad-11e7-9716-c64223bce7aa.png)

**Comment by LynnMcRae** [comment]
as shown, "same value" rules should of course apply to the trimmed value.

**Comment by ndushay** [comment]
here is a way to find druids for records of ckeys with a single trailing space: 
- https://sul-solr.stanford.edu/solr/argo3_prod/select?fq=catkey_id_ssim:*\%20*&fl=id,catkey_id_ssim&facet=false&spellcheck=false

I think this is a way to find ckeys starting with whitespace, but it only found one and it appears to be blank:
- https://sul-solr.stanford.edu/solr/argo3_prod/select?q=catkey_id_ssim:/\%20*/&fl=id,catkey_id_ssim&facet=false&spellcheck=false
