### ISSUE TITLE
Add blue button and bulk action for "Related Catkey"

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#985]
In the new paradigm to support serials in SearchWorks, a "related catkey" element has been added to identityMetadata.

This story would allow a user to add related catkeys to individual objects, or to a list of objects produced either by a search or a pasted druid list.

The desired action would be to:

1. add related catkey to identityMD if missing
2. change or delete existing related catkey as needed

Normal prepare/close version process should handle the republish process.

This would be an action that requires versioning.

@LynnMcRae - anything else to add?

**Comment by andrewjbtw** [comment]
This doesn't seem to be the direction that serials work has gone since 2017. Serials items use "regular" catkeys.
