### ISSUE TITLE
Bulk "Update governing APO" seems to fail after 600-700 objects

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#990]
Per recent conversation on SLACK, Josh Schneider (@joshschneider) from UArchives pointed out a problem in the "Update governing APO" functionality which is that for large jobs (13K+), the update job fails after ~600 objects, and then reruns those ~600 objects several more times before the process dies.

I have tested on batches of 600, which complete with no error, and on batches of 1000, which fail with the same problem as above. Historically, we have submitted batches over 1000 which have succeeded - it is unclear if the problem we're seeing is caused by certain content, or by some change in the system.

@jmartin-sul and @jcoyne have tracked the conversation on SLACK with some suggestions and troubleshooting and are aware of the issue.

This is primarily an analysis ticket, which might spawn a technical ticket(s) for a fix. @jmartin-sul suggested a small update to batch large jobs up front, which would be transparent to the user.

Any input from anyone is welcome here, since this is a bit of a mysterious failure. @LynnMcRae has agreed that this could be worked in the upcoming functional debt mini-sprint.

Anyone with better knowledge is welcome to comment or edit to better characterize this problem.

**Comment by hannahfrost** [comment]
@joshschneider Do you know if this bug still occurs? Can you update governing APO for more than ~600 objects?

**Comment by joshschneider** [comment]
@hannahfrost Since "update governing APO" is now a bulk action, I think it's ok to close this issue. In any case I haven't experienced issues recently; neither have Daniel or Laura.

**Comment by hannahfrost** [comment]
@joshschneider Great, that's what I suspected. Thanks for your help.
