### ISSUE TITLE
Provide a "not released" status in the Released To facet (and as a column in report view)

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#993]
Perhaps there is some facet combination that I am not thinking of but how can we determine what is ready/needs to be released (i.e. to Searchworks)? For example, it would be helpful to have other options under Released To, namely 'not released' to determine what still needs to be released.

Thanks,

Daniel Hartwig
University Archivist
dhartwig@stanford.edu
650-725-1161

**Comment by ndushay** [comment]
In Solr parlance, we have to set `facet.missing=true` for the new fields.

**Comment by ndushay** [comment]
@jcoyne did you already do this in your Argo PR?  If so, please close this.

**Comment by andrewjbtw** [comment]
This issue also mentions the "report view" but I can split that out into its own separate ticket.

**Comment by jcoyne** [comment]
I did this in the ticket for the "Released to Searchworks" facet, but this ticket is for the "Released to" facet, which is untouched.

**Comment by ndushay** [comment]
I'm closing this ticket;  the "Released to" facet is supposed to be removed.  I will make a separate ticket for that.
