### ISSUE TITLE
Analysis: locations in code where we're still pulling from dc fields

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#994]
Per @ndushay - it would be good to do an analysis and assessment of places in our code in Argo, dor-services, and dor-services-app to see where we're still drawing from DC instead of MODS or other appropriate data.

- [ ] argo
- [ ] dor-services
- [ ] dor-services-app

- [ ] DLSS consumers of purl public-xml

Prompted by https://github.com/sul-dlss/argo/issues/910 but appropriate as a code-review / code-cleanup.

**Comment by blalbrit** [comment]
@ndushay - please feel free to comment further.

**Comment by jcoyne** [comment]
There are no locations where we are using DC as a source.
